ets-berkeley-edu/junction

.travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-4652
This is a simpler and more efficient approach to keep our Travis-CI runs working.
=> CLC-4652 Simpler workaround to Travis-CI / RVM JRuby issue

app/assets/templates/canvas_embedded/roster.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4608
Fixes call to print page in api utility service.
See #3221
=> CLC-4608 - Fixed api service call to print page

LICENSE
https://jira.ets.berkeley.edu/jira/browse/CLC-4664
=> CLC-4664 - Update license to 2015

app/models/bearfacts/proxy.rb, app/models/finaid/Proxy.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/3232
=> QA CLC-4659 Header-based authentication for apis.berkeley.edu feeds

app/assets/templates/textbook.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4671
=> CLC-4671 - Textbooks: bookstore purchase link triggers browser encryption security warning

app/controllers/canvas_rosters_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4679
If this tests OK on bCourses-beta, I'll make a QA PR.
=> CLC-4679 Fix Roster export on Safari

app/controllers/canvas_rosters_controller.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/3238
=> QA CLC-4679 Fix Roster export on Safari

app/controllers/bootstrap_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4699
=> CLC-4699 Redirect to /404 for invalid file types

public/canvas/canvas-skin.css
https://jira.ets.berkeley.edu/jira/browse/CLC-4655
Adjusted alt-media box to align with newer design.
=> CLC-4655 - Alt media: Alt media box isn't aligned with the files panel

app/models/berkeley/term.rb, app/models/calendar/queries.rb, config/settings.yml, spec/models/berkeley/term_spec.rb, spec/models/calendar/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4645
=> CLC-4645 Class calendar integration should automatically handle semester change

app/assets/stylesheets/_canvas_course_provision.scss, app/assets/templates/canvas_embedded/course_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4708
Adds .cc-page-provision-admin-mode-switch, .cc-page-provision-term-button-element, and .cc-page-provision-term-button classes,
alphabetizes class definitions in _canvas_course_provision.scss
=> CLC-4708 - Course Provisioning: Make term buttons consistent size

app/models/calendar/exporter.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4728
=> CLC-4728 Check if we have a response.body before converting it to JSON

app/models/canvas/proxy.rb, app/models/canvas/terms.rb, config/settings.yml, fixtures/pretty_vcr_recordings/Canvas_terms.json, spec/models/canvas/proxy_spec.rb, spec/models/canvas/terms_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4644
=> CLC-4644 Handle undefined future bCourses terms

app/models/canvas/proxy.rb, spec/models/canvas/proxy_spec.rb, spec/models/canvas/repair_sections_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-3903
=> CLC-3903 Reverse order of elements from Canvas::Proxy::canvas_current_terms

app/assets/stylesheets/_canvas_course_provision.scss, app/assets/templates/canvas_embedded/course_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4709
=> CLC-4709 - Course Provisioning: Change form header text for selected sections

app/assets/templates/canvas_embedded/canvas_course_sections_form.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4712
=> CLC-4712 - Course Provisioning: Update course boxes to show course title and number of sections

app/models/canvas/provide_course_site.rb, spec/models/canvas/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4707
=> CLC-4707 - Course Provisioning: Update form to select current term by default

public/canvas/canvas-skin.css
https://jira.ets.berkeley.edu/jira/browse/CLC-4655
=> CLC-4655 - One pixel adjustment to left padding

app/assets/javascripts/angular/directives/datePickerDirective.js, app/assets/stylesheets/_datepicker.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-4565
=> CLC-4565 - Android Chrome - clicking arrows on date-picker widget causes widget to vanish

app/assets/stylesheets/_canvas_embedded.scss, app/assets/templates/canvas_embedded/canvas_course_sections_form.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4715
=> CLC-4715 - Course Provisioning: Add section date/time(s), location(s), and instructor(s)

app/assets/templates/canvas_embedded/canvas_course_sections_form.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4715
=> CLC-4715 - Remove typo equal sign character

app/assets/javascripts/angular/controllers/pages/canvasCourseProvisionController.js, app/assets/templates/canvas_embedded/canvas_course_sections_form.html, app/assets/templates/canvas_embedded/course_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4716
* Adds new updateSelected method called when section selected, updating list in $scope.selectedSectionsList. This assembled list shared with other methods, such as selectedCcns().
* Uses ng-disabled to disable 'Next >>' button until $scope.selectedSectionsList is no longer of zero length
=> CLC-4716 - Course Provisioning: Disable 'Next' button until at least one section selected

app/controllers/sessions_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4736
=> CLC-4736 - CAS: Using the redirection on logout feature

app/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js, app/assets/stylesheets/_canvas_embedded.scss, app/assets/templates/canvas_embedded/canvas_course_sections_form.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4717
=> CLC-4717 - Course Provisioning: Make each course box expandable, collapsed by default

app/assets/stylesheets/_canvas_course_add_user.scss, app/assets/stylesheets/_canvas_course_provision.scss, app/assets/stylesheets/_canvas_embedded.scss, app/assets/templates/canvas_embedded/course_add_user.html, app/assets/templates/canvas_embedded/course_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4711
=> Course Provisioning: Add expandable help text for selection of rosters

app/assets/javascripts/angular/controllers/pages/canvasCourseProvisionController.js, app/assets/javascripts/angular/services/canvasCourseProvisionService.js, app/assets/templates/canvas_embedded/canvas_course_sections_form.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4716
=> CLC-4716 - Fix issue with 'Next' button disabled even after using Select All / None toggle links

app/models/my_academics/telebears.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4658
=> CLC-4658 Log UID associated with unknown Tele-BEARS adviser code

app/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js, app/assets/stylesheets/_canvas_embedded.scss, app/assets/templates/canvas_embedded/canvas_course_sections_form.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4744
=> CLC-4744 - Course Provisioning: Post-Demo Fixes

app/assets/templates/canvas_embedded/roster_photo.html
Thanks for the catch on https://github.com/ets-berkeley-edu/calcentral/pull/3281 @christianv - it must have regressed when I moved it to its own template.
=> CLC-4639 Fix alt tag in roster photos

app/assets/javascripts/angular/services/utilService.js, public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4696
=> CLC-4696 Resize large LTI frames to avoid dual scroll bars

script/export-cached-csv-enrollments-set.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-4754
=> CLC-4754 Give our bCourses enrollments fetcher some much needed memory

app/assets/javascripts/angular/controllers/pages/rosterController.js, app/assets/stylesheets/_canvas_roster.scss, app/assets/templates/canvas_embedded/roster.html, app/models/canvas/canvas_rosters.rb, app/models/rosters/campus.rb, spec/controllers/canvas_rosters_controller_spec.rb, spec/models/canvas/canvas_rosters_spec.rb, spec/models/rosters/campus_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4719
=> CLC-4719 - Roster Print: Add header

app/assets/templates/canvas_embedded/course_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4680
=> CLC-4680 - Fix typo

app/models/canvas/terms.rb, fixtures/pretty_vcr_recordings/Canvas_terms.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4762
We've passed the magic count of ten.
Once this goes in, I'll ready a QA PR.
=> CLC-4762 Paginate Canvas Terms API

app/models/canvas/terms.rb, fixtures/pretty_vcr_recordings/Canvas_terms.json
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/3296
The change tests fine on beta/dev.
=> QA CLC-4762 Paginate Canvas Terms API

app/models/oec/biology_post_processor.rb, lib/tasks/oec.rake
https://jira.ets.berkeley.edu/jira/browse/OEC-530
biology_post_processor will:
1. read data from biology.csv
2. sort data to INTEGBI and MCELLBI CSVs based on Justin's reqts
3. delete original biology CSV file
4. rewrite the CSV files for data sets w/ length > 0
The oec:students rake task must not fail when biology.csv is not found.
=> OEC-530, Primary script: oec:courses generated a BIOLOGY file

app/models/canvas/canvas_rosters.rb, app/models/rosters/campus.rb, app/models/rosters/common.rb, spec/models/canvas/canvas_rosters_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/common_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4739
=> CLC-4739 - Roster Export: Add section information to the roster csv export

app/models/oec/courses.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-540
We have unofficial cross-listings (e.g., room shares where cross_listed_flag is null) showing up in our OEC data. We will include those CCNs as long as the dept is participating in OEC.  This change will cause 11 CCNs to be omitted from the set of OEC CSV files.
=> OEC-540, omit x-listings where x_listed_flag is null and dept is not participating in OEC

app/controllers/canvas_controller.rb, app/models/campus_oracle/user_attributes.rb, app/models/canvas/public_authorizer.rb, app/policies/authentication_state_policy.rb, config/routes.rb, public/canvas/canvas-customization.js, spec/controllers/canvas_controller_spec.rb, spec/models/campus_oracle/user_attributes_spec.rb, spec/models/canvas/public_authorizer_spec.rb, spec/policies/authentication_state_policy_spec.rb, spec/support/shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4776
=> CLC-4776 - Site Provisioning: Update API for course creation to support any site creation

app/controllers/bootstrap_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4813
=> CLC-4813 - Going to /dashboard and refreshing breaks calcentral-dev

src/assets/javascripts/angular/configuration/securityConfiguration.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4814
=> CLC-4814 - 401 when creating a task

spec/ui_selenium/my_dashboard_google_up_next_spec.rb, spec/ui_selenium/pages/my_finances_details_page.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4810
Bugs fixed:
* Comparison using the wrong date format
* Comparison using strings instead of dates
=> CLC-4810: fix date comparisons in Selenium tests

src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/canvasCreateProjectSiteController.js, src/assets/stylesheets/_canvas_create_project_site.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/canvas_embedded/create_project_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4779
=> CLC-4779 - Site Provisioning: Create a 'Create a Project Site' tool context

app/models/bearfacts/proxy.rb, app/models/bearfacts/regblocks.rb, app/models/my_academics/academics_module.rb, app/models/my_academics/college_and_level.rb, app/models/my_academics/exams.rb, app/models/my_academics/requirements.rb, app/models/my_academics/telebears.rb, spec/models/bearfacts/exams_spec.rb, spec/models/bearfacts/profile_spec.rb, spec/models/bearfacts/regblocks_spec.rb, spec/models/bearfacts/schedule_spec.rb, spec/models/bearfacts/telebears_spec.rb, spec/models/my_academics/college_and_level_spec.rb, spec/models/my_academics/requirements_spec.rb, spec/models/my_academics/telebears_spec.rb, spec/support/proxy_shared_examples.rb
Part two of the unexpectedly expansive https://jira.ets.berkeley.edu/jira/browse/CLC-4663.
=> CLC-4663 Remove unnecessary parsing from Bearfacts API clients

app/models/oec/courses.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-550
Now primary and secondary cross-listings get equal treatment: Omit a cross-listing if its cross_listed_flag is null and department is not participating in OEC.
=> OEC-550, secondary cross-listings should not include non-OEC dept where cross_listed_flag is null

src/assets/javascripts/angular/directives/disabledLinkDirective.js, src/assets/stylesheets/_disabled_links.scss, src/assets/stylesheets/calcentral.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-4825
=> CLC-4825 - Create a disabledLinkDirective

src/assets/javascripts/angular/directives/disabledLinkDirective.js, src/assets/stylesheets/_disabled_links.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-4825
https://jira.ets.berkeley.edu/jira/browse/CLC-4827
=> CLC-4825 - Follow-up - https://github.com/ets-berkeley-edu/calcentral/pull/3338

app/models/oec/courses.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-560
Simple enough.
=> OEC-560, logger statements changed from warn to info

src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4823
=> CLC-4823 - Converted label to use cc-visuallyhidden instead of style with display:none

src/assets/javascripts/angular/directives/dateValidatorDirective.js
CLC-4812 - My Finances transactions: date validation error persists when date filters are gone
https://jira.ets.berkeley.edu/jira/browse/CLC-4812
=> CLC-4812 Date Validation Error no longer persists on Cars Activity page

src/assets/templates/cars_activity.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4830
* Add table scopes
* Show `search` instead of `go` or `return` when you're in the search text box on iOS. Thanks @nicolaasmatthijs
* Add labels
=> CLC-4830 - CFV - Improve the accessibility on the search details page

src/assets/javascripts/angular/directives/spinnerDirective.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4831
=> CLC-4831 - Set aria-busy on the spinner

src/assets/javascripts/angular/controllers/widgets/taskEditorController.js, src/assets/javascripts/angular/services/taskAdderService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4832
=> CLC-4832 - Unable to add an unscheduled task

src/assets/templates/cars_activity.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4830
=> CLC-4830 - Follow up - add live region

app/models/oec/courses.rb, app/models/oec/courses_diff.rb, lib/tasks/oec.rake, spec/models/oec/courses_diff_spec.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-561
Includes:
1. log level tweaks
2. def diff_found? on CoursesDiff
3. mo' better messaging in oec.rake
=> OEC-561, diff task: log proper message when no diff found

spec/models/canvas/site_creation_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4778
=> CLC-4778 - Strengthen specifications

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4833
The existing code seems nicely set-up for a one-liner.
=> CLC-4833 Disable E-Grades export during Canvas transition to new design

app/models/cal1card/my_cal1card.rb, app/models/cal_link/memberships.rb, app/models/cal_link/organization.rb, app/models/mediacasts/all_playlists.rb, app/models/mediacasts/audio.rb
Last mop-up on https://jira.ets.berkeley.edu/jira/browse/CLC-4663.
=> CLC-4663 Remove unnecessary parsing from last few proxies

src/assets/templates/academics_student_profile.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4811
=> CLC-4811 - Empty Academics "Profile" card for concurrent enrollments

app/models/oec/courses_diff.rb, app/models/oec/queries.rb, lib/tasks/oec.rake, spec/models/oec/courses_diff_spec.rb, spec/models/oec/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-556
See 'rake oec:diff' section of [OEC manual](https://docs.google.com/a/berkeley.edu/document/d/1MAZN5TA39fpRD5zRrUOqafHI1FEKcyqVHnCufpARblw/edit#heading=h.hkx6y2ahi39s) to understand how the optional 'departments' arg can be used.
=> OEC-566, rake diff task: Allow for multiple file inputs

src/assets/templates/academics_student_profile.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4844
UL elements can't live inside P elements.
=> CLC-4844 Fix HTML for Concurrent Enrollment message

app/controllers/canvas_project_provision_controller.rb, app/models/canvas/course.rb, app/models/canvas/course_add_user.rb, app/models/canvas/course_enrollments.rb, app/models/canvas/project_provision.rb, config/routes.rb, config/settings.yml, spec/controllers/canvas_project_provision_controller_spec.rb, spec/models/canvas/course_add_user_spec.rb, spec/models/canvas/course_enrollments_spec.rb, spec/models/canvas/course_spec.rb, spec/models/canvas/project_provision_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js, src/assets/javascripts/angular/controllers/pages/canvasCreateProjectSiteController.js, src/assets/javascripts/angular/controllers/pages/canvasSiteCreationController.js, src/assets/javascripts/angular/factories/canvasProjectProvisionFactory.js, src/assets/javascripts/angular/services/canvasSiteCreationService.js, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/stylesheets/_canvas_create_project_site.scss, src/assets/stylesheets/_canvas_embedded.scss, src/assets/stylesheets/_canvas_emulated.scss, src/assets/stylesheets/_canvas_shared.scss, src/assets/stylesheets/_canvas_site_creation.scss, src/assets/templates/canvas_embedded/_shared/canvas_feed_error.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/create_project_site.html, src/assets/templates/canvas_embedded/site_creation.html
Also included is code for CLC-4782 - Implement Project site creation processing
https://jira.ets.berkeley.edu/jira/browse/CLC-4781
https://jira.ets.berkeley.edu/jira/browse/CLC-4782
=> CLC-4781 - Implement 'Create a Project Site' form

src/assets/javascripts/angular/controllers/pages/canvasCreateProjectSiteController.js, src/assets/templates/canvas_embedded/create_project_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4824
Adds hidden alert area for screen reader in Create a Project Site tool
=> CLC-4824 - Site Provisioning: Review Web Accessibility

app/models/canvas/provide_course_site.rb, spec/models/canvas/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4849
=> CLC-4849 Provide course codes when provisioning by CCN

src/assets/javascripts/angular/controllers/pages/canvasCreateProjectSiteController.js, src/assets/javascripts/angular/controllers/pages/canvasSiteCreationController.js, src/assets/stylesheets/_canvas_site_creation.scss, src/assets/templates/canvas_embedded/create_project_site.html, src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4852
=> CLC-4852 - Site Provisioning: Resolve iframe size / scrollbar display issue

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4854
=> CLC-4854 - Site Overview: Display the user navigation 'Create a Site' option when user is faculty/staff

.travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-4857
=> CLC-4857 - Travis: use Container-Based Infrastructure and set Git depth

app/models/canvas/course_add_user.rb, spec/models/canvas/course_add_user_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4782
=> CLC-4782 - Remove SIS User Import from 'Create a Project Site' processing

app/models/canvas/course_add_user.rb, app/models/canvas/course_user.rb, spec/models/canvas/course_add_user_spec.rb, spec/models/canvas/course_user_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4859
=> CLC-4859 - Project sites: non-admin site owner cannot use "find a person to add" tool

app/models/canvas/course_add_user.rb, app/models/canvas/course_user.rb, spec/models/canvas/course_add_user_spec.rb, spec/models/canvas/course_user_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4859
For Master PR see #3381
=> [QA] CLC-4859 - Project sites: non-admin site owner cannot use "find a person to add" tool

src/assets/templates/academics_classinfo.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4860
=> CLC-4860 Add hyphen to "Cross-listed"

app/models/bearfacts/proxy.rb, app/models/finaid/proxy.rb, spec/models/finaid/proxy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4865
QA version of #3384.
=> [QA] CLC-4865 Fix verbose ERROR logging on student ID lookup failure

app/models/my_academics/academics_module.rb, spec/models/my_academics/teaching_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4875
=> CLC-4875 Restore MyAcademics feed data expected by Webcasts widget

src/assets/templates/academics_classinfo.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4878
=> CLC-4878 Fix missing breadcrumb in course info

app/models/my_academics/academics_module.rb, spec/models/my_academics/teaching_spec.rb
=> [QA] CLC-4875 Restore MyAcademics feed data expected by Webcasts widget

src/assets/templates/academics_classinfo.html
=> [QA] CLC-4878 Fix missing breadcrumb in course info

src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4778
See #3398 for QA PR
=> CLC-4778 - Updated Site Overview index text for course and project site options

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4867
=> CLC-4867 - Update gulp dependencies

src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4778
See #3397 for Dev PR
=> [QA] CLC-4778 - Updated Site Overview index text for course and project site options

src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4778
@christianv merged changes in #3397 before I was able to add the second grammatical error fixes introduced in QA via #3398. This PR seeks to ensure that those changes continue in the Dev branch.
=> CLC-4778 - Fix gramatical errors

public/canvas/canvas-customization.js, public/canvas/canvas-skin.css
https://jira.ets.berkeley.edu/jira/browse/CLC-4673
=> CLC-4673 - Converted span to button with link styling for improved accessibility

src/assets/templates/academics_classinfo.html
=> [QA] CLC-4860 Add hyphen to "Cross-listed"

app/models/my_academics/academics_module.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4883
=> CLC-4883 Translate additional instruction formats

app/models/my_academics/academics_module.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4883
QA version of #3402.
=> [QA] CLC-4883 Translate additional instruction formats

public/canvas/canvas-customization.js, public/canvas/canvas-skin.css
https://jira.ets.berkeley.edu/jira/browse/CLC-4673
See Dev PR in #3399
=> [QA] CLC-4673 - Converted span to button with link styling for improved accessibility

app/models/oec/dept_confirmed_data.rb, lib/tasks/oec.rake
https://jira.ets.berkeley.edu/jira/browse/OEC-571
=> OEC-571, Diff task not respecting 'departments' arg

app/models/my_classes/campus.rb, spec/models/my_classes/campus_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4900
=> CLC-4900 Fix duplicate IDs for multiple primary sections

app/models/my_classes/campus.rb, spec/models/my_classes/campus_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4900
QA version of #3408.
=> [QA] CLC-4900 Fix duplicate IDs for multiple primary sections

app/controllers/stored_users_controller.rb, app/models/user/data.rb, app/models/user/recent_uid.rb, app/models/user/saved_uid.rb, app/models/user/search_users_by_uid.rb, app/models/user/stored_users.rb, config/routes.rb, db/migrate/20150212155014_create_stored_uid_tables.rb, db/migrate/20150212165014_add_stored_uid_table_indexes_and_rename.rb, db/schema.rb, public/dummy/json/stored_users.json, spec/controllers/stored_users_controller_spec.rb, spec/models/user/search_users_by_uid_spec.rb, spec/models/user/search_users_spec.rb, spec/models/user/stored_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4773
=> CLC-4773 - Store "View As" user data in the back-end

app/models/canvas/course_provision.rb, spec/models/canvas/course_provision_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4884
=> CLC-4884 - Add-Delete: Add Preferred Course Ordering in Feed

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4929
https://github.com/angular/angular.js/blob/master/CHANGELOG.md
=> CLC-4929 - Upgrade Angular to 1.3.14

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4930
https://github.com/FortAwesome/Font-Awesome/issues?q=milestone%3A4.3.0+is%3Aclosed
=> CLC-4930 - Update fontawesome to v4.3.0

.jscsrc, package.json, public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4931
=> CLC-4931 - Update JSCS & JSHint

app/models/berkeley/user_roles.rb, app/models/campus_oracle/queries.rb, app/models/campus_oracle/user_attributes.rb, app/models/canvas/csv.rb, spec/models/campus_oracle/queries_spec.rb, spec/models/campus_oracle/user_attributes_spec.rb, spec/models/canvas/maintain_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4906
Also cleared out some unused and repeated code.
=> CLC-4906 bCourses should use student ID for concurrent enrollment

app/models/canvas/egrades.rb, public/canvas/canvas-customization.js, spec/models/canvas/egrades_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4826
@redconfetti , mind taking a look at this one?
=> CLC-4826 Restore E-Grades export; fix terms check

app/models/my_activities/reg_blocks.rb, spec/models/my_activities/reg_blocks_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4890
=> CLC-4890 MyActivities: correct key for regblocks source

app/models/my_classes/classes_module.rb, app/models/my_groups/canvas.rb, app/models/my_groups/sakai.rb, spec/models/my_classes/canvas_spec.rb, spec/models/my_classes/sakai_classes_spec.rb, spec/models/my_groups/canvas_spec.rb, spec/models/my_groups/sakai_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4938
=> CLC-4938 Fix mismatched shortDescription keys in MyClasses and MyGroups

src/assets/templates/academics_classinfo.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4936
=> CLC-4936 Hide section label for sections with empty schedules

app/models/canvas/course_add_user.rb, spec/models/canvas/course_add_user_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4933
=> CLC-4933 Do not return expired affiliations from CourseAddUser search

app/controllers/tools_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4944
=> CLC-4944 - Color Style Reference is Missing

app/models/canvas/course_provision.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/stylesheets/_canvas_course_manage_official_sections.scss, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4877
=> CLC-4877 - Miscellaneous Fixes

app/models/canvas/provide_course_site.rb, spec/models/canvas/course_provision_spec.rb, spec/models/canvas/provide_course_site_spec.rb
Follow-up on https://jira.ets.berkeley.edu/jira/browse/CLC-4895
I exposed a few more instance variables in ProvideCourseSite to make it a _little_ more test-friendly...
=> CLC-4895 Add regression tests for Add-Delete Sections server-side

app/models/my_tasks/google_tasks.rb, config/initializers/timeshift.rb, fixtures/pretty_vcr_recordings/Google_tasks.json, spec/models/google_apps/google_task_lists_proxy_spec.rb, spec/models/my_tasks/my_tasks_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4934
=> CLC-4934 Account for daylight savings transitions in task due dates

app/models/berkeley/colleges.rb, spec/models/berkeley/colleges_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-2539
=> CLC-2539 Display 'GRAD DIV' from Bearfacts as L&S

src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/stylesheets/_canvas_embedded.scss, src/assets/stylesheets/_canvas_shared.scss, src/assets/templates/canvas_embedded/_shared/canvas_errors.html, src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/create_project_site.html, src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4899
=> CLC-4899 - Add-Delete: Implement minimized maintenance notice official course tools

src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4951
The Official Section editing state should be cleared when the user explicitly cancels.
=> CLC-4951 Clear section editing state on Cancel

src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4958
See QA PR in #3458
=> CLC-4958 - Add-Delete: Implement current design for Sections Available to Add

src/assets/stylesheets/ls_advising.scss, src/assets/templates/academics_ls_advising.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4960
=> CLC-4960 - Advising: advisor photo could use a better layout

src/assets/stylesheets/ls_advising.scss, src/assets/templates/academics_ls_advising.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4960
**Note**: QA version of #3459 - make sure that that gets merged & approved before merging this one.
=> CLC-4960 QA - Advising: advisor photo could use a better layout

src/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js, src/assets/templates/canvas_embedded/canvas_users_courses_form.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4958
=> CLC-4958 Integrate course code into Add-Delete and Course Provisioning

src/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js, src/assets/templates/canvas_embedded/canvas_users_courses_form.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4958
QA version of #3461.
=> [QA] CLC-4958 Integrate course code into Add-Delete and Course Provisioning

app/models/canvas/external_app_configurations.rb, config/settings.yml, config/settings/development.yml, spec/models/canvas/reconfigure_external_apps_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4968
After testing this on Dev, I'll make a QA PR.
=> CLC-4968 Feature-flag Official Sections tool

app/models/canvas/external_app_configurations.rb, config/settings.yml, config/settings/development.yml, spec/models/canvas/provide_course_site_spec.rb, spec/models/canvas/reconfigure_external_apps_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/3464
=> QA CLC-4968 Feature-flag Official Sections tool

spec/models/canvas/provide_course_site_spec.rb
Carried over from the unlucky QA PR #3464
=> CLC-4950 Fix some CCN-related timebombs in the tests

src/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4954
=> CLC-4954 Add-Delete: auto-expand courses with included sections

spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/my_dashboard_google_live_updates_spec.rb, spec/ui_selenium/my_dashboard_google_tasks_spec.rb, spec/ui_selenium/my_dashboard_google_up_next_spec.rb, spec/ui_selenium/my_finances_data_cal1card_spec.rb, spec/ui_selenium/my_finances_ui_details_page_spec.rb, spec/ui_selenium/my_finances_ui_landing_page_spec.rb, spec/ui_selenium/pages/api_my_academics_page.rb, spec/ui_selenium/pages/cal_central_pages.rb, spec/ui_selenium/pages/google_page.rb, spec/ui_selenium/pages/my_dashboard_up_next_card.rb, spec/ui_selenium/pages/my_finances_details_page.rb, spec/ui_selenium/pages/my_finances_landing_page.rb, spec/ui_selenium/user_authentication_spec.rb, spec/ui_selenium/user_google_connection_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4969
See JIRA ticket for detail on the issues addressed in this PR.  In summary they are:
* Reducing false test failures caused either by recent changes in the expected application behavior or by bugs in the Selenium code itself.
* Avoiding intermittent errors instantiating the browser and passing it to the rest of a given test.  This involves separating the browser instantiation into its own "before" hook, apart from other test setup code.  I'm not certain this will fix the errors, but it's worth a try.  The bulk of the noise in this PR comes from rearranging these hooks and consequently shifting the rest of the (unaltered) test code.
=> CLC-4969: misc Selenium test bug fixes

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4981
https://github.com/dbushell/Pikaday/blob/master/CHANGELOG.md
=> CLC-4981 - Update Front-end Dependencies: Pikaday

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4984
=> CLC-4984 - Update Front-end Dependencies: minimist & streamqueue

gulpfile.js, package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4982
=> CLC-4982 - Update Front-end Dependencies: gulp-concat, gulp-inject & gulp-minify-css

.gitignore, script/start-torquebox.sh
Longer explanation and background on the JIRA: https://jira.ets.berkeley.edu/jira/browse/CLC-4989
=> CLC-4989 Set alternate tmp directory to prevent FFI error starting Torquebox

script/start-torquebox.sh
My fix to https://jira.ets.berkeley.edu/jira/browse/CLC-4989 broke the master branch deployment. This should fix it.
=> CLC-4989 Fix error in reference to tmp dir

app/models/canvas/site_memberships_maintainer.rb, spec/models/canvas/site_memberships_maintainer_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4990
This is a critical production problem, and so I'll also be submitting a PR against our current QA branch (AKA v52).
=> CLC-4990 Fix Teacher/TA drops from sections with short CCNs

app/models/canvas/site_memberships_maintainer.rb, spec/models/canvas/site_memberships_maintainer_spec.rb
QA (emergency release) flavor of https://github.com/ets-berkeley-edu/calcentral/pull/3478
=> QA CLC-4990 Fix Teacher/TA drops from sections with short CCNs

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4983
=> CLC-4983 - Update Front-end Dependencies: jshint

src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-4966
=> CLC-4966 - Add-Delete: success message hangs around longer than it should

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-4985
=> CLC-4985 - Update Front-end Dependencies: moment

config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-4909
Also see: https://jira.ets.berkeley.edu/jira/browse/CLC-4919
This just documents what configuration the code will be looking for. Next up: the code!
=> CLC-4909 Initial configuration placeholder for new RegStatus API

src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/stylesheets/_canvas_shared.scss, src/assets/templates/canvas_embedded/_shared/canvas_errors.html, src/assets/templates/canvas_embedded/_shared/official_sections_table.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4961
=> CLC-4961 - Add-Delete 2: revise message when no existing sections in list

app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5001
=> CLC-5001 Include expected sections array in feed for transcript-only courses

config/initializers/webmock_allow_net_connect.rb, spec/spec_helper.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5006
=> CLC-5006 Allow HTTP connections to bypass WebMock in any environment

app/controllers/canvas_course_provision_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4949
Six lines of authorization code; two lines of mistakes. "You had ONE JOB..."
=> CLC-4949 Fix two blunders in Official Sections authz code

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/stylesheets/_academics.scss, src/assets/stylesheets/_profile.scss, src/assets/templates/academics_student_profile.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4882
https://jira.ets.berkeley.edu/jira/browse/CLC-4987
Front-end counterpart to #3490 and #3496.
=> CLC-4987 Show better registration data during term transitions

app/models/my_academics/gpa_units.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/templates/academics_student_profile.html
CLC-4868 - Include at least two significant digits in GPA
https://jira.ets.berkeley.edu/jira/browse/CLC-4868
There was multiple ways I wanted to approach the problem (filters in AngularJS, conversion to significant digits in js file) but the simplest way seemed to be to pass in a presentable value in Ruby. Feedback definitely needed for smarter ways
=> GPA has at least 2 Significant Digits

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5007
=> CLC-5007 - Update AngularJS to 1.3.15

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4912
=> CLC-4912 - Accessibility: As a screen reader user, I want the Export to e-grades tool to function with my screen reader

app/models/campus_oracle/connection.rb, app/models/campus_oracle/user_courses/base.rb, app/models/canvas/site_memberships_maintainer.rb, spec/models/canvas/site_memberships_maintainer_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4992
Removes workarounds from #3478.
=> CLC-4992 Zero-pad CCN strings from Oracle queries

config/routes.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4793
=> CLC-4793 Allow cache deletion API to accept keys in query strings

src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5016
=> CLC-5016 Add null/undefined checks to front-end academics parser

app/models/my_activities/canvas_activities.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-2247
=> CLC-2247 Refactor MyActivities::CanvasActivities

gulpfile.js, src/assets/javascripts/angular/controllers/pages/campusController.js, src/assets/javascripts/angular/services/updatedFeedsService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5021
=> CLC-5021 - Fix JSCS errors

app/models/my_tasks/canvas_tasks.rb, app/models/my_tasks/google_tasks.rb, app/models/my_tasks/tasks_module.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5023
=> CLC-5023 Parse tasks without times as Date instead of DateTime

src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4911
Misc fixes related to comments by @christianv in #3502
=> CLC-4911 - Misc Front-end fixes

app/models/my_badges/google_drive.rb, spec/models/my_badges/my_badges_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5026
=> CLC-5026 Update path for Google Drive badge icons

gulpfile.js, package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5029
=> CLC-5029 - Use official Raven.js npm repo & update to 1.1.18

src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5032
=> CLC-5032 Fix unresponsive link buttons in dashboard To Do

app/controllers/application_controller.rb, app/controllers/canvas_project_provision_controller.rb, spec/controllers/canvas_course_add_user_controller_spec.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/controllers/canvas_project_provision_controller_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCreateProjectSiteController.js, src/assets/templates/canvas_embedded/_shared/canvas_errors.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4873
=> CLC-4873 - Create a Project Site: Exceed max char limit and boom: "Unexpected Error"

src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5032
QA version of #3524.
=> [QA] CLC-5032 Fix unresponsive link buttons in dashboard To Do

spec/models/canvas/provide_course_site_spec.rb, spec/models/my_badges/student_info_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5039
=> CLC-5039 Intercept unnecessary calls to live Bearfacts in specs

app/models/canvas/course_sections.rb, app/models/canvas/provide_course_site.rb, app/models/canvas/site_memberships_maintainer.rb, spec/models/canvas/provide_course_site_spec.rb, spec/models/canvas/site_memberships_maintainer_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5037
I was hoping to get this into QA if it tests OK on Dev, but since @redconfetti should review and he's currently out of the office, chances are slim...
=> CLC-5037 Use all site sections (old and new) to determine instructor roles

app/models/my_tasks/google_tasks.rb, spec/models/my_tasks/my_tasks_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5042
QA version of #3532 .
=> [QA] CLC-5042 Do not display email links for Google tasks

app/models/oec/row_converter.rb, spec/models/oec/row_converter_spec.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-580
Includes:
1. Four fields validated per custom regex
2. Capture 'dept_form' data from row
3. A new spec
=> OEC-581, oec:diff should validate year, ccn, ldap and instructor_func

spec/ui_selenium/pages/api_my_academics_page.rb, spec/ui_selenium/pages/my_academics_tele_bears_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5044
=> CLC-5044: fix broken Tele-BEARS Selenium spec

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/templates/academics_semesters.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5043
=> CLC-5043 Revise card display for current transcript-only semesters

src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4869
=> CLC-4869 Correct help text in course site creation

app/models/oec/row_converter.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-581
Let's be tolerant of CCNs such as 09876
=> OEC-581, allow for CCNs with those damn leading zeroes

src/assets/javascripts/angular/controllers/widgets/lsAdvisingController.js
https://jira.berkeley.edu/browse/SISRP-2542
Review by @ctweney
=> SISRP-2542 - Create top navigation prototype to return to CalCentral

app/controllers/canvas_course_add_user_controller.rb, app/controllers/canvas_course_grade_export_controller.rb, config/routes.rb, spec/controllers/canvas_course_add_user_controller_spec.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/javascripts/angular/controllers/pages/canvasSharedFactory.js, src/assets/javascripts/angular/factories/canvasCourseAddUserFactory.js, src/assets/javascripts/angular/factories/canvasCourseGradeExportFactory.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4955
=> CLC-4955 - Update E-Grade Export tool to run in CalCentral Context

app/models/my_tasks/canvas_tasks.rb, app/models/my_tasks/google_tasks.rb, app/models/my_tasks/merged.rb, app/models/my_tasks/tasks_module.rb, spec/models/my_tasks/my_tasks_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-1484
=> CLC-1484 Symbolize keys in tasks feed

script/bamboo-tests.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-4748
This covers the automatic UI tests for master & production.
=> CLC-4748 Add UI test to bamboo-tests.sh capability

app/models/my_tasks/google_tasks.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5064
=> CLC-5064 - Unscheduled tasks have lost their "last modified" date

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5067
=> CLC-5067 - E-Grades Export: Move link in Gradebook to 'E-Grades' button

fixtures/pretty_vcr_recordings/Google_tasks.json, spec/models/my_tasks/my_tasks_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5064
Test coverage to follow up #3549.
=> CLC-5064 Add tests for unscheduled and completed Google tasks

src/assets/stylesheets/_classes.scss, src/assets/templates/widgets/my_classes.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4939
=> CLC-4939 Show short descriptions for course sites in My Classes

app/models/canvas/merged_user_sites.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5085
=> CLC-5085 Order course sites by name in Canvas::MergedUserSites

src/assets/stylesheets/_classes.scss, src/assets/templates/widgets/my_classes.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5087
=> CLC-5087 Vertically center icons in My Classes

spec/ui_selenium/pages/my_academics_class_page.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5089
=> CLC-5089: fix webcast UI test

src/assets/stylesheets/_academics.scss, src/assets/templates/academics_classinfo.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5086
=> CLC-5086 Show short descriptions for course sites on Course Info pages

src/assets/stylesheets/_buttons.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5090
=> CLC-5090 - Instructor class page: class info/roster buttons push webcast & textbook widgets down

README.md
I noticed this gap while prepping for CLC-5046...
=> NOJIRA Missing a new DB table in the "developer seed data" section

app/models/my_tasks/sis_tasks.rb
https://jira.berkeley.edu/browse/SISRP-2657
=> SISRP-2657 Skip over bogus checklist feed items

public/dummy/json/academics.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5114
=> CLC-5114 Modify dummy JSON for multiple primaries

app/models/berkeley/term_codes.rb, spec/models/berkeley/term_codes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5117
=> CLC-5117 Let My Academics cope with the old-school Winter quarter

src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/stylesheets/_canvas_shared.scss, src/assets/templates/canvas_embedded/_shared/sections_table.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4757
=> CLC-4757 Reserve pointer style for clickable items

app/controllers/config_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5104
Note that I'm trying this out on the SIS branch first to make sure it works before submitting to ets master.
=> CLC-5104 (SIS-master branch) Skipping reauth should help ConfigController not return 302s

.rvmrc, .travis.yml, Dockerfile, Gemfile, Gemfile.lock, README.md
https://jira.ets.berkeley.edu/jira/browse/CLC-5116
DO NOT MERGE until you ping me to be ready to handle changes on the Bamboo end immediately after merge.
=> CLC-5116 Upgrade Torquebox to 3.1.2 and JRuby to 1.7.19

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5121
=> CLC-5121 - Update front-end dependencies: gulp-angular-templatecache / gulp-rename / gulp-rev-all / gulp-uglify

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5122
=> CLC-5122 - Update front-end-dependencies: jscs, jshint & moment

app/controllers/canvas_course_grade_export_controller.rb, app/models/canvas/course_assignments.rb, app/models/canvas/egrades.rb, fixtures/pretty_vcr_recordings/Canvas_course_assignments.json, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/models/canvas/course_assignments_spec.rb, spec/models/canvas/egrades_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5072
=> CLC-5072 - E-Grades Export: Update export options feed with muted assignments

src/assets/javascripts/angular/services/utilService.js, src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5035
=> CLC-5035 - Update preventBubble for outbound links

src/assets/templates/settings.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5125
=> CLC-5125 - Student lookup widget looks broken on certain screen widths

src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5070
=> CLC-5070 - E-Grades Export: Implement UX modifications for download options display

src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4940
=> CLC-4940, show tabs if videos.length AND audio.length

src/assets/javascripts/angular/controllers/widgets/studentLookupController.js, src/assets/templates/widgets/student_lookup.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5123
Screencast: https://www.youtube.com/watch?v=xLK8bA_0Lyw
=> CLC-5123 - Student Lookup: "Recent" tab is confusing

app/controllers/canvas_course_grade_export_controller.rb, app/controllers/canvas_course_provision_controller.rb, app/models/canvas/background_job.rb, app/models/canvas/course_provision.rb, app/models/canvas/course_users.rb, app/models/canvas/egrades.rb, app/models/canvas/provide_course_site.rb, config/routes.rb, config/settings.yml, fixtures/pretty_vcr_recordings/Canvas_course_users.json, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/controllers/canvas_course_provision_controller_spec.rb, spec/models/canvas/background_job_spec.rb, spec/models/canvas/course_provision_spec.rb, spec/models/canvas/course_users_spec.rb, spec/models/canvas/egrades_spec.rb, spec/models/canvas/provide_course_site_spec.rb, spec/support/canvas_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5068
=> CLC-5068 - E-Grades Export: Implement background job process for course grade preparation

public/dummy/json/canvas_course_grade_export_job_status_completed.json, public/dummy/json/canvas_course_grade_export_job_status_error.json, public/dummy/json/canvas_course_grade_export_job_status_processing.json, public/dummy/json/canvas_course_grade_export_prepare_egrades_cache.json, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/javascripts/angular/factories/canvasCourseGradeExportFactory.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5069
=> CLC-5069 - E-Grade Export: Implement progress bar interface for background job

src/assets/templates/academics_booklist.html
https://jira.ets.berkeley.edu/jira/browse/CLC-3395
=> CLC-3395 Do not use 'My' with Book List

app/models/canvas/egrades.rb, spec/models/canvas/egrades_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5073
=> CLC-5073 - E-Grades Export: Add muted assignments table with notice and link to error display

src/assets/stylesheets/_academics.scss, src/assets/templates/academics_semester_classes.html
https://jira.ets.berkeley.edu/jira/browse/CLC-3391
=> CLC-3391 Add Book List link to My Academics semester page

src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5071
=> CLC-5071 - Applied Canvas style alerts to error page

Gemfile, Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-5141
=> CLC-5141 Remove Bundler from Gemfile

db/migrate/20150415232131_create_webcast_preferences_table.rb, db/schema.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5129
The opt_out column will support "no thank you" checkbox on Webcast widget. Down the road, this table might support the Webcast sign-up form, hosted by bCourses.  I will update 'release instructions' if / when this is merged.
=> CLC-5129, calcentral db: create table webcast_preferences

db/migrate/20150416164519_webcast_preferences_unique_index.rb, db/schema.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5129
Index correction. Set unique:true on year, term_cd, ccn.
=> CLC-5129, webcast_preferences index renamed and given unique: true

app/controllers/canvas_course_grade_export_controller.rb, app/models/canvas/background_job.rb, app/models/canvas/course_users.rb, app/models/canvas/egrades.rb, config/routes.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/models/canvas/egrades_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5066
=> CLC-5066 - Misc bug fixes

config/initializers/timeshift.rb, lib/proxies/mockable.rb, lib/timeshifter.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5124
NOTE: No Mockable proxy currently uses the timeshifting in ets/master, but there are 2 in the SIS branch that will need it.
=> CLC-5124 Let Timeshifter code work on the new Mockable proxy code

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5066
=> CLC-5066 - Added header to progress bar display. Applied fix to ng-if scope issue.

src/assets/javascripts/angular/controllers/widgets/studentLookupController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5126
=> CLC-5126 - View-as doesn't work on calcentral-dev

spec/ui_selenium/my_academics_data_webcasts_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5151
Test expectations updated per https://jira.ets.berkeley.edu/jira/browse/CLC-4940.
=> CLC-5151: fix webcast Selenium test to expect new UI

app/controllers/canvas_course_grade_export_controller.rb, app/models/canvas/egrades.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/models/canvas/egrades_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5066
=> CLC-5066 - Resolve issue with empty CSV download

spec/models/webcast/preferences_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5130
Bamboo passed on branch: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT46
Slightly more lenient spec is good enough.
=> CLC-5130, exception type of RecordNotUnique will vary per underlying db

app/models/berkeley/course_codes.rb, app/models/canvas/course_provision.rb, spec/models/canvas/course_provision_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5019
=> CLC-5019 Add ordering and tests for merge_non_teaching_site_sections

app/models/my_classes/campus.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5147
=> CLC-5147 Don't append sections to My Classes URLs unless multiple primaries

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5078
=> CLC-5078 - E-Grades Export: Add refresh grades option to download display

src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4911
=> CLC-4911 - Applied style to remove underline from secondary action buttons

config/settings/development.yml, config/settings/test.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-5052
=> CLC-5052 Rename feed_url -> base_url in 2 yml files that I missed

spec/features/act_as_user_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5150
Please wait for Green Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPCHRIS85-1
=> CLC-5150 Fix failing testext test

src/assets/javascripts/angular/controllers/widgets/studentLookupController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5154
=> CLC-5154 - View-As: save/un-save user automatically shows less

app/controllers/canvas_webcast_recordings_controller.rb, app/models/canvas/webcast_recordings.rb, config/routes.rb, spec/controllers/canvas_webcast_recordings_controller_spec.rb, spec/models/canvas/webcast_recordings_spec.rb, spec/models/webcast/course_media_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5146
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT47-1
More renaming in prep for new 'webcast-signup' LTI app.
=> CLC-5146, rename mediacasts to webcast_recordings

src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5139
=> CLC-5139 Skip transcript-only semesters in previous/next paging

src/assets/stylesheets/_academics.scss, src/assets/templates/academics_semester_classes.html
https://jira.ets.berkeley.edu/jira/browse/CLC-3391
=> CLC-3391 Move semester-page book list link to Classes header

src/assets/stylesheets/_academics.scss, src/assets/templates/academics_semester_classes.html
https://jira.ets.berkeley.edu/jira/browse/CLC-3391
QA version of #3636.
=> [QA] CLC-3391 Move semester-page book list link to Classes header

src/assets/templates/academics_final_exam_schedule.html, src/assets/templates/academics_semester_classes.html
Per @christianv comment on #3637.
=> NOJIRA Remove space concatenation from ng-bind

app/controllers/act_as_controller.rb, app/controllers/stored_users_controller.rb, config/routes.rb, spec/controllers/stored_users_controller_spec.rb, spec/features/act_as_user_spec.rb, src/assets/javascripts/angular/controllers/widgets/studentLookupController.js, src/assets/javascripts/angular/factories/adminFactory.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5150
QA branch version of #3620 and #3631
=> CLC-5150 (QA version) Moving deleteRecentUser logic to backend

app/controllers/canvas_lti_controller.rb, app/models/canvas/external_app_configurations.rb, app/views/canvas_lti/lti_course_webcast_sign_up.xml.erb, config/routes.rb, spec/models/canvas/reconfigure_external_apps_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/widgets/webcastSignUpController.js, src/assets/templates/canvas_embedded/course_webcast_sign_up.html, src/assets/templates/widgets/webcast_sign_up.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5061
Bamboo, too: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT49-1
The logic will come next. For example:
1. visibility def in erb file
2. render sign_up widget according to instructor type, ccn(s)
3. etc.
=> CLC-5061, webcast-signup.html wiring prior to adding logic

app/models/advising/my_advising.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5184
=> CLC-5184 Move Advising::MyAdvising to Mockable framework

script/bamboo-tests.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5190
=> CLC-5190 Let RAILS_ENV be set from environment

lib/tasks/output_xml_results.rake, script/bamboo-tests.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5190
https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPUT-JOB1-213/log failed, I believe because "bundle install" ran before the RAILS_ENV was set, and because the spec:xml rake task isn't defined when RAILS_ENV=production. This fixes both issues.
=> CLC-5190 Fix production UI test

app/models/advising/my_advising.rb, app/models/financials/my_financials.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5194
=> CLC-5194 Remove unnecessary JSON parsing from Advising and Financials

src/assets/stylesheets/_myfinances.scss, src/assets/stylesheets/_tables.scss, src/assets/templates/cars_activity.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5205
=> CLC-5205 - Create the cc-table-finances CSS class

src/assets/stylesheets/_activities.scss, src/assets/stylesheets/_widgets.scss, src/assets/templates/widgets/activity.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5204
=> CLC-5204 - Create the cc-widget-title-select class

src/assets/templates/academics_student_profile.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/widgets/roster.html, src/assets/templates/widgets/roster_photo.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5206
=> CLC-5206 - Use data-ng everywhere

spec/ui_selenium/pages/settings_page.rb, spec/ui_selenium/user_authorizations_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5120
These fixes adapt the existing view-as spec to the new UI.  There are also a few syntax changes in the contexts to improve readability of the examples.
=> CLC-5120: fix view-as Selenium tests

spec/models/finaid/my_fin_aid_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5198
=> CLC-5198 Follow-up: fix failing test

app/models/calmail/check_namespace.rb, app/models/calmail/list_members.rb, app/models/calmail/proxy.rb, config/settings.yml, config/settings/test.yml, lib/proxies/http_requester.rb, spec/models/calmail/check_namespace_spec.rb, spec/models/calmail/list_members_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5170
I've updated Bamboo and Dev configurations to enable testing.
=> CLC-5170 First two CalMail API proxies

spec/ui_selenium/pages/my_finances_details_page.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5220
=> CLC-5220: fix finances details page test

src/assets/templates/academics_semester_classes.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5221
=> CLC-5221 Show not-enrolled message when user has no enrolled courses

app/models/webcast/system_status.rb, fixtures/webcast/webcast-system-status.json, fixtures/webcast/webcast.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5216
Bamboo, too: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT50-2
Before I commit the merged feed logic I need test data to be correct w.r.t ccn uniqueness. This PR also includes proper boolean in webcast_system_status.json with corresponding change in spec.
=> CLC-5216, fix test data (ccn uniqueness); sign_up not active when feature flag false

app/controllers/canvas_course_grade_export_controller.rb, app/models/canvas/course_assignments.rb, app/models/canvas/egrades.rb, fixtures/pretty_vcr_recordings/Canvas_course_assignment_unmute.json, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/models/canvas/course_assignments_spec.rb, spec/models/canvas/egrades_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/javascripts/angular/factories/canvasCourseGradeExportFactory.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5075
=> CLC-5075 - E-Grades Export 2: Add option to unmute assignments from error page

app/controllers/canvas_course_grade_export_controller.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5175
=> CLC-5175 - E-Grades Export 2: Update filename to include CCN and 'current' or 'final' distinction

Gemfile, Gemfile.lock, spec/models/calmail/check_namespace_spec.rb, spec/models/calmail/list_members_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5170
We're going to live unhappily with some mystery for a while...
=> CLC-5170 Lock down mocked tests; disable integration tests

app/controllers/canvas_course_grade_export_controller.rb, app/models/canvas/egrades.rb, app/models/canvas/official_course.rb, config/settings.yml, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/models/canvas/egrades_spec.rb, spec/models/canvas/official_course_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/javascripts/angular/services/utilService.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5233
=> CLC-5233 - E-Grades Export 2: Implement auto-download workflow

app/models/calendar/queries.rb, spec/models/calendar/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5176
=> CLC-5176 Add future term to Calendar export

app/models/google_apps/proxy.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5238
=> CLC-5238 Remove call on sometimes-undefined WebMock

config/initializers/disable_webmock_default.rb
Follow-up on #3688
https://jira.ets.berkeley.edu/jira/browse/CLC-5238
=> CLC-5238 Follow-up comment edit

app/models/cal_groups/find_groups.rb, app/models/cal_groups/get_members.rb, app/models/cal_groups/group.rb, app/models/cal_groups/group_delete.rb, app/models/cal_groups/group_save.rb, app/models/cal_groups/proxy.rb, fixtures/json/cal_groups_group_delete.json, fixtures/json/cal_groups_group_save_already_exists.json, fixtures/json/cal_groups_group_save_success.json, lib/proxies/http_requester.rb, spec/models/cal_groups/find_groups_spec.rb, spec/models/cal_groups/get_members_spec.rb, spec/models/cal_groups/group_delete_spec.rb, spec/models/cal_groups/group_save_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5202
https://jira.ets.berkeley.edu/jira/browse/CLC-5239
Also factoring some of the response checks out of CalGroups::Proxy and into subclasses for finer grain.
=> CLC-5202 Add proxies for group save and delete

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-5046
This followup should fix the build on Bamboo.
=> CLC-5046 Remove lock_timeout setting, which only works in Postgres > 9.3

src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5241
=> CLC-5241 - E-Grades Export 2: Misc Styling Fixes

Gemfile, Gemfile.lock
Mopping up after https://github.com/ets-berkeley-edu/calcentral/pull/3691
=> NOJIRA Update google-api-client in Gemfile

lib/tasks/webcast.rake, script/manage-webcast-lti-app.sh, script/webcast.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5136
The rake task will be implemented per https://jira.ets.berkeley.edu/jira/browse/CLC-5242.
=> CLC-5136, rake task and shell scrpt in support of Webcast cron job

app/models/cal_groups/member.rb, app/models/cal_groups/member_add.rb, app/models/cal_groups/member_delete.rb, app/models/cal_groups/member_get.rb, fixtures/json/cal_groups_member_add.json, fixtures/json/cal_groups_member_delete.json, fixtures/json/cal_groups_member_get.json, lib/proxies/http_requester.rb, spec/models/cal_groups/member_add_spec.rb, spec/models/cal_groups/member_delete_spec.rb, spec/models/cal_groups/member_get_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5181
https://jira.ets.berkeley.edu/jira/browse/CLC-5202
HttpRequester gets its last verb.
=> CLC-5202 Add proxies to get, add and delete individual members

db/schema.rb
Missing line from https://github.com/ets-berkeley-edu/calcentral/pull/3700
=> CLC-5135 Update the DB schema version

spec/controllers/canvas_course_add_user_controller_spec.rb
Happened to come up in a search.
=> NOJIRA Remove stray debugging line

src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/settings.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5249
=> CLC-5249 - Remove unused IDs

public/dummy/json/finaid_award.json, public/dummy/json/finaid_budget.json, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/finaidController.js, src/assets/javascripts/angular/controllers/widgets/finaidAwardController.js, src/assets/javascripts/angular/controllers/widgets/finaidBudgetController.js, src/assets/javascripts/angular/directives/budgetChartDirective.js, src/assets/javascripts/angular/factories/finaidFactory.js, src/assets/javascripts/angular/services/finaidTermService.js, src/assets/stylesheets/_budget_chart.scss, src/assets/stylesheets/_finaid_award.scss, src/assets/stylesheets/_finaid_budget.scss, src/assets/stylesheets/_text.scss, src/assets/stylesheets/_widgets.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/directives/budget_chart.html, src/assets/templates/finaid.html, src/assets/templates/finaid_summary.html, src/assets/templates/myfinances.html, src/assets/templates/widgets/finaid_award.html, src/assets/templates/widgets/finaid_budget.html
https://jira.berkeley.edu/browse/SISRP-3682
=> SISRP-3682 - Develop FinAid Awards front-end code

src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/templates/canvas_embedded/_shared/sections_table.html, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5223
=> CLC-5223 - Web Accessibility: Apply Accessibility Guidelines to 'Create a Site' Tool

src/assets/templates/widgets/roster.html, src/assets/templates/widgets/roster_photo.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5224
=> CLC-5224 - Web Accessibility: Apply Accessibility Guidelines to 'Roster Photos' Tool

src/assets/javascripts/angular/controllers/pages/canvasUserProvisionController.js, src/assets/stylesheets/_canvas_user_provision.scss, src/assets/templates/canvas_embedded/user_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5225
=> CLC-5225 - Web Accessibility: Apply Accessibility Guidelines to 'User Provisioning' Tool

app/models/webcast/rooms.rb, spec/models/webcast/rooms_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5242
Our cron job will use this to check rooms associated with a given course.
=> CLC-5242, rooms class has includes_any?

src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5223
=> CLC-5223 - Added hidden label for CCN list textarea

src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5223
=> CLC-5223 - Updated ID for form input to avoid conflict in global namespace

src/assets/stylesheets/_base.scss, src/assets/stylesheets/_canvas_course_add_user.scss, src/assets/templates/canvas_embedded/course_add_user.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5226
=> CLC-5226 - Web Accessibility: Apply Accessibility Guidelines to 'Find a Person to Add' Tool

src/assets/stylesheets/_canvas_course_manage_official_sections.scss, src/assets/templates/canvas_embedded/_shared/sections_table.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5228
=> CLC-5228 - Web Accessibility: Apply Accessibility Guidelines to 'Official Sections' Tool

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5229
=> CLC-5229 - Web Accessibility: Resolve all WAVE Errors/Alerts in 'E-Grades Export' Tool

src/assets/javascripts/angular/controllers/widgets/adminController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5283
Restores a function that #3725 inexplicably left out.
=> CLC-5283 View As: update ID field when recent/saved user clicked

src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5228
=> CLC-5228 - Converted H3 to H2 for proper header hierarchy

src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5227
=> CLC-5227 - Web Accessibility: Resolve all WAVE Errors/Alerts in 'Webcasts' Tool

app/models/canvas/external_tools.rb, app/models/canvas/webcast_eligible_courses.rb, spec/models/canvas/external_tools_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5242
Bug fix on verify tab update. Test coverage, too.
=> CLC-5242, fix raise error when tab update fails; test coverage; logging

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5300
See #3749 for QA PR
=> CLC-5300 - E-Grades Export: selected "section" option not respected when generating download

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5300
See #3748 for master PR
=> [QA] CLC-5300 - E-Grades Export: selected "section" option not respected when generating download

app/models/webcast/merged.rb, fixtures/webcast/webcast.json, spec/models/webcast/merged_spec.rb, spec/models/webcast/recordings_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5299
This is for 'qa' branch. Merged to master in PR #3747 I verified fix on master (dev env).
=> CLC-5299, Webcasts: recordings duplicated on cross-listed course (qa branch)

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5300
Unable to reproduce in local environment. Attempting to see if the conversion of an ngIf to an ngShow will resolve the issue.
=> CLC-5300 - E-Grades Export Hotfix 2 - Electric Boogaloo

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5300
See #3751 for Master PR
=> [QA] CLC-5300 - E-Grades Export Hotfix 2 - Electric Boogaloo

src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5228
=> CLC-5228 - Converted aria-hidden attribute to use ng-attr directive

spec/models/webcast/sign_up_eligible_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5301
Bamboo passed: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT53-2
Ready for review.
=> CLC-5301, non-fake spec must assume is_sign_up_active=true

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_buttons.scss, src/assets/stylesheets/_canvas_colors.scss, src/assets/stylesheets/_canvas_course_add_user.scss, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/stylesheets/_canvas_course_manage_official_sections.scss, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/stylesheets/_canvas_user_provision.scss, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5092
=> CLC-5092 - bCourses CSS: Update Create a Site styling

src/assets/stylesheets/_canvas_base.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5092
=> CLC-5092 - Summarize with proper SASS

spec/ui_selenium/my_academics_data_advising_appts_spec.rb, spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/my_academics_data_status_blocks_spec.rb, spec/ui_selenium/my_finances_data_finaid_spec.rb, spec/ui_selenium/my_finances_data_transaction_detail_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5313
Adding more checks for the health of various feeds, plus minor cleanup.
=> CLC-5313: add "testable users" check to all UID-driven Selenium tests

src/assets/images/canvas/ic-icon-arrow-down.svg, src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_buttons.scss, src/assets/stylesheets/_canvas_roster.scss, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/create_project_site.html, src/assets/templates/widgets/roster.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5093
=> CLC-5093 - bCourses CSS: Course Site Roster Photos styling

src/assets/images/canvas/ic-icon-arrow-down.svg, src/assets/images/canvas/select-menu-arrow-down.svg
https://jira.ets.berkeley.edu/jira/browse/CLC-5093
=> CLC-5093 - Renamed and optimized SVG used in Canvas styled select menus

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_buttons.scss, src/assets/stylesheets/_canvas_roster.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5093
Refactor meant to resolve issues with use of `@extend` in SCSS in ##3769
=> CLC-5093 - Refactor to remove use of @extend in SCSS for Roster Photos tool

spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/pages/api_my_academics_page.rb, spec/ui_selenium/pages/api_my_status_page.rb, spec/ui_selenium/pages/my_academics_page.rb, spec/ui_selenium/pages/my_academics_profile_card.rb, spec/ui_selenium/pages/my_academics_university_reqts_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5289
A new WebDriver test for the academic profile and university requirements UIs on My Academics.  The test iterates through real accounts and verifies the permutations of data and messaging displayed.
=> CLC-5289: QA test for academic profile

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_user_provision.scss, src/assets/templates/canvas_embedded/user_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5094
=> CLC-5094 - bCourses CSS: User Provisioning styling

src/assets/stylesheets/_canvas_course_manage_official_sections.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5097
=> CLC-5097 - Increasing sub-header to 17px

app/models/canvas/course_add_user.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/javascripts/angular/services/utilService.js, src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_course_add_user.scss, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/create_project_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5095
=> CLC-5095 - bCourses CSS: Site Find a Person to Add styling

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_buttons.scss, src/assets/stylesheets/_canvas_colors.scss, src/assets/stylesheets/_canvas_course_add_user.scss, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/stylesheets/_canvas_course_manage_official_sections.scss, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/stylesheets/_canvas_create_project_site.scss, src/assets/stylesheets/_canvas_embedded.scss, src/assets/stylesheets/_canvas_roster.scss, src/assets/templates/canvas_embedded/course_grade_export.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/create_project_site.html, src/bcourses_embedded.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5098
=> CLC-5098 - bCourses CSS: E-Grades styling

spec/ui_selenium/my_academics_data_advising_appts_spec.rb, spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/my_academics_data_status_blocks_spec.rb, spec/ui_selenium/my_dashboard_google_live_updates_spec.rb, spec/ui_selenium/my_dashboard_google_up_next_spec.rb, spec/ui_selenium/my_finances_data_transaction_detail_spec.rb, spec/ui_selenium/pages/api_my_financials_page.rb, spec/ui_selenium/pages/google_page.rb, spec/ui_selenium/pages/settings_page.rb, spec/ui_selenium/util/web_driver_utils.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5326
=> CLC-5326: misc Selenium test fixes

gulpfile.js, package.json, src/assets/javascripts/angular/calcentral.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5296
=> CLC-5296 - Include the ngAria module

src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_buttons.scss, src/assets/stylesheets/_canvas_colors.scss, src/assets/stylesheets/_canvas_course_add_user.scss, src/assets/stylesheets/_canvas_create_project_site.scss, src/assets/stylesheets/_canvas_site_creation.scss, src/assets/templates/canvas_embedded/_shared/back_to_gradebook_link.html, src/assets/templates/canvas_embedded/_shared/background_job_error.html, src/assets/templates/canvas_embedded/_shared/canvas_errors.html, src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/_shared/progress_bar.html, src/assets/templates/canvas_embedded/_shared/sections_table.html, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/course_grade_export.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/create_project_site.html, src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5091
=> CLC-5091 - Misc Tweaks Part 1

app/models/mailing_lists/site_mailing_list.rb, db/migrate/20150521163404_add_list_details_to_canvas_site_mailing_lists.rb, db/schema.rb
Back-end work under https://jira.ets.berkeley.edu/jira/browse/CLC-5211, in order to implement the designs at https://jira.ets.berkeley.edu/jira/browse/CLC-5321.
Adjustments to the SiteMailingList model logic will follow in another PR.
=> CLC-5211 Mailing lists: add members count and recent errors to database

src/assets/stylesheets/_campus.scss, src/assets/stylesheets/_sidebar.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/campus.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5331
=> CLC-5331 - Refactor sidebar code

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_roster.scss, src/assets/templates/widgets/roster.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5093
=> CLC-5093 - Applied cleaner resolution to the @extend fix

src/assets/javascripts/angular/services/academicsService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5298
=> CLC-5298 Only ask about textbooks for unique primary sections

src/assets/stylesheets/_campus.scss, src/assets/stylesheets/_sidebar.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5336
=> CLC-5336 - Campus page doesn't show on mobile

app/models/campus_solutions/proxy.rb, app/models/finaid/my_awards.rb, app/models/finaid/my_budget.rb, app/models/my_tasks/sis_tasks.rb, lib/hash_converter.rb, spec/models/campus_solutions/awards_spec.rb, spec/models/campus_solutions/budget_spec.rb, spec/models/campus_solutions/checklist_spec.rb
https://jira.berkeley.edu/browse/SISRP-4274
=> SISRP-4274 Camelcase fields in CS APIs

app/controllers/canvas_mailing_lists_controller.rb, app/models/mailing_lists/site_mailing_list.rb, config/routes.rb, public/dummy/json/canvas_site_mailing_list_bad_site.json, public/dummy/json/canvas_site_mailing_list_new.json, public/dummy/json/canvas_site_mailing_list_pending.json, public/dummy/json/canvas_site_mailing_list_populated_failure.json, public/dummy/json/canvas_site_mailing_list_populated_success.json, spec/controllers/canvas_mailing_lists_controller_spec.rb, spec/models/mailing_lists/site_mailing_list_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/canvasSiteMailingListController.js, src/assets/javascripts/angular/factories/canvasSiteMailingListFactory.js, src/assets/stylesheets/_canvas_site_mailing_list.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/canvas_embedded/site_mailing_list.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5323
In addition to the front-end, this PR includes some back-end changes to the error reporting, bringing it more in line with Rails validation conventions and making messages more human-readable.
=> CLC-5323 Mailing lists: front-end implementation

app/controllers/canvas_lti_controller.rb, app/models/canvas/external_app_configurations.rb, app/views/canvas_lti/lti_site_mailing_lists.xml.erb, config/routes.rb, config/settings.yml
=> CLC-5211 LTI wiring for mailing list admin app

src/assets/javascripts/angular/controllers/widgets/webcastSignUpController.js, src/assets/stylesheets/_webcast.scss, src/assets/templates/widgets/webcast_sign_up.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5174
* Top margin in webcast widget removed.
* Unneeded sign-up assets removed
=> CLC-5174, Webcast widget needs a layout tweak

app/controllers/campus_solutions_controller.rb, app/models/campus_solutions/address.rb, app/models/campus_solutions/my_address.rb, config/routes.rb, public/dummy/json/cs_address.json, spec/controllers/campus_solutions_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-4274
The POST works on CalCentral but doesn't actually call Campus Solutions yet.
=> SISRP-4274 Create CalCentral POST endpoint for address update

app/views/canvas_lti/lti_site_mailing_lists.xml.erb, config/settings.yml, src/assets/javascripts/angular/configuration/routeConfiguration.js
One misconfiguration, one typo, one missing route. Ace work!
=> CLC-5211 Fix LTI configuration for mailing list app

src/assets/stylesheets/_canvas_site_mailing_list.scss, src/assets/templates/canvas_embedded/site_mailing_list.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5323
Follow-up to keep pace with changes in #3809.
=> CLC-5323 Mailing list app: update alert styling

lib/tasks/mailing_lists.rake, script/update-mailing-list-memberships.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5212
Also some tweaks to the Rake task, for better logging and to match new error handling in the SiteMailingList model.
=> CLC-5212 Shell script for mailing list updates

src/assets/stylesheets/_webcast.scss, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5022
https://jira.ets.berkeley.edu/jira/browse/CLC-5174
Widget styling, tabs or no tabs. Plus, new style for help link.
=> CLC-5209, styles and help link in Webcast widget

app/models/canvas/courses_report.rb, app/models/canvas/csv.rb, app/models/canvas/refresh_all_campus_data.rb, app/models/canvas/report.rb, app/models/canvas/term_enrollments_csv.rb, app/models/canvas/turnitin_reporter.rb, config/settings.yml, fixtures/pretty_vcr_recordings/Canvas_check_provisioning_report_courses.json, fixtures/pretty_vcr_recordings/Canvas_course_assignments.json, fixtures/pretty_vcr_recordings/Canvas_provisioning_report_courses_csv.csv, fixtures/pretty_vcr_recordings/Canvas_provisioning_report_courses_csv.json, fixtures/pretty_vcr_recordings/Canvas_provisioning_report_file_courses.json, fixtures/pretty_vcr_recordings/Canvas_start_provisioning_report_courses.json, spec/models/canvas/turnitin_reporter_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4579
This lets us produce a one-off report from the console. If it meets requirements, a cron job script can land in the next sprint.
=> CLC-4579 Generate report on bCourses TurnItIn usage as CSV

app/models/mailing_lists/site_mailing_list.rb, spec/models/mailing_lists/site_mailing_list_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasSiteMailingListController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5347
=> CLC-5347 Mailing lists: display Calmail connection error

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5274
=> CLC-5274 - Web Accessibility 2: Apply Accessibility Guidelines to 'Create a Site' Tool

src/assets/templates/widgets/roster.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5275
=> CLC-5275 - Web Accessibility 2: Apply Accessibility Guidelines to 'Roster Photos' Tool

src/assets/templates/canvas_embedded/user_provision.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5276
=> CLC-5276 - Web Accessibility 2: Apply Accessibility Guidelines to 'User Provisioning' Tool

app/models/canvas/turnitin_reporter.rb, spec/models/canvas/turnitin_reporter_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4579
Hit this when generating an early report for Summer.
=> CLC-4579 Handle terms without enabled assignments

app/models/campus_solutions/direct_proxy.rb
https://jira.berkeley.edu/browse/SISRP-4274
=> SISRP-4274 Iterate more cleanly

app/models/canvas/turnitin_reporter.rb, lib/tasks/canvas.rake, script/report-turnitin-usage.sh, spec/models/canvas/turnitin_reporter_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4579
This should make QA a little easier.
=> CLC-4579 Rake task to generate TurnItIn report for a term

script/update-mailing-list-memberships.sh
Review of #3824 alerted me to the log in my own eye.
=> NOJIRA Uncomment cd in mailing list update script

app/models/rosters/common.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5350
=> CLC-5350 Add UID to roster photos cache key

app/models/bearfacts/proxy.rb, config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-5308
And a little extra cleanup.
=> CLC-5308 Remove obsolete Bearfacts token

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5280
=> CLC-5280 - Web Accessibility 2: Apply Accessibility Guidelines to 'E-Grades Export' Tool

src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5022
'Report problem' only if webcasts exist.
=> CLC-5022, do not show 'report problem' unless video OR audio

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5280
See #3835 for QA PR
=> CLC-5280 - Resolved aria-disabled issue with non-explicit boolean value

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5280
See #3834 for Dev/Master PR
=> [QA] CLC-5280 - Resolved aria-disabled issue with non-explicit boolean value

spec/support/proxy_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5291
=> CLC-5291 Remove student data proxy external test

spec/models/campus_oracle/queries_spec.rb, spec/models/canvas/csv_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5358
Wait for Bamboo!
=> CLC-5358 Replace lost LDAP UID with existing LDAP UID

spec/models/campus_oracle/queries_spec.rb, spec/models/canvas/csv_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/3837
Needed to fix Bamboo builds.
=> QA CLC-5358 Replace lost LDAP UID with existing LDAP UID

app/models/calmail/proxy.rb, spec/models/calmail/check_namespace_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5346
QA version of #3840.
=> [QA] CLC-5346 Set explicit user agent on Calmail proxy requests

gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5364
=> CLC-5364 - Front-end assets are not being hashed

gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5364
Follow up from #3844 - we should test that one first before merging this PR
=> CLC-5364 QA - Front-end assets are not being hashed

README.md, config/settings/test.yml, config/settings/testext.yml
https://jira.berkeley.edu/browse/SISRP-4458
=> SISRP-4458 -  Removed 'act_as' from the features list

src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/stylesheets/_canvas_site_creation.scss, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5091
* Updated button links to use 300 font-weight
* Site Creation: Make paragraph text use font-weight of '300'
* Official Sections: Updated success notice to say "The sections in this course site have been updated successfully."
* Find a Person to Add: Hide search form and expandable help text while user addition is processing
* Find a Person to Add: Made search result limitation notice use blue info alert rather than yellow warning alert
=> CLC-5091 - Final Design Tweaks

app/models/mailing_lists/site_mailing_list.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5374
QA version of #3855.
=> [QA] CLC-5374 Make model callbacks play more nicely with RailsAdmin

src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/stylesheets/_canvas_base.scss, src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5096
=> CLC-5362 - bCourses Webcasts: audio drop-down lacks Canvas styling

public/dummy/json/finaid_award.json, src/assets/javascripts/angular/factories/finaidFactory.js, src/assets/templates/widgets/finaid_award.html
https://jira.berkeley.edu/browse/SISRP-4516
=> SISRP-4516 - Disable the outbound link directive when clicking on "Revisit Loan Amounts"

src/assets/javascripts/angular/directives/outboundLinkDirective.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5383
=> CLC-5383 - Add ability to disable the outboundLinkDirective

app/models/webcast/course_media.rb, app/models/webcast/merged.rb, spec/controllers/mediacasts_controller_spec.rb, spec/models/canvas/webcast_recordings_spec.rb, spec/models/webcast/course_media_spec.rb, spec/models/webcast/merged_spec.rb, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5394
=> CLC-5394, iTunes links have vanished

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5362
=> CLC-5362 - bCourses CSS 2: Make all apps fit the style guide

src/assets/stylesheets/_widgets.scss
https://jira.berkeley.edu/browse/SISRP-4519
=> SISRP-4519 - Changed broken link in _widgets.scss file

src/assets/stylesheets/_base.scss, src/assets/stylesheets/lib/foundation.css
https://jira.ets.berkeley.edu/jira/browse/CLC-5405
=> CLC-5405 - Clean up unused foundation CSS

spec/ui_selenium/my_academics_data_status_blocks_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5409
=> CLC-5409-improve sanity check in reg status test

app/models/canvas/course_policy.rb, app/policies/authentication_state_policy.rb, spec/models/berkeley/course_policy_spec.rb, spec/models/canvas/course_policy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5403
FYI:
* This addition to policies will be used by webcast-related controllers.
* I did a lot of cleanup in the specs. I only added a few tests of my own.
=> CLC-5403, can_view_webcast_sign_up added to CoursePolicy and spec cleanup

src/assets/javascripts/angular/controllers/widgets/webcastController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5411
=> CLC-5411, Webcast front-end can not assume .videos.length for signUpEligible course

src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5413
=> CLC-5413 - Safari is generating lots of "Can't interpolate" JS errors is the tasks code

public/dummy/json/academics.json, public/dummy/json/academics_transition_not_registered.json, public/dummy/json/academics_transition_registered.json, src/assets/templates/academics_student_profile.html
Tragicomedy at https://jira.ets.berkeley.edu/jira/browse/CLC-5406.
=> CLC-5406 Surface profile messages during term transitions

app/models/campus_oracle/user_attributes.rb, app/models/my_badges/student_info.rb, app/models/notifications/reg_status_translator.rb, public/dummy/json/academics.json, public/dummy/json/academics_transition_not_registered.json, public/dummy/json/academics_transition_registered.json, spec/models/campus_oracle/user_attributes_spec.rb, spec/models/my_academics/exams_spec.rb, spec/models/my_badges/student_info_spec.rb, src/assets/templates/academics_student_profile.html, src/assets/templates/widgets/academic_profile_popover.html, src/assets/templates/widgets/badges_popover.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5406
https://jira.ets.berkeley.edu/jira/browse/CLC-5408
QA omnibus comprising #3874, #3879, #3880, #3882.
=> [QA] CLC-5406 CLC-5408 Fix term transitions in My Academics and badges

src/assets/templates/academics_status_and_blocks.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5419
=> CLC-5419 Surface residency status even if registration status is missing

README.md
Should be uncontroversial changes.
=> README: Copyedit

fixtures/xml/bearfacts_profile_11667051.xml, spec/models/my_academics/college_and_level_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5417
=> CLC-5417 Update sample Bearfacts profile feed

config/settings.yml, spec/models/oec/courses_diff_spec.rb, spec/models/oec/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-636
=> OEC-636, bump OEC default settings.yml to Summer 2015 (w/ spec changes)

src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5366
Trigger bug: https://github.com/angular/angular.js/issues/11959
=> CLC-5366 Work around AngularJS Boolean bug in My Tasks

spec/models/textbooks/proxy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5425
=> CLC-5425 Update Textbooks integration tests for summer 2015

src/assets/templates/widgets/my_classes.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5407
=> CLC-5407 Show faculty-appropriate messages in My Classes

src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js, src/assets/javascripts/angular/controllers/pages/rosterController.js, src/assets/javascripts/angular/directives/focusResetDirective.js, src/assets/javascripts/angular/services/utilService.js, src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_course_manage_official_sections.scss, src/assets/stylesheets/_canvas_roster.scss, src/assets/templates/canvas_embedded/_shared/screenreader_alert.html, src/assets/templates/canvas_embedded/_shared/sections_table.html, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/course_grade_export.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/widgets/roster.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5372
Adds focus management, accessibility announcement service, and other misc accessibility tweaks.
=> CLC-5372 - Web Accessibility 3: misc accessibility issues

script/webcast_lti_refresh.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5428
=> CLC-5428, Point script/webcast_lti_refresh.sh at proper rake task

src/assets/javascripts/angular/controllers/widgets/webcastController.js, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5389
* Removes automatic reading of loaded content (resolves issues with reading relevant alerts)
* Adds announcements when switching between 'Video' and 'Audio' tab.
* Adds announcements when selecting a specific video or audio recording.
=> CLC-5389 - Web Accessibility 3: Webcasts

app/models/webcast/merged.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5442
=> CLC-5442, webcast widget describes steps to sign-up even after sign-up is closed

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5455
=> CLC-5455 - License should be a valid SPDX license expression

app/models/webcast/merged.rb, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5457
Plus, some logging.
=> CLC-5457, readable list in '...will appear here after classes start' section of webcast widget

app/controllers/canvas_course_grade_export_controller.rb, app/controllers/canvas_course_provision_controller.rb, app/models/canvas/background_job.rb, app/models/canvas/provide_course_site.rb, spec/controllers/canvas_course_provision_controller_spec.rb, spec/models/canvas/provide_course_site_spec.rb, spec/support/canvas_shared_examples.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js, src/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5108
=> CLC-5108  - Have Course Site Provisioning use new background job module

src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5458
=> CLC-5458 - In task edit mode, hovering over the container div, shows a triangle in an odd location

spec/models/webcast/merged_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5452
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT58-1
Fallout from #3916
=> CLC-5452, user_id was undefined in spec, after refactor of Webcast::Merged init

app/models/webcast/merged.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5452
These cache entries must be per course_site / uid.
=> CLC-5452, Webcast::Merged cache_key must include @uid

app/models/canvas/webcast_lti_refresh.rb, lib/tasks/canvas.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-5454
Rake task will exclude sis_term_id if id.end_with?('A')  or  id.end_with?('C')
=> CLC-5454, Webcast refresh script is checking more course sites than expected

package.json, src/assets/javascripts/angular/calcentral.js, src/assets/javascripts/angular/services/widgetService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5456
=> CLC-5456 - Unscheduled task edits respond differently to mouse click vs keystroke

gulpfile.js, src/assets/javascripts/angular/calcentral.js, src/assets/javascripts/angular/configuration/securityConfiguration.js, src/assets/javascripts/angular/controllers/calcentralController.js, src/assets/javascripts/angular/services/analyticsService.js, src/assets/javascripts/angular/services/errorService.js, src/assets/javascripts/lib/analytics.js, src/base.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5462
https://jira.berkeley.edu/browse/SISRP-4328
=> CLC-5462 - Synchronous XMLHttpRequest warning

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5465
=> CLC-5465 - Update gulp-inject and streamqueue

app/models/canvas/provide_course_site.rb, spec/models/canvas/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5108
* Also added tests for proper step calculation
=> CLC-5108 - Corrected total steps for course creation by CCN.

gulpfile.js, package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5468
=> CLC-5468 - Minify our AngularJS html templates

src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5215
https://jira.ets.berkeley.edu/jira/browse/CLC-5470
https://jira.ets.berkeley.edu/jira/browse/CLC-5467
A few small wording and markup fixes in Webcast widget.
=> CLC-5470: wording and data-ng-href in webcast widget

gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5473
=> CLC-5473 Do not strip empty attributes from minified HTML

app/controllers/canvas_course_provision_controller.rb, app/models/canvas/provide_course_site.rb, spec/controllers/canvas_course_provision_controller_spec.rb, spec/models/canvas/provide_course_site_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js, src/assets/javascripts/angular/services/utilService.js, src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5395
=> CLC-5395 - Modify workflow of Create a course site tool

app/models/canvas/course_add_user.rb, spec/models/canvas/course_add_user_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5396
Actually only performs SIS User Import if the user is not already present within Canvas. I had to make an executive decision... like a baws
=> CLC-5396 - Remove SIS import on Add a Person tool

app/policies/authentication_state_policy.rb, config/settings.yml, config/settings/test.yml, config/settings/testext.yml, spec/policies/authentication_state_policy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5472
Modified logic in can_view_webcast_sign_up?. Feature flag will be false in upcoming release.
=> CLC-5472, New feature flag: webcast_sign_up_on_calcentral

src/assets/templates/academics_status_and_blocks.html, src/assets/templates/cal1card.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5478
=> CLC-5478 - Bad spacing in "Status and Blocks" header

src/assets/stylesheets/_canvas_base.scss, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5401
=> CLC-5401 Style tabs in webcast widget per Instructure guide

spec/ui_selenium/my_academics_data_webcasts_spec.rb, spec/ui_selenium/pages/my_academics_class_page.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5488
=> CLC-5488: fix QA webcast test

src/assets/javascripts/angular/services/utilService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5491
=> CLC-5491 - IE doesn't like webcasts anymore

src/assets/javascripts/angular/services/utilService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5491
Master PR at #3945
=> CLC-5491 QA - IE doesn't like webcasts anymore

README.md
https://jira.ets.berkeley.edu/jira/browse/CLC-5490
Also pruned a frond.
=> CLC-5490 Update README for Rails 4.1.11

lib/proxies/http_request.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5483
=> CLC-5483 Fix logging in Proxies::HttpRequest

gulpfile.js, src/assets/templates/academics_status_and_blocks.html, src/assets/templates/cal1card.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5478
Different approach to fix the bug described in CLC-5478 after reading @raydavis' comment
=> CLC-5478 QA - Bad spacing in "Status and Blocks" header

lib/proxies/http_request.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5483
QA version of #3950.
=> [QA] CLC-5483 Fix logging in Proxies::HttpRequest

app/models/campus_oracle/user_attributes.rb, spec/models/campus_oracle/user_attributes_spec.rb, src/assets/templates/academics_status_and_blocks.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5419
QA version of #3946.
=> [QA] CLC-5419 Do not surface residency status during term transitions

README.md
https://jira.ets.berkeley.edu/jira/browse/CLC-5490
QA version of #3948.
=> [QA] CLC-5490 Update README for Rails 4.1.11

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5497
=> CLC-5497 - undefined is not a function (evaluating 's.accessibilityAnnounceAnnounce

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5497
=> CLC-5497 QA - undefined is not a function (evaluating 's.accessibilityAnnounceAnnounce

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_buttons.scss, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/create_project_site.html, src/assets/templates/canvas_embedded/site_mailing_list.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5440
=> CLC-5440 - Reverse Cancel/Confirm action buttons in HTML, use CSS to re-order

src/assets/templates/academics_student_profile.html
Fix for one issue @raydavis tracked down in https://jira.ets.berkeley.edu/jira/browse/CLC-5431.
=> CLC-5431 Do not show zero-unit totals for students without standing

src/assets/templates/academics_student_profile.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5431
=> CLC-5431 Do not presume when student profile information is incomplete

public/canvas/canvas-customization.js, src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/javascripts/angular/controllers/pages/canvasSiteCreationController.js, src/assets/stylesheets/_canvas_base.scss, src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5439
=> CLC-5439 - Apply adjustments discovered from web accessibility review

.jshintrc, gulpfile.js, package.json, src/assets/javascripts/angular/directives/datePickerDirective.js, src/assets/javascripts/angular/services/dateService.js, src/assets/javascripts/angular/services/errorService.js, src/assets/javascripts/angular/services/utilService.js, src/assets/javascripts/index.js
https://jira.berkeley.edu/browse/SISRP-4327
https://jira.ets.berkeley.edu/jira/browse/CLC-5475
*Note*: Only merge from Monday onwards
=> SISRP-4327 - Investigate using browserify for JS dependencies

.jshintrc, app/models/my_activities/canvas_activities.rb, gulpfile.js, package.json, public/canvas/canvas-customization.js, spec/models/my_activities/canvas_spec.rb, spec/ui_selenium/my_academics_data_webcasts_spec.rb, spec/ui_selenium/pages/my_academics_class_page.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js, src/assets/javascripts/angular/controllers/pages/canvasSiteCreationController.js, src/assets/javascripts/angular/controllers/pages/profileController.js, src/assets/javascripts/angular/controllers/widgets/tasksController.js, src/assets/javascripts/angular/directives/datePickerDirective.js, src/assets/javascripts/angular/factories/activityFactory.js, src/assets/javascripts/angular/services/dateService.js, src/assets/javascripts/angular/services/errorService.js, src/assets/javascripts/angular/services/utilService.js, src/assets/javascripts/index.js, src/assets/stylesheets/_canvas_base.scss, src/assets/templates/academics_student_profile.html, src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/course_add_user.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/canvas_embedded/site_creation.html
Fix merge conflicts & following files:
* Require lodash in index.js
* Require lodash in profileController & tasksController
* `package.json` & `gulpfile.js`
=> Merge master branch into sis-master

gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5503
=> CLC-5503 - application.js is no longer hashed

gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5335
=> CLC-5335 - Gulp task sometimes doesn't run completely

gulpfile.js
https://jira.berkeley.edu/browse/SISRP-4327
https://jira.ets.berkeley.edu/jira/browse/CLC-5475
#3969
=> SISRP-4327 - Fixed bundleShare function comment syntax and used paths

config/deploy.rb
Looks like this might have broken the build, reverting this for now
https://jira.ets.berkeley.edu/jira/browse/CLC-5504
=> CLC-5504-revert Make first node available ASAP

public/maintenance/index_emergency.html, public/maintenance/index_maintenance.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5505
=> CLC-5505 - Make maintenance page & emergency page responsive

gulpfile.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5514
=> CLC-5514 - Fixed duplicate watchify executions

config/deploy.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5504
Followup PR that fixes the broken build from #3974 . My mistake was omitting the "hosts" param in that run call.
=> CLC-5504 Fix goof in deploy.rb: Only run update-build.sh once per host

.jscsrc, gulpfile.js, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/widgets/carsController.js, src/assets/javascripts/angular/directives/bcSectionsTableDirective.js, src/assets/javascripts/angular/directives/truncateDirective.js, src/assets/javascripts/angular/factories/campusLinksFactory.js, src/assets/javascripts/angular/factories/myClassesFactory.js, src/assets/javascripts/angular/services/updatedFeedsService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5517
=> CLC-5517 - Enable jscs - disallowMultipleSpaces rule

src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-4752
=> CLC-4752 Remove 'Select' from headers in Create a Course Site

src/assets/javascripts/angular/controllers/widgets/textbookController.js, src/assets/javascripts/angular/services/academicsService.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5515
=> CLC-5515 Do not request textbooks if no primary sections are available

src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-5127
Follow up from #3994
=> SISRP-5127 - Dev/Implement Front-End T&C page with dummy data

spec/models/webcast/course_media_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5531
Spec was commented out in #3816
=> CLC-5531, Webcast: bring back recordingStartUTC spec

README.md, gulpfile.js, package.json
https://jira.berkeley.edu/browse/SISRP-4846
https://jira.ets.berkeley.edu/jira/browse/CLC-5522
=> SISRP-4846 - Implemented Browsersync

spec/models/cal1card/my_cal1card_spec.rb
https://jira.berkeley.edu/browse/SISRP-4444
=> SISRP-4444 - Revise my_cal1card_spec to current spec style

app/controllers/ping_controller.rb, spec/controllers/ping_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-4446
=> SISRP-4446 - Write spec to cover ping_controller

spec/controllers/photo_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-4447
=> SISRP-4447 - Write spec to cover PhotoController

config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-5551
New depts: "A,RESEC", "ENE,RES", ENVECON, ESPM, NUSCTX, PLANTBI
=> CLC-5551, departments jump on the OEC train in Fall 2015

app/models/finaid/my_fin_aid.rb, fixtures/xml/finaid_11667051_2013.xml
https://jira.ets.berkeley.edu/jira/browse/CLC-5543
Also include UID in log messages.
=> CLC-5543 Handle FinAid alert category CAL

app/models/ets_blog/rss_proxy.rb, spec/models/ets_blog/release_notes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5566
Good old fashioned do-it-and-immediately-forget-it bug...
=> CLC-5566 Really seriously remove trailing "read more" from release note

app/models/canvas/external_tools.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5571
Continuing to save #4014 from itself.
=> CLC-5571 Use correct PUT endpoint for Canvas::ExternalTools updates

src/assets/javascripts/angular/calcentral.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5557
Note: Looks like we were never really using it anywhere
=> CLC-5557 - JS: Remove calcentral from the global namespace

app/models/my_academics/telebears.rb, fixtures/xml/bearfacts_telebears_99999999_FT.xml, spec/models/my_academics/telebears_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5567
=> CLC-5567 - Do not show empty "Phase I" display for Tele-BEARS

app/models/canvas/sis_import.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5572
=> CLC-5572 Expect unwrapped response from Canvas::SisImport POST

src/assets/javascripts/angular/directives/amountDirective.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5573
=> CLC-5573 - Make coloring optional for the amounts

public/dummy/json/finaid_year.json, src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/stylesheets/_text.scss, src/assets/templates/widgets/finaid_coa.html, src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-5145
=> SISRP-5145 - Dev/Implement Front-End: Cost of Attendance Card

lib/errors/proxy_error.rb, lib/proxies/response_wrapper.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5534
=> CLC-5534 Allow ProxyError to speak for itself

app/models/canvas/sis_course.rb, app/models/canvas_csv/provide_course_site.rb, app/models/canvas_lti/project_provision.rb, spec/models/canvas/sis_course_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5540
=> CLC-5540 Treat Canvas::SisCourse requests as existence checks

app/models/canvas_csv/provide_course_site.rb, spec/models/canvas_csv/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5529
=> CLC-5529 Discourage tampering with the default section of a course site

src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_course_manage_official_sections.scss, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5368
=> CLC-5368 Prevent button text wrapping in Official Sections tool

app/models/oec/biology_post_processor.rb, app/models/oec/courses_group.rb, app/models/oec/csv.rb, app/models/oec/dept_confirmed_data.rb
https://jira.ets.berkeley.edu/jira/browse/OEC-657
=> OEC-657 Informatively report bad characters in CSV files

spec/features/google_badges_url_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5577
Update the mechanics of Google login; usual spec syntax cleanup.
=> CLC-5577 Fix failing Capybara test for Google Calendar links

app/models/canvas/existence_check.rb, app/models/canvas_csv/provide_course_site.rb, spec/models/canvas_csv/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5576
=> CLC-5576 Add course site creator to existing section rather than new one

app/models/campus_solutions/address.rb, app/models/campus_solutions/aid_years.rb, app/models/campus_solutions/awards.rb, app/models/campus_solutions/budget.rb, app/models/campus_solutions/direct_proxy.rb, app/models/campus_solutions/financial_data.rb, app/models/campus_solutions/integration_hub_proxy.rb, app/models/campus_solutions/my_address.rb, app/models/campus_solutions/posting_proxy.rb, app/models/campus_solutions/terms_and_conditions.rb, config/settings.yml, spec/controllers/campus_solutions_controller_spec.rb, spec/models/campus_solutions/address_spec.rb, spec/models/campus_solutions/terms_and_conditions_spec.rb
https://jira.berkeley.edu/browse/SISRP-5147
and https://jira.berkeley.edu/browse/SISRP-5148
and https://jira.berkeley.edu/browse/SISRP-5164
The COA API works and is available in CalCentral as /api/campus_solutions/financial_data?aid_year=2016
The T&C GET API works and is available in CalCentral as /api/campus_solutions/aid_years
The Title IV and Terms & Conditions POST APIs are still broken in Campus Solutions level -- no matter what params I enter it says  "OnRequest could not complete".
=> SISRP-5147 Run T&C and COA GET APIs through the integration hub

app/controllers/user_api_controller.rb, public/dummy/json/status.json, public/dummy/json/status_loggedout.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5579
=> CLC-5579 - CamelCase the keys on the 'features' property on the my status api

app/controllers/application_controller.rb, app/controllers/canvas_lti_controller.rb, app/controllers/sessions_controller.rb, app/policies/authentication_state.rb, app/views/canvas_lti/lti_course_add_user.xml.erb, app/views/canvas_lti/lti_course_grade_export.xml.erb, app/views/canvas_lti/lti_course_manage_official_sections.xml.erb, app/views/canvas_lti/lti_course_mediacasts.xml.erb, app/views/canvas_lti/lti_roster_photos.xml.erb, app/views/canvas_lti/lti_site_creation.xml.erb, app/views/canvas_lti/lti_site_mailing_lists.xml.erb, app/views/canvas_lti/lti_user_provision.xml.erb, spec/controllers/canvas_lti_controller_spec.rb, spec/policies/authentication_state_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-4449
=> CLC-4449 Handle masquerade state in LTI authentication

spec/ui_selenium/my_academics_data_course_captures_spec.rb, spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/my_academics_data_webcasts_spec.rb, spec/ui_selenium/pages/my_academics_class_page.rb, spec/ui_selenium/pages/my_academics_profile_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5584
Fix academic profile test, in light of https://jira.ets.berkeley.edu/jira/browse/CLC-5584.  Also change "webcast" references to "course capture".
=> CLC-5584: fix QA profile and course capture specs

app/models/canvas/external_tools.rb, app/models/canvas/proxy.rb, app/models/canvas/report/base.rb, app/models/canvas/sis_import.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5587
=> CLC-5587 Standardize response for raw_request in Canvas proxies

gulpfile.js, src/assets/javascripts/index.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5545
=> CLC-5545 - Check whether watchify would be able to look for newly added files

app/models/up_next/my_up_next.rb, spec/models/up_next/my_up_next_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5591
=> CLC-5591 Up Next: fall back to email address when display name is not available

app/models/campus_solutions/financial_aid_data.rb
https://jira.berkeley.edu/browse/SISRP-5164
Requires a settings change on calcentral-sis-dev once merged.
=> SISRP-5164 Use the new UC_FA_FINANCIAL_AID_DATA endpoint

app/models/up_next/my_up_next.rb, spec/models/up_next/my_up_next_spec.rb
QA version of #4051.
https://jira.ets.berkeley.edu/jira/browse/CLC-5591
=> [QA] CLC-5591 Up Next: fall back to email address when display name is not available

app/models/canvas_lti/webcast_lti_refresh.rb, spec/models/canvas_lti/webcast_lti_refresh_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5599
=> CLC-5599 Put WebcastLtiRefresh in correct CanvasLti module

app/models/canvas_lti/webcast_lti_refresh.rb, spec/models/canvas_lti/webcast_lti_refresh_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5599
QA version of #4058.
=> [QA] CLC-5599 Put WebcastLtiRefresh in correct CanvasLti module

fixtures/xml/campus_solutions/financial_aid_data.xml, src/assets/javascripts/angular/controllers/widgets/finaid/finaidFundingSourcesController.js, src/assets/javascripts/angular/directives/campusSolutionLinkDirective.js, src/assets/templates/widgets/finaid_funding_sources.html
https://jira.berkeley.edu/browse/SISRP-6156
=> SISRP-6156 - Add ucFrom functionality as a directive

fixtures/xml/campus_solutions/financial_aid_data.xml, src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/stylesheets/_base.scss, src/assets/stylesheets/_finaid_summary.scss, src/assets/templates/widgets/finaid_funding_sources.html, src/assets/templates/widgets/finaid_summary.html, src/assets/templates/widgets/finaid_summary_item.html
https://jira.berkeley.edu/browse/SISRP-5141
=> SISRP-5141 - Dev/Implement Front-End: Aid Summary Card

app/models/ets_blog/rss_proxy.rb, config/settings.yml, fixtures/xml/service_alerts_feed_single.xml, spec/models/ets_blog/service_alerts_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5613
- Point to new locations
- Deal with single-item feeds
=> CLC-5613 CLC-5612 Fix new Release Notes / Alerts feeds

app/models/campus_solutions/aid_years.rb, app/models/campus_solutions/financial_aid_data.rb, app/models/campus_solutions/terms_and_conditions.rb, app/models/campus_solutions/title4.rb, fixtures/xml/campus_solutions/financial_aid_data.xml, src/assets/javascripts/angular/controllers/pages/finaidController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidApprovalsController.js, src/assets/javascripts/angular/directives/finaidPermissionsDirective.js, src/assets/javascripts/angular/factories/finaidFactory.js, src/assets/stylesheets/_finaid_summary.scss, src/assets/templates/directives/finaid_permissions.html, src/assets/templates/finaid.html, src/assets/templates/widgets/finaid_approvals.html, src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-5129
Also fixes:
* POST for both T4 and T&C
* Add labels to the finaid summary card
* Use the same static EmplId everywhere
* Update COA with new data
* Secondary blue color in finaid summary
=> SISRP-5129 - Dev/Implement Front-End: Title IV Card

app/models/google_apps/drive.rb, app/models/google_apps/drive_list.rb, spec/models/google_apps/drive_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5639
A little cleanup while reviewing existing code. No logic added here.
=> CLC-5639, rspec 3 sytnax for existing GoogleApps::DriveList code

app/models/my_badges/merged.rb, spec/controllers/my_badges_controller_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/4071
Please do not merge until alert visibility has been confirmed on Dev. Thanks!
=> QA CLC-5613 Ugly temporary fix for our double-alerts-feed marquee

src/assets/javascripts/angular/directives/accessibleFocusDirective.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5649
=> CLC-5649 - Add an option to dynamically disable the ccAccessibleFocusDirective

src/assets/javascripts/angular/controllers/pages/profileController.js, src/assets/javascripts/angular/controllers/widgets/profile/bConnectedController.js, src/assets/templates/widgets/profile/bconnected.html, src/assets/templates/widgets/profile/bconnected_service_loop.html
https://jira.berkeley.edu/browse/SISRP-5790
=> SISRP-5790 - Front End Dev: Alerts and Notifications Tab - bConnected Card

src/assets/javascripts/angular/controllers/pages/campusController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5656
=> CLC-5656 - JS error when you go to /campus unauthenticated

spec/models/campus_solutions/country_spec.rb
https://jira.berkeley.edu/browse/SISRP-5405
=> SISRP-5405 Ignore failing test until SISRP-6399 is fixed

app/models/google_apps/drive_manager.rb, spec/models/google_apps/drive_manager_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5643
DO NOT MERGE until Bamboo passes: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT-239
Includes:
* get_items_in_folder() and a more flexible find_items()
* specs on DriveManager
* trash_item(id) method
=> CLC-5643, testext on GoogleApps::DriveManager with trash() method added

db/developer-seed-data.sql, spec/models/oec/course_code_spec.rb
Please do not merge until Bamboo checks out: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPT139-14
=> CLC-5620 Really honestly fix Bamboo failures

public/dummy/json/financial_aid_data.json, src/assets/stylesheets/calcentral.scss, src/assets/stylesheets/finaid_coa.scss, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-6502
=> SISRP-6502 - COA - Show budget item totals

src/assets/javascripts/angular/directives/datePickerDirective.js, src/assets/stylesheets/_datepicker.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5582
=> CLC-5582 - Use theming option in pikaday instead of overwriting the CSS ourselves

app/models/campus_solutions/address.rb, app/models/campus_solutions/email.rb, app/models/campus_solutions/emergency_contact.rb, app/models/campus_solutions/language_post.rb, app/models/campus_solutions/person_name.rb, app/models/campus_solutions/phone.rb, app/models/campus_solutions/posting_proxy.rb, app/models/campus_solutions/proxy.rb, app/models/campus_solutions/terms_and_conditions.rb, app/models/campus_solutions/title4.rb, app/models/campus_solutions/work_experience.rb, spec/models/campus_solutions/address_spec.rb, spec/models/campus_solutions/email_spec.rb, spec/models/campus_solutions/emergency_contact_spec.rb, spec/models/campus_solutions/language_post_spec.rb, spec/models/campus_solutions/person_name_spec.rb, spec/models/campus_solutions/phone_spec.rb, spec/models/campus_solutions/terms_and_conditions_spec.rb, spec/models/campus_solutions/title4_spec.rb, spec/models/campus_solutions/work_experience_spec.rb, spec/support/campus_solutions_helper_module.rb
https://jira.berkeley.edu/browse/SISRP-6542
=> SISRP-6542 Set statusCode to 400 and errored to true on user errors

fixtures/json/person_edo.json, spec/models/hub_edos/person_spec.rb, src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js, src/assets/javascripts/angular/controllers/widgets/profile/profileEmailController.js, src/assets/javascripts/angular/controllers/widgets/profile/profilePhoneController.js
https://jira.berkeley.edu/browse/SISRP-5405
=> SISRP-5405 Update person EDO dummy JSON

public/canvas/canvas-customization.js, public/json/campuslinks.json, public/maintenance/index_emergency.html, public/maintenance/index_maintenance.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5103
=> CLC-5103 Adieux, bSpace

app/controllers/my_campus_links_controller.rb, config/routes.rb, public/json/campuslinks.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5666
https://jira.ets.berkeley.edu/jira/browse/CLC-3212
https://jira.ets.berkeley.edu/jira/browse/CLC-5586
https://jira.ets.berkeley.edu/jira/browse/CLC-5673
=> CLC-5666 et al - Make it easier to update Campus Links; update them

src/assets/javascripts/angular/controllers/widgets/profile/profileEmailController.js, src/assets/templates/widgets/profile/contact.html
https://jira.berkeley.edu/browse/SISRP-5399
=> SISRP-5399 - Front End Dev: Profile Tab - Basic Information Card

app/models/canvas_lti/public_authorizer.rb, spec/models/canvas_lti/public_authorizer_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5621
If this tests out, I'll create a QA PR.
=> CLC-5621 Let instructors who are not official staff create course sites

app/models/oec/courses_import_task.rb, spec/models/oec/courses_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5631
=> CLC-5631 Oec: prepopulate dept_form for non-crosslisted courses

app/models/oec/courses_import_task.rb, app/models/oec/task.rb, app/models/oec/term_setup_task.rb, spec/models/oec/courses_import_task_spec.rb, spec/models/oec/term_setup_task_spec.rb, spec/support/oec_spec_helper.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5680
=> CLC-5680 Oec: Convert CSVs to Google Sheets on Drive upload

config/settings.yml, spec/models/google_apps/credential_store_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5683
Config tweak and associated spec. We hope this will become a non-issue when OEC has a dedicated SPA account in qa.
=> CLC-5683, make sure oec scope includes all of default scope

app/models/oec/courses_import_task.rb, fixtures/oec/courses_for_dept_ANTHRO.json, fixtures/oec/courses_for_dept_MATH.json, fixtures/oec/courses_for_dept_POL_SCI.json, fixtures/oec/courses_for_dept_STAT.json, spec/models/oec/courses_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5624
=> CLC-5624 OEC: Omit supervisory instructor_func '3'

spec/ui_selenium/my_academics_data_course_captures_spec.rb, spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/my_academics_data_teaching_spec.rb, spec/ui_selenium/my_dashboard_data_classes_spec.rb, spec/ui_selenium/pages/api_my_academics_page.rb, spec/ui_selenium/pages/api_my_academics_page_semesters.rb, spec/ui_selenium/user_authentication_spec.rb
Includes the following:
* Fix expected course capture “report a problem” link
* Fix My Classes test expectations for multiple primary section courses and for wait lists
* Cutting down some of the bloated academics API page object, including improving method names.  Hopefully slightly easier for QA to maintain now.
=> CLC-5658: Selenium test fixes

spec/models/campus_solutions/email_spec.rb
https://jira.berkeley.edu/browse/SISRP-6732
Should fix the Bamboo thrashing.
=> SISRP-6732 ignore another failing CS testext

fixtures/xml/campus_solutions/financial_aid_data.xml
https://jira.berkeley.edu/browse/SISRP-6734
=> SISRP-6734 - Update mock financial_aid_data.xml

app/models/campus_solutions/emergency_contact.rb, app/models/campus_solutions/financial_aid_data.rb, fixtures/xml/campus_solutions/financial_aid_data.xml, spec/models/campus_solutions/address_spec.rb, spec/models/campus_solutions/email_spec.rb, spec/models/campus_solutions/emergency_contact_spec.rb, spec/models/campus_solutions/financial_aid_data_spec.rb, spec/models/campus_solutions/phone_spec.rb
https://jira.berkeley.edu/browse/SISRP-6734
https://jira.berkeley.edu/browse/SISRP-6592
Fixing an assortment of test failures in email, financial aid data, and emergency contact. 
Best to wait for green Bamboo on this one! https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPCHRIS128-4/test
=> SISRP-6592 and SISRP-6734 - fixing various test failures

app/models/campus_solutions/posting_proxy.rb, spec/models/campus_solutions/address_spec.rb, spec/models/campus_solutions/email_spec.rb, spec/models/campus_solutions/emergency_contact_spec.rb, spec/models/campus_solutions/language_post_spec.rb, spec/models/campus_solutions/person_name_spec.rb, spec/models/campus_solutions/phone_spec.rb, spec/models/campus_solutions/terms_and_conditions_spec.rb, spec/models/campus_solutions/work_experience_spec.rb
https://jira.berkeley.edu/browse/SISRP-6809?filter=-1
=> SISRP-6809 Always send required fields to CS

app/models/canvas/course_user.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5702
https://jira.ets.berkeley.edu/jira/browse/CLC-5705
=> CLC-5702 CLC-5705 Add Lead TA and Reader roles to Canvas course policy

app/models/campus_solutions/aid_years.rb, fixtures/xml/campus_solutions/aid_years.xml, spec/models/campus_solutions/aid_years_spec.rb
https://jira.berkeley.edu/browse/SISRP-6802
=> SISRP-6802 - Use uppercase for the UC_FA_GET_T_C feed

app/controllers/hub_edo_controller.rb, app/models/hub_edos/my_student.rb, app/models/hub_edos/student.rb, config/routes.rb, fixtures/json/student_edo.json, spec/controllers/hub_edo_controller_spec.rb, spec/models/hub_edos/student_spec.rb
https://jira.berkeley.edu/browse/SISRP-6866
=> SISRP-6866 Implement mock API for Student EDO

app/models/oec/course_instructors.rb, app/models/oec/course_supervisors.rb, app/models/oec/courses.rb, app/models/oec/courses_import_task.rb, app/models/oec/instructors.rb, app/models/oec/supervisors.rb, app/models/oec/worksheet.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5729
=> CLC-5729 Rename Oec::CsvExport to Oec::Worksheet

app/models/campus_solutions/my_address.rb, app/models/campus_solutions/my_email.rb, app/models/campus_solutions/my_emergency_contact.rb, app/models/campus_solutions/my_language_post.rb, app/models/campus_solutions/my_person_name.rb, app/models/campus_solutions/my_phone.rb, app/models/campus_solutions/my_work_experience.rb, app/models/campus_solutions/person_data_expiry.rb
https://jira.berkeley.edu/browse/SISRP-6803
=> SISRP-6803 Expire Person and Student EDO when posting person data

app/models/oec/courses_import_task.rb, app/models/oec/report_diff_task.rb, app/models/oec/task.rb, app/models/oec/term_setup_task.rb, lib/tasks/oec.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-5723
Includes:
* proposed change to oec.rake
* refactoring on 'opts' hash use in Oec::Task subclasses
* skeleton of ReportDiffTask
=> CLC-5723, add ReportDiffTask to rake oec:import_courses operation set

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5735
Obviously want to wait for Travis-CI's verdict before merging!
=> CLC-5735 Keep jshint at 2.8.0 until latedef regression is worked out

config/settings/development.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-5665
=> CLC-5530 Remove a few unnecessary development.yml settings

spec/models/campus_solutions/person_name_spec.rb
https://jira.berkeley.edu/browse/SISRP-6950
=> SISRP-6950 Un-ignore test that CS devs have fixed

spec/models/google_apps/sheets_manager_spec.rb
Follow up to #4163.
https://jira.ets.berkeley.edu/jira/browse/CLC-5737
=> CLC-5737 Add now-required dept_code parameter to make Bamboo happy

.scss-lint.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-5662
=> CLC-5662 - SCSS Lint runs slow locally

app/models/oec/remote_drive.rb, app/models/oec/report_diff_task.rb, spec/models/oec/remote_drive_spec.rb, spec/models/oec/report_diff_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5719
Added spec to verify find_dept_courses_spreadsheet(). For the moment, we verify 'should return nil'.
=> CLC-5719, remote_drive gets find_dept_courses_spreadsheet and spec

src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/finaid.html, src/assets/templates/profile.html, src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-6731
=> SISRP-6731 - Use CS finaid & profile feature flag in CalCentral front-end

spec/models/ets_blog/alerts_spec.rb, spec/models/ets_blog/release_notes_spec.rb, spec/models/ets_blog/service_alerts_spec.rb, spec/support/ets_blog_shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-4445
=> SISRP-4445 Revise the specs in ets_blog to conform to current code style

src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/basic_student_id.html
https://jira.berkeley.edu/browse/SISRP-7293
Also fixes an issue with duplicate borders.
=> SISRP-7293 - Don't show the student ID in the UI when it's not available.

spec/models/ets_blog/release_notes_spec.rb
https://jira.berkeley.edu/browse/SISRP-4445
=> SISRP-4445 Revise ets_blog specs to current style: Fix testext failures

app/controllers/campus_solutions/deposit_controller.rb, app/controllers/campus_solutions/higher_one_url_controller.rb, app/controllers/campus_solutions/sir_response_controller.rb, app/models/campus_solutions/deposit.rb, app/models/campus_solutions/higher_one_url.rb, app/models/campus_solutions/my_deposit.rb, app/models/campus_solutions/my_higher_one_url.rb, app/models/campus_solutions/my_sir_response.rb, app/models/campus_solutions/sir_response.rb, config/routes.rb, config/settings.yml, fixtures/xml/campus_solutions/deposit.xml, fixtures/xml/campus_solutions/higher_one_url.xml, fixtures/xml/campus_solutions/sir_response.xml, spec/controllers/campus_solutions/deposit_controller_spec.rb, spec/controllers/campus_solutions/higher_one_url_controller_spec.rb, spec/controllers/campus_solutions/sir_response_controller_spec.rb, spec/models/campus_solutions/deposit_spec.rb, spec/models/campus_solutions/higher_one_url_spec.rb, spec/models/campus_solutions/sir_response_spec.rb
https://jira.berkeley.edu/browse/SISRP-7269
New CalCentral endpoints:
```
GET /api/campus_solutions/deposit?adm_appl_nbr=1234
GET /api/campus_solutions/higher_one_url
POST /api/campus_solutions/sir_response
```
The SIR Response POST isn't working on the CS end yet.
=> SISRP-7269 Implement more onboarding proxies

app/models/oec/remote_drive.rb, spec/models/oec/remote_drive_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5719
Verify remote_drive with real Google API calls. Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT68-1
=> CLC-5719, remote_drive_spec with #real Google API calls

app/models/oec/report_diff_task.rb, app/models/oec/sis_import_sheet.rb, app/models/oec/sis_import_task.rb, app/models/oec/task.rb, app/models/oec/worksheet.rb, spec/models/google_apps/sheets_manager_spec.rb, spec/models/oec/remote_drive_spec.rb, spec/models/oec/sis_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5726
Follow-up to comments on #4176.
=> CLC-5726 Follow-up: give Oec::Worksheet a default export directory

spec/models/campus_solutions/ethnicity_delete_spec.rb, spec/models/campus_solutions/ethnicity_post_spec.rb, spec/models/campus_solutions/work_experience_spec.rb
https://jira.berkeley.edu/browse/SISRP-7329
https://jira.berkeley.edu/browse/SISRP-7330
=> SISRP-7329 Un-ignore test now that Babu fixed Work Experience API

app/models/google_apps/drive_manager.rb, spec/models/google_apps/drive_manager_spec.rb, spec/models/google_apps/sheets_manager_spec.rb, spec/models/oec/remote_drive_spec.rb
* option to permanently delete in trash_item
* fix empty_trash
* simplify error handling
Bamboo is chewing on this change: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT69-1
=> CLC-5718, fix empty_trash; option to permanently delete in trash_item

app/models/canvas_csv/base.rb, app/models/canvas_csv/maintain_users.rb, fixtures/csv/Canvas_provisioning_report_users_csv.csv, spec/models/canvas_csv/add_new_users_spec.rb, spec/models/canvas_csv/base_spec.rb, spec/models/canvas_csv/maintain_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5601
Slight tweak to @paulkerschen 's last, based on looking at the full production user list.
=> CLC-5601 Import first_name/last_name but compare to Canvas full_name

spec/models/campus_solutions/sir_response_spec.rb
https://jira.berkeley.edu/browse/SISRP-7269
=> SISRP-7269 Unignore and fix test in SirResponse

app/models/google_apps/sheets_manager.rb, app/models/oec/remote_drive.rb, app/models/oec/task.rb
Bamboo is churning: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT71-2
Includes:
* spreadsheets_by_title accepts optional parent_id
* configurable date_time in Task, useful in testing
* more readable (I hope) logging
@paulkerschen  The find_dept_courses_spreadsheet change was reverted
=> CLC-5720, fix find_dept_courses_spreadsheet; optional date_time in Task

app/models/canvas/communication_channels.rb, app/models/canvas_csv/maintain_users.rb, config/settings.yml, config/settings/production.yml, fixtures/json/canvas_communication_channels.json, fixtures/json/canvas_communication_channels_delete.json, spec/models/canvas_csv/maintain_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5191
=> CLC-5191 Mark bCourses user accounts which no longer match a CalNet UID

app/models/canvas_lti/webcast_lti_refresh.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5546
=> CLC-5546 Lower the log level of "nothing to do" messages

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, src/assets/javascripts/angular/controllers/widgets/sir/sirController.js, src/assets/javascripts/angular/controllers/widgets/sir/sirItemController.js, src/assets/javascripts/angular/factories/sirFactory.js, src/assets/stylesheets/_sir_item.scss, src/assets/templates/dashboard.html, src/assets/templates/widgets/sir/sir_item.html
https://jira.berkeley.edu/browse/SISRP-6616
* Test for maybe & LAW
* Test for multiple SIR Cards
* Add SIR behind a feature flag
* Add the program description
* Submit the SIR form
=> SISRP-6616 - Develop Front End: SIR Experiences Card

app/models/oec/report_diff_task.rb, spec/models/oec/report_diff_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5753
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT73-1
Covers all logic described in legacy documentation. See section under "rake oec:diff": https://docs.google.com/document/d/1MAZN5TA39fpRD5zRrUOqafHI1FEKcyqVHnCufpARblw/edit
Plus, we report validation errors found during diff. See CLC-5753 link above.
=> CLC-5720, report_diff_task writes summary to Google Drive

app/models/campus_solutions/sir_response.rb, spec/models/campus_solutions/sir_response_spec.rb
https://jira.berkeley.edu/browse/SISRP-7396
=> SISRP-7396 Change SIR Response POST to new API structure

app/models/canvas_csv/provide_course_site.rb, spec/models/canvas_csv/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5762
EDITORIAL: Too many paths weaving around that course provisioning code!
=> CLC-5762 Fix Create a Course Site use of Teacher role

app/models/canvas_csv/provide_course_site.rb, spec/models/canvas_csv/provide_course_site_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/4203
=> QA CLC-5762 Fix Create a Course Site use of Teacher role

app/models/oec/task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5780
=> CLC-5780, rake oec:sis_import local_write fails if tmp/oec does not exist

app/models/oec/queries.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5782
=> CLC-5782 OEC: Filter get_courses query on section_cancel flag

app/controllers/bootstrap_controller.rb
https://jira.berkeley.edu/browse/SISRP-7708
Example Calls:
```
/dashboard?ucUpdateCache=finaid 
/dashboard?ucUpdateCache=profile
```
=> SISRP-7708 Add URL param that will expire CS cache groups

app/models/oec/publish_task.rb, spec/models/oec/publish_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5790
Basic test coverage on new Oec::Task
=> CLC-5790, rspec for OEC publish_task

app/models/oec/term_setup_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5795
=> CLC-5795 OEC: Fix failure to find previous exports during term setup

app/models/campus_solutions/my_sir_response.rb, config/settings.yml
https://jira.berkeley.edu/browse/SISRP-6621
=> SISRP-6621 Expire Checklist when SIR posting; tweak cache timeouts

lib/tasks/oec.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-5789
Rake task for publish to Explorance (i.e., sftp). This will be another option for cron.
=> CLC-5789, rake task for publish_to_explorance

app/models/oec/task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5801
=> CLC-5801 OEC: Allow underscores to represent spaces in dept names from the command line

config/settings.yml, lib/cache/config.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5796
Also enable logging of the max-exceeded caching error.
=> CLC-5796 Restore caching of Course Capture feed

script/run-oec-task.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5773
This script can run any of the OEC rake tasks, given the proper command line args. See usage info.
=> CLC-5773, script delegates to OEC rake tasks

app/models/oec/publish_task.rb, spec/models/oec/publish_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5790
Support local_write standard on publish_task and remove that arg from spec.
=> CLC-5790, local_write for publish_task and nil check on get export csv

app/controllers/campus_solutions/deposit_controller.rb, spec/controllers/campus_solutions/deposit_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-7728
=> SISRP-7728 Camelize adm_appl_nbr param

src/assets/templates/academics_student_profile.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5805
=> CLC-5805 - Add Show / Hide GPA functionality

app/models/google_apps/sheets_manager.rb, app/models/oec/remote_drive.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5798
=> CLC-5798 OEC: Force plaintext formatting on numeric cells in Google Sheets

app/models/oec/report_diff_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5811
If a row has bad data then log error and move on. If a failure occurs when loading csv then abort!
=> CLC-5811, some errors are NOT fatal in report_diff_task

app/models/campus_solutions/checklist_data_expiry.rb, app/models/campus_solutions/my_sir_response.rb
https://jira.berkeley.edu/browse/SISRP-6621
=> SISRP-6621 Fix broken caching invalidation

app/models/oec/diff_report.rb, app/models/oec/report_diff_task.rb, spec/models/oec/report_diff_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5824
Our course-eval spa account has sample diff, in this new format, in folder: 2014-D/departments
=> CLC-5824, one diff_report to rule them all

app/models/oec/sis_import_task.rb, spec/models/oec/sis_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5820
=> CLC-5820 Generate CROSS_LISTED_NAME even when cross-listing is filtered out

spec/controllers/oec_tasks_controller_spec.rb, spec/models/oec/api_task_wrapper_spec.rb, spec/policies/authentication_state_policy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5774
Specs to match #4252.
=> CLC-5774 OEC: specs for API endpoints and task wrappers

app/controllers/oec_tasks_controller.rb, app/models/oec/api_task_wrapper.rb, spec/controllers/oec_tasks_controller_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/oecController.js, src/assets/javascripts/angular/factories/oecFactory.js, src/assets/stylesheets/_oec.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/oec.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5827
Having the API serve up task descriptions helps make the whole thing a little less opaque. Note that ExportTask is advertised as a validation task, while PublishTask is advertised as an export task. https://jira.ets.berkeley.edu/jira/browse/CLC-5833 will bring these into sync.
=> CLC-5827 Front end for OEC control panel

app/models/oec/export_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5830
=> CLC-5830 OEC: ExportTask merges in previous course supervisors if present

app/models/oec/term_setup_task.rb, spec/models/oec/term_setup_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5829
=> CLC-5829 OEC: TermSetupTask should copy in template for confirmation sheets

src/assets/templates/oec.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5827
Addressing @christianv's comments on #4255.
=> CLC-5827 OEC Control Panel: match labels to selects

app/models/oec/courses.rb, app/models/oec/export_task.rb, spec/models/oec/export_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5832
=> CLC-5832 OEC: Run additional validations on export

public/json/campuslinks.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5778
=> CLC-5778 Emergency Preparedness link changed

script/report-lti-usage.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5341
Missed this little file in the previous PR...
=> CLC-5341 Shell script to report LTI app visibility

app/models/oec/courses.rb, app/models/oec/worksheet.rb, spec/models/oec/export_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5836
=> CLC-5836 OEC: Normalize date formatting on CSV import

app/models/hub_edos/user_attributes.rb, app/models/user/api.rb
https://jira.berkeley.edu/browse/SISRP-7950
=> SISRP-7950 Fall back on Campus Oracle for non-student data

app/models/oec/sis_import_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5831
Call it once.
=> CLC-5831, call default_term_dates only once

app/models/canvas_csv/turnitin_reporter.rb, config/settings.yml, spec/models/canvas_csv/turnitin_reporter_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5528
=> CLC-5528 No more special TurnItIn bCourses subaccount

app/models/campus_solutions/address.rb, fixtures/xml/campus_solutions/address.xml, spec/models/campus_solutions/address_spec.rb
https://jira.berkeley.edu/browse/SISRP-7959
=> SISRP-7959 Use the new all-purpose address post endpoint

app/models/campus_solutions/pending_messages.rb, app/models/my_activities/campus_solutions_messages.rb, app/models/my_activities/merged.rb, fixtures/xml/campus_solutions/pending_messages.xml, spec/models/campus_solutions/pending_messages_spec.rb, spec/models/my_activities/campus_solutions_messages_spec.rb
https://jira.berkeley.edu/browse/SISRP-6620
=> SISRP-6620 Backend for CS notifications

app/models/hub_edos/user_attributes.rb, fixtures/json/student_api_via_hub.json
https://jira.berkeley.edu/browse/SISRP-7977
=> SISRP-7977 Use preferred name if available, otherwise fall back to primary name

app/models/oec/term_setup_task.rb, spec/models/oec/term_setup_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5838
=> CLC-5838 OEC: Add term dates to overrides/courses on term setup

src/assets/javascripts/angular/controllers/widgets/profile/profileEmailController.js, src/assets/javascripts/angular/controllers/widgets/profile/profilePhoneController.js, src/assets/javascripts/angular/factories/profileFactory.js, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/profile/contact_address.html, src/assets/templates/widgets/profile/contact_phone.html, src/assets/templates/widgets/profile/contact_phone_editor.html
https://jira.berkeley.edu/browse/SISRP-5400
=> SISRP-5400 - Front End Dev: Profile Tab - Contact Information Card

app/models/oec/term_setup_task.rb, spec/models/oec/term_setup_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5849
=> CLC-5849 OEC: Do not create course_instructors override sheet on term setup

app/models/oec/api_task_wrapper.rb, app/models/oec/task.rb, app/models/oec/term_setup_task.rb, spec/models/oec/sis_import_task_spec.rb, spec/models/oec/term_setup_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5847
Search and replace don't fail me now...
=> CLC-5847 OEC: Rename 'reports' Drive folder to 'logs'

app/models/oec/sis_import_task.rb, app/models/oec/task.rb, fixtures/oec/overrides_instructors.csv, spec/models/oec/sis_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5831
I wrangled a bit with rewriting spec. I generalized and renamed the merge_overrides_data() method.
=> CLC-5831, give overrides/instructors precedent over SIS

app/controllers/campus_solutions/campus_solutions_controller.rb, config/routes.rb, spec/controllers/campus_solutions/address_controller_spec.rb, spec/controllers/campus_solutions/email_controller_spec.rb, spec/controllers/campus_solutions/emergency_contact_controller_spec.rb, spec/controllers/campus_solutions/ethnicity_controller_spec.rb, spec/controllers/campus_solutions/language_controller_spec.rb, spec/controllers/campus_solutions/person_name_controller_spec.rb, spec/controllers/campus_solutions/phone_controller_spec.rb, src/assets/javascripts/angular/configuration/securityConfiguration.js, src/assets/javascripts/angular/controllers/widgets/profile/profilePhoneController.js, src/assets/javascripts/angular/factories/profileFactory.js
https://jira.berkeley.edu/browse/SISRP-8139
There are new paths to all delete endpoints -- look in routes.rb for their structure.
=> SISRP-8139 Make phone and other deletes work

app/models/canvas/authorization_configs.rb, app/models/canvas_lti/reconfigure_authorization_configs.rb, spec/models/canvas_lti/reconfigure_authorization_configs_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5828
=> CLC-5828 Change to Canvas Authentication API

app/models/hub_edos/user_attributes.rb
https://jira.berkeley.edu/browse/SISRP-8146
=> SISRP-8146 Don't barf on missing email[:type]

app/models/campus_solutions/address_label.rb, spec/models/campus_solutions/address_label_spec.rb
https://jira.berkeley.edu/browse/SISRP-8148
=> SISRP-8148 Camelize the field field

app/models/my_tasks/sis_tasks.rb
https://jira.berkeley.edu/browse/SISRP-8152
=> SISRP-8152 - Tasks display is not complete

app/models/oec/publish_task.rb, app/models/oec/task.rb, app/models/oec/worksheet.rb, config/settings.yml, spec/models/oec/publish_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5864
I swap in ```Pathname.new``` because it plays well with existing code like ```LOG_DIRECTORY.join ...```
=> CLC-5864, configurable local_write; replace Rails.root

app/models/my_activities/campus_solutions_messages.rb, app/models/my_classes/merged.rb, app/models/my_groups/merged.rb
https://jira.berkeley.edu/browse/SISRP-8276
=> SISRP-8276 Fix activities feed

app/models/hub_edos/student.rb, spec/models/hub_edos/student_spec.rb
https://jira.berkeley.edu/browse/SISRP-8224
=> SISRP-8224 Convert some keys of the addresses we get from Student API

lib/tasks/canvas.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-5828
=> CLC-5828 Fix bad variable name in Rake task

app/models/slate/checklist.rb, config/settings.yml, spec/models/my_tasks/my_tasks_spec.rb, spec/models/slate/checklist_spec.rb
https://jira.berkeley.edu/browse/SISRP-8364
=> SISRP-8364 Put Slate checklist behind feature flag

config/settings.yml
=> NOJIRA Remove obsolete settings entries

app/models/oec/sis_import_task.rb, spec/models/oec/sis_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5876
=> CLC-5876 OEC: Do not append override rows that match no import rows

app/models/campus_oracle/queries.rb, app/models/campus_oracle/user_courses/transcripts.rb, spec/models/campus_oracle/user_courses/transcripts_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5872
=> CLC-5872 Include transfer credits in My Academics Semesters history

script/run-oec-task.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5877
Fixed name of generated log file, too.
=> CLC-5877, Usage text of run-oec-task.sh needs edit

src/assets/templates/widgets/activity.html, src/assets/templates/widgets/activity_list.html
https://jira.berkeley.edu/browse/SISRP-8374
=> SISRP-8374 - Calcentral Dashboard shows "Recent Activity" instead of "Notifications"

src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-8426
=> SISRP-8426 - FA Net Cost Card - Should display message if student not configured for access

src/assets/templates/finaid.html, src/assets/templates/widgets/finaid_approvals.html
https://jira.berkeley.edu/browse/SISRP-8427
=> SISRP-8427 - Layout bug when you're accepting T&C & T4

app/models/oec/publish_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5864
=> CLC-5864 OEC: Use absolute paths inside SFTP batchfile

app/models/oec/merge_confirmation_sheets_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5879
=> CLC-5879 OEC: Improve logging in MergeConfirmationSheetsTask

src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-8444
=> SISRP-8444 - Calcentral Dashboard shows "To Do" instead of "Tasks"

spec/models/canvas_csv/term_enrollments_spec.rb
Granted, it's only one spec, but the title can serve as a PSA. This was causing the failures in https://jira.ets.berkeley.edu/jira/browse/CLC-5873 whenever it happened to be spec that got first dibs at Timeshifter.
=> CLC-5873 Do not stub Time.now in specs

app/models/canvas_csv/term_enrollments.rb, spec/models/canvas_csv/term_enrollments_spec.rb
See https://jira.ets.berkeley.edu/jira/browse/CLC-5890 for the motivation, and for the reason that a passing Travis at this hour is particularly important.
=> CLC-5890 Use Rails timezone across CanvasCsv::TermEnrollments

app/models/oec/merged_sheet_validation.rb, app/models/oec/task.rb, src/assets/stylesheets/_oec.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5880
Also a spacing fix for the status box.
=> CLC-5880 OEC: report validation failure as error

src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-8836
=> SISRP-8836 - Only show profile to students & hide the bConnected card for now in profile

app/models/hub_edos/proxy.rb, app/models/hub_edos/student.rb, fixtures/json/student_api_via_hub.json, spec/models/hub_edos/student_spec.rb
https://jira.berkeley.edu/browse/SISRP-8853
=> SISRP-8853 Call /all on the student API

app/models/my_tasks/sis_tasks.rb
https://jira.berkeley.edu/browse/SISRP-8866
=> SISRP-8866 More fields from CS on the task feed

src/assets/templates/widgets/sir/sir_item.html
https://jira.berkeley.edu/browse/SISRP-8859
=> SISRP-8859 - Fix "decission"

config/settings.yml, src/assets/javascripts/angular/controllers/widgets/tasksController.js
https://jira.berkeley.edu/browse/SISRP-8854
=> SISRP-8854 - Remove spamChristian

src/assets/javascripts/angular/controllers/widgets/lsAdvisingController.js
https://jira.berkeley.edu/browse/SISRP-8858
=> SISRP-8858 - Remove the temp modifications to lsAdvisingController

app/controllers/bootstrap_controller.rb, app/controllers/campus_solutions/campus_solutions_controller.rb, app/models/campus_solutions/direct_proxy.rb, app/models/campus_solutions/state.rb, app/models/hub_edos/my_person.rb, app/models/hub_edos/user_attributes.rb, app/models/my_tasks/merged.rb
Incorporates several feedback suggestions from @paulkerschen @johncrossman and @raydavis .
=> Mega merge revisions

app/models/hub_edos/student.rb, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/basic_preferred_name.html, src/assets/templates/widgets/profile/demographic_ethnicity.html, src/assets/templates/widgets/profile/demographic_gender.html, src/assets/templates/widgets/profile/demographic_veteran.html, src/assets/templates/widgets/profile/emergency_contact.html, src/assets/templates/widgets/profile/languages_section.html
https://jira.berkeley.edu/browse/SISRP-8847
=> SISRP-8847 - CC Profile - Only show items that are currently production ready

app/controllers/campus_solutions/campus_solutions_controller.rb, config/settings.yml, config/settings/development.yml
https://jira.berkeley.edu/browse/SISRP-8438
=> SISRP-8438 Add feature flag to prevent_acting_as_users_from_posting

src/assets/javascripts/angular/factories/activityFactory.js
https://jira.berkeley.edu/browse/SISRP-8901
=> SISRP-8901 - In Firefox, when returning from Campus Solutions, the Notifications area never completes a refresh and does not display.

src/assets/javascripts/angular/controllers/widgets/sir/sirItemReceivedController.js, src/assets/templates/widgets/finaid_coa.html, src/assets/templates/widgets/finaid_funding_sources.html, src/assets/templates/widgets/finaid_profile.html, src/assets/templates/widgets/sir/sir_item_completed.html
https://jira.berkeley.edu/browse/SISRP-8906
=> SISRP-8906 - sis-master follow up changes

app/models/user/api.rb, spec/models/user/api_spec.rb, spec/models/user/api_with_campus_solutions_enabled_spec.rb
https://jira.berkeley.edu/browse/SISRP-8907
=> SISRP-8907 Add isCampusSolutionsStudent field to user API

app/models/my_activities/campus_solutions_messages.rb, app/models/my_tasks/sis_tasks.rb, spec/models/my_tasks/my_tasks_spec.rb, src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-8866
=> SISRP-8866 - Make update to the tasks API to expose certain CS specific items

spec/models/webcast/merged_spec.rb, spec/models/webcast/recordings_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5898
My in-progress Bamboo build: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT76-1 
Extra cleanup in Bamboo yml while I was applying new SIS configs.
=> CLC-5898, Bamboo yml should use 'webcast-cc-staging', not 'webcast-cc-qa'

app/models/canvas/user_courses.rb, fixtures/json/canvas_courses_page_2.json, spec/models/canvas/user_courses_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5900
If this resolves the issue on dev, I'll follow up with a QA PR, since I assume we'll want to stay ahead of the Canvas API on this one.
=> CLC-5900 Filter out access-restricted or otherwise weird Canvas sites

src/assets/templates/widgets/profile/demographic_ethnicity.html
https://jira.berkeley.edu/browse/SISRP-9321
=> SISRP-9321 - CC Profile - Show ethnicity information

src/assets/templates/widgets/profile/demographic_gender.html
https://jira.berkeley.edu/browse/SISRP-9322
=> SISRP-9322 - CC Profile gender - use genderOfRecord instead of sexAtBirth

src/assets/stylesheets/finaid_coa.scss, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-9352
=> SISRP-9352 - COA Card - Indent budget items in expanded view

src/assets/javascripts/angular/factories/activityFactory.js
https://jira.berkeley.edu/browse/SISRP-9353
=> SISRP-9353 - Title Change for Bunched Messages

src/assets/stylesheets/_text.scss, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-9356
=> SISRP-9356 - COA Card Wording - Fix total titles

src/assets/templates/profile.html, src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-9407
=> SISRP-9407 - Front-end - Add minimal viable fallback for GL3 profile data in CalCentral

app/models/user/api.rb
https://jira.berkeley.edu/browse/SISRP-9407
=> SISRP-9407 Followup - Fallback now alters data for legacy students

app/models/campus_solutions/person_name.rb, src/assets/javascripts/angular/controllers/widgets/profile/basicNameController.js, src/assets/javascripts/angular/controllers/widgets/profile/basicPreferredNameController.js, src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js, src/assets/javascripts/angular/controllers/widgets/profile/profileEmailController.js, src/assets/javascripts/angular/controllers/widgets/profile/profilePhoneController.js, src/assets/javascripts/angular/factories/profileFactory.js, src/assets/javascripts/angular/services/profileService.js, src/assets/templates/widgets/profile/basic_preferred_name.html, src/assets/templates/widgets/profile/basic_preferred_name_editor.html
https://jira.berkeley.edu/browse/SISRP-9408
=> SISRP-9408 - CC: Implement preferred name editing

app/models/campus_solutions/person_name.rb, spec/models/campus_solutions/name_delete_spec.rb, spec/models/campus_solutions/person_name_spec.rb
https://jira.berkeley.edu/browse/SISRP-8863
=> SISRP-8863 Country name format is always '001'

app/models/my_activities/campus_solutions_messages.rb, spec/models/my_activities/campus_solutions_messages_spec.rb, src/assets/stylesheets/_activities.scss
https://jira.berkeley.edu/browse/SISRP-9422
=> SISRP-9422 - UX Dev: Change link in notifications card to read "Read more" if link goes to CS

src/assets/javascripts/angular/controllers/widgets/profile/basicPreferredNameController.js
https://jira.berkeley.edu/browse/SISRP-8863
=> SISRP-8863 - Followup on TODO in PersonName

app/controllers/hub_edo_controller.rb, app/models/hub_edos/my_work_experience.rb, app/models/hub_edos/work_experience.rb, config/routes.rb, fixtures/json/work_experience.json, spec/controllers/hub_edo_controller_spec.rb, spec/models/hub_edos/work_experience_spec.rb
https://jira.berkeley.edu/browse/SISRP-9429
=> SISRP-9429 Add API for work experience

app/models/berkeley/terms.rb, app/models/google_apps/drive_manager.rb, app/models/google_apps/sheets_manager.rb, app/models/oec/publish_task.rb, app/models/oec/term_setup_task.rb
#4380 was merged to master; here we put same changes to qa branch.
https://jira.ets.berkeley.edu/jira/browse/CLC-5893
https://jira.ets.berkeley.edu/jira/browse/CLC-5909
=> CLC-5893 (qa branch), After OEC publish write files to /exports folder as plain test/csv

app/models/campus_oracle/user_courses/transcripts.rb, app/models/my_academics/semesters.rb, spec/models/campus_oracle/user_courses/transcripts_spec.rb, spec/models/my_academics/semesters_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5901
=> CLC-5901 Show REMOVED transcript lines in My Academics history

app/models/hub_edos/user_attributes.rb, app/models/user/api.rb, spec/models/user/api_with_campus_solutions_enabled_spec.rb
https://jira.berkeley.edu/browse/SISRP-9472
=> SISRP-9472 Base is_campus_solutions_student on the correct field

app/models/campus_solutions/dashboard_url.rb, app/models/my_activities/merged.rb, config/settings.yml, fixtures/xml/campus_solutions/dashboard_url.xml, spec/models/campus_solutions/dashboard_url_spec.rb
https://jira.berkeley.edu/browse/SISRP-9461
=> SISRP-9461 Add link to CS Dashboard in My Activities merged feed

src/assets/templates/widgets/activity.html
https://jira.berkeley.edu/browse/SISRP-9460
=> SISRP-9460 - Front-End Dev: Add link to CS Comms Center to notifications card

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js, src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js, src/assets/javascripts/angular/services/profileService.js, src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/emergency_contact.html
https://jira.berkeley.edu/browse/SISRP-9426
=> SISRP-9426 - Follow up(s) on the emergency contact information

src/assets/templates/widgets/activity.html
https://jira.berkeley.edu/browse/SISRP-9460
=> SISRP-9460 - Fix typo

src/assets/templates/widgets/profile/demographic_veteran.html
https://jira.berkeley.edu/browse/SISRP-9481
=> SISRP-9481 - Veteran status value should read as "none specified" when null value returned

app/models/campus_solutions/checklist_data_expiry.rb
https://jira.berkeley.edu/browse/SISRP-9477
=> SISRP-9477 Expire MyChecklist too

app/models/campus_solutions/sir_response.rb, spec/models/campus_solutions/sir_response_spec.rb
https://jira.berkeley.edu/browse/SISRP-9821
=> SISRP-9821 Post chklstItemCd on SIR Response

src/assets/templates/widgets/profile/demographic_gender.html
https://jira.berkeley.edu/browse/SISRP-9480
=> SISRP-9480 - Label for "gender of record" displays as "gender identity", this is not the correct label

src/assets/javascripts/angular/controllers/widgets/sir/sirItemController.js
https://jira.berkeley.edu/browse/SISRP-9821
=> SISRP-9821 - SIR Post API is updating all checklist items on checklist

app/models/canvas_csv/maintain_users.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5881
Another two issues found via the daily incremental-refresh...
=> CLC-5881 Check for reactivated user accounts; explain what to do with duplicates

src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js, src/assets/templates/widgets/profile/contact_address_editor.html
https://jira.berkeley.edu/browse/SISRP-9453
=> SISRP-9453 - Profile - non-required address field appears to require a selection

spec/models/campus_solutions/country_spec.rb, spec/models/campus_solutions/currency_code_spec.rb, spec/models/campus_solutions/ethnicity_setup_spec.rb, spec/models/campus_solutions/name_type_spec.rb, spec/models/campus_solutions/pending_messages_spec.rb
https://jira.berkeley.edu/browse/SISRP-9878
=> SISRP-9878 Relax some testext tests

src/assets/templates/widgets/profile/contact_phone_editor.html
https://jira.berkeley.edu/browse/SISRP-9884
=> SISRP-9884 - Profile Contact Info - phone number max chars not being validated

app/models/oec/course_instructors.rb, app/models/oec/merged_sheet_validation.rb, spec/models/oec/publish_task_spec.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5915
=> CLC-5915 OEC: Validate consistent instructor assignments across cross-listings

src/assets/templates/widgets/profile/contact_phone.html
https://jira.berkeley.edu/browse/SISRP-9854
=> SISRP-9854 - Profile Contact Info - phone extensions being truncated and only visible in edit mode

src/assets/templates/widgets/activity.html
https://jira.berkeley.edu/browse/SISRP-9856
=> SISRP-9856 - Archive link doesn't have the ucFrom added to it.

app/models/canvas_csv/maintain_users.rb
Local testing of master went OK, so here's the QA version of https://github.com/ets-berkeley-edu/calcentral/pull/4404
=> QA CLC-5881 Check for reactivated user accounts; explain duplicates

app/models/my_academics/semesters.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5928
What I would give for a static analysis tool that says, "Hey genius, this one might be nil too."
=> CLC-5928 Do not attempt to merge transcript terms with no courses

app/models/campus_solutions/posting_proxy.rb, spec/models/campus_solutions/address_spec.rb
https://jira.berkeley.edu/browse/SISRP-9872
=> SISRP-9872 Don't send nulls to CS APIs

src/assets/javascripts/angular/controllers/widgets/sir/sirController.js
https://jira.berkeley.edu/browse/SISRP-9882
=> SISRP-9882 - CC00000006 has a SIR item that's in the checklist but not in the SIR Config

app/models/oec/merged_sheet_validation.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5920
The supervisors sheet was evading validation because it happened already to be in the format we send to Explorance, so was simply getting copied over.
=> CLC-5920 OEC: Validate supervisors sheet before export

app/models/oec/merged_sheet_validation.rb, spec/models/oec/validation_task_spec.rb, spec/support/oec_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5918
=> CLC-5918 OEC: validate DEPT_FORM against participating department names

spec/models/google_apps/sheets_manager_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5916
Follow-up to #4419 just for Bamboo, chugging at https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPT203-1.
=> CLC-5916 OEC: Fix Bamboo failures on newly sorted sheets

app/models/oec/courses.rb, app/models/oec/merged_sheet_validation.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5919
See spec for the complete messages surfaced.
=> CLC-5919 OEC: Improve date validation

app/models/oec/term_setup_task.rb, spec/models/oec/term_setup_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5924
=> CLC-5924 OEC: Carry forward course_instructors from previous term if present

config/settings/development.yml, src/assets/templates/widgets/activity.html
https://jira.berkeley.edu/browse/SISRP-9961
=> SISRP-9961 - Archive Communications link behavior

src/assets/templates/widgets/profile/contact_address_editor.html
https://jira.berkeley.edu/browse/SISRP-9932
=> SISRP-9932 - Profile Contact Info - Save button should be disabled while address inputs are loading

src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/demographic.html, src/assets/templates/widgets/profile/editable_soon.html, src/assets/templates/widgets/profile/emergency.html, src/assets/templates/widgets/profile/languages.html
https://jira.berkeley.edu/browse/SISRP-9893
=> SISRP-9893 - Add "This will be editable in April 2016" to profile cards that aren't editable yet.

src/assets/javascripts/angular/controllers/widgets/profile/demographicVeteranController.js
https://jira.berkeley.edu/browse/SISRP-9972
=> SISRP-9972 - JS Error when a person doesn't have veteran status available

src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js
https://jira.berkeley.edu/browse/SISRP-9937
=> SISRP-9937 - CalCentral API: Sending over a null to the back-end for address POST converts it into bad XML for CS

app/models/campus_solutions/posting_proxy.rb, spec/models/campus_solutions/address_spec.rb
https://jira.berkeley.edu/browse/SISRP-9985
=> SISRP-9985 - 400 Response on the SIR POST API

app/models/hub_edos/proxy.rb, spec/models/my_tasks/my_tasks_spec.rb
https://jira.berkeley.edu/browse/SISRP-9992
=> SISRP-9992 Allow switch from basic auth to app ID/token auth

app/models/my_academics/canvas_sites.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5938
The particular cause of this bug was a Canvas group site associated with entries in both the `:semesters` and `:teachingSemesters` arrays of a student's feed. The code identified the relevant term by its index in the `:semesters` array; attempting to access this index in the `:teachingSemesters` array caused a crash because the arrays were of different lengths.
The fix is to track terms not by index but by slug, which stays consistent between arrays.
=> CLC-5938 MyAcademics::CanvasSites: match terms by slug, not index

app/models/my_academics/canvas_sites.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5938
QA version of #4443.
=> [QA] CLC-5938 MyAcademics::CanvasSites: match terms by slug, not index

spec/support/selenium_helper.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5936
=> CLC-5936: Fix require sequence for QA tests

db/migrate/20151027193159_link_to_campus_solutions_from_my_campus.rb, db/schema.rb, public/json/campuslinks.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5927
=> CLC-5927, My Campus link to Berkeley Campus Solutions

spec/ui_selenium/pages/api_my_fin_aid_page.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5946
=> CLC-5946: fix broken FinAid Selenium test

src/assets/stylesheets/_activities.scss, src/assets/templates/widgets/activity_list.html, src/assets/templates/widgets/activity_list_summary.html
https://jira.berkeley.edu/browse/SISRP-9988
=> SISRP-9988 - Support html in teaser messages in CalCentral?

app/models/hub_edos/student.rb, fixtures/json/student_api_via_hub.json, spec/models/hub_edos/student_spec.rb
https://jira.berkeley.edu/browse/SISRP-10487
=> SISRP-10487 Redact elements with uiControl.code == N

spec/ui_selenium/pages/my_finances_landing_page.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5952
=> CLC-5952: fix FinAid element locator in Selenium tests

src/assets/stylesheets/_tasks.scss, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-10540
=> SISRP-10540 - Provide enough padding bottom when there are no items in unscheduled / completed

app/models/hub_edos/proxy.rb, app/models/hub_edos/student.rb, app/models/hub_edos/work_experience.rb
https://jira.berkeley.edu/browse/SISRP-10583
=> SISRP-10583 Work around hub API's lack of charset header

src/assets/javascripts/angular/controllers/widgets/myClassesController.js, src/assets/javascripts/angular/controllers/widgets/upNextController.js, src/assets/javascripts/angular/factories/activityFactory.js
https://jira.berkeley.edu/browse/SISRP-10567
=> SISRP-10567 - JS errors that show up when going to /dashboard without being logged in

app/controllers/sessions_controller.rb
https://jira.berkeley.edu/browse/SISRP-9421
Adjust the field name based on Brian's change to the CAS assertion. Also up the log level so I can see what's going on better in cc-dev.
=> SISRP-9421 Followup: Change attribute name and log a little more

src/assets/templates/widgets/profile/basic_preferred_name_editor.html
https://jira.berkeley.edu/browse/SISRP-10586
=> SISRP-10586 - Profile - preferred name input truncated after Save

src/assets/javascripts/angular/services/finaidService.js
https://jira.berkeley.edu/browse/SISRP-10527
=> SISRP-10527 - Profile: attempt to save invalid address, and address reverts to a previous version

app/models/hub_edos/proxy.rb
https://jira.berkeley.edu/browse/SISRP-10583
=> SISRP-10583 Followup - force encoding also needed in log statement

app/models/hub_edos/student.rb
https://jira.berkeley.edu/browse/SISRP-10610
=> SISRP-10610 Protect against NoMethodError with nil check

src/assets/javascripts/angular/controllers/widgets/myClassesController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-5955
=> CLC-5955 Fix property name in My Classes JS

app/controllers/campus_solutions/financial_aid_funding_sources_controller.rb, app/models/campus_solutions/financial_aid_funding_sources.rb, app/models/campus_solutions/my_financial_aid_funding_sources.rb, config/routes.rb, fixtures/xml/campus_solutions/financial_aid_funding_sources.xml, spec/controllers/campus_solutions/financial_aid_funding_sources_controller_spec.rb, spec/models/campus_solutions/financial_aid_funding_sources_spec.rb
https://jira.berkeley.edu/browse/SISRP-10609
=> SISRP-10609 - Provide proxy pass through for finaid funding sources

app/models/campus_solutions/posting_proxy.rb, spec/models/campus_solutions/address_spec.rb
https://jira.berkeley.edu/browse/SISRP-10589
=> SISRP-10589 Set charset in post to CS to preserve Unicode chars

src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5904
=> CLC-5904 Do not upcase task subtitles by default

app/models/calnet_crosswalk/proxy.rb, app/models/campus_solutions/proxy.rb
https://jira.berkeley.edu/browse/SISRP-10704
=> SISRP-10704 Eliminate and defend against empty crosswalk lookups

app/models/campus_solutions/deposit.rb, app/models/campus_solutions/financial_aid_data.rb, app/models/hub_edos/person.rb, app/models/hub_edos/student.rb, app/models/hub_edos/user_attributes.rb, app/models/hub_edos/work_experience.rb
https://jira.berkeley.edu/browse/SISRP-10703
=> SISRP Add UserCacheExpiry to several proxies that need it

app/models/my_tasks/sis_tasks.rb, src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-10701
=> SISRP-10701 - Add upload link to tasks for Finaid

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js
https://jira.berkeley.edu/browse/SISRP-10614
This removes the JS error
=> SISRP-10614 - Emergency contacts were removed from the student EDO

src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js
https://jira.berkeley.edu/browse/SISRP-10524
=> SISRP-10524 - Profile - required address fields not marked "required"

spec/ui_selenium/my_dashboard_canvas_course_sites_spec.rb, spec/ui_selenium/my_finances_ui_landing_page_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5990
=> QA: fix broken My Finances landing page test

src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5904
Reverts #4472.
=> CLC-5904-revert Do not upcase task subtitles by default

src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-10788
This JIRA blocks all performance testing so I plan to self-merge once T is happy.
=> SISRP-10788 Fix conditional decision to show profile link

src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-8905
=> SISRP-8905 - Net Cost - Don't show budget portion of COA=0

src/assets/stylesheets/finaid_coa.scss, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-9406
=> SISRP-9406 - COA Card - Allign Text for Indented budget items in expanded view

src/assets/stylesheets/_useful.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-5932
=> CLC-5932 - Hyperactive spinners

src/assets/javascripts/angular/controllers/widgets/profile/workExperienceController.js, src/assets/javascripts/angular/controllers/widgets/profile/workExperienceSectionController.js, src/assets/javascripts/angular/factories/profileFactory.js, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/profile/work_experience.html, src/assets/templates/widgets/profile/work_experience_section.html
https://jira.berkeley.edu/browse/SISRP-5787
=> SISRP-5787 - Front End Dev: Credentials Tab - Work Experience Card

src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/templates/widgets/finaid_awards_section.html
https://jira.berkeley.edu/browse/SISRP-10799
=> SISRP-10799 - Awards / Funding sources follow up

src/assets/templates/myfinances.html, src/assets/templates/widgets/finaid_activity.html
https://jira.berkeley.edu/browse/SISRP-10825
=> SISRP-10825 - Front-end changes - FinAid HomePage for Aid Year 15-16

src/assets/javascripts/angular/controllers/pages/finaidController.js
https://jira.berkeley.edu/browse/SISRP-6337
=> SISRP-6337 - CC - Going to /finances/finaid directly results in a 404

src/assets/templates/widgets/finaid_awards_section.html
https://jira.berkeley.edu/browse/SISRP-10864
=> SISRP-10864 - Front-end: Awards / Funding Sources - Add alerts & remaining work-study

src/assets/stylesheets/_useful.scss
https://jira.berkeley.edu/browse/SISRP-10875
=> SISRP-10875 - Profile - odd horizontal bar during updates

app/controllers/campus_solutions/delegate_access_controller.rb, app/models/campus_solutions/delegate_access_create.rb, app/models/campus_solutions/my_delegate_access.rb, config/routes.rb, fixtures/xml/campus_solutions/delegate_access_create.xml, spec/controllers/campus_solutions/delegate_access_controller_spec.rb, spec/models/campus_solutions/delegate_access_create_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5982
This only covers our best guess as to what the happy path will look like. Error and failure handling will require a working API to develop against.
=> CLC-5982 Backend wiring for delegate access creation

src/assets/templates/widgets/profile/contact_email.html
https://jira.berkeley.edu/browse/SISRP-10880
=> SISRP-10880 - Profile - very long strings should wrap

src/assets/stylesheets/_base.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6005
=> CLC-6005 - Weird behavior when opening the side menu on an iOS9 device & latest safari

src/assets/javascripts/angular/controllers/widgets/profile/title4Controller.js, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/stylesheets/_finaid_permissions.scss, src/assets/stylesheets/_finaid_title4.scss, src/assets/stylesheets/_text.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/directives/finaid_permissions.html, src/assets/templates/widgets/finaid_not_available.html, src/assets/templates/widgets/finaid_profile.html, src/assets/templates/widgets/finaid_summary.html, src/assets/templates/widgets/profile/title4.html
https://jira.berkeley.edu/browse/SISRP-8922
=> SISRP-8922 - FA Profile Card - need a way to change T4 Authorization

src/assets/stylesheets/_base.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6005
=> CLC-6005 - Fix vertical scrolling on CalCentral

src/assets/javascripts/angular/controllers/widgets/sir/sirController.js
https://jira.berkeley.edu/browse/SISRP-10773
=> SISRP-10773 - CalCentral SIR process Inconsistent behavior

gulpfile.js
https://jira.berkeley.edu/browse/SISRP-10927
=> SISRP-10927 - Header Google badges have vanished

app/models/oec/task.rb, spec/models/oec/term_setup_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6010
=> CLC-6010 OEC: Display Google authorization errors in UI

src/assets/templates/widgets/profile/contact_address_editor.html
https://jira.berkeley.edu/browse/SISRP-10579
=> SISRP-10579 - Profile - address input is being truncated after the user clicks Save

app/models/berkeley/cal_residency.rb, app/models/campus_oracle/queries.rb, spec/models/berkeley/cal_residency_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6013
A last minute twist to the story!
=> CLC-6013 Do not show Residency prompt to Fall Program for Freshmen students

src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/templates/widgets/finaid_awards.html
https://jira.berkeley.edu/browse/SISRP-10669
=> SISRP-10669 - FinAid Profile Card - T&C T4 Auth responses incorrect

src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js
https://jira.berkeley.edu/browse/SISRP-11044
=> SISRP-11044 - Remove error message when you change the country

app/models/hub_edos/user_attributes.rb
https://jira.berkeley.edu/browse/SISRP-11117
=> SISRP-11117 Guard against missing data in student API

app/models/hub_edos/my_student.rb
=> SISRP-11118 (QA) Protect merged student feed with a feature flag

app/models/hub_edos/my_student.rb
QA branch version of #4523, which claimed to be a QA branch merge, but wasn't. 
This one is. No, really, it is!
=> SISRP-11118 (QA, really) Protect merged student feed with a feature flag

.jscsrc, src/assets/javascripts/angular/controllers/widgets/carsController.js
https://jira.berkeley.edu/browse/SISRP-10922
=> SISRP-10922 Remove duplicate key in CalCentral .jscrc

app/models/campus_solutions/my_aid_years.rb, app/models/campus_solutions/my_checklist.rb, app/models/campus_solutions/my_deposit.rb, app/models/campus_solutions/my_financial_aid_data.rb, app/models/campus_solutions/my_higher_one_url.rb, app/models/hub_edos/my_person.rb, app/models/hub_edos/my_work_experience.rb, lib/cache/user_cache_warmer.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6016
=> [QA] CLC-6016 Do not allow cache warmer to trigger disabled features

app/models/campus_solutions/my_aid_years.rb, app/models/campus_solutions/my_checklist.rb, app/models/campus_solutions/my_deposit.rb, app/models/campus_solutions/my_financial_aid_data.rb, app/models/campus_solutions/my_higher_one_url.rb, app/models/hub_edos/my_person.rb, app/models/hub_edos/my_work_experience.rb, lib/cache/user_cache_warmer.rb
Follow-up to #4527 addressing @ctweney's comment.
https://jira.ets.berkeley.edu/jira/browse/CLC-6016
=> [QA] CLC-6016 Move feature-flag blocking from cache to models

src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js, src/assets/templates/finaid.html, src/assets/templates/widgets/finaid_communications.html
https://jira.berkeley.edu/browse/SISRP-11156
=> SISRP-11156 - UX Develop: Add link to fluid ad-hoc doc upload page on Awards card (place at bottom) for testing

app/models/campus_solutions/my_aid_years.rb, app/models/campus_solutions/my_checklist.rb, app/models/campus_solutions/my_deposit.rb, app/models/campus_solutions/my_financial_aid_data.rb, app/models/campus_solutions/my_higher_one_url.rb, app/models/hub_edos/my_work_experience.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6016
Master-branch squash of #4527, #4528 and #4531, excluding changes to `app/models/hub_edos/my_person.rb`, which was removed from master in #4519.
=> CLC-6016 Extend Campus Solutions feature flags to user-specific models

src/assets/javascripts/angular/controllers/widgets/delegateLinkingController.js, src/assets/javascripts/angular/services/delegateService.js, src/assets/templates/widgets/delegate/linking.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5972
Report the CS error to the user and disable the 'Link' button until required elements are provided.
=> CLC-5972, form validation with CS error reported

db/migrate/20151118213211_disable_campus_solutions_links_in_my_campus.rb, db/schema.rb, public/json/campuslinks.json
https://jira.ets.berkeley.edu/jira/browse/CLC-5927
This particular My Campus link has been set to 'false' for all users. What we do on master branch depends on answer to question in Jira above.
=> CLC-5927, for now, hide My Campus links to Berkeley Campus Solutions

app/models/campus_solutions/checklist.rb, app/models/campus_solutions/deposit.rb, app/models/campus_solutions/higher_one_url.rb, app/models/campus_solutions/my_checklist.rb, app/models/campus_solutions/my_deposit.rb, app/models/campus_solutions/my_higher_one_url.rb, app/models/campus_solutions/sir_config.rb, app/models/campus_solutions/sir_feature_flagged.rb, app/models/campus_solutions/sir_response.rb, spec/models/campus_solutions/checklist_spec.rb, spec/models/campus_solutions/deposit_spec.rb, spec/models/campus_solutions/higher_one_url_spec.rb, spec/models/campus_solutions/sir_config_spec.rb, spec/models/campus_solutions/sir_response_spec.rb, spec/support/campus_solutions_helper_module.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6019
=> CLC-6019 Decouple SIR and profile feature flags on back end

src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/finaidController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidCoaController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/javascripts/angular/services/finaidService.js, src/assets/stylesheets/_finaid_summary.scss, src/assets/stylesheets/finaid_coa.scss, src/assets/templates/widgets/finaid_coa.html, src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-10912
**Note**: Calcentral-sis-dev is actually broken until this PR gets merged (since the API changed)
=> SISRP-10912 - Remove semester options in CalCentral

app/controllers/campus_solutions/delegate_access_controller.rb, app/models/campus_solutions/delegate_management_url.rb, app/models/campus_solutions/delegate_terms_and_conditions.rb, config/routes.rb, fixtures/xml/campus_solutions/delegate_management_url.xml, spec/controllers/campus_solutions/delegate_access_controller_spec.rb, src/assets/javascripts/angular/controllers/widgets/profile/delegateController.js, src/assets/javascripts/angular/factories/delegateFactory.js, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/profile/delegate.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5966
Proxy for getting URL from CS. Plus, front-end profile widget (disabled) so students can users can click over to CS to add / remove delegates.
=> CLC-5968, Campus Solutions URL with which students can manage delegates

src/assets/javascripts/angular/controllers/pages/finaidController.js, src/assets/templates/widgets/finaid_awards_loans.html, src/assets/templates/widgets/finaid_awards_section.html, src/assets/templates/widgets/finaid_communications.html
https://jira.berkeley.edu/browse/SISRP-11243
=> SISRP-11243 - Fluid return text to CalCentral

src/assets/stylesheets/_base.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6021
=> CLC-6021-qa - Roster photos: printing in Firefox only prints one page

src/assets/javascripts/angular/controllers/widgets/finaid/finaidCoaController.js, src/assets/stylesheets/finaid_coa.scss, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-9386
=> SISRP-9386 - COA Card - Academic Year View

src/assets/javascripts/angular/directives/finaidSummaryItemDirective.js, src/assets/stylesheets/_finaid_summary.scss, src/assets/templates/directives/finaid_summary_item.html, src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-10889
=> SISRP-10889 - Net Cost - Indent sub items and don't align totals

src/assets/stylesheets/_canvas_roster.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6029
=> CLC-6029 - My Academics Class Roster print view broken on Firefox

src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-11288
=> SISRP-11288 - FINA Checklist items should only have upload button if Initiated or Incomplete

src/assets/templates/footer.html
https://jira.berkeley.edu/browse/SISRP-11792
=> SISRP-11792 - Modify the CalCentral footer "Feedback" title to "Support"

src/assets/templates/widgets/finaid_profile.html
https://jira.berkeley.edu/browse/SISRP-11271
=> SISRP-11271 - Add links to financial aid profile (STATUS)

db/migrate/20151123150455_link_to_student_loans.rb, db/schema.rb, public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-7644
=> SISRP-7644 Add loan payment estimator link to My Campus

spec/models/user/api_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/myToolboxController.js, src/assets/javascripts/angular/controllers/widgets/actingAsController.js, src/assets/javascripts/angular/controllers/widgets/adminController.js, src/assets/javascripts/angular/controllers/widgets/apiTestController.js, src/assets/javascripts/angular/services/utilService.js, src/assets/stylesheets/_settings.scss, src/assets/stylesheets/_toolbox.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/navigation.html, src/assets/templates/settings.html, src/assets/templates/toolbox.html, src/assets/templates/widgets/toolbox/api_text.html, src/assets/templates/widgets/toolbox/uid_lookup.html, src/assets/templates/widgets/toolbox/view_as.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6040
Includes:
* toolbox page with widgets: view_as, api_test and uid_lookup 
* isLoading flag when needed
* reorganize styles as needed
* tweak to navigation.html: 'My Toolbox' for superusers and users w/ view-as priv
=> CLC-6040, Move widgets to 'My Toolbox' page: View as, API test and UID/SID Lookup

src/assets/stylesheets/finaid_awards.scss, src/assets/templates/widgets/finaid_awards_section.html
https://jira.berkeley.edu/browse/SISRP-10891
=> SISRP-10891 - Award Card - Cant access Outside Resources page if no existing gift aid

src/assets/templates/widgets/sir/sir_item_completed.html
https://jira.berkeley.edu/browse/SISRP-11283
=> SISRP-11283 - GL3 Remove hardcoded SIR response messages

src/assets/templates/navigation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6049
@christianvuerings thanks for the tip on http://fortawesome.github.io/Font-Awesome/icon/wrench/
=> CLC-6049, My Toolbox tab gets wrench icon

app/controllers/campus_solutions/financial_aid_funding_sources_controller_term.rb, app/models/campus_solutions/financial_aid_funding_sources_term.rb, app/models/campus_solutions/my_financial_aid_funding_sources_term.rb, config/routes.rb, fixtures/xml/campus_solutions/financial_aid_funding_sources_term.xml, spec/controllers/campus_solutions/financial_aid_funding_sources_controller_term_spec.rb, spec/models/campus_solutions/financial_aid_funding_sources_term_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsTermController.js, src/assets/javascripts/angular/directives/finaidTableDirective.js, src/assets/javascripts/angular/factories/finaidFactory.js, src/assets/stylesheets/_finaid_table.scss, src/assets/stylesheets/calcentral.scss, src/assets/stylesheets/finaid_awards.scss, src/assets/stylesheets/finaid_coa.scss, src/assets/templates/directives/finaid_table.html, src/assets/templates/finaid_awards_term.html, src/assets/templates/widgets/finaid_awards.html, src/assets/templates/widgets/finaid_awards_term_widget.html, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-11269
SISRP-11881 - Back End Dev: Funding Sources - Term / Wide View
https://jira.berkeley.edu/browse/SISRP-11881
=> SISRP-11269 - Front End Dev: Funding Sources - Term / Wide View

app/models/hub_edos/user_attributes.rb
https://jira.berkeley.edu/browse/SISRP-11886
https://jira.ets.berkeley.edu/jira/browse/CLC-6059
=> SISRP-11886 CLC-6059 InvalidURIError from HubEdos::UserAttributes

app/models/my_activities/campus_solutions_messages.rb, src/assets/javascripts/angular/controllers/widgets/activityController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js, src/assets/javascripts/angular/controllers/widgets/finaidActivityController.js, src/assets/javascripts/angular/controllers/widgets/statusController.js, src/assets/javascripts/angular/factories/activityFactory.js, src/assets/templates/widgets/activity.html, src/assets/templates/widgets/activity_archive.html, src/assets/templates/widgets/activity_list.html, src/assets/templates/widgets/finaid_activity.html, src/assets/templates/widgets/finaid_communications.html
https://jira.berkeley.edu/browse/SISRP-7692
First part: adding messages
Next up: checklist & holds
=> SISRP-7692 - Front-End Dev: FinAid Communications Card

lib/calcentral_config.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6064
I believe we were outsmarted by Log4r's fancy multi-outputter setup. This change sets things right for me locally.
=> CLC-6064 Apply dynamic logging changes to actual logging outputters

src/assets/javascripts/angular/controllers/widgets/profile/basicController.js, src/assets/javascripts/angular/controllers/widgets/profile/contactController.js, src/assets/javascripts/angular/controllers/widgets/profile/demographicController.js, src/assets/javascripts/angular/controllers/widgets/profile/emergencyController.js, src/assets/javascripts/angular/controllers/widgets/profile/languagesController.js, src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js, src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/basic.html, src/assets/templates/widgets/profile/contact.html, src/assets/templates/widgets/profile/demographic.html, src/assets/templates/widgets/profile/editable_soon.html, src/assets/templates/widgets/profile/emergency.html, src/assets/templates/widgets/profile/languages.html, src/assets/templates/widgets/profile/unavailable.html
https://jira.berkeley.edu/browse/SISRP-11943
=> SISRP-11943 - Profile backend breakages are not indicated in UX

app/models/user/api.rb, spec/models/user/api_with_campus_solutions_enabled_spec.rb
https://jira.berkeley.edu/browse/SISRP-11903
While this doesn't take the place of error handling farther down the stack, it should provide some more immediate rigor as far as what's allowed into the /my/status feed.
=> SISRP-11903 Tighten filters on Hub merge into User::Api

spec/models/calnet_crosswalk/by_uid_spec.rb
Fixes this test failure: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPMASTER-JOB1-3553/test/case/59832591
=> NOJIRA Fix failing test

app/models/hub_edos/response_handler.rb, app/models/hub_edos/student.rb, app/models/hub_edos/work_experience.rb, spec/models/hub_edos/response_handler_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6066
https://jira.berkeley.edu/browse/SISRP-11933
This brings a new home for reusable code and, hopefully, a bit more resiliency to the HubEdos module.
=> CLC-6066, less brittle HubEdos module via safe response handling
