config/settings.yml
spec/ui_selenium/my_dashboard_google_tasks_spec.rb
spec/ui_selenium/pages/cal_central_pages.rb
spec/ui_selenium/pages/my_dashboard_to_do_card.rb
spec/ui_selenium/util/web_driver_utils.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4647
Includes the following changes:
* Expect the right date format when task dates occur in a different year from the current year (this fixes most of the recent build failures)
* Move expected date formats to utils since they're shared across tests
* Remove several redundant Google task examples and change the sequence of others to make them more logical
* Extend Google task and basic auth timeouts to reduce occasional test failures
* Remove from the spec all remaining references to the actual HTML implementation in the UI
* Add logging so I can view the Google response time for each call, which should help inform future adjustments to timeouts

CLC-4647: fix Selenium Google tasks test

---

Gemfile
Gemfile.lock

https://jira.ets.berkeley.edu/jira/browse/CLC-4435
The RubyMine integration is still broken, unfortunately.

CLC-4435 Re-enable Spork for JRuby

---

app/models/bearfacts/proxy.rb
app/models/finaid/Proxy.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4659
We were recently told that our old authentication approach will stop working on January 20. This leaves barely enough time for us to handle it in our normal release cycle, and so as soon as this checks out on master, I'll prepare a QA PR.

CLC-4659 Header-based authentication for apis.berkeley.edu feeds

---

public/canvas/canvas-customization.js

https://jira.ets.berkeley.edu/jira/browse/CLC-4654
Adds jQuery event method to toggler causing the arrow icon to properly toggle between 'icon-arrow-right' and 'icon-arrow-down' classes.

CLC-4654 - Alt media: caret needs to point downward when expanding

---

app/assets/stylesheets/_canvas_roster.scss
app/assets/templates/canvas_embedded/roster.html

https://jira.ets.berkeley.edu/jira/browse/CLC-4725
Applies 'cc-page-roster-student-id' class to all student ids displayed. Hides these student IDs from print media using CSS.

CLC-4725 - Roster Print: Remove SIS ID when printing the roster

---

app/assets/templates/canvas_embedded/_shared/canvas_feed_error.html

https://jira.ets.berkeley.edu/jira/browse/CLC-4705
Simply updates the error message displayed to users with no current official sections to display "This feature is currently only available to instructors with course sections scheduled in the current or upcoming terms". This is valid for students or instructors with no current official sections in the current or upcoming terms.

CLC-4705 - Course Provisioning: Ensure form only visible to instructors associated with sections in current terms

---

app/assets/stylesheets/_canvas_embedded.scss
app/assets/templates/canvas_embedded/canvas_course_sections_form.html

https://jira.ets.berkeley.edu/jira/browse/CLC-4713
* Moves section site links display into existing sections list, removing segregated listing of sections related to existing bCourses sites.
* Adds borders to sections, with background colors based on primary or secondary designation for the section.

CLC-4713 - Course Provisioning: Style changes to course meta data

---

app/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js
app/assets/templates/canvas_embedded/course_add_user.html

Fixes broken UID search in "Find a Person to Add": https://jira.ets.berkeley.edu/jira/browse/CLC-4682
The API endpoint expects an underscored parameter value, and changing the view code to match seemed less inconsistent than telling the API to expect camelcase.

CLC-4682 Find a Person to Add: fix formatting of UID parameter

---

app/assets/javascripts/angular/controllers/pages/canvasCourseProvisionController.js
app/assets/templates/canvas_embedded/course_provision.html

Fixes https://jira.ets.berkeley.edu/jira/browse/CLC-4329 along the lines of [this suggestion](http://stackoverflow.com/questions/25471429/angularjs-ng-required-not-working-on-ios) pointed out by @christianv: explicitly show an error message and disable the submit button instead of relying on HTML5 required attribute messaging, which isn't working in Safari.
The extra validity check in the controller code might be redundant, but safety first.
Someone who knows more Angular than me should definitely check this!

CLC-4329 Course provisioning: validate "Site Name" as required field

---

app/models/campus_oracle/queries.rb
spec/models/berkeley/terms_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4737
This slip-up made our Tele-BEARS multiple-term support a no-op.

CLC-4737 Add term_status to SQL query

---

app/assets/javascripts/angular/controllers/pages/canvasCourseProvisionController.js

https://jira.ets.berkeley.edu/jira/browse/CLC-4716
Resolves issue where all sections are pre-selected when creating course site by CCN, however the 'Next' button was disabled until you de-select and re-select a section.
Also resolves issue when switching between semesters by refreshing the selected sections for the currently selected semester.

CLC-4716 - Fix disabled 'Next' button when provisioning by CCN

---

spec/ui_selenium/authentication_deep_linking_spec.rb
spec/ui_selenium/authentication_opt_out_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4736
A couple Selenium tests log out of CalCentral.  These tests were broken by the new redirect in CLC-4736.  The tests now expect the CalCentral splash page to load rather than the CAS "logout success" page.  The tests do still verify that the user is actually logged out of CalNet.

CLC-4736: fix Selenium tests to handle logout redirect

---

app/assets/templates/adviser_message.html
app/models/my_academics/telebears.rb
public/dummy/json/academics.json
spec/models/my_academics/telebears_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4658
Also added direct links for CalSO adviser code handling.

CLC-4658 Handle Access Revoked status in Tele-BEARS

---

spec/ui_selenium/my_dashboard_google_live_updates_spec.rb
spec/ui_selenium/my_dashboard_google_tasks_spec.rb
spec/ui_selenium/my_dashboard_google_up_next_spec.rb
spec/ui_selenium/pages/google_page.rb
spec/ui_selenium/pages/my_dashboard_up_next_card.rb
spec/ui_selenium/util/user_utils.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4676
The new test creates a calendar event at Google and then verifies that the event appears in CalCentral, with all the expected detail. It also opens the event in Google and verifies that the event detail view loads. Since the test will run in the wee hours, it will ensure that the UpNext feed is updated immediately each day.
This also includes some clean-up of related Google mail and task tests.

CLC-4676: UpNext Selenium test

---

spec/ui_selenium/my_finances_data_cal1card_spec.rb
spec/ui_selenium/pages/api_my_cal1_card_page.rb
spec/ui_selenium/pages/my_finances_landing_page.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4575
This test verifies different permutations of the Cal 1 Card UI on My Finances, using a set of real UIDs.  The test verifies that Cal 1 Card data exists for at least one of the test UIDs, so it will fail if the feed is down or if the test UIDs are not useful.  It also verifies the external links to Cal 1 Card and Caldining.  Finally, it generates a CSV containing information about the UIDs to facilitate manual testing and management of the pool of test UIDs themselves.

CLC-4575: Selenium test for Cal 1 Card UI

---

app/assets/javascripts/angular/controllers/pages/rosterController.js
app/assets/templates/canvas_embedded/roster.html
app/assets/templates/canvas_embedded/roster_photo.html
app/controllers/canvas_rosters_controller.rb
app/models/canvas/canvas_rosters.rb
config/routes.rb
spec/controllers/canvas_rosters_controller_spec.rb
spec/models/canvas/canvas_rosters_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4639
Per Ray's spec, the Roster Photos tool no longer checks Canvas course site memberships and relies solely on campus data when loading. This should substantially speed up loading, with some UX effects as detailed in the JIRA.

CLC-4639 Only show official sections in bCourses Roster Photos

---

app/assets/javascripts/angular/controllers/pages/rosterController.js
app/models/canvas/canvas_rosters.rb
spec/controllers/canvas_rosters_controller_spec.rb
spec/models/canvas/canvas_rosters_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4745
Changed CanvasRosters to return section CCNs as strings, as CampusRosters does. The front-end rosterController may receive feeds from either endpoint and was understandably getting confused.

CLC-4745 Fix type inconsistency in roster feeds

---

app/assets/javascripts/angular/services/utilService.js

https://jira.ets.berkeley.edu/jira/browse/CLC-4696
This one's a facepalm. #3289 added variable assignments outside the `updateHeight` function, so they were only set once and wouldn't respond to subsequent changes in the frame height -- or, in the case of slow-loading tools, the initial height of the fully loaded frame.

CLC-4696 Ensure that LTI frame size updates do in fact update

---

app/models/oec/courses_diff.rb
spec/models/oec/courses_diff_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-537
The oec:diff task file find source file based on naming convention. Justin wants *{dept_name}_courses_confirmed.csv*.  This is simple change.

OEC-537, oec:diff task should expect {dept_name}_courses_confirmed.csv

---

app/models/oec/queries.rb
lib/tasks/oec.rake

https://jira.ets.berkeley.edu/jira/browse/OEC-531
For example, secondary MCELLBI sections with cross-listings in PSYCH dept should show in MCELLBI.csv and PSYCH.csv. This allows both depts to vote on whether course should be evaluated. (Reqts confusion has been ironed out. See the OEC-531.)
Fix was to remove the dept constraint in SQL where clause of *get_secondary_cross_listings*
Bonus: *oec.rake courses* gets more logging.

OEC-531, secondary x-listed are expected in CSVs of both participating depts

---

app/models/oec/biology_post_processor.rb
lib/tasks/oec.rake

https://jira.ets.berkeley.edu/jira/browse/OEC-538
One example: The BIO.csv would legitimately get:
2015-B-42154,INTEGBI 95 LEC 002 SPEC RES IN BIO 1B...
Next, BIO_post_processor would move that row to INTEGBI.csv based on its dept_name=INTEGBI.  Problem is that INTEGBI.csv, based on its own SQL query, already has that data.
Our fix is to have BIO_post_processor skip rows in BIO.csv where dept_name = INTEGBI or MCELLBI.
I've also cleaned up logging summary in *oec.rake*.

OEC-538, BIO_post_processor should skip non-BIO depts in BIO csv (e.g., MCB cross-listing)

---

app/models/oec/biology_post_processor.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-538
Following up on https://github.com/ets-berkeley-edu/calcentral/pull/3304
If a BIO course is cross-listed and dept is something *other than* MCELLBI and INTEGBI then the row will remain in the BIO.csv file. In this scenario, the BIO.csv will not be deleted by post-processor.

OEC-538, target CSV defaults to biology. Send row to mcellbi or integbi when appropriate

---

app/assets/stylesheets/_mycalendar.scss
app/assets/templates/widgets/up_next.html
app/models/up_next/my_up_next.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4775
Also fixes:
* Indentation of the `View in bCal` button
* CamelCase the API
* When there are no invitees, don't show `invitees:`

CLC-4775 - Add hangout link to Whats Next event on the dashboard when available

---

app/models/oec/biology_post_processor.rb
app/models/oec/export.rb
lib/tasks/oec.rake
spec/models/oec/export_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-532
Course data is in multiple CSVs - one per dept. When running oec:students we (1) create students.csv in first iteration (i.e., dept) and then (2) append to students.csv in subsequent. This actually simplifies some of the code. Increased test coverage a bit.

OEC-532, optional overwrite_file arg (export class) used by oec:students task

---

README.md

When I ran rake db:schema:load, I experienced this error:
PG::Error: ERROR:  permission denied to create database CALCENTRAL_DEVELOPMENT
After granting 'createdb' privileges to the user CALCENTRAL_DEVELOPMENT, everything seemed to work ok

NOJIRA - Modified Postgres instructions 

---

config/initializers/rails_admin.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-3831
Added is_author and is_viewer to table headers; played around with the header widths to get the necessary data showing when the page is half width.
Screenshots are on at the Jira page

CLC-3831 Reconfigure ccadmin so that the View As column displays on the main Authorizations page

---

app/models/oec/biology_post_processor.rb
app/models/oec/courses.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-531
Primary, secondary and then secondary cross-listed sections are now nested together in CSV. Primary sections for cross-listed sections were always listed first, followed by their secondaries and then the primary and any cross-listings from other department(s).
Plus, Biology CSV post-processor was missing certain 1A, 1B entries due to course-title-shorthand "BIO 1A" (found in campus data)

OEC-531, Primary and secondary sections (and x-listings) now nested within spreadsheet (csv)

---

app/models/finaid/my_fin_aid.rb
app/models/finaid/proxy.rb
lib/proxies/feed_wrapper.rb
lib/proxies/http_requester.rb
spec/lib/proxies/feed_wrapper_spec.rb
spec/models/finaid/my_fin_aid_spec.rb
spec/models/finaid/proxy_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4663
The goal is to replace the current divergent state of our XML and JSON feed parsing, as described in the ticket, with a standard approach using the parsed_response Ruby object that HTTParty gives us for free. 
However, working directly with that parsed_response object brings in some of the headaches and pitfalls that come with traversing large data structures. My approach here is to wrap that object, and its children as extracted, in a new FeedWrapper class. The main benefits are two: 
- Soft failures on missing or unexpectedly formatted elements (without losing the ability to log surprises). Because we don't have to explicitly check for nils and types, we can keep the concision of the current CSS and XPath selectors without having to …

CLC-4663 Remove unnecessary response parsing in Finaid module

---

app/models/oec/courses.rb
app/models/oec/queries.rb
spec/models/oec/courses_diff_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-531
In some cases of cross-listing, we have sections where there are zero enrollments in one department's cross-listing, but not in the other. The effect of this is that we see a few cases like 2015-B-11700 where it has enrollments, but its matched section 2015-B-53051 does not, so it fails to show up on the Chem spreadsheet.
If we exclude a zero enrollment course in the SQL then we never check the enrollment count of its cross-listings. Therefore, we move the exclusion logic out of SQL and specifically at the point of *output << row*.
(Apologies for four commits in one PR. The diff is not overwhelming.)

OEC-531, exclude zero enrollment courses in the rb code, not SQL

---

app/models/oec/queries.rb
lib/tasks/oec.rake

https://jira.ets.berkeley.edu/jira/browse/OEC-533
Both student-related queries now use the clause: (r.enroll_status = 'E' OR r.enroll_status = 'C')
Also, we use two queries (instead of one per dept) to generate the global list of student and enrollment data.

OEC-533, omit wait listed students from course_students.csv

---

app/models/my_classes/campus.rb
app/models/my_classes/canvas.rb
app/models/my_classes/merged.rb
app/models/my_groups/callink.rb
app/models/my_groups/canvas.rb
app/models/my_groups/merged.rb
app/models/my_groups/research.rb
app/models/my_groups/sakai.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-3513
I'm really sorry that the differ isn't smarter about indentation changes. Apart from the first and last lines of the classes, the only changes I made were to namespacing: 
- removing explicit module references where they weren't needed; 
- and prepending a double colon to top-level modules (Sakai, Canvas) where the namespaced module would otherwise be assumed.
I also prepended a double colon to CalLink, which escapes confusion with MyGroups::Callink only by virtue of capitalization (and perhaps that should be standardized in a follow-up PR).

CLC-3515 Replace class Foo::Bar with module Foo; class Bar

---

app/models/textbooks/proxy.rb

Continuing to mop up on https://jira.ets.berkeley.edu/jira/browse/CLC-4663.
This removes redundant JSON parsing from Textbooks::Proxy when live, and switches to our SafeJsonParser when fake.

CLC-4663 Remove unnecessary parsing from Textbooks::Proxy

---

app/models/ets_blog/alerts.rb
app/models/ets_blog/release_notes.rb
spec/models/ets_blog/alerts_spec.rb

Continuing cleanup on https://jira.ets.berkeley.edu/jira/browse/CLC-4663.
EtsBlog::Alerts uses the new FeedWrapper class. EtsBlog::ReleaseNotes is managing without it.
The tests for EtsBlog::Alerts have been slimmed down, because the removal of parsing has left them less to do, and because certain conditions, like a missing fake file, didn't seem to require an explicit test separate from the tests for exception handling.

CLC-4663 Remove unnecessary parsing in EtsBlog proxies

---

lib/tasks/oec.rake

https://jira.ets.berkeley.edu/jira/browse/OEC-555
Workflow:
1. *rake oec:courses* pulls raw course data (one CSV per dept)
1. Department admins add info to CSVs 
1. The "OEC secondary script" (i.e., Perl scripts owned by Ops) concats all CSVs into *courses.csv* 
1. Finally, this *oec:students* task is run. It will read CCNs from courses.csv then generate two CSVs which list course enrollments.
Previously, the *oec:students* task expected a set of CSVs, one per dept.

OEC-555, rake oec:students task will expect a single input: courses.csv

---

lib/tasks/oec.rake

https://jira.ets.berkeley.edu/jira/browse/OEC-539
OEC rake tasks have optional src and dest args (default is Rake.original_dir).  Arg values are expected to be relative or absolute directory paths. Valid usage would be:
> rake oec:courses dest=~/oec
> rake oec:courses dest=tmp/oec
> rake oec:courses dest=/var/tmp/oec
> rake oec:courses dest=../tmp/oec
Paths should be determined relative to user's working dir and *not* base of calcentral repo (as Dir.pwd would have it).

OEC-539, use Rake.original_dir as base dir when src/dest not specified

---

app/models/oec/biology_post_processor.rb
lib/tasks/oec.rake
spec/models/oec/biology_post_processor_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-551
Avoid duplicate rows in INTEGBI.csv caused by biology_post_process. BIO.csv entries were being moved to INTEGBI.csv causing, in the case of certain cross-listings, duplicates. The fix is to identify all unique CCN/UID entries in INTEGBI.csv before moving more over from BIO.csv.
This PR includes simple fix for https://jira.ets.berkeley.edu/jira/browse/OEC-567 in oec.rake:
>      if courses_diff.was_difference_found
>        Rails.logger.warn "#{hr}Find summary in #{courses_diff.output_filename}#{hr}"
>      else
>        File.delete courses_diff.output_filename
>        Rails.logger.warn "#{hr}No diff found in #{dept_name} csv.#{hr}"
>      end

OEC-551, avoid duplicate rows in INTEGBI.csv caused by biology_post_process

---

app/models/canvas/provide_course_site.rb
app/models/my_academics/academics_module.rb
app/models/my_academics/semesters.rb
app/models/my_academics/teaching.rb
app/models/my_classes/campus.rb
app/models/my_classes/classes_module.rb
app/models/rosters/campus.rb
public/dummy/json/academics.json
public/dummy/json/classes.json
spec/models/canvas/provide_course_site_spec.rb
spec/models/my_academics/teaching_spec.rb
spec/models/my_classes/campus_spec.rb
spec/models/my_classes/canvas_spec.rb
spec/models/my_classes/sakai_classes_spec.rb
spec/models/rosters/campus_spec.rb
spec/support/course_shared_examples.rb
src/assets/javascripts/angular/controllers/pages/academicsController.js
src/assets/javascripts/angular/factories/myClassesFactory.js
src/assets/stylesheets/_classes.scss
src/assets/templates/academics_classinfo.html
src/assets/templates/academics_semester_classes.html
src/assets/templates/academics_teaching.html
src/assets/templates/widgets/my_classes.html

https://jira.ets.berkeley.edu/jira/browse/CLC-4455
subsumes https://jira.ets.berkeley.edu/jira/browse/CLC-3355
This PR collapses crosslisted courses for instructors in My Academics and My Classes. Because campus data indicates crosslisting by adding a code to primary sections, this change will only affect instructors assigned to a primary section (no love for GSIs this round).
On the UX side, the the list of section codes in the My Academics semester summary is replaced with a new  column containing summary information on the number and type of sections. When the screen gets small, it collapses to a two-column view that lists only the total number of sections under the course code.
Rather than jam multiple course codes into the breadcrumbs on the Class Info page, a new "Crosslisted As" …

CLC-4455 Organize cross-listed courses more reasonably

---

spec/ui_selenium/my_dashboard_google_up_next_spec.rb
spec/ui_selenium/pages/google_page.rb
spec/ui_selenium/pages/my_dashboard_up_next_card.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4775
In CLC-4775, we've added Google hangout links to Up Next event detail.  This change updates the existing Up Next Selenium test, whereby the test user adds a video link to the Google invite and verifies that the link shows up in CalCentral.

CLC-4775: Add hangout link to Up Next Selenium test

---

app/models/oec/biology_post_processor.rb
app/models/oec/department_registry.rb
lib/tasks/oec.rake
spec/models/oec/biology_post_processor_spec.rb
spec/models/oec/department_registry_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-566
This is advance work on having the oec:diff task work when running dept_name=INTEGBI or dept_name=MCELLBI. Because different operations will rely on BIOLOGY's special case I have encapsulated the logic in DepartmentRegistry.

OEC-566, DeptRegistry encapsulates logic: if BIO then include INTEGBI and MCELLBI, too

---

app/models/canvas/provide_course_site.rb
spec/models/canvas/provide_course_site_spec.rb

This should fix https://jira.ets.berkeley.edu/jira/browse/CLC-4842, but needs to be verified as I'm not set up to test locally.

CLC-4842 Course Provisioning: make first listing the default for course data

---

spec/ui_selenium/pages/my_academics_advising_card.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4855
bHive changed the URL for making a new advising appointment. The new URL seems legit at bHive, so this updates the expected URL in the tests.

CLC-4855: Fix expected bHive URL for making new advising appts

---

app/models/oec/biology_post_processor.rb
app/models/oec/command_line.rb
app/models/oec/courses_diff.rb
app/models/oec/courses_group.rb
app/models/oec/dept_confirmed_data.rb
fixtures/oec/expected_diff_STAT_courses.csv
lib/tasks/oec.rake
spec/models/oec/command_line_spec.rb
spec/models/oec/courses_diff_spec.rb
spec/models/oec/department_registry_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-566
https://jira.ets.berkeley.edu/jira/browse/OEC-564
Couple issues resolved here:
1. Refactor oec.rake and create models to encapsulate (a) csv generation for a group of courses (CoursesGroup) and (b) command line options.
1. Diff task gets minor overhaul. See expected behavior in file fixtures/oec/expected_diff_STAT_courses.csv

OEC-566, INTEGBI diff wrong; no DB_COURSE_NAME in some cases

---

app/models/oec/command_line.rb
app/models/oec/courses_group.rb
lib/tasks/oec.rake
spec/models/oec/command_line_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-570
The significant work is in oec.rake. When diff task with unspecified list of departments we look to the 'src' directory for all files named *_courses_confirmed.csv. The regex is what determines list of departments to diff.

OEC-570, oec:diff w/ unspecified 'depts' should pull all dept_confirmed.csv files in src dir

---

app/models/bearfacts/proxy.rb
app/models/finaid/proxy.rb
spec/models/finaid/proxy_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4865
Fixes regressions from #3310 and #3326 that treated student ID lookup failure as an error condition rather than a fact of everyday life.

CLC-4865 Fix verbose ERROR logging on student ID lookup failure

---

app/models/advising/my_advising.rb
app/models/bearfacts/proxy.rb
app/models/cal1card/my_cal1card.rb
app/models/cal_link/memberships.rb
app/models/cal_link/organization.rb
app/models/canvas/proxy.rb
app/models/finaid/proxy.rb
app/models/financials/my_financials.rb
app/models/financials/proxy.rb
app/models/google_apps/revoke.rb
app/models/mediacasts/all_playlists.rb
app/models/mediacasts/audio.rb
app/models/textbooks/proxy.rb
lib/errors/proxy_error.rb
lib/proxies/http_requester.rb
lib/proxies/response_wrapper.rb
script/check_for_errors.sh
spec/models/advising/my_advising_spec.rb
spec/models/cal1card/my_cal1card_spec.rb
spec/models/cal_link/memberships_spec.rb
spec/models/cal_link/organization_spec.rb
spec/models/ets_blog/alerts_spec.rb
spec/models/financials/my_financials_spec.rb
spec/models/mediacasts/all_playlists_spec.rb
spec/models/mediacasts/audio_spec.rb
spec/models/textbooks/proxy_spec.rb
spec/support/proxy_shared_examples.rb

This PR addresses https://jira.ets.berkeley.edu/jira/browse/CLC-4837 by making a couple of changes to consolidate our error logging.
First, Errors::ProxyError now takes more options and hands them over to ResponseWrapper to format the log output. This should make it easier to keep formatting consistent and avoid problems like CLC-4837, where a multi-line response body was pushing the important information out of view. 
Second, since almost all of the classes using HTTPRequester raise the same error on unexpected status codes, I’ve consolidated that error handling into HTTPRequester itself. Classes that need to raise specialized errors or handle particular status codes themselves can pass HTTPRequester an `on_error` option hash.
The first line of the log shows the actual error message …

CLC-4837 Standardize logging of remote server errors

---

Gemfile
app/controllers/canvas_lti_controller.rb
app/models/canvas/external_app_configurations.rb
app/models/canvas/external_tools.rb
app/models/canvas/reconfigure_external_apps.rb
app/views/canvas_lti/lti_course_add_user.xml.erb
app/views/canvas_lti/lti_course_grade_export.xml.erb
app/views/canvas_lti/lti_course_manage_official_sections.xml.erb
app/views/canvas_lti/lti_course_mediacasts.xml.erb
app/views/canvas_lti/lti_roster_photos.xml.erb
app/views/canvas_lti/lti_site_creation.xml.erb
app/views/canvas_lti/lti_user_provision.xml.erb
config/settings.yml
config/settings/test.yml
fixtures/pretty_vcr_recordings/Canvas_create_external_tool.json
fixtures/pretty_vcr_recordings/Canvas_modify_external_tool.json
fixtures/pretty_vcr_recordings/Canvas_reset_external_tool_by_xml.json
lib/tasks/canvas.rake
script/configure-all-canvas-apps-from-current-host.sh
script/reconfigure-canvas-external-apps.sh
spec/models/canvas/external_tools_spec.rb
spec/models/canvas/reconfigure_external_apps_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4767
This gives us an easy way to add new LTI tools, to reset keys and secrets, and to configure apps on a Canvas server from the CalCentral environment associated with it (i.e., the script can configure bCourses-beta apps that CalCentral-production doesn't yet know about).

CLC-4767 Script to configure all currently defined LTI tools on bCourses

---

app/models/canvas/external_app_configurations.rb

Follow-up to https://github.com/ets-berkeley-edu/calcentral/pull/3411, making it easier to add support for this sprint's major user story, "Official Sections", in Beta and Test environments.
If the app has to be pulled from the release, just revert this commit.

CLC-4767 Enable Official Sections for the current sprint

---

app/models/advising/my_advising.rb
fixtures/json/advising.json
spec/controllers/my_advising_controller_spec.rb
spec/models/advising/my_advising_spec.rb

Addresses https://jira.ets.berkeley.edu/jira/browse/CLC-4932 by filtering out and logging appointments with missing data.
Updates the JSON fixture to match what bHive is currently sending out for Oski, adding some handmade invalid appointments.
Also fixes typos in the logging, and adds logic to sort appointments by date (reverse for past appointments, forward for future), since the feed seems to aspire to this ordering but at least for Oski is a bit jumbled.

CLC-4932 Filter malformed appointments in Advising API

---

app/models/my_tasks/canvas_tasks.rb
spec/models/my_tasks/my_tasks_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4894

CLC-4894 Add updatedAt field to unscheduled Canvas tasks

---

lib/errors/proxy_error.rb
spec/models/canvas/proxy_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4941

CLC-4941 Properly log Canvas proxy errors

---

app/models/ets_blog/release_notes.rb
app/models/my_activities/canvas_activities.rb
app/models/my_badges/google_mail.rb
app/models/my_tasks/canvas_tasks.rb
app/models/sakai/sakai_data.rb
app/models/sakai/site_announcements.rb
lib/html_sanitizer.rb
lib/proxies/feed_wrapper.rb
lib/tasks/vcr.rake
spec/models/my_badges/google_mail_spec.rb
spec/models/my_badges/my_badges_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4841
With these changes, our code no longer uses Nokogiri for anything, but I'm not touching the Gemfile for the moment as other gems (Capybara, omniauth_cas) still have it as a dependency.

CLC-4841 Standardize XML/HTML parsing, removing Nokogiri

---

app/models/oec/courses_diff.rb
fixtures/oec/STAT_courses_confirmed.csv
lib/tasks/oec.rake
spec/models/oec/courses_diff_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-580
The oec:diff task will validate CCN, term, ldap, annotation and instructor_func.  Errors will not cause abort. Instead, all errors will be logged at end of rake task run.

OEC-580, oec:diff should validate CCN, term, ldap, annotation

---

spec/ui_selenium/my_academics_data_enrollment_spec.rb
spec/ui_selenium/pages/api_my_academics_page.rb
spec/ui_selenium/pages/api_my_academics_page_semesters.rb
spec/ui_selenium/pages/api_my_status_page.rb
spec/ui_selenium/pages/my_academics_class_page.rb
spec/ui_selenium/pages/my_academics_enrollments_card.rb
spec/ui_selenium/pages/my_academics_page.rb
spec/ui_selenium/pages/my_academics_semesters_card.rb

This new spec covers the following student enrollment UIs:
* Semester cards on the My Academics page:
** The default semester cards shown
** The 'show more' feature
** The expected content of each semester card
* Semester page enrollment card for each semester
** The expected content for enrolled courses
** The expected content for wait listed courses
* Class page class info and instructor cards for each course
The test also produces a CSV containing enrollment info about the test UIDs in the current and future semester(s), for use in manual testing and for managing the test UIDs themselves.  The test takes a long time to run, so nightly builds will use UIDs sparingly.

CLC-4791: Selenium test for enrollment UIs

---

app/models/oec/biology_post_processor.rb
app/models/oec/courses_diff.rb
lib/tasks/oec.rake
spec/models/oec/courses_diff_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-586
Sample errors reported of rake oec:diff
```ruby
> -----------------------------
>  VALIDATION ERROR(S)
>  PSYCH
>      2010-Z-73716
>          YEAR is invalid: 2010
>          TERM is invalid: Z
>          INSTRUCTOR_FUNC is invalid: 9
>      2015-B-73716
>          PSYCH_courses_confirmed.csv does NOT contain course_id=2015-B-73716 with ldap_uid=1037141
>  STAT
>      2019-S-XXXX
>          YEAR is invalid: 2019
>          TERM is invalid: S
>          CCN is invalid: XXXX
>          LDAP_UID is invalid: LDAP_UID
>          INSTRUCTOR_FUNC is invalid: 9
>      2015-B-GLOP
>          CCN is invalid: GLOP
>          INSTRUCTOR_FUNC is invalid: 10
> -----------------------------
```

OEC-586, report errors of oec:diff in final summary output by oec.rake

---

app/models/oec/courses_group.rb
lib/tasks/oec.rake

https://jira.ets.berkeley.edu/jira/browse/OEC-580
This is a follow up to resolved sub-tasks of OEC-580. When rake oec:diff is done the summary contain, in addition to errors, where the diff results can be found. For example:
```ruby
Summary
STAT
Diff report
Created /Users/john/Projects/github/johncrossman/calcentral/tmp/oec/diff_STAT_courses.csv
... 
```

OEC-580, info useful to Ops is put to final output of script

---

app/models/oec/command_line.rb
app/models/oec/dept_confirmed_data.rb
fixtures/oec/STAT_courses_confirmed.csv
lib/tasks/oec.rake
spec/models/oec/command_line_spec.rb
spec/models/oec/courses_diff_spec.rb
spec/models/oec/dept_confirmed_data_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-585
https://jira.ets.berkeley.edu/jira/browse/OEC-572
We further the use of end-of-script summary. Reporting on CSVs requested but not found (per OEC-585) required a slight refactor of *dept_confirmed_data.rb*.  Specifically:
```
(departments.empty? ? Settings.oec.departments : departments).each do |dept_name|
```
I moved the logic of "if no departments specified then default to all Settings.oec.departments" out of command_line.rb. We can now report missing CSVs in case where **!departments.empty?**

OEC-572, corrupt row data is reported but causes no crash

---

src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js
src/assets/stylesheets/_canvas_course_manage_official_sections.scss
src/assets/templates/canvas_embedded/course_manage_official_sections.html

https://jira.ets.berkeley.edu/jira/browse/CLC-4877
1. "Sending Request" with spinner disappears once the progress bar is displayed
2. Allows TA's to see their own sections that are present, but not allowed to edit sections.
3. Thanks to @christianv and @nicolaasmatthijs on removing the border spacing in the section tables
4. Applied style to 'Add' button for white text
5. Applied border around progress bar area with proper heading

CLC-4877 - Post Demonstration Fixes

---

script/refresh-all-canvas-enrollments.sh
script/refresh-canvas-enrollments.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-4887
The default MaxHeapSize is about 310M, so a boost for these two consistently-growing scripts seems reasonable.

CLC-4887 Give the big bCourses refresh scripts more heap to fall back on

---

app/models/my_classes/classes_module.rb
src/assets/javascripts/angular/factories/myClassesFactory.js

Fixes duplicate repeater error and hidden bCourses sites in https://jira.ets.berkeley.edu/jira/browse/CLC-4448.
The back-end change ensures that bCourses site data in the MyClasses feed does not include duplicate links to campus courses.
The front-end change ensures that even if a campus course appears multiple times in the feed, all entries will be correctly associated with course sites. This matching logic is getting a little unwieldy, and at some point it might be a good idea to move it to the back end.

CLC-4448 Remove duplicate site listings under repeated courses in My Classes

---

src/assets/templates/academics_ls_advising.html

CLC-4641 - Integrate advisor picture into the L&S Advising card
https://jira.ets.berkeley.edu/jira/browse/CLC-4641
Advisers that don't have photos only have their names' displayed

Adviser Picture now on Academics Page

---

app/models/canvas/proxy.rb
spec/models/canvas/course_sections_spec.rb
spec/models/canvas/merged_user_sites_spec.rb
spec/models/canvas/provide_course_site_spec.rb
spec/models/canvas/site_memberships_maintainer_spec.rb
spec/support/spec_helper_module.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4950
Some back-end code was not zero-padding, causing mismatches in front-end.
This must be fixed before QA testing on Monday, and so if the new branch has been cut, I'll prepare a QA PR.

CLC-4950 Standardize CCN formatting in bCourses to fix Official Sections

---

spec/ui_selenium/my_academics_data_webcasts_spec.rb
spec/ui_selenium/pages/my_academics_class_page.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4959
This is a data-driven test for the various permutations of webcast UI.  The expected webcast content will be in the external test user file.  The test checks for the following variations:
* has webcasts or not
* has video or not
* has audio or not
* has valid iTunes links or not
* has valid audio download links or not
* if has video, then loads and auto-plays upon click
* has all expected lectures

CLC-4959: Selenium test for webcast UI

---

app/models/canvas/course_sections.rb
app/models/canvas/provide_course_site.rb
fixtures/pretty_vcr_recordings/Canvas_course_create_section.json
spec/models/canvas/course_sections_spec.rb
spec/models/canvas/provide_course_site_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4913
Establishes API based method for creation of a course section. Updates Canvas::ProvideCourseSite to use this method to automatically create a default course section and enroll the site creator as a 'Teacher' in that section. The exception to this is when the course site is created by CCN.

CLC-4913 - Course Provisioning: As an Instructor, I want to only be added to appropriate sections when creating a course site

---

Gemfile
app/models/regstatus/proxy.rb
fixtures/json/regstatus.json
lib/proxies/mock_http_interaction.rb
lib/proxies/mockable.rb
spec/models/regstatus/proxy_spec.rb
spec/support/proxy_shared_examples.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4909
The structure of this new proxy is based on the Bearfacts proxies. It returns the same custom hashes on error conditions, so that tests can be conveniently bundled in with the other student data proxies.
This simple API endpoint also affords a opportunity to try out a different, VCR-less approach to mocking up web responses. (See https://jira.ets.berkeley.edu/jira/browse/CLC-3383 .) A mock proxy class uses WebMock to intercept HTTP requests and creates a fake response matching the query parameters.

CLC-4909 Add Regstatus API as a new proxy

---

app/controllers/canvas_course_provision_controller.rb
app/models/canvas/course_policy.rb
app/models/canvas/course_provision.rb
app/policies/authentication_state_policy.rb
config/routes.rb
spec/controllers/canvas_course_provision_controller_spec.rb
spec/models/canvas/course_policy_spec.rb
spec/models/canvas/course_provision_spec.rb
src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js
src/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js

https://jira.ets.berkeley.edu/jira/browse/CLC-4949
https://jira.ets.berkeley.edu/jira/browse/CLC-4996
Changing authorization touched enough places that it seemed best to submit this PR separately. Next step is to fill in more course section data in the feed, but that part of the task should have fewer chances of merge conflicts.
* Authorization rules have been changed, made explicit, & moved to the controller.
* A "canEdit" property has been added to the feed to let the front-end know whether to show the Edit button.
* Two API paths were changed to make the authz checks easier and follow existing conventions.
* The Official Sections app can now be run outside an embedded iframe.
TO DO: Add not-an-instructor site section data.

CLC-4949 CLC-4996 Modify bCourses Official Sections authorization rules

---

app/models/oec/course_students.rb
app/models/oec/students.rb
spec/models/oec/file_reader_spec.rb

https://jira.ets.berkeley.edu/jira/browse/OEC-608
ccn_set was modified by merge in student data generation, leading to bad data in course_students generation. I also:
* add a couple log statements
* reorganized the spec for sake of readability

OEC-608, CCN set inadvertantly modified by merge in student data generation

---

src/assets/stylesheets/_profile.scss
src/assets/templates/academics_student_profile.html

Revived from https://github.com/ets-berkeley-edu/calcentral/pull/3487 for @szhu -- please see the earlier PR for comments.
Most students visit the Academics tab to check things other than GPA,
so there's no particular reason for GPA to be larger.
In addition, many students visit CalCentral in public settings and
would prefer to have their GPA less visible to people around them.
This is a temporary solution, but a "show GPA" checkbox might be more
appropriate in the future.

CLC-5003 Remove large size for GPA

---

app/models/my_academics/college_and_level.rb
app/models/my_academics/merged.rb
app/models/my_academics/transition_reg_status.rb
public/dummy/json/academics_transition_no_profile.json
public/dummy/json/academics_transition_not_registered.json
public/dummy/json/academics_transition_registered.json
public/dummy/json/badges_transition.json
spec/models/my_academics/college_and_level_spec.rb
spec/models/my_academics/transition_reg_status_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4910
Merges in registration data only during transitions (as determined by whether the term in the Bearfacts profile matches the current term in CalCentral).
Dummy JSON feeds for different scenarios are also included. In addition to registration-related changes, the `collegeAndLevel` data in the dummies has been made consistent with our current feed structure.

CLC-4910 Merge Regstatus into My Academics feed during term transitions

---

app/controllers/canvas_course_provision_controller.rb
app/models/canvas/course_provision.rb
spec/controllers/canvas_course_provision_controller_spec.rb
spec/models/canvas/course_provision_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4949
Following on from https://github.com/ets-berkeley-edu/calcentral/pull/3498 , this add tests and relocates the last of the model-level authz code to the controller.

CLC-4949 More Course Provisioning / Official Sections authorization cleanup

---

app/models/my_tasks/canvas_tasks.rb
app/models/my_tasks/google_tasks.rb
fixtures/pretty_vcr_recordings/Google_tasks.json
spec/models/my_tasks/my_tasks_spec.rb
src/assets/templates/dashboard_task_loop.html

Include optional email links in Google tasks, per https://jira.ets.berkeley.edu/jira/browse/CLC-5008 . Google tasks have their hard-coded `linkUrl` property replaced with an optional informative value. The front end is made agnostic about task source and will display links for any task with a `linkDescription` property.
On the back end, reworking the task logic provided a good opening for the refactor long requested in https://jira.ets.berkeley.edu/jira/browse/CLC-2246 .

CLC-2246 CLC-5008 Allow tasks from any source to display links

---

app/models/campus_oracle/user_courses/all.rb
app/models/campus_oracle/user_courses/base.rb
app/models/campus_oracle/user_courses/selected_sections.rb
app/models/canvas/course_provision.rb
app/models/canvas/provide_course_site.rb
app/models/my_academics/teaching.rb
spec/models/campus_oracle/user_courses/selected_sections_spec.rb
spec/models/canvas/course_provision_spec.rb
spec/models/canvas/provide_course_site_spec.rb
spec/models/my_academics/teaching_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-4949
Centralize My-Academics-style formatting of arbitrary section lists. (The Canvas-copy-and-paste version had already gone stale.)
Merge arbitrary section data into the normal available-for-course-provisioning feed.
TODO: Standardizing the order of the merged sections.
TODO: RSpec for merge_non_teaching_site_sections.

CLC-4949 Show bCourses site Official Sections without instructor access

---

src/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js
src/assets/templates/canvas_embedded/_shared/sections_table.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5017
Also removes distracting "section already in use" when it's only being used by the current course site in Official Sections.

CLC-5017 Restore "section already in use" for Create Course Site

---

app/models/canvas/course_provision.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5018
Pass by reference strikes again!

CLC-5018 Separate cached user-specific CourseProvision feed from the site-specific feed

---

app/controllers/canvas_course_add_user_controller.rb
app/models/canvas/course_user.rb
spec/controllers/canvas_course_add_user_controller_spec.rb
spec/models/canvas/course_user_spec.rb
src/assets/javascripts/angular/controllers/pages/canvasCourseAddUserController.js

https://jira.ets.berkeley.edu/jira/browse/CLC-4916
Updates the Course User Roles API end-point to include the users role types for authorization in addition to the actual roles. Removes custom roles from the roles hash that were added to temporarily authorize access to the 'Find a Person to Add' tool for the Owner, Maintainer, and Member roles that were introduced to the 'Projects' account.

CLC-4916  - Find a Person to Add: Refactor authorization to respect role type rather than role

---

app/models/my_badges/google_drive.rb
spec/models/my_badges/my_badges_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5026
QA version of #3519.

[QA] CLC-5026 Update path for Google Drive badge icons

---

app/models/my_tasks/google_tasks.rb
spec/models/my_tasks/my_tasks_spec.rb

In light of https://jira.ets.berkeley.edu/jira/browse/CLC-5042, removes the link information added in #3503 without reverting the associated code cleanup.

CLC-5042 Do not display email links for Google tasks

---

script/bamboo-tests.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-4748
Step 1 in getting rid of our archaic Ruby Bamboo plugin dependency. 
This job shows the simplification in Bamboo structure -- we get to drop 2 tasks from the rake stage: https://bamboo.ets.berkeley.edu/bamboo/build/admin/edit/editBuildTasks.action?buildKey=MYB-CLCMVPCHRIS-JOB1

CLC-4748 Run our rake tasks from shell script

---

app/models/canvas/maintain_users.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5063
Multiples of a thousand led to an empty SQL query clause and sudden script termination.

CLC-5063 Do not query an empty list of UIDs from Canvas Refresh

---

spec/models/mediacasts/course_media_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5084
Webcast: recordingStartUTC determines when / how long we show student alerts.

CLC-5084, add recordingStartUTC to real-data test; code conventions

---

spec/models/mediacasts/course_media_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5050
Expected recordingStart date needed change according to a bug fix on the Webcast side. 
Bamboo build against this branch (CLC-5050) was a success: 
https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT41-1

CLC-5050, bug fix in webcast.json feed gives us more exact start times

---

app/models/mediacasts/rooms.rb
app/models/mediacasts/system_status.rb
fixtures/json/rooms.json
fixtures/json/webcast-system-status.json
spec/models/mediacasts/rooms_spec.rb
spec/models/mediacasts/system_status_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5102
Bamboo build: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT43-1
Webcast provides /webcast-system-status.json which has property 'isSignUpActive'=[true | false]. This allows us to take term_yr and term_cd args out of Room class. This is a programmatic way of enabling webcast alerts without adding hard-to-maintain configs.

CLC-5102, webcast-integration in Junction programmatic term transition scheme

---

src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js

https://jira.ets.berkeley.edu/jira/browse/CLC-5036
For admins, the "teachingSemesters" part of the initial feed is filled in from the course site sections. When the site has no sections, there are no "teachingSemesters" in the feed. And that meant the front-end never reached the critical initialization code for "$scope.existingCourseSections": https://github.com/ets-berkeley-edu/calcentral/blob/973056b210423b0e74670349d28351ca67045898/src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js#L68
Since "$scope.existingCourseSections" is key to enabling expected behavior, we should ensure that it's always defined.

CLC-5036 Initialize current list of Official Sections when empty

---

app/models/webcast/course_media.rb
app/models/webcast/recordings.rb
spec/models/webcast/course_media_spec.rb
spec/models/webcast/recordings_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5118
This is the last refactor. The name 'recordings' is succinct and it fits with webcast terminology and the naming in the feed.

CLC-5118, rename all_playlists to recordings (webcast terminology)

---

app/models/berkeley/course_options.rb
app/models/campus_oracle/queries.rb
app/models/campus_oracle/user_courses/base.rb
app/models/my_academics/canvas_sites.rb
app/models/my_academics/semesters.rb
app/models/my_classes/campus.rb
public/dummy/json/academics.json
spec/models/berkeley/course_options_spec.rb
spec/models/campus_oracle/queries_spec.rb
spec/models/campus_oracle/user_courses/base_spec.rb
spec/models/my_academics/canvas_sites_spec.rb
spec/models/my_academics/semesters_spec.rb
spec/models/my_classes/campus_spec.rb
src/assets/javascripts/angular/configuration/routeConfiguration.js
src/assets/javascripts/angular/controllers/pages/academicsController.js
src/assets/javascripts/angular/controllers/widgets/booklistController.js
src/assets/javascripts/angular/services/academicsService.js
src/assets/templates/academics_classinfo.html
src/assets/templates/academics_semesters.html

https://jira.ets.berkeley.edu/jira/browse/CLC-4789
A few notes:
The `course_option` database column, which was only being queried for instructor assignments, is now queried for student enrollments as well because we need it for the edge case of assigning secondary sections among multiple primaries. The value is not included in the final My Academics or My Classes feeds.
Our policy of not exposing section associations for Canvas sites had to be very slightly relaxed in order to point Canvas sites to the correct primary section in the multiple-primaries case. These associations were already exposed in My Classes, and are now exposed in My Academics as well.
The front-end component looks much bigger than it actually is because our collection of utility functions for parsing the academics …

CLC-4789 Separate multiple primary section enrollments in Class Info

---

app/models/cal1card/my_cal1card.rb
app/models/ets_blog/alerts.rb
app/models/ets_blog/release_notes.rb
app/models/regstatus/proxy.rb
config/settings.yml
lib/proxies/mock_http_interaction.rb
lib/proxies/mockable.rb
lib/proxies/mockable_xml.rb
spec/models/cal1card/my_cal1card_spec.rb
spec/models/ets_blog/release_notes_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5052
3 new proxies are now on the Mockable framework. Mockable now correctly handles basic authentication. It also provides a read_file convenience method. And, you can now mock proxies that deliver XML instead of JSON. 
Note: This change requires a settings.yml configuration change: Renaming the feed_url param to base_url in 3 proxies: blog_latest_release_notes_feed_proxy, app_alerts_proxy, cal1card_proxy. Changing the setting will be part of the release notes.

CLC-5052 Expanding the functionality of Mockable

---

app/models/my_academics/academics_module.rb
app/models/my_academics/semesters.rb
app/models/my_academics/teaching.rb
src/assets/javascripts/angular/controllers/pages/academicsController.js
src/assets/javascripts/angular/controllers/widgets/booklistController.js
src/assets/javascripts/angular/controllers/widgets/textbookController.js
src/assets/javascripts/angular/services/academicsService.js
src/assets/stylesheets/_academics.scss
src/assets/templates/academics_class_sites.html
src/assets/templates/academics_classinfo.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5127
Multiple-primary backend code is moved from MyAcademics::Semesters to MyAcademics::AcademicsModule so that MyAcademics::Teaching can use it as well.
textbookController.js is reworked along the lines of booklistController.js to handle concurrent textbook queries for multiple primary sections when necessary. Some common code is extracted to academicsService.js.
The Class Info template is modified to fit the redesign, and the Class Sites card extracted to its own template.

CLC-5127 Reorganize instructor Class Info page for multiple primaries

---

app/models/webcast/preferences.rb
spec/models/webcast/preferences_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5130
Preferences class bound to db table 'webcast_preferences' with spec

CLC-5130, active-record class for webcast_preferences table

---

app/controllers/act_as_controller.rb
app/controllers/stored_users_controller.rb
config/routes.rb
spec/controllers/stored_users_controller_spec.rb
spec/features/act_as_user_spec.rb
src/assets/javascripts/angular/controllers/widgets/studentLookupController.js
src/assets/javascripts/angular/factories/adminFactory.js

https://jira.ets.berkeley.edu/jira/browse/CLC-5150
This saves a couple of Ajax requests (and a bunch of code) by consolidating the recentUser save into the act-as controller code. 
This PR is a little risky (although it is covered by the changes to the act_as_user_spec). If we're feeling conservative for 55, please consider holding off on merge until after tomorrow's QA branch.

CLC-5150 Move deleteRecentUser logic to backend

---

app/models/campus_oracle/connection.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5156
**NOTE**: Wait till after the QA branch has been cut.
This is for 56, not 55.

CLC-5156 - Deprecation warning with establish_connection: use symbol for campusdb

---

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js

See #3642 for QA branch
https://jira.ets.berkeley.edu/jira/browse/CLC-5172
Switched order of error checking and validation to ensure sections are loaded before validating course state

CLC-5172 - E-Grades Export: empty CSVs

---

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js

See #3641 for Development branch
https://jira.ets.berkeley.edu/jira/browse/CLC-5172
Switched order of error checking and validation to ensure sections are loaded before validating course state

[QA] CLC-5172 - E-Grades Export: empty CSVs

---

lib/proxies/mockable.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5177
The use case for this only exists in the sis-master branch at the moment, but I think it's good to get into master.

CLC-5177 Mock request matcher can now handle ports or no ports

---

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js
src/assets/stylesheets/_canvas_base.scss
src/assets/stylesheets/_canvas_buttons.scss
src/assets/stylesheets/_canvas_colors.scss
src/assets/stylesheets/_canvas_course_grade_export.scss
src/assets/stylesheets/_canvas_emulated.scss
src/assets/stylesheets/calcentral.scss
src/assets/templates/canvas_embedded/_shared/back_to_gradebook_link.html
src/assets/templates/canvas_embedded/course_grade_export.html

CLC-5169 - E-Grades Export: Apply 2nd iteration UX changes to error display
https://jira.ets.berkeley.edu/jira/browse/CLC-5169
CLC-5187 - E-Grades Export: "refresh" doesn't re-validate grading scheme or muted assignments
https://jira.ets.berkeley.edu/jira/browse/CLC-5187
See 'master' PR #3646 for un-squashed development branch version.

[QA] CLC-5169 - E-Grades Export: Apply 2nd iteration UX changes to error display

---

public/canvas/canvas-customization.js

@jonmhays noticed a space missing between the download icon and the 'E-Grades' text in the label that we add to the Gradebook. This is a fix for that.
See #3652 for QA PR

NOJIRA - Add space before 'E-Grades' button text, after icon

---

public/canvas/canvas-customization.js

@jonmhays noticed a space missing between the download icon and the 'E-Grades' text in the label that we add to the Gradebook. This is a fix for that.
See #3651 for master PR.

[QA] NOJIRA - Add space before 'E-Grades' button text, after icon

---

lib/tasks/output_xml_results.rake

This reverts commit d689e18448f056e43b3ff67d19f01dda278781b2 which doesn't fix the issue, and will break people's torquebox knob building step.

Revert "CLC-5190 Make sure spec:xml is always defined"

---

app/models/campus_oracle/queries.rb
spec/models/campus_oracle/queries_spec.rb
spec/models/webcast/system_status_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5216
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT50-4
mediacasts_controller will invoke the query get_all_course_sections to pull ccn list per dept, catalog_id. The ccn list will be passed to Webcast code (future PR) and return zero or more sets of recordings.

CLC-5216, get_all_course_sections added to queries.rb; plus query_spec upgrade

---

app/models/cal_groups/find_groups.rb
app/models/cal_groups/get_members.rb
app/models/cal_groups/proxy.rb
config/settings.yml
fixtures/json/cal_groups_find_groups.json
fixtures/json/cal_groups_get_members.json
spec/models/cal_groups/find_groups_spec.rb
spec/models/cal_groups/get_members_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5202
https://jira.ets.berkeley.edu/jira/browse/CLC-5180
NB: New cal_groups_proxy local settings have been added to calcentral-dev. These should be copied over to ets-dev prior to merge, or Bamboo will fail.
Otherwise, trying to hew close to the logic in #3671 for consistency's sake. Like those proxies, these don't currently contemplate caching, but the calls could take a cache wrapper straightforwardly enough.

CLC-5202 First two CalGroups proxies

---

app/models/calmail/add_list_member.rb
app/models/calmail/check_namespace.rb
app/models/calmail/domain_mailing_lists.rb
app/models/calmail/remove_list_member.rb
spec/models/calmail/add_list_member_spec.rb
spec/models/calmail/check_namespace_spec.rb
spec/models/calmail/domain_mailing_lists_spec.rb
spec/models/calmail/list_members_spec.rb
spec/models/calmail/remove_list_member_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5170
I believe these are all the APIs of use to the Mailman integration as currently scoped out.

CLC-5170 Add all CalMail API calls needed for Mailman mailing lists

---

db/migrate/20150430222956_alter_webcast_preferences_table.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5135
Index was on a composite key so remove_index per three columns. No new migrate file here.

CLC-5135, remove_index only reversible if given a :column option

---

db/migrate/20150430222956_alter_webcast_preferences_table.rb
db/schema.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5135
Painful exercise in understanding reversible db migrations.

CLC-5242, db migrate - drop table, etc. - must be reversible

---

app/models/finaid/proxy.rb
config/settings.yml

https://jira.ets.berkeley.edu/jira/browse/CLC-5234
Finaid tests pass on Bamboo with token removed from code.

CLC-5234 Remove obsolete 'token' from MyFinAid proxy

---

spec/ui_selenium/my_academics_data_enrollment_spec.rb
spec/ui_selenium/pages/api_my_academics_page_semesters.rb
spec/ui_selenium/pages/my_academics_class_page.rb
spec/ui_selenium/pages/my_academics_enrollments_card.rb
spec/ui_selenium/pages/my_academics_page.rb
spec/ui_selenium/pages/my_academics_semesters_card.rb

Test updated to include coverage for the following:
* Multiple primary sections:
* On semester cards, appending section codes to course codes under the right circumstances
* Offering multiple class pages for multiple primary sections, also under the right circumstances
* EAP and additional credit
* Verifying the content of cards with transcript data but no enrollment data
The test changes have been verified with the full set of ~180 test user accounts.

CLC-5158: fix enrollments Selenium spec

---

spec/ui_selenium/my_academics_data_advising_appts_spec.rb
spec/ui_selenium/my_academics_data_enrollment_spec.rb
spec/ui_selenium/my_academics_data_final_exams_spec.rb
spec/ui_selenium/my_academics_data_status_blocks_spec.rb
spec/ui_selenium/my_academics_data_telebears_spec.rb
spec/ui_selenium/my_academics_data_webcasts_spec.rb
spec/ui_selenium/my_dashboard_google_live_updates_spec.rb
spec/ui_selenium/my_dashboard_google_tasks_spec.rb
spec/ui_selenium/my_dashboard_google_up_next_spec.rb
spec/ui_selenium/my_finances_data_acct_summary_spec.rb
spec/ui_selenium/my_finances_data_cal1card_spec.rb
spec/ui_selenium/my_finances_data_finaid_spec.rb
spec/ui_selenium/my_finances_data_transaction_detail_spec.rb
spec/ui_selenium/my_finances_ui_details_page_spec.rb
spec/ui_selenium/my_finances_ui_landing_page_spec.rb
spec/ui_selenium/pages/my_finances_details_page.rb
spec/ui_selenium/user_authentication_spec.rb
spec/ui_selenium/user_authorizations_spec.rb
spec/ui_selenium/user_google_connection_spec.rb
spec/ui_selenium/util/web_driver_utils.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5253
Includes the following changes:
* New util method for quitting the browser, which tolerates errors:  this is to overcome situations where the browser hasn't instantiated in the first place.  The subsequent NoMethodError kills the remaining test suite.  Also renamed the command to launch the browser, to better distinguish it from the quit method.
* A hardcoded pause after quitting the browser: this is another experiment to avoid the RuntimeError occasionally encountered when launching the browser.  When one test quits and another launches, the browser instances might be tripping over one another.  In any case, these sporadic errors cause regular build failures.
* Fixed a broken XPath for the finances details test.

CLC-5253: misc fixes for Selenium tests

---

app/models/canvas/external_tools.rb
app/models/canvas/webcast_lti_refresh.rb
app/models/webcast/rooms.rb
lib/tasks/canvas.rake
spec/models/canvas/webcast_lti_refresh_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5134
Bamboo build: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT51-10
Method in Webcast::Rooms need implementation:
```
def any_in_webcast_enabled_room?(ccn_list)
raise RuntimeError, 'Method not implemented'
end
``` 
That said, the GET/PUT calls to Canvas tabs API are done. Please let me know if they need work.

CLC-5134, add Canvas API call to show Webcast tab when appropriate

---

app/models/mailing_lists/site_mailing_list.rb
config/initializers/rails_admin.rb
db/migrate/20150430231721_create_canvas_site_mailing_lists.rb
db/schema.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5212
This is a dependency for both the admin app side and the membership refresh script side of bCourses site mailing lists. Once it's in place, either side should be doable semi-independently. CCAdmin can be used to create mailing-list-associations by hand for early testing of refresh script logic.

CLC-5211 New DB table for bCourses site mailing lists

---

spec/ui_selenium/my_dashboard_google_live_updates_spec.rb
spec/ui_selenium/my_dashboard_google_tasks_spec.rb
spec/ui_selenium/my_dashboard_google_up_next_spec.rb
spec/ui_selenium/pages/settings_page.rb
spec/ui_selenium/user_authorizations_spec.rb
spec/ui_selenium/user_google_connection_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5120
These changes restore the view-as and look-up portions of the User Authorizations spec to the former UI (see CLC-5203), also removing supporting code that pertained to the formerly-new UI.

CLC-5120: fix view-as tests again

---

app/models/canvas/external_tools.rb
app/models/canvas/report.rb
app/models/canvas/sections_report.rb
app/models/webcast/audio.rb
spec/models/webcast/audio_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5242
Bamboo build: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT51-19
Few related changes in this PR:
* class that pulls from Webcast audio RSS must tolerate 404s
* optional options hash to Faraday connection so you can config in dev (e.g., ssl verify: false)
* ExternalTools needs proper method-PUT syntax in update_canvas_course_site_tab

CLC-5134, ExternalTools : update_canvas_course_site_tab needs proper method PUT

---

app/views/canvas_lti/lti_course_mediacasts.xml.erb
app/views/canvas_lti/lti_course_webcast_sign_up.xml.erb

It means teachers and students. Only "public" links can be seen by other types of site members, such as observers.
https://jira.ets.berkeley.edu/jira/browse/CLC-5272

CLC-5272 LTI app visibility "members" does not mean members

---

app/models/canvas/report.rb
app/models/canvas/sections_report.rb
app/models/canvas/webcast_eligible_courses.rb
app/models/canvas/webcast_lti_refresh.rb
lib/tasks/canvas.rake
spec/models/canvas/webcast_eligible_courses_spec.rb
spec/models/canvas/webcast_lti_refresh_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5256
Changes / fixes:
* Only allow ssl override to Faraday; otherwise nil
* check for 'has Webcast recordings' needs explicit [:videos] check
* clean up logger statements
Waiting on Bamboo, too: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT51-22

CLC-5256, restrict options sent to Faraday; bug fix on recordings.has_key?

---

lib/tasks/canvas.rake

https://jira.ets.berkeley.edu/jira/browse/CLC-5134
The rake task webcast_lti_refresh code does not need to know about our SSL verification problems.

CLC-5134, remove use of SKIP_CANVAS_SSL_VERIFY option in rake task

---

spec/ui_selenium/my_academics_data_enrollment_spec.rb
spec/ui_selenium/my_academics_data_final_exams_spec.rb
spec/ui_selenium/my_academics_data_teaching_spec.rb
spec/ui_selenium/pages/api_my_academics_page_semesters.rb
spec/ui_selenium/pages/my_academics_class_page.rb
spec/ui_selenium/pages/my_academics_classes_card.rb
spec/ui_selenium/pages/my_academics_page.rb
spec/ui_selenium/pages/my_academics_teaching_card.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5269
This is a new test to cover what instructors see in the Academics UI.  The test iterates through UIDs, checking the teaching semester information that appears in the Academics landing page, semester pages, and class pages.
There is also some minor refactoring and reorganizing of code already used by the student academics test, since there is much overlap with this new test.

CLC-5269: Selenium test for academics teaching UI

---

app/models/webcast/merged.rb
app/models/webcast/recordings.rb
app/models/webcast/rooms.rb
app/models/webcast/sign_up_eligible.rb
app/models/webcast/system_status.rb
fixtures/webcast/eligible-for-webcast.json
fixtures/webcast/webcast.json
spec/models/webcast/merged_spec.rb
spec/models/webcast/recordings_spec.rb
spec/models/webcast/sign_up_eligible_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5299
This bug has to do with the deprecated :video and :audio elements of Webcast merged feed. In the case of cross-listings we were merging all recordings into an array and thus the duplicates. My fix is to use a Set object instead. I added a test to verify.

CLC-5299, Webcasts: recordings duplicated on cross-listed course

---

app/models/user/recent_uid.rb
spec/models/user/stored_users_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5157
The number 30 is a wild guess at what looks reasonable in the new/old UI. This can be changed.

View As: limit number of Recent Users to 30

---

app/controllers/config_controller.rb

The real fix happened in a different commit, https://github.com/ets-berkeley-edu/calcentral/pull/3629
Revert "CLC-5104 Skipping reauth should help ConfigController not return 302s"
This reverts commit 7365dbf305df631b0111b2206e4a5edb78019d86.

Revert SIS fix to CLC-5104 

---

app/controllers/stored_users_controller.rb
app/models/user/stored_users.rb
spec/models/user/stored_users_spec.rb
src/assets/templates/settings.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5292
Note that this reverts the change in #3725 to StoredUsersController#store_saved_uid, which removed a user from the Recent Users list after saving.

CLC-5292 Allow saved users to appear under Recent Users without save link

---

spec/models/cal_groups/find_groups_spec.rb
spec/models/cal_groups/member_check_spec.rb
spec/models/cal_groups/members_check_spec.rb
spec/models/cal_groups/members_get_spec.rb

This should temporarily clear up Bamboo failures while waiting on a fix for https://jira.ets.berkeley.edu/jira/browse/CLC-5251 .

CLC-5251 Ignore testext specs for CalGroups proxies

---

app/controllers/canvas_mailing_lists_controller.rb
app/models/mailing_lists/site_mailing_list.rb
config/routes.rb
config/settings.yml
lib/tasks/mailing_lists.rake
public/dummy/json/canvas_site_mailing_list_bad_site.json
public/dummy/json/canvas_site_mailing_list_created.json
public/dummy/json/canvas_site_mailing_list_new.json
public/dummy/json/canvas_site_mailing_list_pending.json
spec/controllers/canvas_mailing_lists_controller_spec.rb
spec/models/mailing_lists/site_mailing_list_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5212
This PR includes:
- Dummy JSON based on @raydavis's front-end sketchwork;
- Back-end code required to generate that JSON;
- A simple rake task exercising portions of that back-end code to repopulate all mailing lists registered in the local database.

CLC-5211 CLC-5212 Backend and rake task for site mailing lists

---

app/models/berkeley/term_codes.rb
app/models/calmail/proxy.rb
app/models/mailing_lists/site_mailing_list.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5212
Follow-up to #3765 based on code review and testing.
- Force-downcase email addresses from campus data to match Mailman's internal storage;
- Fix logging in the SiteMailingList class and add logging to the Calmail proxies;
- Use `Hash#to_param` to build the list creation URL;
- Move term code abbreviation to Berkeley::TermCodes.

CLC-5211 CLC-5212 Site mailing lists: back-end followup

---

config/settings.yml

https://jira.ets.berkeley.edu/jira/browse/CLC-5322
DO NOT MERGE until Bamboo passes: 
https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT54-1
With the v57 release we will cut over to new Webcast sub-domain: webcast-cc. The Webcast dev and qa environments have already been moved to new sub-domain.
Why? Because ETS' Events and Production team would like to claim _video.berkeley.edu_.

CLC-5322, new Webcast domain name: webcast-cc

---

app/models/webcast/audio.rb
app/models/webcast/course_media.rb
app/models/webcast/merged.rb
spec/models/webcast/audio_spec.rb
spec/models/webcast/course_media_spec.rb
spec/models/webcast/merged_spec.rb
spec/models/webcast/recordings_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5329
Notes:
* We log errors related to HTTP GET of audio RSS but we no longer put error info in merged feed
* New specs to make sure code sees a difference between (1) courses with zero recordings and (2) courses not signed up for Webcast
* simple renaming in course_media.rb

CLC-5329, tolerate Webcast audio RSS 404; don't bother front-end with such problems

---

app/models/campus_oracle/course_sections.rb
spec/models/campus_oracle/course_sections_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5217
Webcast front-end needs to know about instructor_func. PR includes refactor of course_sections_spec.rb
Note: In an upcoming PR the Webcast merged feed will leverage this change in order to put "webcast authorized" instructors in its front-end api

CLC-5217, instructor_func added to instructors_feed; update course_sections_spec

---

app/controllers/mediacasts_controller.rb
app/models/canvas/webcast_eligible_courses.rb
app/models/canvas/webcast_recordings.rb
app/models/webcast/course_media.rb
app/models/webcast/merged.rb
spec/controllers/mediacasts_controller_spec.rb
spec/models/canvas/webcast_recordings_spec.rb
spec/models/webcast/course_media_spec.rb
spec/models/webcast/merged_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5209
Work necessary to support Webcast widget work:
* Use MyAcademics::Teaching to fold in section metadata. E.g., instructors authorized to sign up.
* Webcast::Merged is now UserSpecificModel.
* We put nothing in feed when CCN has no webcast. Previously, there was an error message, of sorts. 
* remove list of webcast enabled rooms from front-end api until it's necessary

CLC-5209, merged webcast feed includes section and instructor metadata

---

app/models/webcast/proxy.rb
spec/models/webcast/merged_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5209
DO NOT MERGE until https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT55-1 passes
* Fix to Bamboo failure: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPMASTER-3049/
* Remove the now obsolete :video_error_message => 'No Webcast data found'

CLC-5209, we return nil instead of 'No Webcast data found'

---

spec/models/webcast/course_media_spec.rb

We refreshed Webcast's QA env with production webcast.json which does not have the recordingStartUTC property because that feature is not yet live. I've commented out the line in spec and created a Jira: https://jira.ets.berkeley.edu/jira/browse/WCT-5456

NOJIRA, fix spec w.r.t recordingStartUTC feature

---

app/models/calmail/proxy.rb
spec/models/calmail/check_namespace_spec.rb

A workaround for https://jira.ets.berkeley.edu/jira/browse/CLC-5346.

CLC-5346 Set explicit user agent on Calmail proxy requests

---

script/start-torquebox.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-2890
Changes log file lines like:
``3069.896: [GC3069.896: [ParNew: 439129K->21021K(460800K), 0.0239510 secs] 1099234K->684402K(3020800K), 0.0242140 secs] [Times: user=0.09 sys=0.00, real=0.03 secs] ``
to log file lines like:
``2015-06-01T14:58:40.732+0800: [GC (Allocation Failure)2015-06-01T14:58:40.732+0800: [ParNew: 409600K->22682K(460800K), 0.0224090 secs] 409600K->22682K(1996800K), 0.0224830 secs] [Times: user=0.08 sys=0.01, real=0.02 secs] ``

CLC-2890 Improve garbage collection logging in Torquebox

---

app/models/webcast/merged.rb
spec/models/canvas/webcast_recordings_spec.rb
spec/models/webcast/merged_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5363

CLC-5363, Zero-padding needed on certain CCNs in Junction's Webcast feed

---

app/models/mailing_lists/site_mailing_list.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5374
1. Once Calmail confirms list creation, save state right away to avoid redundant queries;
2. Don't bother asking Calmail about the blank list names that RailsAdmin initializes as part of its business.

CLC-5374 Make model callbacks play more nicely with RailsAdmin

---

app/models/webcast/course_media.rb
app/models/webcast/merged.rb
app/models/webcast/proxy.rb
app/models/webcast/sign_up_eligible.rb
app/models/webcast/system_status.rb
fixtures/webcast/eligible-for-webcast.json
spec/controllers/mediacasts_controller_spec.rb
spec/models/canvas/webcast_recordings_spec.rb
spec/models/webcast/course_media_spec.rb
spec/models/webcast/merged_spec.rb
spec/models/webcast/recordings_spec.rb
spec/models/webcast/rooms_spec.rb
spec/models/webcast/sign_up_eligible_spec.rb
spec/models/webcast/system_status_spec.rb
src/assets/templates/widgets/webcast.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5376
https://jira.ets.berkeley.edu/jira/browse/CLC-5377
DO NOT https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT55-JOB1-19 passes
FYI
* structure changed from  *[media][year][term] = hash-per-ccn*   to   *[media] = array-of-sections*
* all keys in merged feed (consumed by front-end) are camelCase
* feed now includes *:thisUserCanSignUp* which is based on user's ldap_uid

CLC-5376, camelCase and flattened structure in feed to Webcast front-end

---

fixtures/webcast/warehouse/webcast.json
spec/models/webcast/merged_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5394
Bug is already fixed on master. This spec hopes to prevent future breakage.

CLC-5394, spec to verify iTunes audio when iTunes video is nil

---

app/models/campus_oracle/user_attributes.rb
app/models/my_badges/student_info.rb
app/models/notifications/reg_status_translator.rb
spec/models/campus_oracle/user_attributes_spec.rb
spec/models/my_academics/exams_spec.rb
spec/models/my_badges/student_info_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5408
The most expedient approach to a quieter /my/badges feed:
1. Check if the CalCentral current term is not considered current in campus data;
2. If so, return nil registration data from CampusOracle::UserAttributes;
3. Have MyBadges::StudentInfo attempt to fill in that nil data by calling out to MyAcademics::TransitionRegStatus;
3a. If the student is registered for the CalCentral current term, say so;
3b. If the student is not registered for the CalCentral current term, pass along null, no-action-required data that won't trigger front-end alerts.

CLC-5408 Quell registration alerts during term transitions

---

app/policies/authentication_state.rb
app/policies/authentication_state_policy.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5403  (Closed #3876 in favor of this PR)
The method changed in authentication_state.rb was returning nil instead of false. My spec didn't like that. I think a non-nil return value is more intuitive.

CLC-5403, show sign-up text in CalCentral if user.viewing_as?

---

src/assets/templates/widgets/academic_profile_popover.html

Fix for the missing badges reported in comments to https://jira.ets.berkeley.edu/jira/browse/CLC-5408.
Use of a null regstatus wiped out the entire popover. The toggle removed here has been in the code a long time and seems to have been supplanted by finer-grained toggles within the template. Browser testing on a small batch of UIDs didn't turn up any bad behavior.

CLC-5408 Restore student alert popover when registration data missing

---

src/assets/templates/widgets/badges_popover.html

@christianv quickly caught that #3879 as it stands will reintroduce https://jira.ets.berkeley.edu/jira/browse/CLC-4045, and pointed out the fix.

CLC-5408 Avoid reintroducing CLC-4045

---

app/controllers/canvas_webcast_recordings_controller.rb
app/controllers/mediacasts_controller.rb
app/models/canvas/webcast_recordings.rb
app/models/webcast/merged.rb
spec/controllers/canvas_webcast_recordings_controller_spec.rb
spec/models/canvas/webcast_recordings_spec.rb
spec/models/webcast/merged_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5403
Follow up to #3877
What to notice:
* policy object passed to Merged class
* we use can_view_webcast_sign_up?  to determine who on the front-end gets webcast sign-up info
* one enhancement to the feed: 
** boolean userCanSignUpOneOrMore determines boilerplate in the widget 
** boolean userCanSignUp determines whether we show sign-up link per section

CLC-5403, CoursePolicy paradigm to manage auth in webcast merged feed

---

src/assets/javascripts/angular/controllers/widgets/webcastController.js
src/assets/stylesheets/_webcast.scss
src/assets/templates/widgets/webcast.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5218
https://jira.ets.berkeley.edu/jira/browse/CLC-5215
This PR is focused on getting the content right, not the tab styles. Styling comes next. QA will begin testing by verifying scenarios. E.g., sign-up links surface per CSIR code.
We will use the same widget code in bCourses and CalCentral. But it will render appropriately based on context. For example:
* For instructors and students, the tabbed design and sign-up links will only surface in bCourses, not CalCentral.
* For standard users in CalCentral, the Webcast card will not change. But, for the purpose of debugging and development, users with view-as privileges will see sign-up info in non-production environments.

CLC-5218, webcast widget with tabs, boilerplate and sign-up links

---

spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb
spec/ui_selenium/my_academics_data_status_blocks_spec.rb
spec/ui_selenium/pages/api_my_academics_page.rb
spec/ui_selenium/pages/my_academics_profile_card.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5450
Updates the logic in the existing "status and blocks" spec to incorporate the new handling of term transition periods in the status popover and in the My Academics UI.

CLC-5450: fix Selenium tests for reg status

---

app/controllers/canvas_webcast_recordings_controller.rb
app/controllers/mediacasts_controller.rb
app/models/canvas/webcast_recordings.rb
app/models/webcast/merged.rb
spec/controllers/canvas_webcast_recordings_controller_spec.rb
spec/models/canvas/webcast_recordings_spec.rb
spec/models/webcast/merged_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5452
This problem was caused by wrong id passed to fetch_from_cache in Canvas::WebcastRecordings class.   The id was @canvas_course_id and it's now "#{@canvas_course_id}/#{@uid}"

CLC-5452, Webcast: instructor of record does not have sign-up UI

---

app/models/my_academics/academics_module.rb
app/models/my_activities/merged.rb
app/models/my_activities/webcasts.rb
fixtures/webcast/warehouse/webcast.json
spec/models/my_activities/webcasts_spec.rb
src/assets/javascripts/angular/controllers/widgets/webcastController.js
src/assets/javascripts/angular/factories/activityFactory.js
src/assets/templates/widgets/activity_list.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5106
- Webcast recordings from current-term courses dated within the last ten days will appear in Recent Activity.
- A new 'linkText' property overrides the 'More info' text with 'View webcast.'
- Clicking 'View webcast' passes the recording's YouTube ID to the Class Info page and pre-selects the proper recording in the Webcasts widget.

CLC-5106 Show webcast recordings in Recent Activity

---

app/models/canvas/external_tools.rb
app/models/canvas/webcast_lti_refresh.rb
spec/models/canvas/external_tools_spec.rb
spec/models/canvas/webcast_lti_refresh_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5453
This does not resolve the Jira but I would like to run webcast-cron with 'id' passed in body of the HTTP PUT. I'm also passing 'position' and 'visibility' to rule out their necessity.

CLC-5453, extra args for tab api; cleanup in find_canvas_course_tab()

---

spec/ui_selenium/my_dashboard_google_up_next_spec.rb
spec/ui_selenium/my_finances_ui_details_page_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5476
Fixes two tests: one that sorts and filters Oski's financial transactions and another that tests Up Next.

CLC-5476: fix two WebDriver tests

---

app/models/campus_oracle/user_attributes.rb
spec/models/campus_oracle/user_attributes_spec.rb
src/assets/templates/academics_status_and_blocks.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5419
Back to the blunt hammer! No one, resident or not, sees any residency status during term transitions including summer.

CLC-5419 Do not surface residency status during term transitions

---

spec/ui_selenium/my_academics_data_status_blocks_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5419
Suppressing residency breaks QA's test, which expects it to be visible regardless of term.  The test now checks for a transition term before assuming residency is present.

CLC-5419: fix Selenium residency test

---

spec/models/berkeley/course_policy_spec.rb

Bamboo failure https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPMASTER-3159  gives confusing summary, "...#can_view_roster_photos? when webcast content...". I'm fixing the 'describe' and hoping Bamboo behaves on second try.

NOJIRA, relevant describe for subset of webcast related expectations

---

app/models/campus_oracle/user_attributes.rb
app/models/my_badges/student_info.rb
spec/models/campus_oracle/user_attributes_spec.rb
spec/models/my_badges/student_info_spec.rb

One more rejiggering of the summer registration logic. 
In the case of nil registration status during a term transition, check MyAcademics::TermTransition and,
- If registered, override;
- If not registered, let the nil status pass through.
See https://jira.ets.berkeley.edu/jira/browse/CLC-5431 for motivation and https://jira.ets.berkeley.edu/jira/browse/CLC-5433 for a corollary.

CLC-5431 CLC-5433 Allow regstatus feed to override nil registration status during term transitions

---

spec/ui_selenium/my_academics_data_webcasts_spec.rb
spec/ui_selenium/pages/my_academics_class_page.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5488
The previous test fix for the webcast UI changes didn't handle the UI well enough.  This should provide better timing while elements load and better control of elements in the iframe.

CLC-5488: Selenium test for webcast fix

---

app/models/my_activities/canvas_activities.rb
spec/models/my_activities/canvas_spec.rb
src/assets/javascripts/angular/factories/activityFactory.js

https://jira.ets.berkeley.edu/jira/browse/CLC-5482 has incorporated much of https://jira.ets.berkeley.edu/jira/browse/CLC-2107.
See CLC-5482 on the motivation for the `activityFactory.js` changes, which cover the rare case of a course site associated with multiple campus courses.

CLC-2107 CLC-5482 Set source of course-site activities to campus course code

---

public/canvas/canvas-customization.js
src/assets/javascripts/angular/services/utilService.js

In order to provide better scrolling support between an LTI iFrame and the parent container, I've added a `getScrollInformation` event that will respond with the scroll information such as:
- LTI iFrame height
- Parent container height
- Current scroll position
- Current distance to bottom of screen
All other scrolling support events will now also respond with the same scroll information.
This will make it possible to add infinite scrolling capabilities to tools such as Collabosphere.

CLC-5501 - Extend scrolling support in canvas-customization.js

---

config/deploy.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5504
Rearranges the capistrano file so that the first node is online sooner.

CLC-5504 Make first node available ASAP

---

app/models/webcast/sign_up_eligible.rb
spec/models/webcast/recordings_spec.rb
spec/models/webcast/sign_up_eligible_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5507
And a touch of cleanup on recordings_spec

CLC-5507, Webcast::SignUpEligible error (backend) when eligible-for-webcast.json feed is empty

---

app/models/canvas/merged_user_sites.rb
app/models/my_activities/canvas_activities.rb
spec/models/canvas/merged_user_sites_spec.rb
spec/models/my_activities/canvas_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5520
Fixes an association that was broken by integer/string mismatch, and extends the course-site improvement in #3968 to cover group sites as well.

CLC-5520 Fix course associations for Canvas group sites

---

app/models/my_activities/dashboard_sites.rb
app/models/my_classes/campus.rb
app/models/my_classes/canvas.rb
app/models/my_classes/classes_module.rb
app/models/my_classes/merged.rb
app/models/my_classes/sakai_classes.rb
spec/models/my_classes/campus_spec.rb
spec/models/my_classes/canvas_spec.rb
spec/models/my_classes/merged_spec.rb
spec/models/my_classes/sakai_classes_spec.rb
spec/models/rosters/campus_spec.rb

See https://jira.ets.berkeley.edu/jira/browse/CLC-5371 for motivation.
A `gradingInProgressClasses` key is added to My Classes for the four-week period after end of term, when grading information is likely to show up. This surfaces no new information in My Classes, but lets the Recent Activity widget associate announcements with recently completed courses.
It might have been more elegant to arrange the My Classes semesters in an array, as with My Academics, but it's clearly more pragmatic to leave existing feed elements alone.

CLC-5371 Add grading-in-progress term information to My Classes feed

---

app/models/canvas/external_tools.rb
spec/models/canvas/external_tools_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5526
When we use the Canvas Tab API we must avoid collateral damage. I.e., changes to 'hidden' property on non-targeted tabs. Therefore, the extraneous tabs are self-healing.

CLC-5526, Canvas Tab API bug + Webcast cron = workaround B

---

app/controllers/blog_feed_controller.rb
app/models/ets_blog/alerts.rb
app/models/ets_blog/release_notes.rb
app/models/ets_blog/rss_proxy.rb
app/models/ets_blog/service_alerts.rb
app/models/my_badges/merged.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml
config/settings/testext.yml
fixtures/xml/service_alerts_feed.xml
fixtures/xml/service_alerts_feed_diacriticals.xml
fixtures/xml/service_alerts_feed_empty.xml
fixtures/xml/service_alerts_feed_title_only.xml
public/dummy/json/badges.json
public/dummy/json/badges_registration_alert.json
public/dummy/json/badges_transition.json
public/dummy/json/blog.json
public/dummy/json/status.json
public/dummy/json/status_loggedout.json
spec/controllers/blog_feed_controller_spec.rb
spec/models/ets_blog/alerts_spec.rb
spec/models/ets_blog/release_notes_spec.rb
spec/models/ets_blog/service_alerts_spec.rb
src/assets/javascripts/angular/controllers/pages/splashController.js
src/assets/templates/alerts.html
src/assets/templates/splash.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5427
I got rid of two obsolete feature flags before adding the new one.
After the transition to the new feed sources, we'll want to delete the old "Alerts" class.

CLC-5427 Add new feed source for Alerts / Release Notes

---

app/models/canvas/course_assignments.rb
app/models/canvas/course_user.rb
app/models/canvas/external_tools.rb
app/models/canvas/proxy.rb
app/models/canvas/section_enrollments.rb
app/models/canvas/user_courses.rb
spec/models/canvas/authorization_configs_spec.rb
spec/models/canvas/course_assignments_spec.rb
spec/models/canvas/course_enrollments_spec.rb
spec/models/canvas/course_sections_spec.rb
spec/models/canvas/course_settings_spec.rb
spec/models/canvas/course_spec.rb
spec/models/canvas/course_user_spec.rb
spec/models/canvas/course_users_spec.rb
spec/models/canvas/external_tools_spec.rb
spec/models/canvas/groups_spec.rb
spec/models/canvas/section_enrollments_spec.rb
spec/models/canvas/sis_course_spec.rb
spec/models/canvas/sis_user_profile_spec.rb
spec/models/canvas/terms_spec.rb
spec/models/canvas/user_activity_stream_spec.rb
spec/models/canvas/user_courses_spec.rb
spec/models/canvas/user_profile_spec.rb
spec/support/canvas_shared_examples.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5564
`Canvas::Proxy#paged_get` is changed to patch leaky exception handling and guarantee the response body that other classes are expecting, by default an empty array.
Tests are tightened up, and the expectation is made clearer that on request failure, a paged proxy will return an empty array under `:body`, but an unpaged proxy will not return `:body`. 
For ease in testing, some short Canvas proxy methods are split into two even shorter methods: one returning a full response with headers, and another returning the body alone.

CLC-5564 Have paged Canvas proxies return empty array on failure

---

app/models/calmail/add_list_member.rb
app/models/calmail/remove_list_member.rb
app/models/mailing_lists/site_mailing_list.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5558
@raydavis should sign off before merge.
- New members default to moderated.
- Production Calmail seems to evaluate Boolean query parameters as true, no matter what the value. Only if they are omitted entirely from the query will they default to false.

CLC-5558 Change default mailing list settings: moderated, less verbose

---

src/assets/templates/widgets/webcast.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5469
https://jira.ets.berkeley.edu/jira/browse/CLC-5381
Vague phrases are never incorrect. Maybe "course captures" are coming and maybe they're not... The LTI app does not know the answer.

CLC-5469, 'Horn says 'recordings scheduled' but CalCentral says 'no recordings scheduled'

---

app/controllers/campus_solutions_controller.rb
app/models/campus_solutions/aid_years.rb
app/models/campus_solutions/financial_data.rb
app/models/campus_solutions/my_aid_years.rb
app/models/campus_solutions/my_financial_data.rb
app/models/campus_solutions/proxy.rb
config/routes.rb
fixtures/xml/campus_solutions/aid_years.xml
fixtures/xml/campus_solutions/financial_data.xml
spec/controllers/campus_solutions_controller_spec.rb
spec/models/campus_solutions/aid_years_spec.rb
spec/models/campus_solutions/financial_data_spec.rb

Covers several backend JIRAs in one PR: 
https://jira.berkeley.edu/browse/SISRP-5147
https://jira.berkeley.edu/browse/SISRP-5148
https://jira.berkeley.edu/browse/SISRP-5164
Front-end isn't hooked up yet because there are a couple of points of disagreement to discuss: 
1) The "feed" key at the top of each CS-derived feed
2) The treatment of things that are plural in the dummy JSON but which are derived from XML arrays (e.g. item[]).

SISRP-5147 SISRP-5148 SISRP-5164 APIs for T&Cs, Title IV, Cost of Attendance

---

app/models/canvas_lti/external_app_configurations.rb
app/models/canvas_lti/webcast_eligible_courses.rb
app/models/canvas_lti/webcast_lti_refresh.rb
app/models/my_activities/webcasts.rb
app/views/canvas_lti/lti_course_mediacasts.xml.erb
spec/models/my_activities/webcasts_spec.rb
src/assets/javascripts/angular/controllers/widgets/webcastController.js
src/assets/javascripts/angular/factories/activityFactory.js
src/assets/templates/academics_classinfo.html
src/assets/templates/academics_student_profile.html
src/assets/templates/widgets/webcast.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5553
https://jira.ets.berkeley.edu/jira/browse/WCT-5478
Includes name change in:
* LTI app
* My Activities
* Widget
The term "webcast" is still pervasive in the code (e.g., 'type' attribute in my_activities feed). My changes only apply to user-facing text.

CLC-5553, rename Webcast service to 'Course Capture'

---

spec/ui_selenium/my_dashboard_google_up_next_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5591
The existing Selenium test for Google events verifies the organizer in the Up Next card.  For now, the test will expect the organizer's email address rather than display name.

CLC-5591: Fix Selenium UpNext test to expect organizer email

---

app/controllers/campus_solutions_controller.rb
app/models/campus_solutions/direct_proxy.rb
app/models/campus_solutions/integration_hub_proxy.rb
app/models/campus_solutions/my_terms_and_conditions.rb
app/models/campus_solutions/my_title4.rb
app/models/campus_solutions/posting_proxy.rb
app/models/campus_solutions/proxy.rb
app/models/campus_solutions/terms_and_conditions.rb
app/models/campus_solutions/title4.rb
config/routes.rb
config/settings.yml
fixtures/xml/campus_solutions/terms_and_conditions.xml
fixtures/xml/campus_solutions/title4.xml
spec/controllers/campus_solutions_controller_spec.rb
spec/models/campus_solutions/terms_and_conditions_spec.rb
spec/models/campus_solutions/title4_spec.rb

Addresses https://jira.berkeley.edu/browse/SISRP-5147 and https://jira.berkeley.edu/browse/SISRP-5148 .
The front end does not yet call these endpoints. Here's how to do that: 
POST /api/campus_solutions/terms_and_conditions?uc_response=Y&aid_year=2016
POST /api/campus_solutions/title4?uc_response=N
Or put params in the form body and Rails will figure it out. 
Both T&C and Title4 go thru the hub. Params are sent to CS via the hub as an XML document. We use Rails to_xml to convert. It needs a couple of specific options because CS will choke on whitespace/newline.

SISRP-5147 and SISRP-5148 - T&C and Title4 POST endpoints

---

app/models/my_badges/merged.rb
spec/controllers/my_badges_controller_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5613
If this tests out on calcentral-dev, it will have to go into the interim release as well.

CLC-5613 Ugly temporary fix for our double-alerts-feed marquee

---

config/settings.yml

https://jira.ets.berkeley.edu/jira/browse/CLC-5650
This may not be the whole problem, but it certainly plays a key part.

CLC-5650 Give the new Service Alerts feed a short cache life

---

app/models/campus_solutions/address.rb
app/models/campus_solutions/aid_years.rb
app/models/campus_solutions/awards.rb
app/models/campus_solutions/budget.rb
app/models/campus_solutions/checklist.rb
app/models/campus_solutions/financial_aid_data.rb
app/models/campus_solutions/financial_aid_expiry.rb
app/models/campus_solutions/my_financial_aid_data.rb
app/models/campus_solutions/my_terms_and_conditions.rb
app/models/campus_solutions/my_title4.rb
lib/cache/related_cache_key_tracker.rb

https://jira.berkeley.edu/browse/SISRP-6245
Whenever a POST to CS happens for T&C or Title4, the AidYears and FinancialAidData feeds get cache cleared as well. Also, other FinAid classes now participate correctly in the UserCacheExpiry scheme. 
Motivation for the RelatedCacheKeyTracker module: FinancialAidData feed needs two keys to work: uid and aid_year. This is because it's one-year-at-a-time. Since the feed needs two keys, so does its associated cache. Unfortunately, the UserCacheExpiry system (upon which HotPlate and LiveUpdates rely) can only expire based on uid. The set of uid-year keys cached by FinancialAidData remain unknown to UserCacheExpiry. So, we use RelatedCacheKeyTracker to record linked keys by uid as they go into the cache. That way we can expire them when …

SISRP-6245 Expire cache for finaid endpoints when doing a POST

---

app/models/google_apps/client.rb
app/models/google_apps/credential_store.rb
app/models/google_apps/drive_manager.rb
app/models/google_apps/proxy.rb
config/settings.yml
spec/models/google_apps/credential_store_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5646
https://jira.ets.berkeley.edu/jira/browse/CLC-5639
Changes include:
* YAML scheme to support custom google api credentials
* CredentialStore class which aligns with Google API convention and follows our convention
* DriveManager provides CRUD operations. I don't see a need for a class per CRUD type.

CLC-5639, DriveManager class can create dir and upload file; plus YAML scheme

---

app/models/google_apps/drive_manager.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5639
Google Drive is strange. A folder can have multiple items with the same name. Furthermore, an item can belong to multiple folders (i.e., parents).  The new methods in this PR try to account for such rules.

CLC-5639, find_folders_by_title and find_items_by_title (more generic)

---

db/developer-seed-data.sql

Please do not merge until Bamboo is happy: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPT139-10/
https://jira.ets.berkeley.edu/jira/browse/CLC-5620
The raw SQL used by the `db:seed` rake task was not explicitly dropping the new `oec_course_codes` table before rebuilding.
Also making `catalog_id` non-nullable, as specified in the migration.

CLC-5620 Follow-up: fix Bamboo failure

---

app/controllers/google_auth_controller.rb
config/settings.yml

https://jira.ets.berkeley.edu/jira/browse/CLC-5635
In google_auth_controller, scope was set as an array. Now we're passing in a set of space-separated values. The underlying OAuth2::Client code is flexible and can handle both:
case new_scope
when Array
...
when String
@scope = new_scope.split(' ')

CLC-5635, 'scope' value used by google_auth_controller is now set in yml 

---

app/controllers/google_auth_controller.rb
spec/controllers/google_auth_controller_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5635
Includes:
* rspec 3 treatment
* rename *get_client* to more accurate *get_google_api_auth*
* readability in *get_google_api_auth* method

CLC-5635, clean up GoogleAuthController and spec

---

app/models/google_apps/drive_manager.rb
spec/models/google_apps/drive_manager_spec.rb

In setting up Drive tasks for https://jira.ets.berkeley.edu/jira/browse/CLC-5654, I realized that one requirement I forgot to specify was copying a file to a new folder without having to download and re-upload.
The Drive API takes three steps to implement this action (duplicate file, add new parent, remove old parent). Fortunately, the new DriveManager class is nicely built and gives clear patterns to follow.
`find_folders` convenience method also thrown in.

CLC-5654 Add Google Drive methods to move files between folders

---

app/models/google_apps/drive_manager.rb
app/models/oec/course_instructors.rb
app/models/oec/course_supervisors.rb
app/models/oec/courses.rb
app/models/oec/csv_export.rb
app/models/oec/instructors.rb
app/models/oec/supervisors.rb
app/models/oec/task.rb
app/models/oec/term_setup_task.rb
spec/models/oec/term_setup_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5654
- Oec::TermSetupTask inherits from Oec::Task, which holds a lot of lower-level logic expected to be shared between tasks.
- Different CSV formats are defined as skeletal subclasses of Oec::CsvExport.
- DriveManager gets some logging and exception handling. Since it's quite a different animal from our usual proxies, there was unfortunately no good way to test the term setup task other than a lot of fiddly expectation-setting on a mock object.

CLC-5654 Implement term setup task

---

app/models/google_apps/credential_store.rb
app/models/google_apps/proxy.rb
config/settings.yml
spec/models/google_apps/proxy_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5604
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT60-2
Includes:
* More test coverage
* fake data: *refresh_token* override to go with existing *access_token* override

CLC-5604, new proxy_spec and better fake data handling in CredentialStore

---

app/models/google_apps/sheets_manager.rb
spec/models/google_apps/sheets_manager_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5675
Bamboo build: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT61-4
In addition to specs, I added this to spreadsheet_by_id(...) method:
````
rescue Google::APIClient::ClientError => e
Rails.logger.error "Google API code is unhappy with spreadsheet_by_id(#{id}) call. Exception: #{e}"
...
````

CLC-5674, GoogleApps::SheetsManager specs on 'no results found'; plus, mo' better logging

---

app/models/campus_oracle/queries.rb
app/models/canvas_csv/base.rb
app/models/mailing_lists/site_mailing_list.rb
spec/models/canvas_csv/add_new_users_spec.rb
spec/models/canvas_csv/base_spec.rb
spec/models/canvas_csv/maintain_users_spec.rb
spec/models/mailing_lists/site_mailing_list_spec.rb

Partial revert of #4060, going back to `first_name` and `last_name` from campus data in place of `person_name`.
See comments to https://jira.ets.berkeley.edu/jira/browse/CLC-3181 for motivation.

CLC-3181 Use campus DB first_name and last_name instead of person_name

---

app/models/oec/term_setup_task.rb

Follow-up for https://jira.ets.berkeley.edu/jira/browse/CLC-5654.
For obscure constant-loading reasons, the handy ActiveSupport `subclasses` method is returning an array of subclasses when run in the console or as part of a test, but an empty array when run as part of a Rake task. Work around for the moment by listing subclasses explicitly.

CLC-5654 Explicitly list Oec::CsvExport subclasses

---

src/assets/stylesheets/_buttons.scss

https://jira.ets.berkeley.edu/jira/browse/CLC-5681

CLC-5681 - Hovering a cc-button-link element with an icon doesn't underline the icon

---

app/controllers/google_auth_controller.rb
app/models/google_apps/client.rb
app/models/google_apps/drive_manager.rb
app/models/google_apps/proxy.rb
spec/models/google_apps/proxy_spec.rb

DO NOT MERGE until Bamboo is happy: 
https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT63-1
https://jira.ets.berkeley.edu/jira/browse/CLC-5667
As I move to put OEC's oauth2 tokens in the db via CredentialStore class, I want to remove risk on the bConnected side. In the future, as Google API work progresses, we can refactor proxy.rb and leverage CredentialStore.

CLC-5667, divorce OEC CredentialStore from bConnected proxy

---

app/models/google_apps/credential_store.rb
app/models/google_apps/drive_manager.rb
app/models/google_apps/sheets_manager.rb
app/models/oec/task.rb
config/settings.yml
spec/models/google_apps/credential_store_spec.rb
spec/models/google_apps/drive_manager_spec.rb
spec/models/google_apps/sheets_manager_spec.rb

DO NOT MERGE until https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT64-2 succeeds
* CredentialStore now wraps *oauth2_data* db table. https://jira.ets.berkeley.edu/jira/browse/CLC-5667
* New OEC spa account *ets.course.eval.qa@gmail.com*: https://jira.ets.berkeley.edu/jira/browse/CLC-5632
* OEC/OAuth configs moved under existing 'oec' in yml. 
* Once tokens are in database we can remove *access_token* and *refresh_token* from yml. That removal will happen w/ release after next.

CLC-5667, Get OEC-related OAuth2 tokens in db

---

spec/models/oec/courses_import_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5628
At present Travis and Bamboo don't have the same test data for course code mappings, and I was not vigilant enough on this point.
One catch was a real catch: with the new `RM SHARE` value for the crosslisting flag, `row['CROSS_LISTED_FLAG'] == 'Y'` is no longer equivalent to `row['CROSS_LISTED_FLAG'].present?`
Otherwise, course-code mappings are just patched in with stubs to clean up the disparity.

CLC-5628 Compensate for disparate test data on Bamboo

---

app/models/google_apps/sheets_manager.rb
app/models/oec/task.rb
app/models/oec/term_setup_task.rb
spec/models/google_apps/sheets_manager_spec.rb
spec/support/oec_spec_helper.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5724
A worksheet object might wrap a CSV file read from disk or a hash in memory. Our GoogleApps::SheetsManager doesn't care and thus the abstraction.

CLC-5724, upload_worksheet() brings abstraction to GoogleApps::SheetsManager

---

app/models/oec/course_code.rb
app/models/oec/courses_import_task.rb
app/models/oec/task.rb
app/models/oec/term_setup_task.rb
lib/tasks/oec.rake
spec/models/oec/courses_import_task_spec.rb
spec/models/oec/term_setup_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5731
Oec::CoursesImportTask can now filter by either friendly course-code "department names" (SPANISH, CATALAN) or unfriendly department codes (IBIBI, LPPSP). 
On all tasks, a `local_write` option can be set to any truthy value in order to skip Google Drive upload and instead output local CSVs and logfiles for debugging purposes. Otherwise local output-and-delete is skipped entirely in favor of the Better Way from #4148.
Task logging is standardized a bit.

CLC-5731 Allow OEC tasks to take department-filter and local-write arguments

---

app/models/berkeley/departments.rb
app/models/oec/courses_import_task.rb
app/models/oec/report_diff_task.rb
app/models/oec/task.rb
spec/models/berkeley/departments_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5719
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT66-1
Another step towards ReportDiffTask:
* option to pull concise department title per [requirements](https://confluence.ets.berkeley.edu/confluence/pages/viewpage.action?pageId=46142744)
* reusable find_or_create_today_subfolder() code moves to Oec::Task
* specs

CLC-5719, pull dept spreadsheet from Drive with naming convention

---

app/models/oec/courses.rb
app/models/oec/sis_import_sheet.rb
app/models/oec/sis_import_task.rb
app/models/oec/task.rb
app/models/oec/worksheet.rb
lib/tasks/oec.rake
spec/models/google_apps/sheets_manager_spec.rb
spec/models/oec/sis_import_task_spec.rb

The previous `Oec::Courses`, which is a format we only expect to use for SIS imports, becomes `Oec::SisImportSheet`. 
`Oec::CoursesImportTask` becomes `Oec::SisImportTask` to signal the close connection between task and sheet format.
The new vanilla `Oec::Courses` includes no instructor-data columns and doesn't need the `dept_code` attribute.
Other cleanup:
- Remove Oec::Worksheet's inheritance from CsvExport, since that inheritance was giving us nothing but the `export_directory` instance variable;
- Rename Oec::Worksheet's `export` method to `write_csv`, since CSV output is no longer the usual means of export.

CLC-5737 Oec: distinguish normalized and denormalized Courses worksheets

---

app/models/oec/diff_report.rb
app/models/oec/remote_drive.rb
app/models/oec/report_diff_task.rb
app/models/oec/task.rb
spec/models/oec/report_diff_task_spec.rb

* Spreadsheets will be built from DiffReport instances.
* Oec::RemoteDrive wraps SheetsManager so we can move helper methods out of Oec::Task
* Specs

CLC-5720, diff_report worksheet; remote_drive extends generic Google operations

---

app/models/google_apps/drive_manager.rb
app/models/google_apps/sheets_manager.rb
spec/models/google_apps/sheets_manager_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5726
For the sake of speed, this gives us the option to bypass the Sheets API entirely and get a CSV export straight from a Google Drive file object.
Bamboo is chugging: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPT152-7

CLC-5726 Allow SheetsManager to export sheets as CSV

---

app/models/google_apps/drive_manager.rb

The OEC specs will use empty_trash() to leave no trace of test data.

CLC-5720, empty_trash() added to drive_manager

---

app/models/campus_solutions/aid_years.rb
app/models/campus_solutions/deleting_proxy.rb
app/models/campus_solutions/financial_aid_data.rb
app/models/campus_solutions/list_of_values.rb
app/models/campus_solutions/posting_proxy.rb
app/models/campus_solutions/terms_and_conditions.rb
app/models/campus_solutions/title4.rb
spec/models/campus_solutions/ethnicity_delete_spec.rb
spec/models/campus_solutions/ethnicity_post_spec.rb
spec/models/campus_solutions/translate_spec.rb
spec/models/campus_solutions/work_experience_spec.rb

https://jira.berkeley.edu/browse/SISRP-7300
https://jira.berkeley.edu/browse/SISRP-7325
This PR should make Bamboo green again (apart from unrelated Google test failures). 
This removes the last of our thru-the-hub proxies, but I'm not going to drop that code yet, because the Person EDO will make use of it when we have the real thing available.

SISRP-7300 and SISRP-7325 - Fixing test failures 

---

app/models/google_apps/drive_manager.rb
app/models/google_apps/sheets_manager.rb
spec/models/oec/remote_drive_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5719
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT70-1
[Google API docs](https://developers.google.com/drive/web/search-parameters) say, "Surround with single quotes '. Escape single quotes in queries." I know of no other necessary escaping.
I was able to reproduce the problem using SWOME (Gender and Women's Studies) in oec_remote_drive_spec #real test. That spec is now passing.

CLC-5719, escape Google API query args

---

app/models/oec/sis_import_task.rb

Check Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CPT157-3
Follow up to #4188, which caused side-effect failures in specs running Oec::SisImportTask. Our default fake_now is still set to 2013, and Berkeley::Terms won't return information on terms two years in the future.
If a nil term is encountered, output no date information and move on.

CLC-5728 OEC: Allow SisImportTask to handle nil terms

---

app/models/oec/queries.rb
app/models/oec/sis_import_task.rb
lib/tasks/oec.rake
spec/models/oec/queries_spec.rb
spec/models/oec/sis_import_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5743
Oec::SisImportTask is getting a lot of options, but I think we want the ability to toggle this one.
When `import_all` is switched off (the default), a query on a non-participating department will return an empty array instead of blowing up.
When `import_all` is switched on, the `include_in_oec` flag in our database is ignored, and a full course listing is returned.

CLC-5743 OEC: Better handling for non-participating departments

---

app/models/campus_solutions/list_of_values.rb
app/models/campus_solutions/proxy.rb

temporary workaround to https://jira.berkeley.edu/browse/SISRP-7380 
I think this will work, but the problem doesn't manifest for me locally or on Bamboo builds. It only appears in the calcentral-sis-dev environment. I think that has to do with Ruby falling back on the OS default charset, but I'm not sure. Anyway, this PR should be relatively harmless to merge and see if it unblocks @christianv for dev.

SISRP-7380 Workaround for bogus data in responses: force_encoding to UTF-8

---

app/models/berkeley/departments.rb
app/models/google_apps/drive_manager.rb
app/models/google_apps/sheets_manager.rb
app/models/oec/sis_import_sheet.rb
app/models/oec/sis_import_task.rb
spec/models/berkeley/departments_spec.rb
spec/models/oec/sis_import_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5748
Also tweaks the concise-name regex to catch "Charles and Louise Travers Department of Political Science", and rolls back some of the apostrophe escaping on Google API calls. (It turns out that you do need the escaping when building a query string, but that escaping metadata parameters in the Ruby API will add an extra backslash. Obviously....)

CLC-5748 Surface user-friendly department names where possible

---

app/models/oec/report_diff_task.rb
app/models/oec/worksheet.rb
spec/models/oec/report_diff_task_spec.rb

DO NOT MERGE until Bamboo passes https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT72-1 
Before pushing diff spreadsheets to Google Drive I want to verify basic logic of "is there a diff?". Notice that rows are compared when they align according to id generated by extract_id(). This code still looks out for "annotated" course ids; for example, "2015-D-12345_GSI" in which "GSI" is the annotation.
Follow up tasks:
* https://jira.ets.berkeley.edu/jira/browse/CLC-5718
* Push diff reports to Google Drive

CLC-5720, round one of ReportDiffTask has diff-marker per dept

---

app/models/canvas_csv/maintain_users.rb

Researching https://jira.ets.berkeley.edu/jira/browse/CLC-5192 convinced me that it would be helpful to log the existing SIS User ID of the bCourses account alongside the projected new SIS User ID.

CLC-5191 Improve logging of SIS User ID changes

---

lib/tasks/oec.rake

https://jira.ets.berkeley.edu/jira/browse/CLC-5779
If Oec::Task does not return 'true' then abort loop in rake oec:sis_import.

CLC-5779, skip ReportDiff if SisImportTask fails

---

app/models/oec/course_instructors.rb
app/models/oec/courses.rb
app/models/oec/export_task.rb
app/models/oec/instructors.rb
app/models/oec/report_diff_task.rb
app/models/oec/students.rb
app/models/oec/supervisors.rb
app/models/oec/validation_error_counter.rb
app/models/oec/validator.rb
app/models/oec/worksheet.rb
spec/models/oec/export_task_spec.rb
spec/models/oec/report_diff_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5640
Validation for exported data, as demoed this morning.
The pretty formatting in Oec::ReportDiffTask is extracted to Oec::Validator for reusability. Error message collections are changed from arrays to hashes with an integer count as value, making it easier to log repeated errors compactly.
A bit of metaprogramming in Oec::Worksheet allows its subclasses to set their own validation rules with ActiveRecord-style macros.

CLC-5640 OEC: validate export data before output

---

app/models/oec/publish_task.rb
config/settings.yml

https://jira.ets.berkeley.edu/jira/browse/CLC-5788
https://jira.ets.berkeley.edu/jira/browse/CLC-5787
Notes:
* Publish task pulls exports from remote drive, SFTPs them to Explorance and writes stdout/stderr to log file in remote drive 'reports' dir.
* I'm using *LFTP* (see https://en.wikipedia.org/wiki/Lftp) which gives more options in using *SFTP*. For example, scriptable way of providing password.
* If password is blank in yml the code will assume ssh keys are at work and exclude password from command line script.

CLC-5700, publish_task invokes sftp to push to Explorance

---

app/models/oec/export_task.rb
app/models/oec/publish_task.rb
app/models/oec/report_diff_task.rb
app/models/oec/sis_import_task.rb
app/models/oec/task.rb
lib/tasks/oec.rake
spec/models/oec/export_task_spec.rb
spec/models/oec/publish_task_spec.rb
spec/models/oec/report_diff_task_spec.rb
spec/models/oec/sis_import_task_spec.rb
spec/models/oec/term_setup_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5799
Happily, #4191 already gave Oec::Task a configurable DateTime, which lets us match timestamps between folder names and report/log files.
With all these timestamps now about, spaces and colons are preferred in remote item names where feasible.

CLC-5799 OEC: Include timestamp in imports and exports subfolders

---

app/models/canvas_csv/maintain_users.rb
config/settings.yml
spec/models/canvas_csv/maintain_users_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5802
Our database continues to miss many active accounts. And even after it's fixed, we know that what Oracle has done before, Oracle will someday do again.

CLC-5802 Feature-flag bCourses user inactivation to deal with unreliable campus data

---

spec/models/oec/remote_drive_spec.rb

DO NOT MERGE until https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT74-1
Changes:
* specs should have unique summaries
* #real test now uses 'IQBBB' =>  'QB3 Institute'

NOJIRA, fix remote_drive_spec #real test by swapping in 'QB3' dept_code

---

app/models/oec/task.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5809
These two will be used in a subsequent PR:
* def self.date_format
* def self.timestamp_format
This gives us more intuitive timestamps on log files.

CLC-5809, write_log in Oec::Task should always use DateTime.now when write_log

---

app/models/oec/publish_task.rb
app/models/oec/report_diff_task.rb
app/models/oec/task.rb
lib/tasks/oec.rake
spec/models/oec/report_diff_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5812
Allows for report_diff without generating more sis_imports. We always use most recent SIS data.

CLC-5812, oec:report_diff uses latest (SIS) imports folder by default

---

app/models/google_apps/sheets_manager.rb
app/models/oec/course_confirmation.rb
app/models/oec/create_confirmation_sheets_task.rb
app/models/oec/merge_confirmation_sheets_task.rb
app/models/oec/report_diff_task.rb
app/models/oec/worksheet.rb
spec/models/google_apps/sheets_manager_spec.rb
spec/models/oec/create_course_confirmation_sheets_task_spec.rb
spec/models/oec/merge_course_confirmation_sheets_task_spec.rb
spec/models/oec/report_diff_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5769
- Departmental confirmation sheets are now a single Google Sheet with multiple worksheets. Oec::CreateConfirmationSheetsTask will look for a 'TEMPLATE' sheet in the departmental folder and copy over its styling and validation for departmental sheets. If the 'TEMPLATE' sheet is not found, it will create a new Google Sheet without styling or validation.
- Updating cells in place is accomplished with the new SheetsManager#update_worksheet, re-implementing the functionality of GoogleDrive::Spreadsheet#save with acceptable performance.
- Other tasks are changed to expect a multi-worksheet confirmation sheet. Calling the CSV export URL for a multi-worksheet Google Sheet will generate a CSV for the first worksheet only. As it happens, this is …

CLC-5769 Use template sheets for departmental confirmations

---

app/models/oec/publish_task.rb
app/models/oec/report_diff_task.rb
app/models/oec/task.rb
config/settings.yml
spec/models/oec/publish_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5793
* reuse the logic in report_diff: publish_task now defaults to *date_time_of_most_recent 'exports'* 
* tidy up logging
* strictly ssh keys in dev, qa and prod – no more sftp_password

CLC-5700, enhance publish_task; no more sftp_password

---

script/run-oec-task.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-5700
Bash script enhancements:
* 'report_diff' is a task option
* more granular timestamp on log file
* override RAILS_ENV if you want
* ${2} is not needed in script. The **oec.rake** code will pick up cmd line args via ENV['foo']

CLC-5700, enhance run-oec-task.sh

---

app/models/oec/publish_task.rb
config/settings.yml

https://jira.ets.berkeley.edu/jira/browse/CLC-5793
Changes:
* dev and qa environments use SSH keys so the code can stop relying on *lftp*
* we use sftp's batch-mode
* name of ssh_private_key_file must be explicit (see Settings.oec) because other apps might have a need for other keys in ~/.ssh

CLC-5793, toss out lftp; publish_task is always SSH

---

app/controllers/oec_tasks_controller.rb
app/models/oec/administrator.rb
app/models/oec/api_task_wrapper.rb
app/models/oec/remote_drive.rb
app/policies/authentication_state_policy.rb
config/routes.rb
config/settings.yml

https://jira.ets.berkeley.edu/jira/browse/CLC-5774
Part one:
- creates an `index` endpoint serving task, term and department information useful to the front end;
- creates a `run` endpoint that accepts a slimmed-down set of options and shunts OEC tasks over to a Torquebox background job;
- authorizes these endpoints to superusers or the new `administrator_uid` in YAML, which will be the same as the Google account ID in production but may not be in dev/QA.
Specs to follow.

CLC-5774 Create Junction API endpoints wrapping OEC tasks

---

app/models/oec/publish_task.rb
lib/tasks/oec.rake
spec/models/oec/publish_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5835
The 'OEC/Google Drive automated tasks' is updated, too.

CLC-5835, remove 'datetime_to_publish' from publish task

---

app/models/oec/api_task_wrapper.rb
app/models/oec/export_and_publish_task.rb
app/models/oec/export_task.rb
app/models/oec/publish_task.rb
lib/tasks/oec.rake
script/run-oec-task.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-5833
* New ExportAndPubish class so ApiWrapper can do both in one task
* 'validation_without_export' opt for ExportTask
* reordering in oec.rake according to real-world workflow
* PublishTask will not remove tmp_dir when local_write

CLC-5833, user can validate-only or export-and-publish

---

app/models/oec/api_task_wrapper.rb
spec/models/oec/api_task_wrapper_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5841
Clients of ApiTaskWrapper don't need to know about the :validate_without_export config.

CLC-5841, if standalone ExportTask then implicitly add :validate_without_export

---

app/models/oec/courses.rb
app/models/oec/export_task.rb
app/models/oec/sis_import_task.rb
app/models/oec/task.rb
spec/models/oec/export_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5832
Code to pull default term dates from supplemental_sources/courses is extracted into the base Oec::Task class so that validations can check against it. Also constrains values on MODULAR_COURSE and EVALUATION_TYPE.

CLC-5832 OEC: Add new validations on export

---

app/models/canvas_csv/lti_usage_reporter.rb
spec/models/canvas_csv/lti_usage_reporter_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5341
Why do you think they call it Excel?

CLC-5341 Keep "129182,129410" from displaying as "129,182,129,410"

---

db/migrate/20151002183441_remove_obsolete_oauth_oec.rb
db/schema.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5846
* Environments still using uid=12004714: local, testext, dev, qa 
* Prod will use a new uid based on yaml settings (prepared prior to v66 release)

CLC-5846, if OEC uid=12004714 is obsolete then delete oauth2_data

---

app/models/oec/api_task_wrapper.rb
src/assets/javascripts/angular/controllers/pages/oecController.js
src/assets/stylesheets/_oec.scss
src/assets/templates/oec.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5839
For tasks where department selection has no effect:
- Show text "All participating departments" in place of dropdown;
- If the departmentCode option was previously set, strip it on submit.

CLC-5839 OEC control panel: hide departments dropdown when not relevant

---

config/settings.yml

Canvas is a .com not a .edu.
https://jira.ets.berkeley.edu/jira/browse/CLC-5851

CLC-5851: QA needs coffee

---

app/models/calnet_crosswalk/proxy.rb
app/models/hub_edos/student.rb
app/models/hub_edos/user_attributes.rb
app/models/user/student.rb
fixtures/json/student_api_via_hub.json
spec/models/calnet_crosswalk/proxy_spec.rb
spec/models/hub_edos/student_spec.rb
spec/models/hub_edos/user_attributes_spec.rb

https://jira.berkeley.edu/browse/SISRP-8275
Student API payload changed slightly, so I made those adjustments. 
It no longer sends us student ID or LDAP UID, so we now look in the crosswalk for the student ID, and make use of the UID that we already have anyway.

SISRP-8275 Adapt to student API payload changes

---

app/controllers/oec_tasks_controller.rb
app/models/oec/api_task_wrapper.rb
app/models/oec/sis_import_task.rb
app/models/oec/task.rb
config/routes.rb
spec/controllers/oec_tasks_controller_spec.rb
spec/models/oec/api_task_wrapper_spec.rb
spec/models/oec/term_setup_task_spec.rb
src/assets/javascripts/angular/controllers/pages/oecController.js
src/assets/javascripts/angular/factories/oecFactory.js
src/assets/stylesheets/_oec.scss
src/assets/templates/oec.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5852
This approach is based on our progress-bar wiring for Canvas tasks, but requires less ceremony. When an OEC task is started, the front end receives an ID linked to a cache key. It then polls the back end every two seconds for status and logs until the task is complete, displaying the latest to the user as it goes.

CLC-5852 OEC: Show task status and in-progress log in control panel

---

app/controllers/campus_solutions/address_controller.rb
app/controllers/campus_solutions/campus_solutions_controller.rb
app/controllers/campus_solutions/email_controller.rb
app/controllers/campus_solutions/emergency_contact_controller.rb
app/controllers/campus_solutions/ethnicity_controller.rb
app/controllers/campus_solutions/language_controller.rb
app/controllers/campus_solutions/person_name_controller.rb
app/controllers/campus_solutions/phone_controller.rb
app/controllers/campus_solutions/sir_response_controller.rb
app/controllers/campus_solutions/terms_and_conditions_controller.rb
app/controllers/campus_solutions/title4_controller.rb
app/controllers/campus_solutions/work_experience_controller.rb

https://jira.berkeley.edu/browse/SISRP-8365
Note that as soon as this is merged, you'll have to use a real CalNet login, or else use the basic auth backdoor, whenever you want to test the Profile edit functionality. Profile View still works in act-as mode, however.

SISRP-8365 Don't allow Post or Delete when user is acting-as

---

app/models/oec/report_diff_task.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5869

CLC-5869 OEC: Do not log stacktrace on non-fatal diff errors

---

app/models/oec/sis_import_task.rb
app/models/oec/task.rb
lib/tasks/oec.rake
spec/models/oec/sis_import_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5858
Oec::Task subclasses can define a follow-up task to run on success. This allows consistent behavior between the command-line and browser interfaces.
A task passes its own option set to the follow-up, as well as its own log under a `:previous_task_log` option. This allows the follow-up to seamlessly append its own logs in the control panel UI, but keep logfiles separate for upload to Drive. 
This PR also addresses https://jira.ets.berkeley.edu/jira/browse/CLC-5759 by having SisImportTask call ReportDiffTask only when `local_write` is turned off.

CLC-5759 CLC-5858 OEC: Allow tasks to define their own follow-ups

---

app/models/oec/task.rb
src/assets/templates/oec.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5878
Also adds an Angular track-by to avoid errors on duplicate lines.

CLC-5878 Do not show date and timezone in per-line log timestamps

---

app/controllers/oec_tasks_controller.rb
app/models/oec/api_task_wrapper.rb
app/models/oec/course_code.rb
app/models/oec/task.rb
src/assets/stylesheets/_oec.scss
src/assets/templates/oec.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5865
The department list from the API gets a `participating` boolean, which is used to display a list of participating departments when the "All participating departments" option is selected.
For tasks that don't accept a department option, the irrelevant "All participating departments" text is removed.
Oec::CourseCode::included_dept_names is a middleman of a method and doesn't need to be in there.

CLC-5865 OEC: Show list of participating departments in control panel

---

app/models/canvas_csv/maintain_users.rb
app/models/canvas_csv/refresh_all_campus_data.rb
lib/tasks/canvas.rake
script/refresh-canvas-users.sh
spec/models/canvas_csv/maintain_users_spec.rb
spec/models/canvas_csv/refresh_all_campus_data_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5881
The fixed known_uids bug would create a second user account for an expired enrollment.
Also carries CLC-5873 fix from https://github.com/ets-berkeley-edu/calcentral/pull/4331.

CLC-5881 Add bCourses user refresh script

---

spec/models/google_apps/drive_manager_spec.rb
spec/models/oec/remote_drive_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5882
Bamboo passed: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT75-2
Before I retire the 'ets.course.eval.qa' account and point textext specs at 'course-eval' I want to guarantee that test-data (e.g., term_date = 1066-D) does not collide with manual testing of QA dept.

CLC-5882, google spec testext must not collide with other testing

---

spec/models/hub_edos/student_spec.rb

Followup for https://jira.berkeley.edu/browse/SISRP-8853 that fixes a testext failure on Bamboo.

SISRP-8853 Remove failing test that's not needed in testext

---

app/models/campus_solutions/profile_feature_flagged.rb
app/models/user/api.rb
config/settings.yml
spec/models/user/api_spec.rb
spec/models/user/api_with_campus_solutions_enabled_spec.rb

https://jira.berkeley.edu/browse/SISRP-9407
New feature flag, cs_profile_visible_for_legacy_users, does what it says. When the flag is true (the default), everyone gets the profile feature. When false, only new students in CS get it. 
@christianv will need to followup with the front-end changes for this: Hide Profile UI when showSisProfileUI is false in the /api/my/status feed.

SISRP-9407 Backend logic for profile-fallback 

---

app/models/oec/merge_confirmation_sheets_task.rb
app/models/oec/validator.rb
spec/models/oec/merge_confirmation_sheets_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5892
Failure to match confirmation rows with SIS import rows still logs validation errors, but no longer screens them out of the merge. Downstream validation requires problems to be cleared up before export.
Also fixes option handling in `Validator#validate_and_add`. For some reason I thought that Rails considered boolean `false` to be "present," but it is very definitely "blank."

CLC-5892 OEC: include unmatched and conflicting SIS data in confirmation-sheet merge

---

app/models/berkeley/terms.rb
app/models/google_apps/drive_manager.rb
app/models/google_apps/sheets_manager.rb
app/models/oec/publish_task.rb
app/models/oec/term_setup_task.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5893
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CJT78
The *course_students* sheet has 100-200K rows and Google is unhappy, it exceeds max rows. With this PR, we archive published files to /exports folder as 'text/csv'. It's lightweight and Google is playing nice.

CLC-5893, after OEC publish write files to /exports folder as plain test/csv

---

Gemfile
Gemfile.lock
app/controllers/sessions_controller.rb
app/models/calnet_crosswalk/proxy.rb
config/initializers/omniauth.rb

https://jira.berkeley.edu/browse/SISRP-9421
We use a fork of omniauth-cas (https://github.com/ets-berkeley-edu/omniauth-cas) that was graciously provided by Steve Hansen to wrangle the SAML assertion into a form we can use. 
If the SAML assertion gave us a student ID and/or CS EMPLID, we store them in cache, which will reduce the load on the crosswalk service. 
Before merging, the team should duly consider the risk involved in maintaining our own fork of omniauth-cas, and weigh it against the benefits.

Make CalCentral use the SAML Assertion from CAS to retrieve IDs where it can

---

app/models/canvas_csv/ldap.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5881
LDAP is probably not the cause of our mysterious slowdowns in testing, but it's an obvious gap in our knowledge.

CLC-5881 Add slow-proxy logging for LDAP

---

app/controllers/google_auth_controller.rb
app/models/google_apps/proxy.rb
app/models/google_apps/userinfo.rb
config/routes.rb
fixtures/json/google_user_current_scope.json
spec/models/google_apps/userinfo_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5791
https://jira.ets.berkeley.edu/jira/browse/CLC-4299
* A new API request parameter grants non-standard API authorizations for devs, admins, & SPA account use. The include_granted_scopes option ensures that previously added scopes are not lost.
* A new API endpoint shows the authorization scope for the currently logged-in user. (This is mostly for QA right now, but I can picture later use in the UX.)
See CLC-5791 for a walkthrough and screenshot.

CLC-5791 CLC-4299 Add Google API scope on demand to existing OAuth2 tokens

---

app/models/oec/publish_task.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5922
@johncrossman, let me know if it seems right to have a single `ls` command run after the upload rather than before.

CLC-5922 OEC: Remove verbose logging from SFTP command

---

app/controllers/yaml_settings_controller.rb
lib/calcentral_config.rb
spec/controllers/yaml_settings_controller_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5906
Note:
* Code does before and after diff on feature flags (litmus test)
* Message to the user guesses at success / failure. Ultimately, user must verify success with his/her own smoke-testing.
* Overhauled the spec

CLC-5906, dynamically flip key configurations without redeploy/restart

---

app/models/oec/create_confirmation_sheets_task.rb
app/models/oec/folder.rb
app/models/oec/merge_confirmation_sheets_task.rb
app/models/oec/merged_sheet_validation.rb
app/models/oec/publish_task.rb
app/models/oec/remote_drive.rb
app/models/oec/report_diff_task.rb
app/models/oec/sis_import_task.rb
app/models/oec/task.rb
app/models/oec/term_setup_task.rb
spec/models/oec/create_confirmation_sheets_task_spec.rb
spec/models/oec/merge_confirmation_sheets_task_spec.rb
spec/models/oec/remote_drive_spec.rb
spec/models/oec/report_diff_task_spec.rb
spec/models/oec/sis_import_task_spec.rb
spec/models/oec/term_setup_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5926
This part-one PR does no renaming of folders but centralizes folder names in a constant Hash. Once this is cleared, part two will switch the names over.

CLC-5926 OEC: Avoid repetitively hardcoding folder names

---

app/models/oec/folder.rb
app/models/oec/term_setup_task.rb
spec/models/oec/term_setup_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5926
Following #4436, the actual renames.

CLC-5926 OEC: Use human-friendly folder names; separate out merged confirmation sheets

---

app/models/hub_edos/work_experience.rb

https://jira.berkeley.edu/browse/SISRP-9984
Missing data will appear to the client UI as a 404 but won't get logged as an error in the app log.

SISRP-9984 Don't treat 404 from work experience API as an error

---

app/models/hub_edos/proxy.rb
app/models/hub_edos/student.rb
app/models/hub_edos/user_attributes.rb
app/models/user/api.rb
spec/models/hub_edos/user_attributes_spec.rb
spec/models/user/api_with_campus_solutions_enabled_spec.rb

https://jira.berkeley.edu/browse/SISRP-9437
https://jira.ets.berkeley.edu/jira/browse/CLC-5948
https://jira.ets.berkeley.edu/jira/browse/CLC-5957
Start with Oracle roles if we have them, then merge in any available data from Hub affiliations. So far all we know about is undergraduate and graduate student status.
Inline comments explain some of the fake-proxy fiddling.

SISRP-9437 Merge rather than overwriting Oracle-derived roles

---

app/models/oec/api_task_wrapper.rb
app/models/oec/sis_import_task.rb
app/models/oec/task.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5907
See issue comments for the motivation behind taking out some timestamps.
Also generally improve logging on the import task, and update the contextual help.

CLC-5907 OEC: Omit timestamps in skipped-course logs, keep them out of the browser

---

script/bamboo-tests.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-5969
```bamboo-tests.sh``` is used by Bamboo to run testext or run testext + uitests. See comments in CLC-5969 that highlight the oddity Xvfb placement. This change guarantees that Xvfb check happens when uitests are run.

CLC-5969, UITEST needs the Xvfb check before the 'if' block

---

config/settings.yml
src/assets/javascripts/angular/configuration/routeConfiguration.js
src/assets/javascripts/angular/controllers/pages/welcomeDelegateController.js
src/assets/javascripts/angular/controllers/widgets/delegateAccountLinkingController.js
src/assets/stylesheets/_welcome_delegate.scss
src/assets/templates/welcome_delegate.html
src/assets/templates/widgets/delegated_access/link_accounts.html

https://jira.ets.berkeley.edu/jira/browse/CLC-5996
https://jira.ets.berkeley.edu/jira/browse/CLC-5973
The magic URL would be /welcome_delegate The next step is to put some meat on the bones of widgets/delegated_access/link_accounts.html  Plus, 'cs_delegated_access ' feature flag.
(See relevant comments on closed PR #4490)

CLC-5996, front-end wiring for 'Welcome Delegate' page and widget to link accounts

---

app/models/campus_solutions/person_data_expiry.rb
app/models/campus_solutions/person_data_updating_model.rb
app/models/hub_edos/affiliations.rb
app/models/hub_edos/contacts.rb
app/models/hub_edos/demographics.rb
app/models/hub_edos/my_student.rb
app/models/hub_edos/student.rb
fixtures/json/affiliations.json
fixtures/json/demographics.json
fixtures/json/student_contacts.json
spec/models/hub_edos/affiliations_spec.rb
spec/models/hub_edos/contacts_spec.rb
spec/models/hub_edos/demographics_spec.rb

NOTE for Christian: The /students/demographic Hub endpoint doesn't yet include birth and gender, but it will shortly (Faiza promised that it's easy). As soon as it does, this code will pick it up. The /students/affiliation endpoint already existed, so now I take advantage of it. 
Squashed commit of the following:
commit b6b2a1fde158f0617b68f5b476f06acf2d3e0547
Author: Chris Tweney <chris@media.berkeley.edu>
Date:   Fri Nov 13 07:09:37 2015 -0800
SISRP-10872 Add birth, gender, and affiliation
commit 68502b02cfe845d4f50223525c47b1019948c373
Author: Chris Tweney <chris@media.berkeley.edu>
Date:   Thu Nov 12 10:46:57 2015 -0800
SISRP-10872 Fix test failure
commit 8e4c5901cf523e23611a3c48f20c9225617e74b7
Author: Chris Tweney <chris@media.berkeley.edu>
Date:   Thu Nov 12 10:27:31 2015 -0800 …

SISRP-10872 Consume student API in chunks rather than /all

---

app/models/campus_solutions/my_aid_years.rb
app/models/campus_solutions/my_financial_aid_data.rb

I hope this is my last QA PR under https://jira.ets.berkeley.edu/jira/browse/CLC-6016.
A couple of Finaid-related models are switched from the CS profile flag (which I hastily put in yesterday) to the CS finaid flag. Using the wrong flag would presumably have created a separate leak between GL3 and GL4 ("...the _Titanic_ and her sister ship _Olympic_ were built with a cellular double bottom and divided into 16 major watertight compartments with 15 transverse watertight bulkheads that ran clear across the ship...").
Bamboo has built at https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT216-1. I believe the failures, including the CampusSolutions::AidYears failure, are red herrings; they're triggered by Campus Solutions errors farther down the stack and are showing up on all our branches …

[QA] CLC-6016 Finaid-related Campus Solutions user models should observe finaid flag

---

lib/calcentral_config.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6020
Rails initialization is always twisty, but the crux seems to be that our logging constants (from Log4r) are evaluated as integers 0 through 6, not the corresponding string values; so the integers are what to check for.

CLC-6020 Expect logger levels as integers, not strings

---

src/assets/stylesheets/_base.scss

https://jira.ets.berkeley.edu/jira/browse/CLC-6021

CLC-6021 - Roster photos: printing in Firefox only prints one page

---

app/models/hub_edos/my_student.rb

A Campus Solutions ID lookup failure from the Hub will return a feed of `{noStudentId: true}`, with no status code; so we oughtn't to blow up if a status code is missing.
https://jira.ets.berkeley.edu/jira/browse/CLC-6018

CLC-6018 Robustly handle Hub ID lookup failures

---

app/models/hub_edos/user_attributes.rb
spec/models/hub_edos/user_attributes_spec.rb

Followup for https://jira.berkeley.edu/browse/SISRP-10872 eliminates the last usage of /students/all.

SISRP-10872 Followup - use the merged MyStudent feed from UserAttributes

---

app/models/my_academics/college_and_level.rb
spec/models/my_academics/college_and_level_spec.rb
src/assets/templates/academics_student_profile.html

https://jira.ets.berkeley.edu/jira/browse/CLC-6007
Aside from single-quote and Rspec cleanup, the changes are:
- Ensure that MyAcademics::CollegeAndLevel always returns a `termName` value, falling back to the CalCentral current term if it can't extract a term from Bearfacts;
- Surface a more detailed message in the profile template, including term name, when a student is considered active but not registered.

CLC-6007 Mention term in blinkered My Academics Profile

---

app/models/user/api.rb
public/dummy/json/status.json
spec/models/user/api_spec.rb
spec/models/user/api_with_campus_solutions_enabled_spec.rb
spec/ui_selenium/pages/api_my_status_page.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6039
Nothing surfaces on the UI yet. This is purely putting hasToolboxTab in the /api/my/status feed when user is "super" or can-view-as. Eventually, this tab will have view-as features and other admin-ish type cards.

CLC-6039, /api/my/status -> hasToolboxTab when superuser, can-view-as

---

app/models/user/api.rb
app/policies/authentication_state_policy.rb
src/assets/javascripts/angular/controllers/widgets/adminController.js
src/assets/javascripts/angular/services/utilService.js
src/assets/stylesheets/_toolbox.scss
src/assets/templates/toolbox.html
src/assets/templates/widgets/toolbox/api_test.html
src/assets/templates/widgets/toolbox/uid_lookup.html
src/assets/templates/widgets/toolbox/view_as.html

https://jira.ets.berkeley.edu/jira/browse/CLC-6051
https://jira.ets.berkeley.edu/jira/browse/CLC-6040
Includes:
* My Toolbox widgets look like proper cards
* Remove extraneous styles
* While you view-as, the My Toolbox tab behaves per target user privileges 
* When you click to view-as you are sent to '/'  (ie, Dashboard)
Note: spec will come in future PR - https://jira.ets.berkeley.edu/jira/browse/CLC-6053

CLC-6051, hide /toolbox when view-as; card styling

---

app/models/canvas_csv/base.rb
app/models/canvas_csv/lti_usage_reporter.rb
app/models/canvas_csv/turnitin_reporter.rb
app/models/google_apps/drive_manager.rb
app/models/google_apps/sheets_manager.rb
app/models/oec/create_confirmation_sheets_task.rb
app/models/oec/remote_drive.rb
app/models/oec/term_setup_task.rb
app/models/oec/worksheet.rb
config/settings.yml
lib/tasks/canvas.rake
spec/models/canvas_csv/turnitin_reporter_spec.rb
spec/models/google_apps/sheets_manager_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5840
The first commit untangles OEC-specific classes from the more generic GoogleApps module, allows SPA accounts (for example) to find shared folders, and adds a convenient upload-to-a-worksheet method.
The second commit uploads LTI and TurnItIn usage reports to a folder shared between PDG and TLS.
The third fixes my new textext test and removes some confusingly ignored arguments from existing ones.

CLC-5840 Distribute LTI Usage / TurnItIn reports through Google Drive

---

app/controllers/my_academics_controller.rb
app/models/campus_oracle/user_courses/all.rb
app/models/my_academics/college_and_level.rb
app/models/my_academics/filtered_for_delegate.rb
app/models/my_academics/gpa_units.rb
app/models/my_academics/semesters.rb
app/models/my_academics/transition_term.rb
app/models/user_specific_model.rb
app/policies/authentication_state.rb
config/settings.yml
spec/controllers/my_academics_controller_spec.rb
spec/models/campus_oracle/user_courses/all_spec.rb
spec/models/my_academics/filtered_for_delegate_spec.rb
spec/models/my_academics/semesters_spec.rb
src/assets/javascripts/angular/controllers/pages/academicsController.js
src/assets/templates/academics.html
src/assets/templates/academics_semesters.html
src/assets/templates/academics_status_and_blocks.html

https://jira.ets.berkeley.edu/jira/browse/CLC-6024
Road map:
- In general, stuff to be hidden from delegates is so deeply intertwined in the My Academics feed that it seemed best to construct an entirely new feed rather than diving deep into the existing structure and unmerging all the merged components. Hence the new MyAcademics::FilteredForDelegate.
- Fortunately, the two flavors of MyAcademics::FilteredForDelegate (with and without grades) are similar enough that additional grade filtering can use the same filter-for-view-as logic that already exists in My Badges and elsewhere.
- MyAcademics::Merged and MyAcademics::FilteredForDelegate are cached separately. Feed components that supply both without alteration (CollegeAndLevel, GpaUnits, and TransitionTerm) are now individually cached …

CLC-6024 Present filtered My Academics to delegate viewers

---

src/assets/javascripts/angular/controllers/widgets/apiTestController.js
src/assets/stylesheets/_settings.scss
src/assets/stylesheets/_toolbox.scss
src/assets/templates/toolbox.html
src/assets/templates/widgets/toolbox/api_test.html
src/assets/templates/widgets/toolbox/uid_lookup.html
src/assets/templates/widgets/toolbox/view_as.html

https://jira.ets.berkeley.edu/jira/browse/CLC-6052
* Fix spacing on the settings page
* Fix spacing for the last column on the toolbox page
* Fix background color on the toolbox page (we shouldn't make it white as soon as we have a `cc-widget` on it.
* Bring back the error messages (like `That does not appear to be a valid UID or SID.`) for the UID / SID Lookup
* Add `label` to `UID/SID Lookup` for accessibility reasons
* Fix weird spinner behavior on Chrome when running the CalCentral API Test
* Fix alignment of check & spinner icons with their text next to it (flex-base)
* Allow for re-running the API tests
* Fix the main spinner for `CalCentral API Test` (only hide the contents on the widget, not the widget container)
* Refactor `CalCentral API Test` - and fix the dependency on the …

CLC-6052 - Fix some things on the toolbox page

---

app/controllers/act_as_controller.rb
app/controllers/sessions_controller.rb
app/models/calnet_crosswalk/by_sid.rb
app/models/calnet_crosswalk/by_uid.rb
app/models/calnet_crosswalk/proxy.rb
app/models/hub_edos/proxy.rb
app/models/user/search_users.rb
app/models/user/stored_users.rb
app/models/user/student.rb
config/settings.yml
spec/features/act_as_user_spec.rb
spec/models/calnet_crosswalk/by_uid_spec.rb
spec/models/my_tasks/merged_spec.rb
spec/models/user/search_users_spec.rb

https://jira.berkeley.edu/browse/SISRP-10824
This is a partial fix. It lets you view-as a new user who's not in Oracle. But there's a minor bug where such users won't record in the view-as admin history (SISRP-11917).

SISRP-10824 Use Crosswalk for view-as admin lookup

---

package.json
src/assets/templates/academics.html
src/assets/templates/footer.html

https://jira.ets.berkeley.edu/jira/browse/CLC-6075
("http" is used to avoid browser warnings in certain combinations of test environments between Java and Drupal).

CLC-6075 Point to new Support page for GL3

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
spec/controllers/bootstrap_controller_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6072
See latest comment in Jira. The change in `sessions_controller.rb` fixes [same problem when logging out on localhost:3001](https://jira.ets.berkeley.edu/jira/browse/CLC-6072?focusedCommentId=232320&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-232320)

CLC-6072, 'gulp build' expects port 3001 but underlying code would deduce 3000

---

spec/ui_selenium/my_dashboard_canvas_course_sites_spec.rb
spec/ui_selenium/my_dashboard_data_classes_spec.rb
spec/ui_selenium/pages/api_my_academics_page.rb
spec/ui_selenium/pages/cal_central_pages.rb
spec/ui_selenium/pages/my_dashboard_my_classes_card.rb
spec/ui_selenium/user_authorizations_spec.rb
spec/ui_selenium/user_google_connection_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6084
A few of the Selenium tests fail occasionally, mainly because DOM updates happen in a way the tests don't expect.  This is the first of a set of changes to make the tests more robust.

CLC-6084 - more Selenium test fixes

---

app/models/google_apps/drive_list.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6095
For how the fix works, see https://github.com/ets-berkeley-edu/calcentral/blob/master/lib/proxies/mock_http_interaction.rb#L34:
- When defining a mock request, we usually pass in a `uri_matching` key with a partial URI, which Proxies::Mockable then turns into a nice URI-matching regexp.
- However, if a class needs the flexibility of building its own regexp, it can be passed in with just `uri` as the key.

CLC-6095 Allow fake Google Drive proxy to respond to v2 or v3 API calls

---

app/models/oec/api_task_wrapper.rb
app/models/oec/task.rb
app/models/oec/term_setup_task.rb
lib/tasks/oec.rake
script/run-oec-task.sh
spec/models/google_apps/sheets_manager_spec.rb
spec/models/oec/create_confirmation_sheets_task_spec.rb
spec/models/oec/merge_confirmation_sheets_task_spec.rb
spec/models/oec/publish_task_spec.rb
spec/models/oec/remote_drive_spec.rb
spec/models/oec/report_diff_task_spec.rb
spec/models/oec/sis_import_task_spec.rb
spec/models/oec/term_setup_task_spec.rb
spec/models/oec/validation_task_spec.rb

See https://jira.ets.berkeley.edu/jira/browse/CLC-6012 for a description of the new behavior.
In addition to implementing the `allow_past_term` flag, option handling from environment variables is taken out of the Rake tasks and consolidated in `Oec::Task.opts_from_environment`.
Changes to tests include shifting example terms back a year or two, as our Berkeley::Terms logic doesn't recognize terms too far in the future from "now" (still locked to 2013 for testing purposes).

CLC-6012 OEC: Do not allow automated tasks to run past end of semester

---

app/models/google_apps/client.rb
app/models/google_apps/drive_list.rb
app/models/google_apps/proxy.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6095
This change fixes the bDrive badge on my local machine and pacifies the GoogleApps::DriveList testext that's been failing on master for the last 24 hours. 
Bamboo run: https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT229-1/test - the failures that do appear are just our usual batch.
#4638 is reverted, since the version-specific URL match turned out to be our coal-mine canary.

CLC-6095 Lock Google Drive client to v2 API

---

app/models/canvas/report/base.rb
spec/models/canvas_csv/base_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6097
Full parsing of large bCourses reports consumes large amounts of memory, CPU, and time.
When one-row-at-a-time parsing is viable, CSV.foreach('filename.csv') is much more efficient.
This PR should help us move in that direction.

CLC-6097 Optionally download Canvas CSVs to the file system

---

spec/models/campus_solutions/proxy_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6099
If we get ERRMSGTEXT from CS we send canned JSON (e.g., statusCode: 400) to front-end.

CLC-6099, test coverage on CampusSolutions::Proxy is_errored

---

src/assets/javascripts/angular/controllers/widgets/statusController.js
src/assets/templates/widgets/gear_popover.html

https://jira.ets.berkeley.edu/jira/browse/CLC-6112
This refactor of the status popover front end replaces the enormous compound Boolean with a couple of scope variables to clarify intent. In brief, status header and messaging should only show if:
- there are active alerts or warnings;
- or the user has non-null registration data;
- or the user has non-null financial data.

CLC-6112 Only show status header when there is status messaging

---

app/models/canvas/communication_channels.rb
app/models/canvas/report/base.rb
app/models/canvas_csv/maintain_users.rb
lib/tasks/canvas.rake
spec/models/canvas_csv/base_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6097
- Work around change to Canvas API permissions.
- Add separate Rake task to delete emails for inactive accounts, since it can take 12+ hours.
- Reduce memory/CPU cost of user account maintenance.
- Fix CSV download-to-file-system UTF-8 bug.
- Fix unit test bug CLC-6119.

CLC-6097 CLC-6119 bCourses email address deletion

---

app/models/notifications/reg_block_code_translator.rb
lib/cache/cacheable.rb
lib/cache/related_cache_key_tracker.rb

Attempt at gathering diagnostics on the trigger of https://jira.ets.berkeley.edu/jira/browse/CLC-6129
Also fixes a bad config reference in RelatedCacheKeyTracker.

CLC-6129 Log and override stray 0 cache expiration times

---

app/models/campus_solutions/financial_aid_expiry.rb

https://jira.berkeley.edu/browse/SISRP-12703
The list of cache entries to be expired on return from CS was not kept up to date with the list of cached FinAid-related feeds.
@christianvuerings, @davidlimcheng , once this reaches ETS master, we'll want it and other recent fixes merged into SIS-master for GL4 SIT.

SISRP-12703 Fix scope of Financial Aid cache expiration

---

app/models/user/api.rb
spec/models/user/api_spec.rb

https://jira.berkeley.edu/browse/SISRP-12545

SISRP-12545 Allow ex-student status from Oracle views to override student status from Hub

---

src/assets/templates/widgets/profile/contact_email.html

https://jira.ets.berkeley.edu/jira/browse/CLC-6146
After this fix I grep'd for similar typos. No more violations found.
```grep -R visually src/ | grep -v cc-visuallyhidden```
Note: The grep above _excludes_ valid usages of cc-visuallyhidden.

CLC-6146, Profile - 'Add' button for email is showing accessibility text

---

app/models/user/api.rb
spec/models/user/api_spec.rb

https://jira.berkeley.edu/browse/SISRP-12545
QA version of #4694.

[QA] SISRP-12545 Allow ex-student status from Oracle views to override student status from Hub

---

app/models/calendar/queries.rb
app/models/campus_oracle/connection.rb
spec/models/calendar/queries_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6153
Belt and suspenders for a world in which terms can be nil. The calendar model should not include nil values in its terms array; nor should the Oracle connection freak out if someone does send it a terms array with nil values.

CLC-6153 Handle nil term values in Oracle queries

---

script/sis/sis_script_utils.sh
script/sis/verify_sis_api_endpoints.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-6155
When testing the Delegated Access endpoints I identified another error condition to grep for: 'not authorized'.  I removed "/UC_DA_T_C.v1/get" because it's a placeholder and invalid.

CLC-6155, add 'not authorized' to grep'ing response for errors

---

.travis.yml
script/bamboo-tests.sh
script/build-torquebox.sh
script/calcentral-update.sh
script/configure-all-canvas-apps-from-current-host.sh
script/export-cached-csv-enrollments-set.sh
script/load-test-dev.sh
script/migrate.sh
script/reconfigure-canvas-test-servers.sh
script/refresh-all-canvas-enrollments.sh
script/refresh-canvas-enrollments.sh
script/refresh-canvas-users.sh
script/report-lti-usage.sh
script/report-turnitin-usage.sh
script/run-oec-task.sh
script/start-torquebox.sh
script/sync-canvas-guest-users.sh
script/sync-canvas-new-users.sh
script/update-mailing-list-memberships.sh

https://jira.ets.berkeley.edu/jira/browse/CLC-6025
This is safe to land before the clusters are moved to 1.8.

CLC-6142 Add -Xcompile.invokedynamic=false for Java 8

---

config/settings.yml
lib/jms/jms_connection.rb
lib/services/jms_worker.rb

https://jira.berkeley.edu/browse/SISRP-13249
JmsConnection now handles multiple queues, and JmsWorker handles multiple JmsConnection instances (as we might need to listen to the new Hub connection and our old Bearfacts connection simultaneously).
This implementation sticks with a single handler instance, since our Notifications::Handler seems already well set up to dispatch received messages among multiple processors.
NB: Changing connections and queues to arrays breaks YAML compatibility. Please ping me before merge so that YAML edits can be synchronized with deploys. Developer machines should also update their YAML, since the incompatibility will probably secretly persist until the next time one tries to run Torquebox.

SISRP-13249 Allow JmsWorker to handle multiple connections and queues

---

lib/cache/cacheable.rb
spec/lib/cache/cacheable_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6165
This has been plaguing us for many months, but the logging in Monday's release finally pinpointed the cause.

CLC-6165 Fix bug when cache refreshes on the exact minute it expired

---

app/controllers/sessions_controller.rb
app/models/calnet_crosswalk/proxy.rb
app/models/hub_edos/user_attributes.rb
app/models/user/api.rb
app/models/user/student.rb
fixtures/json/calnet_crosswalk_12352.json
spec/controllers/sessions_controller_spec.rb
spec/models/user/api_spec.rb
src/assets/templates/toolbox.html
src/assets/templates/widgets/toolbox/delegate_quick_links.html

https://jira.berkeley.edu/browse/SISRP-13262
Use of `berkeleyEduCSDelegateID` is not arbitrary - it was imagined in https://jira.berkeley.edu/browse/SISRP-10867 Having a placeholder implementation is useful; we can refactor the backend as the technical spec evolves.
`delegate_quick_links.html` is a new card on My Toolbox and it demonstrates the front-end logic of `isDelegateUser`.

SISRP-13262, delegate_quick_links card using (placeholder) attribute: berkeleyEduCSDelegateID

---

lib/services/jms_worker.rb

https://jira.berkeley.edu/browse/SISRP-13249
Follow-up to #4734 with a stray logging fix and needless `||=` removed.

SISRP-13249 Fix logging in JmsWorker

---

lib/services/jms_worker.rb

https://jira.berkeley.edu/browse/SISRP-13249
One more follow-up to #4734.

SISRP-13249 Pacify Torquebox by restoring unused JmsWorker opts

---

app/models/campus_solutions/direct_proxy.rb
app/models/campus_solutions/financial_aid_data.rb
app/models/campus_solutions/financial_aid_funding_sources.rb
app/models/campus_solutions/financial_aid_funding_sources_term.rb
app/models/campus_solutions/my_aid_years.rb
app/models/campus_solutions/my_financial_aid_data.rb
app/models/campus_solutions/posting_proxy.rb
spec/models/campus_solutions/financial_aid_data_spec.rb
spec/models/campus_solutions/financial_aid_funding_sources_spec.rb
spec/models/campus_solutions/financial_aid_funding_sources_term_spec.rb

https://jira.berkeley.edu/browse/SISRP-13434
Correct a false assumption that only PostingProxy will return UC_CM_FAULT_DOC; financial aid proxies are returning it also.
When CampusSolutions::MyFinancialAidData is called by LiveUpdatesWarmer, set it to the user's default aid year. It would be nice to have it warm up other years as well, but that would require architectural changes to the class.

SISRP-13434 CS finaid proxies: add default year, improve error handling

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/user_api_controller.rb
app/models/user_specific_model.rb
app/policies/authentication_state.rb
spec/controllers/user_api_controller_spec.rb
spec/models/user_specific_model_spec.rb
spec/policies/authentication_state_spec.rb

https://jira.berkeley.edu/browse/SISRP-13257
https://jira.berkeley.edu/browse/SISRP-13257
We are moving towards a functioning `Delegate > Students` card. I'm going to start with the session markers that take is in and out of delegate-view-as mode. If / when this PR is merged I will follow with `delegate_act_as_controller.rb` and more front-end changes.

SISRP-13257, 'original_delegate_user_id' is session marker when delegate-view-as student

---

app/models/campus_solutions/proxy.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6098
In `campus_solutions/proxy` the call to `convert_feed_keys(feed)` can return either an array or a hash. However, our `is_errored?` method has assumed hash so this PR includes a sanity check.
In the case of error, we now log the cs_id and raw response.

CLC-6098, informative logging in campus_solution proxy, plus hash check

---

app/models/hub_edos/affiliations.rb
app/models/hub_edos/contacts.rb
app/models/hub_edos/demographics.rb
app/models/hub_edos/proxy.rb
app/models/hub_edos/student.rb
app/models/hub_edos/user_attributes.rb
app/models/hub_edos/work_experience.rb
config/routes.rb

Part one of https://jira.ets.berkeley.edu/jira/browse/CLC-6168.
- Subclasses of HubEdos::Proxy (including subclasses of HubEdos::Student) lose endpoint-level caching.
- Controller-accessible merged models HubEdos::MyStudent, HubEdos::MyWorkExperience, and User::Api keep their caching.
- Bits of shared code in HubEdos::Proxy subclasses are condensed into the parent class.
- HubEdos::UserAttributes, which is not a proxy, stops pretending to be one.
- A stray Rails route is removed for HubEdos::Person, a model lost in the mists of time.

CLC-6168 Flatten caching in HubEdos models

---

src/assets/javascripts/angular/controllers/widgets/delegateStudentsController.js
src/assets/templates/delegate_acting_as.html
src/assets/templates/no_bconnected.html
src/index-main.html

https://jira.berkeley.edu/browse/SISRP-13251
On the front-end, we continue to match the `act_as` pattern w.r.t delegate_acting_as. We also hide "connect bConnected" from delegates per https://jira.berkeley.edu/browse/SISRP-13258

SISRP-13251, like view-as footer we have delegate-view-as footer

---

app/controllers/act_as_controller.rb
app/controllers/canvas_lti_controller.rb
app/controllers/sessions_controller.rb
app/models/hub_edos/user_attributes.rb
app/models/user/authentication_validator.rb
config/settings.yml
fixtures/json/affiliations.json
lib/cache/cacheable.rb
spec/models/hub_edos/affiliations_spec.rb
spec/models/hub_edos/user_attributes_spec.rb
spec/models/user/authentication_validator_spec.rb

https://jira.berkeley.edu/browse/SISRP-12478
Subtasks:
SISRP-13420 Change SIR/Onboarding trigger
SISRP-13318 CC authentication needs to treat unreleased acceptances as null UIDs	
So far I haven't figured out a good way to mimic the "uid_error" behavior when Viewing As a not-yet-released admit. Doing that will just send you back to the landing page.

SISRP-12478 Handling undergrad/Slate applicants before official acceptance

---

app/models/oec/create_confirmation_sheets_task.rb
app/models/oec/merge_confirmation_sheets_task.rb
app/models/oec/merged_sheet_validation.rb
app/models/oec/remote_drive.rb
app/models/oec/report_diff_task.rb
app/models/oec/task.rb
app/models/oec/validator.rb
spec/models/oec/merge_confirmation_sheets_task_spec.rb
spec/models/oec/validation_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6175
For a large class of OEC errors involving user-modifiable data on Google Drive, surface the problem to users, but log at WARN instead of ERROR and don't include a stack trace.
For more serious problems, Google connection errors, etc., retain current behavior.

CLC-6175 Reduce log level on OEC unexpected-data errors

---

src/assets/templates/launcher.html
src/assets/templates/profile.html
src/assets/templates/widgets/gear_popover.html
src/assets/templates/widgets/profile_popover.html

https://jira.berkeley.edu/browse/SISRP-13258
https://jira.berkeley.edu/browse/SISRP-6601
Page 9 of PDF attached to SISRP-6601 has expected behavior.
**Note:** 
* This PR does not include top-nav logic to show/hide My Academics, My Finances and My Campus according to delegate permissions.
* I tried to be sparing in use of `api.user.profile.delegateActingAsUid`. The 'profile popover' is a sensitive beast.

SISRP-13258, delegate user cannot access profile, bconnected, alerts

---

app/controllers/user_api_controller.rb
app/models/hub_edos/user_attributes.rb
app/models/user/api.rb
fixtures/json/student_contacts.json
spec/controllers/user_api_controller_spec.rb
spec/models/hub_edos/user_attributes_spec.rb
spec/models/user/api_spec.rb
src/assets/templates/widgets/gear_popover.html

https://jira.berkeley.edu/browse/SISRP-13375
*Note:* From what I can tell, `preferred_name` and `last_name` are not used in templates but I kept them in the feed, with camelCase.  See Jira comments for more info.

SISRP-13375, delegate should never see student's preferred name

---

app/models/campus_solutions/delegate_students.rb
app/policies/authentication_state.rb
spec/controllers/campus_solutions/delegate_access_controller_spec.rb
spec/models/campus_solutions/delegate_students_spec.rb
spec/policies/authentication_state_spec.rb

https://jira.berkeley.edu/browse/SISRP-7689
The response (feed) from DelegateStudents needs a front-end-friendly structure (e.g., `feed[:privileges][:viewEnrollments] = true|false`). This leads to implementation of AuthenticationState#delegate_permissions. The `delegate_students.html` template will need trivial updates once this is merged.

SISRP-7689, transform delegate_students feed; delegate_permissions

---

app/models/service_alerts/merged.rb
spec/models/service_alerts/merged_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6185
Cache deletion before:
`/api/cache/delete?key=ServiceAlerts::Merged/ServiceAlerts::Merged`
`/api/cache/delete?key=ServiceAlerts::Merged/json-ServiceAlerts::Merged`
Cache deletion after:
`/api/cache/delete/ServiceAlerts::Merged`
[sigh]

CLC-6185 Fix wonky ServiceAlerts::Merged cache keys

---

app/controllers/delegate_act_as_controller.rb
app/models/campus_solutions/delegate_students.rb
spec/models/campus_solutions/delegate_students_spec.rb

https://jira.berkeley.edu/browse/SISRP-7689
The user cannot delegate-view-as unless s/he has one of: :financial, :viewEnrollments, :viewGrades. Delegates with only :phone privileges will be denied. Also, front-end needs `ldap_uid` in delegate_students card.

SISRP-7689, strengthen act_as_authorization and give front-end uid, too

---

spec/ui_selenium/my_profile_basic_info_spec.rb
spec/ui_selenium/my_profile_contact_info_spec.rb
spec/ui_selenium/pages/my_profile_basic_info_card.rb
spec/ui_selenium/pages/my_profile_contact_info_card.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6174
Changes:
- Alters validation tests for preferred name
- Ditches tests that will hit "preferred" flag validation errors
- Uses basic auth instead of CAS authentication so that any type of UID can be tested

CLC-6174 -  QA test fixes for v72 (profile tests)

---

app/controllers/advisor_act_as_controller.rb
app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/user_api_controller.rb
app/models/user_specific_model.rb
app/policies/authentication_state.rb
config/routes.rb
spec/controllers/user_api_controller_spec.rb
spec/models/user_specific_model_spec.rb
spec/policies/authentication_state_spec.rb
src/assets/javascripts/angular/factories/adminFactory.js

https://jira.berkeley.edu/browse/SISRP-14236
Following the pattern established by delegate-view-as. I created a distinct advisor-act-as controller and session variable because overloading the delegate-act-as logic would be prone to regressions.

SISRP-14236, act-as pattern for new advisor use case

---

app/models/campus_solutions/delegated_access_feature_flagged.rb
app/models/user/api.rb
app/policies/authentication_state_policy.rb
spec/models/hub_edos/user_attributes_spec.rb
spec/models/user/api_spec.rb
spec/policies/authentication_state_policy_spec.rb
src/assets/templates/toolbox.html
src/assets/templates/widgets/profile/delegate.html

https://jira.berkeley.edu/browse/SISRP-14262
* move `has_toolbox_tab?` to `User::Api` because logic needs user roles 
* `has_toolbox_tab?` is false if user is in view-as mode 
* delegate users lose status when feature flag is false
* clean up conditionals in `toolbox.html`

SISRP-14262, advisors get Toolbox; clean up data-ng-if statements in toolbox.html

---

app/controllers/yaml_settings_controller.rb
config/torquebox.rb
lib/calcentral_config.rb
lib/services/settings_reload_worker.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-5935
This doesn't solve the problem of accessing the web subsystem across multiple nodes, but I'm curious to see if it works with message processors across the cluster.

CLC-5935 Reload YAML settings in Torquebox message processors

---

app/models/campus_solutions/enrollment_terms.rb
fixtures/xml/campus_solutions/enrollment_terms.xml
public/dummy/json/enrollment_terms.json
spec/controllers/campus_solutions/enrollment_terms_controller_spec.rb
spec/models/campus_solutions/enrollment_terms_spec.rb

https://jira.berkeley.edu/browse/SISRP-13947
Adjusting proxy behavior to reflect data coming from a real endpoint.
Note that this proxy is no longer a straight passthrough; the `ACAD_CAREER` element is being denormalized to individual terms, as I think this will make things easier for the front end.

SISRP-13947 Add academic careers and student ID to enrollment terms proxy

---

app/controllers/campus_solutions/financial_aid_data_controller.rb
app/models/campus_solutions/my_financial_aid_filtered_for_advisor.rb
spec/controllers/campus_solutions/financial_aid_data_controller_spec.rb
spec/models/campus_solutions/my_financial_aid_filtered_for_advisor_spec.rb

https://jira.berkeley.edu/browse/SISRP-14283
FinancialAidDataController invokes filtered feed, which excludes 'Expected Family Contribution' and similar, when advisor-view-as mode.

SISRP-14283, filter out EFC when advisor-view-as

---

src/assets/javascripts/angular/services/profileMenuService.js
src/assets/templates/profile.html
src/assets/templates/widgets/profile/demographic.html
src/assets/templates/widgets/profile_popover.html

https://jira.berkeley.edu/browse/SISRP-14422
Advisor-view-as mode can get to /profile but will not see student's:
* demographics
* bConnected
* "Assign a delegate" call-to-action
I'm going to add *delegateActingAsUid* references to the `profileMenuService.js` logic just in case we decide to show limited profile to Delegates.

SISRP-14422, When advisor-view-as mode, show Profile but hide Demographics tab

---

app/models/campus_solutions/enrollment_term.rb
fixtures/xml/campus_solutions/enrollment_term.xml
fixtures/xml/campus_solutions/enrollment_terms.xml
public/dummy/json/enrollment_term.json
public/dummy/json/enrollment_terms.json
spec/controllers/campus_solutions/enrollment_term_controller_spec.rb
spec/controllers/campus_solutions/enrollment_terms_controller_spec.rb
spec/models/campus_solutions/enrollment_term_spec.rb
spec/models/campus_solutions/enrollment_terms_spec.rb
src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
src/assets/templates/widgets/enrollment/decide.html
src/assets/templates/widgets/enrollment_card.html

https://jira.berkeley.edu/browse/SISRP-13947
Adjustments to reflect the final shape of the enrollment term APIs, which diverge from originally expected behavior.
In particular, the "get all enrollment terms" endpoint currently returns many terms for each student, some of which will return no enrollment information via the "get specific enrollment term" endpoint. This requires a change in front-end behavior: instead of showing individual spinners for each term, we have to keep the main spinner active until all terms have loaded. Otherwise individual term cards would briefly appear with spinners, then disappear after coming back empty.

SISRP-13947 Update enrollment card to match API structure

---

app/models/campus_solutions/delegate_students_expiry.rb
app/models/campus_solutions/my_delegate_access.rb
spec/controllers/campus_solutions/delegate_access_controller_spec.rb
spec/models/campus_solutions/my_delegate_access_spec.rb

https://jira.berkeley.edu/browse/SISRP-14454
...such that the newly claimed student shows up on 'My Students' card.

SISRP-14454, flush CampusSolutions::DelegateStudents cache when user claims student

---

config/settings.yml

https://jira.berkeley.edu/browse/SISRP-14453
Fyi, if a delegate user claims a student the  `DelegateStudents` cache will be programmatically flushed.

SISRP-14453, proxy cache to 24h for DelegateStudents, etc.

---

script/sis/verify_sis_api_endpoints.sh
src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
src/assets/templates/widgets/enrollment/schedule.html

https://jira.berkeley.edu/browse/SISRP-14284
Follows up on #4849 with front-end code, and also an updated SIS verify script.
The changes in the Angular controller are necessary because the plural "enrollment terms" feed includes the required `acadCareer` parameter, but the singular "enrollment term" feed does not. Data from the latter must extend the former rather than replacing it.

SISRP-14284 Enrollment card front-end updates

---

spec/support/selenium_helper.rb
spec/ui_selenium/my_finances_finaid_budget_spec.rb
spec/ui_selenium/my_finances_finaid_legacy_spec.rb
spec/ui_selenium/my_finances_finaid_profile_spec.rb
spec/ui_selenium/my_finances_finaid_summary_spec.rb
spec/ui_selenium/pages/api_cs_aid_years_page.rb
spec/ui_selenium/pages/api_cs_fin_aid_data_page.rb
spec/ui_selenium/pages/api_cs_fin_aid_funding_sources_page.rb
spec/ui_selenium/pages/my_finances_financial_aid_page.rb
spec/ui_selenium/pages/my_finances_landing_page.rb
spec/ui_selenium/pages/my_finances_pages.rb
spec/ui_selenium/pages/my_profile_title_iv_card.rb
spec/ui_selenium/util/user_utils.rb
spec/ui_selenium/util/web_driver_utils.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6149
Includes:
* Rename existing Fin Aid messages spec to "legacy"
* Tests for the Fin Aid Summary UI (finances landing page and Fin Aid page), the Fin Aid Profile UI (including Title IV updates), and the Estimated Cost of Attendance UI
* A small number of sanity tests for the numbers presented to the user, though this will be expanded with part 2
Part 2 will include the Awards UI and the Comms UI

CLC-6149 - QA WebDriver tests for FinAid UIs, part 1

---

app/models/my_academics/filtered_for_delegate.rb
app/models/user/api.rb
app/models/user_specific_model.rb
app/policies/authentication_state.rb
spec/models/my_academics/filtered_for_delegate_spec.rb
spec/models/user/api_spec.rb
spec/models/user_specific_model_spec.rb
spec/policies/authentication_state_spec.rb
src/assets/templates/dashboard.html
src/assets/templates/navigation.html
src/assets/templates/profile.html

https://jira.berkeley.edu/browse/SISRP-14433
https://jira.berkeley.edu/browse/SISRP-14531
https://jira.berkeley.edu/browse/SISRP-14530
Few changes wrapped in one PR:
* move delegate_permissions check out of authentication_state
* all users get delegate_students check in `User::Api`
* `api.user.profile.hasDashboardTab`
* spec changes accordingly

SISRP-14433, any user, regardless of affiliations, can have delegating students

---

app/controllers/campus_solutions/academic_plan_controller.rb
app/models/campus_solutions/academic_plan.rb
app/models/campus_solutions/my_academic_plan.rb
config/routes.rb
fixtures/xml/campus_solutions/academic_plan.xml
public/dummy/json/academic_plan.json
spec/controllers/campus_solutions/academic_plan_controller_spec.rb
spec/models/campus_solutions/academic_plan_spec.rb

https://jira.berkeley.edu/browse/SISRP-14515
Note that the XML fixture includes an unparseable array attribute for the `ACADEMICPLAN` element, as currently returned by the CS API (bug reported in https://jira.berkeley.edu/browse/SISRP-14585). Still, `feed.updateAcademicPlan.url` is coming through, so we should be able to surface the deeplink in the front end if that is, in fact, a GL5 requirement.

SISRP-14515 Enrollment card: back end for academic plan

---

app/controllers/delegate_act_as_controller.rb
src/assets/templates/widgets/toolbox/delegate_students.html

https://jira.berkeley.edu/browse/SISRP-14532
Add `CampusSolutions::DelegateStudentsExpiry.expire` and toss out unnecessary `CalnetCrosswalk::ByUid` lookup.

SISRP-14532, Expire cache prior to delegate-view-as session to guarantee up-to-date privileges

---

app/models/my_academics/filtered_for_delegate.rb
spec/controllers/my_academics_controller_spec.rb
spec/models/my_academics/filtered_for_delegate_spec.rb

https://jira.berkeley.edu/browse/SISRP-14578
The feed of `filtered_for_delegate` depends on delegate privileges which cannot be predicted at cache warming time.

SISRP-14578, filtered_for_delegate should not have LiveUpdatesEnabled

---

app/models/campus_solutions/my_deposit.rb
app/models/campus_solutions/my_enrollment_term.rb
app/models/campus_solutions/my_financial_aid_data.rb
app/models/campus_solutions/my_financial_aid_funding_sources.rb
app/models/campus_solutions/my_financial_aid_funding_sources_term.rb
lib/cache/cached_feed.rb
lib/cache/json_added_cacher.rb
lib/cache/related_cache_key_tracker.rb
spec/lib/cache/related_cache_key_tracker_spec.rb

https://jira.berkeley.edu/browse/SISRP-13892
Refactor to make Cache::RelatedCacheKeyTracker work with Cache::JsonAddedCacher. Also changes RelatedCacheKeyTracker to group related keys by uid+class instead of just uid, so that expiring one set of related keys doesn't expire all other related keys for the user.

SISRP-13892 Make RelatedCacheKeyTracker aware of JSON keys

---

app/controllers/campus_solutions/financial_aid_data_controller.rb
app/models/campus_solutions/my_financial_aid_filtered_for_advisor.rb
app/models/campus_solutions/my_financial_aid_filtered_for_delegate.rb
spec/controllers/campus_solutions/financial_aid_data_controller_spec.rb
spec/models/campus_solutions/my_financial_aid_filtered_for_delegate_spec.rb

https://jira.berkeley.edu/browse/SISRP-14529
Piggyback on logic of the advisors filter whilst keeping purposes separate.

SISRP-14529, hide Est. Family Contrib and similar financial data from delegates

---

app/models/calnet_ldap/user_attributes.rb
spec/models/calnet_ldap/user_attributes_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6200
One more cached translator proxy, on the model of CampusOracle::UserAttributes and HubEdos::UserAttributes.

CLC-6200 Add a CalnetLdap flavor of UserAttributes

---

app/policies/authentication_state.rb

https://jira.berkeley.edu/browse/SISRP-14663
The change in `viewing_as?` method is what forces reauth. The rest is also necessary for validating the post-reauth checks.

SISRP-14663, Advisor view-as should respect reauthentication

---

package.json

https://jira.ets.berkeley.edu/jira/browse/CLC-6205
We'll restore jscs: "^2.0.0" with https://jira.ets.berkeley.edu/jira/browse/CLC-6206

CLC-6205, pin jscs to 2.0.0 for now

---

app/controllers/config_controller.rb
app/models/campus_solutions/my_delegate_access.rb
spec/controllers/campus_solutions/delegate_access_controller_spec.rb

https://jira.berkeley.edu/browse/SISRP-14454
User::Api flush is needed to get `hasToolboxTab: true` and then 'My Students' card.

SISRP-14454, flush User::Api cache after delegate claims student

---

spec/ui_selenium/my_academics_data_final_exams_spec.rb
spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb
spec/ui_selenium/my_academics_data_status_blocks_spec.rb
spec/ui_selenium/my_finances_data_acct_summary_spec.rb
spec/ui_selenium/pages/api_my_academics_page.rb
spec/ui_selenium/pages/api_my_badges_page.rb
spec/ui_selenium/pages/my_academics_status_and_blocks_card.rb
spec/ui_selenium/user_authorizations_spec.rb
spec/ui_selenium/util/user_utils.rb

https://jira.berkeley.edu/browse/SISRP-14107
Final set of Selenium test fixes for v73:
* Toolbox View as - wait more patiently for "saved" and "recent" users tables to be updated
* CFV - stop expecting open transactions and account balance to be in sync in test environments
* Status and residency - don't expect residency info for Haas students; test clean-up
* Academic profile - trigger test failure only when term transition occurs (as way of alerting to the coming and going of term transition phases)
* Final exams - test clean-up

SISRP-14107 - QA test fixes

---

src/assets/javascripts/angular/factories/adminFactory.js

https://jira.berkeley.edu/browse/SISRP-15082
You get limited Advisor-view-as session if you are not SuperUser and do not have standard view-as permission.

SISRP-15082, Acting as a super user with the advisor affiliation gives the wrong experience

---

app/models/campus_solutions/academic_plan.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml
config/settings/testext.yml
fixtures/xml/campus_solutions/academic_plan.xml
public/dummy/json/academic_plan.json
spec/controllers/campus_solutions/academic_plan_controller_spec.rb
spec/models/campus_solutions/academic_plan_spec.rb
src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
src/assets/javascripts/angular/factories/adminFactory.js
src/assets/templates/widgets/advisor/resources.html
src/assets/templates/widgets/enrollment/plan.html

https://jira.berkeley.edu/browse/SISRP-15110
SISRP-15173 - Advisor View As: JS error when attempting to view as
https://jira.berkeley.edu/browse/SISRP-15173
SISRP-15179 - Hide Academic Progress report - in advising resources till GL5.4
https://jira.berkeley.edu/browse/SISRP-15179
SISRP-15092 - Hide academic planner link till GL5.4 on enrollment card.
https://jira.berkeley.edu/browse/SISRP-15092

SISRP-15110 - Update CalCentral with the new academic planner API url

---

app/models/cal1card/my_cal1card.rb
app/models/cal1card/photo.rb
config/settings.yml
spec/models/cal1card/photo_spec.rb

https://jira.berkeley.edu/browse/SISRP-14362
It turns out this is no longer a requirement for delegated access, but we're bound to need it at some point.
NB: This shortens the Cal1card base URL and will require corresponding changes in local YAML.

SISRP-14362 Create proxy for Cal1card photo API

---

app/models/user/api.rb
spec/models/user/api_spec.rb

https://jira.berkeley.edu/browse/SISRP-15334
When delegate-view-as mode the `get_my_students query` should use uid = original_delegate_user_id

SISRP-15334, delegates should not see Academics if privilege is only 'financial'

---

src/assets/templates/academics.html

https://jira.berkeley.edu/browse/SISRP-15336
We were seeing teaching card because `api.user.profile.roles.faculty` is true, not because front-end is receiving teaching classes.

SISRP-15336, delegate sees GSI teaching card

---

app/controllers/act_as_controller.rb
app/controllers/sessions_controller.rb
app/models/campus_solutions/user_api_expiry.rb

https://jira.berkeley.edu/browse/SISRP-15340
There are two scenarios to consider – see Jira comments. Note: `UserApiController.expire` is a no-op but we add it to `UserApiExpiry` just in case.

SISRP-15340, When delegate ends view-as session, flush cache per student UID

---

app/controllers/application_controller.rb
app/controllers/delegate_act_as_controller.rb
spec/controllers/config_controller_spec.rb

https://jira.berkeley.edu/browse/SISRP-13710
`current_user.viewing_as?` is true when delegate enters view-as so we must get more granular. Only require re-auth if it's standard-view-as or advisor-view-as.

SISRP-13710, delegate users do not need to reauth when view-as

---

app/models/hub_edos/user_attributes.rb
spec/models/hub_edos/user_attributes_spec.rb
spec/models/user/api_spec.rb

https://jira.berkeley.edu/browse/SISRP-15467
Exceptions in Hub API parsing currently trigger complete blankness. Service policy is that as much UX as possible should survive any API issues.

SISRP-15467 Do not break api/my/status on unexpected Hub payloads

---

src/assets/templates/delegate_welcome.html

https://jira.berkeley.edu/browse/SISRP-15505
We don't want delegate to inadvertently go to this page while still viewing-as.

SISRP-15505, no 'Link Your Account with Your Student' page when delegate-view-as mode

---

app/models/campus_solutions/language_delete.rb
config/routes.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml
config/settings/testext.yml
fixtures/xml/campus_solutions/language_delete.xml
spec/controllers/campus_solutions/language_controller_spec.rb
spec/models/campus_solutions/language_delete_spec.rb
src/assets/javascripts/angular/services/profileMenuService.js

@johncrossman, @paulkerschen: PR covers some minor/cosmetic changes for the languages edit story on the ruby side, plus a feature flag
+ change xhr param name froom `jpmCatItemId` to `languageCode` (prefer the latter in the angular controller that refers to it)
+ change expected languageCode values from `EN` to `LEN`
+ add feature flag `cs_profile_languages`
Let me know if anything should be modified here.

SISRP-10777 ~ prework for profile language edits on the backend

---

script/sis/verify_sis_api_endpoints.sh

https://jira.berkeley.edu/browse/SISRP-14832
The intended precedence seems to work. I.e., local.yml wins when feature flag is set in both files.

SISRP-14832, verify_sis_api_endpoints loads config/settings.yml for default feature flag settings

---

app/models/campus_solutions/my_financial_aid_filtered_for_advisor.rb
app/models/campus_solutions/my_financial_aid_filtered_for_delegate.rb
spec/models/campus_solutions/my_financial_aid_filtered_for_advisor_spec.rb
spec/models/campus_solutions/my_financial_aid_filtered_for_delegate_spec.rb

https://jira.berkeley.edu/browse/SISRP-15079
Refactors for filtering of 'Expected Family Contribution' and 'Berkeley Family Contribution' only, allowing 'Dependency Status' and 'Family Members in College'

SISRP-15079 - Refactors for filtering of confidential group items

---

app/controllers/act_as_controller.rb
app/controllers/advisor_act_as_controller.rb
app/controllers/application_controller.rb
app/controllers/concerns/session_key.rb
app/controllers/delegate_act_as_controller.rb
app/controllers/sessions_controller.rb
app/models/user_specific_model.rb
app/policies/authentication_state.rb
spec/controllers/act_as_controller_spec.rb
spec/controllers/bootstrap_controller_spec.rb
spec/controllers/campus_solutions/financial_aid_data_controller_spec.rb
spec/controllers/canvas_lti_controller_spec.rb
spec/controllers/google_auth_controller_spec.rb
spec/controllers/my_badges_controller_spec.rb
spec/controllers/my_events_controller_spec.rb
spec/controllers/my_tasks_controller_spec.rb
spec/controllers/my_up_next_controller_spec.rb
spec/controllers/routes_list_controller_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/controllers/user_api_controller_spec.rb
spec/models/campus_solutions/my_financial_aid_filtered_for_advisor_spec.rb
spec/models/campus_solutions/my_financial_aid_filtered_for_delegate_spec.rb
spec/models/user/api_spec.rb
spec/models/user_specific_model_spec.rb
spec/models/webcast/merged_spec.rb
spec/policies/authentication_state_policy_spec.rb
spec/policies/authentication_state_spec.rb

https://jira.berkeley.edu/browse/SISRP-15421
This is a prelude to cache-key management scheme involving auth-state. There are many files touched but most are specs. No major refactoring, just formalizing session keys.

SISRP-15421, formalize set of view-as related session keys

---

app/controllers/act_as_controller.rb
app/controllers/application_controller.rb
app/controllers/photo_controller.rb
app/controllers/sessions_controller.rb
app/controllers/user_api_controller.rb
app/models/cal1card/photo.rb
app/models/campus_solutions/user_api_expiry.rb
app/models/user/api.rb
app/models/user/photo.rb
lib/cache/key_generator.rb
spec/controllers/photo_controller_spec.rb
spec/lib/cache/key_generator_spec.rb

https://jira.berkeley.edu/browse/SISRP-15421
Examples of caching gone wrong: 
* https://jira.berkeley.edu/browse/SISRP-15340 
* https://jira.berkeley.edu/browse/SISRP-15276
**Note:** custom cache keys will also happen when `canvas_masquerading_user_id` is present.
This PR is a partial undo of #4935

SISRP-15421, cache key generator to accomodate isolated view-as caches

---

app/models/my_academics/college_and_level.rb
app/models/my_badges/student_info.rb
public/dummy/json/academics.json
public/dummy/json/academics_transition_future_profile.json
public/dummy/json/academics_transition_past_profile_not_registered.json
public/dummy/json/academics_transition_past_profile_registered.json
spec/models/my_academics/college_and_level_spec.rb
src/assets/javascripts/angular/controllers/pages/academicsController.js
src/assets/javascripts/angular/services/academicsService.js
src/assets/stylesheets/_profile.scss
src/assets/templates/academics_student_profile.html

https://jira.berkeley.edu/browse/SISRP-13245
JIRA with designs: https://jira.berkeley.edu/browse/SISRP-11939
While waiting for the Hub to finalize its academic status endpoint, we can go ahead and adapt our legacy academics feed to the GL5 academic profile design.
- All users, new and old, get the new design from the JIRA, _except_ that continuing students will not lose the "Including AP / Not Including AP" distinction if relevant.
- Our incomplete-profile messaging remains, but users with 10-digit Campus Solutions IDs will not be directed to Bearfacts.
- The back end replaces its concept of "standing" with possibly-plural "careers."
- "Colleges" becomes "majors," in order to make room for the "minors" data that our new source will provide.

SISRP-13245 Adapt legacy Bearfacts data to GL5 academic profile design

---

app/controllers/act_as_controller.rb
app/controllers/delegate_act_as_controller.rb
app/controllers/sessions_controller.rb

https://jira.berkeley.edu/browse/SISRP-15608
Post-processing when view-as session ends. Same pattern as `after_successful_start`.

SISRP-15608, handle delegate deletion during view-as session

---

app/controllers/photo_controller.rb
app/models/campus_oracle/queries.rb
app/models/rosters/campus.rb
app/models/rosters/canvas.rb
app/models/rosters/common.rb
app/models/user/photo.rb
spec/controllers/photo_controller_spec.rb
spec/models/rosters/canvas_spec.rb
spec/models/rosters/common_spec.rb
spec/models/user/api_spec.rb
src/assets/javascripts/angular/directives/loadErrorDirective.js
src/assets/templates/widgets/roster_photo.html

https://jira.berkeley.edu/browse/SISRP-13855
Moving away from database photo queries loses us the ability to check (via photo_bytes join) whether a photo exists for a given student before trying to fetch it. An Angular directive now swaps in the "photo unavailable" image in the event of a load error.

SISRP-13855 Use Cal1card proxy for user and roster photos

---

app/controllers/advisor_act_as_controller.rb
app/controllers/delegate_act_as_controller.rb

https://jira.berkeley.edu/browse/SISRP-15732
Related to #4807
References to NotAuthorizedError were invalid, and thus won't result in the empty 403 response we're wanting.
```
>> NotAuthorizedError
NameError: uninitialized constant NotAuthorizedError
>> Pundit::NotAuthorizedError
=> Pundit::NotAuthorizedError
```
This wasn't caught because the class constant isn't called when the conditional doesn't apply
```
>> raise MyMadeUpException if 1 == 0
=> nil
>> raise MyMadeUpException if 1 == 1
NameError: uninitialized constant MyMadeUpException
>> AnotherMadeUpconstant.do_something if 1 == 0
=> nil
```

SISRP-15732 - Fixes references to Pundit::NotAuthorizedError exception class

---

app/controllers/hub_edo_controller.rb
app/models/hub_edos/contacts.rb
app/models/hub_edos/demographics.rb
app/models/hub_edos/my_student.rb
app/models/user_specific_model.rb
spec/controllers/hub_edo_controller_spec.rb
spec/models/hub_edos/my_student_spec.rb
spec/support/campus_solutions_helper_module.rb
src/assets/javascripts/angular/controllers/widgets/statusController.js

https://jira.berkeley.edu/browse/SISRP-15682
We don't want proxy classes to care about session variables so I've made the previously static `include_fields` list configurable via `options` hash. I also added `Cache::KeyGenerator.per_view_as_type` as needed.

SISRP-15682, filter /api/edos/ feeds per view-as type

---

app/models/oec/administrator.rb
spec/models/oec/administrator_spec.rb

https://jira.berkeley.edu/browse/SISRP-15812
Thank you @redconfetti for reporting this bug. Auth is strengthened and we log error if config is blank.

SISRP-15812, more robust auth for oec.admin

---

src/assets/templates/widgets/profile/languages_section_editor.html

@christianvuerings this fix restores the name attribute to the required select element (it's ref'd in validation code).

SISRP-10777 Languages Card template fix

---

src/assets/templates/cars_summary.html

https://jira.berkeley.edu/browse/SISRP-15810
**Note:** This PR only hides the `CARS > eBill` link. The other examples are "My Campus" links (i.e., pulled from calcentral db) and don't come with metadata related to `canSeeCSLinks`. Delegates will continue to see all My Campus links. Afaik, we have no security risk here. @raydavis agrees.

SISRP-15810, hide link to Bear Facts > CARS > eBill unless user canSeeCSLinks

---

app/models/my_academics/college_and_level.rb
app/models/user/student.rb
spec/models/user/student_spec.rb

https://jira.berkeley.edu/browse/SISRP-15999 should have been addressed in #4973, but this gives us a fighting chance to verify outside of production.
Also ensure that Hub-sourced academic data includes a term name even if nothing else.

CLC-15999 Point legacy_user? check to LDAP if CS ID is unavailable

---

fixtures/xml/campus_solutions/ferpa_deeplink_url.xml
spec/models/campus_solutions/ferpa_deeplink_spec.rb

https://jira.berkeley.edu/browse/SISRP-16031
The RSpec change is backwards-compatible (just in case the CS API reverts to the old payload format).

SISRP-16031 Stop pretending we can predict CS FERPA URL paths

---

app/models/berkeley/user_roles.rb
app/models/my_badges/student_info.rb
spec/models/berkeley/user_roles_spec.rb
spec/models/my_badges/student_info_spec.rb

https://jira.berkeley.edu/browse/SISRP-14774
Replacement for BearFacts-API-dependent logic.
For now, the Academics profile continues to rely on academic status feeds rather than affiliations.

SISRP-14774 Identify Law students from Campus Solutions

---

config/settings.yml
lib/proxies/base_proxy.rb
spec/lib/proxies/base_proxy_spec.rb

https://jira.berkeley.edu/browse/SISRP-15830
Notes:
* I've put default 30 second timeout on Hub, CS, Crosswalk. That value matches what was in use before: `application.outgoing_http_timeout`
* BaseProxy intercepts the call to `get_response()` and injects optional timeout. This seemed the most elegant way to avoid code duplication in subclasses. Notice that `Proxies::HttpClient` does not have a handle on the Settings object.
* In a moment I'll describe steps to verify in Jira above.

SISRP-15830, proxy can have custom HTTP-timeout setting

---

app/controllers/bootstrap_controller.rb
lib/cache/related_cache_key_tracker.rb

I wouldn't call this a long-term fix for https://jira.berkeley.edu/browse/SISRP-16120, but I would like to see if it reduces blockage for QA while we consider next steps.
Also remove the ucUpdateCache query-param check for finaid and enrollment, since that's one bit of redundancy we have power to skip.

SISRP-16120 Have RelatedCacheKeyTracker register keys after creation, not before

---

app/models/oec/merged_sheet_validation.rb
spec/models/oec/publish_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6226 revealed a need for more explicit referential integrity checks between worksheets prior to sending them Blue-ward. 
Validate that certain ID sets are identical between worksheets, as specified.

CLC-6226 OEC: tighten data integrity checks prior to Blue push

---

lib/proxies/base_proxy.rb

3 X [every user in CalCentral] X [every time the basic Hub caches expire] = an awful lot of duplicate log messages.

NOJIRA Do not repeatedly log configuration setting at WARN-level

---

app/models/calnet_ldap/user_attributes.rb
spec/models/calnet_ldap/user_attributes_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6238
This was always our intention but we weren't checking the right LDAP attributes.
(The equivalent change for bCourses account management will be handled in other tasks.)

CLC-6238 Display CalNet Directory first/last names as determined by user

---

src/assets/javascripts/angular/controllers/pages/academicsController.js
src/assets/templates/academics_student_profile.html

https://jira.berkeley.edu/browse/SISRP-16301
Main issue here is the strict-equality check, `value !== null`.  If value is `0` or `undefined` or the empty string, this check will still return `true`.  
<del>Better to set the property to a Number explicitly in the controller using `parseFloat` and check in the template that `value > 0`</del>
@christianvuerings `parseFloat()` returns `NaN` when the input does not contain at least one digit.  Also,  the `value > 0` checks should be corrected to `value >= 0`

SISRP-16301 - Academic Profile: "Earned Units" label showing when there are no units yet

---

app/models/campus_oracle/queries.rb
spec/models/campus_oracle/queries_spec.rb

https://jira.berkeley.edu/browse/SISRP-16369
@raydavis should review/merge this one because I think he is author of `get_student_term_info(person_id)` which is documented with 'currently used only for support and research, not by deployed code'.  If its usefulness has expired then this PR can be merged.
`is_previous_ugrad?(ldap_uid)` was only used by the spec.

SISRP-16369, remove two unused queries from CampusOracle::Queries

---

config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/test.yml
config/settings/testext.yml

https://jira.berkeley.edu/browse/SISRP-16371
For now, only the _settings.yml_ file gets `edo_oracle` config. Plus:
* I added extra line breaks in YAMLs for readability.
* `application` setting is always at top of YAML

SISRP-16371, edo_oracle in YAMLs of Git:/config

---

script/sis/verify_sis_api_endpoints.sh

https://jira.berkeley.edu/browse/SISRP-16579
I've moved `API_ERROR_INDICATORS` to top of script, for the sake of prominence, and added to its list per Jira above.

SISRP-16579, SIS API endpoint must know about new Hub API error format

---

config/settings.yml
config/settings/development.yml
config/settings/production.yml
config/settings/testext.yml

https://jira.berkeley.edu/browse/SISRP-14768
EDO DB settings should be configured per environment on the `campusdb` convention, and called `edodb` to match the database.yml entry.

SISRP-14768 Per-environment edodb settings on campusdb pattern

---

app/models/berkeley/term.rb
app/models/berkeley/term_codes.rb
app/models/edo_oracle/queries.rb
spec/models/berkeley/term_codes_spec.rb
spec/models/berkeley/term_spec.rb

https://jira.berkeley.edu/browse/SISRP-15857
No spec yet; a sanity check under testext is coming.
Term-code converter also takes more flexible input.

SISRP-15857 EdoDb: Get instructing sections for UID and terms

---

app/models/edo_oracle/queries.rb

https://jira.berkeley.edu/browse/SISRP-15857
- Remove join on unused SISEDO.CLASSV00_VW.
- Do not screen out results where crs."status-code" is NULL because LEFT OUTER JOIN matched no row in SISEDO.API_COURSEV00_VW.

SISRP-15857 EdoDb: tweaks to get_sections_from_section_ids

---

app/models/user/aggregated_attributes.rb
app/models/user/api.rb
spec/models/user/aggregated_attributes_spec.rb

The student-overview page for Advisors needs an easy way to pull student attributes using our split-brain logic. This PR extracts logic of EDO/LDAP/Legacy precedence from User::Api and makes it available as a standalone for future use in student_overview_controller. 
**Note:** No change to `api_spec.rb`.

SISRP-15118, student summary card needs a standalone, split-brain getUserAttributes feed

---

app/models/edo_oracle/queries.rb
spec/models/edo_oracle/queries_spec.rb

https://jira.berkeley.edu/browse/SISRP-16710
Adds EdoOracle::Queries.get_section_meetings method as equivalent of CampusOracle::Queries.get_section_schedules

SISRP-16710 - Adds EdoOracle::Queries.get_section_meetings

---

app/models/berkeley/term.rb
app/models/berkeley/terms.rb
config/settings.yml
spec/models/berkeley/term_spec.rb

First bit of support for https://jira.berkeley.edu/browse/SISRP-16877.
A YAML cutoff is handy for two reasons:
- Moving it into the future is equivalent to switching off an EdoOracle feature flag entirely.
- Moving it into the past allows devs and QA to do limited verification of EdoOracle against converted legacy data.

SISRP-16877 Add cutoff in YAML to specify per-term academic data source

---

app/controllers/student_overview_controller.rb
app/models/user/aggregated_attributes.rb
app/models/user/api.rb
config/routes.rb
spec/controllers/student_overview_controller_spec.rb
spec/models/user/aggregated_attributes_spec.rb

`StudentOverviewController` returns aggregated-user-attributes as long as user `can_view_as_for_all_uids?` and the target UID is student, exStudent or applicant. Making `User::AggregatedAttributes` a CachedFeed seemed necessary, sensible and not terribly disruptive to `User::Api`. 
**Note:** Changes in `routes.rb` are in the spirit of readability.

SISRP-15118, AggregatedAttributes feed for Advisor's student summary card

---

app/models/berkeley/term.rb
app/models/berkeley/term_codes.rb
app/models/berkeley/terms.rb
app/models/campus_oracle/user_courses/base.rb
app/models/edo_oracle/course_sections.rb
app/models/edo_oracle/queries.rb
app/models/edo_oracle/user_courses/all.rb
app/models/edo_oracle/user_courses/base.rb
app/models/edo_oracle/user_courses/selected_sections.rb
spec/models/berkeley/term_spec.rb
spec/models/berkeley/terms_spec.rb
spec/models/campus_oracle/user_courses/base_spec.rb
spec/models/edo_oracle/course_sections_spec.rb
spec/models/edo_oracle/queries_spec.rb
spec/models/edo_oracle/user_courses/base_spec.rb

https://jira.berkeley.edu/browse/SISRP-16715
https://jira.berkeley.edu/browse/SISRP-16716
https://jira.berkeley.edu/browse/SISRP-16877
https://jira.berkeley.edu/browse/SISRP-16878
EdoOracle::UserCourses contains translator classes on the pattern of CampusOracle::UserCourses. There is some oddness and redundancy in the constructed feeds because that's what the higher-level classes are expecting.
Cross-listings can now be determined from the cs-course-id column; implicitly taught sections can be determined from the primaryAssociatedSection column. Both are tracked while building the UserCourses feed for instructors.
Specs are present but will need better data to exercise a wider range of cases.
Legacy term cutoff logic is moved into Berkeley::Terms initialization so as to avoid a bunch of …

SISRP-16877 EdoOracle::UserCourses models and tests

---

app/models/edo_oracle/queries.rb
spec/models/edo_oracle/queries_spec.rb

https://jira.berkeley.edu/browse/SISRP-16717
Creates EdoOracle::Queries method as equivalent of CampusOracle::Queries.terms

SISRP-16717 - Adds EdoOracle::Queries.terms

---

app/models/edo_oracle/queries.rb
spec/models/edo_oracle/queries_spec.rb

https://jira.berkeley.edu/browse/SISRP-16713
Creates EdoOracle::Queries method as equivalent of CampusOracle::Queries.get_enrolled_students

SISRP-16713 - EdoOracle::Queries.get_enrolled_students

---

app/models/edo_oracle/connection.rb
app/models/edo_oracle/queries.rb
spec/models/edo_oracle/queries_spec.rb

https://jira.berkeley.edu/browse/SISRP-17106
Implement EDO DB equivalent of CampusOracle::Queries#has_instructor_history?

SISRP-17106 - Adds EdoOracle::Queries#has_instructor_history?

---

app/models/edo_oracle/queries.rb

Follow-up to #5137 (fun with booleans that ain't booleans). We want primary sections ordered first.
https://jira.berkeley.edu/browse/SISRP-16880

SISRP-16880 EdoOracle::Queries: 'true' > 'false'

---

app/models/berkeley/term.rb
app/models/edo_oracle/queries.rb
spec/models/edo_oracle/queries_spec.rb

https://jira.berkeley.edu/browse/SISRP-17149
Establishes equivalent of CampusOracle::Queries.has_student_history? inside of EdoOracle::Queries

SISRP-17149 - EdoOracle::Queries.has_student_history?

---

app/models/calnet_crosswalk/proxy.rb
fixtures/json/calnet_crosswalk_5030615093.json
fixtures/json/calnet_crosswalk_61889.json
spec/models/calnet_crosswalk/by_cs_id_spec.rb
spec/models/calnet_crosswalk/by_uid_spec.rb

https://jira.berkeley.edu/browse/SISRP-16962
Note:
* We do a conservative check on `isPrimaryForIdentifierType`: evaluate to false if and only if element is present and equal to false.
* The `isActive` attribute has been unreliable in production so we give it no import in our spec / fixture.

SISRP-16962, CalCentral must consider isPrimaryForIdentifierType flag in Crosswalk response

---

app/models/edo_oracle/queries.rb
app/models/edo_oracle/user_courses/base.rb
spec/models/edo_oracle/user_courses/base_spec.rb

https://jira.berkeley.edu/browse/SISRP-16877
The nature of the course-section join in the EDO DB is such that the "course" half of the row might come back null. We must adapt or perish.

SISRP-16877 Handle sparse results from EDO DB

---

app/models/edo_oracle/connection.rb
app/models/edo_oracle/queries.rb
config/settings.yml
config/settings/test.yml
config/settings/testext.yml
lib/oracle_base.rb

https://jira.berkeley.edu/browse/SISRP-17174
WARNING: A no-op "fake: true" development.yml configuration setting (along with misleading default "edodb" values in settings.yml) wrongly slipped into an earlier commit. This default setting will now have an effect, and developers who want real EDO DB access must update their development.local.yml files.

SISRP-17174 Implement basic fake mode for EDO DB

---

app/models/canvas_csv/add_new_users.rb
app/models/canvas_csv/base.rb
app/models/canvas_csv/maintain_users.rb
app/models/canvas_csv/site_memberships_maintainer.rb
app/models/mailing_lists/site_mailing_list.rb
spec/models/canvas_csv/add_new_users_spec.rb
spec/models/canvas_csv/base_spec.rb
spec/models/canvas_csv/maintain_users_spec.rb
spec/models/mailing_lists/site_mailing_list_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6239
Most of this PR teaches bCourses to accept the slightly more abstracted User::BasicAttributes structure in lieu of an Oracle row. 
The only (intended) change to logic is removal of the code path that handles Oracle-LDAP disjuncture.

CLC-6239 Switch bCourses user account data source to Oracle-LDAP merge

---

app/controllers/student_overview_controller.rb
config/routes.rb
spec/controllers/student_overview_controller_spec.rb
src/assets/javascripts/angular/configuration/routeConfiguration.js
src/assets/javascripts/angular/controllers/pages/advisorStudentOverviewController.js
src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
src/assets/javascripts/angular/factories/advisorStudentOverviewFactory.js
src/assets/javascripts/angular/factories/enrollmentFactory.js
src/assets/javascripts/angular/services/userService.js
src/assets/templates/advisor_student_overview.html
src/assets/templates/widgets/enrollment/schedule.html

https://jira.berkeley.edu/browse/SISRP-16749
Notables:
* student_overview_controller enforces `authorize_student_lookup` on all of its routes
* front-end enrollment-card code is reused with new hook added: `apiService.util.getAdvisingStudentLookupUID()`
* suppress magic URLs with expanded `canSeeCSLinks` logic in userService.js

SISRP-16749, enrollment card for advising-student-lookup with canSeeCSLinks: false

---

app/controllers/application_controller.rb
app/controllers/campus_solutions/higher_one_url_controller.rb
app/controllers/concerns/disallow_classic_view_as.rb
app/controllers/user_api_controller.rb
app/models/campus_solutions/my_higher_one_url.rb
app/models/up_next/my_up_next.rb
app/models/user/api.rb
lib/cache/cached_feed.rb
public/dummy/json/status.json
spec/controllers/campus_solutions/higher_one_url_controller_spec.rb
spec/controllers/user_api_controller_spec.rb
spec/models/user/api_spec.rb
src/assets/javascripts/angular/controllers/widgets/sir/sirItemReceivedController.js
src/assets/javascripts/angular/services/userService.js
src/assets/templates/widgets/enrollment/schedule.html
src/assets/templates/widgets/sir/sir_item_received.html

https://jira.berkeley.edu/browse/SISRP-17213
* Fixes some broken Higher One controller logic.
* Completes our menu of View-As authorization options.
* Centralizes session-state-dependent elements of the User::Api feed in the merged model class.
* Reduces duplication of back-end and front-end authorization logic.
* Fixes a little annoyance for us Rails console users (not being able to type User::Api.new(uid).init.get_feed)
@christianvuerings, so far I've been unable to find a way to test the front-end changes.
@johncrossman , I'd appreciate your eyes on this one, too. Thanks!

SISRP-17213 Do not fetch or show unusable Higher One link

---

app/models/berkeley/terms.rb
app/models/campus_oracle/queries.rb
app/models/canvas/current_teacher.rb
app/models/edo_oracle/queries.rb
app/models/user/academic_history.rb
spec/models/berkeley/terms_spec.rb
spec/models/campus_oracle/user_courses/has_instructor_history_spec.rb
spec/models/campus_oracle/user_courses/has_student_history_spec.rb
spec/models/canvas/current_teacher_spec.rb
spec/models/edo_oracle/queries_spec.rb
spec/models/user/academic_history_spec.rb

https://jira.berkeley.edu/browse/SISRP-17167
* Introduces Berkeley::Terms.legacy_group to segregate terms into a hash with `:legacy` and `:sisedo` arrays.
* Updated EdoOracle::Queries.has_instructor_history? so that it returns `false` when terms array is empty
* Ensures CampusOracle::Queries.has_instructor_history? returns false when terms array is empty
* Retrofits Canvas::CurrentTeacher to use User::AcademicHistory.has_instructor_history? with support for legacy and SISEDO sources

SISRP-17167 - Retrofit Canvas::CurrentTeacher#user_currently_teaching?

---

app/models/rosters/campus.rb
app/models/rosters/canvas.rb
app/models/rosters/common.rb
spec/models/rosters/campus_spec.rb
spec/models/rosters/canvas_spec.rb

https://jira.berkeley.edu/browse/SISRP-17267

SISRP-17267 Retrofit rosters to query EdoOracle on non-legacy terms

---

app/models/rosters/common.rb
spec/models/rosters/campus_spec.rb
spec/models/rosters/canvas_spec.rb

https://jira.berkeley.edu/browse/SISRP-17267
Corrective follow-up to #5162. In my haste to retrofit the rosters I neglected to honor my own abstraction layer.

SISRP-17267 Rosters should rely on merged User::BasicAttributes layer

---

app/policies/authentication_state_policy.rb
spec/policies/authentication_state_policy_spec.rb
src/assets/templates/advising_student.html

https://jira.berkeley.edu/browse/SISRP-17445
* add @user.directly_authenticated? to logic of `can_view_as_for_all_uids?`
* test coverage
* /advising/student/$UID gets 404 unless directly_authenticated

SISRP-17445, 404 on student overview if not directlyAuthenticated

---

app/models/campus_oracle/user_attributes.rb
spec/models/campus_oracle/user_attributes_spec.rb
src/assets/templates/academics_status_holds_blocks.html

https://jira.berkeley.edu/browse/SISRP-17479
Residency status is no longer being kept current in DB2, and must be suppressed in CalCentral until we switch to Campus Solutions as source of record. We've been told to suppress the accompanying message and link as well.

SISRP-17479 Suppress CampusOracle-derived residency status and messaging

---

app/models/campus_solutions/my_academic_plan.rb
app/models/campus_solutions/my_aid_years.rb
app/models/campus_solutions/my_billing.rb
app/models/campus_solutions/my_enrollment_term.rb
app/models/campus_solutions/my_enrollment_terms.rb
app/models/campus_solutions/my_financial_aid_compare_awards_current.rb
app/models/campus_solutions/my_financial_aid_compare_awards_list.rb
app/models/campus_solutions/my_financial_aid_compare_awards_prior.rb
app/models/campus_solutions/my_financial_aid_data.rb
app/models/campus_solutions/my_financial_aid_funding_sources.rb
app/models/campus_solutions/my_financial_aid_funding_sources_term.rb
app/models/campus_solutions/my_holds.rb
app/models/hub_edos/my_student.rb
app/models/hub_edos/my_work_experience.rb

https://jira.berkeley.edu/browse/SISRP-17104
Last batch for now. Similar problems doubtlessly lurk in other classes, but the changes thus far cover the feeds directly involved in SISRP-16997 and make a pretty big QA footprint.
* LiveUpdatesEnabled with FreshenOnWarm bypasses the feed's configured lifespan while the user is logged in by forcing a feed refresh every 5 minutes. We don't want to hit external APIs that often, so this should only be done if the feed is made up of other source feeds all of which are themselves cached, the idea being to catch them not long after they expire.
* All server-side feeds marked as LiveUpdatesEnabled will react to the 5-minute ping. But the only ones which get checked by the browser are the 6 listed in "updatedFeedsService.js". The others won't be …

SISRP-17104 Cache fixes for CampusSolutions, HubEdos feeds

---

app/controllers/advising_student_controller.rb
app/controllers/advisor_act_as_controller.rb
app/controllers/campus_solutions/advising_resources_controller.rb
app/controllers/concerns/advisor_authorization.rb
app/controllers/concerns/view_as_authorization.rb
app/controllers/search_users_controller.rb
app/controllers/stored_users_controller.rb
app/policies/authentication_state_policy.rb
spec/controllers/advising_student_controller_spec.rb
spec/controllers/concerns/advisor_authorization_spec.rb
spec/controllers/concerns/view_as_authorization_spec.rb
spec/policies/authentication_state_policy_spec.rb
src/assets/javascripts/angular/controllers/widgets/adminController.js

https://jira.berkeley.edu/browse/SISRP-16933
This PR does not include additional user attribute based on LDAP: STUDENT-STATUS-EXPIRED status. My next PR will have that portion.
Advisors had been riding the coattails of `policy.can_view_as_for_all_uids?` but no more. With this PR, advisors can only view-as students and applicants. The level of view-as power is relevant when querying stored_users, initiating view-as session and viewing student profile. It is those controllers which now reference filters in `AdvisorAuthorization` and `ViewAsAuthorization`.

SISRP-16933, advisors can only view-as students and applicants

---

app/models/user/basic_attributes.rb
spec/models/user/basic_attributes_spec.rb
src/assets/templates/widgets/roster.html

https://jira.berkeley.edu/browse/SISRP-17554
Avoid generating invalid SQL when passed an empty array.
Also make the rosters front end do the right thing when handed an empty array of students, and fix the longstanding annoyance where "Students have not yet signed up for this class" always appears beneath the "You must be a teacher in this bCourses course" auth failure message.

SISRP-17554 Return empty User::BasicAttributes for empty enrollments

---

app/controllers/act_as_controller.rb
app/controllers/application_controller.rb
app/controllers/concerns/advisor_authorization.rb
src/assets/javascripts/angular/controllers/widgets/adminController.js

https://jira.berkeley.edu/browse/SISRP-16933
The view-as related controllers, which include *AdvisorAuthorization*, override new `render_403(error)` in *ApplicationController*. This gives Advisors an explanation for denied access to non-student UIDs.

SISRP-16933, surface 403 error message on View As widget

---

app/models/edo_oracle/user_courses/base.rb
spec/models/edo_oracle/user_courses/base_spec.rb

https://jira.berkeley.edu/browse/SISRP-17560
Follow-up to #5152 leverages that PR's `course_ids_from_row` implementation to ensure that rows are correctly sorted by course code even when `dept_name` and `catalog_id` are missing.

SISRP-17560 Correctly sort sparse EdoOracle course rows

---

app/models/berkeley/course_codes.rb
app/models/edo_oracle/user_courses/all.rb
app/models/edo_oracle/user_courses/base.rb
app/models/edo_oracle/user_courses/selected_sections.rb
spec/models/edo_oracle/user_courses/base_spec.rb

https://jira.berkeley.edu/browse/SISRP-17510
EdoOracle doesn't guarantee the database-level sorting of course codes that we got from CampusOracle, so we must run feeds through our own Ruby sorter at a higher level.

SISRP-17510 Force canonical course-code sorting on EdoOracle::UserCourses

---

app/models/canvas_csv/maintain_users.rb
app/models/canvas_csv/refresh_all_campus_data.rb
app/models/canvas_csv/site_memberships_maintainer.rb
app/models/canvas_lti/sis_adapter.rb
spec/models/canvas_csv/maintain_users_spec.rb
spec/models/canvas_csv/refresh_all_campus_data_spec.rb
spec/models/canvas_csv/site_memberships_maintainer_spec.rb
spec/models/canvas_lti/sis_adapter_spec.rb

https://jira.berkeley.edu/browse/SISRP-17294
This is mostly @redconfetti 's work. Thanks, Jason!
At present the changes have only been tested via RSpec. I haven't yet tried a script run (partly because of persistent "Faraday::SSLError certificate verify failed" issues).

SISRP-17294 Adapt bCourses maintenance scripts to new data sources

---

app/models/edo_oracle/queries.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6260
#5201 was an honest try but wrong. The real equivalent to our legacy `dept_name` is not `academicDepartment-code` but `subjectArea` (e.g. "CATALAN" not "SPANPOR").

CLC-6260 Use actual real correct EDODb column for department code

---

app/models/canvas_csv/site_memberships_maintainer.rb

https://jira.berkeley.edu/browse/SISRP-17647

SISRP-17647 User tracker for Canvas maintenance should be hash, not array

---

app/models/edo_oracle/queries.rb
app/models/edo_oracle/user_courses/base.rb

Under the wide umbrella of https://jira.berkeley.edu/browse/SISRP-17616, change course-section join to run through a display-name translation table.
Also remove unnecessary LEFT OUTER qualifiers from instructor, enrollment and meeting joins.

SISRP-17616 Use translation table when joining class and section by displayName

---

app/models/edo_oracle/queries.rb

In investigating https://jira.berkeley.edu/browse/SISRP-17531, I regrettably learned that a partial revert of #5224 is necessary. 
The aim was to allow withdrawn course descriptions to filter through for past data; but I opened the door too wide and started allowing a mix of active and withdrawn descriptions, with the withdrawn rows partially nulled out.
Also switch our translation table to the materialized MVW version.

SISRP-17531 Do not allow inactive EDODb courses to sneak through as null rows

---

app/models/calnet_ldap/client.rb
app/models/calnet_ldap/parser.rb
app/models/calnet_ldap/user_attributes.rb
app/models/user/search_users_by_name.rb
spec/models/calnet_ldap/client_spec.rb
spec/models/user/search_users_by_name_spec.rb

https://jira.berkeley.edu/browse/SISRP-17462 and its parent https://jira.berkeley.edu/browse/SISRP-16693
The following searches are equivalent: "John Doe", "Doe, John", "Mr. John Doe", "John Doe" and "Doe Jr., John". This code tokenizes the incoming string and tosses out "Jr.", etc. In this example, we'd perform two LDAP searches on `displayname`:  'John* Doe*' and 'Doe* John*'.  In my own testing, this is what gets near feature parity with _berkeley.edu/directory_.  Note: these searches are not cached – whether they should be is debatable.

SISRP-17462, LDAP search by name with option to filter by role

---

src/assets/templates/widgets/profile/information_disclosure.html

https://jira.berkeley.edu/browse/SISRP-16006
see message from Doug 5 April 2016 ~ "[advisors and delegates] should not be able to update a student's FERPA releases and/or CalNet Directory Data"

SISRP-16006: hide paragraphs with ferpa and calnet directory links

---

app/models/edo_oracle/queries.rb

https://jira.berkeley.edu/browse/SISRP-17905
In a last review of the join revised at #5238, I made a rather obvious discovery, which is that the join is not necessary. All of the selected columns and all of the constraints come from the enrollments view; joining to the section view is an expensive no-op.
Also remove a stray `puts`.

SISRP-17905 Remove unneeded section join in EdoOracle::Queries.get_enrolled_students

---

app/controllers/concerns/advisor_authorization.rb
app/controllers/search_users_controller.rb
spec/controllers/search_users_controller_spec.rb

https://jira.berkeley.edu/browse/SISRP-17963
Notes:
* Because the incoming `id` might be UID or SID, we must move the advisor-authorization check *after* the SearchUsers call. At that point, we use `user['ldap_uid']` and remove all doubt concerning id type.
* I had to improve the error message because a search on SID would return an error message containing only the corresponding UID. That would certainly confuse an Advisor. We now have both in the message.

SISRP-17963, advisor auth check in view-as must know diff between UID and SID

---

app/controllers/campus_solutions/slr_deeplink_controller.rb
app/models/campus_solutions/slr_deeplink.rb
config/routes.rb
config/settings.yml
fixtures/xml/campus_solutions/slr_deeplink.xml
spec/controllers/campus_solutions/slr_deeplink_controller_spec.rb
spec/models/campus_solutions/slr_deeplink_spec.rb

https://jira.berkeley.edu/browse/SISRP-17759
This PR adds ruby infrastructure for fetching statement of legal residency deeplink ~ detail jira at https://jira.berkeley.edu/browse/SISRP-16994

SISRP-17759-Ruby ~ backend support for SLR deeplink fetch

---

app/controllers/campus_solutions/slr_deeplink_controller.rb
app/models/campus_solutions/slr_deeplink.rb
config/settings.yml
spec/controllers/campus_solutions/slr_deeplink_controller_spec.rb
spec/models/campus_solutions/slr_deeplink_spec.rb

https://jira.berkeley.edu/browse/SISRP-17759
This fixes internal ruby class names, from SLRDeeplink to SlrDeeplink

SISRP-17759 - 5.3 - My Academics (Student) - Status, Blocks and Holds

---

app/models/edo_oracle/queries.rb

https://jira.berkeley.edu/browse/SISRP-17803
Thanks to CalCentral Bugfinder Squad, we now know that a database row with instructor name and blank instructor ID should not be interpreted as "valid instructor assignment with missing ID," but as "missing instructor assignment with erroneous name."

SISRP-17803 Filter out blank-ID instructor assignments from EDODb queries

---

spec/lib/proxies/base_proxy_spec.rb

The Bamboo QA build just failed on `base_proxy_spec` because http://www.url.com was down.  The spec has nothing to do with actual HTTP call so we stub it out.

NOJIRA, base_proxy_spec no longer relies on real HTTP call

---

app/controllers/search_users_controller.rb
app/models/user/stored_users.rb
spec/models/user/stored_users_spec.rb
src/assets/javascripts/angular/controllers/pages/userOverviewController.js
src/assets/javascripts/angular/controllers/widgets/adminController.js
src/assets/javascripts/angular/controllers/widgets/userSearchController.js
src/assets/javascripts/angular/services/adminService.js
src/assets/templates/widgets/toolbox/user_search.html
src/assets/templates/widgets/toolbox/user_search_results.html

https://jira.berkeley.edu/browse/SISRP-16088
All three tabs (search, saved and recent) will shuffle user list and available links based on latest stored_users in db. To avoid complexity in the js I added a 'saved' property to server-side user searches. E.g., each user in search results has the flag.
A little cleanup:
* symbolize keys in stored_users 
* fewer js files offending the camelcase rule

SISRP-16088, all tabs are wired to save, delete and view-as user

---

src/assets/javascripts/angular/services/adminService.js

https://jira.berkeley.edu/browse/SISRP-18350
I missed an instance of `ldap_uid` v. `ldapUid` concern. View-as links from new student-lookup card need to use `getLdapUid(user)`.

SISRP-18350, view-as from Advisor dashboard needs logic of: ldap_uid OR ldapUid

---

app/models/oec/report_diff_task.rb
app/models/oec/task.rb
spec/models/oec/sis_import_task_spec.rb

https://jira.ets.berkeley.edu/jira/browse/CLC-6269
In order to do its job, ReportDiffTask needs the timestamp of the most recent SIS import. If it can't get that timestamp, it should say so and error out gracefully.

CLC-6269 OEC: Tune error handling in ReportDiffTask

---

app/models/hub_edos/registrations.rb
app/models/hub_edos/response_handler.rb
fixtures/json/hub_registrations.json
spec/models/hub_edos/registrations_spec.rb
spec/models/hub_edos/response_handler_spec.rb

https://jira.berkeley.edu/browse/SISRP-18057
This will be needed to check CS for academic status in non-"current" terms, thus allowing us to (for example) know whether someone should be treated as a Law student in the Class Enrollment card for a future term.
(The PR also scrapes GoLive 4 API formats into the dustbin of history.)

SISRP-18057 Add HubEdos::Registrations proxy

---

app/controllers/campus_solutions/higher_one_url_controller.rb
app/models/campus_solutions/higher_one_url.rb
app/models/campus_solutions/my_higher_one_url.rb
config/routes.rb
spec/controllers/campus_solutions/higher_one_url_controller_spec.rb
src/assets/templates/widgets/billing_summary.html

https://jira.berkeley.edu/browse/SISRP-17831
I left the "old" methods of polling for the HigherOne URL we use on the SIR card there.  I believe the plan was to QA both methods, and if this way was preferable, then we'd replace the functionality on the SIR card with this method?  cc @pfarestveit 
Let me know if I can make this better - it feels pretty un-DRY, but since these methods are so authentication-state-specific, I wasn't sure if I could make some of these shared variables between the two methods more global.
I also wasn't able to test the delegate part of this yet, I've created [SISRP-18446] (https://jira.berkeley.edu/browse/SISRP-18446) to address this.
Thanks!

SISRP-17831 - Add SSO to HigherOne for Students and Delegates for Billing Summary

---

src/assets/javascripts/angular/controllers/widgets/billingController.js

https://jira.berkeley.edu/browse/SISRP-18358
AngularJS clears filters if the search term resolves to `undefined`.  The previous filter wasn't working, because I had set the search property to `itemTermId: ''`  This worked for most items, but when an item was sent over with `itemTermId: null`, it would filter it out.  I've now correctly set the `searchTermId.itemTermId` to default to undefined, to ensure we're not incorrectly filtering out any items.

SISRP-18358 - CC-SIS-DEV: Deposit Payment not displaying in All Transactions

---

app/models/berkeley/user_roles.rb

https://jira.berkeley.edu/browse/SISRP-18518
Code comment for future generations. Possible CS affiliation status codes:
* 'ACT' (active)
* 'INA' (inactive)
* 'ERR' (bad data which CalCentral should ignore)

SISRP-18518, comment lists the possible CS affiliation status codes

---

app/controllers/advising_student_controller.rb
src/assets/templates/widgets/toolbox/user_preview.html

https://jira.berkeley.edu/browse/SISRP-17782
https://jira.berkeley.edu/browse/SISRP-17783
Two new links on student overview card:
* 'GTE Forms' if feature flag cs_advising_gte_forms is true (GoLive 5.6)
* 'Academic Planner' by student_uid w/ underlying feature flag hook
Template gets a bit of cleanup, too.

SISRP-17782, Advising student overview: GTE forms and Academic Planner links

---

app/controllers/stored_users_controller.rb
config/routes.rb
spec/controllers/stored_users_controller_spec.rb
spec/features/act_as_user_spec.rb
src/assets/javascripts/angular/controllers/pages/userOverviewController.js
src/assets/javascripts/angular/controllers/widgets/userSearchController.js
src/assets/javascripts/angular/factories/adminFactory.js
src/assets/templates/widgets/toolbox/user_search_results.html

https://jira.berkeley.edu/browse/SISRP-18523
Notes:
* get and post stored_users grouped in routes under `/api/view_as/`
* in user-search-results we `storeAsRecent()` on-click to see user overview
* spec tidying

SISRP-18523, storeUserAsRecent on-click from search results, before view-as

---

app/controllers/campus_rosters_controller.rb
app/controllers/canvas_rosters_controller.rb
app/models/canvas_lti/sis_adapter.rb
app/models/edo_oracle/queries.rb
app/models/rosters/campus.rb
app/models/rosters/common.rb
public/dummy/json/campus_rosters.json
spec/controllers/campus_rosters_controller_spec.rb
spec/controllers/canvas_rosters_controller_spec.rb
spec/models/canvas_lti/sis_adapter_spec.rb
spec/models/edo_oracle/queries_spec.rb
spec/models/rosters/campus_spec.rb
spec/models/rosters/common_spec.rb

https://jira.berkeley.edu/browse/SISRP-18651
- Add grade option and units to enrollment query and roster feed, making sure the graded component is the section used;
- Stop filtering out email addresses;
- Clear up some existing confusion in the enrollment query between legacy 'pnp_flag' and new 'grading_basis.'

SISRP-18651 Add grade option, units, email address to campus roster feed

---

app/models/berkeley/term_codes.rb
app/models/campus_solutions/billing.rb
app/models/campus_solutions/enrollment_term.rb
app/models/my_academics/college_and_level.rb
app/models/my_academics/gpa_units.rb
app/models/my_academics/transition_term.rb
app/models/my_badges/student_info.rb
config/settings.yml
spec/models/my_academics/college_and_level_spec.rb
src/assets/javascripts/angular/controllers/pages/academicsController.js

This preserves the current client-server contracts and front-end logic, although both are in desperate need of refactoring.
Next feeds which need to learn about life-after-BearFacts: GPA and StudentInfo (AKA RegStatus).

SISRP-17895 Adapt CollegeAndLevel to end of Bear Facts data

---

app/controllers/campus_solutions/fpp_enrollment_controller.rb
app/models/campus_solutions/fpp_enrollment.rb
config/routes.rb
fixtures/xml/campus_solutions/fpp_enrollment.xml

https://jira.berkeley.edu/browse/SISRP-18730
Question regarding `CampusSolutions::GlobalCachedProxy`:
I can't think of a use case in which an invalid ID-less call would be made on this endpoint, especially since we are disallowing delegate and act-as access to this endpoint.  Can someone enlighten me as to the use of this passthrough in this specific case?

SISRP-18730 - Create Back-End for Get FPP Enrollment API using Mock Fixture

---

app/models/user/aggregated_attributes.rb

https://jira.berkeley.edu/browse/SISRP-16402
This will be our third way of identifying Law students, and it's the one of least utility, since it isn't explicitly tied to a particular academic term. The other two (term-specific) sources are already in use in production:
* MyBadges::StudentInfo (derived from MyAcademics::CollegeAndLevel)
* CampusSolutions::EnrollmentTerms'

SISRP-16402 Expose CS "Law" affiliation (of limited use at present)

---

src/assets/templates/academics_status_holds_blocks.html

https://jira.berkeley.edu/browse/SISRP-17759
This PR removes the hide/show toggle for California Residency, showing the residency detail by default.

5.4 - My Academics (Student) - Status, Blocks and Holds

---

src/assets/javascripts/angular/controllers/widgets/userSearchController.js
src/assets/templates/widgets/toolbox/user_search_results.html

https://jira.berkeley.edu/browse/SISRP-18663
PR includes an accessibility fix for the "displaying {x} users" message, depending which tab is viewed.

SISRP-18663 - Student Lookup,SID as Search Criteria, result missing name link

---

src/assets/javascripts/angular/configuration/routeConfiguration.js
src/assets/javascripts/angular/controllers/pages/academicsController.js
src/assets/javascripts/angular/controllers/widgets/classInfoEnrollmentController.js
src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
src/assets/javascripts/angular/directives/sortableColumnDirective.js
src/assets/stylesheets/_academics.scss
src/assets/stylesheets/_useful.scss
src/assets/templates/academics_classinfo.html
src/assets/templates/directives/academics_class_info_enrollment.html
src/assets/templates/directives/sortable_column.html

https://jira.berkeley.edu/browse/SISRP-18516
Class Info pages for instructors get a new "Enrollment" tab between "Class Info" and "Roster," if it's a Campus Solutions term and the feature flag is turned on. Per requirements, each tab position gets its own URL, and tabs are changed from buttons to links.
Enrollment and waitlist summaries surface the fields we can currently get without database overhead (name, SID, email, units and grade option). More fields may come later. Tables are sortable and reverse-sortable by column, and like rosters can be filtered by section.

SISRP-18516 Class Info enrollment tab front end

---

Gemfile
Gemfile.lock

https://jira.berkeley.edu/browse/SISRP-18781

SISRP-18781 Enable SSL TLSv1.2 protocol for textbooks API, etc.

---

app/controllers/search_users_controller.rb
app/controllers/stored_users_controller.rb
spec/controllers/search_users_controller_spec.rb
spec/controllers/stored_users_controller_spec.rb
spec/features/act_as_user_spec.rb
src/assets/javascripts/angular/controllers/widgets/userSearchController.js
src/assets/templates/widgets/toolbox/uid_lookup.html
src/assets/templates/widgets/toolbox/user_search_results.html
src/assets/templates/widgets/toolbox/view_as.html

https://jira.berkeley.edu/browse/SISRP-18763
The view-as templates have had a lot snake_case (e.g., ldap_uid). The work on Advisor student lookup has, at times, followed the same snake_case pattern because of shared code, causing bugs like SISRP-18763. It's time to refactor away the bad pattern.

SISRP-18763, refactor out snake_case in search_users, uid_lookup and view_as templates

---

app/models/calnet_ldap/client.rb
spec/models/calnet_ldap/client_spec.rb
spec/models/user/search_users_by_name_spec.rb

https://jira.berkeley.edu/browse/SISRP-18739
Based on feedback from @raydavis and @paulkerschen in PR #5353 
I'm now using `Net::LDAP::Filter.intersect` to construct chain all filters before running the LDAP search. If the input is a single token then the constructed filter is: `first_name=Doe* OR last_name=Doe*`.

SISRP-18739, if search input is 'Doe' then search LDAP with *Doe*

---

app/models/edo_oracle/queries.rb
app/models/edo_oracle/user_courses/base.rb
spec/models/edo_oracle/user_courses/base_spec.rb

https://jira.berkeley.edu/browse/SISRP-18733
Some gymnastics that I wish weren't necessary.
For complex reasons having to do with EDO DB implementation, checking for an 'ACTIVE' status code under ON rather than WHERE will screen out a small class of valid courses that exist in the cross-listing table as 'ACTIVE', but in the course table as 'DEPRECATED'.
However, for complex reasons having to do with EDO DB implementation, rewriting the query in this way will result in duplicate results for a small class of courses that link to both active, correctly formatted department names (e.g., 'PHYS ED') and deprecated, incorrectly formatted department names ('PHYSED') through the course/class translation table.
However, for complex reasons having to do with EDO DB implementation, we can screen out …

SISRP-18733 More workarounds for spotty EDO DB data
