ets-berkeley-edu/junction

app/controllers/application_controller.rb, spec/controllers/bootstrap_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6061
We must redirect because you are now viewing-as a user that might not have access to /toolbox page.
=> CLC-6061, redirect to dashboard after view-as + reauth

app/models/calnet_crosswalk/proxy.rb, app/models/hub_edos/my_student.rb, app/models/hub_edos/proxy.rb
https://jira.berkeley.edu/browse/SISRP-11950
=> SISRP-11950 Improve logging of HubEdos / Crosswalk errors

app/models/hub_edos/proxy.rb, app/models/hub_edos/student.rb
Eagle-eyed @paulkerschen spotted this nasty error path in my previous https://github.com/ets-berkeley-edu/calcentral/pull/4590
=> SISRP-11950 Fix exception when lookup of CS ID fails

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-12042
=> SISRP-12042 - Undergraduate applicants generate JS errors in CalCentral

src/assets/javascripts/angular/controllers/widgets/sir/sirItemController.js
https://jira.berkeley.edu/browse/SISRP-12043
=> SISRP-12043 - Undergrad applicants have a SIR card with only a 'Yes' option - this generates a JS error

src/assets/javascripts/angular/controllers/widgets/profile/languagesSectionController.js, src/assets/templates/widgets/profile/languages_section.html
https://jira.berkeley.edu/browse/SISRP-10752
=> SISRP-10752 - Profile - CS language data - Only 'native' surfaces in CalCentral

src/assets/javascripts/angular/services/profileMenuService.js
https://jira.berkeley.edu/browse/SISRP-12049
=> SISRP-12049 - Hide Emergency Contacts data for GL3

app/models/my_tasks/sis_tasks.rb, src/assets/javascripts/angular/controllers/widgets/tasksController.js, src/assets/javascripts/angular/factories/tasksFactory.js, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-12036
=> SISRP-12036 - Onboarding - completed checklist items are not consistent with completed tasks UI

src/assets/stylesheets/_activities.scss, src/assets/templates/widgets/activity_list.html
Submitted with design consideration and approval from Rachel Hollowgrass.
https://jira.ets.berkeley.edu/jira/browse/CLC-5752
=> CLC-5752 - Recent Activity: item title can overlap the toggle

spec/ui_selenium/my_academics_data_advising_appts_spec.rb, spec/ui_selenium/my_academics_data_course_captures_spec.rb, spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/my_academics_data_final_exams_spec.rb, spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/my_academics_data_status_blocks_spec.rb, spec/ui_selenium/my_academics_data_teaching_spec.rb, spec/ui_selenium/my_academics_data_telebears_spec.rb, spec/ui_selenium/my_dashboard_canvas_course_sites_spec.rb, spec/ui_selenium/my_dashboard_data_classes_spec.rb, spec/ui_selenium/my_finances_data_acct_summary_spec.rb, spec/ui_selenium/my_finances_data_cal1card_spec.rb, spec/ui_selenium/my_finances_data_finaid_spec.rb, spec/ui_selenium/my_finances_data_transaction_detail_spec.rb, spec/ui_selenium/pages/cal_net_auth_page.rb, spec/ui_selenium/pages/canvas_page.rb, spec/ui_selenium/pages/my_dashboard_notifications_card.rb, spec/ui_selenium/user_authorizations_spec.rb, spec/ui_selenium/util/web_driver_utils.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6062
Misc test fixes.
=> CLC-6062: fix broken Selenium tests and speed up QA builds

src/assets/javascripts/angular/controllers/widgets/profile/title4Controller.js, src/assets/templates/widgets/profile/title4.html
https://jira.berkeley.edu/browse/SISRP-12021
=> SISRP-12021 - Implement changes for Title 4 update

app/models/hub_edos/my_work_experience.rb
QA BRANCH ONLY. There is no corresponding PR on 'master' branch. 
See analysis in https://jira.ets.berkeley.edu/jira/browse/CLC-6078
Tests passed on localhost... Let's see what Travis thinks.
=> CLC-6078, qa branch only: WorkExperience is not GL3 so is_feature_enabled=false

spec/ui_selenium/my_profile_contact_info_spec.rb, spec/ui_selenium/pages/api_my_fin_aid_page.rb, spec/ui_selenium/pages/my_dashboard_tasks_card.rb, spec/ui_selenium/pages/my_finances_landing_page.rb, spec/ui_selenium/pages/my_profile_contact_info_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6062
=> CLC-6062: a few more broken Selenium tests fixed

spec/policies/authentication_state_policy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6053
=> CLC-6053, spec for has_toolbox_tab in AuthenticationStatePolicy

src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-12116
=> SISRP-12116 - Can carriage returns be included on Task text?

app/models/my_activities/campus_solutions_messages.rb
https://jira.berkeley.edu/browse/SISRP-10909
=> SISRP-10909 - In Calcentral no Notifications are generated

app/models/my_activities/campus_solutions_messages.rb
https://jira.berkeley.edu/browse/SISRP-10909
*Note* - we need to confirm that #4612 works on calcentral-dev first.
=> SISRP-10909 QA - In Calcentral no Notifications are generated

app/models/google_apps/client.rb, app/models/my_badges/google_mail.rb, app/models/my_badges/merged.rb, app/models/my_tasks/google_tasks.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6079
Remove debug logging with possible security risk.
=> CLC-6079, security concern in debug logging

src/assets/templates/dashboard_task_noitems.html, src/assets/templates/widgets/up_next.html
https://jira.berkeley.edu/browse/SISRP-11793
=> SISRP-11793 - CalCentral delay "get connected to bConnected" card display till user has email setup

app/models/oec/remote_drive.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6082
See https://github.com/ets-berkeley-edu/calcentral/commit/af2925113b08e83bf6462c4a4bb30acb72b28c49#diff-ff48e91237623e644c000ed830c6490cL17
=> CLC-6082 Update Oec::RemoteDrive to match changed DriveManager method

src/assets/templates/dashboard_task_noitems.html, src/assets/templates/widgets/up_next.html
https://jira.berkeley.edu/browse/SISRP-11793
*Note* Make sure that @pfarestveit verified this fix on calcentral-dev before merging.
=> QA - SISRP-11793 - CalCentral delay "get connected to bConnected" card display till user has email setup

app/models/oec/remote_drive.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6082
QA version of #4616.
=> [QA] CLC-6082 Update Oec::RemoteDrive to match changed DriveManager method

app/models/calnet_crosswalk/proxy.rb
https://jira.berkeley.edu/browse/SISRP-12145
This PR doesn't aim to change how CalnetCrosswalk::Proxy talks to other classes; all the public lookup methods still return nil on a 404 response. However, since 404s are expected in the normal course of business, they shouldn't be logged as errors. Two changes are made:
- Since subclasses of CalnetCrosswalk::Proxy may search by either UID or SID, the misleading hard-coded "UID" is removed from log messages and a class method substituted in.
- In the event of a 404 response, a `:notFound` key is added to the response before caching. Like the `:errored` key for other failures, this will cause public methods to return nil, but it won't trigger error logging.
=> SISRP-12145 Do not log Crosswalk ID lookup failures as errors

app/models/calnet_crosswalk/proxy.rb
https://jira.berkeley.edu/browse/SISRP-12145
QA version of #4619.
=> [QA] SISRP-12145 Do not log Crosswalk ID lookup failures as errors

src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/basic.html, src/assets/templates/widgets/profile/double_entry.html, src/assets/templates/widgets/profile/editable_soon.html
https://jira.berkeley.edu/browse/SISRP-12148
=> SISRP-12148 - UX Develop: Implement design revisions to better direct Students about changes to Bearfacts

src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/basic.html, src/assets/templates/widgets/profile/double_entry.html, src/assets/templates/widgets/profile/editable_soon.html
https://jira.berkeley.edu/browse/SISRP-12148
*Note* Only merge this as soon as we have an ok from @pfarestveit on #4621
=> SISRP-12148 QA - UX Develop: Implement design revisions to better direct Students about changes to Bearfacts

src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-12147
*Note* GL3 change
=> SISRP-12147 - SIR card is beneath Tasks and Notifications in mobile view - expected?

src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-12147
=> QA - SISRP-12147 - SIR card is beneath Tasks and Notifications in mobile view - expected?

app/models/hub_edos/user_attributes.rb, app/models/user/api.rb, src/assets/templates/widgets/activity.html
https://jira.berkeley.edu/browse/SISRP-12200
=> SISRP-12200 - Previous Communications link not showing for applicants

src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-12147
=> SISRP-12147 - Follow up - SIR card is beneath Tasks and Notifications in mobile view - expected?

src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-12156
=> SISRP-12156 - Can links within the text of the task (Checklist Item verbiage) open in a new window?

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-12042
=> QA SISRP-12042 - Undergraduate applicants generate JS errors in CalCentral

app/models/hub_edos/user_attributes.rb, app/models/user/api.rb, src/assets/templates/widgets/activity.html
https://jira.berkeley.edu/browse/SISRP-12200
=> QA SISRP-12200 - Previous Communications link not showing for applicants

app/models/calnet_crosswalk/proxy.rb, app/models/google_apps/client.rb, app/models/hub_edos/user_attributes.rb, app/models/my_badges/google_mail.rb, app/models/my_badges/merged.rb, app/models/my_tasks/google_tasks.rb, app/models/oec/remote_drive.rb, app/models/user/api.rb, src/assets/stylesheets/_profile_page.scss, src/assets/templates/dashboard.html, src/assets/templates/dashboard_task_noitems.html, src/assets/templates/widgets/activity_archive.html, src/assets/templates/widgets/profile/basic.html, src/assets/templates/widgets/profile/double_entry.html, src/assets/templates/widgets/profile/editable_soon.html, src/assets/templates/widgets/up_next.html
Fixed 1 Merge conflict in `activity_archive.html`
=> Merge master into sis-master

app/models/hub_edos/my_student.rb
https://jira.berkeley.edu/browse/SISRP-12219
=> SISRP-12219 - Show 'your information is not available' when we don't get any iHub data back at all.

app/models/hub_edos/my_student.rb
https://jira.berkeley.edu/browse/SISRP-12219
=> QA - SISRP-12219 - Show 'your information is not available' when we don't get any iHub data back at all.

app/models/my_tasks/sis_tasks.rb, src/assets/templates/dashboard_task_loop.html, src/assets/templates/dashboard_task_noitems.html
https://jira.berkeley.edu/browse/SISRP-12050
=> SISRP-12050 - Show actual completed date in CalCentral

app/models/google_apps/client.rb, app/models/google_apps/drive_list.rb, app/models/google_apps/proxy.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6095
QA squash of #4638 and #4641.
=> [QA] CLC-6095 Lock Google Drive client to v2 API

app/models/google_apps/clear_task_list.rb, app/models/google_apps/create_task_list.rb, app/models/google_apps/delete_task.rb, app/models/google_apps/delete_task_list.rb, app/models/google_apps/events_batch_delete.rb, app/models/google_apps/events_batch_get.rb, app/models/google_apps/events_batch_insert.rb, app/models/google_apps/events_batch_update.rb, app/models/google_apps/events_delete.rb, app/models/google_apps/events_get.rb, app/models/google_apps/events_insert.rb, app/models/google_apps/events_list.rb, app/models/google_apps/events_recent_items.rb, app/models/google_apps/events_update.rb, app/models/google_apps/insert_task.rb, app/models/google_apps/tasks_list.rb, app/models/google_apps/update_task.rb, app/models/google_apps/userinfo.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6101
Bamboo https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT230-2 is happy on the Google front.
=> CLC-6101 Explicitly version all Google API calls

app/models/google_apps/sheets_manager.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6087
=> CLC-6087 Log Google worksheet update errors more thoroughly

spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/my_dashboard_canvas_course_sites_spec.rb, spec/ui_selenium/my_dashboard_google_live_updates_spec.rb, spec/ui_selenium/my_dashboard_google_tasks_spec.rb, spec/ui_selenium/my_dashboard_google_up_next_spec.rb, spec/ui_selenium/my_profile_basic_info_spec.rb, spec/ui_selenium/pages/canvas_page.rb, spec/ui_selenium/pages/my_dashboard_tasks_card.rb, spec/ui_selenium/user_authorizations_spec.rb, spec/ui_selenium/util/web_driver_utils.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6084
A second PR, mainly aimed at refactoring the WebDriver tests for Tasks so that they can interact with any task in any time bucket from any source and so that the tests themselves are more readable.  The refactoring is important for testing checklist items in future tests.  Also a couple minor fixes.
=> CLC-6084: additional Selenium test fixes

app/models/campus_solutions/my_delegate_access.rb, app/models/campus_solutions/my_financial_aid_funding_sources.rb, app/models/campus_solutions/my_financial_aid_funding_sources_term.rb, app/models/my_academics/filtered_for_delegate.rb, spec/controllers/my_academics_controller_spec.rb, spec/models/my_academics/filtered_for_delegate_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6106
=> CLC-6106 Feature-flag GL4-specific merged models against cache warming

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-12410
=> SISRP-12410 - Regular staff JS error: TypeError: Cannot read property 'errored' of undefined

src/assets/templates/navigation.html
https://jira.berkeley.edu/browse/SISRP-12400
=> SISRP-12400 - 'My Toolbox' doesn't stay highlighted when you click on it.

src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js, src/assets/templates/widgets/finaid_awards_loans.html, src/assets/templates/widgets/finaid_awards_section.html, src/assets/templates/widgets/finaid_communications_tasks.html, src/assets/templates/widgets/finaid_profile.html
https://jira.berkeley.edu/browse/SISRP-7714
=> SISRP-7714 - Update / add directive to expire cache in CalCentral for finaid / profile

src/assets/templates/widgets/profile/title4.html
https://jira.berkeley.edu/browse/SISRP-12357
=> SISRP-12357 - Update Title4 text for people that have not previously authorized

src/assets/javascripts/angular/controllers/widgets/finaid/FinaidProfileController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidCoaController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/javascripts/angular/controllers/widgets/statusController.js, src/assets/templates/widgets/finaid_awards.html, src/assets/templates/widgets/finaid_awards_term_widget.html, src/assets/templates/widgets/finaid_coa.html, src/assets/templates/widgets/finaid_communications.html, src/assets/templates/widgets/finaid_errored.html, src/assets/templates/widgets/finaid_profile.html, src/assets/templates/widgets/finaid_summary.html, src/assets/templates/widgets/finaid_summary_footer.html, src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-12462
=> SISRP-12462 - Provide error messages when finaid data is unavailable

src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6114
=> CLC-6114 - "Not registered" message missing from Academics page

src/assets/templates/widgets/gear_popover.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6111
=> CLC-6111 - Combined Profile/Status/Settings button is accessibility concern

src/assets/templates/widgets/activity_list_link.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5895
=> CLC-5895 - Update activity_list_link with ng-bind

spec/ui_selenium/pages/cal_central_pages.rb, spec/ui_selenium/pages/my_profile_bconnected_card.rb, spec/ui_selenium/pages/my_toolbox_page.rb, spec/ui_selenium/user_authentication_spec.rb, spec/ui_selenium/user_authorizations_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6109
What should be the final set of changes...
=> CLC-6109 - QA: fix Selenium tests post mega-merge for GL4

config/initializers/rails_admin.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6121
=> CLC-6121 Add OEC course-code mappings to ccadmin

app/models/oec/report_diff_task.rb, spec/models/oec/report_diff_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6122
=> CLC-6122 OEC: Do not treat absent confirmation sheets as errors

app/models/my_activities/campus_solutions_messages.rb
https://jira.berkeley.edu/browse/SISRP-12544
=> SISRP-12544 - Communications Not Surfacing CC-DEV yet Surfacing in CC-SIS-DEV

app/models/hub_edos/user_attributes.rb, spec/models/hub_edos/user_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-8927
Also adds test coverage per https://jira.ets.berkeley.edu/jira/browse/CLC-6089.
=> SISRP-8927 CLC-6089 Correctly populate student, ex-student, applicant and instructor roles

src/assets/javascripts/angular/services/profileService.js, src/assets/templates/widgets/profile/contact_address.html, src/assets/templates/widgets/profile/emergency_contact.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6127
=> CLC-6127 - CalCentral Allows HTML in Profile Data

src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js
https://jira.berkeley.edu/browse/SISRP-12597
=> SISRP-12597 - Eternal spinner on main dashboard finaid summary widget

src/assets/stylesheets/_accessibility.scss, src/assets/templates/widgets/profile/basic_preferred_name.html, src/assets/templates/widgets/profile/contact_address.html, src/assets/templates/widgets/profile/contact_email.html, src/assets/templates/widgets/profile/contact_phone.html
https://jira.berkeley.edu/browse/SISRP-11948
=> SISRP-11948 - Accessibility of Profile feature: Buttons to 'Add' and 'Edit' do not have descriptive titles

spec/ui_selenium/pages/my_academics_profile_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6131
=> CLC-6131 - fix bad element locator in Selenium test

src/assets/stylesheets/_header.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6110
=> CLC-6110 - Header profile photo is too itsy bitsy teensy weensy

spec/models/campus_solutions/checklist_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6116
Happy Bamboo https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT236-2
=> CLC-6116 Fix Bamboo failure in CampusSolutions::ChecklistSpec

src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js, src/assets/templates/widgets/finaid_communications_tasks.html
https://jira.berkeley.edu/browse/SISRP-12069
=> SISRP-12069 - Add show / hide completed financial aid tasks functionality

app/models/campus_solutions/address_label.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6134
=> CLC-6134 Log unexpected Campus Solutions address labels and move on

src/assets/templates/widgets/toolbox/view_as.html
https://jira.berkeley.edu/browse/SISRP-11928
=> SISRP-11928 - Fix spinner on the View as widget in the toolbox

app/models/service_alerts/alert.rb, config/initializers/rails_admin.rb, db/developer-seed-data.sql, db/migrate/20151222002724_create_service_alerts.rb, db/schema.rb, spec/models/service_alerts/alert_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-5589
Note that the `preview` method plus rails_admin configuration should allow alerts to be created, previewed and published right from within ccadmin.
=> CLC-5589 New ActiveRecord model for service alerts

src/assets/javascripts/angular/controllers/widgets/myClassesController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6137
=> CLC-6137 Bad property name in MyClasses front-end updates

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, src/assets/javascripts/angular/controllers/pages/profileController.js, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/profile.html
https://jira.berkeley.edu/browse/SISRP-12748
=> SISRP-12748 - Make profile menu service dynamic

config/initializers/session_store.rb, config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6126
=> CLC-6126 Reduce session lifespan

src/assets/javascripts/angular/controllers/widgets/academicsGpaController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6140
@christianvuerings or @nicolaasmatthijs , mind taking a look?
Many thanks to @marwahaha for pointing out this issue at https://github.com/ets-berkeley-edu/calcentral/pull/4689.
=> CLC-6140 Might as well include A and A+ grades in GPA calculations

app/models/bearfacts/profile.rb, lib/proxies/mock_http_interaction.rb, spec/controllers/my_academics_controller_spec.rb, spec/lib/proxies/mockable_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6141
=> CLC-6141 Disambiguate mock proxy URIs which are subpaths of other proxies

src/assets/stylesheets/_header.scss, src/assets/templates/widgets/gear_popover.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6130
I *think* this is correct.  Also, would it make sense to add a "if .errored" to loadFinances() in statusController.js?
=> CLC-6130 - Amount Due Number After Name in Header Looks Odd

spec/ui_selenium/my_dashboard_canvas_course_sites_spec.rb, spec/ui_selenium/pages/api_my_fin_aid_page.rb, spec/ui_selenium/pages/my_dashboard_notifications_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6145
Plus a little cleanup.
=> CLC-6145 - QA: fix expected date formats

spec/ui_selenium/pages/my_dashboard_notifications_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6145
Need to return the expected date string.
=> CLC-6145 - QA: fix broken test fix

spec/ui_selenium/pages/my_profile_basic_info_card.rb, spec/ui_selenium/pages/my_profile_contact_info_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6145
Gnarly XPath = brittle element locator
=> CLC-6145 - QA: update profile info element locators

src/assets/templates/widgets/profile/contact_email.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6146
Do not merge this qa PR until the corresponding master PR #4697 is merged / verified.
=> CLC-6146, Profile - 'Add' button for email is showing accessibility text

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6112
Follow-up to fix #4662.
=> CLC-6112 Catch null-or-undefined registration code in status check

src/assets/stylesheets/_header.scss, src/assets/templates/widgets/gear_popover.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6130
=> QA CLC-6130 - Amount Due Number After Name in Header Looks Odd

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6112
QA version of #4703.
=> [QA] CLC-6112 Catch null-or-undefined registration code in status check

src/assets/javascripts/angular/controllers/widgets/statusController.js, src/assets/templates/widgets/status_popover.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6151
=> CLC-6151 Show registration alerts only to active students

src/assets/javascripts/angular/controllers/widgets/statusController.js, src/assets/templates/widgets/status_popover.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6151
QA version of #4707.
=> [QA] CLC-6151 Show registration alerts only to active students

app/models/hub_edos/student.rb, fixtures/json/student_api_via_hub.json, fixtures/json/student_contacts.json, spec/models/hub_edos/contacts_spec.rb, spec/models/hub_edos/student_spec.rb
https://jira.berkeley.edu/browse/SISRP-12376
=> SISRP-12376 - Remove the 'Do Not Display' code from CalCentral

app/models/calendar/queries.rb, app/models/campus_oracle/connection.rb, spec/models/calendar/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6153
QA version of #4709.
=> [QA] CLC-6153 Handle nil term values in Oracle queries

src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-12558
[Git commit 7cf549c](https://github.com/christianvuerings/calcentral/commit/7cf549c6c5b425355597bbdc541adf680da9f517) fixed https://jira.berkeley.edu/browse/SISRP-12156 via data-cc-compile-directive. In this PR, I revert commit 7cf549c.
I'll reopen SISRP-12156 and, meanwhile, revert this change on master and qa.
=> SISRP-12558, revert change on data-cc-compile-directive = task.notes (SISRP-12156)

src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-12558
This is QA follow up to PR #4711 which I verified in cc-sis-qa.
=> SISRP-12558, QA PR: revert change on data-cc-compile-directive = task.notes (SISRP-12156)

script/sis/parse_yaml.sh, script/sis/verify_sis_api_endpoints.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6157
[CLC-6123](https://jira.ets.berkeley.edu/jira/browse/CLC-6123) demonstrates a need for automated verification of SIS APIs. This script will read configs from specified YAML file.
See curl conventions described in [ChrisT exit notes](https://docs.google.com/document/d/1JspjhNQ-rHL1PsnpwL3n3TUprxk55Tej2t20XLExRzI/edit#)
=> CLC-6157, script to verify required SIS endpoints (e.g., used by Ops)

.gitignore, script/sis/sis_script_utils.sh, script/sis/verify_sis_api_endpoints.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6155
In addition to adding new DA endpoints to the script (e.g., "/UC_CC_DELEGATED_ACCESS_URL.v1/get") I also:
* validate cmd line input
* write response body to log file
* grep response for known errors
Change to `.gitignore` allows us to write log files to a subdir of `/log/` 
cc: @dkawase
=> CLC-6155, script to verify API endpoints now includes Delegated Access

src/assets/templates/academics_student_profile.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6158
=> CLC-6158 Show transition-term profile header to active students only

spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/pages/my_academics_profile_card.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6158
=> CLC-6158 - QA test update for ex-student view in term transition

script/sis/sis_script_utils.sh, script/sis/verify_sis_api_endpoints.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6155
With the release coming up on Monday I want to have clean output from this script. Ops (e.g., @dkawase) is the customer here.
=> CLC-6155, better output from sis_api_test script

src/assets/javascripts/angular/controllers/widgets/profile/basicPreferredNameController.js, src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/basic_preferred_name_editor.html
https://jira.berkeley.edu/browse/SISRP-12175
=> SISRP-12175 - UX Develop: Preferred Name – Restrict character set for input in Profile

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsTermController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidCoaController.js, src/assets/templates/widgets/finaid_awards_term_widget.html, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-12479
=> SISRP-12479 - Use '.errored' for finaid angular controllers

lib/server_runtime.rb, src/assets/templates/footer.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6161
Clean up footer. Changes in `server_runtime.rb` are strictly code style.
=> CLC-6161, minor cleanup in footer; remove /tools ref

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-13172
=> SISRP-13172 - Negative service indicators should only show for applicants & students

app/models/campus_solutions/proxy.rb
They're quite dull.
@christianvuerings , wouldn't you agree?
=> NOJIRA Stop logging CS request options even at DEBUG level

app/models/hub_edos/proxy.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6085
Hub outages sometimes result in unexpected 404 responses with unexpected payloads that defeat our JSON parser. As of #4590 we're logging the payload, so we might as well return our predetermined `empty_feed` rather than letting the JSON parser fail and return the same result.
Everything else is formatting fixes in the same class.
=> CLC-6085 Do not attempt to parse bizarro Hub 404s as JSON

src/assets/javascripts/angular/services/profileMenuService.js
https://jira.berkeley.edu/browse/SISRP-13165
=> SISRP-13165 - Only show Link to FERPA Release Classic Interface to students

config/settings.yml
https://jira.berkeley.edu/browse/SISRP-13174
*Note*: Very low priority PR
=> SISRP-13174 - Better standard settings.yml settings for hub_edos_proxy & campus_solutions_proxy

src/assets/templates/uid_error.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6163
=> CLC-6163 Remove trailing double quote in uid_error template

Gemfile, Gemfile.lock, lib/jms/jms_connection.rb, lib/services/jms_worker.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6142
After this lands on CC-SIS-QA and we arrange a test messaging run with Tamer, we can remove the logger.debug statement.
=> CLC-6142 Upgrade ActiveMQ

src/assets/javascripts/angular/services/utilService.js
https://jira.berkeley.edu/browse/SISRP-13362
=> SISRP-13362 - CalCentral-QA ToolBox View As UID/SID Field

config/settings.yml, config/settings/development.yml, config/settings/test.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-5648
=> CLC-5648 Remove obsolete service alerts proxy configs

Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-6100
=> CLC-6100 Bump Gemfile.lock to latest revision of our omniauth-cas fork

app/models/my_tasks/sis_tasks.rb
https://jira.berkeley.edu/browse/SISRP-13376
=> SISRP-13376 - CalCentral-QA Checklist Items not Surfacing

public/maintenance/index_emergency.html, public/maintenance/index_maintenance.html, src/base.html
https://jira.berkeley.edu/browse/SISRP-13418
=> SISRP-13418 - CalCentral - Remove minimal-ui from our viewport meta tag

src/assets/javascripts/angular/services/errorService.js, src/assets/stylesheets/_act_as.scss, src/assets/stylesheets/_canvas_create_course_site.scss, src/assets/stylesheets/_footer.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/acting_as.html, src/assets/templates/canvas_embedded/create_course_site.html, src/assets/templates/footer.html, src/index-main.html
https://jira.berkeley.edu/browse/SISRP-13251
We will be introducing `delegate_acting_as.html` and other files/variables using proper underscore between `acting` and `as`.  This PR refactors the old naming convention (`actingas`) to match.
=> SISRP-13251, refactor actingas > acting_as and actas > act_as

src/assets/templates/dashboard_task_loop.html, src/assets/templates/dashboard_task_noitems.html
https://jira.berkeley.edu/browse/SISRP-13455
=> SISRP-13455 - Issues with unscheduled campus solutions tasks

src/assets/javascripts/angular/controllers/widgets/delegateStudentsController.js, src/assets/javascripts/angular/factories/delegateFactory.js, src/assets/templates/toolbox.html, src/assets/templates/widgets/toolbox/delegate_students.html
https://jira.berkeley.edu/browse/SISRP-13260
The design has not been applied to `delegate_students.html` but it is working in terms of start / stop delegate-act-as mode. The card pays attention to feature flag.
=> SISRP-13260, Delegate Students card on Toolbox - basic wiring

app/controllers/act_as_controller.rb, app/controllers/delegate_act_as_controller.rb, config/routes.rb, src/assets/javascripts/angular/controllers/widgets/actingAsController.js, src/assets/javascripts/angular/controllers/widgets/delegateActingAsController.js, src/assets/javascripts/angular/factories/adminFactory.js
https://jira.berkeley.edu/browse/SISRP-13257
You'll see that `DelegateActAsController` extends `ActAsController`. If shared logic becomes a problem we'll split off the `delegate-act-as` code. After this merge I'll drop in `footer.html` and related.
=> SISRP-13257, controller to manage session during delegate-view-as mode

app/models/my_tasks/sis_tasks.rb, src/assets/templates/dashboard_task_noitems.html
https://jira.berkeley.edu/browse/SISRP-12616
Also fixes an issue at
https://jira.berkeley.edu/browse/SISRP-13455
=> SISRP-12616 - Checklist on main Dashboard should honor FA viewing restrictions

src/assets/javascripts/angular/controllers/widgets/profile/title4Controller.js
https://jira.berkeley.edu/browse/SISRP-13426
=> SISRP-13426 - Update Title IV authorization shows not authorized even after selecting to Authorize

src/assets/templates/widgets/finaid_profile.html, src/assets/templates/widgets/finaid_summary.html, src/assets/templates/widgets/finaid_summary_fundingoffered.html, src/assets/templates/widgets/finaid_summary_netcost.html, src/assets/templates/widgets/sir/sir_item.html
https://jira.berkeley.edu/browse/SISRP-13406
=> SISRP-13406 - FinAid accessibility: "separator" being voiced for horizontal bars

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/stylesheets/_finaid_summary.scss, src/assets/templates/widgets/finaid_awards.html, src/assets/templates/widgets/finaid_summary.html, src/assets/templates/widgets/finaid_summary_fundingoffered.html, src/assets/templates/widgets/finaid_summary_netcost.html
https://jira.berkeley.edu/browse/SISRP-12732
Also fixes:
SISRP-13413 - FinAid Awards: "Term View" link should not be offered if there are no awards
https://jira.berkeley.edu/browse/SISRP-13413
=> SISRP-12732 - MyNetCost Info not on FinAid cards anymore

lib/services/jms_worker.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6142
=> CLC-6142 Remove temporary JMS diagnostic logging

src/assets/templates/toolbox.html, src/assets/templates/widgets/toolbox/delegate_intro_to_calcentral.html
https://jira.berkeley.edu/browse/SISRP-13261
* New card for Toolbox page
* Hide delegate cards when feature flag
=> SISRP-13261, Welcome to CalCentral for delegate users

app/models/campus_solutions/my_checklist.rb, app/models/campus_solutions/my_deposit.rb, app/models/hub_edos/user_attributes.rb, app/models/my_tasks/merged.rb, config/settings.yml, spec/models/hub_edos/user_attributes_spec.rb
Discussion of various points are spread across the following JIRAs:
https://jira.berkeley.edu/browse/SISRP-13067
https://jira.berkeley.edu/browse/SISRP-13422
https://jira.berkeley.edu/browse/SISRP-12526
=> SISRP-13067 SISRP-12526 Tune caching for Admissions

src/assets/templates/uid_error.html
https://jira.berkeley.edu/browse/SISRP-13317
Also belatedly updated the CalCentral support link.
=> SISRP-13317 Modify "no-UID" error page for applicants-in-progress

app/controllers/routes_list_controller.rb, src/assets/javascripts/angular/controllers/widgets/apiTestController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6054
=> CLC-6054 Fix outdated entries in API test lists

src/assets/templates/academics_student_profile.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5910
=> CLC-5910 Ensure visibility of concurrent-enrollment academics profile message

script/sis/verify_sis_api_endpoints.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6124
* Organized CS API calls by feature flag dependency.
* Added `UC_DEPOSIT_AMT.v1/deposit` (cs_sir flag)
=> CLC-6124, verify_sis_api_endpoints script in prep for v72 smoke test

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, public/dummy/json/enrollment_term.json, public/dummy/json/enrollment_terms.json, src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/javascripts/angular/factories/enrollmentFactory.js, src/assets/templates/academics.html, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment/meet_advisor.html, src/assets/templates/widgets/enrollment/plan.html, src/assets/templates/widgets/enrollment/schedule.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-13232
=> SISRP-13232 - CalCentral Enrollment Card (MVP): back-end and front-end work

src/assets/javascripts/angular/controllers/pages/finaidController.js, src/assets/templates/finaid.html
https://jira.berkeley.edu/browse/SISRP-13506
=> SISRP-13506 - Navigation Bread Crumb should read Financial Aid and Scholarships

src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js, src/assets/templates/widgets/finaid_communications_tasks.html
https://jira.berkeley.edu/browse/SISRP-13496
=> SISRP-13496 - FA TASKs Get rid of toggle functionality..just show all.

src/assets/templates/directives/finaid_table.html
https://jira.berkeley.edu/browse/SISRP-13672
=> SISRP-13672 - Awards by term page misaligned for SID 23444979

src/assets/templates/widgets/sir/sir_item_received.html
https://jira.berkeley.edu/browse/SISRP-13564
=> SISRP-13564 - Add sentence to the SIR received message to notify students when they can log in and see updates

src/assets/templates/widgets/sir/sir_item_received.html
https://jira.berkeley.edu/browse/SISRP-13564
=> SISRP-13564 QA - Add sentence to the SIR received message to notify students when they can log in and see updates

src/assets/templates/widgets/sir/sir_item_completed.html
https://jira.berkeley.edu/browse/SISRP-13951
=> SISRP-13951 - Change code on SIR card for LAW Maybe option

src/assets/templates/widgets/sir/sir_item_completed.html
https://jira.berkeley.edu/browse/SISRP-13951
=> QA SISRP-13951 - Change code on SIR card for LAW Maybe option

script/build-torquebox.sh, script/calcentral-update.sh, script/calendar.sh, script/configure-all-canvas-apps-from-current-host.sh, script/export-cached-csv-enrollments-set.sh, script/load-test-dev.sh, script/migrate.sh, script/reconfigure-canvas-test-servers.sh, script/refresh-all-canvas-enrollments.sh, script/refresh-canvas-enrollments.sh, script/refresh-canvas-users.sh, script/report-lti-usage.sh, script/report-turnitin-usage.sh, script/start-torquebox.sh, script/sync-canvas-guest-users.sh, script/sync-canvas-new-users.sh, script/update-mailing-list-memberships.sh, script/webcast_lti_refresh.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5842
SPOILER: there are no surprises.
=> CLC-5842 Allow override of RAILS_ENV in shell scripts

app/models/my_tasks/sis_tasks.rb
https://jira.berkeley.edu/browse/SISRP-13642
=> SISRP-13642 - CalCentral - Status Date Not Displaying for Unscheduled Checklists

src/assets/javascripts/angular/services/profileService.js, src/assets/templates/widgets/profile/contact_email_editor.html, src/assets/templates/widgets/profile/contact_phone_editor.html
https://jira.berkeley.edu/browse/SISRP-9941
=> SISRP-9941 - Profile Contact Info - don't show the preferred checkbox when the item is preferred

src/assets/javascripts/angular/services/userService.js, src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-13445
=> SISRP-13445 - CalCentral bConnected information incorrectly displaying for Pre-SIR

src/assets/javascripts/angular/services/userService.js, src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-13445
=> SISRP-13445 QA - CalCentral bConnected information incorrectly displaying for Pre-SIR

app/models/user/api.rb, app/models/user_specific_model.rb, app/policies/authentication_state_policy.rb, fixtures/xml/campus_solutions/delegate_access_students.xml, spec/controllers/my_academics_controller_spec.rb, spec/models/campus_solutions/delegate_students_spec.rb, spec/models/user_specific_model_spec.rb, spec/policies/authentication_state_spec.rb, src/assets/templates/navigation.html
https://jira.berkeley.edu/browse/SISRP-7689
Show/hide navigation according to delegate_permissions when user is in delegate-view-as mode. Tidying in `api.rb`, too.
=> SISRP-7689, User::API controls nav tabs per delegate-view-as privileges

app/models/hub_edos/proxy.rb
https://jira.berkeley.edu/browse/SISRP-14047
=> SISRP-14047 Handle new no-data response from Hub

spec/ui_selenium/pages/cal_net_auth_page.rb
https://jira.berkeley.edu/browse/SISRP-14107
=> SISRP-14107 - QA test fix (broken element locator)

script/sis/sis_script_utils.sh
https://jira.berkeley.edu/browse/SISRP-14138
The script missed the 'No service was found' scenario.
=> SISRP-14138, script to verify SIS API gets more validation

src/assets/templates/widgets/toolbox/view_as.html
https://jira.berkeley.edu/browse/SISRP-13442
=> SISRP-13442 - UX DESIGN: View-As Card with Names for Advising Pt 1

spec/ui_selenium/my_profile_contact_info_spec.rb, spec/ui_selenium/pages/my_profile_contact_info_card.rb
https://jira.berkeley.edu/browse/SISRP-14107
=> SISRP-14107: fix QA profile contact info test

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-13247
=> SISRP-13247 Add enrollment card dependencies to API verify script

app/models/hub_edos/user_attributes.rb, spec/models/hub_edos/user_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-13314
In https://jira.berkeley.edu/browse/SISRP-14215, Richard Wood explains that fromDate and toDate should be ignored.
=> SISRP-13314, :advisor=true per affiliation type

app/controllers/bootstrap_controller.rb, app/models/campus_solutions/enrollment_term_expiry.rb
https://jira.berkeley.edu/browse/SISRP-13850
On the model of profile and finaid expiration parameters.
=> SISRP-13850 Add cache expiration query parameter for CS enrollment data

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-7687
Script will verify API endpoints to the extent of feature flags.
=> SISRP-7687, verify script pays attention to feature flags

src/assets/templates/widgets/enrollment/enrollment_link.html
https://jira.berkeley.edu/browse/SISRP-13850
=> SISRP-13850 - CalCentral Enrollment Card: Caching

spec/ui_selenium/pages/api_my_fin_aid_page.rb
https://jira.berkeley.edu/browse/SISRP-14107
=> SISRP-14107 - fix whitespace issue in QA FinAid test

src/assets/javascripts/angular/controllers/widgets/delegateStudentsController.js, src/assets/stylesheets/_toolbox.scss, src/assets/templates/widgets/toolbox/delegate_students.html
https://jira.berkeley.edu/browse/SISRP-13260
WIP: 
+ `src/assets/javascripts/angular/controllers/widgets/delegateStudentsController.js` contains temporary logic to set a `student.fakeProfilePhotoAPI`
+ `src/assets/templates/widgets/toolbox/delegate_students.html` uses the temporary `student.fakeProfilePhotoAPI`
=> SISRP-13260 - Build "Students" card in delegate user's default view ("Toolbox")

src/assets/javascripts/angular/services/userService.js, src/assets/stylesheets/_buttons.scss, src/assets/templates/dashboard_task_loop.html, src/assets/templates/directives/finaid_permissions.html, src/assets/templates/widgets/activity.html, src/assets/templates/widgets/activity_list_link.html, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/enrollment_hide_links.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment_card.html, src/assets/templates/widgets/finaid_awards_loans.html, src/assets/templates/widgets/finaid_awards_section.html, src/assets/templates/widgets/finaid_communications.html, src/assets/templates/widgets/finaid_communications_tasks.html, src/assets/templates/widgets/finaid_profile.html, src/assets/templates/widgets/finaid_summary_footer.html, src/assets/templates/widgets/profile/basic_preferred_name.html, src/assets/templates/widgets/profile/contact_address.html, src/assets/templates/widgets/profile/contact_email.html, src/assets/templates/widgets/profile/contact_phone.html, src/assets/templates/widgets/profile/title4.html, src/assets/templates/widgets/sir/sir_item.html
https://jira.berkeley.edu/browse/SISRP-14142
Since there is so much overlap, this also includes
SISRP-14421 - Hide links to CS (classic and fluid) when acting as a delegate or advisor
https://jira.berkeley.edu/browse/SISRP-14421
=> SISRP-14142 - In View As mode - Edit / add buttons should be disabled

src/assets/javascripts/angular/controllers/widgets/delegateLinkingController.js
https://jira.berkeley.edu/browse/SISRP-13315
This is a one-liner.
=> SISRP-13315 - After Delegate accepts a student send him/her to My Toolbox and display all accepted students

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-14211
URLs used by the Hub to query Campus Solutions. You won't find these in CalCentral proxy code.
cc: @dkawase
=> SISRP-14211, add latest GL4 URLs to our SIS api testing script

src/assets/javascripts/angular/controllers/widgets/academicDatesController.js, src/assets/stylesheets/_toolbox.scss, src/assets/templates/toolbox.html, src/assets/templates/widgets/toolbox/academic_dates.html
https://jira.berkeley.edu/browse/SISRP-13264
conflicts should all be resolved
cc @johncrossman @christianvuerings
=> SISRP-13264 - Build "Academic Dates..." card in delegate user's default view ("Toolbox")

src/assets/javascripts/angular/factories/profileFactory.js
https://jira.berkeley.edu/browse/SISRP-14457
I love XLATs!
=> SISRP-14457 - Add 'Pay Frequency' XLAT Values to Profile-Work Experience

src/assets/stylesheets/_tables.scss, src/assets/templates/widgets/toolbox/view_as.html
https://jira.berkeley.edu/browse/SISRP-14135
=> SISRP-14135 - Front End Dev: View-As Card with Names for Advising Pt 1

app/models/campus_solutions/my_financial_aid_funding_sources.rb, app/models/campus_solutions/my_financial_aid_funding_sources_term.rb
https://jira.berkeley.edu/browse/SISRP-14578
A couple of classes were missed in #4747.
=> SISRP-14578 Ensure default aid year for user-specific finaid models

app/models/campus_solutions/holds.rb
Further log diving on https://jira.berkeley.edu/browse/SISRP-14578 is turning up several unrelated bugs. Here's another one.
=> SISRP-14578 Do not explode on missing SERVICE_INDICATORS element

src/assets/javascripts/angular/controllers/pages/dashboardController.js, src/assets/javascripts/angular/services/userService.js
https://jira.berkeley.edu/browse/SISRP-14530
Default home is `/dashboard` but delegates in view-as mode must have default based on privileges.
=> SISRP-14530, delegate-view-as will not have dashboard so default to next best

src/assets/templates/toolbox.html
https://jira.berkeley.edu/browse/SISRP-14262
My changes in PR #4828 were undone by #4844 – which I did review :) 
I now restore the delicate combo of conditionals in `toolbox.html`.
=> SISRP-14262, fix access to toolbox widgets per api.user.profile

app/controllers/sessions_controller.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml
https://jira.berkeley.edu/browse/SISRP-14653
=> SISRP-14653 - UX Develop: Prototype - Send a redirect parameter to the CS logout when a user logs out of CalCentral

fixtures/xml/campus_solutions/academic_plan.xml, fixtures/xml/campus_solutions/enrollment_term.xml, public/dummy/json/academic_plan.json, public/dummy/json/enrollment_term.json, spec/models/campus_solutions/enrollment_term_spec.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/javascripts/angular/directives/outboundLinkDirective.js, src/assets/javascripts/angular/factories/enrollmentFactory.js, src/assets/stylesheets/_enrollment_card.scss, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment/plan.html, src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-14635
Also fixes:
SISRP-14634 - Class Scheduler outbound link should open in new window
https://jira.berkeley.edu/browse/SISRP-14634
=> SISRP-14635 - Enrollment card: front end for academic planner deeplink

app/models/campus_solutions/financial_aid_data.rb, app/models/campus_solutions/financial_aid_funding_sources.rb, app/models/campus_solutions/financial_aid_funding_sources_term.rb, app/models/campus_solutions/my_financial_aid_data.rb, app/models/campus_solutions/my_financial_aid_filtered_for_advisor.rb, app/models/campus_solutions/my_financial_aid_funding_sources.rb, app/models/campus_solutions/my_financial_aid_funding_sources_term.rb, spec/controllers/campus_solutions/financial_aid_data_controller_spec.rb, spec/controllers/campus_solutions/financial_aid_funding_sources_controller_spec.rb, spec/controllers/campus_solutions/financial_aid_funding_sources_controller_term_spec.rb, spec/models/campus_solutions/my_financial_aid_filtered_for_advisor_spec.rb
https://jira.berkeley.edu/browse/SISRP-14578
The wall built in #4747 was leaky. Also, remove needless default zero for aid_year.
=> SISRP-14578 Zealously block empty aid_year from LiveUpdates

src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-14648
=> SISRP-14648 - Enrollment Card - where should 'Discovery Courses' go?

app/models/user/api.rb
https://jira.berkeley.edu/browse/SISRP-14711
Give advisors some dashboard love.
=> SISRP-14711, Advisors should see /dashboard when view-as mode

src/assets/javascripts/angular/directives/finaidPermissionsDirective.js, src/assets/templates/directives/finaid_permissions.html, src/assets/templates/widgets/finaid_approvals.html
https://jira.berkeley.edu/browse/SISRP-14765
=> SISRP-14765 - Can't Accept Terms and Conditions in cc-sis-test in View-As mode

app/models/user/api.rb, spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-7688
Generic and concise way to control access to grade info.
=> SISRP-7688, access to My Academics does not guarantee access to grades

src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-14762
=> SISRP-14762 - Hide grades in CalCentral UX when api.user.profile.canViewGrades is false

src/assets/templates/widgets/profile/work_experience_section.html
https://jira.berkeley.edu/browse/SISRP-12506
=> SISRP-12506 - Profile - work experience date info not shown if only end date exists - expected?

app/controllers/campus_solutions/advising_resources_controller.rb, app/models/campus_solutions/advising_resources.rb, config/routes.rb, fixtures/xml/campus_solutions/advising_resources.xml, public/dummy/json/advising_resources.json, script/sis/verify_sis_api_endpoints.sh, spec/controllers/campus_solutions/advising_resources_controller_spec.rb, spec/models/campus_solutions/advising_resources_spec.rb
https://jira.berkeley.edu/browse/SISRP-13763
Another day, another proxy.
=> SISRP-13763 Back end for advising resources deep links

script/sis/verify_sis_api_endpoints.sh
For example:
```
export UID_CROSSWALK=20023764
export SID=4000087685
export CAMPUS_SOLUTIONS_ID=4000087685
script/sis/verify_sis_api_endpoints.sh  ~/.calcentral_config/development.local.yml
```
cc: @dkawase
=> NOJIRA, verify script changes: add CS endpoint, allow for ID overrides

app/models/canvas_csv/maintain_users.rb, spec/models/canvas_csv/maintain_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6199
I expect this will migrate to a module method at some point to be used from other classes, but didn't want to delay the fix.
=> CLC-6199 Fix reactivation of bCourses account when SIS ID is also changed

src/assets/templates/academics.html, src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-14767
=> SISRP-14767: Show 404 for privilege url when viewing as delegate w/o corresponding privilege

src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/adjust_waitlisted.html
https://jira.berkeley.edu/browse/SISRP-14651
=> SISRP-14651 - CS Enrollment Card API - Change Unit format

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-14832
*From Jira description:* Talked with Darlene today and we agreed on the following process:
* SIS team tells us what to expect (e.g., enrollment-related endpoints are not ready)
* we run the verify script and ignore failures associated with "unready" feature flags (i.e., endpoint sets)
This requires a change to the format and info in script output.
IMO, this change makes the script more readable.
See "USAGE" section of diff for more info.
=> SISRP-14832, verify_sis_api_endpoints.sh should report feature flag per endpoint-set / failure

public/json/campuslinks.json
https://jira.ets.berkeley.edu/jira/browse/CLC-6192
=> CLC-6192 Update Housing links in My Campus

app/models/calnet_ldap/user_attributes.rb, app/models/user/api.rb, app/models/user/student.rb, config/settings/test.yml, spec/models/calnet_ldap/user_attributes_spec.rb, spec/models/user/api_spec.rb, spec/models/user/student_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6200
Bamboo https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT271-JOB1-1 shows only our usual failures, plus one on `Berkeley::CoursePolicy#can_view_webcast_sign_up?` that _looks_ like a fluke...
=> CLC-6200 Insert LDAP attributes as intermediate fallback between Hub and Oracle

app/controllers/config_controller.rb, spec/controllers/config_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-14845
See Jira for sample screenshot.
=> SISRP-14845, If user can_administrate? then surface SIS dependencies in /api/config

Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-6100
Incorporate https://github.com/ets-berkeley-edu/omniauth-cas/pull/2.
=> CLC-6100 Bump omniauth-cas fork to latest revision

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
https://jira.berkeley.edu/browse/SISRP-14877
=> SISRP-14877 - Avoid JS error when we get a 500 on the enrollment card from CS

app/models/calnet_ldap/client.rb, spec/models/calnet_ldap/client_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6207
=> CLC-6207 Handle LDAP errors

app/models/calnet_ldap/client.rb, spec/models/calnet_ldap/client_spec.rb
QA versions of https://github.com/ets-berkeley-edu/calcentral/pull/4902
=> QA CLC-6207 Handle LDAP errors

app/models/calnet_ldap/user_attributes.rb, spec/models/calnet_ldap/user_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-14914
=> SISRP-14914 Fall back to Oracle when LDAP contains conflicting student affiliations

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment/meet_advisor.html, src/assets/templates/widgets/enrollment/plan.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-14996
Also fixes:
SISRP-14997 - Multiple enrollment cards, clicking on "plan" opens it for everyone
https://jira.berkeley.edu/browse/SISRP-14997
=> SISRP-14996 - Don't hardcode "phase1" in CalCentral - since we can also have priority

app/models/calnet_ldap/user_attributes.rb, spec/models/calnet_ldap/user_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-14914
QA version of #4904.
=> [QA] SISRP-14914 Fall back to Oracle when LDAP contains conflicting student affiliations

app/models/my_tasks/sis_tasks.rb
https://jira.berkeley.edu/browse/SISRP-13642
=> QA SISRP-13642 - CalCentral - Status Date Not Displaying for Unscheduled Checklists

app/models/campus_solutions/my_person_name.rb, app/models/campus_solutions/user_api_expiry.rb, app/models/campus_solutions/user_api_updating_model.rb, spec/controllers/campus_solutions/person_name_controller_spec.rb, src/assets/javascripts/angular/controllers/widgets/profile/basicPreferredNameController.js, src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-10695
This was interesting ~ Let me know what you think!
=> SISRP-10695 - Profile - update preferred name, gear still shows previous name

src/assets/javascripts/angular/services/profileService.js, src/assets/templates/widgets/profile/contact_email_editor.html, src/assets/templates/widgets/profile/contact_phone_editor.html
https://jira.berkeley.edu/browse/SISRP-9941
QA version of #4801
=> SISRP-9941 - [QA branch] Profile Contact Info - don't show the preferred checkbox when the item is preferred

app/models/campus_solutions/delegate_students.rb, spec/models/campus_solutions/delegate_students_spec.rb
https://jira.berkeley.edu/browse/SISRP-15057
=> SISRP-15057, CalCentral, when querying CS API for students per delegate, should use ByCsId(empl_id) to get LDAP_UID

app/models/campus_solutions/enrollment_term.rb, src/assets/stylesheets/_flexbox.scss, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/adjust_waitlisted.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment/meet_advisor.html, src/assets/templates/widgets/enrollment/plan.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-15077
Also fixes
SISRP-14820 - Show waitlisted classes as soon as we have test data in BCSDEV
https://jira.berkeley.edu/browse/SISRP-14820
=> SISRP-15077 - Show enrollment card even though we don't have the period data yet

spec/ui_selenium/my_profile_basic_info_spec.rb, spec/ui_selenium/pages/cal_central_pages.rb
https://jira.berkeley.edu/browse/SISRP-10695
=> SISRP-10695 - QA test update for preferred name change on popover icon

app/controllers/photo_controller.rb, spec/controllers/photo_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-15111
=> SISRP-15111 Do not surface /api/my/photo to delegates

spec/ui_selenium/my_profile_basic_info_spec.rb, spec/ui_selenium/my_profile_contact_info_spec.rb
https://jira.berkeley.edu/browse/SISRP-15236
=> SISRP-15236 - run QA profile editing tests on Bamboo nightly

src/assets/templates/widgets/sir/sir_item_completed.html
https://jira.berkeley.edu/browse/SISRP-13659
=> SISRP-13659 - SIR Card Behavior for Maybe

src/assets/javascripts/angular/controllers/widgets/delegateStudentsController.js, src/assets/stylesheets/_delegate_student.scss, src/assets/stylesheets/_toolbox.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/academics_student_profile.html, src/assets/templates/widgets/delegate_student_img.html, src/assets/templates/widgets/toolbox/delegate_students.html
https://jira.berkeley.edu/browse/SISRP-15107
=> SISRP-15107 - Show bear photo to all delegates

src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/plan.html
https://jira.berkeley.edu/browse/SISRP-15321
=> SISRP-15321 - Enrollment card - show / hide planner date & withdraw link

src/assets/stylesheets/_enrollment_card.scss, src/assets/stylesheets/_flexbox.scss, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/adjust_waitlisted.html
https://jira.berkeley.edu/browse/SISRP-15342
=> SISRP-15342 - Enrollment card - change to Add / Swap links instead of Update

app/models/canvas_csv/maintain_users.rb, spec/models/canvas_csv/maintain_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6214
True, shmue, so long as it's Boolean...
=> CLC-6214 Fix reverso-blunder in Canvas Login ID parsing

config/settings.yml
https://jira.berkeley.edu/browse/SISRP-15333
=> SISRP-15333 - Log out from CalCentral > bcs-web-dev-03: /uc_cust/data/portal/html/logout.html > 404 "Not Found"

app/models/campus_solutions/delegate_students.rb, fixtures/xml/campus_solutions/delegate_access_students.xml
https://jira.berkeley.edu/browse/SISRP-13265
CS API change on ROLENAME of phone-only: `UC_CS_DA_THIRD_PARTY_RELEASE`
=> SISRP-13265, Delegate My Students card > No link to view-as when privilege is only by phone

app/controllers/campus_solutions/delegate_access_controller.rb, app/models/campus_solutions/delegate_terms_and_conditions.rb, fixtures/xml/campus_solutions/delegate_terms_and_conditions.xml, script/sis/verify_sis_api_endpoints.sh, spec/controllers/campus_solutions/delegate_access_controller_spec.rb, src/assets/templates/widgets/delegate/linking.html
https://jira.berkeley.edu/browse/SISRP-15402
Wire in the real deal.
=> SISRP-15402, GET Delegated Access terms and conditions via CS API endpoint

app/models/berkeley/user_roles.rb, fixtures/json/affiliations.json, fixtures/json/person_edo.json, fixtures/json/student_edo.json, spec/models/berkeley/user_roles_spec.rb, spec/models/user/authentication_validator_spec.rb
https://jira.berkeley.edu/browse/SISRP-15412
=> SISRP-15412 - Enrollment card is not showing on calcentral-sis-dev

fixtures/xml/campus_solutions/ferpa_deeplink_url.xml, spec/models/campus_solutions/ferpa_deeplink_spec.rb
https://jira.berkeley.edu/browse/SISRP-15406
=> SISRP-15406 - Fix ferpa_deeplink_spec: "Campus solutions:: ferpa deeplink real proxy"

fixtures/json/affiliations.json, fixtures/json/person_edo.json, fixtures/json/student_edo.json
https://jira.berkeley.edu/browse/SISRP-15412
=> SISRP-15412 - follow up - Enrollment card is not showing on calcentral-sis-dev

src/assets/templates/widgets/enrollment/meet_advisor.html, src/assets/templates/widgets/enrollment/schedule.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-15427
=> SISRP-15427 - CalCentral - enrollment card - updates for advising

app/models/notifications/jms_message_handler.rb, app/models/notifications/sis_expiry_processor.rb, fixtures/jms_recordings/ist_jms.txt, spec/models/notifications/jms_message_handler_spec.rb, spec/models/notifications/sis_expiry_processor_spec.rb
https://jira.berkeley.edu/browse/SISRP-13250
The wiring of event topics to expiry modules is incomplete and will require functional validation. However, it should be easy from here to wire up the right behavior once we're certain what that behavior is.
=> SISRP-13250 Expire user data by functional area based on JMS event topic

app/controllers/campus_solutions/work_experience_controller.rb, app/models/campus_solutions/my_work_experience.rb, app/models/campus_solutions/work_experience.rb, app/models/campus_solutions/work_experience_delete.rb, config/routes.rb, fixtures/xml/campus_solutions/prior_work_delete.xml, spec/models/campus_solutions/work_experience_delete_spec.rb, spec/models/campus_solutions/work_experience_spec.rb
https://jira.berkeley.edu/browse/SISRP-15395
Thanks for the direction, @paulkerschen!
=> SISRP-15395 - Back End Dev: Credentials Tab - Work Experience Card - Delete

src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-15416
=> SISRP-15416 - CalCentral: message/mitigation for when Class Schedule is viewable

app/models/calnet_ldap/user_attributes.rb, app/models/user/api.rb, spec/models/calnet_ldap/user_attributes_spec.rb, spec/models/user/api_spec.rb, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/profile/basic_nonstudent.html
https://jira.berkeley.edu/browse/SISRP-15401
Still needs review by the UX designers.
=> SISRP-15401 Only show CS-based Profile data to active students or applicants

spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-15401
Not the DRYest PR I ever made, but hopefully it gets the point across.
=> SISRP-15401 Bulletproof User::Api test against testext env

src/assets/templates/widgets/advisor/resources.html
https://jira.berkeley.edu/browse/SISRP-15474
SISRP-15475 - Advising resources - Add link to Academic Progress Report
https://jira.berkeley.edu/browse/SISRP-15475
=> SISRP-15474 - Hide the link to Advisee Student Center

src/assets/templates/widgets/profile/basic_nonstudent.html
It is CRITICALLY ESSENTIAL that this be deployed before the UX designers review the change and mock me.
=> SISRP-15401 Fix typo

src/assets/templates/widgets/enrollment/adjust_waitlisted.html
https://jira.berkeley.edu/browse/SISRP-15489
=> SISRP-15489 - Enrollment card: Also add drop link to waitlisted classes

src/assets/templates/widgets/finaid_awards_section.html
https://jira.berkeley.edu/browse/SISRP-15487
=> SISRP-15487 - Remove UPPERCASE formatting of itemtype comment on the award card

app/models/calnet_ldap/user_attributes.rb, app/models/canvas_csv/maintain_users.rb, app/models/user/api.rb, spec/models/calnet_ldap/user_attributes_spec.rb, spec/models/canvas_csv/maintain_users_spec.rb, spec/models/user/api_spec.rb, src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/profile/basic_nonstudent.html
I may have to rewrite the User::Api RSpec changes to fix Bamboo, but let's give it a try...
=> QA for interim release: CLC-6214, SISRP-15401

fixtures/xml/campus_solutions/delegate_access_students.xml, spec/models/campus_solutions/delegate_students_spec.rb, src/assets/javascripts/angular/controllers/widgets/delegateStudentsController.js, src/assets/templates/widgets/toolbox/delegate_students.html
https://jira.berkeley.edu/browse/SISRP-15470
=> SISRP-15470 - Delegated Access: mixed content JS error when clicking Toolbox student link

app/models/user/api.rb, spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-15443
=> SISRP-15443 - When viewing as a delegate, the gear/popover image is suppressed entirely

src/assets/templates/academics.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6212
=> CLC-6213 Align students/teachers academics_final_exam_schedule logic

src/assets/templates/widgets/profile/delegate.html
https://jira.berkeley.edu/browse/SISRP-13252
No link is better than bad link.
=> SISRP-13252, when CS gives bad delegate.URL we 'turn off' student's access to CS > Delegated Access

spec/models/oec/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6217
=> CLC-6217 Update courses for OEC integration tests

src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-15497
=> SISRP-15497 - Add link to Class Enrollment Card

src/assets/templates/widgets/enrollment/meet_advisor.html
https://jira.berkeley.edu/browse/SISRP-15498
=> SISRP-15498 - Advising Appointment Linking

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6194
=> CLC-6194 Replace support link on bCourses 404 page

app/models/my_academics/filtered_for_delegate.rb, spec/controllers/my_academics_controller_spec.rb, spec/models/my_academics/filtered_for_delegate_spec.rb
https://jira.berkeley.edu/browse/SISRP-15399
=> SISRP-15399, delegates with view-academics privilege should see exam schedule

src/assets/templates/widgets/toolbox/delegate_quick_links.html
https://jira.berkeley.edu/browse/SISRP-15590
=> SISRP-15590 - Delegated Access Quick Links: why is list beneath "CalParents" link-less?

src/assets/javascripts/angular/controllers/widgets/finaid/finaidApprovalsController.js
https://jira.berkeley.edu/browse/SISRP-12062
=> SISRP-12062 - Need message to display if students says no to Title IV authorization

src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-15651
=> SISRP-15651 - Academics page hitting JS error

src/assets/templates/widgets/profile/basic_preferred_name_editor.html, src/assets/templates/widgets/profile/contact_address_editor.html, src/assets/templates/widgets/profile/contact_email_editor.html, src/assets/templates/widgets/profile/contact_phone_editor.html
https://jira.berkeley.edu/browse/SISRP-15673
=> SISRP-15673 - Change "..." to &hellip; entity in profile templates

src/assets/templates/widgets/profile/basic.html, src/assets/templates/widgets/profile/basic_nonstudent.html
https://jira.berkeley.edu/browse/SISRP-15495
PR needs @raydavis or similar sign-off. Is wording okay? Is my assumption correct that concurrent students can use CalNet directory to update personal info?
=> SISRP-15495, concurrent enrollment students see non-student message on profile page

app/models/user/search_users.rb, spec/models/user/search_users_spec.rb
https://jira.berkeley.edu/browse/SISRP-15536
Use an enumerable type (Set) that forces uniqueness.
=> SISRP-15536, UID/SID lookup producing two identical results

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-15634
Change default IDs and fix URL path on UC_DEPOSIT_AMT check.
=> SISRP-15634, remove trailing slash from UC_DEPOSIT_AMT call

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
https://jira.berkeley.edu/browse/SISRP-15695
=> SISRP-15695 - CalCentral: Enrollment Card - section #6: Adjust - Default to Open

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, src/assets/templates/widgets/advisor/resources.html
https://jira.berkeley.edu/browse/SISRP-15693
=> SISRP-15693 - Hide Study List / GTW Forms Links on Advising Resources Card till GL5.3

public/dummy/json/student_with_languages.json, src/assets/javascripts/angular/controllers/widgets/profile/languagesSectionController.js, src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/languages_section.html, src/assets/templates/widgets/profile/languages_section_editor.html
26 Feb 2016
@christianvuerings here's a first pass at changes to the language section controller and template, plus the new language section editor template
=> SISRP-10777: templates and controller changes ~ refactored

src/assets/stylesheets/_profile_page.scss, src/assets/templates/widgets/profile/delegate.html, src/assets/templates/widgets/profile/emergency_contact.html
https://jira.berkeley.edu/browse/SISRP-14260
=> SISRP-14260 - Improves accessibility of link to manage delegates

app/models/user/api.rb, spec/models/user/api_spec.rb, src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-15727
=> SISRP-15727 - New Students Can't Get to FinAid until they SIR (CalCentral-DEV)

app/models/campus_solutions/dashboard_url.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, script/sis/verify_sis_api_endpoints.sh, spec/models/campus_solutions/dashboard_url_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6154
We've been tossing in many new feature flags... It feels good to rip one out.
=> CLC-6154, no need for show_notifications_archive_link feature flag

app/models/berkeley/term.rb, app/models/berkeley/terms.rb, app/models/canvas_lti/course_provision.rb, app/models/user_specific_model.rb, lib/active_attr_model.rb
https://jira.berkeley.edu/browse/SISRP-15737
Finally tracked this occasionally crippling annoyance to its source...
=> SISRP-15737 Fix classname logging in ActiveAttr-using classes

src/assets/templates/dashboard.html, src/assets/templates/widgets/sir/sir_item_received.html
https://jira.berkeley.edu/browse/SISRP-15750
=> SISRP-15750 - Hide SIR Card for delegates & disable actions on SIR card for advisors

app/models/links/campus_link_loader.rb, app/models/links/my_campus_links.rb, public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-15754
The campuslinks.json changes add a '"applicant": true,' line under every '"student": true,' line.
=> SISRP-15754 Show applicants the same My Campus links as students

src/assets/javascripts/angular/controllers/widgets/profile/languagesSectionController.js
@christianvuerings PR fixes for:
+ the promise creation logic in `loadInformation()`
+ a sorting problem in `parsePerson()`
+ the filtering logic in `parseLanguages()`
=> SISRP-10777 - Front End Dev: Credentials Tab - Languages Card - Edit

src/assets/templates/widgets/enrollment/plan.html, src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-15761
=> SISRP-15761 - Delegated Access: college scheduler link is available to delegate

src/assets/templates/widgets/delegate/linking.html
https://jira.berkeley.edu/browse/SISRP-15804
Explanation for this PR is in the jira bug...
=> SISRP-15804 - Delegated Access: clicking "show more" T&C on welcome page submits the form

app/models/oec/merged_sheet_validation.rb, spec/models/oec/publish_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6226
=> CLC-6226 OEC: Ensure suffixed ccns are included in student csv generation

src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/adjust_waitlisted.html
https://jira.berkeley.edu/browse/SISRP-15806
=> SISRP-15806 - CC Design/API - added fields request

src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-15504
**NOTE**: Only merge this evening around 5pm!
=> SISRP-15504 - Grade base link vs add/drop/swap

app/models/user/authentication_validator.rb, spec/models/user/authentication_validator_spec.rb
https://jira.berkeley.edu/browse/SISRP-15828
Nil check on `cs_feed[:feed]['student']['affiliations']` and a little tidying in spec.
=> SISRP-15828, delegated-access: FATAL error authenticating new delegate-only user

app/policies/authentication_state_policy.rb, spec/policies/authentication_state_policy_spec.rb
https://jira.berkeley.edu/browse/SISRP-15849
One line tweak plus tidying in spec.
=> SISRP-15849, oec auth policy w.r.t view-as mode

app/models/campus_solutions/advising_resources.rb, app/models/campus_solutions/user_api_expiry.rb, app/models/campus_solutions/user_api_updating_model.rb, app/models/notifications/sis_expiry_processor.rb, lib/cache/related_cache_key_tracker.rb
https://jira.berkeley.edu/browse/SISRP-13248
=> SISRP-13248 Wire up additional expiry behavior to JMS listener

app/models/canvas_csv/add_new_users.rb, spec/models/canvas_csv/add_new_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6229
Also brushed some dust off the specs.
=> CLC-6229 sync-canvas-new-users should check for "inactive-" bCourses accounts

src/assets/templates/delegate_welcome.html
https://jira.berkeley.edu/browse/SISRP-15872
You must be directly-authenticated to use `/delegate_welcome`.
=> SISRP-15872, delegate_welcome should not be available to users viewing-as

app/controllers/campus_solutions/higher_one_url_controller.rb, app/models/campus_solutions/higher_one_url.rb, app/models/campus_solutions/my_higher_one_url.rb, spec/models/campus_solutions/higher_one_url_spec.rb
https://jira.berkeley.edu/browse/SISRP-15767
https://jira.berkeley.edu/browse/SISRP-15658
Resulting URL from CS will be appropriate to user session.
=> SISRP-15767, HigherOne GET URL API to optional delegate_uid

src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-15948
=> SISRP-15948 - Change the Enrollment Card label for Course Catalog

src/assets/javascripts/angular/services/profileMenuService.js
https://jira.berkeley.edu/browse/SISRP-15842
=> SISRP-15842 - Title IV Authorize Later -- Page Not Found

src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-15970
=> SISRP-15970 - Enrollment card - add 'Edit link'

spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/pages/api_my_academics_page.rb, spec/ui_selenium/pages/my_academics_profile_card.rb, spec/ui_selenium/pages/my_toolbox_page.rb, spec/ui_selenium/user_authorizations_spec.rb
https://jira.berkeley.edu/browse/SISRP-15236
Updates the existing QA test for the academic profile card with new UI elements, new data structure, and new expectations.
=> SISRP-15236 - QA Selenium fixes v74, academic profile

app/models/bearfacts/proxy.rb, app/models/bearfacts/regblocks.rb, app/models/my_academics/college_and_level.rb, app/models/my_academics/exams.rb, app/models/my_academics/gpa_units.rb, app/models/my_academics/regblocks.rb, app/models/my_academics/requirements.rb, app/models/my_academics/telebears.rb, spec/models/bearfacts/exams_spec.rb, spec/models/bearfacts/profile_spec.rb, spec/models/bearfacts/regblocks_spec.rb, spec/models/bearfacts/schedule_spec.rb, spec/models/bearfacts/telebears_spec.rb, spec/models/my_academics/exams_spec.rb, spec/models/my_academics/regblocks_spec.rb, spec/models/my_academics/requirements_spec.rb, spec/models/my_academics/telebears_spec.rb, spec/support/proxy_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6230
=> CLC-6230 Guard Bearfacts proxies against calls with CS IDs

app/models/campus_solutions/enrollment_term.rb, spec/controllers/campus_solutions/enrollment_term_controller_spec.rb, spec/models/campus_solutions/enrollment_term_spec.rb
https://jira.berkeley.edu/browse/SISRP-15749
=> SISRP-15749 Force CS enrollment terms to display year-last

src/assets/templates/widgets/profile/contact_address_editor.html
https://jira.berkeley.edu/browse/SISRP-16001
=> SISRP-16001 - Changing Country still allows State field edits, even for countries without States

app/models/links/my_campus_links.rb, spec/models/links/my_campus_links_spec.rb
https://jira.berkeley.edu/browse/SISRP-15960
Includes:
* a spec that tests only ex-student scenarios
* code cleanup
=> SISRP-15960, My Campus and Financial Resources links are not showing for ex-students

src/assets/templates/widgets/toolbox/delegate_students.html
https://jira.berkeley.edu/browse/SISRP-15507
=> SISRP-15507, better messaging on delegate_students card

app/models/campus_solutions/higher_one_url.rb, spec/models/campus_solutions/higher_one_url_spec.rb
https://jira.berkeley.edu/browse/SISRP-15767
Correction based on Babu's latest comment in https://jira.berkeley.edu/browse/SISRP-15658  cc: @christianvuerings
=> SISRP-15767, Campus Solutions wants UID, not CS_ID

app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-12475
=> SISRP-12457 Add CS holds expiry to event notification listener

src/assets/templates/widgets/advisor/resources.html
https://jira.berkeley.edu/browse/SISRP-15529
=> SISRP-15529 - Add Deep Link to Advising Resources Card

config/torquebox.rb
https://jira.berkeley.edu/browse/SISRP-16100
Balance the load!
=> SISRP-16100 Run JmsWorker on all nodes

config/torquebox.rb
Revert #5041 (https://jira.berkeley.edu/browse/SISRP-16100) at least while work on https://jira.berkeley.edu/browse/SISRP-16120 continues.
=> SISRP-16100 Revert JmsWorker to singleton mode

config/settings.yml, spec/ui_selenium/pages/google_page.rb, spec/ui_selenium/util/web_driver_utils.rb
https://jira.berkeley.edu/browse/SISRP-15236
=> SISRP-15236: QA test fixes

app/controllers/application_controller.rb, app/controllers/user_api_controller.rb, app/models/hub_edos/my_student.rb, app/models/user/api.rb, app/policies/authentication_state.rb, lib/cache/related_cache_key_tracker.rb, spec/controllers/config_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-16046
This is a stopgap to fix some critical QA issues. I will follow up with JIRAs to:
* Clean up and consolidate the many flavors of feed filtering.
* Check for redundant Photo caching.
=> SISRP-16046 Fix expiration of View-As caches

src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-16199
=> SISRP-16199 - Better messaging for continuing students in - Finaid

app/controllers/bootstrap_controller.rb
https://jira.berkeley.edu/browse/SISRP-16120
Partial revert of #5042.
=> SISRP-16120 Restore ucUpdateCache param check for finaid, enrollment

spec/models/campus_solutions/deposit_spec.rb
https://jira.berkeley.edu/browse/SISRP-13071
Removing one squeaky wheel at a time...
=> SISRP-13071 Disable Deposit test pending restored test data

spec/ui_selenium/pages/my_academics_teaching_card.rb, src/assets/templates/academics_teaching.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6220
Low-hanging fruit for something which has been complained about in public...
=> CLC-6220 Broaden text description of academic employee status

app/models/calnet_ldap/user_attributes.rb, spec/models/calnet_ldap/user_attributes_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5055 .
Please do not merge until we get an OK from @johncrossman and @pfarestveit .
=> QA CLC-6238 Display CalNet Directory first/last names as determined by user

src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-15276
=> SISRP-15276: Advisor View As: popover photo is being cached across view-as sessions

app/models/campus_solutions/my_terms_and_conditions.rb, src/assets/javascripts/angular/controllers/pages/finaidController.js
https://jira.berkeley.edu/browse/SISRP-16318
=> SISRP-16318 - Checklist not immediately showing in FA Comms after signing T&Cs

app/models/campus_solutions/my_terms_and_conditions.rb, src/assets/javascripts/angular/controllers/pages/finaidController.js
https://jira.berkeley.edu/browse/SISRP-16318
See jira - this has been verified by Steve McGabe
=> SISRP-16318 QA - Checklist not immediately showing in FA Comms after signing T&Cs

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6236
32 feature flags with more to come. Let's tidy them up just a bit.
=> CLC-6236, YAMLs: feature flags at end-of-file, alpha order

src/assets/templates/widgets/delegate/linking.html
https://jira.berkeley.edu/browse/SISRP-15856
=> SISRP-15856 - Delegated Access: entering excessively long strings for token and email causes CS SQL error

src/assets/javascripts/angular/services/profileMenuService.js
https://jira.berkeley.edu/browse/SISRP-16343
=> SISRP-16343 - Profile is not editable for new admits

src/assets/javascripts/angular/services/profileMenuService.js
https://jira.berkeley.edu/browse/SISRP-16343
=> SISRP-16343 QA - Profile is not editable for new admits

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-16284
Having HTTP response time in stdout was helpful during recent Hub problems.
=> NOJIRA, HTTP response time to stdout in case of further CS/Hub performance problems

src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-15276
QA branch
master PR https://github.com/ets-berkeley-edu/calcentral/pull/5057
=> qa-SISRP-15276 - Advisor View As: popover photo is being cached across view-as sessions

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-16301
QA branch
master PR https://github.com/ets-berkeley-edu/calcentral/pull/5060
=> qa-SISRP-16301 - Academic Profile: "Earned Units" label showing when there are no units yet

app/models/calnet_ldap/user_attributes.rb, lib/safe_utf8_encoding.rb, spec/lib/safe_utf8_encoding_spec.rb, spec/models/calnet_ldap/user_attributes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6243
=> CLC-6243 Handle special characters from Calnet LDAP

src/assets/templates/widgets/profile/editable_soon.html
https://jira.berkeley.edu/browse/SISRP-16406
=> SISRP-16406 - Profile: "this will be editable in April 2016" is not true

app/models/calnet_ldap/user_attributes.rb, lib/safe_utf8_encoding.rb, spec/lib/safe_utf8_encoding_spec.rb, spec/models/calnet_ldap/user_attributes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6243
QA version of #5075.
=> [QA] CLC-6243 Handle special characters from Calnet LDAP

src/assets/templates/widgets/profile/editable_soon.html
https://jira.berkeley.edu/browse/SISRP-16406
QA branch
master PR at https://github.com/ets-berkeley-edu/calcentral/pull/5074
=> QA-SISRP-16406 - Profile: "this will be editable in April 2016" is not true

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, src/assets/templates/widgets/advisor/resources.html
https://jira.berkeley.edu/browse/SISRP-16453
=> SISRP-16453 - Advising Resources: Remove Update Semester Study List

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/plan_law.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-16496
=> SISRP-16496 - Enrollment card - Make Law specific changes

src/assets/templates/widgets/finaid_summary.html, src/assets/templates/widgets/finaid_summary_fundingoffered.html
https://jira.berkeley.edu/browse/SISRP-15844
=> SISRP-15844 - FinAid/Scholarships Clickable Pane Missing Title Text

src/assets/stylesheets/_myfinances.scss, src/assets/templates/cars_summary.html
https://jira.berkeley.edu/browse/SISRP-16500
=> SISRP-16500 - Retrofit CARS Activity Front-end for transition, incorporating feature flag

config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6245
=> CLC-6245 New CalCentral introductory video

spec/ui_selenium/my_academics_data_status_blocks_spec.rb, spec/ui_selenium/my_finances_finaid_profile_spec.rb, spec/ui_selenium/my_finances_finaid_summary_spec.rb, spec/ui_selenium/my_profile_basic_info_spec.rb, spec/ui_selenium/pages/api_cs_fin_aid_data_page.rb, spec/ui_selenium/pages/google_page.rb, spec/ui_selenium/pages/my_academics_teaching_card.rb, spec/ui_selenium/pages/my_dashboard_tasks_card.rb, spec/ui_selenium/pages/my_finances_financial_aid_page.rb, spec/ui_selenium/pages/my_finances_pages.rb, spec/ui_selenium/pages/my_profile_page.rb
Misc Selenium test fixes and updates.
=> SISRP-16530 - QA test fixes in v75

src/assets/templates/academics.html
https://jira.berkeley.edu/browse/SISRP-16495
=> SISRP-16495 - Hide the 'Class Enrollment SUMMER 2016' & 'Final Exam Schedule' for Law students

app/models/berkeley/term_codes.rb, app/models/campus_oracle/connection.rb, app/models/edo_oracle/connection.rb, app/models/edo_oracle/queries.rb, config/database.yml, config/settings.yml, lib/oracle_base.rb, spec/models/berkeley/term_codes_spec.rb, spec/models/campus_oracle/queries_spec.rb, spec/models/edo_oracle/queries_spec.rb, spec/support/oracle_shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-14768
* Establishes OracleBase to share logic between Oracle modules
* Introduces EdoOracle classes
* Migrates shared logic to OracleBase from CampusOracle::Connection
* Adds EDO Term conversion methods to Berkeley::TermCodes
=> SISRP-14768 - Retrofit preparation

spec/ui_selenium/my_dashboard_canvas_course_sites_spec.rb, spec/ui_selenium/pages/my_dashboard_tasks_card.rb
=> SISRP-16530 - QA test fixes for Google tasks and Canvas course sites

src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-16653
=> SISRP-16653 - My Finances Page Gap

src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/javascripts/angular/factories/financesFactory.js, src/assets/templates/billing_details.html, src/assets/templates/myfinances.html, src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-16476
=> SISRP-16476 - Create Billing Summary Front-End

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-16714
=> SISRP-16714 EdoDb: create enrolled sections query

src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-13552
=> SISRP-13552 - Add column head "Due" to sections "Today" and "Future"

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-16579
Sample from curl_stdout.log:
````
200 HTTP status
Total time (seconds): 0.171
URL: https://bpr-test.calnet.berkeley.edu/registry-service/api/v1/identifiers/CAMPUS_SOLUTIONS_ID/25129630
Response body: /Users/john/Projects/github/johncrossman/calcentral/log/sis_api_test_2016-03-22_123315/calnet_crosswalk/_CAMPUS_SOLUTIONS_ID_25129630.log\n
200 HTTP status
Total time (seconds): 0.168
URL: https://bpr-test.calnet.berkeley.edu/registry-service/api/v1/identifiers/LEGACY_SIS_STUDENT_ID/25129630
Response body: /Users/john/Projects/github/johncrossman/calcentral/log/sis_api_test_2016-03-22_123315/calnet_crosswalk/_LEGACY_SIS_STUDENT_ID_25129630.log\n
````
=> SISRP-16579, write cURL output to file and stdout gets path to response content

app/models/edo_oracle/queries.rb, spec/models/edo_oracle/queries_spec.rb
https://jira.berkeley.edu/browse/SISRP-16708
=> SISRP-16708 - Adding spec for EdoOracle::Queries.get_sections_from_ids

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/stylesheets/_enrollment_card.scss, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/plan_law.html
https://jira.berkeley.edu/browse/SISRP-16114
=> SISRP-16114 - 1) Law specific links in CC

src/assets/templates/widgets/advisor/resources.html
=> SISRP-16435 - Add 2 links to the Advising Resources for GL 5.2

app/models/edo_oracle/queries.rb, spec/models/edo_oracle/queries_spec.rb
https://jira.berkeley.edu/browse/SISRP-16714
=> SISRP-16714 Add comments and specs for instructing and enrolled section queries

app/models/berkeley/cal_residency.rb, spec/models/berkeley/cal_residency_spec.rb
https://jira.berkeley.edu/browse/SISRP-16719
=> SISRP-16719 - Status Holds and Blocks Card - Residency update

spec/ui_selenium/my_academics_data_status_blocks_spec.rb, spec/ui_selenium/pages/google_page.rb, spec/ui_selenium/pages/my_profile_bconnected_card.rb
=> SISRP-16530 - fix a few QA test timeouts

spec/ui_selenium/my_finances_ui_landing_page_spec.rb, spec/ui_selenium/my_profile_basic_info_spec.rb, spec/ui_selenium/my_profile_contact_info_spec.rb, spec/ui_selenium/pages/my_finances_pages.rb
Oski is no longer reliable as a test user, and I don't want to use real student data for test runs on a server.
=> SISRP-16530 - stop nightly run of QA profile tests

src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-16940
=> SISRP-16940 - Law Enrollment Card - change Appointment Start Times text

app/models/edo_oracle/queries.rb, spec/models/edo_oracle/queries_spec.rb, spec/spec_helper.rb, spec/support/custom_matchers.rb
https://jira.berkeley.edu/browse/SISRP-16711
=> SISRP-16711 - Adds EdoOracle::Queries.get_section_instructors

app/controllers/student_overview_controller.rb, app/models/campus_solutions/student_lookup_feature_flagged.rb, app/models/user/aggregated_attributes.rb, app/models/user/api.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, spec/controllers/student_overview_controller_spec.rb, spec/models/user/aggregated_attributes_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/advisorStudentOverviewController.js, src/assets/javascripts/angular/factories/advisorStudentOverviewFactory.js, src/assets/templates/advisor_student_overview.html, src/assets/templates/widgets/advisor/student_profile.html
Includes:
* groundwork for Advisor's student_overview page
* `aggregated_attributes` becomes a proper feed with camelCase keys
=> SISRP-15118, advisor_student_overview page and initial student summary widget

app/controllers/my_activities_controller.rb, app/controllers/my_tasks_controller.rb, app/models/my_activities/merged.rb, app/models/my_tasks/merged.rb, spec/controllers/my_activities_controller_spec.rb, spec/controllers/my_tasks_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-16726
=> SISRP-16726 Filter FinAid Communications for delegates

script/sis/verify_sis_api_endpoints.sh
New endpoint: `/BILLING_API/get?EMPLID=`
`echo_usage()` moved up to serve as both function and script documentation.
=> NOJIRA, add cs_billing endpoint to verify_sis_api_endpoints script

app/models/berkeley/grade_options.rb, app/models/berkeley/terms.rb, app/models/campus_oracle/user_courses/base.rb, app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb, app/models/my_academics/academics_module.rb, app/models/my_academics/semesters.rb, app/models/my_academics/teaching.rb, app/models/my_classes/campus.rb, spec/models/berkeley/grade_options_spec.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/my_academics/semesters_spec.rb, spec/models/my_academics/teaching_spec.rb, spec/models/my_classes/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-16879
https://jira.berkeley.edu/browse/SISRP-16880
=> SISRP-16879 SISRP-16880 Adapt My Academics and My Classes to incorporate EdoOracle

src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-13552
:warning: **NOTE** Handle with care, this is a QA PR
=> SISRP-13552 QA - Add column head "Due" to sections "Today" and "Future"

app/models/calnet_ldap/client.rb
https://jira.berkeley.edu/browse/SISRP-16961
https://jira.ets.berkeley.edu/jira/browse/CLC-6239
This is for use in a new User::BulkBasicAttributes class which would fill any gaps in CampusOracle::Queries.get_basic_people_attributes results.
=> SISRP-16961 Add bulk CalNet LDAP query

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/stylesheets/_enrollment_card.scss, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/plan_law.html, src/assets/templates/widgets/enrollment_card.html
Combines all the QA PRs for the LAW changes to the enrollment card:
* SISRP-16496 - Enrollment card - Make Law specific changes
https://jira.berkeley.edu/browse/SISRP-16496
* SISRP-16114 - 1) Law specific links in CC
https://jira.berkeley.edu/browse/SISRP-16114
* SISRP-16940 - Law Enrollment Card - change Appointment Start Times text
https://jira.berkeley.edu/browse/SISRP-16940
:warning: **NOTE** Handle with care, this is a QA PR
=> SISRP-16496 / SISRP-16114 / SISRP-16940 - QA PR

app/models/berkeley/cal_residency.rb, spec/models/berkeley/cal_residency_spec.rb
https://jira.berkeley.edu/browse/SISRP-16719
:warning: **NOTE** Handle with care, this is a QA PR
=> SISRP-16719 QA - Status Holds and Blocks Card - Residency update

app/models/edo_oracle/user_courses/base.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.berkeley.edu/browse/SISRP-16880
=> SISRP-16880 EDO DB knows no Booleans

app/controllers/student_overview_controller.rb, spec/controllers/student_overview_controller_spec.rb, src/assets/javascripts/angular/controllers/pages/advisorStudentOverviewController.js, src/assets/templates/academics.html, src/assets/templates/academics_semester.html, src/assets/templates/advisor_student_overview.html, src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-16750
`MyAcademics::Exams` added to feed for Student Overview page. Includes move of `academics_final_exam_schedule.html` to widgets dir.
=> SISRP-16750, Advisor student overview page: exam schedule

spec/ui_selenium/my_academics_data_status_blocks_spec.rb, spec/ui_selenium/pages/my_academics_status_and_blocks_card.rb
https://jira.berkeley.edu/browse/SISRP-16719
=> SISRP-16719 - QA residency test update

app/models/calnet_ldap/client.rb, app/models/calnet_ldap/user_attributes.rb, spec/models/calnet_ldap/client_spec.rb, spec/models/calnet_ldap/user_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-16961
=> SISRP-16961 Allow CalnetLdap::UserAttributes to return results in bulk

spec/ui_selenium/pages/api_cs_fin_aid_data_page.rb
=> SISRP-16530 - fix QA FinAid test

app/controllers/application_controller.rb, app/controllers/campus_solutions/campus_solutions_controller.rb, app/controllers/campus_solutions/college_scheduler_controller.rb, src/assets/javascripts/angular/services/userService.js, src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-17144
=> SISRP-17144 Do not create unusable link to Schedule Planner

app/models/user/basic_attributes.rb, spec/models/user/basic_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-16961
=> SISRP-16961 User::BasicAttributes module and spec

spec/ui_selenium/my_profile_basic_info_spec.rb, spec/ui_selenium/user_authentication_spec.rb, spec/ui_selenium/user_authorizations_spec.rb, spec/ui_selenium/user_delegated_access_spec.rb
=> SISRP-16530 - misc QA test fixes

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-15857
=> SISRP-15857 EDO DB: Fix instructor and secondary-section queries

spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/my_academics_data_final_grades_spec.rb, spec/ui_selenium/pages/api_my_academics_page_semesters.rb, spec/ui_selenium/pages/my_academics_classes_card.rb, spec/ui_selenium/pages/my_academics_final_grades_card.rb, spec/ui_selenium/pages/my_academics_gpa_calc_card.rb, spec/ui_selenium/user_delegated_access_spec.rb
https://jira.berkeley.edu/browse/SISRP-16536
New Selenium test to verify presentation on the Final Grades and GPA Calculator cards and to support academics retrofit testing.  Does not include functional testing of the GPA Calc card, which will be added when there's time to do it.
=> SISRP-16536 - QA test for Final Grades, GPA Calc cards

src/assets/javascripts/angular/controllers/widgets/sir/sirItemReceivedController.js
Followup to https://github.com/ets-berkeley-edu/calcentral/pull/5160/files/91fc7fe959e0e3e9110529cb3e03591997257db2#r58232370
=> SISRP-17213 Fix code style violation

app/models/canvas_csv/site_memberships_maintainer.rb, app/models/canvas_lti/sis_adapter.rb, app/models/edo_oracle/queries.rb, spec/models/canvas_lti/sis_adapter_spec.rb
https://jira.berkeley.edu/browse/SISRP-17254
=> SISRP-17254 - Retrofit CanvasCsv::SiteMembershipsMaintainer

app/models/berkeley/course_policy.rb, app/models/rosters/campus.rb, spec/models/berkeley/course_policy_spec.rb, spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-17267
=> SISRP-17267 Incorporate EdoOracle into roster viewing permissions

app/models/edo_oracle/course_sections.rb, app/models/edo_oracle/query_caching.rb, app/models/edo_oracle/user_courses/all.rb, app/models/edo_oracle/user_courses/base.rb, app/models/edo_oracle/user_courses/selected_sections.rb, spec/models/edo_oracle/course_sections_spec.rb, spec/models/edo_oracle/user_courses/all_spec.rb
https://jira.berkeley.edu/browse/SISRP-17304
This PR patches points of failure in the higher-level EdoOracle classes. Other classes that directly access EdoOracle::Queries will want similar protection.
=> SISRP-17304 Handle EDO DB errors

src/assets/javascripts/angular/controllers/pages/advisingStudentController.js, src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js, src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js, src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js, src/assets/javascripts/angular/services/profileService.js, src/assets/stylesheets/_profile.scss, src/assets/templates/advising_student.html, src/assets/templates/widgets/advisor/student_profile.html
Advising-student-overview page is done except for photo on student profile card.
* `fixFormattedAddresses` util is used in three different spots so I made it a reusable function in profileService
=> SISRP-15118, advising student profile card with photo_unavailable_bear

src/assets/templates/academics_classinfo.html, src/assets/templates/faculty-resources.html
https://jira.berkeley.edu/browse/SISRP-17261
=> SISRP-17261 - UX Develop: Dashboard (faculty) - Faculty Resources

src/assets/javascripts/angular/controllers/pages/advisingStudentController.js, src/assets/templates/advising_student.html, src/assets/templates/widgets/advisor/student_profile.html
Removed `alt` from div as requested by @christianvuerings in PR #5167 
Notice: The included `delegate_student_img.html` expects `student.fullName` when rendering alt text on photo_unavailable_bear. This PR does the necessary naming change in advisingStudentController.js.
=> SISRP-15118, leverage the img alt text in delegate_student_img.html

app/models/user/aggregated_attributes.rb, app/models/user/api.rb
First installment of https://jira.berkeley.edu/browse/SISRP-17104 .
NOTE: The commit messages are longer than the code changes. I expect that pattern to continue!
=> SISRP-17104 Fixes to User::Api caching

src/assets/templates/widgets/profile/information_disclosure.html
https://jira.berkeley.edu/browse/SISRP-16006
=> SISRP-16006 - FERPA display message text needs confirmation

src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-17478
=> SISRP-17478 Relabel 'earned units' as 'cumulative units'

app/models/berkeley/colleges.rb, spec/models/berkeley/colleges_spec.rb
https://jira.berkeley.edu/browse/SISRP-17477
=> SISRP-17477 Do not translate GRAD DIV affiliation for profile

app/models/my_academics/college_and_level.rb, fixtures/json/hub_academic_status.json, fixtures/json/hub_student.json, spec/models/my_academics/college_and_level_spec.rb
https://jira.berkeley.edu/browse/SISRP-17476
=> SISRP-17476 Parse minors from Hub academic status

app/controllers/advising_student_controller.rb, app/models/hub_edos/academic_status.rb, app/models/hub_edos/my_student.rb, app/models/hub_edos/proxy.rb, app/models/my_academics/college_and_level.rb, app/models/my_academics/filtered_for_delegate.rb, app/models/my_academics/gpa_units.rb, app/models/my_academics/merged.rb, app/models/my_academics/transition_term.rb, app/models/user/photo.rb, config/settings.yml, spec/controllers/advising_student_controller_spec.rb, src/assets/javascripts/angular/controllers/pages/advisingStudentController.js
https://jira.berkeley.edu/browse/SISRP-17104
As with part 1, the commit messages tell the story.
=> SISRP-17104 Cache cleanup part 2: MyAcademics

app/models/my_academics/college_and_level.rb, public/dummy/json/academics.json, spec/models/my_academics/college_and_level_spec.rb, src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-17475
=> SISRP-17475 Add 'Terms in Attendance' to CS-sourced academic profile

config/initializers/slow_request_notifications.rb, config/settings.yml
https://jira.berkeley.edu/browse/SISRP-15690
=> SISRP-15690 Log slow /api/my/status requests

app/controllers/concerns/advisor_authorization.rb, app/models/berkeley/user_roles.rb, app/models/calnet_ldap/user_attributes.rb, spec/controllers/concerns/advisor_authorization_spec.rb, spec/models/berkeley/user_roles_spec.rb, spec/models/user/aggregated_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-16933
My added comments in `Berkeley::UserRoles` are a good summary for this PR. I encourage both @raydavis and @paulkerschen to review.
If Jeremy gets back to me with more LDAP groups to consider then I'll submit another PR.
=> SISRP-16933, translate LDAP-group: students-ug-grace to role: recentStudent

src/assets/templates/advising_student.html
https://jira.berkeley.edu/browse/SISRP-16087
This change only applies to `/advising/student` page
=> SISRP-16087, hide univ reqts card from Fall 2016 students (ie, no Bear Facts)

src/assets/javascripts/angular/controllers/pages/advisingStudentController.js, src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/advisor/student_profile.html
https://jira.berkeley.edu/browse/SISRP-17446
User gets:
* error summary
* clickable email address 
* spinner stop via `finally`
=> SISRP-17446, explain why 403 on /advising/student page; clickable email

app/models/canvas_lti/egrades.rb, spec/models/canvas_lti/egrades_spec.rb
https://jira.berkeley.edu/browse/SISRP-17255
=> SISRP-17255 - Retrofit CanvasLti::Egrades

app/models/edo_oracle/course_sections.rb, spec/models/edo_oracle/course_sections_spec.rb
https://jira.berkeley.edu/browse/SISRP-17561
Explain what is meant by REQGA. Also translate 24-hour time to the 12-hour format that CalCentral uses elsewhere.
=> SISRP-17561 Friendlier presentation of class schedules

app/models/edo_oracle/user_courses/base.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.berkeley.edu/browse/SISRP-17520
=> SISRP-17520 Allow directory attributes to override EdoOracle instructor name

src/assets/templates/academics_final_grades.html
https://jira.berkeley.edu/browse/SISRP-16858
=> SISRP-16858 Remove broken link to Bearfacts unofficial transcripts

app/models/google_apps/drive_manager.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6261
Error message should report on `item.id`.
=> CLC-6261, var referenced in error msg does not exist (OEC/Google related)

app/models/edo_oracle/queries.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6260
=> CLC-6260 Use correct department code column in EdoOracle::Queries

app/models/berkeley/user_roles.rb, spec/models/berkeley/user_roles_spec.rb, spec/models/calnet_ldap/user_attributes_spec.rb
... no matter what the expiry date.
https://jira.berkeley.edu/browse/SISRP-16949
=> SISRP-16949 Current-student affiliation now trumps expired-student

src/assets/javascripts/angular/controllers/pages/dashboardController.js
https://jira.berkeley.edu/browse/SISRP-16401
=> SISRP-16401 - Page title missing when redirected to Dashboard

app/models/edo_oracle/course_sections.rb, app/models/edo_oracle/queries.rb, spec/models/edo_oracle/course_sections_spec.rb
https://jira.berkeley.edu/browse/SISRP-17373
=> SISRP-17373 - Academics retrofit: section schedule locations need translations

src/assets/stylesheets/_finaid_summary.scss
https://jira.berkeley.edu/browse/SISRP-13477
=> SISRP-13477 - UX DESIGN: Side Spacing on FinAid Net Cost

src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-17620
Blind PR, since a sticky SSLError keeps me from fully testing locally.
=> SISRP-17620 Replace "0.0" units with "--" in Class Enrollment

src/assets/templates/widgets/finaid_profile.html
https://jira.berkeley.edu/browse/SISRP-13581
=> SISRP-13581 - FinAid accessibility: links/buttons should offer more context

app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.berkeley.edu/browse/SISRP-17622
=> SISRP-17622 De-duplicate repeated secondary sections from EDODb queries

app/models/edo_oracle/user_courses/base.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.berkeley.edu/browse/SISRP-17617
More work in the spirit of #5187.
=> SISRP-17617 Patch more missing values from sparse EDODb rows

app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb, spec/models/edo_oracle/user_courses/base_spec.rb
QA version of #5207, #5209, #5211.
=> [QA] CLC-6260 SISRP-17617 SISRP-17622 EDODb bugfixes

src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/adjust_waitlisted.html
https://jira.berkeley.edu/browse/SISRP-17620
=> SISRP-17620 - Enrollment Card: 0.00 units issue

src/assets/templates/widgets/toolbox/delegate_quick_links.html
https://jira.berkeley.edu/browse/SISRP-17735
=> SISRP-17735, delegated access: new and improved links for parents

src/assets/templates/widgets/toolbox/delegate_quick_links.html
https://jira.berkeley.edu/browse/SISRP-17735
QA PR corresponding to #5213
=> SISRP-17735, [QA branch] delegated access: new and improved links for parents

src/assets/templates/academics_semester.html
QA PR for https://jira.berkeley.edu/browse/SISRP-16495
Apply fix to 'Final Exam Schedule' label on academic semesters template
=> [ QA ] SISRP-16495: hide 'Class Enrollment SUMMER 2016' & 'Final Exam Schedule' for Law students

src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-17360
Had to change the indentation of the HTML to insert a `data-cc-spinner-directive` `div`.
It's good to be back!
=> SISRP-17360 - Create Sort Functionality for Billing Activity

src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-17723
=> SISRP-17723 - Link to Final Exam Calendar

app/models/canvas_csv/site_memberships_maintainer.rb
https://jira.berkeley.edu/browse/SISRP-17647
Adds fault tolerance for enrollment processing when UID not present in campus data
=> SISRP-17647 - Add fault tolerance for enrollment processing when UID not present

app/models/canvas_csv/site_memberships_maintainer.rb
QA PR - equivalent of #5222
https://jira.berkeley.edu/browse/SISRP-17647
=> [QA] SISRP-17647 - Add fault tolerance for enrollment processing when UID not present in campus data

app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb
https://jira.berkeley.edu/browse/SISRP-17616
QA version of #5220.
=> [QA] SISRP-17616 Use translation table when joining class and section by displayName

src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-17767
Also included a tiny little fix to `resetSearch()` that resets the parsed dates as well.
=> SISRP-17767 - Changes to SF transactions in Billing Activity

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsCompareController.js, src/assets/templates/directives/finaid_table.html, src/assets/templates/widgets/finaid_awards_compare_current_prior.html, src/assets/templates/widgets/finaid_awards_compare_netcost.html, src/assets/templates/widgets/finaid_awards_compare_packages.html, src/assets/templates/widgets/finaid_awards_compare_section.html, src/assets/templates/widgets/finaid_awards_compare_summary.html, src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-5136
=> SISRP-5136 - UX Dev: Repackage Compare Card

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-17531
QA version of #5228.
=> [QA] SISRP-17531 Do not allow inactive EDODb courses to sneak through as null rows

src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-17870
Minor fixes to the Billing Activity card concerning when certain amounts should be displayed, discovered after meeting with the Student Financials team.
=> SISRP-17870 - Fixes for Billing Activity

app/controllers/advising_student_controller.rb, app/controllers/concerns/advisor_authorization.rb, app/controllers/search_students_controller.rb, app/models/user/search_users_by_name.rb, config/routes.rb
https://jira.berkeley.edu/browse/SISRP-17462
Follow up on #5226 with associated controller. Plus, cleanup.
=> SISRP-17462, /api/search/students/by_name/:name controller

src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-17723
=> [QA] SISRP-17723: add Final Exam Schedule link to term enrollment card

app/models/campus_solutions/enrollment_term_expiry.rb
https://jira.berkeley.edu/browse/SISRP-17790
This untested change is to be verified on a cluster.
=> SISRP-17790 Expire My Academics semesters on enrollment cache clear

src/assets/templates/widgets/profile/information_disclosure.html
QA PR for https://jira.berkeley.edu/browse/SISRP-16006
=> [QA] SISRP-16006: hide paragraphs with ferpa and calnet directory links

app/models/campus_solutions/enrollment_term_expiry.rb
=> [QA] SISRP-17790 Expire My Academics semesters on enrollment cache clear

app/models/calnet_ldap/user_attributes.rb, spec/models/calnet_ldap/client_spec.rb
https://jira.berkeley.edu/browse/SISRP-16693
Fix Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPMASTER-4071
=> SISRP-17462, Bamboo failure on static method calling module mixin

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-17905
=> SISRP-17905 Correct enrollment-section join in EdoOracle::Queries.get_enrolled_students

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-17905
QA version of #5238.
=> [QA] SISRP-17905 Correct enrollment-section join in EdoOracle::Queries.get_enrolled_students

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-17905
QA version of #5240 - see rationale there. No change in behavior, but removes needless drag on the database.
=> [QA] SISRP-17905 Remove unneeded section join in EdoOracle::Queries.get_enrolled_students

config/settings.yml
https://jira.berkeley.edu/browse/SISRP-17939
Also remove unused cache configuration.
@johncrossman, this would be a v75.1 candidate. Should I also enter a QA PR, or would you rather wait on those?
=> SISRP-17939 Reduce Crosswalk cache lifespan

config/settings.yml
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5245
=> [QA] SISRP-17939 Reduce Crosswalk cache lifespan

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-17984
Latest endpoints, cleanup.
=> SISRP-17984, update verify_sis_api_endpoints script post GL 5.2

app/controllers/advising_student_controller.rb, app/controllers/concerns/advisor_authorization.rb, app/controllers/search_users_controller.rb, spec/controllers/search_users_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-17963
See notes in corresponding master PR #5249
=> [QA] SISRP-17963, advisor auth check in view-as must know diff between UID and SID

src/assets/templates/academics_classinfo.html, src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-17980
move faculty resource links to dashboard
=> SISRP-17980 - 5.3 - Dashboard (Faculty) - Faculty Resources

src/assets/templates/academics_classinfo.html, src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-17980
=> [QA] SISRP-17980: move faculty resource links to dashboard

package.json, script/front-end-test.sh
https://jira.berkeley.edu/browse/SISRP-17974
* Use the same version as on Bamboo
* Make sure Travis installs the correct version too
Follow up from #5253
=> SISRP-17974 - Update front-end dependencies - Follow up

spec/ui_selenium/my_dashboard_canvas_course_sites_spec.rb, spec/ui_selenium/util/web_driver_utils.rb
Minor fixes for Canvas test runs and general test flow control.
=> SISRP-17719 - minor QA test fix

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-17803
QA version of #5255.
=> [QA] SISRP-17803 Filter out blank-ID instructor assignments from EDODb queries

src/assets/stylesheets/_user_search.scss, src/assets/templates/widgets/toolbox/user_search.html
https://jira.berkeley.edu/browse/SISRP-16088
User search widget to be used by Advisors. The Saved and Recent sections will be constructed in future PR.
=> SISRP-16088, user search widget used by Advisors on Dashboard

app/controllers/campus_rosters_controller.rb, app/models/my_academics/merged.rb, spec/controllers/my_academics_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-17933
=> SISRP-17933 Filter GSI teaching data from advisor views

src/assets/templates/dashboard_task_editor.html
https://jira.berkeley.edu/browse/SISRP-18168
=> SISRP-18168 - Tasks: "add" and "cancel" buttons have disappeared

spec/lib/proxies/base_proxy_spec.rb
#5265 was for master and this PR is for QA.
=> [QA] NOJIRA, base_proxy_spec no longer relies on real HTTP call

public/dummy/json/academic_dates.json, src/assets/javascripts/angular/controllers/widgets/academicDatesController.js, src/assets/templates/widgets/toolbox/academic_dates.html
https://jira.berkeley.edu/browse/SISRP-14416
=> SISRP-14416 - 5.4 - Delegated Access - Dashboard (delegate) - Academic Dates and Deadlines

src/assets/stylesheets/_widgets.scss, src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-16645
=> SISRP-16645 - UX Design: Non-hover affordance for expandable items

src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/billingDetailsController.js, src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/javascripts/angular/controllers/widgets/carsController.js, src/assets/stylesheets/_myfinances.scss, src/assets/templates/billing_details.html, src/assets/templates/cars_summary.html, src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-16662
Adding links to both the CARS and CS finances details pages, to each other, for the transition.
Also added `currentTerm` subheadings for certain places designated within the designs.
=> SISRP-16662 - Add Transition Links to Billing Summary and Billing Details Pages

app/models/berkeley/user_roles.rb
https://jira.berkeley.edu/browse/SISRP-18252
Finally got the sample data.
=> SISRP-18252 Include grad students in recentStudent role

app/models/advising/my_advising.rb, app/models/cal1card/my_cal1card.rb, app/models/campus_solutions/my_checklist.rb, app/models/campus_solutions/my_deposit.rb, app/models/campus_solutions/my_higher_one_url.rb, app/models/finaid/merged.rb, app/models/financials/my_financials.rb, config/settings.yml, spec/controllers/my_advising_controller_spec.rb, spec/models/advising/my_advising_spec.rb, spec/models/cal1card/my_cal1card_spec.rb, spec/models/financials/my_financials_spec.rb
https://jira.berkeley.edu/browse/SISRP-18145
Mostly feeds marked for server-side LiveUpdates processing but ignored by client-side logic.
=> SISRP-18145 Fix more misaligned cache configurations

src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-18105
Baby PR to remove "Status" from "Balance" view.
=> SISRP-18105 - Fixes for Billing Activity/Summary Pt.2

app/models/canvas_lti/sis_adapter.rb, app/models/edo_oracle/queries.rb, app/models/edo_oracle/subject_areas.rb, app/models/edo_oracle/user_courses/base.rb, spec/models/canvas_lti/sis_adapter_spec.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/edo_oracle/subject_areas_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.berkeley.edu/browse/SISRP-17640
=> SISRP-17640 Decompress EDODb subject areas for bCourses compatibility

app/controllers/search_users_controller.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/javascripts/angular/controllers/widgets/adminController.js, src/assets/javascripts/angular/controllers/widgets/userSearchController.js, src/assets/javascripts/angular/services/adminService.js, src/assets/stylesheets/calcentral.scss, src/assets/templates/dashboard.html, src/assets/templates/user_overview.html, src/assets/templates/widgets/toolbox/user_preview.html, src/assets/templates/widgets/toolbox/user_search.html, src/assets/templates/widgets/toolbox/user_search_results.html
https://jira.berkeley.edu/browse/SISRP-16088
Highlights:
* Rename `/advising/student/:uid` to more generic `/user/overview/:uid`.
* For advisors, dashboard gets search-users widget.
* Reusable `user_search_results.html` for search results, stored and recent lists.
=> SISRP-16088, saved and recent tab on widget; rename files 'student' to generic 'user'

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/stylesheets/_academics.scss, src/assets/stylesheets/_flexbox.scss, src/assets/stylesheets/_profile.scss, src/assets/stylesheets/_widgets.scss, src/assets/templates/academics_semesters.html, src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-17838
=> SISRP-17838 - 5.4 - My Academics (Students) - Semesters - Enrollment Verification and Transcripts

app/models/my_activities/notification_activities.rb
Fix for the very occasional https://jira.berkeley.edu/browse/SISRP-17947.
=> SISRP-17947 Postgres notifications query requires string UID

spec/ui_selenium/my_finances_data_acct_summary_spec.rb, spec/ui_selenium/my_finances_data_transaction_detail_spec.rb, spec/ui_selenium/my_finances_ui_details_page_spec.rb, spec/ui_selenium/pages/api_my_financials_page.rb
FYI I removed a superfluous conditional, which altered the indentation.  The actual changes are very small.
=> SISRP-17719 - fix QA finances tests

app/models/textbooks/proxy.rb
https://jira.berkeley.edu/browse/SISRP-5504
Hoping this will eliminate an old time-waster...
=> SISRP-5504 Plug leak to live Google in mocked Textbooks test

app/models/my_academics/academics_module.rb, spec/models/my_academics/teaching_spec.rb
https://jira.berkeley.edu/browse/SISRP-18304
=> SISRP-18304 Preserve course titles when merging EDODb cross-listings

src/assets/javascripts/angular/services/adminService.js
=> SISRP-16088, not valid: ('ldap_uid' in user)

app/controllers/cache_controller.rb, spec/controllers/cache_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-18160
If this tests OK on master, I'll ask approval for a QA PR.
=> SISRP-18160 Fix UID conversion from api/cache/warm

spec/ui_selenium/my_dashboard_data_classes_spec.rb, spec/ui_selenium/pages/api_my_status_page.rb, spec/ui_selenium/pages/my_dashboard_faculty_resources_card.rb
https://jira.berkeley.edu/browse/SISRP-17980
=> SISRP-17980 - add QA test coverage for faculty resources links

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/stylesheets/_enrollment_card.scss, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-18009
=> SISRP-18009 - 5.4 - My Academics - Enrollment

app/controllers/cache_controller.rb, spec/controllers/cache_controller_spec.rb, src/assets/stylesheets/_header.scss
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5286
=> [QA] SISRP-18160 Fix UID conversion from api/cache/warm

src/assets/javascripts/angular/controllers/widgets/carsController.js, src/assets/templates/cars_summary.html
https://jira.berkeley.edu/browse/SISRP-18293
Removing infinite spinner, + wrapped link to new CS page in a feature-flagged `div`.
=> SISRP-18293 - My Finances account summary - infinite spinner beneath 'Make Payment'

src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-18009
=> SISRP-18009 - Updates link text from 'Change Grade Base' to 'Change Grading Option'

spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/pages/api_my_advising_page.rb, spec/ui_selenium/pages/api_my_fin_aid_page.rb, spec/ui_selenium/pages/my_academics_classes_card.rb, spec/ui_selenium/pages/my_academics_semesters_card.rb
=> SISRP-17719 - QA test fixes

app/models/calnet_crosswalk/by_uid.rb, app/models/calnet_crosswalk/proxy.rb
https://jira.berkeley.edu/browse/SISRP-18341
=> SISRP-18341 Streamline Crosswalk cache expiration

spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/pages/api_my_badges_page.rb
My test fix for the "enrollment verification" link needs its own fix...
=> SISRP-17719 - QA test fix for law link

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, public/dummy/json/transfer_credit.json, src/assets/javascripts/angular/controllers/widgets/transferCreditController.js, src/assets/javascripts/angular/directives/transferUnitsDirective.js, src/assets/javascripts/angular/factories/transferCreditFactory.js, src/assets/stylesheets/_transfer_credit.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/academics.html, src/assets/templates/widgets/transfer_credit.html, src/assets/templates/widgets/transfer_credit_list_item.html, src/assets/templates/widgets/transfer_credit_type_units.html
https://jira.berkeley.edu/browse/SISRP-15878
=> SISRP-15878 Transfer credits front end and dummy JSON

app/models/campus_oracle/user_attributes.rb, app/policies/authentication_state_policy.rb, spec/models/campus_oracle/user_attributes_spec.rb, spec/models/canvas_lti/site_creation_spec.rb, spec/policies/authentication_state_policy_spec.rb
https://jira.berkeley.edu/browse/SISRP-17203
=> SISRP-17203 Update can_create_canvas_project_site? for new data sources

app/models/campus_solutions/user_search.rb, fixtures/xml/campus_solutions/user_search.xml, spec/models/campus_solutions/user_search_spec.rb
https://jira.berkeley.edu/browse/SISRP-18343
See 'GET User Search' in doc https://docs.google.com/document/d/1fILoxlPJhh22ngJbshCU7AIHUGqco07KbbwpZFuG1q4/edit#
=> SISRP-18343, Campus Solutions proxy for GET User Search

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/enrollment_card.html
No need to check a feed other than the CS EnrollmentTerms for the academic career associated with the term.
=> SISRP-17895 Determine Law status in Class Enrollment from EnrollmentTerms

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-17932
Some DBA-advised tuning, including an alternate enrollments view for use when filtering on UID.
=> SISRP-17932 Optimize EDO DB queries

app/controllers/campus_solutions/billing_controller.rb, spec/controllers/campus_solutions/higher_one_url_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-18446
Wow, thank you all, for making Delegated Access implementation incredibly simple.
=> SISRP-18446 - Implement HigherOne SSO for Delegates for Billing Summary

app/models/campus_solutions/user_search.rb, fixtures/xml/campus_solutions/user_search.xml, spec/models/campus_solutions/user_search_spec.rb
https://jira.berkeley.edu/browse/SISRP-18507
See the Jira linked to the one above for more on data distinctions. Frankie Pun (CS dev) was first to suggest we remove ACAD_COLLEGE.
=> SISRP-18507, CS API mod to UC_CC_USER_LOOKUP: remove ACAD_COLLEGE in favor of ACAD_PROGRAM

src/assets/javascripts/angular/controllers/widgets/tasksController.js, src/assets/javascripts/angular/controllers/widgets/userSearchController.js, src/assets/stylesheets/_buttons.scss, src/assets/stylesheets/_user_search.scss, src/assets/stylesheets/colors.scss, src/assets/templates/widgets/tasks.html, src/assets/templates/widgets/toolbox/user_search.html, src/assets/templates/widgets/toolbox/user_search_results.html
https://jira.berkeley.edu/browse/SISRP-18339
Ready for review.
- This includes an incidental fix to `tasksController.js` which was causing some issues during other testing.
- Star icons are used as content inside of buttons so I put all css for those in `_buttons.css`.
- There is some discrepancy between searched users and saved users, namely the saved state on searched users.  There's a `updateSearchedUserSavedStates()` function in `userSearchController.js` to synchronize the `saved` state in the search tab.
=> SISRP-18339 - 5.4 - Advisor Dashboard, User Lookup: Star icons to save / delete users

app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb, app/models/edo_oracle/user_courses/selected_sections.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.berkeley.edu/browse/SISRP-18304
=> SISRP-18304 EDO DB: Fill in missing course names for cross-listed enrollments

app/models/campus_solutions/academic_profile_feature_flagged.rb, app/models/hub_edos/academic_status.rb, app/models/hub_edos/registrations.rb, app/models/my_academics/college_and_level.rb, app/models/my_academics/gpa_units.rb, config/settings.yml, spec/models/hub_edos/academic_status_spec.rb, spec/models/hub_edos/registrations_spec.rb, spec/support/campus_solutions_helper_module.rb
Simplifying a bit before I start re-complicating...
=> SISRP-17895 Remove cs_academic_profile feature flag

app/models/my_academics/requirements.rb, src/assets/templates/widgets/student_university_requirements.html
https://jira.berkeley.edu/browse/SISRP-18106
=> SISRP-18106 - Updates University Requirements card to support Exempt status

src/assets/javascripts/angular/controllers/widgets/billingController.js
https://jira.berkeley.edu/browse/SISRP-17837
Also just made `parseAmounts()` a bit more "pure" =)
=> SISRP-17837 - Make amounts searchable with dollar signs for Billing Activity

src/assets/javascripts/angular/controllers/widgets/userSearchController.js, src/assets/stylesheets/_buttons.scss, src/assets/stylesheets/_user_search.scss, src/assets/templates/widgets/toolbox/user_search_results.html
https://jira.berkeley.edu/browse/SISRP-18340
Note that "view as" features are removed as well (https://jira.berkeley.edu/browse/SISRP-18350)
=> SISRP-18340 - 5.4 - Advisor Dashboard, User Lookup: 'Show More' when 51 or more results

config/settings.yml, fixtures/ui_selenium/canvasCourses.json, spec/support/selenium_helper.rb, spec/ui_selenium/canvas_course_site_creation_spec.rb, spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/pages/api_my_academics_page_semesters.rb, spec/ui_selenium/pages/canvas_create_course_site_page.rb, spec/ui_selenium/pages/canvas_page.rb, spec/ui_selenium/pages/canvas_site_creation_page.rb, spec/ui_selenium/util/user_utils.rb, spec/ui_selenium/util/web_driver_utils.rb
https://jira.berkeley.edu/browse/SISRP-18368
Basic data-driven Selenium script to generate course sites, along with rudimentary verification of the workflows.
=> SISRP-18368 - basic QA script for bCourses site creation

app/controllers/search_users_controller.rb, src/assets/javascripts/angular/controllers/widgets/userSearchController.js
https://jira.berkeley.edu/browse/SISRP-18584
Search-by-id on advisor-student-lookup and you now get name info.
=> SISRP-18584, search-by-id now returns name info, displayed in search results

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-18615
Added two CS endpoints and cleaned up. Script is more readable and a little smaller.
=> SISRP-18615, GL 5.4 endpoints added to verify-sis script

src/assets/stylesheets/_buttons.scss, src/assets/stylesheets/_widgets.scss, src/assets/templates/widgets/toolbox/user_preview.html, src/assets/templates/widgets/toolbox/user_search_results.html
https://jira.berkeley.edu/browse/SISRP-18520
This PR fixes layout spacing on Student Overview, and fixes star-icon CSS active and focus state in Student Lookup.
=> SISRP-18520 - Advisor Student Overview: contact info addresses need cleaner layout

src/assets/stylesheets/_myfinances.scss, src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-17871
Responsive due dates that hide when view is "small".
=> SISRP-17871 - Implement responsive Due Dates for Billing Activity

src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-18650
=> SISRP-18650 - 5.4 - My Academics (Student) - Enrollment - Textbook Lookup

src/assets/templates/widgets/toolbox/user_search.html, src/assets/templates/widgets/toolbox/user_search_results.html
https://jira.berkeley.edu/browse/SISRP-18661
contains `maxlength` attribute fix for https://jira.berkeley.edu/browse/SISRP-18662
NOTE:  Please merge this __after__ https://github.com/ets-berkeley-edu/calcentral/pull/5322
=> SISRP-18661 - Student lookup, when entered nonstudent UID, page reloads without any message

src/assets/stylesheets/_enrollment_card.scss
https://jira.berkeley.edu/browse/SISRP-18395
=> SISRP-18395 - Enrollment card: section arrows overlap dates

src/assets/stylesheets/_useful.scss, src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-18670
Change proposed here is a CSS class we could reuse, unless there are objections...
=> SISRP-18670 - Student Overview Personal Summary 'View As' text not inline with Student Name

app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb, app/models/my_academics/teaching.rb, app/models/rosters/campus.rb, app/models/rosters/common.rb, public/dummy/json/academics.json, public/dummy/json/campus_rosters.json, spec/models/edo_oracle/queries_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/my_academics/teaching_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-18713
=> SISRP-18713 Add enrollment limits and waitlist positions to queries and feeds

app/models/my_academics/gpa_units.rb, spec/models/my_academics/gpa_units_spec.rb
Another one down. I also modified the CS/Hub logic to obey the existing GPA-as-string API contract.
=> SISRP-17895 Adapt MyAcademics::GpaUnits to end of Bear Facts data

app/controllers/mediacasts_controller.rb, app/models/my_academics/exams.rb, app/models/my_academics/regblocks.rb, app/models/my_academics/requirements.rb, app/models/my_academics/telebears.rb, app/models/my_badges/student_info.rb, spec/models/my_academics/telebears_spec.rb
The idea here is to stave off total disaster rather than to ensure a good UX in Fall 2016. I'll open follow-up tickets for remaining legacy-data mopping chores.
=> SISRP-17895 Add simple end-of-BearFacts protection & lots of TODOs

src/assets/stylesheets/_canvas_base.scss
Fixed CSS priority issue with primary buttons that are anchors
=> CLC-6224 - Fixed CSS priority issue with primary buttons that are anchors

public/dummy/json/academic_dates.json
https://jira.berkeley.edu/browse/SISRP-18486
=> SISRP-18486 - Delegate "academic dates and deadlines" is a rather messy list

app/controllers/my_eft_enrollment_controller.rb, app/models/eft/my_eft_enrollment.rb, config/routes.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, fixtures/json/eft_enrollment.json, spec/models/eft/my_eft_enrollment_spec.rb
https://jira.berkeley.edu/browse/SISRP-18743
Includes some configuration for an EFT proxy that has not yet been developed.
=> SISRP-18743 - Create Back-End for Get EFT Enrollment API using Mock Fixture

public/canvas/canvas-customization.css, public/canvas/canvas-customization.js, src/assets/stylesheets/_canvas_base.scss, src/assets/stylesheets/_canvas_course_manage_official_sections.scss
CLC-6277 - bCourses re-skinning: create a site course list has outsized font (https://jira.ets.berkeley.edu/jira/browse/CLC-6277)
CLC-6279 - bCourses re-skinning: official sections "sections in this course site" nearly busting out of its container (https://jira.ets.berkeley.edu/jira/browse/CLC-6279)
=> bCourses re-skinning bug fixes

app/controllers/search_users_controller.rb
https://jira.berkeley.edu/browse/SISRP-18780
https://jira.berkeley.edu/browse/SISRP-18774
* Remove dupes in post_processing of result set.
* Move `add_user_attributes` such that results of search-by-SID get name info
=> SISRP-18780, apply uniq filter on user-search result set

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-18352
Will update release-specific instructions upon merge.
=> SISRP-18352 - 5.4 My Finances (Student) - Financial Resources

app/models/berkeley/terms.rb, app/models/my_academics/academics_module.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, public/dummy/json/academics.json, public/dummy/json/academics_transition_future_profile.json, public/dummy/json/academics_transition_past_profile_not_registered.json, public/dummy/json/academics_transition_past_profile_registered.json, spec/models/berkeley/terms_spec.rb, spec/models/my_academics/semesters_spec.rb, spec/models/my_academics/teaching_spec.rb
https://jira.berkeley.edu/browse/SISRP-18516
For purposes of the enrollment tab, the front will want to know if a given term is sourced from Campus Solutions; there are probably other purposes in the future.
=> SISRP-18516 Feature flag and feed item for Class Info enrollment tab

app/models/user/search_users_by_name.rb, spec/models/user/search_users_by_name_spec.rb
https://jira.berkeley.edu/browse/SISRP-18746
I don't want to be too fancy here and risk the rejection of valid input. We'll let QA decide if other expected use cases need consideration.
=> SISRP-18746, reject wildcard-only searches

app/models/textbooks/proxy.rb, public/dummy/json/textbooks_details.json, public/dummy/json/textbooks_error.json, spec/models/textbooks/proxy_spec.rb, src/assets/javascripts/angular/controllers/widgets/booklistController.js, src/assets/javascripts/angular/factories/textbookFactory.js, src/assets/templates/academics_booklist.html, src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-18764
=> SISRP-18764 - Update Textbook and Booklist to avoid instructor email overload

src/assets/templates/academics_status_holds_blocks.html, src/assets/templates/california_residency_status.html
https://jira.berkeley.edu/browse/SISRP-17759
Shows the Residency descriptions based on this design for 5.4, https://jira.berkeley.edu/browse/SISRP-16994
=> SISRP-17759: Use Residency descriptions defined in SISRP-16994

spec/ui_selenium/my_academics_data_enrollment_spec.rb, spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/my_academics_data_teaching_spec.rb, spec/ui_selenium/my_finances_finaid_legacy_spec.rb, spec/ui_selenium/my_finances_finaid_summary_spec.rb, spec/ui_selenium/pages/api_cs_aid_years_page.rb, spec/ui_selenium/pages/api_my_academics_page.rb, spec/ui_selenium/pages/api_my_badges_page.rb, spec/ui_selenium/pages/api_my_cal1_card_page.rb, spec/ui_selenium/pages/api_my_fin_aid_page.rb, spec/ui_selenium/pages/api_my_status_page.rb, spec/ui_selenium/pages/canvas_page.rb, spec/ui_selenium/pages/my_academics_classes_card.rb, spec/ui_selenium/pages/my_toolbox_page.rb, spec/ui_selenium/user_delegated_access_spec.rb
=> SISRP-17719 - QA test fixes v76

src/assets/templates/widgets/enrollment_card_summer_2016.html
https://jira.berkeley.edu/browse/SISRP-17171
=> SISRP-17171 - 5.4 - My Academics (Student) - Enrollment - Summer 2016 Card - Add Text

app/controllers/application_controller.rb, app/controllers/search_users_controller.rb, app/models/user/search_users_by_name.rb
https://jira.berkeley.edu/browse/SISRP-18746
I've been introduced to the subtleties of logging level + error handling in `ApplicationController`.  This is a follow up to PR #5344
=> SISRP-18746, do not log an ERROR when client passes bad arg to controller

app/controllers/application_controller.rb, app/controllers/canvas_controller.rb, app/controllers/canvas_course_add_user_controller.rb, app/controllers/canvas_course_grade_export_controller.rb, app/controllers/canvas_course_provision_controller.rb, app/controllers/canvas_lti_controller.rb, app/controllers/canvas_mailing_lists_controller.rb, app/controllers/canvas_project_provision_controller.rb, app/controllers/canvas_rosters_controller.rb, app/controllers/canvas_site_creation_controller.rb, app/controllers/canvas_user_provision_controller.rb, app/controllers/canvas_webcast_recordings_controller.rb, app/controllers/concerns/allow_lti.rb, app/controllers/concerns/session_key.rb, app/controllers/config_controller.rb, app/controllers/sessions_controller.rb, app/controllers/user_api_controller.rb, app/models/user_specific_model.rb, app/policies/authentication_state.rb, spec/controllers/campus_rosters_controller_spec.rb, spec/controllers/canvas_course_provision_controller_spec.rb, spec/controllers/my_classes_controller_spec.rb, spec/controllers/my_groups_controller_spec.rb, spec/controllers/user_api_controller_spec.rb, spec/support/shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6271
Also adds Canvas masquerading ID to my/status feed. (It started being filtered out at some point.)
=> CLC-6271 Include LTI sessions in new controller filters

src/assets/javascripts/angular/controllers/widgets/userSearchController.js
https://jira.berkeley.edu/browse/SISRP-18736
QA version of PR #5360
=> [QA] SISRP-18736, if user search has error then clear previous results

src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
https://jira.berkeley.edu/browse/SISRP-18908
This was just merged to Master, @:
https://github.com/ets-berkeley-edu/calcentral/pull/5359
=> SISRP-18908 - Return Holds Section to Status, Holds, & Blocks (QA PR)

src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/user_overview.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-18744
=> SISRP-18744 - Advisor student overview page needs a better UX while data elements are loading

app/models/user/api.rb, public/dummy/json/status.json, spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-18979
QA version of PR #5368
=> [QA] SISRP-18979, remove hasCanvasAccount which is only used by spec

src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-18941
See QA PR #5367
=> SISRP-18941 - Remove Enrollment Verification and Transcript Links

src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-18941
See Dev PR #5365
=> [QA] SISRP-18941 - Remove Enrollment Verification and Transcript Links

config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6287
https://jira.ets.berkeley.edu/jira/browse/CLC-6289
QA version of PR #5371
=> [QA] CLC-6287 / CLC-6289, bump up cache-expiration on Canvas::MergedUserSites and ServiceAlerts::Merged

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-19015
Straight copy from the equivalent legacy Oracle queries.
=> SISRP-19015 Filter out dropped class enrollments

src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-19014
add Berkeleytime link to schedule of classes
=> SISRP-19014 - GL5.4 - My Academics page - Class Enrollment card - BerkeleyTime feature

app/models/campus_oracle/user_courses/base.rb, app/models/edo_oracle/user_courses/base.rb, app/models/my_classes/campus.rb, public/dummy/json/academics.json, public/dummy/json/academics_transition_future_profile.json, public/dummy/json/academics_transition_past_profile_not_registered.json, public/dummy/json/academics_transition_past_profile_registered.json, public/dummy/json/classes.json, spec/models/campus_oracle/user_courses/all_spec.rb, spec/models/campus_oracle/user_courses/base_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/my_classes/campus_spec.rb, src/assets/javascripts/angular/services/academicsService.js, src/assets/templates/academics_semester_classes.html, src/assets/templates/widgets/my_classes.html
https://jira.berkeley.edu/browse/SISRP-18807
QA version of #5370.
=> [QA] SISRP-18807 Distinguish enrolled courses from zero-position waitlisted courses

config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6287
https://jira.ets.berkeley.edu/jira/browse/CLC-6289
Small steps towards a land of better performance, assuming such a place exists.
=> CLC-6287 / CLC-6289, bump up cache-expiration on Canvas::MergedUserSites and ServiceAlerts::Merged

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-18468
=> SISRP-18468 Filter non-recurring section meetings from EDO DB query

app/models/edo_oracle/queries.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5373
=> [QA] SISRP-19015 Filter out dropped class enrollments

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-18468
QA version of #5380.
=> [QA] SISRP-18468 Filter non-recurring section meetings from EDO DB query

config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6299
QA version of PR #5382
=> CLC-6299, Cal1card::Photo cache.expiration config to 4.hours

app/models/user/api.rb, public/dummy/json/status.json
https://jira.ets.berkeley.edu/jira/browse/CLC-6297
QA version of PR #5384
=> CLC-6297, remove 'canvasEmail' from User::Api

src/assets/templates/academics_status_holds_blocks.html
https://jira.berkeley.edu/browse/SISRP-19022
=> SISRP-19022 - Residency: wrong icons shown for "pending" and "not yet submitted"

app/controllers/advising_student_controller.rb, config/routes.rb, src/assets/javascripts/angular/factories/holdsFactory.js
https://jira.berkeley.edu/browse/SISRP-19036
=> SISRP-19036 - 5.4 Student Overview - Enrollment - Ensure Holds are pulling from Student data, not Advisor

Gemfile
For fake-proxy-under-load-test purposes.
=> [QA] NOJIRA Make Webmock gem available under production RAILS_ENV

app/controllers/advising_student_controller.rb, config/routes.rb, src/assets/javascripts/angular/factories/holdsFactory.js
QA PR of 
https://github.com/ets-berkeley-edu/calcentral/pull/5378
JIRA:
https://jira.berkeley.edu/browse/SISRP-19036
=> [QA] SISRP-19036 - 5.4 Student Overview - Enrollment - Ensure Holds are pulling from Student data, not Advisor

src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-19014
[QA] add Berkeleytime link to schedule of classes
DEV PR https://github.com/ets-berkeley-edu/calcentral/pull/5374
=> [QA] SISRP-19014 - GL5.4 - My Academics page - Class Enrollment card - BerkeleyTime feature

src/assets/templates/academics_status_holds_blocks.html
https://jira.berkeley.edu/browse/SISRP-19020
hide residency block if no residency.code in feed
DEV PR https://github.com/ets-berkeley-edu/calcentral/pull/5377
=> [QA] SISRP-19020 - Residency: Haas EWMBA student showing "California Residency" with blank status

src/assets/templates/academics_status_holds_blocks.html
https://jira.berkeley.edu/browse/SISRP-19022
DEV PR https://github.com/ets-berkeley-edu/calcentral/pull/5376
=> [QA] SISRP-19022 - Residency: wrong icons shown for "pending" and "not yet submitted"

app/controllers/advising_student_controller.rb, app/models/campus_solutions/advising_resources.rb, config/settings.yml, spec/controllers/campus_solutions/advising_resources_controller_spec.rb, src/assets/templates/widgets/advisor/advising_links.html, src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-19058 (remove Academic Planner link on Advising Student Profile card)
QA version of #5393
=> [QA] SISRP-16435, links for Advisors: Multi-Year Academic Planner and Schedule Planner

src/assets/templates/widgets/up_next.html
https://jira.berkeley.edu/browse/SISRP-17920
Note: This is 5.6 change
=> SISRP-17920 - Update bConnected information when a user doesn't have an account yet

src/assets/templates/widgets/profile/address.html, src/assets/templates/widgets/profile/contact_address_editor.html, src/assets/templates/widgets/profile/contact_email_editor.html, src/assets/templates/widgets/profile/contact_phone_editor.html
Master PR:  #5397 
JIRA: 
https://jira.berkeley.edu/browse/SISRP-19184
=> [QA] SISRP-19184 - Profile Contact Info: click edit and data vanishes

src/assets/templates/california_residency_status.html
https://jira.berkeley.edu/browse/SISRP-19070
California Residency status text changes for 5.4
=> SISRP-19070 - SLR: Correcting Language of Status

src/assets/templates/california_residency_status.html
https://jira.berkeley.edu/browse/SISRP-19070
California Residency status text changes for 5.4
master PR https://github.com/ets-berkeley-edu/calcentral/pull/5399
=> [QA] SISRP-19070 - SLR: Correcting Language of Status

src/assets/templates/widgets/toolbox/user_preview.html
This is QA version of PR #5403
=> [QA] SISRP-16435, hide resource links on student overview resource when blank config

src/assets/templates/widgets/toolbox/user_preview.html
Student overview should not surface blank URLs.
=> SISRP-16435, hide resource links on student overview resource when blank config

src/assets/templates/california_residency_status.html
https://jira.berkeley.edu/browse/SISRP-19070?focusedCommentId=360891&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-360891
master PR https://github.com/ets-berkeley-edu/calcentral/pull/5405
=> [QA] SISRP-19070 fix typo and non-resident more info URL

src/assets/templates/california_residency_status.html
https://jira.berkeley.edu/browse/SISRP-19070?focusedCommentId=360891&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-360891
=> SISRP-19070 fix typo and non-resident more info URL

app/models/campus_solutions/advising_resources.rb, config/settings.yml
https://jira.berkeley.edu/browse/SISRP-18949
=> SISRP-18949 - Reconfigures hardcoded linking to include 'UCemplid' for student specific links

src/assets/templates/widgets/profile/work_experience_editor.html
https://jira.berkeley.edu/browse/SISRP-19203
Similar to #5397.
=> SISRP-19203 - Ensure all <select> tags have a closing </select> tag

config/settings.yml, src/assets/templates/widgets/profile/languages.html, src/assets/templates/widgets/profile/languages_section_editor.html
final touches added
expose Languages card in production (if you prefer, I can remove the feature flag from the yml files).
=> SISRP-10777 - 5.6 - Profile Tab - Languages Card - Edit

src/assets/stylesheets/_profile_page.scss
https://jira.berkeley.edu/browse/SISRP-19249
=> SISRP-19249 - Profile info edits - validation errors have become swollen

app/controllers/bootstrap_controller.rb, app/controllers/canvas_lti_controller.rb, spec/controllers/bootstrap_controller_spec.rb, spec/controllers/canvas_lti_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6314
This may not fix all the problems we see in production but it should fix the first bunch.
Since this will be needed in a maintenance release, I'll prepare a QA PR after we check this one out.
=> CLC-6314 Fix LTI / CalCentral clashes

app/models/my_academics/transition_term.rb
https://jira.berkeley.edu/browse/SISRP-19313
The bug is now logging more than 100K errors a day on production.
I'll attach screenshots to the JIRA ticket.
=> SISRP-19313 Do not ask legacy RegStatus API about non-legacy students

app/controllers/bootstrap_controller.rb, app/controllers/canvas_lti_controller.rb, spec/controllers/bootstrap_controller_spec.rb, spec/controllers/canvas_lti_controller_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5416
=> [QA] CLC-6314 Fix LTI / CalCentral clashes

app/models/my_academics/transition_term.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5418
=> [QA] SISRP-19313 Do not ask legacy RegStatus API about non-legacy students

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/widgets/enrollment/adjust_enrolled.html, src/assets/templates/widgets/enrollment/adjust_waitlisted.html
https://jira.berkeley.edu/browse/SISRP-16115
Taken directly from @christianvuerings 's [branch](https://github.com/christianvuerings/calcentral/tree/SISRP-16115) =)
Groups enrolled/waitlisted classes by academic career.
=> SISRP-16115 - Dual / Multi Career students in CalCentral

src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-19389
=> SISRP-19389 - Remove 'Schedule Planner' link from Advising Resources Widget

app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-19435
=> SISRP-19435 - Adds EMPLID value to 'Schedule Planner' link in Personal Summary Card

src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-19388
=> SISRP-19388 - Update 'Multi-Year Planner' link to open in a new window

app/models/campus_solutions/advising_resources.rb, config/settings.yml
https://jira.berkeley.edu/browse/SISRP-18949
See #5411 for DEV PR
=> [QA] SISRP-18949 - Reconfigures hardcoded linking to include 'UCemplid' for student specific links

src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-19389
See #5423 for DEV PR
=> [QA] SISRP-19389 - Remove 'Schedule Planner' link from Advising Resources Widget

src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-19388
See #5428 for DEV PR
=> [QA] SISRP-19388 - Update 'Multi-Year Planner' link to open in a new window

app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-19435
See #5429 for DEV PR
=> [QA] SISRP-19435 - Adds EMPLID value to 'Schedule Planner' link in Personal Summary Card

app/models/campus_solutions/advising_resources.rb, config/settings.yml, spec/controllers/campus_solutions/advising_resources_controller_spec.rb, src/assets/templates/widgets/advisor/advising_links.html, src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-19386
See #5434 for DEV PR
=> [QA] SISRP-19386 - Advisor Resource Link updates

config/settings.yml
https://jira.berkeley.edu/browse/SISRP-19892
=> SISRP-19892 - cs_profile_languages feature flag should default to false until the GL 5.6 sprint

script/start-torquebox.sh
https://jira.berkeley.edu/browse/SISRP-19471
Based on my reading, this is very unlikely to be the cause of our recent systemic failures, but it may decrease their frequency while we investigate the real problem.
QA first, given the schedule.
=> [QA] SISRP-19471 Increase ReservedCodeCacheSize for Torquebox

spec/ui_selenium/pages/canvas_page.rb, spec/ui_selenium/pages/canvas_site_creation_page.rb, spec/ui_selenium/pages/my_profile_contact_info_card.rb
https://jira.berkeley.edu/browse/SISRP-19166
=> SISRP-19166 - small QA test fixes

app/models/campus_solutions/advising_resources.rb, config/settings.yml, src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-19390
NOTE: This is no longer slated for GL 5.4b. Rich Meyer has confirmed that this is being pushed to another GL (5.6?)
=> SISRP-19390 - 5.6 - Advising Resources - Add WebNow Documents link

script/bamboo-tests.sh, script/build-torquebox.sh, script/export-cached-csv-enrollments-set.sh, script/refresh-all-canvas-enrollments.sh, script/refresh-canvas-enrollments.sh, script/refresh-canvas-users.sh, script/start-torquebox.sh
https://jira.berkeley.edu/browse/SISRP-19471
=> SISRP-19471 Increase ReservedCodeCacheSize; remove pre-Java-8 options

app/models/campus_solutions/fpp_enrollment.rb, spec/controllers/campus_solutions/fpp_enrollment_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-19921
* Fixture is exactly the same!
=> SISRP-19921 - Add FPP Proxy Information, Update Back-End for Actual Response

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-19916
Two more endpoints to verify. This is a do-over of closed PR #5442
=> SISRP-19916, verify-sis-api script gets UC_SF_FPP_LINKS_GET and Hub:/registrations

app/controllers/user_api_controller.rb, config/routes.rb, spec/controllers/user_api_controller_spec.rb, spec/features/act_as_user_spec.rb, spec/ui_selenium/pages/cal_central_pages.rb, spec/ui_selenium/user_authentication_spec.rb, src/assets/javascripts/angular/services/userService.js, src/assets/templates/footer.html
https://jira.berkeley.edu/browse/SISRP-19724
Nostalgic but distracting.
=> SISRP-19724 Remove long-obsolete code for "opt-out" no-op

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-18674
Adds a couple of new links, and updates a couple of older ones.
=> SISRP-18674 - Update Current List of Campus Links (Financial)

lib/top_h_parser.rb, script/memcached-stats.sh, script/performance-dump.sh, spec/lib/top_h_parser_spec.rb
https://jira.berkeley.edu/browse/SISRP-19471
https://jira.ets.berkeley.edu/jira/browse/CLC-6325
I'll start a Confluence page explaining how to use all this later today, but we definitely want data-gathering support in place before next week's load tests.
=> SISRP-19471 Support analysis of emergency / QA performance issues

app/models/my_academics/college_and_level.rb, fixtures/json/hub_academic_status.json, spec/models/my_academics/college_and_level_spec.rb, src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-19237
* Adds 'fpf' role to collegeAndLevel node of Academics feed
* Adds academic plan codes to college and level node of Academics feed
* Displays alternative set of links relevant to FPF students
=> SISRP-19237 - FPF Enrollment Card

src/assets/javascripts/angular/controllers/pages/finaidController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsCompareController.js, src/assets/javascripts/angular/directives/amountChangeSymbolDirective.js, src/assets/javascripts/angular/directives/finaidTableDirective.js, src/assets/stylesheets/_finaid_compare_awards.scss, src/assets/templates/directives/finaid_table.html, src/assets/templates/widgets/finaid_awards_compare_netcost.html, src/assets/templates/widgets/finaid_awards_compare_packages.html, src/assets/templates/widgets/finaid_awards_compare_summary.html
https://jira.berkeley.edu/browse/SISRP-17880
=> SISRP 17880 - Repackage Compare Card - Show difference with icons / gaps

src/assets/templates/widgets/finaid_awards_compare_widget.html
https://jira.berkeley.edu/browse/SISRP-20520
=> SISRP-20520 Remove duplicate finaid_errored.html include in finaid_awards_compare_widget.html

fixtures/xml/campus_solutions/financial_aid_compare_awards_current.xml, fixtures/xml/campus_solutions/financial_aid_compare_awards_prior.xml, src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsCompareController.js
https://jira.berkeley.edu/browse/SISRP-20521
=> SISRP-20521 Update package fixtures for Finaid Compare Packages Card

Gemfile, Gemfile.lock, app/models/textbooks/proxy.rb, script/start-torquebox.sh
https://jira.berkeley.edu/browse/SISRP-18781
=> SISRP-18781 Re-enable Textbooks API; limit Metaspace memory consumption

app/controllers/campus_solutions/emergency_phone_controller.rb, app/models/campus_solutions/emergency_phone.rb, app/models/campus_solutions/emergency_phone_delete.rb, app/models/campus_solutions/my_emergency_phone.rb, config/routes.rb, fixtures/xml/campus_solutions/emergency_phone_delete.xml, fixtures/xml/campus_solutions/emergency_phone_post.xml, spec/controllers/campus_solutions/emergency_phone_controller_spec.rb, spec/models/campus_solutions/emergency_phone_delete_spec.rb, spec/models/campus_solutions/emergency_phone_spec.rb
https://jira.berkeley.edu/browse/SISRP-19914
- EmergencyPhone#post model _done_
- EmergencyPhone#delete model _done_
- EmergencyPhoneController _done_
=> SISRP-19914 - Dev: emergency contact add / deleting multiple phones - backend prep work

public/canvas/canvas-customization.css
https://jira.ets.berkeley.edu/jira/browse/CLC-6329
=> CLC-6329 - Hide items in bCourses help menu

src/assets/javascripts/angular/services/academicsService.js
Working on SISRP-20271, which is being put on hold for higher priority task assigned to me. Just wanted to contribute these descriptions.
=> [NOJIRA] - Adds some JSDocs to academicService

public/canvas/index.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6328
=> CLC-6328 - Ensure development and test servers point to correct CalCentral instance

app/models/user/api.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js, src/assets/templates/academics.html, src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-20535
Due to time pressure, we'll test on QA first.
=> QA SISRP-20535 All students/applicants with Holds need to reach My Academics

src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js, src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/assets/templates/academics_status_holds_blocks.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-18744
Reverting UX changes due to further downstream UX blockers
=> [QA] Revert SISRP-18744

spec/ui_selenium/canvas_course_site_creation_spec.rb, spec/ui_selenium/my_academics_data_status_blocks_spec.rb, spec/ui_selenium/my_profile_bconnected_spec.rb, spec/ui_selenium/pages/my_dashboard_tasks_card.rb, spec/ui_selenium/user_delegated_access_spec.rb
https://jira.berkeley.edu/browse/SISRP-20678
=> SISRP-20678 - QA test fixes

src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-18744
One more revert - spinner should be on parent element (orphaned) without a card title or widget body
=> QA Revert SISRP-18744 - revert to parent

app/controllers/my_eft_enrollment_controller.rb, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/javascripts/angular/factories/financesLinksFactory.js, src/assets/stylesheets/_lists.scss, src/assets/stylesheets/_text.scss, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-19350
* Since a lot of the code shared the same changes, I merged EFT and FPP into the same commit
* Lots of HTML due to conditional views
* Next on list:  reorder these
=> SISRP-19350 - Add EFT and FPP Links for Financial Resources

src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
https://jira.berkeley.edu/browse/SISRP-20580
=> QA SISRP-20580 Haas/Law student residency with infinite spinner

app/models/user/api.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js, src/assets/templates/academics.html, src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-20535
Master-branch version of https://github.com/ets-berkeley-edu/calcentral/pull/5474
=> SISRP-20535 All students/applicants with Holds need My Academics

src/assets/stylesheets/_finaid_compare_awards.scss, src/assets/templates/widgets/finaid_awards_compare_current_prior.html, src/assets/templates/widgets/finaid_awards_compare_section.html
https://jira.berkeley.edu/browse/SISRP-20522
=> SISRP-20522 Add Key to compare symbols to Compare Packages card

public/dummy/json/campus_rosters.json, src/assets/javascripts/angular/factories/rosterFactory.js, src/assets/stylesheets/_academics.scss, src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-20664
=> SISRP-20587 - 5.6 - My Academics Course Page (Instructor) - Apply 12 column card width

src/assets/stylesheets/_academics.scss, src/assets/templates/academics_classinfo.html, src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-20665
* Updates 'Enrolled' widget as 'Enrollment List'
* Adds notes concerning sortable tables and bMail links
* Adds 2px grey border for style
* Moves "No students are currently ... in this class" and other notice into grey border for visual inclusion in widget
* Changes 'Total' label for student count to 'On List'
=> SISRP-20665 - My Academics (Instructor) Class Page Enrollments - Update card title as 'Enrollment List'

src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-20666
=> SISRP-20666 - 5.6 - Course Page Enrollments section (Instructor) - Apply List and Available count

public/dummy/json/campus_rosters.json, src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-20667
=> SISRP-20667 - Add email addresses to enrollment lists

src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
https://jira.berkeley.edu/browse/SISRP-20580
This is the Master branch PR
QA PR already merged https://github.com/ets-berkeley-edu/calcentral/pull/5477
=> SISRP-20580 Haas/Law student residency with infinite spinner

fixtures/json/hub_demographics.json, fixtures/json/hub_student.json, public/dummy/json/student_with_residency.json, spec/models/hub_edos/demographics_spec.rb, src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
https://jira.berkeley.edu/browse/SISRP-19758
=> SISRP-19758 Display 'official', not 'tuition' residency in CalCentral

src/assets/templates/academics.html, src/assets/templates/academics_semester.html
https://jira.berkeley.edu/browse/SISRP-20508
Either students or instructors might need to see the final exam schedule, but only if the schedule contains something.
=> SISRP-20508 Do not show empty Final Exam Schedule card

fixtures/ui_selenium/profile.json, spec/ui_selenium/my_profile_work_experience_spec.rb, spec/ui_selenium/pages/my_profile_contact_info_card.rb, spec/ui_selenium/pages/my_profile_page.rb, spec/ui_selenium/pages/my_profile_work_experience_card.rb
https://jira.berkeley.edu/browse/SISRP-20493
=> SISRP-20493 - QA test for profile work experience

app/models/my_classes/merged.rb, spec/controllers/my_classes_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-19252
=> SISRP-19252 Filter instructing classes from My Classes under advisor view-as

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-20452
* This template is starting to look pretty gnarly
* Next:  Reorder these links and links pulled from `campusLinks.json`
=> SISRP-20452 - Add 1098-T Tax form and Delegate Access Links to Financial Resources

app/models/campus_solutions/advising_resources.rb, config/settings.yml, src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-19922
=> SISRP-19922 - 5.6 - My Dashboard (Advisor) - Advising Resources

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsCompareController.js, src/assets/templates/widgets/finaid_awards_compare_summary.html
https://jira.berkeley.edu/browse/SISRP-18680
=> SISRP-18680 FinAid Award Comparison Enrollment details unclear

app/models/calendar/preprocessor.rb, app/models/campus_oracle/calendar.rb, spec/models/calendar/calendar_integration_spec.rb, spec/models/calendar/calendar_scaling_spec.rb, spec/models/calendar/preprocessor_spec.rb, spec/models/campus_oracle/calendar_spec.rb
https://jira.berkeley.edu/browse/SISRP-21097
New queries will live in a parallel EdoOracle::Calendar class.
=> SISRP-21079 Move legacy Calendar::Queries to CampusOracle::Calendar

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-20940
* Thanks @redconfetti for pointing me to the directive to use for these CS links.
* This will most probably cause merge conflicts with #5492, if that PR is merged first.  I'll rebase if so.
=> SISRP-20940 - Enroll FPP CS page looses calcentral header

src/assets/stylesheets/_lists.scss, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-21011
* Fixed nested text (that aren't links), and used `data-ng-bind` for scope variables.
=> SISRP-21011 - Fix EFT Status HTML and use data-ng-bind

app/models/edo_oracle/course_sections.rb, spec/models/edo_oracle/course_sections_spec.rb
https://jira.berkeley.edu/browse/SISRP-19992
And un-pend the spec.
=> SISRP-19992 Correctly parse EDO DB locations without room numbers

app/controllers/advising_student_controller.rb, fixtures/json/my_academics_merged.json, public/dummy/json/advising_student_academics.json, spec/controllers/advising_student_controller_spec.rb, src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-20822
When viewing a student's semester card the advisor does not get links to class pages, etc.
=> SISRP-20822, add the Semesters card to the Student Overview page

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js, src/assets/templates/widgets/profile/emergency_phone.html, src/assets/templates/widgets/profile/emergency_phone_fields.html
https://jira.berkeley.edu/browse/SISRP-21140
=> SISRP-21140 - Multiple phones for Emergency Contact should limit to one of each available phone type

src/assets/javascripts/angular/factories/advisingFactory.js, src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-19922
=> SISRP-19922 - Remove 'GTE Forms' link from Advising Resources card

src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-21045
* Only show due date if the API is bringing over `itemDueFlag !== null`
=> SISRP-21045 - Billing Activity : If Due Date is missing then it shows abrupt line ending

app/models/campus_oracle/course_sections.rb, app/models/edo_oracle/course_sections.rb, app/models/edo_oracle/queries.rb, app/models/my_academics/academics_module.rb, fixtures/json/my_academics_merged.json, public/dummy/json/academics.json, public/dummy/json/academics_transition_future_profile.json, public/dummy/json/academics_transition_past_profile_not_registered.json, public/dummy/json/academics_transition_past_profile_registered.json, public/dummy/json/classes.json, spec/models/berkeley/course_policy_spec.rb, spec/models/campus_oracle/course_sections_spec.rb, spec/models/campus_oracle/user_courses/all_spec.rb, spec/models/campus_oracle/user_courses/selected_sections_spec.rb, spec/models/canvas_csv/provide_course_site_spec.rb, spec/models/edo_oracle/course_sections_spec.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/my_academics/semesters_spec.rb, spec/models/my_academics/teaching_spec.rb, spec/support/course_shared_examples.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/services/academicsService.js, src/assets/stylesheets/_academics.scss, src/assets/templates/academics_classinfo.html, src/assets/templates/canvas_embedded/_shared/sections_table.html
https://jira.berkeley.edu/browse/SISRP-18468
Back end at the top, front end at the bottom, and a regrettably large update of tests and test data (including getting all the different My Academics dummies back into alignment) in the middle.
=> SISRP-18468 Expand My Academics class schedules to include one-time meetings

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-20698
Rich confirmed that we these links should be available to all users.
=> SISRP-20698, all users get links to eForms on My Campus

app/models/edo_oracle/queries.rb, app/models/rosters/common.rb, public/dummy/json/academics.json, public/dummy/json/campus_rosters.json, spec/models/edo_oracle/queries_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/canvas_spec.rb, spec/models/rosters/common_spec.rb, src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/stylesheets/_academics.scss, src/assets/stylesheets/_canvas_roster.scss, src/assets/stylesheets/_myfinances.scss, src/assets/stylesheets/_selects.scss, src/assets/stylesheets/_widgets.scss, src/assets/templates/cars_activity.html, src/assets/templates/directives/academics_class_info_enrollment.html, src/assets/templates/oec.html, src/assets/templates/widgets/activity.html, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-20670
=> SISRP-20587 - Course Page Enrollments section - Add 'Email to List' option

app/controllers/advising_student_controller.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, public/dummy/json/advising_resources.json, src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-19922
=> SISRP-19922 - Removing 'cs_advising_gte_forms' feature from Personal Summary Card

app/controllers/campus_solutions/residency_message_controller.rb, app/models/berkeley/residency_message_code.rb, app/models/campus_solutions/residency_message.rb, app/models/hub_edos/demographics.rb, config/routes.rb, fixtures/json/hub_demographics.json, fixtures/xml/campus_solutions/residency_message.xml, spec/controllers/campus_solutions/residency_message_controller_spec.rb, spec/models/berkeley/residency_message_code_spec.rb, spec/models/campus_solutions/residency_message_spec.rb, spec/models/hub_edos/demographics_spec.rb
https://jira.berkeley.edu/browse/SISRP-19374
PR for the Ruby support.  
UI will be in separate PR.
=> SISRP-19374 - 5.6 - Academics - Status, Holds, Blocks - Residency Message Catalog

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js
https://jira.berkeley.edu/browse/SISRP-21186
Always set samePhone and sameAddress to false to allow any address edits.
=> SISRP-21186 - Cannot add new emergency contact for the first time

app/models/hub_edos/demographics.rb, spec/models/hub_edos/demographics_spec.rb, src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js, src/assets/javascripts/angular/factories/residencyMessageFactory.js, src/assets/templates/academics_status_holds_blocks.html, src/assets/templates/california_residency_status.html
https://jira.berkeley.edu/browse/SISRP-19374
PR for the UI portion.
paired with Ruby support PR https://github.com/ets-berkeley-edu/calcentral/pull/5511
=> SISRP-19374 - 5.6 - Academics - Status, Holds, Blocks - Residency Message Catalog - UI

app/models/rosters/campus.rb, public/dummy/json/campus_rosters.json, spec/controllers/campus_rosters_controller_spec.rb, src/assets/templates/academics_classinfo.html, src/assets/templates/widgets/enrollment/consult_advisor.html
https://jira.berkeley.edu/browse/SISRP-21299
=> SISRP-21299 Update campus directory links

app/models/edo_oracle/queries.rb, app/models/rosters/common.rb, public/dummy/json/campus_rosters.json, spec/models/edo_oracle/queries_spec.rb, spec/models/rosters/common_spec.rb, src/assets/javascripts/angular/controllers/pages/rosterController.js, src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/templates/directives/academics_class_info_enrollment.html, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-20671
=> SISRP-20671 - Add 'Export' option

src/assets/templates/widgets/profile/emergency_contact_editor.html, src/assets/templates/widgets/profile/emergency_phone_fields.html
https://jira.berkeley.edu/browse/SISRP-21397
=> SISRP-21397 - Emergency Contacts - it should be possible to de-select a non-required selection

src/assets/templates/widgets/profile/emergency_contact.html
https://jira.berkeley.edu/browse/SISRP-21402
=> SISRP-21402 - Emergency Contacts - "Edit" buttons should be disabled while viewing-as

src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-19068
=> SISRP-19068 Do not show waitlisted primary sections in My Academics semesters overview

package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-6352
=> CLC-6352 Lock down gulp-header to 1.8.2

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js
https://jira.berkeley.edu/browse/SISRP-21404
Fixes default values before edit instead of on save.
=> SISRP-21404 - Emergency Contacts - unable to edit a migrated contact

src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/stylesheets/_academics.scss, src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-20670
=> SISRP-20670 - Applied Copy Addresses feature to replace Email List button

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-21424
=> SISRP-21424 Order multiple section meetings by start date

src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21401
=> SISRP-21401 Disable Make Payment button for act-as

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js
https://jira.berkeley.edu/browse/SISRP-21404
=> SISRP-21404: SISRP-21404 - Emergency Contacts - fix defaultCountry assignment

app/models/edo_oracle/queries.rb, app/models/rosters/campus.rb, app/models/rosters/common.rb, public/dummy/json/campus_rosters.json, spec/models/canvas_csv/term_enrollments_spec.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/common_spec.rb, src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-20669
=> SISRP-20669 - Add 'Terms' column to enrollment lists

src/assets/templates/widgets/profile/languages_section.html
https://jira.berkeley.edu/browse/SISRP-21452
=> SISRP-21452 - Profile Languages: "Add" and "Edit" buttons should be disabled when viewing as

src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-21398
https://jira.berkeley.edu/browse/SISRP-21399
=> SISRP-21398 SISRP-21399 Hide inapplicable financial links in view-as

src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-21396
=> SISRP-21396 Hide 'Delegate Access' financial link from delegates

src/assets/templates/widgets/status_holds_blocks.html
https://jira.berkeley.edu/browse/SISRP-21411
Cosmetic fix with inline style attribute.
=> SISRP-21411 - Residency is no longer properly aligned with reg status

src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-20673
=> SISRP-20673 - Hiding columns in medium and small view

app/models/rosters/common.rb, public/dummy/json/campus_rosters.json, spec/models/rosters/common_spec.rb, src/assets/stylesheets/_canvas_roster.scss, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-20821
=> SISRP-20821 - Adds Terms and Majors to Roster Tab

spec/ui_selenium/my_academics_data_student_semesters_spec.rb, spec/ui_selenium/my_academics_data_teaching_semesters_spec.rb, spec/ui_selenium/pages/api_my_academics_page_semesters.rb, spec/ui_selenium/pages/my_academics_class_page.rb
https://jira.berkeley.edu/browse/SISRP-21535
=> SISRP-21535 - fix and rename QA semesters tests

src/assets/javascripts/angular/controllers/pages/rosterController.js, src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/javascripts/angular/directives/spinnerDirective.js, src/assets/javascripts/angular/services/rosterService.js, src/assets/stylesheets/_useful.scss, src/assets/templates/academics_classinfo.html, src/assets/templates/directives/academics_class_info_enrollment.html, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-20587
See QA PR #5537
=> SISRP-20587 - Adds spinner message for Enrollments/Rosters. Adds email link to names in Rosters.

src/assets/javascripts/angular/controllers/pages/rosterController.js, src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/javascripts/angular/directives/spinnerDirective.js, src/assets/javascripts/angular/services/rosterService.js, src/assets/stylesheets/_useful.scss, src/assets/templates/academics_classinfo.html, src/assets/templates/directives/academics_class_info_enrollment.html, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-20587
See Dev PR #5536
=> [QA] SISRP-20587 - Adds spinner message for Enrollments/Rosters. Adds email link to names in Rosters.

app/models/campus_oracle/queries.rb, app/models/edo_oracle/queries.rb, app/models/rosters/campus.rb, app/models/rosters/canvas.rb, app/models/rosters/common.rb, spec/models/campus_oracle/queries_spec.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/canvas_spec.rb, spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-18649
=> SISRP-18649 Query rosters for all sections of a course in one go

app/models/campus_oracle/queries.rb, app/models/edo_oracle/queries.rb, app/models/rosters/campus.rb, app/models/rosters/canvas.rb, app/models/rosters/common.rb, spec/models/campus_oracle/queries_spec.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/canvas_spec.rb, spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-18649
QA version of #5539.
=> [QA] SISRP-18649 Query rosters for all sections of a course in one go

app/models/campus_solutions/my_higher_one_url.rb, spec/models/campus_solutions/my_higher_one_url_spec.rb
https://jira.berkeley.edu/browse/SISRP-21595
Nothin' from nothin' leaves nothin'.
=> SISRP-21595, do not strip my_higher_one_url when nil

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-21266
* Query arg on UC_CC_USER_LOOKUP was improper 
* Usage info referred to an obsolete environment var
=> SISRP-21266, verify script: fix UC_CC_USER_LOOKUP; improve usage info

src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21371
=> SISRP-21371 - Billing Summary - Negative Balance should say Credit Balance

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js, src/assets/templates/widgets/profile/emergency_phone_fields.html
https://jira.berkeley.edu/browse/SISRP-21187 - The first phone number has no type.
https://jira.berkeley.edu/browse/SISRP-21542 - When all but one type of phone number has been entered, a last one could not be added.
=> SISRP-21187 SISRP-21542 Fix emergency contact phone number issues

src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js, src/assets/templates/widgets/profile/emergency_phone_fields.html
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5546
=> QA SISRP-21187 SISRP-21542 Fix emergency contact phone number issues

src/assets/javascripts/angular/controllers/widgets/profile/workExperienceSectionController.js, src/assets/templates/widgets/profile/work_experience_section.html
https://jira.berkeley.edu/browse/SISRP-21453
https://jira.berkeley.edu/browse/SISRP-20157
QA PR of #5543
=> [QA] SISRP-21453 & SISRP-20157 - Profile Work Experience: Add and Edit buttons should be disabled when viewing-as, start and end dates not shown

src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21401
QA PR of #5549
=> [QA] SISRP-21401 - Make Payment for Fall 2016 button should be greyed out in view as mode

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-18292
Design:  https://jira.berkeley.edu/browse/SISRP-16119
* OK'd with designer (Chara) the alphabetical-ness of what I'm PR-ing vs. the design.
=> SISRP-18292 - 5.6 - My Campus (Students) - Request Transcripts and Enrollment Verifications

src/assets/stylesheets/_academics.scss, src/assets/stylesheets/_canvas_roster.scss, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-21652
QA first!
=> [QA] SISRP-21652 Unbust roster photo printing

app/models/edo_oracle/queries.rb
QA FIRST fix for https://jira.berkeley.edu/browse/SISRP-21615
Master branch PR to follow.
=> [QA] SISRP-21615 Display fringe academic plan types as majors in roster

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-18292
Design: https://jira.berkeley.edu/browse/SISRP-16119
QA PR of #5551
=> [QA] SISRP-18292 - 5.6 - My Campus (Students) - Request Transcripts and Enrollment Verifications

src/assets/templates/widgets/status_holds_blocks.html
QA FIRST fix for https://jira.berkeley.edu/browse/SISRP-21018
Master branch PR to follow.
=> [QA] SISRP-21018 Do not show dangling "California Residency" label

src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21371
QA PR of #5545
=> [QA] SISRP-21371 - Billing Summary - Negative Balance should say Credit Balance

src/assets/templates/widgets/status_holds_blocks.html
Master branch version of QA PR https://github.com/ets-berkeley-edu/calcentral/pull/5560
=> SISRP-21018 Do not show dangling "California Residency" label

spec/ui_selenium/my_academics_data_profile_and_reqts_spec.rb, spec/ui_selenium/my_academics_data_status_blocks_holds_spec.rb, spec/ui_selenium/pages/api_cs_holds_page.rb, spec/ui_selenium/pages/api_cs_residency_message_page.rb, spec/ui_selenium/pages/api_edos_student_page.rb, spec/ui_selenium/pages/my_academics_profile_card.rb, spec/ui_selenium/pages/my_academics_status_blocks_holds_card.rb, spec/ui_selenium/pages/my_finances_financial_aid_page.rb
https://jira.berkeley.edu/browse/SISRP-21535
=> SISRP-21535 - fix QA status, profile, residency tests

src/assets/stylesheets/_canvas_roster.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6363
See #5570 for DEV PR
=> [QA] CLC-6363 - bCourses - roster photos section select is not rendering properly

src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-21347
QA version of #5550.
=> [QA] SISRP-21347 Do not show enrollment cards with no enrollments

app/models/rosters/common.rb, spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-21686
Master PR to follow.
=> [QA] SISRP-21686 De-duplicate majors in roster query

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-21634
QA PR of #5574
=> [QA] SISRP-21634 - Remove change of course-load eForm link from MyCampus Links section

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-21615
=> [QA] SISRP-21615 Add CRT plans to enrollment/waitlist tab display

src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/javascripts/angular/controllers/widgets/carsController.js, src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21691
QA PR for #5577
=> [QA] SISRP-21691 - Financials UI needs error handling of unexpected feeds

src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-21625
QA PR of #5568
=> [QA] SISRP-21625 - UAT 5.6 - Cal Central - My Finances - Billing Summary- Details - Fall 2016 Sorting incorrectly

app/models/berkeley/residency_message_code.rb, app/models/hub_edos/demographics.rb, spec/models/berkeley/residency_message_code_spec.rb
QA FIRST fix for https://jira.berkeley.edu/browse/SISRP-21616
The original specs were incomplete and the implementation needed a complete overhaul.
=> [QA] SISRP-21616 Fix Residency message codes

app/controllers/advising_student_controller.rb, app/controllers/my_registrations_controller.rb, app/models/my_registrations/my_registrations.rb, spec/models/my_registrations/my_registrations_spec.rb
https://jira.berkeley.edu/browse/SISRP-21571
See #5581 for DEV PR
=> [QA] SISRP-21571 - Add fault tolerance to Advising Student Registrations feed

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-21615
Master-branch squash of QA PRs #5561 and #5576.
=> SISRP-21615 Display fringe academic plan types as majors in roster

src/assets/stylesheets/_academics.scss, src/assets/stylesheets/_canvas_roster.scss, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-21652
Master-branch version of #5556.
=> SISRP-21652 Unbust roster photo printing

src/assets/stylesheets/_canvas_roster.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6363
See #5569 for QA PR
=> CLC-6363 - bCourses - roster photos section select is not rendering properly

app/models/rosters/common.rb, spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-21686
Master-branch version of #5572.
=> SISRP-21686 De-duplicate majors in roster query

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-21634
=> SISRP-21634 - Remove change of course-load eForm link from MyCampus Links section

src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/javascripts/angular/controllers/widgets/carsController.js, src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21691
* Removes infinite spinners
* Adds error text for empty feeds
* Empty feeds are usually accompanied by a 200 status - something we'll dig more into post-sprint.
=> SISRP-21691 - Financials UI needs error handling of unexpected feeds

app/controllers/advising_student_controller.rb, app/controllers/my_registrations_controller.rb, app/models/my_registrations/my_registrations.rb, spec/models/my_registrations/my_registrations_spec.rb
https://jira.berkeley.edu/browse/SISRP-21571
See #5582 for QA PR
=> SISRP-21571 - Add fault tolerance to Advising Student Registrations feed

app/models/berkeley/residency_message_code.rb, app/models/hub_edos/demographics.rb, spec/models/berkeley/residency_message_code_spec.rb
Master-branch version of https://github.com/ets-berkeley-edu/calcentral/pull/5579
=> SISRP-21616 Fix Residency message codes

src/assets/templates/widgets/profile/work_experience_section.html
https://jira.berkeley.edu/browse/SISRP-20231
=> SISRP-20231 - Profile Work Experience: only a single add or edit form should be allowed at once

spec/ui_selenium/my_academics_data_status_blocks_holds_spec.rb, spec/ui_selenium/pages/api_cs_residency_message_page.rb
https://jira.berkeley.edu/browse/SISRP-21535
=> SISRP-21535 - QA residency test fixes

app/models/my_registrations/my_registrations.rb, spec/models/my_registrations/my_registrations_spec.rb
https://jira.berkeley.edu/browse/SISRP-21780
New Summer 2016 students currently get a JavaScript exception and no indication of registration status. This PR seems to restore the intended behavior.
=> SISRP-21780 Include legacy terms such as Summer 2016 in Registrations feed

app/models/edo_oracle/adapters/oec.rb, spec/models/edo_oracle/adapters/oec_spec.rb, spec/models/edo_oracle/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6362
Slight refactor of model class for easier testing (did you know: methods called via `super` can't be stubbed?).
=> CLC-6362 Specs for OEC EdoOracle retrofit

spec/support/selenium_helper.rb, spec/ui_selenium/my_finances_financials_cs_data_spec.rb, spec/ui_selenium/my_finances_financials_cs_ui_spec.rb, spec/ui_selenium/my_finances_financials_legacy_data_spec.rb, spec/ui_selenium/pages/api_cs_billing_page.rb, spec/ui_selenium/pages/api_my_financials_page.rb, spec/ui_selenium/pages/my_finances_billing_page.rb, spec/ui_selenium/pages/my_finances_details_page.rb, spec/ui_selenium/pages/my_finances_pages.rb, spec/ui_selenium/util/web_driver_utils.rb
https://jira.berkeley.edu/browse/SISRP-21150
=> SISRP-21150 - QA tests for new Finances UI

app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-21863
=> SISRP-21863 - Apply Event Notification Framework to CampusSolutions::MyBilling

app/models/my_academics/teaching.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-21878
I neglected to global-search for "pastSemestersCount" before submitting https://github.com/ets-berkeley-edu/calcentral/pull/5589 ...
=> SISRP-21878 Fix My Academics for instructors

app/controllers/act_as_controller.rb, src/assets/javascripts/angular/controllers/widgets/adminController.js, src/assets/javascripts/angular/controllers/widgets/delegateStudentsController.js, src/assets/templates/widgets/toolbox/delegate_students.html
https://jira.berkeley.edu/browse/SISRP-21883
=> SISRP-21883 Front-end for self View-As and self Delegation issues

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-21762
=> SISRP-21762 Restrict protected Veteran's Benefits link to students

README.md, src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js, src/assets/stylesheets/_academics.scss, src/assets/templates/academics_classinfo.html, src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-21707
=> SISRP-21707 - 5.6d - Course Enrollment Tab - Email an Enrollment Manager

app/models/oec/merged_sheet_validation.rb, app/models/oec/task.rb, app/models/oec/term_setup_task.rb, spec/models/oec/publish_task_spec.rb, spec/models/oec/validation_task_spec.rb, spec/support/oec_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6347
=> CLC-6347 OEC: Carry over course-instructor pairings from previous terms

src/assets/javascripts/angular/controllers/widgets/finaid/finaidCoaController.js, src/assets/templates/directives/finaid_table.html
https://jira.berkeley.edu/browse/SISRP-12998
=> SISRP-12998 Fix FinAid Estimated Cost of Attendance labels

spec/ui_selenium/my_finances_financials_cs_data_spec.rb, spec/ui_selenium/my_finances_financials_cs_ui_spec.rb, spec/ui_selenium/pages/api_cs_billing_page.rb, spec/ui_selenium/pages/my_finances_billing_page.rb, spec/ui_selenium/pages/my_finances_pages.rb
https://jira.berkeley.edu/browse/SISRP-21535
Updates to financials QA tests, since several CalCentral bugs have been fixed and tests need new expectations.
=> SISRP-21535 - QA finances test fixes

src/assets/javascripts/angular/controllers/widgets/billingController.js
https://jira.berkeley.edu/browse/SISRP-22027
* I can't for the life of me reproduce this bug (wish I took a screenshot), but in any case it does make the function more robust, and it did fix the temporary bug I saw of the numbers not being converted to strings.
=> SISRP-22027 - Financials Amounts Not Showing Up

app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6377
=> CLC-6377 OEC: Exclude online courses from room-share lookup

app/models/edo_oracle/adapters/oec.rb, spec/models/edo_oracle/adapters/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6375
=> CLC-6375 OEC: Surface student ID only for active students

src/assets/javascripts/angular/controllers/widgets/billingController.js, src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-21781
=> SISRP-21781 - Finances Billing - sort by amount is wrong unless in Balance view

config/settings.yml
QA first for https://jira.ets.berkeley.edu/jira/browse/CLC-6380
(if @pfarestveit and @johncrossman are OK with that).
=> QA CLC-6380 Show Delegated Access video on splash page

config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, src/assets/templates/widgets/enrollment/consult_advisor.html
https://jira.berkeley.edu/browse/SISRP-19891
=> SISRP-19891 Remove Class Enrollment Advisors feature

config/settings.yml
Master branch version of https://github.com/ets-berkeley-edu/calcentral/pull/5614
=> CLC-6380 Show Delegated Access video on splash page

src/assets/javascripts/angular/directives/youtubeDirective.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6312
See the Jira description. The new and interesting arg is `authuser=1`. *Note:* I alphabetized the args, too.
=> CLC-6312, update YouTube embed args passed by youtubeDirective

app/models/links/campus_link_loader.rb, app/models/links/my_campus_links.rb, public/json/campuslinks.json, spec/models/links/my_campus_links_spec.rb
https://jira.berkeley.edu/browse/SISRP-22116
Up to now, the server has just been returning whatever the "student" role got.
=> SISRP-22116 Start splitting out My Campus Links for exStudent role

script/sis/verify_sis_api_endpoints.sh
Endpoint relates to `cs_profile_emergency_contacts` feature flag.
=> NOJIRA, UcApiEmergencyContactGet added to verify_sis_api_endpoints

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-21252
* Follows the same logic as before, just added the CS Financials data sources
=> SISRP-21252 - Financials - how will amount due alerts in CalCentral appear for CS financials?

spec/controllers/service_alerts_controller_spec.rb, spec/models/service_alerts/merged_spec.rb, src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-21252
QA PR of #5619 
Also includes commit from #5621 to appease our Travis
=> [QA]SISRP-21252 - Financials - how will amount due alerts in CalCentral appear for CS financials?

app/models/ets_blog/rss_proxy.rb, lib/proxies/authenticated_api.rb, lib/proxies/http_client.rb, lib/proxies/tls12.rb, src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-22282
https://jira.ets.berkeley.edu/jira/browse/CLC-6386
Reversion of https://github.com/ets-berkeley-edu/calcentral/pull/5624
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5623
Nothing so invigorating as a couple of blockers on the release candidate two days before the release...
=> QA fixes for SISRP-22282 & CLC-6386

src/assets/templates/campus_link_list.html, src/assets/templates/widgets/finances_links.html, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6391
Per @davidlimcheng suggestion in #5625
=> CLC-6391, use data-ng-attr-title when value is dynamic

app/models/canvas_csv/base.rb, app/models/canvas_csv/site_memberships_maintainer.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6385
It's a dangerous world out there.
=> CLC-6385 Protect Canvas refresh script against bad LDAP UIDs

src/assets/templates/myfinances.html, src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21312
=> SISRP-21312 - Hide CARS card for new students without CARS data

app/models/oec/sis_import_sheet.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6393
=> CLC-6393 OEC: Guard against nil comparisons when sorting SIS import sheets

src/assets/stylesheets/_webcast.scss, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6392
Willa is currently working on the Service-Now page. Sample card:
=> CLC-6392, Course Capture: instructions for accessing private YouTube videos

src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6395
See screenshot in the Jira.
=> CLC-6395, only show alert when we have 1+ videos in list

src/assets/stylesheets/_webcast.scss, src/assets/templates/widgets/webcast.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6398
See Jira above for expected renderings.
=> CLC-6398, Course Capture widget: trimming, padding and verbiage

app/controllers/campus_solutions/link_controller.rb, app/models/campus_solutions/link.rb, config/routes.rb, config/settings.yml, fixtures/xml/campus_solutions/link_api.xml, fixtures/xml/campus_solutions/link_api_error.xml, fixtures/xml/campus_solutions/link_api_multiple.xml, spec/controllers/campus_solutions/link_controller_spec.rb, spec/models/campus_solutions/link_spec.rb
https://jira.berkeley.edu/browse/SISRP-22628
@redconfetti @paulkerschen @raydavis  Link API backend is ready for first-pass review
=> SISRP-22628 - 6.0 - Backend - Link API for Campus Solutions

script/sis/verify_sis_api_endpoints.sh
=> NOJIRA, link API added to verify_sis_api_endpoints.sh

app/controllers/campus_solutions/enrollment_verification_messages_controller.rb, app/models/campus_solutions/enrollment_verification_messages.rb, config/routes.rb, config/settings.yml, fixtures/xml/campus_solutions/enrollment_verification_messages.xml, public/dummy/json/enrollment_verification_messages.json, spec/models/campus_solutions/enrollment_verification_messages_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js, src/assets/javascripts/angular/factories/enrollmentVerificationFactory.js, src/assets/stylesheets/_academics.scss, src/assets/stylesheets/_enrollment_verification.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/academics_enrollment_verification.html, src/assets/templates/academics_semesters.html, src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-22431
* Feature-flag driven
* No links yet - links to come following Links API implementation + SSO to National Student ClearingHouse API
* Included both a fixture and a dummy JSON - a little overboard maybe?
* We're always going to want to grab the three messages once this page hits, so I just grab the whole message set instead of making three separate API calls
=> SISRP-22431 - 6.0 - Enrollment Verification Options Pt.1 - Feature Flag, Front-End

spec/models/berkeley/terms_spec.rb, spec/models/webcast/merged_spec.rb
https://jira.berkeley.edu/browse/SISRP-22634
=> SISRP-22634 More testext fixes for Hub Term API addition

app/controllers/mediacasts_controller.rb, spec/controllers/mediacasts_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6403
Previous implementation was unreliable for cross-listed courses. We now get enrolled/teaching sections with matching dept_name and catalog_id then search for course-captures with matching section_ids. 
Willa has signed off on a (long ago requested) biz logic change that comes with this PR: If the course has multiple primary sections and the user is neither enrolled in nor teaching the section with recordings then s/he will not have access to those recordings.
=> CLC-6403, course-capture recordings of section(s) enrolled or teaching

src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
https://jira.berkeley.edu/browse/SISRP-22733
@redconfetti , this is another one you'll likely be interested by.
=> SISRP-22733 Fix Law-specific Class Enrollment sections

src/assets/templates/widgets/profile/emergency_contact_editor.html, src/assets/templates/widgets/profile/work_experience_editor.html
https://jira.berkeley.edu/browse/SISRP-21178
https://jira.berkeley.edu/browse/SISRP-20482
Fixed two very small bugs as a way to get my feet wet! Prevented job titles, employers, and contact names to be maxlength of 50, as well as payrate to be max 15 characters and hours per week to be max 3 characters (Take 2!)
=> SISRP-21178 Profile inputs should not permit greater than max chars

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-22788
* In order to use a parameter defined with $routeProvider on any given template, we need to bind the value to the respective controller
* Helpful [Stack Overflow](http://stackoverflow.com/questions/27533386/angular-passing-params-from-routeprovider-to-controller) on the topic.
=> SISRP-22788 - 'Enrollment Verification' Link Shows Up on Advisor User Overview

src/assets/javascripts/angular/controllers/widgets/statusController.js, src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-21160
The first commit should fix a problem in production (trying to load CS financial data without a CS ID).
The second commit fixes a regression which crept in at https://github.com/ets-berkeley-edu/calcentral/commit/e3cb33a0305bd43e164ff03282b4c3963460bfd6 : 
```
if ($scope.finances.csFinances) { // This block is entered with an empty but truthy csFinances object
cs = {
pastDue: $scope.finances.csFinances.pastDueAmount,  // goes to undefined
minDue: $scope.finances.csFinances.amountDueNow // goes to undefined
};
$scope.totalPastDueAmount += cs.pastDue;  // goes to NaN
$scope.minimumAmountDue += cs.minDue; // goes to NaN
}
```
=> SISRP-21160 Fix CARS-related front-end bugs

src/assets/javascripts/angular/controllers/widgets/transferCreditController.js
https://jira.berkeley.edu/browse/SISRP-22791
Fixes the Transfer Credit infinite spinner when no transfer credit data provided.
=> SISRP-22791 - Transfer Credit card is not loading

src/assets/templates/widgets/profile/emergency_contact.html, src/assets/templates/widgets/profile/languages_section.html, src/assets/templates/widgets/profile/languages_section_editor.html, src/assets/templates/widgets/profile/work_experience_editor.html, src/assets/templates/widgets/profile/work_experience_section.html
https://jira.berkeley.edu/browse/SISRP-21154: Consistent UI on Profile
https://jira.berkeley.edu/browse/SISRP-20195: Restrict pay rate and hours
https://jira.berkeley.edu/browse/SISRP-19994: Languages sort alphabetically
Note: since I currently do not have a dev.local.yml file, I am not able to make post requests, and so I wasn't able to fully test 21154. I'm hoping the no emergency contacts looks like the no languages card, and that when there's already a language, there isn't an extra add link. If someone can quickly check to make sure the PR is good and that visually there aren't any problems, I'd be grateful. Thanks!
=> 21154 / 20195 / 19994 - Consistent UI on profile, restrict pay rate and hours, languages sort alphabetically

src/assets/templates/academics_classinfo.html, src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-21766
=> SISRP-21766 Show Section ID as "Class Number", course code as "Course"

src/assets/templates/academics_classinfo.html
Follow-up PR from https://github.com/ets-berkeley-edu/calcentral/pull/5659
=> SISRP-21766 Simplify template logic

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-21687
CalCentral: Effectively organizing organizations who organizationally effectivenize.
=> SISRP-21687 Fix Organizational Effectiveness link

src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-22931
* See JIRA comments! (But only if you want to)
=> SISRP-22931 - Billing Summary Fall 2016 card not displaying in CalCentral-DEV but fees in QAT

script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-23025
=> SISRP-23025, hub_term_api test added to verify_sis_api_endpoints.sh

app/controllers/advising_student_controller.rb, app/controllers/hub_edo_controller.rb, app/models/hub_edos/my_academic_status.rb, app/models/my_academics/academics_module.rb, app/models/my_academics/class_enrollments.rb, app/models/notifications/sis_expiry_processor.rb, config/routes.rb, fixtures/json/hub_academic_status.json, public/dummy/json/hub_academic_status.json, spec/models/my_academics/class_enrollments_spec.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/javascripts/angular/controllers/widgets/holdsController.js, src/assets/javascripts/angular/controllers/widgets/statusController.js, src/assets/javascripts/angular/factories/academicStatusFactory.js, src/assets/templates/widgets/holds.html, src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-22622
* Pt. 1 - Switching from Service Indicators API to Student/Academic-Status for Holds
* Service Indicators API included both positive and negative service indicators.  Holds are categorized as negative SI only, necessitating this change.
* Pt. 2 - Removing all Service Indicators API code.
=> SISRP-22622 - Switch Holds API to Pull from Hub Pt.1

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-22922
=> SISRP-22922 - CalCentral Prod - My Academics - Fall 2016 enrollment no longer appearing for student

app/controllers/campus_solutions/link_controller.rb, app/models/campus_solutions/link.rb, fixtures/xml/campus_solutions/link_api.xml, fixtures/xml/campus_solutions/link_api_multiple.xml, spec/controllers/campus_solutions/link_controller_spec.rb, spec/models/campus_solutions/link_spec.rb, src/assets/javascripts/angular/controllers/widgets/csLinkFactory.js
https://jira.berkeley.edu/browse/SISRP-22629
=> SISRP-22629 - 6.0 - Frontend - Link API for Campus Solutions

script/sis/verify_sis_api_endpoints.sh
=> NOJIRA, change per CampusSolutions::Link change

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-21727
master PR https://github.com/ets-berkeley-edu/calcentral/pull/5674
=> [QA] SISRP-21727 - Financial Resources - Emergency Loan Link with CS Link API

app/models/campus_solutions/link.rb, spec/models/campus_solutions/link_spec.rb, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-21727
uses CS Link API to fetch "Add an Emergency Loan" link and append it to the "Financial Assistance" section in "Financial Resources" card.
Depends on PR https://github.com/ets-berkeley-edu/calcentral/pull/5660
=> SISRP-21727 - 6.0 - Financial Resources - Emergency Loans link

app/controllers/campus_solutions/link_controller.rb, app/models/campus_solutions/link.rb, fixtures/xml/campus_solutions/link_api.xml, fixtures/xml/campus_solutions/link_api_multiple.xml, spec/controllers/campus_solutions/link_controller_spec.rb, spec/models/campus_solutions/link_spec.rb, src/assets/javascripts/angular/controllers/widgets/csLinkFactory.js
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5660
=> [QA] SISRP-22629 - 6.0 - Frontend - Link API for Campus Solutions

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-22147
master PR https://github.com/ets-berkeley-edu/calcentral/pull/5675
=> [QA] SISRP-22147 - 6.0 - My Campus Links - eForms

app/controllers/campus_solutions/enrollment_verification_deeplink_controller.rb, app/models/campus_solutions/enrollment_verification_deeplink.rb, config/routes.rb, config/settings.yml, fixtures/json/enrollment_verification_deeplink.json, public/dummy/json/enrollment_verification_deeplink.json, src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js, src/assets/javascripts/angular/factories/enrollmentVerificationFactory.js, src/assets/stylesheets/_enrollment_verification.scss, src/assets/templates/widgets/academics/enrollment_verification.html
=> [QA]SISRP-22703 - Add Link to CS Enrollment Verification

app/models/my_academics/college_and_level.rb, app/models/my_academics/gpa_units.rb
https://jira.berkeley.edu/browse/SISRP-23107
See DEV PR #5681
=> [QA] SISRP-23107 - Ensure parsed feeds do not include raw EDO Hub response

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-22147
adds "Change of Academic Plan" eForm URL to My Campus > Forms > Student Forms
=> SISRP-22147 - 6.0 - My Campus Links - eForms

app/models/my_academics/college_and_level.rb, app/models/my_academics/gpa_units.rb
https://jira.berkeley.edu/browse/SISRP-23107
See QA PR #5683
=> SISRP-23107 - Ensure parsed feeds do not include raw EDO Hub response

app/models/my_registrations/my_registrations.rb
https://jira.berkeley.edu/browse/SISRP-23154
* Based on @raydavis's comment @ #5680
=> SISRP-23154 - Refactor My Registrations call on Berkeley::Term

src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-23167
Master PR, QA PR to follow - please merge QA first.
=> SISRP-23167 - CNP notification not expanding for Grad Student

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-23165
QA PR of #5689
=> [QA] SISRP-23165 - Header Popover alert has alert, but no hold/bock details

src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-23167
=> [QA FIRST] SISRP-23167 - CNP notification not expanding for Grad Student

src/assets/javascripts/angular/controllers/widgets/csLinkFactory.js, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finances_links.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5691
https://jira.berkeley.edu/browse/SISRP-21727
PR fixes csLinkFactory bug with to the csLinkUrl string, and replaces the campus solutions link directive with vanilla anchor tag and outboundLink property.
=> [QA] SISRP-21727 - 6.0 - Financial Resources - Emergency Loans link

src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/course_grade_export.html, src/assets/templates/widgets/status_and_holds.html, src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-23175
* Apparently there's no such class as `cc-icon-yellow` and it should be `cc-icon-gold`!
* Found a couple of other places referencing `cc-icon-yellow` so I changed those as well.
* Should I open a QA PR for this?
=> SISRP-23175 - CNP notification should have Yellow Color icon

src/assets/javascripts/angular/services/statusHoldsService.js, src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-23183
Master PR of #5697
=> SISRP-23183 - Graduate students - Exception from CNP -Incomplete text in expanded view

src/assets/templates/canvas_embedded/_shared/maintenance_notice.html, src/assets/templates/canvas_embedded/course_grade_export.html, src/assets/templates/widgets/status_and_holds.html, src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-23175
QA PR of #5698 .
=> [QA] SISRP-23175 - CNP notification should have Yellow Color icon

app/models/berkeley/user_roles.rb, app/models/user/aggregated_attributes.rb, spec/models/berkeley/user_roles_spec.rb, spec/models/user/aggregated_attributes_spec.rb, spec/models/user/api_spec.rb
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/5696
=> SISRP-23217 Enable GRADUATE, UNDERGRAD CS Affiliations

src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-23173
* Apologies for this, prior sloppy code on my part.  This is why coding shouldn't happen past 10pm =\
=> [QA] SISRP-23173 - Header popover shows CNP and Registration alert but no Status Block Card exists

app/models/campus_solutions/link.rb, spec/controllers/campus_solutions/link_controller_spec.rb, spec/models/campus_solutions/link_spec.rb
https://jira.berkeley.edu/browse/SISRP-23223
master PR https://github.com/ets-berkeley-edu/calcentral/pull/5703
=> [QA] SISRP-23223 - CS Link API - suppress `properties` hash in front-end JSON

src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-23173
Master PR of #5702.
=> SISRP-23173 - Header popover shows CNP and Registration alert but no Status Block Card exists
