ets-berkeley-edu/junction

- public/dummy/json/holds_empty.json
- public/dummy/json/holds_present.json
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/factories/holdsFactory.js
- src/assets/stylesheets/_enrollment_card.scss
- src/assets/templates/widgets/enrollment/adjust.html
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
- src/assets/templates/widgets/enrollment/consult_advisor.html
- src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-16788
* Adds static advisor contact list for display to Berkeley Law students
* Modifies text in appointment time section. Fixes logic for detecting if student is a Law student (see  [SISRP-17895](https://jira.berkeley.edu/browse/SISRP-17895))
* Fixes logic for displaying date in Enrollment Adjust section template, and fixing the exclusion of the 'Change Grading Option' and 'Withdraw' links
* Adds dummy feeds for holdsFactory
> SISRP-16788 - Enrollment - Law: show different text for advisors depending on program

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-18564
The Jira description says "reload the page and all is good".  All is good because `apiService.user.fetch()` is invoked where route=`/user/overview`. The canSeeCSLinks property is sensitive to this route and suppresses all CS links.  The snippet below is from *routeConfigurations.js*:
```
when('/user/overview/:uid', {
templateUrl: 'user_overview.html',
controller: 'UserOverviewController',
isAdvisingStudentLookup: true
}).
```
> SISRP-18564, refresh user properties because canSeeCSLinks property is sensitive to the /user/overview route

- src/assets/javascripts/angular/controllers/widgets/userSearchController.js
https://jira.berkeley.edu/browse/SISRP-18736
Reset `users` array (i.e., search results) on error.
> SISRP-18736, if user search has error then clear previous results

- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
More info at:
https://jira.berkeley.edu/browse/SISRP-18908
I left the whole `$watchGroup` logic in there because I'm not exactly sure how the behavior of `studentInfo.regStatus.code` works over time.
@johncrossman, let me know if I should PR this against QA Branch as well.
> SISRP-18908 - Return Holds Section to Status, Holds, & Blocks

- app/models/user/api.rb
- public/dummy/json/status.json
- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-18979
The May 09 load test failed to complete (twice!) due to max'ing out of db connections, Apache threads, etc. Another symptom: Instructure reported OutOfMemory via Canvas API response. We don't know cause(s) of load test failure yet. But, two CalCentral feeds logged many SLOW PROXYs:
* /api/my/status
* /api/my/activities
In the process of scrutinizing that code I came across the apparently unused `hasCanvasAccount` which I believe is the only Canvas dependency in `/api/my/status`. I see no reason not to remove it.
> SISRP-18979, remove hasCanvasAccount which is only used by spec

- app/models/campus_oracle/user_courses/base.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_classes/campus.rb
- public/dummy/json/academics.json
- public/dummy/json/academics_transition_future_profile.json
- public/dummy/json/academics_transition_past_profile_not_registered.json
- public/dummy/json/academics_transition_past_profile_registered.json
- public/dummy/json/classes.json
- spec/models/campus_oracle/user_courses/all_spec.rb
- spec/models/campus_oracle/user_courses/base_spec.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- spec/models/my_classes/campus_spec.rb
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/academics_semester_classes.html
- src/assets/templates/widgets/my_classes.html
https://jira.berkeley.edu/browse/SISRP-18807
Various bits of CalCentral code have used "has waitlist position of zero?" as shorthand for "is not waitlisted in this section?" This will no longer fly in the EDO DB world, which conceives positionless waitlists for non-enrollment sections. Accordingly we need an explicit `waitlisted` section property.
> SISRP-18807 Distinguish enrolled courses from zero-position waitlisted courses

- config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6299
A little tweak in support of `/api/my/status` performance.
> CLC-6299, Cal1card::Photo cache.expiration config to 4.hours

- app/models/user/api.rb
- public/dummy/json/status.json
https://jira.ets.berkeley.edu/jira/browse/CLC-6297
Removal of unused property in `/api/my/status` means one less db call.
> CLC-6297, remove 'canvasEmail' from User::Api

- src/assets/templates/academics_status_holds_blocks.html
https://jira.berkeley.edu/browse/SISRP-19020
Suppresses residency block in template, if `residency.description` is not set by the controller's `parseCalResidency()` function - i.e., when `residency` is empty in the feed.
Also adding spinner for the residency block in loading state and when `residency.description` is not yet set.
> SISRP-19020 - Residency: Haas EWMBA student showing "California Residency" with blank status

- app/controllers/advising_student_controller.rb
- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- spec/controllers/campus_solutions/advising_resources_controller_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-19058 (remove Academic Planner link on Advising Student Profile card)
* Generic Advising Resources card gets: multi_year_academic_planner, schedule_planner
* Student Profile card for Advisors gets: multi_year_academic_planner_student_specific, schedule_planner_student_specific
Eventually these links should be served by CS API but there is an urgent need. Thus we manage them via CalCentral settings.
> SISRP-16435, links for Advisors: Multi-Year Academic Planner and Schedule Planner

- src/assets/templates/widgets/profile/address.html
- src/assets/templates/widgets/profile/contact_address_editor.html
- src/assets/templates/widgets/profile/contact_email_editor.html
- src/assets/templates/widgets/profile/contact_phone_editor.html
https://jira.berkeley.edu/browse/SISRP-19184
According to this [W3 page (section 4.3)](https://www.w3.org/TR/html-markup/syntax.html), `<select>` elements are not void elements, and must have a closing `</select>` tag - otherwise, the `<select>` will eat up all of the elements underneath it, which is what it was doing when the "edit" button was being pushed.
This bug also lives in other places, primarily in Profile, so I've created [SISRP-19203](https://jira.berkeley.edu/browse/SISRP-19203) to ensure the other ones get cleaned up as well.
> SISRP-19184 - Profile Contact Info: click edit and data vanishes

- config/settings.yml
https://jira.berkeley.edu/browse/SISRP-19251
Re: `campus_solutions_links.advising`. Default URLs are blank, for now.
> SISRP-19251, default for advising links is blank URL

- Gemfile
https://jira.ets.berkeley.edu/jira/browse/CLC-6308
Master-branch version of #5392.
> CLC-6308 Make Webmock gem available under production RAILS_ENV

- src/assets/stylesheets/_campus.scss
- src/assets/stylesheets/_foundation_overrides.scss
- src/assets/stylesheets/_widgets.scss
- src/assets/templates/academics.html
- src/assets/templates/academics_booklist.html
- src/assets/templates/academics_classinfo.html
- src/assets/templates/academics_semester.html
- src/assets/templates/billing_details.html
- src/assets/templates/cars_details.html
- src/assets/templates/dashboard.html
- src/assets/templates/directives/finaid_permissions.html
- src/assets/templates/finaid.html
- src/assets/templates/finaid_awards_compare.html
- src/assets/templates/finaid_awards_term.html
- src/assets/templates/myfinances.html
- src/assets/templates/toolbox.html
- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-18222
* Adds 2-column layout support to page templates
* Adjusts the My Campus widget width percentage for medium width devices (40% to 60%)
* Adds styles to support removal of right-gutter for 2nd column in 2-column layouts, as well as when medium viewport in use (which reduce to 2-column layout)
* Removes right gutter from Roster view when instructor viewing class page
> SISRP-18222 - 3-2-1 Columns in CalCentral

- config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6318
* `webcast-cc-staging` holds a closer copy of production data
* QA dept can override this config when testing Course Capture end-to-end.
> CLC-6318, change default webcast_proxy to webcast-cc-staging

- app/controllers/mediacasts_controller.rb
- app/models/edo_oracle/queries.rb
- config/routes.rb
- fixtures/webcast/warehouse/webcast.json
- spec/controllers/mediacasts_controller_spec.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/webcast/recordings_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6276
* If `Berkeley::Terms.legacy? term_yr, term_cd` then `CampusOracle::Queries` else `EdoOracle::Queries`. 
* Change to `routes.rb` does not change feed URL signature. 
* Test coverage
I revised PR #5419 by removing the no-op bits of `ORDER BY`
> CLC-6276, prepare CalCentral's course-capture controller for Fall 2016 / EDO db

- src/assets/templates/academics_classinfo.html
- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-18916
If there's an error in the feed, display "There was an error retrieving enrollment data" inside waitlist and enrollments blocks instead of "No students ..." messages.
> SISRP-18916 - Faculty class enrollment error could use better UI

- Gemfile
https://jira.berkeley.edu/browse/SISRP-19471
https://jira.berkeley.edu/browse/SISRP-19757
QA PR first due to very tight schedule.
> [QA] SISRP-19757 Remove thread-unsafe Webmock gem from production builds

- Gemfile
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/5431
I've added a comment for safety.
> SISRP-19757 Remove thread-unsafe Webmock gem from production builds

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- spec/controllers/campus_solutions/advising_resources_controller_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-19386
* Changes link name to 'Multi-Year Planner' instead of 'Multi-Year Academic Planner'
* Removes unused generic 'Schedule Planner' link from feed.
* Adds generic 'Multi-Year Planner' link for use on 'Advising Resources' card
* Updates 'Schedule Planner' link under 'Personal Summary' card so that it opens in a new window
> SISRP-19386 - Advisor Resource Link updates

- spec/models/edo_oracle/course_sections_spec.rb
https://jira.berkeley.edu/browse/SISRP-19992
The bug is not fixed. This PR only demonstrates what is broken. 
See `pending do` block.
> SISRP-19992, translate_location spec targeting locations withouth room number

- spec/models/edo_oracle/queries_spec.rb
- spec/models/webcast/audio_spec.rb
https://jira.berkeley.edu/browse/SISRP-19664
> SISRP-19664 - In EdoOracle::Queries spec, :textext should be :testext

- app/models/eft/my_eft_enrollment.rb
- config/settings.yml
- fixtures/json/eft_enrollment.json
- spec/models/eft/my_eft_enrollment_spec.rb
https://jira.berkeley.edu/browse/SISRP-19804
* Removed some unnecessary class inclusions, as the incoming feed is already JSON'd (I hope this is correct)
* Removed custom error handling, since the error messages coming from EFT should be more helpful in determining any problems
* Good ol' Oski info
* I do have a security token to enable this proxy (currently just for its QA environment) - what would be the best way to communicate this to all developers?
> SISRP-19804 - Add EFT Proxy Information, Update Back-End for Actual Response

- Gemfile
- Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-6325
https://jira.berkeley.edu/browse/SISRP-18781
CalCentral is unable to sustain even a light load with this version of the jruby-openssl Gem.
Unfortunately, that means losing support for the SSL TLSv1.2 protocol, and another release with broken "Textbooks" and "Book List" functionality.
> SISRP-18781 CLC-6325 Remove memory-killing jruby-openssl; disables textbooks

- app/controllers/campus_solutions/emergency_contacts_controller.rb
- app/models/campus_solutions/emergency_contacts.rb
- app/models/campus_solutions/emergency_contacts_feature_flagged.rb
- config/routes.rb
- fixtures/xml/campus_solutions/emergency_contacts.xml
- fixtures/xml/campus_solutions/emergency_contacts_empty.xml
- spec/controllers/campus_solutions/emergency_contacts_controller_spec.rb
- spec/controllers/campus_solutions/language_code_controller_spec.rb
- spec/models/campus_solutions/emergency_contacts_spec.rb
- spec/support/campus_solutions_helper_module.rb
- src/assets/javascripts/angular/controllers/widgets/profile/emergencyContactController.js
- src/assets/javascripts/angular/factories/profileFactory.js
- src/assets/javascripts/angular/services/profileService.js
- src/assets/templates/widgets/profile/emergency_contact.html
https://jira.berkeley.edu/browse/SISRP-19912
This is behind the feature flag, 'cs_profile_emergency_contacts'
Part of the longer SISRP-10778 story.  This PR is for work required to get a student's emergency contact data from the *correct* GET endpoint, instead of the hub's edos/student feed.
The fixture and the model spec are lengthy in order to verify certain transformations are done in the ruby so we don't have to do it in the JavaScript.
The JavaScript and template are modified to use the new data structure, but the UI is left in read-only state.
> SISRP-19912 - Dev: emergency contact edit - backend prep work

- app/models/campus_solutions/financial_aid_compare_awards_list.rb
https://jira.berkeley.edu/browse/SISRP-20582
* The iterating `format_date` function was running on all `feed` hashes, even empty ones, causing the NoMethodError
* Made the function conditional on the existence of `['AWARD_PARMS']`
> SISRP-20582 - CampusSolutions::FinancialAidCompareAwardsList - NoMethodError undefined method (v77 load test on May 31)

- public/json/campuslinks.json
- src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
- src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-19189
* Had to get rid of the "Registration Fees" campus links JSON object, since it was actually a duplicate of "Tuition and Fees" (just changed the name)
* Uses `data-ng-repeat-start` and `data-ng-repeat-end` to insert custom list items into an `ngRepeat` iterating through an array at a certain index
* Found out that the HTML for the EFT status items are not matching up with the design, created [SISRP-21011](https://jira.berkeley.edu/browse/SISRP-21011) to fix that
* Changed `campuslinks` to `campusLinks` just to keep casing consistent with the rest of the variables
> SISRP-19189 - Reorder Links as shown in Design for Financial Resources

- app/models/textbooks/proxy.rb
- spec/models/textbooks/proxy_spec.rb
- spec/support/cacheable_expectations.rb
- src/assets/javascripts/angular/services/academicsService.js
https://jira.berkeley.edu/browse/SISRP-17285
Two new requirements for a happy Fall 2016 textbooks feed:
- Query by five-digit course id, not three-digit section number;
- Zero-pad catalog id to at least three characters.
> SISRP-17285 Adapt textbook API requests to Campus Solutions course data

- src/assets/javascripts/angular/controllers/pages/billingDetailsController.js
- src/assets/javascripts/angular/controllers/widgets/billingController.js
- src/assets/javascripts/angular/controllers/widgets/carsController.js
- src/assets/templates/billing_details.html
- src/assets/templates/cars_summary.html
- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-20266
* I wanted to actually get your opinions on this PR before merging
* This goes in-hand with the "Prior to Fall 2016" subheading shown on the CARS Summary card
* The requirement is to show a "Fall 2016" subheading during the transition period.  Once CARS is retired, we'll want to remove the subheading - the problem is, that date is currently a moving target.
* This PR makes the subheading conditional on the "Current Term" that is being returned by the API.  Since CS "Current Term" is kind of funky, I've included "Summer 2016" as part of the conditional
* I think it'd be a good idea to create a new CalShare task (as opposed to a JIRA ticket), which acts as the source of record in SIS, to remove this code for GL7.  This ensures it won't fall …
> SISRP-20266 - Remove currentTerm displaying on Billing Summary

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-20823
The Jira asks for URL-per-environment (e.g., calcentral-qa would serve a link to BCSQAT). That is not possible within {{campuslinks.json}} schema so we'll have the prod BCS URL in all environments.
Specs: https://docs.google.com/spreadsheets/d/11iNO36RkCutBVYe0LA7p7hiT0Du_7YFK_g_jN3RhIHo/edit#gid=1697061413
> SISRP-20823, My Campus gets new section: Forms > Student Forms

- app/models/campus_oracle/calendar.rb
- app/models/edo_oracle/calendar.rb
- app/models/edo_oracle/connection.rb
- app/models/edo_oracle/queries.rb
- lib/oracle_base.rb
- spec/models/edo_oracle/calendar_spec.rb
https://jira.berkeley.edu/browse/SISRP-21097
Some of our existing Oracle fanciness is moved into superclasses for reuse.
Also, CampusOracle::Calendar is explicitly told not to query CS terms.
*Note:* these new queries are not yet called in production. Nothing to QA for v78.
> SISRP-21097 Queries and specs for EdoOracle::Calendar

- app/models/berkeley/term_codes.rb
- app/models/my_registrations/my_registrations.rb
- public/dummy/json/my_registrations.json
- spec/models/my_registrations/my_registrations_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/factories/registrationsFactory.js
- src/assets/templates/academics_status_holds_blocks.html
https://jira.berkeley.edu/browse/SISRP-18965
* For Fall 2016 regstatus, I focused on keeping the exact same design as we do now
* Instead of detangling `academicsController.js`, I decided to insert the new feed into `academicsStatusHoldsBlocks.js`.  This will also reduce the number of extra calls needed when placing this card onto the Advisor - Student Overview page (which is the next step).
* Will need to apply the same refactoring to `academicsController.js` as well though, but that will be post GL5.6.
* I also had to simplify the Rspec tests, since `CampusOracle::Queries` does not have any information on any terms prior to the "current" term.  What it does have, though, does suffice to test the functionality of the model.
* I know this is asking a lot, but it would be great if I could …
> SISRP-18965 - 5.6 - My Dashboard (Student) - Status, Blocks and Holds - Add Pre-Fall 2016 Terms to Registrations Feed, Refactor Reg

- script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-21573
CS API is fine. Our verify script needed a fix.
> SISRP-21573, stray slash in URL (verify_sis_api_endpoints script)

- src/assets/javascripts/angular/controllers/widgets/profile/workExperienceSectionController.js
- src/assets/templates/widgets/profile/work_experience_section.html
https://jira.berkeley.edu/browse/SISRP-21453
https://jira.berkeley.edu/browse/SISRP-20157
* Start/End dates stopped showing because they were reformatted in the returned EDO.  Fixed them everywhere they appeared.
* Had to use `data-ng-if` instead of `data-ng-disabled` on Add/Edit buttons.
> SISRP-21453 & SISRP-20157 - Profile Work Experience: Add and Edit buttons should be disabled when viewing-as, start and end dates not shown

- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21401
* I actually had to talk myself thru this one:
* We want the "Make Payment" button to DISABLE only for view-as users (`&&` statement)
* We want the "View Official Monthly Payment" item to ENABLE for directlyAuthenticated or delegates (`||` statement)
* Hence, one `&&` and one `||` for the seemingly same link to HigherOne.
> SISRP-21401 - Make Payment for Fall 2016 button should be greyed out in view as mode

- src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-21347
Since this is a partial revert of #5364, it will reintroduce the mystery-spinner issue first noted in https://jira.berkeley.edu/browse/SISRP-18744.
> SISRP-21347 Do not show enrollment cards with no enrollments

- app/models/edo_oracle/queries.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/rosters/common_spec.rb
Replaces academic program codes with enrollment specific academic career code in rosters feed
https://jira.berkeley.edu/browse/SISRP-21513
> SISRP-21513 - Replaces academic program codes with career codes for rosters

- app/models/rosters/common.rb
- spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-21615
> SISRP-21615 Use EDO DB, not LDAP, as student id source in rosters

- app/models/rosters/common.rb
- spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-21615
QA version of #5553
> [QA] SISRP-21615 Use EDO DB, not LDAP, as student id source in rosters

- app/models/edo_oracle/queries.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/rosters/common_spec.rb
Replaces academic program codes with enrollment specific academic career code in rosters feed
https://jira.berkeley.edu/browse/SISRP-21513
See #5554 for DEV PR
> [QA] SISRP-21513 - Replaces academic program codes with career codes for rosters

- app/models/rosters/common.rb
- spec/models/rosters/campus_spec.rb
- spec/models/rosters/common_spec.rb
Updates terms in attendance value calculation for Rosters feed to depend on enrollment specific academic career code
https://jira.berkeley.edu/browse/SISRP-21513
See #5559 for QA PR
> SISRP-21513 - Updates terms in attendance value calculation

- app/models/rosters/common.rb
- spec/models/rosters/campus_spec.rb
- spec/models/rosters/common_spec.rb
Updates terms in attendance value calculation for Rosters feed to depend on enrollment specific academic career code
https://jira.berkeley.edu/browse/SISRP-21513
See #5555 for DEV PR
> [QA] SISRP-21513 - Updates terms in attendance value calculation

- src/assets/javascripts/angular/controllers/widgets/billingController.js
- src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-21625
* Confirmed with functional owner that we want to keep case-insensitivity
* From AngularJS documentation:  "Note: If you notice numbers not being sorted as expected, make sure they are actually being saved as numbers and not strings."
* Due dates weren't sorting correctly because they were sorting on flags instead of the actual date
> SISRP-21625 - UAT 5.6 - Cal Central - My Finances - Billing Summary-Details - Fall 2016 Sorting incorrectly

- app/models/campus_oracle/calendar.rb
- app/models/campus_oracle/oec.rb
- app/models/canvas_lti/sis_adapter.rb
- app/models/edo_oracle/adapters/common.rb
- app/models/edo_oracle/adapters/oec.rb
- app/models/edo_oracle/calendar.rb
- app/models/edo_oracle/oec.rb
- app/models/edo_oracle/subject_areas.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/oec/queries.rb
- app/models/oec/sis_import_task.rb
- lib/oracle_base.rb
- spec/models/campus_oracle/oec_spec.rb
- spec/models/oec/sis_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6361
- Most of the former Oec::Queries is moved to CampusOracle::Oec.
- A parallel EdoOracle::Oec class is created.
- A subclass EdoOracle::Adapters::Oec adapts the new query results to nearly the exact format of the old. This class piggybacks on work originally done in CanvasLti::SisAdapter, and some common code is extracted from that class into a new EdoOracle::Adapters::Common.
- What remains of Oec::Queries is the interface of four methods directly called by OEC tasks. These methods are now extended by CampusOracle::Oec and EdoOracle::Oec. The Oec::Queries module forwards method calls to one class or the other, depending on term code.
- Oec::SisImportTask changes very slightly to handle the adapted data. (Evaluation type may be already set …
> CLC-6361 Adapt OEC queries to EDO DB source

- app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6361
Follow-up to #5587, moving the status-code condition from WHERE to JOIN so as not to screen out courses which have 1) a deprecated status code in the EDO course view, but 2) an active status code in the EDO cross-listing view.
> CLC-6361 OEC: tweak EDO DB query

- spec/models/edo_oracle/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6362
Follow up to #5591. The QAT instance of the EDO DB has better data than the DEV instance but is currently inaccessible from Bamboo. Wrap failing specs in a `pending` until the firewall issues are resolved.
> CLC-6362 Unblock Bamboo while EDO DB is inaccessible

- src/assets/javascripts/angular/controllers/widgets/billingController.js
- src/assets/templates/widgets/billing_activity.html
- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-21785
Also fixes:
https://jira.berkeley.edu/browse/SISRP-21704
* Verified with functional that CS will never send amounts with more than two decimal places
* Since JS is terrible at keeping trailing zeroes on `floats`, decided to just leave the `float` as is, and append a `string` version of that float to the object for presentation, while any controller/filter/sort logic is still based on the `float`.
* Still need to fix the "all transactions" sort, which is breaking because it still sorts on `itemBalance` but is showing `itemLineAmount`
> SISRP-21785 - Finances Billing - Balance filter showing paid transactions with zero balance

- app/controllers/act_as_controller.rb
- app/controllers/concerns/advisor_authorization.rb
- app/controllers/concerns/view_as_authorization.rb
- app/controllers/sessions_controller.rb
- spec/controllers/act_as_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-21883
This first PR fixes the Delegate log-out issue and does basic server-side blocking of View-As-self requests. Front-end code needs to be changed to show error responses from ``/act_as``.
> SISRP-21883 First fixes for View-As self issues

- app/models/campus_solutions/higher_one_url.rb
- spec/models/campus_solutions/higher_one_url_spec.rb
https://jira.berkeley.edu/browse/SISRP-21164
Also:  https://jira.berkeley.edu/browse/SISRP-21729
* API is now expecting both DELEGATE_UID and CSID of the student that the delegate wants to navigate to
* Has not been smoke tested yet due to upstream dependencies
> SISRP-21164 - Delegate having Multiple students higherone navigates to wrong student profile

- app/models/edo_oracle/adapters/oec.rb
- spec/models/edo_oracle/adapters/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6374
> CLC-6374 OEC: Pull email addresses from User::BasicAttributes when missing from DB

- spec/controllers/service_alerts_controller_spec.rb
- spec/models/service_alerts/merged_spec.rb
Currently these are breaking Travis CI due to CLC-6386. That SSLError issue needs to be fixed, but even so a RAILS_ENV=test rspec run should not rely on reaching live servers.
> NOJIRA Tests which hit real server endpoints should be confined to textext

- app/models/ets_blog/rss_proxy.rb
- lib/proxies/authenticated_api.rb
- lib/proxies/http_client.rb
- lib/proxies/tls12.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6386
(The new ``request_options`` mix-ins can also be applied to some existing proxy classes -- I just haven't gotten around to it yet...)
> CLC-6386 Use TLS1.2 SSL for RSS feeds

- app/models/webcast/course_media.rb
- app/models/webcast/merged.rb
- app/models/webcast/recordings.rb
- fixtures/webcast/warehouse/webcast.json
- spec/models/webcast/course_media_spec.rb
- spec/models/webcast/merged_spec.rb
- spec/models/webcast/recordings_spec.rb
- src/assets/templates/widgets/webcast.html
Back-end: https://jira.ets.berkeley.edu/jira/browse/CLC-6387
Front-end: https://jira.ets.berkeley.edu/jira/browse/CLC-6389
Includes:
* new playlist property in `/api/media` feed 
* better syntax in specs
* replace YouTube-embed in Course Capture card with a nicely formatted list of links
> CLC-6387, YouTube playlist ID added to API used by Course Capture card

- src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-21252
* "Status" was showing for staff/faculty in the popover because JS was parsing `$scope.minimumAmountDue` to `NaN`, and `NaN !== null` is parsed to `true`, giving these users `$scope.hasBillingData = true`.
* This will evaluate `null`, `NaN`, and `0` cases to false - see [this thread for some good information](http://stackoverflow.com/questions/5515310/is-there-a-standard-function-to-check-for-null-undefined-or-blank-variables-in)
> SISRP-21252 - Financials - how will ‘amount due’ alerts in CalCentral appear for CS financials?

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/controllers/widgets/transferCreditController.js
- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-15878
- using MVP design in https://jira.berkeley.edu/browse/SISRP-12170
- using cumulativeUnits from /my/academics feed
- fixes stack trace caused by `null` ref in `academicsStatusHoldsBlocksController.js`
> SISRP-15878: 6.0 - My Academics - Transfer Credits

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-22490
* If either `current` or `next` are `null`, then hide that regstatus
* This does **not** change any logic on `academicsController.js` that conditionally shows/hide the "Status and Holds" card - that will come in a future refactoring PR
* Includes "My Academics" and "User Overview" versions of this card
* Moves shared code into a service
* Keeps legacy messaging, but that will likely turn into message catalog stuff in a future PR
> SISRP-22490 - Add Both Current and Next RegStatus to Status & Holds

- app/models/berkeley/terms.rb
https://jira.berkeley.edu/browse/SISRP-22634
Blocker bug resulting from merger of legacy and CS terms data.
> SISRP-22634 Resolve disagreement over "current term" between legacy & CS

- app/controllers/campus_solutions/link_controller.rb
- app/models/campus_solutions/link.rb
- spec/controllers/campus_solutions/link_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-22628
Fix to earlier PR https://github.com/ets-berkeley-edu/calcentral/pull/5641
This PR adds actual expectations to the Link Controller Spec for behavior when params are (or are not) specified.
> SISRP-22628: fix LinkController#get options param setting and spec

- config/settings/development.yml
A little late following our convention on this one...
> SISRP-20755 Use fake Hub Term API in default developer.yml

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
The Roles added to the MyAcademics::CollegeAndLevel feed are no longer necessary after the refactor done in [SISRP-22857](https://jira.berkeley.edu/browse/SISRP-22857). This is a follow up to remove this data which is no longer needed.
https://jira.berkeley.edu/browse/SISRP-23011
> SISRP-23011 - My Academics Feed - College and Level - Remove FPF Role Logic

- app/models/oec/worksheet.rb
- spec/models/oec/publish_task_spec.rb
- spec/models/oec/worksheet_spec.rb
- spec/support/oec_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6397
The code wanted to error out on mismatch, but didn't quite know how. Spec for reassurance.
> CLC-6397 OEC: Enforce matching header rows when parsing from CSV

- src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-22623
* Also see [SISRP-22515](https://jira.berkeley.edu/browse/SISRP-22515) for more discussion (but only if you want to)
* We only want to show these links to students who have been matriculated
* Only when students have been matriculated are they given a "undergrad, grad, or law" affiliation in CS
* "Student" affiliation is given to students even when they are still "ADMT_UX", or applicant-only, in CS.  This is why we need the addition of the "undergrad, grad, or law" affiliation as well.
* Had to remove "Billing FAQ" from campuslinks.json and place it in the controller, since we also want to hide that link for applicant-only students.
> SISRP-22623 - Hide certain Financial Resources links in CalCentral PRD for individuals who do not have ‘student’ affiliation

- app/controllers/advising_student_controller.rb
- app/controllers/hub_edo_controller.rb
- app/models/berkeley/term.rb
- app/models/hub_edos/my_student_attributes.rb
- app/models/hub_edos/student_attributes.rb
- app/models/my_registrations/my_registrations.rb
- config/routes.rb
- fixtures/json/hub_student_attributes.json
- public/dummy/json/hub_student_attributes.json
- public/dummy/json/my_registrations.json
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/factories/studentAttributesFactory.js
- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
Also includes:
* SISRP-23069 - Update Status and Holds on User Overview (Advisors)
* SISRP-23070 - Refactor My Academics for Status and Holds Card
* NOJIRA - Misc Status & Hold Unit Test Fixes
Stuff:
* Apologies for the huge PR.  
* I realize that we're using undergraduate Add/Drop date to drive CNP action for Grad/Law students.  This logic is due to the lack of a "Grad CNP" date from the Terms API, but it was a functional decision to have Grad/Law CNP action taken 5 weeks into the term, which fits perfectly with undergraduate add/drop date.
* The logic for what we show and when can get pretty complex.  The [Design JIRA](https://jira.berkeley.edu/browse/SISRP-13817) lays out things pretty well, which also links to a [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1Pl_eS5uxKT-hj …
> SISRP-22752 - Add CNP to Status and Holds, Update Popover

- app/controllers/campus_solutions/enrollment_verification_deeplink_controller.rb
- app/models/campus_solutions/enrollment_verification_deeplink.rb
- config/routes.rb
- config/settings.yml
- fixtures/json/enrollment_verification_deeplink.json
- public/dummy/json/enrollment_verification_deeplink.json
- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/javascripts/angular/factories/enrollmentVerificationFactory.js
- src/assets/stylesheets/_enrollment_verification.scss
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-22703
* Design JIRA:  https://jira.berkeley.edu/browse/SISRP-15681
* The feature flag for `enrollment_verification_deeplink` will be flipped once the CS mod is done.  This has been approved for the no-fly zone, if necessary.
* Deeplink is hardcoded since we are transitioning to the Links API, but to my understanding the API won't be ready to be used until post GL6.
* In the meantime, we'll be showing the link to the Google doc.
* For testing, we are able to use the same Google Doc, with the request that we prepend "test-" in front of the test ID used.
> SISRP-22703 - Add Link to CS Enrollment Verification

- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
https://jira.berkeley.edu/browse/SISRP-23165
* This is a QA only PR, since our Master and QA branches deviate on how to handle `holds` for the Enrollment Card.
* This change is needed since coercing an empty array into a boolean results in a `true` value - as described [in this helpful article](http://james.padolsey.com/javascript/truthy-falsey/)
* The JIRA also contains another bug regarding registration status, which I will open in a separate PR that matches a fix for Master (more details in JIRA comments)
> [QA] SISRP-23165 - Enrollment Card Holds Fix - QA Only

- src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-23165
* There is an extra count in the popover because we are counting "Not Officially Registered" terms without the S09 service indicator attached to it.  We want to make non-S09 terms invisible to students until S09 has been attached to the specific term.
* JIRA also outlines a Holds bug for the Enrollment Card that is already fixed on Master, due to @redconfetti's refactoring.
* I do think this should be a QA PR as well, as students will be receiving an alert when they shouldn't be.  Let me know if you agree & I'll open a QA PR.
> SISRP-23165 - Header Popover alert has alert, but no hold/bock details

- app/models/berkeley/user_roles.rb
- app/models/user/aggregated_attributes.rb
- spec/models/berkeley/user_roles_spec.rb
- spec/models/user/aggregated_attributes_spec.rb
- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-23217
QA-FIRST PR!
This bug was caused by a disconnect between two levels of CalCentral code. One class added the CS Affiliations as User Roles, then a class farther up carefully filtered them out again.
The motivation behind this split-brain behavior is far in the past, and we can instead now use the UserRoles class as a single trusted source.
> [QA] SISRP-23217 Enable GRADUATE, UNDERGRAD CS Affiliations

- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-23183
* Start to pull from correct hub property, despite the hub pulling the wrong field from CS.
* So for now, this message will be hardcoded in the front-end.
* Also fixes a typo for `<div data-ng-if="!registration.positveIndicators.R99">` =(
> [QA] SISRP-23183 - Graduate students - Exception from CNP -Incomplete text in expanded view

- app/models/campus_solutions/link.rb
- spec/controllers/campus_solutions/link_controller_spec.rb
- spec/models/campus_solutions/link_spec.rb
https://jira.berkeley.edu/browse/SISRP-23223
> SISRP-23223 - CS Link API - suppress `properties` hash in front-end JSON

- app/controllers/sessions_controller.rb
- app/models/calnet_crosswalk/proxy.rb
- app/models/hub_edos/user_attributes.rb
- app/models/user/search_users.rb
- app/models/user/student.rb
- spec/controllers/sessions_controller_spec.rb
- spec/models/calnet_crosswalk/by_cs_id_spec.rb
- spec/models/calnet_crosswalk/by_uid_spec.rb
- spec/models/user/search_users_spec.rb
https://jira.berkeley.edu/browse/SISRP-23303
A bit of clarification before our code learns about CS-provided identifiers. This method actually only looks for a _legacy_ (pre-CS) Student ID.
> SISRP-23303 Rename misleading "lookup_student_id" Crosswalk method

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-23408
The print-in-Schedule-of-Classes flag is not intended to suppress section meeting times and locations for enrolled students and assigned teaching staff.
> SISRP-23408 Include all class meeting schedules for students/instructors

- app/models/campus_solutions/advising_resources.rb
- app/models/campus_solutions/link.rb
- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-21983
Link definitions are <del>still in play</del> *done* in the CS Link URL API table.
This PR includes an additional change to link.rb, to normalize LinkAPI result with CalCentral's CSLinkDirective, and adds support for `title` attributes in the CSLinkDirective.
> SISRP-21983 - 6.0d - Advising Resources - Add Appointment System & Advisor Notes links

- app/controllers/my_advising_controller.rb
- app/models/advising/my_advising.rb
- app/models/campus_solutions/advising_expiry.rb
- app/models/notifications/sis_expiry_processor.rb
- config/routes.rb
- config/settings.yml
- spec/controllers/my_advising_controller_spec.rb
- spec/models/advising/my_advising_spec.rb
https://jira.berkeley.edu/browse/SISRP-22717
We've been advised that the sis:staff:advisor ENF topic, which currently expires advising resources, will be used to expire advising appointments as well.
> SISRP-22717 Merged model and controller for advising card

- app/controllers/my_clearing_house_url_controller.rb
- app/models/clearing_house/my_clearing_house_url.rb
- config/routes.rb
- config/settings.yml
- config/settings/testext.yml
- fixtures/html/my_clearing_house_url.html
- spec/controllers/my_clearing_house_url_controller_spec.rb
- spec/models/clearing_house/my_clearing_house_url_spec.rb
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-23275
* @raydavis, I had attempted to figure out how to get Mockable to render the HTML given back to us by NSC, unfortunately I couldn't figure it out and due to time constraints had to instead return an empty object in fake mode =\.  Let me know if this is acceptable.
* This is also my first time attempting handling raised errors, so I'd appreciate a review on if I had correctly implemented that aspect.
* For more information on why I had to set "Referer" and "User-Agent" headers in the API call, see the attached guides at parent JIRA [SISRP-23271](https://jira.berkeley.edu/browse/SISRP-23271)
> SISRP-23275 - 6.0d - Add Clearinghouse link to Enrollment Verification page

- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-23757
* Since the Terms API will start bumping Summer 2016 out of "Current" and replace it with Fall 2016, this problem of not expiring visibility for Summer regstatus should actually take care of itself - this is just a precaution.
* Let me know if I should make a QA PR for this as well, since Summer 2016 term ends on 8/12 according to the Terms API.  But as I had stated, this problem should take care of itself.
> SISRP-23757 - Ensure Summer 2016 Regstatus Expires after End of Instruction

- app/models/hub_edos/user_attributes.rb
https://jira.berkeley.edu/browse/SISRP-23714
This is a very focused fix for the regression in QA. It leaves the underlying issue (loss of the noStudentId flag from component Hub feeds) in place.
> SISRP-23714 Handle Hub EDOs feeds which lack identifiers

- app/controllers/campus_solutions/enrollment_verification_deeplink_controller.rb
- app/controllers/campus_solutions/enrollment_verification_messages_controller.rb
https://jira.berkeley.edu/browse/SISRP-23777
* See comments for why I did not include `DisallowAdvisorViewAs` or `DisallowClassicViewAs` for `verification_enrollment_messages.rb`.
> SISRP-23777 - Enrollment verification - advisors have access to /api/campus_solutions endpoints

- src/assets/javascripts/angular/controllers/widgets/billingController.js
https://jira.berkeley.edu/browse/SISRP-23528
* Lots of good conversation in the JIRA comments
* Bottom line, CS has a peculiar method of assessing financial line items which cause "obsolete" line items with `amount === 0 && balance === 0` to come through.
* The functional team would really like to get this fix in for 6.0d, would it be possible to put in a QA PR for this as well?
> SISRP-23528 - Cal Central Suppress zero amounts in billing details

- app/models/canvas/course_sections.rb
- spec/models/canvas/course_sections_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6425
As usual when Instructure adds pagination, we found out by our payloads suddenly being restricted to 10 items.
> CLC-6425 Add pagination to Canvas Course Sections API call

- app/models/canvas/course_sections.rb
- spec/models/canvas/course_sections_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5780
@pfarestveit suggested and the bCourses service lead confirmed that this is a blocker for bCourses, and that the code change needs to be in place before Summer 2016 final grading finishes and Fall 2016 course site creation enters full frenzy.
> [QA] CLC-6425 Add pagination to Canvas Course Sections API call

- app/models/my_registrations/my_registrations.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5793
EXPLANATION: All available terms are already in the Berkeley::Terms object. That logic has the smarts to know how to handle the between-terms situation so that CalCentral always has a "current" term even when the SIS does not (because of being between the official end of one term and the official beginning of the other).
When MyRegistrations unnecessarily tried to recreate the "current" term in its own code, it missed that nuance.
> [QA] SISRP-24173 Fix term-transition loss of registration status feed

- spec/models/berkeley/terms_spec.rb
There is no "fake" mode for Berkeley::Terms, so once we hit term transition, the Bamboo testext run of these tests hit unexpected results from live feeds and started failing.
> NOJIRA Fix Berkeley::Terms RSpec breakage on testext

- .scss-lint.yml
- script/front-end-test.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-5956
* scss_lint upgrade: 0.38.0 --> 0.49.0
* Per CLC-5956, I hope to resolve "scss_lint conflicts with installed executable from scss-lint" with `gem cleanup scss_lint` prior to `gem install scss_lint ...`
* I created https://jira.ets.berkeley.edu/jira/browse/CLC-6433 to "Enable PseudoElement, ColorVariable linters (scss_lint) and fix corresponding issues"
> CLC-5956, upgrade scss_lint to 0.49.0; disable linters: PseudoElement, ColorVariable

- app/models/my_academics/college_and_level.rb
- fixtures/json/hub_academic_status.json
- public/dummy/json/academics.json
- public/dummy/json/hub_academic_status.json
- spec/models/hub_edos/academic_status_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/my_badges/student_info_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicProfileController.js
- src/assets/javascripts/angular/controllers/widgets/photoController.js
- src/assets/javascripts/angular/controllers/widgets/transferCreditController.js
- src/assets/stylesheets/_profile.scss
- src/assets/templates/academics_student_profile.html
- src/assets/templates/widgets/academics/college_and_level.html
Note: This includes the refactor from [SISRP-23083](https://jira.berkeley.edu/browse/SISRP-23083) that was reverted and excluded from the GL 6.0 and GL 6.0d releases.
It also includes the renaming of `photoController.js` as `academicProfileController.js` mentioned in [Ray's comments](https://jira.berkeley.edu/browse/SISRP-23083?focusedCommentId=390629&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-390629) within SISRP-23083.
https://jira.berkeley.edu/browse/SISRP-23083
https://jira.berkeley.edu/browse/SISRP-22377
> SISRP-22377 - 7.0 - My Academics - Academic Profile - Exp Grad Term

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-24452
This PR does a couple things:
* Expands "Not Enrolled" status - previously students would only see "Not enrolled" if they were at 0 units + it was past CNP action.  This makes it so that students will be "Not Enrolled" if they are at 0 enrolled units, regardless of current date.
* Switches academic career checks from `/api/my/status` to term-specific `registration.academicCareer.code`.  This will minimize any potential `roles` conflicts (e.g. for a student going from undergrad to grad), as well as enable advisors to view whatever the student is viewing.
* Since advisor user overview is no long reliant on `/api/my/status`, we can start surfacing intended message catalog messages for academicCareer-specific student messaging.
> SISRP-24452 - Students with no reg, 0 units should see 'Not Enrolled' status alone but there is no registration section at all

- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-24774
Notes for this PR:
* Since we are showing up to two terms (current and next), we need to enable the "Status" section to show if either of these terms are applicable to show registration status.  The changes in `$scope.$watchGroup` reflects this need.
* Uses term-specific career code "UCBX" to determine whether or not we should show that term's regstatus, which is more reliable due to possible conflicting `roles`.
> SISRP-24774 - Concurrent Enrollment Student (Sep 24th) - shouldn't display any REG status.

- app/models/my_academics/college_and_level.rb
- app/models/my_academics/gpa_units.rb
- spec/models/my_academics/gpa_units_spec.rb
bug fix where I cloned the response obj to be changed in the college_and_level rather than the response obj being changed itself which led to a bug downstream when response was being referenced by the hub_gpa_units module.
followed API spec for pulling the equivalent of "totalUnitsAttempted" field from CS similar to what was provided by legacy
> SISRP-24125 - My Academics>[term name] - GPA Calculator (ID and add CS total-units-at-risk-in-letter-grade-attempts equivalent)

- app/models/calnet_ldap/client.rb
- app/models/user/api.rb
* @redconfetti suggested it was time to start noticing when supposedly active students don't have a Campus Solutions ID, & I agree with him.
* DEBUG-level logging of raw responses from most upstream APIs is invaluable when investigating issues or generating tests, but our CalNet LDAP client missed that step.
> NOJIRA Additional logging to help production support & bug investigation

- spec/ui_selenium/my_profile_basic_info_spec.rb
- spec/ui_selenium/my_profile_bconnected_spec.rb
Nightly UI tests (Selenium) fail often w.r.t MyProfile specs. Is it due to a sleepy Hub API? Nonetheless, the fix is to only run 'em locally.  cc: @pfarestveit
> NOJIRA, nightly Selenium on Bamboo: do not run my_profile_basic_info_spec

- app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6441
OEC was not invited to the party in #5670.
> CLC-6441 Include 'stop further enrollment' sections in OEC queries

- app/models/user/parser.rb
- spec/models/calnet_ldap/user_attributes_spec.rb
QA-first PR for https://jira.ets.berkeley.edu/jira/browse/CLC-6440.
> [QA] CLC-6440 When LDAP 'mail' attribute is missing, fall back to berkeleyEduOfficialEmail

- app/models/user/parser.rb
- spec/models/calnet_ldap/user_attributes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6440
Master-branch version of #5858.
> CLC-6440 When LDAP 'mail' attribute is missing, fall back to berkeleyEduOfficialEmail

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
Code change addresses 2 jiras:
- https://jira.berkeley.edu/browse/SISRP-25322
- https://jira.berkeley.edu/browse/SISRP-25324
> SISRP-25322 - My Academics - Profile Card - Expected Graduation - Displaying as "2016 Fall" instead of "Fall 2016"

- app/models/my_academics/exams.rb
- public/dummy/json/academics_interim_two_sets_conflicts.json
- spec/models/my_academics/exams_spec.rb
Follow up to https://jira.berkeley.edu/browse/SISRP-15935, remove the "curr" field to declutter the examSchedules field.
Previous PR: https://github.com/ets-berkeley-edu/calcentral/pull/5833
> SISRP-15935 Remove extra current field in exams

- app/models/campus_solutions/link.rb
- spec/models/campus_solutions/link_spec.rb
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/templates/widgets/student_resources.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5871
Main jira: https://jira.berkeley.edu/browse/SISRP-24502
Addresses the TypeError messages.
Realized too late I included the fix to this related jira: https://jira.berkeley.edu/browse/SISRP-24174
Addresses infinite spinner on student resources.
> [ QA ] SISRP-24502 - CalCentral prod: FATAL TypeError (can't convert nil into String) at campus_solutions/link.rb:47: 'get_url'

- app/models/my_groups/merged.rb
- config/settings.yml
- public/dummy/json/groups.json
- src/assets/javascripts/angular/services/updatedFeedsService.js
https://jira.berkeley.edu/browse/SISRP-25121
First of about a half-dozen cache structure changes to reduce load.
Removed LiveUpdatesEnabled because the "My Groups" feed is not volatile or important enough to require an update every 2 minutes.
Removed JsonAddedCacher because the feed's not long and complex enough to benefit from cached JSON, and it's referred to from another class on the server side.
> SISRP-25121 Reduce caching load of MyGroups

- app/models/edo_oracle/course_sections.rb
- app/models/edo_oracle/queries.rb
- app/models/my_academics/exams.rb
- spec/models/edo_oracle/course_sections_spec.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/my_academics/exams_spec.rb
https://jira.berkeley.edu/browse/SISRP-23422
Note: We still check whether CS data is available based on whether we are 8 weeks before the end of the term. If functionals do not approve, we can change the date in a following pull request.
Update: alternate exams that are not in finals week (in which instructors deliberately change the final exam time) will NOT be in this data, but there is a field called "Alternate Method" somewhere in which we can specify that the exam may be different. Still getting details.
May be missing some test cases. Open to any ideas you may have; thanks!
> SISRP-23422 Final Exam Schedule Use CS Data

- app/controllers/advising_student_controller.rb
- app/controllers/my_academics_controller.rb
- app/models/canvas_csv/provide_course_site.rb
- app/models/my_academics/filtered_for_advisor.rb
- config/settings.yml
- spec/controllers/advising_student_controller_spec.rb
- spec/controllers/my_academics_controller_spec.rb
- spec/models/canvas_csv/provide_course_site_spec.rb
- spec/models/my_academics/filtered_for_advisor_spec.rb
- spec/models/my_academics/merged_spec.rb
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-25121
Front-end code does not check My Academics for Live Updates & so the feed should not be repeatedly pinged by server-side warming.
MyAcademics::Merged can be cached in JSON form thanks to the addition of FilteredForAdvisor.
This also fixes an inconsistency between Advisor View-As & User Overview.
> SISRP-25121 Reduce caching load of MyAcademics

- app/models/edo_oracle/adapters/oec.rb
- app/models/oec/queries.rb
- spec/models/edo_oracle/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6444
Follow-up to fix Bamboo failures in #5897, my fault for trying to refactor on the cheap. Also unleashes a portion of the testext suite previously wrapped in a `pending`.
Bamboo with no OEC failures at https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT384-1
> CLC-6444 Refactor and improve OEC testext specs

- app/models/edo_oracle/queries.rb
- app/models/rosters/campus.rb
- spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-25648
* Added maxEnroll, maxWaitlist columns to secondary sections DB query to fix bogus 0 amounts.
* Fixed string-vs.-symbol mix-up in logic which derives enrolled and waitlisted enrollment counts. This PR switches to the front-end's classification logic.
> SISRP-25648 Fixes to class Enrollment Section Overview capacity, counts

- app/models/campus_solutions/advising_resources.rb
- spec/controllers/campus_solutions/advising_resources_controller_spec.rb
- spec/models/campus_solutions/advising_resources_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-25750
+ Should display links listed in design at https://jira.berkeley.edu/browse/SISRP-25611
+ `Schedule of Classes` and `WebNow Documents` links come from advisor resources api, the rest come from the link api.
+ Should suppress the `Academic Progress Reports` link until 7.2.
> SISRP-25750 - 7.1 - Retrofit Advising Resources links to the link API

- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-25196
[academics_classinfo.html](https://github.com/ets-berkeley-edu/calcentral/blob/v82/src/assets/templates/academics_classinfo.html#L264) includes this directive twice on one page, leading to screen reader problems.
The directive JS sets "studentRole" to either "waitlisted" or "enrolled".
> SISRP-25196 Avoid duplicate element IDs in academics-class-info-enrollment-directive

- spec/models/campus_solutions/student_outstanding_balance_spec.rb
- spec/models/campus_solutions/student_term_gpa_spec.rb
https://jira.berkeley.edu/browse/SISRP-26144
* The problem stemmed from me re-using shared tests, when they really weren't applicable.
* Due to them being testext tests, the mistake snuck past through to Bamboo.
> SISRP-26144 - Broken integration tests from Student Success work

- app/models/edo_oracle/adapters/oec.rb
- app/models/edo_oracle/connection.rb
- app/models/edo_oracle/oec.rb
- app/models/oec/merged_sheet_validation.rb
- app/models/oec/queries.rb
- app/models/oec/sis_import_sheet.rb
- app/models/oec/worksheet.rb
- app/models/oec/worksheet_row.rb
- config/settings.yml
- spec/models/edo_oracle/adapters/oec_spec.rb
- spec/models/edo_oracle/oec_spec.rb
- spec/models/oec/create_confirmation_sheets_task_spec.rb
- spec/models/oec/merge_confirmation_sheets_task_spec.rb
- spec/models/oec/publish_task_spec.rb
- spec/models/oec/queries_spec.rb
- spec/models/oec/term_setup_task_spec.rb
- spec/support/oec_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6444
Bamboo: https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT384-13/
This PR does two things, split into two commits.
Part one reworks the enrollments query. Used to be, when gathering student and enrollment data for OEC, we would query Oracle only for sections we cared about, and would run two separate queries on those sections: a get_enrollments query that returned section-ID/UID associations, and a get_students query that used SELECT DISTINCT to return unique rows of student data.
Now that we have more than 4000 evaluated sections in production, our giant list is hobbling the database. We ditch the list, run a single query to get all student and enrollment data for the term, and post-process in code.
Our standard DB-facing code does …
> CLC-6444 OEC: Reduce memory overhead of enrollments query and worksheet processing

- app/controllers/my_academics_controller.rb
- spec/controllers/my_academics_controller_spec.rb
- spec/models/my_academics/filtered_for_delegate_spec.rb
https://jira.berkeley.edu/browse/SISRP-25001
- Breaks unit test dependency on BearFacts; replaces detailed low-level unit tests with higher-level tests for delegate and advisor access
- Fixes MyAcademicsController.residency so it always returns JSON
> SISRP-25001 - Test Fixtures Still Rely on Bearfacts / Legacy Data

- app/models/edo_oracle/course_sections.rb
- app/models/edo_oracle/queries.rb
- app/models/my_academics/exams.rb
- spec/models/edo_oracle/course_sections_spec.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/my_academics/exams_spec.rb
https://jira.berkeley.edu/browse/SISRP-25993
- Incorporate classes that have an alternate method of final exams or no exam at all.
Note: I did a hacky thing, in order to send a class that has no exam and an alternate method to the bottom, I set its Time field to something like the year 999999. If this isn't a good way to go, I'm open to other suggestions.
I apologize for this being late, not sure whether this should be cherry-picked into QA, but this should be the final piece to the final exam schedule feature.
> SISRP-25993 - Final Exam Schedule Incorporate Course Exceptions

- src/assets/templates/widgets/enrollment/consult_advisor.html
https://jira.berkeley.edu/browse/SISRP-20510
removed inconsistency in displaying notification icons. using <span> tags instead of <div> tags for enrollment card holds icon is consistent with other card using similar icons. This also removed the required cc-flex style which created an inconsistent look/spacing on safari based browsers.
> SISRP-20510 - Hold icon on Enrollment card rendering poorly on iOS

- app/models/my_academics/exams.rb
https://jira.berkeley.edu/browse/SISRP-26305
* `course` variable name was overwriting the original `|course|` input parameter, this became a problem for students taking two of the same classes, as the 2nd `course` would try to parse the first, already-parsed `course`.
> SISRP-26305 - MyAcademics::Exams for UID 1064465: NoMethodError: undefined method gsub for nil:NilClass

- app/models/edo_oracle/adapters/common.rb
- spec/models/edo_oracle/adapters/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6453
cc: @paulkerschen 
The new 'PROXY' instructor role-code is coming soon. At the very least, we should not `raise ArgumentError` when the role-code lands. Future PRs will address specific business logic concerns. E.g., OEC.
Fyi, (personal) Bamboo build in-progress: https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CJT85-2
> CLC-6453, instructor role-code 'PROXY' assists instructor(s) with grading (e.g., Head GSI)

- app/models/edo_oracle/adapters/oec.rb
- app/models/oec/sis_import_task.rb
- fixtures/oec/courses_for_dept_SPANISH.json
- spec/models/oec/sis_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6448
https://jira.ets.berkeley.edu/jira/browse/CLC-6449
Note that because of this special handling, we no longer get to set evaluation type ahead of time in EdoOracle::Adapters::Oec.
> CLC-6448 CLC-6449 OEC: special handling for Law and Spanish/Portuguese depts

- spec/models/calnet_ldap/client_spec.rb
- spec/models/calnet_ldap/user_attributes_spec.rb
This is a reaction to Bamboo build failure: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPMASTER-JOB1-4600/test/case/60932119
This PR only adjust expectation in the spec. CalCentral code is not touched – it references the `:berkeleyeduaffiliations` attribute in only `Berkeley::UserRoles`:
```
affiliations = ldap_record[:berkeleyeduaffiliations].to_a
```
*Bottom line:* It's not a problem if CalNetLdap returns an `Enumerable` instead of `Net::BER::BerIdentifiedArray`.  Our code will not know the difference.
> NOJIRA, CalNetLdap search returns berkeleyeduaffiliations as Enumerable

- app/models/campus_solutions/student_resources.rb
https://jira.berkeley.edu/browse/SISRP-26598
Links names in the ruby model were not camelized correctly for the JavaScript or template
> SISRP-26598 - Student Dashboard Resources Card links are missing

- app/models/my_academics/filtered_for_delegate.rb
- src/assets/templates/academics.html
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-26567
* Good bug - led to the decision not to surface Final Exams to delegates, more info in the JIRA.
* Also included a CSS fix
* Also included an `!isAdvisingStudentLookup` conditional that was accidentally removed in #5905.  This makes it so that advisors don't see the "Book List" link on the User Overview page.  As it stands, if an advisor clicks on that link, they will be taken to a 404 page.
> SISRP-26567 - MyAcademics::Exams for UID 1507981: NoMethodError: undefined method final_exam_cs_data_available for nil:NilClass

- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-26595
+ Problem caused by not using the cc-campus-solutions-link-item-directive for items from the Link API.
+ The change here will fix the 2 eForms links, and the Multi-Year Planner link.
+ The WebNow and Schedule of Classes links come from another API that does not provide hover text.
+ The Academic Progress Report should not be visible in 7.1
> SISRP-26595 - Advisor Resources link hover text isn't always included in the markup

- app/models/my_academics/exams.rb
- spec/models/my_academics/exams_spec.rb
https://jira.berkeley.edu/browse/SISRP-26727
Replaced method to completely remove letters from the course code. Things like 'C242C' would become '0' instead of '242', so it was replaced.
> SISRP-26727 - Final exams graduate courses should not show up in interim

- app/models/my_academics/exams.rb
- spec/models/my_academics/exams_spec.rb
https://jira.berkeley.edu/browse/SISRP-26727
Master PR: https://github.com/ets-berkeley-edu/calcentral/pull/5990
Replaced method to completely remove letters from the course code. Things like 'C242C' would become '0' instead of '242', so it was replaced.
> [QA] SISRP-26727 - Final exams graduate courses should not show up in interim

- public/dummy/json/academics_interim_two_sets_conflicts.json
- src/assets/templates/academics.html
- src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-26668
Removed messaging for graduate students once cs data becomes available. Also showed the card back to law students, in which they will see the same messages as grad students.
The most important changes are located in academics.html and final_exam_schedule.html (both one line changes), the others in academics_interim_two_sets_conflicts.json was just to test those front-end changes.
> SISRP-26668 - Final exams conflicting messaging

- public/dummy/json/academics_interim_two_sets_conflicts.json
- src/assets/templates/academics.html
- src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-26668
Master PR: https://github.com/ets-berkeley-edu/calcentral/pull/5988
Removed messaging for graduate students once cs data becomes available. Also showed the card back to law students, in which they will see the same messages as grad students.
The most important changes are located in academics.html and final_exam_schedule.html (both one line changes), the others in academics_interim_two_sets_conflicts.json was just to test those front-end changes.
> [QA] SISRP-26668 - Final exams conflicting messaging

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- spec/models/campus_solutions/advising_resources_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-26666
+ removes the Schedule of Classes link from Dashboard Advisor Resources
+ adds hover text to WebNow Documents link in Dashboard Advisor Resources
+ adds hover text to student-specific Schedule Planner link on Student Overview (Advisor Resources)
Release Notes for 7.1 updated - remove `cs_advising_scheduler_view` flag from all environments:
https://confluence.ets.berkeley.edu/confluence/pages/viewpage.action?spaceKey=MYB&title=Release-Specific+Instructions
> SISRP-26666 - Advising Resources - should not include 'Schedule of Classes - Scheduler View' link

- app/controllers/photo_controller.rb
- app/policies/authentication_state_policy.rb
- config/routes.rb
- spec/controllers/photo_controller_spec.rb
- src/assets/javascripts/angular/directives/profileImageDirective.js
- src/assets/stylesheets/_profile_image.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/widgets/delegate_student_img.html
- src/assets/templates/widgets/profile_img.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-22665
- Adds a new endpoint to return a photo for a specified UID (only available to advisors and superusers)
- Adds a directive that calls that endpoint and displays the photo
I was hoping to move the authorization logic from the angular templates into the PhotoController for better security.  That way a single endpoint could return either the requested person's photo, or the generic bear photo if the requestor is not authorized (e.g., a delegate).  
HOWEVER, the generic bear photo is an SVG.  I tried having the endpoint send the SVG but it wouldn't render.  It works when that file is requested by delegate_student_img.html.  Didn't want to spend too much time figuring it out, but if anyone knows a quick solution I'd love to hear it!  That would …
> SISRP-22665 - Displays profile image instead of default image on advisor Student Lookup

- script/export-cached-csv-enrollments-set.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6460
Give `export-cached-csv-enrollments-set.sh` same JVM args used by other Canvas scripts.
> CLC-6460, add -J-Xmx1024m to avoid OOM error in export-cached-csv-enrollments-set.sh

- app/models/campus_solutions/student_term_gpa.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/student_success/gpa_trends.html
https://jira.berkeley.edu/browse/SISRP-26676
* The JIRA title is a bit misleading - bottom line, we want to suppress the current term GPA because CS will always return 0.0, as grades have not been entered yet.
* We still want to show the term though
> SISRP-26676 - Student Success Card needs to suppress current term GPA

- app/models/user/api.rb
- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-26772
We leverage the existing call to `User::HasStudentHistory.has_student_history?`. Note: relying on `CampusSolutions::Billing` to decide if `has_financials_tab?` is risky w.r.t performance.
> SISRP-26772, My Finances tab if student or has_student_history

- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-26745
Second fix added in template for the multi-year planner link (should open in new window): https://jira.berkeley.edu/browse/SISRP-26746
> SISRP-26745 - Advising Resources - Advising Assignments link is missing

- app/controllers/canvas_mailing_lists_controller.rb
- app/models/mailing_lists/calmail_list.rb
- app/models/mailing_lists/mailgun_list.rb
- app/models/mailing_lists/member.rb
- app/models/mailing_lists/site_mailing_list.rb
- config/settings.yml
- db/developer-seed-data.sql
- db/migrate/20161017234930_add_type_to_canvas_site_mailing_lists.rb
- db/migrate/20161017235830_create_canvas_site_mailing_list_members.rb
- db/schema.rb
- spec/controllers/canvas_mailing_lists_controller_spec.rb
- spec/models/mailing_lists/calmail_list_spec.rb
- spec/models/mailing_lists/mailgun_list_spec.rb
- spec/support/mailing_list_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6464
https://jira.ets.berkeley.edu/jira/browse/CLC-6465
We handle the split between old Calmail lists and new Mailgun lists by creating two subclasses for MailingLists::SiteMailingList, and using Rails single-table inheritance to associate those subclasses with a new `type` column. For now, lists created through the bCourses admin tool still default to Calmail.
Membership logic for Mailgun lists is a bit simpler than that for Calmail, since we're using a local database rather than an external API. However, we do now need to track "is sender?" permissions, since no external service is managing those.
Bamboo build https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CPT389-2 has no mailing list failures.
> CLC-6464 CLC-6465 New tables and models for mailing lists; adapt sync logic

- app/models/campus_solutions/proxy.rb
- spec/models/campus_solutions/proxy_spec.rb
https://jira.berkeley.edu/browse/SISRP-25362 (ticket not related; I ran into this issue working on the degree progress API but it was a preexisting issue)
If we try to hit a CS endpoint that doesn't exist, we'll get a string response but a successful status code.  This fix will flag it as an error so we can properly deal with it and avoid `TypeError`s down the line.
> SISRP-25362 - adds handling for CS API error responses with status=200

- app/models/my_academics/exams.rb
- public/dummy/json/academics.json
- spec/models/my_academics/exams_spec.rb
- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-26288
Design: https://jira.berkeley.edu/browse/SISRP-22748
Pull request to get some feelers out to devs. Essentially the purpose is to show instructors their scheduled final exam slot on the class page so they know whether to cancel or hold their final exam at that time. Most of this is in the `assign_exam_to_instructor` method, which copies and utilizes many of the already existing methods in `exams.rb` (which is both good and bad...). Any comments will be appreciated!
More information and what it's supposed to look like on the JIRA!
> SISRP-26288 - Show instructors their scheduled final exam

- app/models/edo_oracle/adapters/common.rb
- spec/models/edo_oracle/adapters/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6474
https://jira.berkeley.edu/browse/SISRP-27043
Misunderstanding in official code. Short name is `5-PROXY` but value received by CalCentral is `APRX`. This wrongness in CalCentral is causing Canvas refresh script to fail. See JIRAs for more info.
> SISRP-27043, instructor role-code (IRC) is APRX, not PROXY

- script/calcentral-update.sh
- script/calendar.sh
- script/configure-all-canvas-apps-from-current-host.sh
- script/export-cached-csv-enrollments-set.sh
- script/load-test-dev.sh
- script/memcached-stats.sh
- script/migrate.sh
- script/reconfigure-canvas-test-servers.sh
- script/refresh-all-canvas-enrollments.sh
- script/refresh-canvas-enrollments.sh
- script/refresh-canvas-users.sh
- script/report-lti-usage.sh
- script/report-turnitin-usage.sh
- script/run-oec-task.sh
- script/standard-calcentral-JVM-OPTS-profile
- script/start-torquebox.sh
- script/stop-torquebox.sh
- script/sync-canvas-guest-users.sh
- script/sync-canvas-new-users.sh
- script/update-mailing-list-memberships.sh
- script/webcast_lti_refresh.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6475
New `script/standard-calcentral-JVM-OPTS-profile` to be sourced by scripts needing our default JVM/JRUBY args. In this JIRA, the OutOfMemoryError was hit by `sync-canvas-new-users.sh` but it could happen in other Canvas related scripts running nothing more than `export JRUBY_OPTS="--dev"`
In addition to standardization in many of our shell scripts, this PR does tidying which makes the scripts more readable and reliable.
> CLC-6475, we risk OutOfMemoryError in scripts not using standard JVM arg setup

- app/models/rosters/campus.rb
https://jira.berkeley.edu/browse/SISRP-21920
Just in case this fix doesn't make it into GoLive 7.2, we should stop logging in Production.
> SISRP-21920 - Downgrade enrollment limit calculation error to DEBUG level

- script/calcentral-update.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6475
Prior to PR #6041, we had `source .rvmrc`. In my preference for absolute paths, I changed it to `source "${PWD}/.rvmrc"`.  That might have made Bamboo unhappy: https://bamboo.ets.berkeley.edu/bamboo/browse/CLCD-CQDC
After this merge, if Bamboo passes then I'll restore `source .rvmrc` (relative path) on all scripts.
> CLC-6475, revert to 'source' on relative path in calcentral-update

- app/models/eft/my_eft_enrollment.rb
- spec/models/eft/my_eft_enrollment_spec.rb
- src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-27057
* `#get_internal` was getting hit, and returning `{}` because `@campus_solutions_id` would not be available yet.  `@campus_solutions_id` becomes available when `#get_parsed_response` calls `#lookup_student_id`
* So, we were not making the API call, and sending the front-end an empty object.  I've added some logging to help diagnose this, and moved the call to `#lookup_student_id` to the correct place.  Also added a nil-check security blanket for the front-end.
* It's perplexing because I'm not sure why this was previously working.  It shouldn't have - the only thing I can think of that might have changed are @raydavis's recent changes to the caching mechanisms.  But even tracing those thru their histories, I couldn't find any bypass of …
> SISRP-27057 - CalCentral Prod: EFT status & EFT account info not displaying

- app/controllers/advising_student_controller.rb
- app/models/berkeley/degree_progress.rb
- app/models/campus_solutions/degree_progress_feature_flagged.rb
- app/models/campus_solutions/degree_progress_grad_advising_feature_flagged.rb
- app/models/campus_solutions/degree_progress_grad_student_feature_flagged.rb
- app/models/degree_progress/graduate_milestones.rb
- app/models/degree_progress/milestones_module.rb
- app/models/degree_progress/my_graduate_milestones.rb
- app/policies/authentication_state_policy.rb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- script/sis/verify_sis_api_endpoints.sh
- spec/controllers/advising_student_controller_spec.rb
- spec/controllers/campus_solutions/degree_progress_controller_spec.rb
- spec/models/berkeley/degree_progress_spec.rb
- spec/models/degree_progress/graduate_milestones_spec.rb
- spec/models/degree_progress/my_graduate_milestones_spec.rb
- spec/support/campus_solutions_helper_module.rb
- spec/support/degree_progress_shared_examples.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academics/degreeProgressController.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/templates/academics.html
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academics/degree_progress_graduate.html
Advisors will see the Degree Progress card when they do Student Lookup on a GRAD or LAW student.
I added a separate feature flag for the advisor version of the card.  The advisor version is planned for 7.2 and the student version is planned for 7.3+ at the moment.
This is the UI side of the work; the backend work was reviewed under https://github.com/ets-berkeley-edu/calcentral/pull/6027.
> SISRP-25362 - Adds Degree Progress (GRAD) card to Student Overview

- app/controllers/mailing_lists_message_controller.rb
- app/models/mailgun/proxy.rb
- app/models/mailgun/send_message.rb
- app/models/mailing_lists/outgoing_message.rb
- spec/controllers/mailing_lists_message_controller_spec.rb
- spec/models/mailgun/send_message_spec.rb
- spec/models/mailing_lists/incoming_message_spec.rb
- spec/models/mailing_lists/outgoing_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6471
Since attachment handling involves multipart file upload, which isn't supported by HTTParty, we have to switch the Mailgun proxy over to unpartying old Faraday.
> CLC-6471 bCourses mailing lists: send authenticated messages to list members

- app/models/mailing_lists/mailgun_list.rb
- app/models/mailing_lists/site_mailing_list.rb
- src/assets/javascripts/angular/controllers/pages/canvasSiteMailingListController.js
- src/assets/javascripts/angular/factories/canvasSiteMailingListFactory.js
- src/assets/stylesheets/_canvas_site_mailing_list.scss
- src/assets/templates/canvas_embedded/site_mailing_list.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6480
The Mailgun workflow is simpler than the CalMail workflow. CalMail lists are first "registered" in the Junction database and then created in CalMail; but Mailgun lists live only in Junction and can be created in one shot.
A couple of methods are moved into the MailingLists::SiteMailingList superclass to avoid errors when we first instantiate a placeholder list without yet knowing what subclass it will be.
> CLC-6480 bCourses mailing lists: tweak admin tool to handle Mailgun lists

- app/controllers/mailing_lists_message_controller.rb
- app/models/mailing_lists/incoming_message.rb
- config/routes.rb
- spec/controllers/mailing_lists_message_controller_spec.rb
- spec/models/mailing_lists/incoming_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6467
End-to-end testing immediately proves its worth! The Rails controller has its own uses for `dispatch` and doesn't like having its toes stepped on.
> CLC-6467 bCourses mailing lists: stay out of ActionController's vocabulary

- app/models/campus_oracle/queries.rb
- app/models/canvas_lti/course_add_user.rb
- spec/models/campus_oracle/queries_spec.rb
- spec/models/canvas_lti/course_add_user_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6481
Filtering them after the SQL query leads to bogus null results or peculiar result counts.
> CLC-6481 Exclude inactive accounts from bCourses DB queries

- app/models/mailing_lists/incoming_message.rb
- app/models/mailing_lists/outgoing_message.rb
- app/models/mailing_lists/site_mailing_list.rb
- db/developer-seed-data.sql
- db/migrate/20161026183144_add_canvas_site_name_to_canvas_site_mailing_lists.rb
- db/schema.rb
- spec/models/mailing_lists/incoming_message_spec.rb
- spec/models/mailing_lists/outgoing_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6471
Follow-up to #6053 with a few improvements:
- Handle the magic suffixes that will route test messages to non-prod environments;
- JSONify the outgoing `recipient-variables` param so Mailgun handles it properly;
- Add the Canvas site name to the sender's display name (which requires us to store the site name on our end).
> CLC-6471 bCourses mailing lists: improvements to message forwarding

- app/models/calnet_ldap/client.rb
https://jira.berkeley.edu/browse/SISRP-26579
Unconstrained name searches can take more than a half-hour to complete, mostly due to the poor performance of data fetches from CS Hub.
> SISRP-26579 Limit size of advisor student lookups

- app/models/mailing_lists/outgoing_message.rb
- spec/models/mailing_lists/outgoing_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6471
One more follow-up to #6053. While we may never hit this limit, per Mailgun documentation, batch sending is limited to 1000 addresses at a time.
The spec change is largely indentation; new tests are at the bottom.
> CLC-6471 bCourses mailing lists: batch recipients into groups of 1000

- app/controllers/google_auth_controller.rb
- app/controllers/oec_google_auth_controller.rb
- app/controllers/oec_tasks_controller.rb
- app/models/google_apps/oauth2_tokens_grant.rb
- app/models/google_apps/proxy.rb
- app/models/oec/api_task_wrapper.rb
- config/routes.rb
- spec/controllers/google_auth_controller_spec.rb
- spec/controllers/oec_google_auth_controller_spec.rb
- src/assets/javascripts/angular/factories/oecFactory.js
This PR is a cleaner version of #6071 (closed)
https://jira.ets.berkeley.edu/jira/browse/CLC-6478
This is the first half of the CLC-6478 story. The logic of `GoogleAuthController` was moved to a the reusable model `GoogleApps::Oauth2TokensGrant`. Next, a dedicated OEC controller was added, with stricter access rules, that allows the same kind of token management.
A lot more test coverage.
The next step will be removal OEC's client_id and client_secret from YAML.
> CLC-6478, GoogleAuthController variant to manage OEC-specific Google tokens

- app/models/mailing_lists/outgoing_message.rb
- spec/controllers/mailing_lists_message_controller_spec.rb
- spec/models/mailing_lists/outgoing_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6471
Another try at attachment handling. Local testing had encouraged a bad assumption about how Rails represents multipart uploads (custom objects, not hashes).
> CLC-6471 bCourses mailing lists: fix attachment handling

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
https://jira.berkeley.edu/browse/SISRP-26969
Replacement for #6064. Removes application of code that filters out inactive academic statuses now that the iHub Academic Status API should no longer return academic statuses that have no active plans present.
> SISRP-26969 - Remove inactive status filtering from MyAcademics::CollegeAndLevel

- app/models/my_academics/grading.rb
- config/settings.yml
- config/settings/test.yml
- spec/models/my_academics/grading_spec.rb
https://jira.berkeley.edu/browse/SISRP-27262
Add a second grading period in yml settings to allow for Law department to have different grading period. The code will check authenticated user roles for Law and use the appropriate settings from  yml for grading period.
> SISRP-27262 - Add grading period specific to Law students

- app/controllers/google_auth_controller.rb
- app/controllers/oec_google_auth_controller.rb
- app/models/canvas_csv/base.rb
- app/models/google_apps/client.rb
- app/models/google_apps/credential_store.rb
- app/models/google_apps/drive_manager.rb
- app/models/google_apps/oauth2_tokens_grant.rb
- app/models/google_apps/proxy.rb
- app/models/google_apps/revoke.rb
- app/models/google_apps/sheets_manager.rb
- app/models/oec/remote_drive.rb
- app/models/oec/task.rb
- app/models/user/oauth2_data.rb
- config/settings.yml
- spec/controllers/google_auth_controller_spec.rb
- spec/controllers/oec_google_auth_controller_spec.rb
- spec/models/google_apps/credential_store_spec.rb
- spec/models/google_apps/drive_manager_spec.rb
- spec/models/google_apps/sheets_manager_spec.rb
- spec/models/user/oauth2_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6478
Core classes in GoogleApps module now rely on `app_id` to determine which client_id, etc. to use.
> CLC-6478, eliminate need for Google access- and refresh-tokens in YAML file (OEC)

- app/models/google_apps/credential_store.rb
- spec/models/google_apps/credential_store_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6489
Two things:
1. We guarantee symbolized hash keys prior to `write_credentials`.
1. Fix 'real' rspec: `load_credentials` should not expect  custom override of expiration_time. It's purely a read operation.
> CLC-6489, DriveManager might pass non-symbol keys to CredentialStore

- app/controllers/oec_tasks_controller.rb
- spec/controllers/oec_tasks_controller_spec.rb
- src/assets/javascripts/angular/controllers/pages/oecController.js
- src/assets/templates/oec.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6493
UI will report, "...features are unavailable because no Google OAuth tokens are registered with UID 12004714. Please report this problem." Thus, less guesswork for our beleaguered OEC admin.
> CLC-6493, UI should report error if no Google OAuth tokens registered to UID of OEC

- app/models/berkeley/user_roles.rb
- app/models/user/aggregated_attributes.rb
- spec/models/berkeley/user_roles_spec.rb
- spec/models/user/aggregated_attributes_spec.rb
- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-26980
https://jira.berkeley.edu/browse/SISRP-26578
- CS is now processing Student affiliation changes in a timely fashion.
- CalNet is switching from "XYZ-STATUS-EXPIRED" to "FORMER-XYZ" affiliations.
- CalNet no longer routinely returns apparent conflicts. The old expdate logic is unneeded.
- Revised rspec mocks to reflect the sparse CS role hashes.
> SISRP-26980 SISRP-26578 Trust CS on active Student affiliation; CalNet changes

- app/models/canvas_lti/webcast_lti_refresh.rb
- spec/models/canvas_lti/webcast_lti_refresh_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6494
See `context 'Canvas reports an error'` below to understand purpose. We're not sure why it failed but at least the nightly cron won't abort. More QA will help us understand severity.
> CLC-6494, Course Capture LTI script: when Canvas Tab API call fails, log error and return nil

- app/models/canvas/course_users.rb
- app/models/mailing_lists/site_mailing_list.rb
- config/settings.yml
- fixtures/json/canvas_course_users_page_1.json
- fixtures/json/canvas_course_users_page_2.json
- spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6495
We expect this feature flag to remain turned off in the normal course of business, but QA will appreciate the ability to turn it on.
This does require adding email addresses to our Canvas::CourseUsers feed, which doesn't strike me as a serious performance concern.
> CLC-6495 bCourses mailing lists: allow email address override from Canvas

- app/models/berkeley/user_roles.rb
- app/models/user/aggregated_attributes.rb
- spec/models/berkeley/user_roles_spec.rb
- spec/models/user/aggregated_attributes_spec.rb
- spec/models/user/api_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/6092
The key CalNet change is due to land in production on Nov. 3. The key CS change has already happened. Under the circumstances, I think there's less risk with this PR than without it, despite the ludicrously limited testing.
> [QA] SISRP-26980 SISRP-26578 CS & CalNet affiliation changes

- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-26755
See QA PR #6110
The issue that was occurring was that the `isCsLink` flag is being forced in [CampusSolutions::AdvisingResources](https://github.com/ets-berkeley-edu/calcentral/blob/ed63d211/app/models/campus_solutions/advising_resources.rb#L131), which results in the link not opening in a new window... and the "ucFrom" parameter (and other related parameters) being included.
So instead of using the `ccCampusSolutionsLinkItemDirective` like we do with these links, I just broke this out into using the `ccCampusSolutionsLinkDirective` to force it to behave as specified in the JIRA (open in a new window, do not use ucFrom parameters to make CalCentral banner appear).
> SISRP-26755 - Schedule Planner link - Campus Solutions page header needs to be removed

- app/controllers/concerns/advisor_authorization.rb
- app/controllers/search_users_controller.rb
- app/models/berkeley/user_roles.rb
- app/models/user/aggregated_attributes.rb
- app/models/user/parser.rb
- spec/controllers/advising_student_controller_spec.rb
- spec/controllers/concerns/advisor_authorization_spec.rb
- spec/models/berkeley/user_roles_spec.rb
- spec/models/user/aggregated_attributes_spec.rb
- spec/models/user/search_users_by_name_spec.rb
https://jira.berkeley.edu/browse/SISRP-26578
This functional change has been approved for Sunday's release, and so a QA PR will quickly follow.
I've done a quick verification on my laptop against the Dev LDAP server.
> SISRP-26578 Give Advisors access to ex-students' academic data

- app/models/berkeley/degree_progress_graduate.rb
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- spec/support/degree_progress_shared_examples.rb
- Removes form notification from Adv to Cand Plan II milestone. 
- Adds new codes to grad milestone status map
> SISRP-25362 - Updates Degree Progress (GRAD) text translation 

- app/models/google_apps/drive_manager.rb
- app/models/google_apps/sheets_manager.rb
- spec/models/google_apps/drive_manager_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6499
Notes:
* read Jira above on `Google::APIClient::InstalledAppFlow` removal
* `google_api` and `drive_api` methods lazy-load API proxy (only one `discovered_api('drive', 'v2')` to maintain)
* `drive_manager_spec` no longer makes real Google API calls; it simply confirms our error handling and handling of multiple rows in Google response 
* hash syntax is cleaner
> CLC-6499, remove Google::APIClient::InstalledAppFlow from DriveManager class

- config/settings/testext.yml
- spec/models/google_apps/credential_store_spec.rb
- spec/models/google_apps/sheets_manager_spec.rb
- spec/models/oec/remote_drive_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6489
Notes:
* The #real test in `credential_store_spec` was of little value; it is gone.
* But, the #realness of `sheets_manager_spec` and `remote_drive_spec` is valuable. I followed the pattern of `google_proxy` configs on Bamboo and add new setting: `oec.google. testext.refresh_token`
I updated `testext.local.yml` on Bamboo (docker), ran a personal build and it's green: https://bamboo.ets.berkeley.edu/bamboo/browse/CPB-CJT86-4
> CLC-6489, OEC-related testext uses Bamboo-only refresh_token

- script/sync-canvas-new-users.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6475
2GB max heap size; HeapDumpOnOutOfMemoryError enabled.
@dkawase says that the script crashed in prod (again) last night so I'll propose a QA PR when this is merged.  @raydavis should chime in.
According to recent [Stack Overflow post](http://stackoverflow.com/questions/35930340/xxheapdumponoutofmemoryerror-max-file-size-limit), "there is no overhead in running with [the HeapDumpOnOutOfMemoryError] option".
> CLC-6475, JVM - during sync-canvas-new-users script - gets large Max Heap Size

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-27492
Succinct explanation from Liz (functional owner) so you don't have to dig through the JIRA:
> We will remove these two links from the Advising Resources card from the Advisor Dashboard for GL 7.2. Both links exist on the Student Overview Page > Personal Summary card and has a better experience as the EMPLID of the student is passed in they land exactly where they need to in Campus Solutions without having extra clicks and a page view that we were trying to avoid them having.
> SISRP-27492 - Advising Dashboard - Remove Academic Progress Link and What If Report Link

- script/sync-canvas-new-users.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6503
More info on [HeapDumpPath at Stack Overflow](http://stackoverflow.com/questions/542979/using-heapdumponoutofmemoryerror-parameter-for-heap-dump-for-jboss).
@dkawase does not need a QA PR for this change.
> CLC-6503, HeapDumpPath tells JVM where to put heap-dump file

- app/models/user/stored_users.rb
- spec/models/user/stored_users_spec.rb
https://jira.berkeley.edu/browse/SISRP-27641
Oddly, we had `found.size > 0` and `found.first` nil. Race condition? This change _should_ avoid recurrence.
> SISRP-27641, User::StoredUsers: avoid destroy call on nil:NilClass

- script/sync-canvas-new-users.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6503
See @dkawase's most recent comment in JIRA above. The `mkdir` is safe.
> CLC-6503, Ops requested a dedicated directory for Java Heap dump

- app/models/canvas_csv/refresh_all_campus_data.rb
- app/models/canvas_csv/term_enrollments.rb
- spec/models/canvas_csv/refresh_all_campus_data_spec.rb
- spec/models/canvas_csv/term_enrollments_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6505
Steven is contacting Instructure about `ErrorReport:140435606` (as seen in JIRA above). Regardless of what we learn, protecting ourselves from `nil` is a good thing.
> CLC-6505, Canvas data refresh must handle nil from Canvas::Report::Sections.get_csv

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/templates/academics_student_profile.html
- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
Remove obsolete registration-status messages in My Academics Profile: https://jira.berkeley.edu/browse/SISRP-25637
Add between-terms message in My Academics Status and Holds: https://jira.berkeley.edu/browse/SISRP-25843
Remove obsolete Bear Facts links: https://jira.berkeley.edu/browse/SISRP-27636
As a side effect of other work, https://jira.berkeley.edu/browse/SISRP-26943 (conflicts between "Profile" and "Status and Holds") is also resolved.
> SISRP-25637 SISRP-27636 Update term transition logic in Academics Profile & Status

- app/controllers/canvas_lti_controller.rb
- app/controllers/canvas_mailing_list_controller.rb
- app/controllers/canvas_mailing_lists_controller.rb
- app/models/canvas/course_policy.rb
- app/models/canvas_lti/external_app_configurations.rb
- app/models/mailing_lists/site_mailing_list.rb
- app/views/canvas_lti/lti_site_mailing_list.xml.erb
- config/routes.rb
- spec/controllers/canvas_mailing_list_controller_spec.rb
- spec/models/canvas/course_policy_spec.rb
- spec/support/mailing_list_shared_examples.rb
- src/assets/javascripts/angular/configuration/routeConfiguration.js
- src/assets/javascripts/angular/controllers/pages/canvasSiteMailingListController.js
- src/assets/javascripts/angular/controllers/pages/canvasSiteMailingListsController.js
- src/assets/javascripts/angular/factories/canvasSiteMailingListFactory.js
- src/assets/javascripts/angular/factories/canvasSiteMailingListsFactory.js
- src/assets/templates/canvas_embedded/site_mailing_list.html
- src/assets/templates/canvas_embedded/site_mailing_lists.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6473
The least disruptive way I could find to set up a second mailing list LTI tool alongside the existing one was to enforce a convention up and down the stack where`mailing_list`, `mailingList` code (singular) drives the new course-level tool for creating a single list, while `mailing_lists`, `mailingLists` code (plural) drives the existing admin-level tool for managing all lists. Getting this naming consistent involved a couple of file renames that make the diff harder to read than it should be.
> CLC-6473 Per-course LTI tool for mailing list creation

- Gemfile
- Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-27745
As this is my first time updating a gem, I'd like to run through what I did to ensure we're all on the same page:
* Updated `Gemfile` with newest version - this ensures we don't automatically update with each new released version.
* In ~/calcentral, ran `bundle update jruby-openssl`, followed with `gem cleanup jruby-openssl` to remove older, unused versions that don't have any dependencies.
* Would I go through the same process on each node upon merge, to update the gem on each cluster?
Additionally:
* Testing on my local machine seemed totally fine - no breaks or unexpected behavior.
* @raydavis, you mentioned getting this onto CC-QA as soon as possible - shall I open a QA PR for that upon merge of this PR?
> SISRP-27745 - Update jruby-openssl gem to newest version

- spec/models/campus_solutions/faculty_committees_spec.rb
- spec/models/campus_solutions/student_committees_spec.rb
- spec/models/my_committees/faculty_committees_spec.rb
- spec/models/my_committees/student_committees_spec.rb
https://jira.berkeley.edu/browse/SISRP-28019
update 11/15: 
* after discussing with @raydavis, I removed the static UID's and returned them to random ones.
* added mocks to fake the CrossWalk calls 
-------------------------------------------------
* fix testext failures due to random uid. 
This was a tough one. I had to configure my local machine to testext, thank @redconfetti for your help on that.  It was difficult since it was an intermittent error. Some randomly generated uid's being used in the CS proxy calls for the committees API's were sometimes valid and sometimes errored the crosswalk calls. At the end, I'm not sure why the proxy calls are still requiring a valid uid to be passed even though the fake flag is set to true.
> SISRP-28019 - Committees card need to show Insider/outsider details for committee members

- app/models/campus_solutions/advising_academic_plan.rb
- app/models/my_academics/academic_plan.rb
- app/models/my_academics/filtered_for_advisor.rb
- fixtures/xml/campus_solutions/advising_academic_plan.xml
- public/dummy/json/advising_student_academics.json
- script/sis/verify_sis_api_endpoints.sh
- spec/models/campus_solutions/advising_academic_plan_spec.rb
- spec/models/my_academics/academic_plan_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_plan.html
- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-25379
This a redo for PR https://github.com/ets-berkeley-edu/calcentral/pull/6083/
This is a brand new card "Academic Plan" for advisors and super users on the user_overview page. This card replaces the semesters and enrollments cards on this page.
There was enough refactoring after the last review that I decided not to reopen the old PR but create a new one with start from a zero review. 
* Add  academic plan feed as a merged feed under my academics filtered for advisor merged model.
* corrected some bugs found under the first review. 
* add missed UX features.
> SISRP-25379 - Student Overview (Advisor) - Academic Plan card

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/support/spec_helper_module.rb
- src/assets/stylesheets/_profile.scss
- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-27695
Students can have a sub-plan associated with their plan (major or minor) which will now display on the Profile card.
So far it looks like there will be a 1-1 relationship between plan and sub-plan.  I'm checking to see if we'll ever have to handle a list of sub-plans and will make changes accordingly if that's the case.
> SISRP-27695 - Adds sub-plan to the Profile card

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/javascripts/angular/directives/academicPlansDirective.js
- src/assets/templates/directives/academic_plans.html
- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-27695
Designated emphasis is to grad students as a minor is to undergrads.  
We'll display it alongside majors and minors.  Following the "rule of 3", since we're now repeating the same code three times in the template I moved it into a directive.  We'll likely be adding a fourth type (certificates) in the future.
> SISRP-27695 - Adds designated emphasis to Profile card

- app/models/campus_solutions/advising_resources.rb
- app/models/my_academics/transfer_credit.rb
- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-27748
Design JIRA:  https://jira.berkeley.edu/browse/SISRP-27670
* There's actually a typo in the link being returned by the Link API, but that shouldn't stop us from moving on =) The typo (a space in the URL) can be addressed on Monday, and doesn't have an impact on the CalCentral code
* There's currently no documentation on JIRA that we want to remove the student-specific TC Report link from the Personal Summary card, but I got verbal confirmation from Chara earlier this week.  I'll ask her to update relevant JIRAs to include that.
> SISRP-27748 - 7.3 Transfer Credit - Link to Student Overview (advisor)

- app/models/my_academics/academic_plan.rb
https://jira.berkeley.edu/browse/SISRP-28251
* fix for double counting units for classes with transcript data.
> SISRP-28251 - Student Overview Academic Plan Card shows wrong total unit count

- src/assets/stylesheets/_academics.scss
- src/assets/stylesheets/_base.scss
- src/assets/stylesheets/_student_success.scss
https://jira.berkeley.edu/browse/SISRP-27722
After complaints that our headers looked wimpy on Windows 7, I updated the h3 and h4 styles* so that they appear similar on both Windows (Chrome) and Mac (Chrome).  I will continue spot-checking in other browsers as time permits.  Wanted to get this out first in case there are any concerns, since this affects the entire site.
If you want to see the before/after, view screenshots here:  https://drive.google.com/open?id=0BzCFJacXKzFBdGxWWWhBN2xQdmM
*I'm a little concerned about not being able to test every single header on the site.
> SISRP-27722 - Standardizes <h*> styles sitewide for mac/win compatibility

- src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-28337
* needed to filter out call for non-students since roles object is not populated.
> SISRP-28337 - My Academics Page JavaScript error "Cannot read property 'haasMastersFinEng' of undefined"

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6520
Info on jQuery selectors in play:
* http://api.jquery.com/nth-last-child-selector/
* http://api.jquery.com/prepend/
My initial solution (PR #6215) was faulty. We cannot rely on `waitUntilAvailable('#start_new_course', ...)` because that button does not always render (see default Canvas logic). Therefore, UC Berkeley's custom rules (e.g., staff can 'Create a Site') won't work; the replace logic will never fire.
> CLC-6520, 'Create a Site' button after Canvas dashboard_sidebar renders

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6520
PR #6217 did not do the job. See Steven Williams comments in Jira above about unwanted buttons in "To Do" and "Recent Activity" items. This PR targets the no-class `<div>` within immediate children of `#right-side`.
DO NOT MERGE until Steven Williams does initial validation at https://ucberkeley.beta.instructure.com
> CLC-6520, select #right-side child w/o class for prepend 'Create a Site'

- app/models/campus_solutions/advising_academic_plan.rb
- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/advising_academic_plan.xml
- public/dummy/json/advising_student_academics.json
- script/sis/verify_sis_api_endpoints.sh
- src/assets/templates/academics_plan.html
https://jira.berkeley.edu/browse/SISRP-28446
I corrected the URL for the API and found that the payload returned differed a little from the original spec. I made the needed adjustments to account for the lack of "Array" attribute on "Terms" element and different structure at the class level data.
> SISRP-28446 - Academic Plan - point to correct API and adjust for variations in payload

- app/models/campus_solutions/advising_resources.rb
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-28441
* Adding back the What-If Report and Academic Progress Report links I ripped out in #6124.
* Links have been unit tested in BCSDEV, will hit BCSQAT later today.
> SISRP-28441 - Advising dashboard - advising resources card missing links

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-28454
* added comment in grading header to alert user of latency between CS and CC
> SISRP-28454 - CalCentral showing incorrect grade roster status in Faculty Grading - Confusing to users

- app/models/campus_solutions/faculty_delegate.rb
- app/models/my_academics/faculty_delegate.rb
- app/models/my_academics/grading.rb
- spec/models/my_academics/faculty_delegate_spec.rb
https://jira.berkeley.edu/browse/SISRP-28333
* Added instance level variable for grading log issue. 
* used cached proxy from FacultyDelegate API calls, this will help for instructors with the same set of sections
* added logic to only apply FacultyDelegate to semester for student users and only teaching semesters for non-student users, this should improve performance by at least 50%
> SISRP-28333 - MyAcademics feed taking over 90 sec to load for faculty user in CC-QA

- app/models/my_academics/grading.rb
- spec/models/my_academics/grading_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_classinfo.html
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-28502
Multiple areas for dramatic improvement via minor changes to language and placement:
Changes to Instructor Card:
* Move "Grading Legend" to appear beneath the courses
* Rename "Enter Grades" to "Can enter grades"
* Rename "Enter and approve grades" to "Can enter and approve grades"
Changes to Grade Tab:
* Switch the order of the 2 links on this page
* Rename "Links for final grades are on the Fall 2016 page" to "Fall 2016 Final Grades"
* Make "Fall 2016 Final Grades" larger and more prominent
* Make "Assistance with Grading: General" less prominent, smaller and lower on the page
Changes to Grading Card:
* Reorder Teaching section with Grading section - Grading appears before Teaching
* Rename "Course Grades" link to "Enter Grades"
* Create 1 …
> SISRP-28502 - Grading: UAT Feedback on Nov 30

- package.json
https://jira.berkeley.edu/browse/SISRP-28750
Forces AngularJS to v1.5.8 instead of v1.6.0 with [broken calls](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rainbow-tsunami-2016-12-08) to $http.get(...).success / error
> SISRP-28750 - Downgrade AngularJS from 1.6.0 to 1.5.8

- app/models/my_academics/semesters.rb
https://jira.berkeley.edu/browse/SISRP-28730
* updated the semesters feed parsing to include grades from enrollments for all non-legacy terms even if not current term or grading in progress conditions. 
moving forward the new CS will keep official grades in enrollments and does not have a transcript records table. legacy terms will continue to pull from transcripts until data migration is complete and code can be stripped out to only point to CS enrollments.
> SISRP-28730 - Fall 2016 Grades need to be pulled from CS into Calcentral

- app/controllers/advising_student_controller.rb
- app/controllers/hub_edo_controller.rb
- app/models/berkeley/academic_roles.rb
- app/models/hub_edos/academic_status.rb
- app/models/hub_edos/my_academic_status.rb
- app/models/my_academics/college_and_level.rb
- app/models/my_academics/gpa_units.rb
- app/models/notifications/sis_expiry_processor.rb
- spec/models/berkeley/academic_roles_spec.rb
- spec/models/hub_edos/my_academic_status_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/support/spec_helper_module.rb
This is the backend work required to support https://jira.berkeley.edu/browse/SISRP-27699.
We needed a way for every page in calcentral to be aware of the roles that are assigned to a student based on their academic status (plan or career).  Prior to this, that information was added to the feed in `CollegeAndLevel` and only available on the My Academics page.
I refactored the roles logic into a new model called `MyAcademicStatus`, which takes the feed from `AcademicStatus` and inserts the roles into it.  The roles will now be included in the `CollegeAndLevel` feed and in `HubEdoController#academic_status`.  `GpaUnits` and `AdvisingStudentController` are still calling `AcademicStatus` directly unless anyone sees a reason to switch those over too.
I also added a new role that will be …
> SISRP-27699 - Implements strategy for identifying summer visiting students

- app/models/calnet_ldap/client.rb
- spec/models/calnet_ldap/client_spec.rb
https://jira.berkeley.edu/browse/SISRP-28781
This will ensure up-to-date personal attributes in the user's own view, in advisor Student Overview, and in View-As.
Bulk attributes (such as shown in class rosters) may continue to be out-of-date for non-active campus accounts until follow-up task SISRP-28908 is addressed.
> SISRP-28781 Check Alumni & Expired-account LDAP populations if needed

- src/assets/javascripts/angular/services/statusHoldsService.js
https://jira.berkeley.edu/browse/SISRP-28993
* The value of `unitsEnrolled` coming from the Registrations API has more of an "units in progress" definition in CS.  So, at the end of the term, `unitsEnrolled` drops to zero.  `unitsTaken` then becomes the value we need to look at.
* Also tried to clean up the code to be a bit more DRY.
> SISRP-28993 - Not Enrolled status for students who are enrolled in classes - CC Status and Holds (INC0376834)

- Gemfile
- Gemfile.lock
- app/models/calnet_crosswalk/proxy.rb
https://jira.berkeley.edu/browse/SISRP-28736
This reverts commit 152173c97d1bee4567e1f236959b8aa950c80046.
The reversion is already in the QA branch for a prospective v85.2 release. However, since our post-0.9.7 stability problems  are very unlikely to be resolved in time for GL7.4, it seems safest to get it into the master branch now.
SISRP-29026 is a critical-priority task to undo the undoing.
> SISRP-28736 TEMPORARY reversion of jruby-openssl back to 0.9.7

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academics/degree_progress_graduate.html
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
* Biggest change on our end (lot of stuff going on in that ticket) is opening this up to students who have *any* Degree Progress data - not just current students.
* Also reformatted front-end to use one spinner for both graduate and undergraduate data.  There's a small population who might have both a graduate and an undergraduate Degree Progress card, but for the most part, people will only have one.
* This brought up a design question though - as we are introducing yet another spinner to the User Overview page.  Do we go the My Academics (Student) route and use one spinner for everything?  But that would delay user's views of ready-to-go data.  I discussed this with @lyttam and Chara and while it is a larger question that should include both …
> SISRP-25362 - 7.4 - Student Overview (Advisor) Degree Progress card for Grad and Law Careers

- app/models/edo_oracle/queries.rb
- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-29104
* Not shown here:  Updated EDODB query that should resolve existing CS data not being returned.
* The `IS NOT NULL` query parameter doesn't actually need to be there, even when the value is empty in CS, the query will return a value.  That is, there are no "`mtg."location-code" IS NOT NULL` rows.  I'm guessing they send us an empty string instead.
> SISRP-29104 - CalCentral - Class Information page missing lecture date, time and location for Sp17 UGBA 118 (INC0367091 & INC0376337)

- app/controllers/advising_student_controller.rb
- app/controllers/bootstrap_controller.rb
- app/models/my_academics/academic_plan.rb
- app/models/my_academics/filtered_for_advisor.rb
- config/routes.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/templates/widgets/academic_plan.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-28787
* Adds a cache expiry function when user clicks the Multi-Year Planner link, and another cache expiry function when the user clicks "Return to Student Overview" while in CS.
* Also added to the Multi-Year Planner link in `user_preview.html`.  If we're showing the same link in two different places on the same page, we should have them behave the same way.
* This PR is a bit larger than I expected to be - so feel free to ping me on any questions.  I do intend to open a QA PR for this as well.
> SISRP-28787 - Add Cache Expiration for Outgoing/Incoming Academic Plan Link

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/pages/myFinancesController.js
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/holdsController.js
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/javascripts/angular/factories/academicStatusFactory.js
- src/assets/javascripts/angular/factories/campusLinksFactory.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/javascripts/angular/services/apiService.js
- src/assets/javascripts/angular/services/profileMenuService.js
https://jira.berkeley.edu/browse/SISRP-27699
Per discussion on #6299, I moved the fetching of academic status from `academicsService` back into `academicStatusFactory`, and moved the finagling of holds data from the various controllers that use it into the factory level for increased DRYness.
`academicStatusFactory` now exposes two functions:  `getHolds` and `getAcademicRoles`, which are used in a standard way by all the calling controllers.  Thoughts/critiques on this approach are appreciated!
> SISRP-27699 - Refactors academic roles and holds handling

- src/assets/stylesheets/_finaid_summary.scss
- src/assets/templates/widgets/finaid_summary_netcost.html
https://jira.berkeley.edu/browse/SISRP-27698
The testing team pointed out that the horizontal separator was missing from the "Net Cost" section on the Financial Aid and Scholarships card.  In fact, it was just blending into its surroundings as we changed the background color of the section.  I overrode the sitewide \<hr\> style to make this one darker so it stands out.
QA PR forthcoming.
> SISRP-27698 - re-styles <hr> to make it visible

- app/models/canvas_lti/egrades.rb
- spec/models/canvas_lti/egrades_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6534
See screenshot attached to Jira above.
Duplicates in the eGrades dropdown happen when the course has:
* multiple primary sections
* secondary section has multiple parents/primaries. I.e., duplicate rows, per section id, in `SISEDO.CLASSSECTIONV00_VW` with differing `primaryAssociatedSectionId` values.
This multiple parent info might be useful in other scenarios but the eGrades feature doesn't care. So, we put de-dupe logic at level of the model.
*Note:* overhaul of spec and up-to-date test data.
> CLC-6534, avoid duplicate section ids in eGrades export

- src/assets/stylesheets/_canvas_base.scss
- src/assets/stylesheets/_canvas_buttons.scss
- src/assets/stylesheets/_canvas_course_add_user.scss
- src/assets/stylesheets/_canvas_course_grade_export.scss
- src/assets/stylesheets/_canvas_user_provision.scss
- src/base.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6522
Since Lato is a web font not shared across iframes, we need to fetch it from Google ourselves for bCourses pages only.
A couple of sizes and weights are tweaked to play better with the new font.
This should apply to all LTI tools except Roster Photos, which continues to use plain old CalCentral Arial for shared-template reasons.
> CLC-6522 Update font in local bCourses LTI tools to Lato

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-29434
While smoke-testing the 7.4 release we noticed a JS error on Student Overview.  Seems pretty minor and doesn't impact functionality, and it is only occurring when the advising_academic_planner feature flag is set to false.
> SISRP-29434 - Makes link handling null-safe on Student Overview

- app/models/edo_oracle/adapters/oec.rb
- app/models/edo_oracle/oec.rb
- app/models/oec/queries.rb
- spec/models/edo_oracle/adapters/oec_spec.rb
- spec/models/oec/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6533
In cases where a preferred name is not present, we fill in from User::BasicAttributes, as we do for missing email addresses.
> CLC-6533 OEC: return preferred name from enrollments query

- app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-29001
* See JIRA comments for logic behind this PR.
> SISRP-29001 - ENF grade-roster events fail on EDO DB ConnectionTimeoutError

- app/models/edo_oracle/adapters/common.rb
- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/academics_module.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- src/assets/javascripts/angular/services/academicsService.js
https://jira.berkeley.edu/browse/SISRP-29225
* Adds department code to course/section related EDO DB queries
* Adds `dept_code` to MyAcademics::Semesters feed within classes
* Updates BookListsController to pass `dept_code` instead of department name field for Textbooks API request
> SISRP-29225 - Bookstore - not returning books with 2-part dept name (SOC WEL, COGSCI, etc)

- spec/models/my_activities/webcasts_spec.rb
https://jira.berkeley.edu/browse/SISRP-28970
The `fake: false` spec is testing 'connection failure' and term data matters not to that test. (Personal Bamboo build is happy: https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-TRC3-1)
> SISRP-28970, webcast_spec: when fake=false use stubbed term data

- app/models/my_activities/merged.rb
- app/models/my_activities/notification_activities.rb
- app/models/my_activities/webcasts.rb
- spec/models/my_activities/webcasts_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6547
Default `cutoff` is 10 days. Course Capture is 2 days.
> CLC-6547, Course Capture related notifications will expire after 2 days

- app/models/my_academics/class_enrollments.rb
- config/settings.yml
- config/settings/test.yml
- spec/models/my_academics/class_enrollments_spec.rb
- src/assets/templates/widgets/enrollment/decide_concurrent.html
https://jira.berkeley.edu/browse/SISRP-29725
Implements the ability to configure the deadline dates for the enrollment application process for the Class Enrollment card, within the 'Enroll' section of the 'Concurrent Enrollment' flavor of the card.
> SISRP-29725 - Implement deadline date configuration for concurrent enrollment 'decide' section

- app/models/my_academics/gpa_units.rb
- fixtures/json/hub_academic_status.json
https://jira.berkeley.edu/browse/SISRP-29459
lots of analysis for the smallest change :) 
* fix put in to source cumulative units for new field added to academic status API
> SISRP-29459 - CalCentral CUM Units is only displaying UC Berkeley Units total

- src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-29827
* How I got caught:  The front-end academicsController has an `if` statement to show the most relevant semester on the My Academics tab for instructors, but only if `MyAcademics::Semesters` is empty.  If you're not tunneled to the CampusOracle DB, you'll never hit this part of the statement, because `fake` will always return data for you in `MyAcademics::Semesters`.
> SISRP-29827 - Midpoint Status Column is missing on My Academics Tab

- app/models/hub_enrollments/current_enrollments.rb
- app/models/hub_enrollments/my_current_enrollments.rb
- app/models/hub_enrollments/proxy.rb
- config/settings.yml
- fixtures/json/hub_current_enrollments.json
- script/sis/verify_sis_api_endpoints.sh
- spec/models/hub_enrollments/current_enrollments_spec.rb
https://jira.berkeley.edu/browse/SISRP-29795
Some more good information on why I chose to create a "CurrentEnrollments" class instead of a more general, catch-all "Enrollments" class here:
https://jira.berkeley.edu/browse/SISRP-29571
* The Enrollments Proxy portion of the `verify_sis_endpoints` script *WILL* fail for the time being, until v2 of the Enrollments API proxy gets migrated to Hub UAT.
> SISRP-29795 - Create Enrollment API Proxy

- app/models/hub_enrollments/my_current_enrollments.rb
- app/models/my_academics/semesters.rb
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-29571
* Need to rename "Current Enrollments", opened up [SISRP-29960](https://jira.berkeley.edu/browse/SISRP-29960) to do that
* Surfaces midpoint grades for the current semester to enrollments where the user has a role of "Student"
* Removed `jsonifiedfeed` from Enrollments API because I realized we only use it on server-side.
> SISRP-29571 - Mid-Point Grades: Student-Facing

- config/database.yml
- config/settings/development.yml
https://jira.berkeley.edu/browse/SISRP-29026
Just makes it easier to do more realistic testing when ``RAILS_ENV=development`` -- should be a no-op unless you change your settings.
> SISRP-29026 Enable concurrent request handling in development mode

- app/models/edo_oracle/course_sections.rb
- app/models/edo_oracle/queries.rb
- spec/models/edo_oracle/course_sections_spec.rb
- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-29841
* Consumed flag already in EDODB instructor view to hide instructors names from class info page if flag is not set to 'Y' and a student is viewing the page. 
* correct logic to allow GSI's to also see grading delegate information.
> SISRP-29841 - CalCentral/My Academics shows instructor names that should not print

- app/models/berkeley/summer16_enrollment_terms.rb
- app/models/campus_oracle/user_courses/base.rb
- app/models/edo_oracle/user_courses/base.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-26723
Some students have two different SIDs on our system - they were issued one SID when they enrolled in summer courses, and a second SID when they came back the following fall.
These unlucky students have summer 2016 course enrollment data on the legacy Campus Oracle DB under the first SID, and the same data on EDO DB under the second SID.
The effect of this PR is to check in both datasources for summer 2016 enrollments.  That way, if a student logs in with the first SID they will see their summer 2016 enrollments, and if they log in with the second SID they will see those same summer 2016 enrollments as well as fall 2016 and later.
> SISRP-26723 - Look for summer-2016 course data/enrollments in both legacy and EDO

- app/models/my_committees/committees_module.rb
- app/models/my_committees/faculty_committees.rb
- app/models/my_committees/student_committees.rb
- spec/models/my_committees/faculty_committees_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/widgets/higher_degree_faculty_committees.html
https://jira.berkeley.edu/browse/SISRP-30081
It came to light that the flag we were relying to distinguish an active committee from an inactive one is not being kept up-to-date in CS.  To avoid showing misleading info in 7.5, we are scrapping the "Active" and "Completed" committees lists and just showing them all in a single list.
> SISRP-30081 - Removes active/completed committee distinction

- app/models/berkeley/degree_progress_graduate.rb
- app/models/degree_progress/milestones_module.rb
- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-29961
* Peppered in some `#try`'s in some unrelated methods just in case.
* The `order_number` definition is kind of weird because both Master and PhD tracks share a milestone, "Department Final Recommendations."  I was limited to assigning this milestone only one order number, despite it showing up in different places in each respective track.  I staggered the Masters track to start at 2 to make up for this.
> SISRP-29961 - Ensure proper ordering of milestones - Reopened

- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-30252
In [SISRP-29535](https://jira.berkeley.edu/browse/SISRP-29535) a CS link that was configured in the application YAML was migrated to the CS Link API, and the `enrollment_verification_deeplink` feature flag was removed. A static link (Google form) was left in as a fallback, displayed when the previously configured link was not present, resulting in two links shown.
This update retains the original logic, however clarification is still being requested from the SR team (and may result in a follow up PR).
* Updates logic for fallback to static Google link for Enrollment Verification.
* Removes unused scope settings.
> SISRP-30252 - 'Request Official Verification' - Google form link showing in addition to CS link

- src/assets/javascripts/angular/services/academicsService.js
https://jira.berkeley.edu/browse/SISRP-30297
* This bug surfaced due to my initial misunderstanding of Lodash's `_.every`, which returns `true` only if all iterations return `true`.
> SISRP-30297 - Midpoint Status column is missing when the Grading card has Law and Non Law classes

- app/controllers/canvas_course_grade_export_controller.rb
- app/controllers/torquebox_controller.rb
- app/models/canvas_csv/provide_course_site.rb
- app/models/canvas_csv/site_memberships_maintainer.rb
- app/models/canvas_lti/course_provision.rb
- app/models/canvas_lti/egrades.rb
- app/models/oec/api_task_wrapper.rb
- app/models/oec/task.rb
- config/torquebox.rb
- lib/background_job.rb
- lib/torquebox_tester.rb
- spec/controllers/canvas_course_grade_export_controller_spec.rb
- spec/controllers/canvas_course_provision_controller_spec.rb
- spec/models/canvas_csv/provide_course_site_spec.rb
- spec/models/canvas_lti/course_provision_spec.rb
- spec/models/oec/api_task_wrapper_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6571
The changes mostly aim to help diagnose problems by linking Torquebox background job Correlation IDs to Junction task status IDs, but two bugs are fixed as well:
* Stop throwing 400 errors when an OEC task starts (as noted in CLC-6570).
* Do not let a single unusually long-running task block tools like bCourses Course Site creation.
> CLC-6571 Add Torquebox links to ETS service jobs; increase concurrency

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-30189
* `aria-hidden="true"` makes the content invisible to screen readers.
* I thought there wasn't really a need to have a screenreader slog through the legend when there's no use for it, since the status themselves will be dictated as speech already.
> SISRP-30189 - Grading in CalCentral Accessibility Issues

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-29777
Fixes the logic around displaying the Graduate Degree Progress card due to these funny cases:
- Student may have UGRD and GRAD degree progress, and need to see both cards
- GRAD and LAW students with milestones need to see the card
- GRAD and LAW students with no milestones need to see the card with a message
- Ex-students should see the card as long as they still have milestones
QA PR forthcoming
> SISRP-29777 - Show Degree Progress card to GRAD/LAW students with no milestones

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6579
In case you're interested, verify the ID on both UIs:
* old: https://ucberkeley.test.instructure.com/courses/1452646/users
* new: https://ucberkeley.beta.instructure.com/courses/1460916/users
Steps per URL above:
1. open console
1. find DOM element with `$('#group_categories_tabs ul li a:first')`
1. verify that anchor tag on "Everyone" (tab) is selected
I'll put steps above to the Jira, too.
> CLC-6579, proper ID of tab on Add People

- app/models/my_committees/student_committees.rb
- spec/models/my_committees/student_committees_spec.rb
https://jira.berkeley.edu/browse/SISRP-30527
Committee members who have been "reconned" (ended their term on the committee) will have a service end date in the past.  Faculty should see inactive members on the Committees card, but students should not.
> SISRP-30527 - Filters inactive committee members from the student committees card

- app/models/oec/merged_sheet_validation.rb
- spec/models/oec/publish_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6586
From this day forward, we wish to preserve instructor data for all time.
> CLC-6586 OEC: Remove one-year-ago cutoff for old instructor data

- app/models/oec/diff_report.rb
- app/models/oec/report_diff_task.rb
- spec/models/oec/report_diff_task_spec.rb
Per requirements in https://jira.ets.berkeley.edu/jira/browse/CLC-6588:
- The symbolic '+/-' column is replaced with a more verbose 'REASON' column.
- Rows with multiple discrepancies will appear multiple times in the diff, each time with a different value in the 'REASON' column.
- Values without discrepancies are omitted from the report, apart from 'COURSE_NAME', which enables identification.
> CLC-6588 OEC: Highlight salient differences in diff report

- app/models/campus_solutions/degree_progress/undergrad_requirements_expiry.rb
- app/models/notifications/sis_expiry_processor.rb
- app/models/notifications/sis_expiry_single_student_provider.rb
- app/models/notifications/sis_expiry_students_provider.rb
- spec/models/notifications/sis_expiry_student_provider_spec.rb
- spec/models/notifications/sis_expiry_students_provider_spec.rb
- spec/support/sis_expiry_shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-28700
The Degree Progress card for undergrads gets its data from the Academic Progress Report.  Advisors want to be able to run the APR, which generates a new set of data, and see that data reflected in CalCentral right away rather than wait for the cache to expire.
An event will fire when the APR is run for a single student.  The event notification allows for an array of student IDs in case we want to have the event fire when the APR is run in batch (for many students).
Payload for the event notification is detailed here:  https://docs.google.com/document/d/10uOE80vkeDXpf-7jv_I0vfnIlSpZUsUTvKIa1zLkZ1k/edit#heading=h.qa4txi13e9gh
> SISRP-28700 - Adds expiry handler for undergrad Degree Progress

- app/models/canvas/course_users.rb
A copy-and-paste in #4014 has this class referencing a nonexistent instance variable.
> NOJIRA Fix Canvas::CourseUsers cache key

- app/models/my_academics/semesters.rb
https://jira.berkeley.edu/browse/SISRP-29263 
* force semesters to pull grades from CS for summer-2016 and when allow_legacy_fallback is false
> SISRP-29263 - CalCentral missing summer 2016 classes for Fall 2016 

- app/models/my_academics/academic_plan.rb
- app/models/my_academics/academics_module.rb
- app/models/my_academics/advisor_links.rb
- app/models/my_academics/filtered_for_advisor.rb
- app/models/my_academics/merged.rb
- app/models/my_academics/student_links.rb
- app/models/my_academics/transfer_credit.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/my_academics/advisor_links_spec.rb
- spec/models/my_academics/student_links_spec.rb
- src/assets/templates/widgets/academic_plan.html
- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-30588
A conflict arose where a link intended only for student was embedded in the students Transfer Credits model. Passing links down the chain to the model to determine if it should provide the 'Student' links, or the 'Advisor' links would be inappropriate.
After some analysis I see that the Student Overview page is sharing a filtered version of the My Academics feed, which doesn't include links intended for Advisors. It's pure student data, yet only the data Advisors should see for the student.
The trend thus far has been to retrieve links for Advisors from the Advising Resources feed shared between the 'Advising Resources' card on the My Dashboard page, and the Personal Summary card on the Student Overview (containing student specific links that …
> SISRP-30588 - CalCentral Code Fix: Transfer Credit Report Links

- app/models/canvas/course.rb
- app/models/rosters/campus.rb
- app/models/rosters/table_columns.rb
- spec/models/canvas/course_spec.rb
- spec/models/rosters/campus_spec.rb
- spec/models/rosters/table_columns_spec.rb
- src/assets/javascripts/angular/controllers/pages/rosterController.js
- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
- src/assets/javascripts/angular/services/rosterService.js
- src/assets/stylesheets/_print.scss
- src/assets/stylesheets/_roster.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/academics_classinfo.html
- src/assets/templates/canvas_embedded/roster.html
- src/assets/templates/directives/academics_class_info_enrollment.html
- src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-30579
* Adds Rosters::TableColumns module
* Merges prepared column data and headers into Rosters::Campus data feed
* Updated rosters template to hide new search options from bCourses (Canvas) LTI tool
* Refactors Rosters::Campus
* Adds instructional format code and section number to Rosters::Campus feed
* Adds list view, migrates roster filtering to shared rosterService methods
* Moves logic for viewing selected section of students and statistics to rosterService
* Updates Canvas::Course object to represent as `Canvas Course ID 1234` instead of `#<Canvas::Course:0x2aadf2a9>`
> SISRP-30579 - 8.0: Faculty - Current Roster (INC0305230)

- app/models/edo_oracle/user_courses/base.rb
https://jira.berkeley.edu/browse/SISRP-30740
* bug fix parsing of enrolment data
> SISRP-30740 - Incorrect session displayed for students enrolled in courses with section scheduled in multiple session.

- app/models/google_apps/oauth2_tokens_grant.rb
- app/models/google_apps/userinfo.rb
- spec/controllers/google_auth_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6501
The call to get OEC `current_scope` (Google OAuth) had been using default app_id therefore finding no match in the db. Furthermore, OEC-mode is not compatible with the Google API call for 'self' so we ride the coattails of `can_administer_oec?` check.
> CLC-6501, /api/oec/google/current_scope must use proper app_id in GoogleProxy call

- config/deploy.rb
This script is used in Bamboo deploy jobs. The old "sandbox" environment is long gone, but the code isn't just harmless noise. Its lack of a nil check led us to proliferate unnecessary lines in our ``.calcentral_config/server_config.yml`` files.
> NOJIRA Remove very obsolete "sandbox" from Capistrano script

- db/developer-seed-data.sql
Fix for https://github.com/ets-berkeley-edu/calcentral/pull/6483
I'd used normal Rails migration to test locally, but Bamboo relies on developer-seed-data.sql to start from a fresh DB.
> SISRP-28447 Add new service_alerts column to developer-seed-data

- src/assets/javascripts/angular/configuration/routeConfiguration.js
- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/stylesheets/_academic_summary.scss
- src/assets/templates/academic_summary_page.html
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academic_summary/academic_summary_card.html
- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-31014
* Follows the OG `academic_semesters.html` card logic very closely.
* Got rid of all the `isAcademicSummary` logic for that card - since they're two separate cards now, there's no need for that parameter.
* The final chapter of the 8.0 - Academic Summary trilogy (for now)
> SISRP-31014 - 8.0 - Academic Summary - Semesters

- app/models/berkeley/user_roles.rb
- spec/models/berkeley/user_roles_spec.rb
- spec/models/campus_oracle/user_attributes_spec.rb
- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-24076
The 'AFFILIATE-TYPE-CONCURR ENROLL' affiliation has been [discontinued from use by CalNet LDAP](https://calnetweb.berkeley.edu/calnet-technologists/ldap-directory-service/how-ldap-organized/people-ou/people-ou-affiliations).
This updates CalCentral to use the 'EXTENSION' affiliation sourced from Campus Solutions.
> SISRP-24076 - New data source for Concurrent Enrollment role

- app/models/degree_progress/my_graduate_milestones.rb
- app/models/degree_progress/undergrad_requirements.rb
- spec/models/degree_progress/my_undergrad_requirements_spec.rb
- spec/models/degree_progress/undergrad_requirements_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_degree_progress.scss
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
Parent:  https://jira.berkeley.edu/browse/SISRP-30580
Advisors will see a message with a link to run the APR.  Students will see a message with no link. (https://jira.berkeley.edu/browse/SISRP-30636)
I also wrapped the report run date and label in `ngIf` because it seems the API is not sending that date.  I will investigate that further, but at least wanted to make sure we don't ever display the label with the date missing.
> SISRP-30636 - Adds APR link to UGRD Degree Progress card for advisor only

- app/models/my_committees/committees_module.rb
- src/assets/templates/academics.html
https://jira.berkeley.edu/browse/SISRP-30618
* Full disclosure, was not able to test this locally due to lack of test data, but we should have test cases in time for QA. 
* Removing the template from `academics.html` with a conditional should stop `AcademicsHigherDegreeCommitteesController` from instantiating, preventing the call to `api/my/committees`.
* If a delegate did manually hit the `api/my/comittees` endpoint, the `Pundit::NotAuthorizedError` will still be raised in the logs, notifying us of anything fishy.  For this reason, I did not add anything to the existing restrictions on `my_committees_controller.rb`.
* Changing `#empty?` to `#blank?` ensures no no error is raised if CS sends us `nil` for that particular field.
> SISRP-30618 - Authorization errors in CC Production logs related to committees

- app/models/degree_progress/my_graduate_milestones.rb
- src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
- src/assets/templates/academics.html
- src/assets/templates/widgets/academics/degree_progress_graduate.html
Parent:  https://jira.berkeley.edu/browse/SISRP-25708
If user is an ex-student, we don't know whether they were grad or undergrad.  We only want to show them the card if they were grad.  
To get around this problem, we will only show the card to ex-students IF the API returns data for the card (effectively indicating that the person was a grad student). (https://jira.berkeley.edu/browse/SISRP-31364)
> SISRP-31364 - Allows ex-student to see GRAD Degree Progress

- app/models/degree_progress/my_graduate_milestones.rb
- src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
- src/assets/templates/academics.html
- src/assets/templates/widgets/academics/degree_progress_graduate.html
QA PR for #6510
-----
Parent: https://jira.berkeley.edu/browse/SISRP-25708
If user is an ex-student, we don't know whether they were grad or undergrad. We only want to show them the card if they were grad.
To get around this problem, we will only show the card to ex-students IF the API returns data for the card (effectively indicating that the person was a grad student). (https://jira.berkeley.edu/browse/SISRP-31364)
> [QA] SISRP-31364 - Allows ex-student to see GRAD Degree Progress

- config/deploy.rb
The shell scripts assume they will be started from the top "calcentral" directory & should write output to the "./log/" directory.
Capistrano instead started them from "calcentral/scripts", leading to errors for all logging.
This is an old bug but the Bamboo agent is the only one who would have seen it in action.
> NOJIRA Fix Capistrano deploy script

- app/models/berkeley/graduate_milestones.rb
- app/models/degree_progress/milestones_module.rb
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- spec/support/degree_progress_shared_examples.rb
Parent:  https://jira.berkeley.edu/browse/SISRP-25708
UAT found some milestones with unexpected status codes.  We'll show these as 'Not Satisfied'.  If status code is missing, also show 'Not Satisfied'. (https://jira.berkeley.edu/browse/SISRP-31367)
> SISRP-31367 - Defaults milestone status to 'Not Satisfied'

- app/models/berkeley/graduate_milestones.rb
- app/models/degree_progress/milestones_module.rb
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- spec/support/degree_progress_shared_examples.rb
QA PR for #6512
-----
Parent: https://jira.berkeley.edu/browse/SISRP-25708
UAT found some milestones with unexpected status codes. We'll show these as 'Not Satisfied'. If status code is missing, also show 'Not Satisfied'. (https://jira.berkeley.edu/browse/SISRP-31367)
> [QA] SISRP-31367 - Defaults milestone status to 'Not Satisfied'

- app/models/edo_oracle/user_courses/all.rb
- app/models/edo_oracle/user_courses/base.rb
https://jira.berkeley.edu/browse/SISRP-31399
* If you're not a delegate, your `semesters` feed will be based off of `EdoOracle::UserCourses::All#get_all_campus_courses`, which includes `EdoOracle::UserCourses::Base#merge_detailed_section_data`.  This function uses `#uniq!` to get rid of duplicate section data. 
* If you are a delegate, your `semesters` feed will be based off of `EdoOracle::UserCourses::All#get_enrollments_summary`, which does not have the `#uniq!` function called.
* This PR adds the call to `#uniq!` to `#get_enrollments_summary`.  
* Why did we only start seeing this bug now?  Either we missed it in multiple QA attempts on the delegate experience, or, more likely, the EDODB query started returning duplicate sections for each class.  Maybe this has something to do with the …
> SISRP-31399 - Delegates Seeing Duplicate Classes in Semesters

- spec/models/degree_progress/my_undergrad_requirements_spec.rb
- spec/models/degree_progress/undergrad_requirements_spec.rb
https://jira.berkeley.edu/browse/SISRP-30580
Unit tests for student-facing undergrad Degree Progress were still failing on bamboo, despite using fake data.  Fixed them by stubbing the feature flag to be `true`.  
Also stubbed the advisor-facing feed to return fake data, although these tests were not failing (yet).
> SISRP-30580 - Fixes testext test failures

- spec/models/degree_progress/my_undergrad_requirements_spec.rb
- spec/models/degree_progress/undergrad_requirements_spec.rb
QA PR for #6520
-----
https://jira.berkeley.edu/browse/SISRP-30580
Unit tests for student-facing undergrad Degree Progress were still failing on bamboo, despite using fake data. Fixed them by stubbing the feature flag to be true.
Also stubbed the advisor-facing feed to return fake data, although these tests were not failing (yet).
> [QA] SISRP-30580 - Fixes testext test failures

- config/initializers/rails_admin.rb
https://jira.berkeley.edu/browse/SISRP-31555
As SIS QA pointed out, the original label is too ambiguous.
> SISRP-31555 Clarify meaning of "Splash" in Service Alert / Release Note

- app/models/notifications/sis_expiry_students_provider.rb
- spec/models/notifications/sis_expiry_students_provider_spec.rb
https://jira.berkeley.edu/browse/SISRP-28700
Changes the expected shape of the notification to match what Integration Broker is sending.
This is for post-8.0 emergency release.
> SISRP-28700 - Prevents error when receiving APR event notif

- app/models/edo_oracle/queries.rb
- app/models/rosters/common.rb
- config/settings.yml
https://jira.berkeley.edu/browse/SISRP-31609
* joined the enrollments get_roster EDODB query to PERSON_EMAILV00_VW
* updated enrollment/roster email with EDODB email if email obtained from CALDAP was blank
* added feature flag allow_alt_email_addr_for_enrollments to mitigate any performance issues during ER
> SISRP-31609 - Faculty cannot view and communicate via email with visiting summer students - Enrollment page

- app/models/my_committees/committees_module.rb
https://jira.berkeley.edu/browse/SISRP-31605
Trying to cover all the tricky cases with a committee, it's associated milestones, and the attempts on those milestones.
When the student made an unsuccessful attempt on an advancement milestone, the API doesn't give us the "advanced date".  In this case we have get that date from the attempt itself.
> SISRP-31605 - Extends 'advanced date' logic to look at milestone attempts

- app/models/berkeley/graduate_milestones.rb
- app/models/degree_progress/milestones_module.rb
- app/models/my_committees/committees_module.rb
- spec/models/berkeley/graduate_milestones_spec.rb
- spec/support/degree_progress_shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-31578
This required some refactoring of the status code translation that's used by both Degree Progress and Committees.  Previously, we mapped all the status codes to their labels in a single Hash.  That won't work anymore since we now have a one-to-many relationship between status codes and labels, so I split it into three separate mappings.
> SISRP-31578 - Replaces QE Approval 'Completed' status label with 'Approved'

- src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira.berkeley.edu/browse/SISRP-31756
The links that show on the student-facing Degree Progress card were disabled, but the header was still showing.
> SISRP-31756 - Hides Degree Progress link header when no links to show

- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academic_plan.html
- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-31889
* I want to reiterate as said in the ticket, that this is just a bandage fix so that students can see their grades in the current term.
* [SISRP-32020](https://jira.berkeley.edu/browse/SISRP-32020) will be the larger work of reassessing how `semesters.rb` parses data, and making related changes to the front-end templates.
* QA PR to come since this will be part of Tuesday's Emergency Release.
> SISRP-31889 - Grading: Prod: Spring Final Grades Not Appearing for Students in CalCentral (SNow 445421)

- app/models/my_committees/faculty_committees.rb
- spec/models/my_committees/faculty_committees_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/academics_higher_degree_faculty_committees.html
- src/assets/templates/widgets/higher_degree_faculty_committees.html
https://jira.berkeley.edu/browse/SISRP-31757
Allow faculty user to toggle between active and completed committees.  This feature was removed in 7.5 and now we are putting it back.
> SISRP-31757 - Separates faculty committees into active and completed

- app/models/berkeley/graduate_milestones.rb
- app/models/degree_progress/milestones_module.rb
- app/models/my_committees/committees_module.rb
- app/models/my_committees/student_committees.rb
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- spec/support/degree_progress_shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-31579
Degree Progress for graduate students:
We only want to show the proposed exam date between the time when the student is approved to take the qualifying exam and when they first attempt the exam.
> SISRP-31579 - updates Proposed Exam Date logic on Degree Progress

- app/models/advising/my_advising.rb
- app/models/campus_solutions/advising_resources.rb
- app/models/campus_solutions/student_resources.rb
- app/models/degree_progress/my_graduate_milestones.rb
- app/models/degree_progress/undergrad_requirements.rb
- app/models/my_academics/academics_module.rb
- app/models/my_academics/advisor_links.rb
- app/models/my_academics/class_enrollments.rb
- app/models/my_academics/grading.rb
- app/models/my_academics/student_links.rb
- app/models/my_committees/committees_module.rb
- lib/link_fetcher.rb
- spec/lib/link_fetcher_spec.rb
- spec/models/my_academics/grading_spec.rb
https://jira.berkeley.edu/browse/SISRP-31911
Original goal was just to change the log level to DEBUG on a couple proxies that were treating missing links as ERRORs, but it felt right to take a step further to promote DRYness.  
Going forward:  for any proxies needing to call the Link API, simply include `LinkFetcher`.
> SISRP-31911 - Refactors Link API calls into a mixin

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- spec/models/calnet_ldap/user_attributes_spec.rb
Two followups from https://github.com/ets-berkeley-edu/calcentral/pull/6571
* [SISRP-29647](https://jira.berkeley.edu/browse/SISRP-29647) - Remove still more obsolete legacy advising (bHive) settings
* [SISRP-31764](https://jira.berkeley.edu/browse/SISRP-31764) - When I added a testext check for CS ID, I neglected to confirm that my chosen UID was actually in CS.
> SISRP-29647 Remove obsolete legacy advising (bHive) settings

- app/models/degree_progress/milestones_module.rb
- spec/support/degree_progress_shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-32137
This brings the Degree Progress card more in line with the Committees card.  We weren't bothering to show "Exam n:" on the second or third exam attempt as long as they passed it on that attempt.  Now we will show the exam number on every attempt.
> SISRP-32137 - Number each attempt on the Qualifying Exam milestone

- src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-30166
We were setting `hasAlerts` to true even when the number of holds was zero.
> SISRP-30166 - Hides popover alert icon when zero alerts

- script/build-torquebox.sh
- script/install-jars.rb
Reverts ets-berkeley-edu/calcentral#6579
The Bamboo build is failing due to a missing `build-torquebox.sh` script, which we've narrowed down to this PR.  @raydavis, let's chat this out when you get back to the office.
> Revert "SISRP-32253 Remove obsolete scripts"

- app/models/edo_oracle/oec.rb
- app/models/oec/course_code.rb
- spec/models/edo_oracle/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6625
OEC mappings by specific catalog ID should match on that precise ID rather than using substrings.
Also, specific OEC mappings to a foreign department should be excluded from the home department: that is, if MCELLBI 90A appears under Freshman and Sophomore Seminars, it should not also appear under Molecular and Cell Biology.
> CLC-6625 OEC: tighten course code mappings

- README-VAGRANT.md
- README.md
- docs/Canvas-README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- gulpfile.js
Reverts ets-berkeley-edu/calcentral#6586
Seems like this did mess up browser-sync after all.  Reverting for now, more research needed.
> Revert "SISRP-31200 - Revision asset files in development build mode"

- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/semesters.rb
- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-31171
* Adds "Grade Point" column to Academic Summary
* This is still dependent on the EDODB SOR work that @nkutub is working on, although it is code complete.  Once the `allow_legacy_fallback` switch is worked out and turned to false, then Grade Points should start showing up for all terms, not just Legacy-Cutoff-and-onwards terms.  Reason being, CampusOracle doesn't have this data, but EDODB does.
> 8.1 - Academic Summary - Add 'Grade Point' Column

- app/models/my_academics/academics_module.rb
- app/models/my_academics/semesters.rb
- spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-28717
* Cleans up some minor bugs when switching the `allow_legacy_fallback` flag to `false`.
* Updates the Rspec tests to not expect a `semesters[:additionalCredits]` node when only pulling from CS.
* Double-checked with Student Records regarding the `semesters[:additionalCredits]` node - we are pulling EAP/AP/UC EXT data from there according to #3483 - all of which are covered by other avenues in CalCentral (can expand more on this if needed)
* Would like @nkutub to give this a review before merging
* Once this is merged, we'll be able to flip the switch in all clusters to only pull from EDODB.
> SISRP-28717 - 8.1: Update SOR to CS for CalCentral

- spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-32347
Hopefully this clears up the Rspec failures.
@nkutub made a good point that these flags should not be set in the Rspec, and that these tests should actually be rewritten as part of the next phase of the SOR saga.
> SISRP-32347 - Rspec Failures on semesters_spec.rb

- app/models/degree_progress/milestones_module.rb
https://jira.berkeley.edu/browse/SISRP-32470
User can have Degree Progress data without having any valid milestones - in this case, we want to show the "no data" message.
QA PR to follow.
> SISRP-32470 - Returns empty response when no Grad Div milestones to show

- src/assets/stylesheets/_academic_plan.scss
- src/assets/stylesheets/_academic_summary.scss
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academic_plan.html
- src/assets/templates/widgets/academic_summary/academic_summary_card.html
https://jira.berkeley.edu/browse/SISRP-32493
* Also fixes an issue with Academic Plan where it did not have an `isLoading` spinner.
* The QA PR will look a bit different, because of @redconfetti's PR #6600 that touches a bit on the Academic Plan card.  But, the end result will be exactly the same.
> SISRP-32493 - Update SOR to CS- Pre-Spring 2010 Data is Missing - Temporary Messaging

- app/models/calnet_crosswalk/proxy.rb
https://jira.berkeley.edu/browse/SISRP-32562
* Lots of stuff in the JIRA, but basically CalNet changed their 404 response body and we started logging errors because of it.
* This conforms to the new 404 response body.
> SISRP-32562 - CalnetCrosswalk::ByCsId being called with a UID, returning Error

- src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
- src/assets/templates/academics.html
- src/assets/templates/academics_student_profile.html
- src/assets/templates/myfinances.html
- src/assets/templates/widgets/academics/college_and_level.html
"Summer visitors" are students with one of a dozen or more particular academic plans.  In a prior release we created a filtered experience since they don't need full access to CC.
This became a problem for students that have a regular academic plan besides their summer visitor plan.  As a short term solution, we're reversing some of the filtering so those students can see necessary information.
https://jira.berkeley.edu/browse/SISRP-32149
Design:  https://jira.berkeley.edu/browse/SISRP-32933
> SISRP-32149 - Remove logic that hides certain features from summer visitors

- app/controllers/my_committees_controller.rb
- app/models/my_committees/committees_module.rb
https://jira.berkeley.edu/browse/SISRP-32561
* Cuts down on # of erroneous calls by not making API calls to `MyCommitteesController#member_photo` or `CalnetCrosswalk::ByCsId` if the EMPL ID given by CS starts with `GCMT`, which is a sign that the committee member is not Berkeley faculty.
Would appreciate it if @lyttam can take a look at this one, along w/ any other reviewers.
> SISRP-32561 - Investigate 'GCMT' CS IDs in Prod Error Logs

- app/controllers/my_badges_controller.rb
- app/models/user/api.rb
- spec/models/user/api_spec.rb
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/services/userService.js
- src/assets/stylesheets/_toolbox.scss
- src/assets/templates/launcher.html
- src/assets/templates/navigation.html
- src/assets/templates/widgets/profile_popover.html
- src/assets/templates/widgets/toolbox/academic_dates.html
https://jira.berkeley.edu/browse/SISRP-32544
Only users who are delegates and nothing else should have the special delegate experience.  If they are a delegate and also an advisor, for example, they still need to see stuff that is relevant to advisors.
Also did some refactoring of api/my/status feed.
> SISRP-32544 - Delegate UX: remove page links, bConnected icons, profile menu item

- app/controllers/sessions_controller.rb
https://jira.berkeley.edu/browse/SISRP-32341
Adds a bit of logging so we can validate a proper UID from SAML, whoever we are authenticating with.
> SISRP-32341 - Add logging of UID obtained from SAML response

- app/models/campus_solutions/link.rb
- fixtures/xml/campus_solutions/link_api_empty.xml
- spec/models/campus_solutions/link_spec.rb
https://jira.berkeley.edu/browse/SISRP-33187
This will prevent our proxies that fetch links from blowing up when the link API response is empty or otherwise bad.
> SISRP-33192 - Adds graceful handling of empty Link API responses

- app/models/edo_oracle/view_checker.rb
https://jira.berkeley.edu/browse/SISRP-33211
I realized that blank values doesn't necessarily mean that the data is invalid. For instance, not every course has a catalog number prefix or suffix.
```
- catalogNumber-prefix column value blank in SISEDO.API_COURSEV00_MVW results
- catalogNumber-suffix column value blank in SISEDO.API_COURSEV00_MVW results
- finalExam column value blank in SISEDO.CLASSSECTIONALLV00_MVW results
- WAITLISTPOSITION column value blank in SISEDO.ENROLLMENTV00_VW results
- WAITLISTPOSITION column value blank in SISEDO.CC_ENROLLMENTV00_VW results
```
The script now only checks if the query that includes the dependent columns succeeds or fails.
```
--- SISEDO Checkup ----------
Successes:
- SISEDO.API_COURSEV00_MVW has no issues
- SISEDO.CLASSSECTIONALLV00_MVW has no …
```
> SISRP-33211 - Removes check for column values

- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/academics_module.rb
- spec/models/my_academics/teaching_spec.rb
- spec/models/my_activities/webcasts_spec.rb
- src/assets/javascripts/angular/configuration/routeConfiguration.js
- src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-31645
* this fix mostly impacts courses with multiple sessions during summer terms
* added session code to course_id is academics feed if available.
* semesters card links now keyed off of course_id and not couse_slug
> SISRP-31645 - Displaying same Class Information page for students enrolled in courses with section scheduled in multiple sessions

- app/models/mailing_lists/site_mailing_list.rb
- spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6679
We're going to treat this as a known limitation for our test environments.
> CLC-6679 Canvas's Course Users API now censors email for pending invitees

- app/models/oec/department_mappings.rb
- spec/models/oec/department_mappings_spec.rb
I missed this boneheaded refactoring error because my higher-level tests all stubbed the broken method. Thanks for the catch, Bamboo!
> CLC-6666 Fix OEC cross-listings bug caught by testext

- app/controllers/campus_solutions/link_controller.rb
- app/models/campus_solutions/link.rb
- lib/link_fetcher.rb
- spec/lib/link_fetcher_spec.rb
- spec/models/campus_solutions/link_spec.rb
- spec/models/my_academics/advisor_links_spec.rb
- spec/models/my_academics/enrollment_verification_spec.rb
- spec/models/my_academics/grading_spec.rb
- spec/models/my_academics/student_links_spec.rb
https://jira.berkeley.edu/browse/SISRP-27378
This moves the URL parameter replacement up one layer from the caching, so that only the generic form of each link will be cached (and not the form that has particular URL params).
The way it was working before, a link with EMPLID param would be cached with "EMPLID=12345", and when that link was requested again for a new EMPLID, the item in the cache would be replaced by the new one.
> SISRP-27378 - moves url param replacement outside of cached model

- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/services/linkService.js
https://jira.berkeley.edu/browse/SISRP-33544
This is a temporary fix not intended to actually go into GL 9.0. It's just a workaround to get past an issue with CAS URL encoding so that testing can continue 05/30/17 - 05/31/17
> SISRP-33544 - UX Dev: Url encode ampersands used in query string of CS Links

- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-31677
The CalCentral back-end already ensures that Students are able to get the data from the My Academics feed, and that Advisors are able to obtain the Advisor Student Academics feed (for Student Overview page).
Because the back-end ensures that the user is gaining access ONLY to the link they should see, this updates the logic to only show the link that is available, with Advisor link presence suppressing the Student link from displaying. This closes the gap of an Advisor viewing-as a student, but not seeing the Advisor link.
> SISRP-31677 - Updates logic to allow link visibility for Advisors viewing as Students

- script/sis/verify_sis_api_endpoints.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6687
Crosswalk is now disabled on Junction, but our pre-release API verification script didn't get the news.
> CLC-6687 Do not verify Crosswalk endpoint if disabled

- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/services/linkService.js
https://jira.berkeley.edu/browse/SISRP-33544
This is an amendment to #6677
> SISRP-33544 - Url encode ampersands used in query string of CS Links

- app/models/campus_solutions/advising_expiry.rb
https://jira.berkeley.edu/browse/SISRP-33671
In GL 9, my refactor of `AdvisingResources` resulted in some log noise when `AdvisingExpiry` tried to remove that model from the cache.  That feed is made up of just links, and I don't see any reason to expire those, so I'm removing that piece to fix the error that's getting logged.
> SISRP-33671 - Removes the ENF-triggered expiry of advising links

- spec/controllers/my_registrations_controller_spec.rb
https://jira.berkeley.edu/browse/SISRP-34180
* Local `terms` and Bamboo `terms` are different for this test - I'm not sure why exactly, but that's a different problem.
* Changed the test to accommodate any kind of `terms` fixture, or any kind of fixture used by the Controller.
> SISRP-34180 - Fix Bamboo MyRegistrationsController Error

- app/models/my_academics/semesters.rb
- spec/models/my_academics/semesters_spec.rb
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-33580
For each semester in the feed, if the feed was being filtered for a delegate user then we were removing the semester `slug`.  We would then rely on the existence or non-existence of that key in the UI to determine whether to suppress information that a delegate shouldn't see.
Unfortunately this caused `merge_withdrawals` to blow up because it relies on the slug being present.  This fix sets a `filteredForDelegate` flag instead of removing the `slug`.
> SISRP-33580 - Fixes bug in delegate-filtered semesters feed

- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-31823
The API that this template depends on is reflecting the wrong values for two nodes. The values should be swapped in the API, but we do not have time for that in GL 9.2
After this update the Academic Summary card will reflect the correct values. The [Transfer Credit card template](https://github.com/ets-berkeley-edu/calcentral/blob/e2ca0a6a/src/assets/templates/widgets/transfer_credit.html#L27,L28) already reflects this swap. 
It is noted in [SISRP-34230](https://jira.berkeley.edu/browse/SISRP-34230) that both of these templates should be updated once the API is fixed to reflect the proper values in the right nodes in [SISRP-34229](https://jira.berkeley.edu/browse/SISRP-34229).
> SISRP-31823 - UX: Academic Summary - Non-Adjusted and Transfer Credit Total Switched

- app/models/my_registrations/registrations_module.rb
https://jira.berkeley.edu/browse/SISRP-34223
* Luckily, there was an existing bug that made this implementation very easy to do!
> SISRP-34223 - For Grad/LAW student not enrollment then CNP message should be Red Colored Text 'Not Enrolled in Classes'

- app/models/oec/department_mappings.rb
- db/developer-seed-data.sql
- spec/models/oec/department_mappings_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6694
I'm impressed (in a queasy way) that the bug was legal Ruby syntax...
> CLC-6694 OEC: Exclude non-participating courses from room share checks

- app/models/berkeley/academic_roles.rb
https://jira.berkeley.edu/browse/SISRP-31635
Students with the 'grad' role see the default version of the Enrollment card... but we still need to flag their enrollment as 'grad' so that we can show the Late Add/Drop link on the card (only shows for grad, summerVisitor, and courseworkOnly roles).
> SISRP-31635 - adds 'grad' to enrollment roles

- src/assets/templates/widgets/enrollment/adjust.html
https://jira.berkeley.edu/browse/SISRP-31635
Academic roles are currently designed to be exclusive - for example, if someone has a Haas plan and a GRAD career, we assign only one role and plan takes precedence over the career.  In that instance, the enrollment card won't know that the person is a grad student because the Haas plan role prevented the GRAD career role from getting assigned.
This fix is a temporary workaround to enable Haas/GRAD students to see the Late Add/Drop link (which should show for ALL grad students).  In the future, we can rework the design of the academic roles to avoid this problem.
> SISRP-31635 - allows grad students who have a plan-based role to see Late Add/Drop link

- src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-34598
Fixes sorting issue in Rosters page, List view. Similar to #6697
> SISRP-34598 - DIS sort still not working in calcentral rosters

- app/models/canvas/course_settings.rb
- app/models/canvas_csv/provide_course_site.rb
- app/models/canvas_lti/project_provision.rb
- spec/models/canvas/course_settings_spec.rb
- spec/models/canvas_csv/provide_course_site_spec.rb
- spec/models/canvas_lti/project_provision_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6707
Aimed at a Junction-only emergency release to be deployed before July 15, when Instructure's change takes effect.
> CLC-6707 Set home page of new sites to our preferred default

- app/models/my_academics/exams.rb
- spec/models/canvas/course_enrollments_spec.rb
Two tests failed on the master testext build.  The failures seem to be related to differences in Ruby implementations between v1.9.3 and v2.3.
> SISRP-26133 - Fixes Ruby compatibility-related test failures

- Gemfile
- Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-26133 (JRuby upgrade)
https://jira.berkeley.edu/browse/SISRP-34748 (Problem related to upgrade that this PR attempts to address)
@raydavis' last build using jruby-openssl 0.9.19 worked; here's hoping that downgrading from 0.9.20 fixes our slow build problem.
> SISRP-26133 - Downgrades openssl to 0.9.19

- app/models/my_academics/transfer_credit.rb
- fixtures/xml/campus_solutions/transfer_credit.xml
- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-34230
We ended up not reverting the swap, because the swap was actually correct. We instead ensured that the keys used are more correct, specifically the 'unitsNonAdjusted' being renamed as 'unitsAdjusted'... because that's actually what it represents.
> SISRP-34230 - Revert Non-Adjusted and Total Transfer Credit Unit count after API Swap

- Gemfile
- Gemfile.lock
When running `bundle install` after the jruby upgrade, we were seeing this message:
```
Downloading rspec-rails-3.1.0 revealed dependencies not in the API or the
lockfile (rspec-support (~> 3.1.0)).
Either installing with `--full-index` or running `bundle update rspec-rails`
should fix the problem.
```
The "problem" was that our Gemfile and Gemfile.lock were both specifying rspec-support ~> 3.1.2 (which allows anything 3.1.2 and above, short of 3.2).
I changed it to allow rspec-support-3.1.0 and above, short of 3.2 (see https://rubygems.org/gems/rspec-rails/versions/3.1.0).  This should allow us to run a clean `bundle install` without doing any extra steps.
> SISRP-26133 - Fixes rspec-rails dependency issue

- app/models/degree_progress/milestones_module.rb
https://jira.berkeley.edu/browse/SISRP-34908
The API is changing so that every milestone has an `<ATTEMPTS>` node.  CalCentral will only consider the "QE Results" milestone attempts.
> SISRP-34908 - Handle milestone attempts only for QE Results

- npm-shrinkwrap.json
https://jira.berkeley.edu/browse/SISRP-31448
* Follow-up for #6766, although I had aligned the font-awesome package in `package.json`, I totally forgot that I had to update the `npm-shrinkwrap.json` too.  This is why the clusters were still on font-awesome@4.7.0.
> SISRP-31448 - Update font-awesome in npm-shrinkwrap.json

- npm-shrinkwrap.json
Reverts ets-berkeley-edu/calcentral#6769
* 1 of 3 reversions.  3rd reversion being #6758 - but hopefully we won't need to do that one.  
* Needs to be reverted due to the bug outlined in https://jira.berkeley.edu/browse/SISRP-31448, that @raydavis and @pfarestveit unearthed.
> Revert "SISRP-31448 - Update font-awesome in npm-shrinkwrap.json"

- Gemfile
- Gemfile.lock
QA PR for #6786 
https://jira.berkeley.edu/browse/SISRP-29026
> [QA] SISRP-29026 - Downgrades jruby-openssl to lowest version compatible with jruby-9.1.5.0

- Gemfile
- Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-29026
> [QA] SISRP-29026 - puts jruby-openssl back to 0.9.19

- .rvmrc
- .travis.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- app/models/my_academics/college_and_level.rb
- script/update-build.sh
jruby-openssl-0.9.19 seemed to cause performance issues - so we are switching back to the last-used version, 0.9.7.  This requires a downgrade of jruby to 9.0.* (going with 9.0.1.0 in this case).
> SISRP-26133 - Downgrades jruby and jruby-openssl

- script/build-torquebox.sh
`bundle install` gets run twice during a testext build on bamboo.  This will force it to use the same gemset both times.
> SISRP-26133 - Adds GEMSET param to build-torquebox script

- src/assets/javascripts/angular/services/rosterService.js
https://jira.berkeley.edu/browse/SISRP-35815
* Updates logic to rely on 'enroll_status' code, rather than the 'waitlist_position' value, as it appears that the waitlist position is not always present for waitlisted rosters
* Also includes update to docs to specify specific Bundler version when setting up workstation
> SISRP-35815 - GSI's not able to view waitlist details in Cal Central 

- app/controllers/sessions_controller.rb
- config/routes.rb
https://jira.berkeley.edu/browse/SISRP-35050
Adds HTTP Delete route for /logout that does not return redirect URL in JSON response, but instead directly redirects the user to CAS for logout after destroying session. Needed to support the 'Logout' button presented in CCAdmin.
> SISRP-35050 - CCAdmin logout button does not log you out

- .travis.yml
- app/models/edo_oracle/oec.rb
- app/models/oec/api_task_wrapper.rb
- app/models/oec/department_mappings.rb
- app/models/oec/queries.rb
- app/models/oec/sis_import_task.rb
- app/models/oec/task.rb
- spec/models/edo_oracle/oec_spec.rb
- spec/models/oec/api_task_wrapper_spec.rb
- spec/models/oec/sis_import_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6739
These changes all affect the include-only-these-explicit-departments code path in the OEC UX.
The include-all-participating-departments logic remains buried in `Oec::Tasks initialize`:
```
@departments_filter = if opts[:dept_codes]
{dept_code: opts[:dept_codes].split}
else
{include_in_oec: true}
end
```
and `Oec::SisImportTask run_internal`:
```
Oec::DepartmentMappings.new(term_code: @term_code).by_dept_code(@departments_filter).each do |dept_code, course_codes|
```
where the `course_codes` values eventually make their way to `EdoOracle::Oec.depts_clause` calls.
> CLC-6739 OEC should include explicitly selected non-participating departments

- app/models/my_committees/committees_module.rb
- app/models/my_committees/faculty_committees.rb
- spec/models/my_committees/committees_module_spec.rb
- spec/models/my_committees/faculty_committees_spec.rb
https://jira.berkeley.edu/browse/SISRP-34657
Previously, a committee was presented to faculty as 'Completed' if the student had finished the necessary milestones.  With this change we will instead show a faculty committee as 'Completed' if the faculty member's service on the committee has ended.
> SISRP-34657 - Marks faculty committee as active based on service date

- app/models/my_committees/committees_module.rb
- app/models/my_committees/faculty_committees.rb
- app/models/my_committees/student_committees.rb
- spec/models/my_committees/committees_module_spec.rb
- spec/models/my_committees/faculty_committees_spec.rb
- spec/models/my_committees/student_committees_spec.rb
- src/assets/templates/widgets/academics/higher_degree_committee_member.html
https://jira.berkeley.edu/browse/SISRP-34658
Students will now be able to see the start and end date of each faculty member's service on that student's committees.
> SISRP-34658 - Surfaces member service dates on Student Committees card

- spec/models/my_academics/grading_spec.rb
https://jira.berkeley.edu/browse/SISRP-30494
'test' environment tests had configurations in place that 'testext' did not. This update ensures that they're properly stubbed in both environments.
> SISRP-30494 - Fix failing testext tests

- fixtures/json/hub_academic_status.json
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/my_committees/committees_module_spec.rb
- src/assets/templates/widgets/academics/degrees_conferred.html
Student can have two types of honor attached to their conferred degree - a general scholarship honor and a plan honor (AKA honor for scholarship in a plan).  This update will surface the plan honors, and will also fix the general scholarship honor so that it displays the full name rather than an abbreviated version.
https://jira.berkeley.edu/browse/SISRP-32864
This update also fixes a bug:  https://jira.berkeley.edu/browse/SISRP-35376
> SISRP-32864 - Surfaces honors for scholarship in a plan

- app/models/my_committees/committees_module.rb
- app/models/my_committees/faculty_committees.rb
- app/models/my_committees/student_committees.rb
- spec/models/my_committees/faculty_committees_spec.rb
- spec/models/my_committees/student_committees_spec.rb
- src/assets/templates/widgets/higher_degree_committees.html
https://jira.berkeley.edu/browse/SISRP-36097
Removes some data from the student-facing card, but leaves it as-is on the faculty card.  This required some moving around of code, since we want to have `CommitteesModule` contain only functionality that is shared between the faculty and student versions.
> SISRP-36097 - Removes milestone attempts and status from Student Committees card

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-34493
* Finally makes `My Academics` + `User Overview` follow the same logic on whether or not we show Residency information.
* Removes crazy spinner behavior, and unifies all proxy calls within the `Status and Holds` card to one spinner.
* Most importantly, removes unnecessary `$watch` usage.  [Here](https://www.airpair.com/angularjs/posts/angularjs-performance-large-applications) are some thoughts on why `$watch` should be avoided:
> scope.$watch() has now been discussed on several occasions. In general, scope.$watch is indicative of bad architecture. There are very few cases when some combination of services and reference bindings can not achieve the same results with lower overhead.
> SISRP-34493 - Change  Logic in Status and Holds Controller (+userOverview)

- app/models/berkeley/academic_roles.rb
- app/models/hub_edos/my_academic_status.rb
- app/models/my_academics/academics_module.rb
- app/models/my_academics/class_enrollments.rb
- app/models/my_academics/college_and_level.rb
- app/models/my_academics/graduation.rb
- public/dummy/json/academics.json
- public/dummy/json/enrollment_instructions.json
- spec/models/berkeley/academic_roles_spec.rb
- spec/models/hub_edos/my_academic_status_spec.rb
- spec/models/my_academics/class_enrollments_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/my_academics/graduation_spec.rb
- spec/support/spec_helper_module.rb
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/templates/widgets/enrollment/adjust.html
https://jira.berkeley.edu/browse/SISRP-34542
This is a big refactor of academic roles, and how they are used by the enrollment card to determine which version of the card to display.  It will enable more flexibility in how these roles are assigned, so that we can assign multiple roles to a single student based on their career, program, plan, or any other CPP stack data.
> SISRP-34542 - Refactors academic roles to handle multiple roles

- app/models/edo_oracle/queries.rb
- app/models/my_academics/gpa_units.rb
- spec/models/my_academics/gpa_units_spec.rb
https://jira.berkeley.edu/browse/SISRP-35805
* Obtains cumulative P/NP units from EDODB, which holds values that take into account repeat classes, which are more accurate than the values from the Hub (which are not technically wrong).
* Had to get rid of a "total unit" sanity check for this, because the cumulative units will no longer align with the EDODB units.  According to Design team, this is an expected non-issue.
> SISRP-35805 - P/NP Bug Fix - Calculate P/NP Total Correctly

- spec/models/my_committees/committees_module_spec.rb
Committees test fails occasionally due to a timing issue with date comparisons. Hoping to fix it by setting the time attributes to zero (making the mock data into a date rather than a timestamp).
> NOJIRA - Fixes intermittently failing unit test

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
https://jira.berkeley.edu/browse/SISRP-36120
Sort method cannot sort on nil, so forced code to convert to string just in case.
> SISRP-36120 - Class enrollment card not loading for law student

- spec/models/my_committees/committees_module_spec.rb
This test breaks our Travis build occasionally.  I don't think it provides enough value to justify putting any more effort into fixing, so I'm removing it.
> NOJIRA - Removes intermittently failing unit test

- app/models/canvas/admins.rb
- fixtures/json/canvas_admins_90242_page_1.json
https://jira.ets.berkeley.edu/jira/browse/CLC-6754
The undocumented change is currently on bCourses-Beta. Next production release is scheduled for 28 October 2017.
> CLC-6754 Canvas dropped sis_login_id from its Account Admins API

- gulpfile.js
- package.json
https://jira.berkeley.edu/browse/SISRP-36573
"Fixes" by forcing our builds to use gulp-clean-css@3.4.0.  It's not clear to me what the breaking change to the underlying clean-css library was, but this seems like an acceptable workaround.
> SISRP-36573 - Fixes issue with missing font-awesome assets

- src/assets/javascripts/angular/services/widgetService.js
https://jira.berkeley.edu/browse/SISRP-36753
This prevents the corresponding "Class Enrollment" section from collapsing when a link inside a section is clicked.
> widgetService: Fix nodeName check in `toggleShow`

- app/models/campus_solutions/link.rb
- public/dummy/json/degree_progress_ugrd.json
- public/dummy/json/enrollment_instructions.json
- public/dummy/json/student_resources.json
https://jira.berkeley.edu/browse/SISRP-36868
I originally thought that we needed to move from using HashConverter.camelize to [HashConverter.downcase_and_camelize](https://github.com/ets-berkeley-edu/calcentral/blob/eb795453/lib/hash_converter.rb#L15), but it turns out that this isn't a good idea, because the downcase will destroy existing camelcase keys. Both are used where appropriate for now.
We don't use this 'IS_CS_LINK' key, nor does the ccCampusSolutionsLinkDirective recognize :ISCsLink as a key. So this is just a simple maintenance task to remove the unused key.
```
>> hash = {'IS_CS_LINK' => 'test'}
=> {"IS_CS_LINK"=>"test"}
>> HashConverter.downcase_and_camelize(hash)
=> {:isCsLink=>"test"}
>> HashConverter.camelize(hash)
=> {:iSCsLink=>"test"}
>> hash = {:isCsLink => 'test'}
=> …
```
> SISRP-36868 - Update CampusSolutions::Link to include only proper camelcase key for isCsLink

- src/assets/templates/finaid.html
Reverts ets-berkeley-edu/calcentral#6868
This work is being deferred to `2018-01-28 Major` release.
> SISRP-32575 - Calentral FA Cards do not show for new Transfer students if enrolled in Summer w/non-degree plan

- app/models/campus_solutions/proxy.rb
- spec/models/campus_solutions/proxy_spec.rb
https://jira.berkeley.edu/browse/SISRP-29407
CS proxies will now return a 400 error response if the `<ERRMSGTEXT/>` node exists but is empty.
> SISRP-29407 - Handles empty ERRMSGTXT response

- app/models/my_academics/class_enrollments.rb
- spec/models/my_academics/class_enrollments_spec.rb
- src/assets/templates/widgets/enrollment/adjust.html
- src/assets/templates/widgets/enrollment/decide.html
- src/assets/templates/widgets/enrollment/explore.html
- src/assets/templates/widgets/enrollment/haas/explore.html
- src/assets/templates/widgets/enrollment/haas/plan.html
- src/assets/templates/widgets/enrollment/plan.html
- src/assets/templates/widgets/enrollment/schedule.html
This functionality wasn't completed and signed off on time. Reverting all commits in QA:
* Reverts "SISRP-37144 - [UX Design: Show time zone information for enrollment phases](4ac0de0c0260815cd6e22290dc74a7e236d1d519)"
* Reverts "SISRP-37144 - [Adds timezone offset for schedule of classes period. Updates times displayed in Class Enrollment sections](https://github.com/ets-berkeley-edu/calcentral/pull/6908/commits/510cc3cc4c0f958be8eb852be1b4022b5deb06a1)"
* Reverts "SISRP-37144 - [Surface timezone offset and render with provided offset](https://github.com/ets-berkeley-edu/calcentral/pull/6906/commits/2e3c66a0a5e7232ec7057577885f823fdb7f354f)"
> [QA] Revert commits for SISRP-37144

- app/models/my_academics/college_and_level.rb
- app/models/my_academics/grading.rb
- spec/models/my_academics/grading_spec.rb
https://jira.berkeley.edu/browse/SISRP-37370
These two errors have been occurring in instances where a response from CS is missing data and we aren't handling it gracefully.
> SISRP-37370 - Fixes errors in academics feed

- app/controllers/application_controller.rb
- app/controllers/new_admit_resources_controller.rb
- app/controllers/sir_statuses_controller.rb
- app/models/campus_solutions/new_admit_resources.rb
- app/models/edo_oracle/queries.rb
- config/routes.rb
- public/dummy/json/new_admit_resources.json
- spec/models/campus_solutions/new_admit_resources_spec.rb
- src/assets/javascripts/angular/controllers/widgets/newAdmitResourcesController.js
- src/assets/javascripts/angular/directives/expandableLinkListDirective.js
- src/assets/javascripts/angular/factories/newAdmitResourcesFactory.js
- src/assets/stylesheets/_new_admit_resources.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/dashboard.html
- src/assets/templates/directives/expandable_link_list.html
- src/assets/templates/widgets/new_admit_resources.html
Dev JIRA: https://jira.berkeley.edu/browse/SISRP-37573
Design JIRA: https://jira.berkeley.edu/browse/SISRP-36596
* 2 commits, one for back-end and one for the front-end
* Speaking with the designer, she mentioned that the format of the New Admit Resources card, which is a collection of expandable lists, will most likely be re-used in the future.  This is why I chose to create an angular directive (`cc-expandable-link-list`) for it, even though I'm only using it twice (couldn't use it more because of one-off weirdness, like inline links in the link description)
> SISRP-37573 - New Admit UX Dev: New Admit Resources card

- app/models/campus_solutions/person_name.rb
- spec/models/campus_solutions/person_name_spec.rb
- src/assets/javascripts/angular/controllers/widgets/profile/basicPreferredNameController.js
master PR for #6937 
The change will be included in a 1/21 emergency release.  This PR will port the change over to master so it doesn't get overwritten by the 1/28 release.
> SISRP-38047 - Prevents user from updating any name other than the preferred name

- app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-38220
I folded `CampusSolutions::Sir::MyDeposit` into `CampusSolutions::Sir::SirStatuses`, so I removed caching on `MyDeposit` since we're already caching it in `SirStatuses`.  This led to a breakage in functionality, since CalCentral was not updating correctly after payment was made to HigherOne (which triggers the ENF).  This should fix it.
> SISRP-38220 - Pay Deposit button stays even after a deposit is paid and it takes few minute to show confirmation message to student

- app/models/campus_solutions/new_admit_resources.rb
https://jira.berkeley.edu/browse/SISRP-38064
* Had to add a nil entry to the existing configuration to preserve ordering
> SISRP-38064 - New Resources Card  -> Financial Aid & Scholarships section links aren't in order as per design

- src/assets/templates/widgets/new_admit_resources.html
https://jira.berkeley.edu/browse/SISRP-38355
Dynamic link that goes to CS only if student has matriculated, it's also the only CS-centric link in the card, so we don't have to worry about this happening for the other links.
> SISRP-38355 - Error navigating back to calcentral from 'Add a Withdrawal request' efrom from New Admit Resource card

- app/models/edo_oracle/view_checker.rb
- app/models/my_academics/academic_records.rb
1.  Fixes the following error by replacing `nil` with an empty Hash.
```[2018-01-30 10:23:08] [FATAL] 
NoMethodError (undefined method `delete' for nil:NilClass):
app/models/my_academics/academic_records.rb:19:in `get_official_transcript_request_data'
app/models/my_academics/academic_records.rb:8:in `get_feed_internal'
```
2.  Adds some new views to the SISEDO view testing script.
> NOJIRA - Fixes academic records error and updates SISEDO view checker

- app/models/campus_solutions/my_financial_aid_data.rb
- app/models/campus_solutions/my_financial_aid_filtered_for_advisor.rb
- spec/models/campus_solutions/my_financial_aid_data_spec.rb
- spec/models/campus_solutions/my_financial_aid_filtered_for_advisor_spec.rb
- spec/models/campus_solutions/my_financial_aid_filtered_for_delegate_spec.rb
- src/assets/javascripts/angular/controllers/widgets/finaid/finaidHousingController.js
- src/assets/templates/widgets/finaid_housing.html
https://jira.berkeley.edu/browse/SISRP-38358
I address two separate bugs here - thus the two commits.
1.  The housing card showed an infinite spinner
2.  The `CampusSolutions::FinancialAidHousing` data wasn't being added to the `MyFinancialAidFilteredForAdvisor` or `MyFinancialAidFilteredForDelegate` feeds
> SISRP-38358 - Allows Housing card to display to advisors and delegates

- src/assets/javascripts/angular/controllers/pages/oecController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6775
Why was it ever in there? Why did it work?
> CLC-6775 Remove empty object from OEC controller scope

- app/controllers/campus_solutions/address_controller.rb
- app/models/campus_solutions/address.rb
- app/models/campus_solutions/person_data_updating_model.rb
- app/models/campus_solutions/posting_proxy.rb
- spec/controllers/campus_solutions/address_controller_spec.rb
- spec/models/campus_solutions/address_spec.rb
- src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js
- src/assets/javascripts/angular/services/profileService.js
https://jira.berkeley.edu/browse/SISRP-38229
New `valid?` method can be overridden to do specific validation in any class inheriting from `PostingProxy`.  I imagine we'll only need to do validation on POST requests.  In this case, we validate the address type against a whitelist because CS apparently does not do this type of validation, nor does the API.
> SISRP-38229 - Adds validation to address posting proxy

- src/assets/javascripts/angular/controllers/pages/finaidController.js
- src/assets/javascripts/angular/services/finaidService.js
- src/assets/javascripts/angular/services/userService.js
https://jira.berkeley.edu/browse/SISRP-38585
* `redirectToPage()` falls back to `redirectToHome()` if for some reason the page isn't available to the user.
* I had to do two redirects here because `finaidController` and `finaidSummaryController` both have code that can lead to a redirect.  Unfortunately, I had to leave them both in because there is very little overlap in the cases in which they are activated.
> SISRP-38585 - FA Aid Year Specific Page Redirect

- app/models/campus_solutions/sir/sir_statuses.rb
- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/view_checker.rb
- spec/models/campus_solutions/sir/sir_statuses_spec.rb
https://jira.berkeley.edu/browse/SISRP-38331
"gep" stands for "Global Edge Program"
> SISRP-38331 - CalCentral: Hide Pathways Selection Link from GEP Waitlist

- app/models/user/api.rb
- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-37023
* Originally, we gave applicants access to My Academics so that they can see their holds (#5478), but now we are only showing holds *after* matriculation, so we can remove that access.
> SISRP-37023 - Hide My Academics Page from New Admits

- src/assets/javascripts/angular/services/academicsService.js
https://jira.berkeley.edu/browse/SISRP-37758
* Updates the semester shown by default inside of the [Semester Classes card](https://confluence.ets.berkeley.edu/confluence/display/MYB/Semester+Classes+Widget) so that it prefers the semester that has grading in progress first, current semester second, the next upcoming semester third, and whatever semester is found that doesn't meet any of that criteria as a fallback.
> SISRP-37758 - Grading Links at Term Change - Dev for CLC

- app/controllers/campus_solutions/terms_and_conditions_controller.rb
- app/models/campus_solutions/my_terms_and_conditions.rb
- app/models/campus_solutions/terms_and_conditions.rb
- spec/controllers/campus_solutions/terms_and_conditions_controller_spec.rb
- spec/models/campus_solutions/terms_and_conditions_spec.rb
- src/assets/javascripts/angular/controllers/pages/finaidController.js
https://jira.berkeley.edu/browse/SISRP-38227
Prevents a user from accepting the terms and conditions for an aid year that isn't available.  For example, if they can only see data for aid years 2017 and 2018, they shouldn't be able to accept for 2019.
Also fixes a bug in FinaidController.
> SISRP-38227 - Adds validation to Terms & Conditions

- app/controllers/campus_solutions/financial_resources_controller.rb
- app/models/campus_solutions/financial_resources_general.rb
- app/models/campus_solutions/financial_resources_parameterized.rb
- config/routes.rb
- spec/models/campus_solutions/financial_resources_parameterized_spec.rb
- src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
- src/assets/javascripts/angular/factories/financesLinksFactory.js
- src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-38360
* In addition to adding a link to Summer Aid Estimator, this also lays the groundwork to move the work done in [financesLinksController.js](https://github.com/davidlimcheng/calcentral/blob/master/src/assets/javascripts/angular/controllers/widgets/financesLinksController.js) to the back-end, specifically to `CampusSolutions::FinancialResourcesGeneral` and `CampusSolutions::FinancialResourcesParameterized`.
* Why two models?  `FinancialResourcesGeneral` was made for all general all-purpose links that aren't user-specific and don't need any special parameters.  Since this is only serving one link at the moment, which is already cached in `Links`, I did not put any caching mechanisms on this model.
* `FinancialResourcesParameterized` was made for …
> SISRP-38360 - Add link to Summer Aid Estimator in CalCentral

- app/controllers/campus_solutions/sir_response_controller.rb
- app/models/campus_solutions/address.rb
- app/models/campus_solutions/checklist_data_updating_model.rb
- app/models/campus_solutions/email.rb
- app/models/campus_solutions/posting_proxy.rb
- app/models/campus_solutions/sir/my_sir_response.rb
- app/models/campus_solutions/sir/sir_response.rb
- app/models/campus_solutions/terms_and_conditions.rb
- spec/controllers/campus_solutions/sir_response_controller_spec.rb
- spec/models/campus_solutions/sir/sir_response_spec.rb
https://jira.berkeley.edu/browse/SISRP-38366
* Adds validation to the SIR response POST
* Also creates `ChecklistDataUpdatingModel` because `PersonDataUpdatingModel` really had nothing to do with SIR
* Changes `valid?` from a class method to an instance method.  I believe that it needed to be an instance method so that classes outside of the `CampusSolutions` module (in this PR, `SirStatuses` is under `CampusSolutions::Sir::SirStatuses`) could access inherited instance variables
* For that reason, changes `valid?` to an instance method on all the other models it was already defined in
> SISRP-38366 - New admits admission offer acceptance - improve validation

- app/models/concerns/academic_roles.rb
- app/models/degree_progress/my_graduate_milestones.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/concerns/academic_roles_spec.rb
- spec/models/degree_progress/my_graduate_milestones_spec.rb
- spec/models/my_academics/my_academic_roles_spec.rb
- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-38587
Three versions of the link to run the APR were created specifically for Grad, Law, and Haas students.  Each of those three links can be enabled/disabled independently of the others.
- Adds two new Haas plan-based roles. 
-- Only these 2 Haas roles should see the Haas link - other Haas roles will not see a link.
-- I did not update the other places in the code that use Haas roles to take these new roles into account.
- Adds 4 new plan-based roles for Law students
> SISRP-38829 - Adds APR link to My Academics > Grad Degree Progress

- spec/models/campus_solutions/sir/sir_response_spec.rb
https://jira.berkeley.edu/browse/SISRP-38366
* Previous PR broke these testext tests
* This test isn't really valid anymore, because "an invalid post" will never pass our server-side validation to reach an actual proxy call, and that piece is already being tested elsewhere in the spec.
> SISRP-38366 - New admits admission offer acceptance - improve validation (fix testext)

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-39127
@raydavis @paulkerschen - I've notified @dkawase and @yoshers about this update as this will affect the Canvas/bCourses enrollment query in EdoOracle::Queries.get_enrolled_students
See other `master` PR #7012 
See QA PR in #7018
> SISRP-39127 - Update CalCentral roster queries to use SISEDO.CC_ENROLLMENTV00_VW

- app/models/campus_solutions/sir/sir_statuses.rb
- spec/models/campus_solutions/sir/sir_statuses_spec.rb
https://jira.berkeley.edu/browse/SISRP-38975
When no data returned for new admit status, the SIR and New Admit Resources cards were receiving 500 responses and failing to display.
QA PR forthcoming.
> SISRP-38975 - fixes error preventing SIR and New Admit cards from loading

- src/assets/javascripts/angular/controllers/widgets/tasksController.js
- src/assets/javascripts/angular/services/tasksService.js
- src/assets/stylesheets/_tasks.scss
- src/assets/templates/dashboard_task_loop.html
- src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39233
Note: I'm leaving the 'furtherActionNeeded' display status in place because there are plans to make it into a sub-section (like Being Processed tasks) in this upcoming release. We're just waiting on design finalization in another JIRA.
> SISRP-39233 - Tasks Card - Remove "Further Action Needed" Section

- app/models/my_academics/gpa_units.rb
- app/models/my_academics/transfer_credit.rb
- spec/models/my_academics/gpa_units_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
https://jira.berkeley.edu/browse/SISRP-39773
Changes made to the `GpaUnits` feed:
- Merge the `TransferCredit` data into the feed on the back-end instead of in the UI code
- Cache the `TransferCredit` feed since we're using it in two places now
- Include all the keys in the `GpaUnits` response object, whether they have a value or they are nil
> SISRP-39773 - Hides cumulative transfer credits from Law students

- config/database.yml
- config/settings.yml
https://jira.berkeley.edu/browse/SISRP-34988
Makes it possible for SIS admins to configure production.local.yml (or other environment specific config files) to specify an SSL mode value.
```yaml
postgres:
sslmode: 'require'
```
See [PostgreSQL SSL Mode statements](https://www.postgresql.org/docs/9.1/static/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS)
> SISRP-34988 - CalCentral application does not connect to Postgres via SSL

- spec/models/edo_oracle/career_term_spec.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- spec/models/my_academics/semesters_spec.rb
Specs introduced under #7100 that run against a fake H2 database fail on Bamboo when they try to run against the real SISEDO database.
For now, we'll skip these tests when running in `testext`.
> SISRP-39586 - Prevents specs that hit H2 from running on bamboo

- app/models/concerns/careers.rb
- app/models/edo_oracle/career.rb
- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/all.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/gpa_units.rb
- app/models/my_academics/semesters.rb
- spec/models/concerns/careers_spec.rb
- spec/models/edo_oracle/career_spec.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-38837
- Non-Law students can see all past and present enrollments.
- Active Law students can only see their active career enrollments.
- A dual career law student (active in 2 careers) can see enrollments in both active careers
> SISRP-38837 - hides non-Law enrollments from active Law students

- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/all.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/semesters.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-38837
Since the query is shared by multiple callers, I had to move the filtering to the view model layer - otherwise, the filtering would sometimes get skipped because of caching.
> SISRP-38837 - Moves career filtering logic to the Semesters model

- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-40537
Changes logic around showing/hiding transcript links based on feedback from campus partner.
> SISRP-40537: Allows former Law students to see non-Law transcript links

- app/models/user/oauth2_data.rb
https://jira.berkeley.edu/browse/SISRP-37214
One usage of the deprecated class was already cleaned up during the JRuby/Rails upgrade (https://github.com/ets-berkeley-edu/calcentral/commit/dc24345764d06adc818ec0a0631e40d91bdd0975).  I must have missed this other one.
> SISRP-37214: Fixes OpenSSL deprecation warning

- app/controllers/application_controller.rb
https://jira.berkeley.edu/browse/SISRP-40732
When we created the `releaseAdmit` role, we inadvertently removed the ability for advisors to do student lookup on people with the ADMT_UX affiliation.
Please merge #7202 before this one.
> SISRP-40732: Allows advisors to look up released admits

- public/dummy/json/activities.json
- public/dummy/json/advising_student_academics.json
- public/dummy/json/badges.json
- public/dummy/json/cal1card.json
- public/dummy/json/classes.json
- public/dummy/json/cs_address.json
- public/dummy/json/finaid.json
- public/dummy/json/finaid_summary.json
- public/dummy/json/financials.json
- public/dummy/json/status.json
- public/dummy/json/up_next.json
- spec/ui_selenium/pages/my_dashboard_up_next_card.rb
- src/assets/javascripts/angular/controllers/widgets/upNextController.js
- src/assets/templates/widgets/up_next.html
https://jira.berkeley.edu/browse/SISRP-37550
Removes `feedName` and `lastModified` timestamp data from dummy feeds. Removes code from [Up Next card](https://wikihub.berkeley.edu/display/SIS/CalCentral+Up+Next+Card) that is no longer needed.
> SISRP-37550 - Remove leftover dependent code from LiveUpdates

- script/bamboo-tests.sh
https://jira.berkeley.edu/browse/SISRP-40517
I've tested this out on a personal-branch build on ETS Bamboo.
* By default, a test-and-build will only run Travis-CI-style unit tests. 12 minutes, no quarantines.
* If you pine for the full "testext" experience, you can go to "Configuration" / "Tasks" / "Command bamboo-tests.sh", and add `RAILS_ENV=testext` to the "Environment variables" property. 22 minutes, no shortage of quarantines.
> SISRP-40517 Bamboo should not run integration tests by default

- app/models/data_loch/s3.rb
- config/settings.yml
- lib/tasks/data_loch.rake
- spec/models/data_loch/s3_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6896
To reduce the pain of configuration + crontab + potential-rollback transitions across environments, the new code is backwards compatible. If it tests out OK, I'll create a follow-up JIRA to remove the backwards-facing code.
> CLC-6896 Make Junction's data available to multiple Nessie environments

- Gemfile
- Gemfile.lock
- app/models/google_apps/sheets_manager.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6899
My latest comment in the Jira describes the change.
I ran this on my laptop and it hummed along for 4+ hours until crashing on `Timeout error; url: https://apis.berkeley.edu/uat/sis/v1/terms`.  38 dept sheets were created in course-eval's `2018-D/Step 1: SIS Import` folder. The sis-data in those 38 looks legit. I would like to get this change on `junction-qa` and give it a proper run.  cc: @raydavis
> CLC-6899, OEC sis-import fix; google-drive gem update and better session mgmt

- Gemfile
- Gemfile.lock
- app/models/canvas/sis_import.rb
- app/models/canvas_csv/maintain_users.rb
- app/models/canvas_csv/refresh_all_campus_data.rb
- config/settings.yml
- lib/zipper.rb
- spec/models/canvas_csv/refresh_all_campus_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6919
Also takes care of CLC-6920, since `canvas_proxy.import_zipped_csvs` can be configured `false` to restore the old loop-APIs-then-loop-CSV-imports behavior.
> CLC-6919 Use zip archive for daily SIS Imports to bCourses

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-39065
Fixes issue in which 30 results are not being displayed because we are filtering out null ID rows in the CalCentral layer. This adds logic to filter out this rows in the DB layer.
QA PR to come after #7358 is merged.
cc @marcpechaitis
> SISRP-39065 - add logic to student lookup query to filter out null ID rows

- Gemfile
- Gemfile.lock
- app/models/oec/api_task_wrapper.rb
- config/settings.yml
- config/settings/production.yml
- lib/background_job.rb
- lib/background_thread.rb
- lib/backgroundable_shim.rb
- spec/lib/background_thread_spec.rb
- spec/lib/backgroundable_shim_spec.rb
- spec/support/canvas_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6928
By default, "production" environments (the clusters) will continue to rely on Torquebox, but "development" and "test" will exercise the new Torquebox-free code.
> CLC-6928 Allow concurrent-ruby in place of Torquebox Backgroundable

- spec/models/finaid/my_housing_spec.rb
An oversight on my part. `Concerns::DatesAndTimes.cast_utc_to_pacific` accounts for both PST and PDT.
> NOJIRA: Fixes DST-related test failure

- app/models/edo_oracle/user_courses/base.rb
- app/models/rosters/campus.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-41586
Decision is to pull this work due to a bug with the SISEDO views until 12/05. See QA PR #7408
* Revert "SISRP-41586 - Updates course section name format"
* This reverts commit 6067324385e3a0a981e111e5ca595a9f33509ce4.
* See #7401
* Revert "SISRP-41586 - Course Name Differs on Final Exam Schedule"
* This reverts commit 1528999bee8542ce02291764f72e6dcf306a06a3.
* See #7367
> Revert SISRP-41586

- app/controllers/sessions_controller.rb
- app/models/berkeley/user_roles.rb
- app/models/user/authentication_validator.rb
- config/settings.yml
- spec/models/hub_edos/user_attributes_spec.rb
- spec/models/user/authentication_validator_spec.rb
Changes Authentication Validator logic to accommodate users utilizing Single Sign-On from Slate. To sum it up:
- if you are an undergraduate student/applicant,
- check to see if you've authenticated via Slate SSO
- if so, deny if the `ADMT_UX` affiliation has not been provisioned
- continue login if otherwise
- if you are not an undergraduate student/applicant,
- use current login logic
cc @raydavis - Wanted to ping you since this functionality is a dependency of `CanvasLtiController`. This will change the way undergraduates are handled - the assumption was that if you are able to authenticate via CAS (as opposed to Slate), then you belong in CalCentral (line 64 in `authentication_validator.rb`). I hope this doesn't conflict with the Canvas …
> SISRP-42744 - CalCentral Access Fringe Case Review & Analysis

- app/models/canvas_lti/sis_adapter.rb
- app/models/edo_oracle/bcourses.rb
- app/models/edo_oracle/connection.rb
- spec/models/canvas_lti/sis_adapter_spec.rb
- src/assets/templates/canvas_embedded/_shared/background_job_error.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6957
These two queries play too central a role for the show to go on without them.
The PR also fixes end-user reporting of background job errors.
> CLC-6957 Short-circuit bCourses refresh on DB errors

- app/models/user/aggregated_attributes.rb
https://jira.berkeley.edu/browse/SISRP-44236
This bug was created with the merge of #7420 (SISRP-42744 - CalCentral Access Fringe Case Review & Analysis), so if that ticket for any reason needs to be reverted, this one does as well.
> SISRP-44236 - Some cc-dev/cc-sis-test logins are not recognizing staff affiliations

- app/models/google_apps/userinfo.rb
- app/models/user/oauth2_data.rb
- fixtures/json/google_userinfo.json
- spec/models/google_apps/userinfo_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6963
It never made sense that they made places that never enabled G+ go through a G+ branded API to access account info.
The bad news is that customers have to explicitly enable the more sensibly branded API before using it. Which means...
DO NOT MERGE UNTIL SIS CALCENTRAL HAS CONFIRMED ACCESS TO THE PEOPLE API!
> CLC-6963 Google finally drops the misleading "Google-Plus" API

- src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-44440
Removes left-over hard coded link details, after CS Link API was implemented for this link in #7454
> SISRP-44440 - Removes unused link details

- Gemfile
- Gemfile.lock
Original JIRA: https://jira.berkeley.edu/browse/SISRP-42655
This reverts commit 5a755e7b724e5640043ed772844ae17420e53971.
This is being reverted because it is a culprit for: 
https://jira.berkeley.edu/browse/SISRP-45121
Following this merge, we will retest and see if it is safe to include back in the `qa` branch.
> [QA] Revert "SISRP-42655: Update gems to fix security vulnerabilities"

- app/models/canvas/course.rb
- app/models/canvas/course_sections.rb
- app/models/canvas/external_tools.rb
- app/models/canvas_lti/toggle_sis_lti_tools.rb
- app/models/rosters/canvas.rb
- config/settings.yml
- config/settings/test.yml
- lib/tasks/canvas.rake
- spec/models/canvas/course_sections_spec.rb
- spec/models/canvas/external_tools_spec.rb
- src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js
- src/assets/templates/canvas_embedded/_shared/sections_table.html
- src/assets/templates/widgets/roster.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6998
The final step in achieving ODS independence. (Along with more attempts to deal with Canvas's buggy Tabs API.)
See JIRA comments for more background.
> CLC-6998 Disable E-Grades, Roster Photos, Official Sections for pre-CS Canvas sites

- app/models/edo_oracle/bcourses.rb
- app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7013
AKA "Withdraw Without Academic Penalty", in which a student is allowed to withdraw from a course after the drop deadline has passed.
> CLC-7013 Teach bCourses & OEC about the "W" GRADE_MARK

- app/models/edo_oracle/bulk.rb
QA-first workaround for https://jira.ets.berkeley.edu/jira/browse/CLC-7036
It's hard to interpret this as anything other than an Oracle bug, although it would be nice to get DBA confirmation. (Oracle has recently had at least one other bug relating to old-style WHERE-clause implicit joins.)
> [QA] CLC-7036 Work around order-dependent Oracle issue in WHERE clause

- lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7028
In my excitement yesterday I forgot to remove this reference to the 'note-topics' job.
> CLC-7028: Removes leftover (obsolete) job

- script/data-loch-snapshot.sh
When I tried to run the script on junction-dev, I ran into the old `Java::JavaLang::OutOfMemoryError`. Increasing the heap size resolved this.
> CLC-7059: Increases heap size for advisor data upload

- app/models/webcast/merged.rb
- app/models/webcast/recordings.rb
- spec/models/webcast/recordings_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7072
... dropping a bit of CalCentral-specific support code on the way.
> CLC-7072 Continue to support pre-CS Course Captures in bCourses

- config/settings/production.yml
Adjusts the data_loch path added in #7615, and the canvas_proxy path it was presumably copied from (which is already getting overridden in local configs, but no need to have a confusing default hanging around).
> CLC-7071 Update paths for temp directories in configs

- public/canvas/index.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7130
In regard to issue above, R1 peer says, "...you should be able to fix it by wrapping in function: window.addEventListener('load', () => { ... })".  This PR follows that recommendation.
I suggest you append `?w=1` to URL of this page.
Note: The `DOMContentLoaded` approach described in https://github.com/instructure/canvas-lms/commit/48c055ed0e3c4b8e11a1103566e86ae99b03e54e is "not reliable".
> CLC-7130, load canvas-customization when 'load' event is fired

- public/canvas/index.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7130
The QA dept ran Teena against this change in canvas-beta. See "Plain JavaScript ready() Alternative" at https://www.sitepoint.com/jquery-document-ready-plain-javascript/  to understand this diff.
> CLC-7130, if document.readyState is acceptable then load canvas-customization

- config/database.yml
- config/settings.yml
Rails 4 keeps this off by default due to stability issues in some DB implementations. It's been useful for some shops; disastrous for some others.
> CLC-7125 Try enabling the ActiveRecord Reaper for Oracle connections

- .travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7145
I reviewed output of the latest Travis build and I think we're ready for review/merge. The Javascript linting, CSS linting, and RSpec run in parallel. But, this PR is not about improving build time. It's about "jobs" syntax, use of conditionals, and exploring env variables. cc: @raydavis @paulkerschen @lyttam
> CLC-7145, tweak #1 for travis.yml: replace deprecated 'matrix' syntax with 'jobs'

- app/models/canvas_csv/base.rb
- app/models/canvas_csv/maintain_users.rb
- app/models/user/auth.rb
- app/policies/authentication_state_policy.rb
- config/initializers/rails_admin.rb
- db/developer-seed-data.sql
- db/migrate/20191101190708_add_canvas_whitelist.rb
- db/schema.rb
- spec/models/berkeley/course_policy_spec.rb
- spec/models/canvas_csv/maintain_users_spec.rb
- spec/models/user/auth_spec.rb
- spec/policies/authentication_state_policy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7135
This PR also removes the obsolete `author` account type, which was originally used to support campus-link-list editing.
> CLC-7135 Whitelist to block inactivation of bCourses accounts

- .travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7146
We use the "artifacts" add-on to upload to s3: https://docs.travis-ci.com/user/uploading-artifacts
The strategy: When a PR is merged, Travis will run another build to (1) build the knob and (2) upload it to s3. This strategy is controlled by conditionals in `.travis.yml`. For example, `if: type = push`. Again, building of knob and s3 upload will not happen when PR is first submitted.
> CLC-7146, aws s3 cp ojdbc7.jar to local lib, during package phase

- .travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7147
The deploy script will download `s3://${bucket}/${branch}/latest.txt`, grab info, and download the specified knob file.
> CLC-7147, Travis build uploads 'latest.txt' to reduce work for deploy script

- .travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7192
`npm install` was not run if `type = push` (i.e., when build `calcentral.knob`) thus we were missing `node_modules` in deploy.
> CLC-7192, 'npm install' with both push and pull

- .travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7208
This PR appends the full commit hash, not the seven char abbreviation. This might be more convenient.
> CLC-7208, add git commit hash to identifier of build artifact

- script/deploy/deploy-to-current-node.sh
- script/migrate.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7213
prod deploys will use `deploy-to-current-node.sh`, which tolerates same-knob-id deploys. Other environments use the more restrictive `deploy-to-all-nodes.sh`. Use `?w=1` to review.
> CLC-7213, in prod, Ops might need to deploy same knob-id more than once

- script/deploy/_cron_pre_deploy_task.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7217
See Jira for the deets.
> CLC-7217, deploy-junction cron in dev/qa must grab 'fresh' deploy scripts prior to exec

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/initializers/secure_headers.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7204
The gem API has substantially changed. See https://github.com/github/secure_headers/blob/master/docs/upgrading-to-3-0.md: "secure_headers 3.0 is a near-complete rewrite."
> CLC-7204 Update secure_headers gem

- app/models/data_loch/stocker.rb
- app/models/edo_oracle/bulk.rb
- lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/BOAC-3314
Though academic standing entries come with a term attached, the BOA UX won't be thinking of them as per-term values and the update schedule doesn't fit with the rest of our per-term data. Accordingly we'll just grab the most recent standing available per SID and treat it as non-term-specific data.
> BOAC-3314 Add academic standing to nightly loch jobs

- app/models/canvas_csv/base.rb
- app/models/canvas_csv/maintain_users.rb
- app/models/canvas_csv/refresh_campus_data_base.rb
- app/models/canvas_csv/refresh_campus_data_recent.rb
- app/models/canvas_csv/site_memberships_maintainer.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7325
The main thing here is that the job looks at CSV exports from previous jobs so it doesn't attempt to redo their work. Also some general code cleanup and streamlining.
> CLC-7325 bCourses recent-update job takes previous job results into account

- app/models/webcast/recordings.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7392
`fixtures/course_capture/legacy_recordings.json` is being used in non-test envs. We _should_ be using the file under `~/.calcentral_config/`
> [JQA] CLC-7392, webcast/recordings init fix: 'fake' false in non-test env

- config/environments/development.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7479
Previous PR removed `sass` but not all sassiness. Error at startup: `NoMethodError: undefined method `sass' for Rails::Application::Configuration`
> CLC-7479, Junction is a bit too sassy

- app/models/berkeley/term.rb
- app/models/berkeley/terms.rb
- lib/cache/cacheable_date_time.rb
- spec/lib/cache/cacheable_date_time_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7459
Devs who have noticed a slew of “invalid offset is ignored” warnings in our recent spec runs might be interested in https://github.com/jruby/jruby/issues/6385. It hits us whenever we try to stash term dates in the Rails cache, and we can work around it with a simple wrapper class using Ruby delegation.
> CLC-7459 Work around JRuby 9.2 DateTime serialization issue

- Gemfile
- Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-7459
Who here is sick of seeing
```
~/.rvm/gems/jruby-9.2.13.0@calcentral/gems/log4r-1.1.10/lib/log4r/outputter/outputter.rb:54: warning: `+' after local variable or literal is interpreted as binary operator
~/.rvm/gems/jruby-9.2.13.0@calcentral/gems/log4r-1.1.10/lib/log4r/outputter/outputter.rb:54: warning: even though it seems like unary operator
~/.rvm/gems/jruby-9.2.13.0@calcentral/gems/log4r-1.1.10/lib/log4r/formatter/formatter.rb:72: warning: `+' after local variable or literal is interpreted as binary operator
~/.rvm/gems/jruby-9.2.13.0@calcentral/gems/log4r-1.1.10/lib/log4r/formatter/formatter.rb:72: warning: even though it seems like unary operator
```
on every startup, spec and script run? I sure am!
> CLC-7459 Use Log4r fork with syntax fix

- app/models/edo_oracle/connection.rb
- app/models/edw_oracle/connection.rb
- config/database.yml
- config/initializers/populate_sisedo_test_data.rb
- config/initializers/populate_sysadm_test_data.rb
- config/settings.yml
- config/settings/production.yml
- config/settings/test.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7488
The oracle_enhanced adapter uses the same config pattern as Postgres, so no more need for distinct `edodb_test` and `edwdb_test` config groups.
> CLC-7488 Condense Oracle configs across environments

- src/components/bcourses/UserProvision.vue
- src/router.ts
- src/views/StandaloneLti.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7540
This is just to get the /canvas/user_provision routing in place - styling and function calls don’t work. The idea is that StandaloneLti.vue is a simple wrapper view that can load the bCourses tools outside the LTI context, as in the old Angular setup.
> CLC-7540 Initial routing + template for standalone User Provision

- src/components/Footer.vue
- src/components/bcourses/roster/RosterList.vue
- src/components/bcourses/roster/RosterPhotos.vue
- src/components/toolbox/ToolboxHeader.vue
- src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7551
In local env:
* Developers see this toggle by default because `VUE_APP_DEBUG=true` in `.env.development`. You can override that value with `.env.development.local`, which is git-ignored. Article: [how-to-use-environment-variables-in-vue-js](https://medium.com/js-dojo/how-to-use-environment-variables-in-vue-js-273eba0102b0)
* Screen-reader alert shows in footer, as in BOA.
> CLC-7551, screen-readers have access to roster-view-mode toggle

- .gitignore
- script/deploy/_start-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7572
`public/assets` belongs to old Angular days. It's in the `qa` WAR files but not those built in `dev`. Devs should remove the dir locally, if present.
> CLC-7572, 'public/assets' is no longer in the mix

- public/lti.html
- vue.config.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7575
I'm using 'pages' feature in vue-cli: https://cli.vuejs.org/config/#pages
Unlike index.html, `lti.html` is not top-level HTML; it's a fragment. However, _vue-cli_ treats it as top-level HTML and injects 'head' element as shown below. 
```
<head><link ...></head>
<div class="cc-off-canvas-container bc-canvas-embedded" data-bc-iframe-resize>...</div><script type=module src=/static/js/chunk-vendors.425a010b.js></script>...
```
This might not render nicely in iFrame but let's see. We'll tweak it.
> CLC-7575, compile lti.html same as index.html (vue-cli)

- config/warble.rb
- script/deploy/_start-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7573
During the build, all front-end assets are "compiled" into the `dist/` directory. The `public/` dir is essential for that build step but it does not need to be in the WAR file. Let's not cause confusion, down the road, by having unused stuff in the deployment.
> CLC-7573, 'public' dir does not belong in WAR file

- src/main.ts
- src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7577
If they’re auth errors from the academics API, anyhow. Additional special cases can be worked in as needed.
> CLC-7577 Allow individual LTI components to handle errors

- src/api/canvas.ts
- src/components/bcourses/create/ConfirmationStep.vue
- src/components/bcourses/create/CreateCourseSiteHeader.vue
- src/components/bcourses/create/MonitoringJob.vue
- src/components/bcourses/create/SelectSectionsStep.vue
- src/views/CreateCourseSite.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7525
An all-in-one `CreateCourseSite` component is unwieldy. Breaking up its template code based on steps in workflow makes sense, methinks.
> CLC-7525, break CreateCourseSite.vue into components per 'workflowStep'

- script/deploy/_start-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7587
I'd like to use Apache config to serve `/oauth` instead of copying files around at deploy time.
> CLC-7587, remove 'oauth' copy in _start_tomcat.sh

- config/settings/production.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7587
I believe `~/tomcat9/webapps/ROOT/WEB-INF` is Rails.root. I tested the legacy_ccn_mappings config value in `~/.calcentral_config/production.local.yml` and Junction no longer complains about file not found.
> CLC-7587, 'terms.term_definitions_json_file' exists in settings; let's override in prod.yml

- src/components/bcourses/CourseSectionsTable.vue
- src/views/CreateCourseSite.vue
Checkbox values were switched to `section.ccn` but select-all logic was not updated.
> CLC-7530, fix select-all checkbox of select sections table

- src/components/toolbox/ActAs.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7599
Store-as-recent happens server-side when act-as session starts:
https://github.com/ets-berkeley-edu/calcentral/blob/bf11e27068c8b3b3e3a9780e62da076066125446/app/controllers/act_as_controller.rb#L49
> CLC-7599, No need for store-user-as-recent on client-side. And avoid CORs error on re-auth?

- src/assets/javascripts/angular/controllers/pages/oecController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7630
Since occasional memcached misses are a fact of life, the front end should retry OEC jobs a couple of times before assuming the worst.
> [QA] CLC-7630 OEC task polling: three times a failure

- src/components/bcourses/CourseAddUser.vue
- src/components/bcourses/SiteMailingList.vue
- src/components/bcourses/SiteMailingLists.vue
- src/components/bcourses/create/ConfirmationStep.vue
- src/components/bcourses/create/CreateCourseSiteHeader.vue
- src/views/CreateProjectSite.vue
Fixes https://jira.ets.berkeley.edu/jira/browse/CLC-7615 and similar problems elsewhere. Using `type=“submit”` on buttons and `@submit.prevent` in forms is the accessibility lesson of the day.
> CLC-7615 Fix keyboard navigation in Vue forms

- app/controllers/act_as_controller.rb
- app/controllers/application_controller.rb
- spec/controllers/bootstrap_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7620
This has no impact and no relation to masquerading in Canvas.
> CLC-7620, Junction act-as no longer requires reauth

- app/models/berkeley/teaching.rb
- app/models/canvas/merged_user_sites.rb
- app/models/canvas_csv/provide_course_site.rb
- spec/models/berkeley/teaching_spec.rb
- spec/models/canvas/merged_user_sites_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7547
> CLC-7547 Remove unnecessary past-term API calls from course provision feed

- script/deploy/_start-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7646
Having a static index.html in place can short-circuit server-side auth logic on app load.
> CLC-7646 Don't let Tomcat serve static html files

- app/models/canvas_csv/term_enrollments.rb
- config/settings.yml
- script/refresh-canvas-enrollments.sh
- script/refresh-canvas-recent.sh
- script/refresh-canvas-users.sh
- script/sync-canvas-guest-users.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7716
- Move some cache expirations from obsolete 8am to sensible midnight;
- Handle unexpectedly missing local CSV exports;
- Fix misleading message on script failure.
> CLC-7716 Stability improvements to Canvas enrollments refresh

- app/models/mailing_lists/site_mailing_list.rb
- config/settings.yml
- spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7711
> CLC-7711 bCourses mailing lists: set alternateId address source in configuration

- README.md
- script/deploy/_cron_pre_deploy_task.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7740
I want Ops to green-light this change before we merge.
> CLC-7740, deploy script mod to go with Github repo renaming: 'junction'

- README.md
- script/deploy/_cron_pre_deploy_task.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7740
If we need a patch release, from this instance of `qa` branch, then this script change will be necessary in order to deploy.
master PR is #8075
> [QA] CLC-7740, deploy script mod to go with Github repo renaming: 'junction'
