- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-22147
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5706
> [QA] SISRP-22147 - 6.0 - My Campus Links - remove Change of Academic Plan link

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-22147
The Change of Academic Pan form will not be ready for GL6.0. We will need to pull this code from the QA branch.
> SISRP-22147 - 6.0 - My Campus Links - remove Change of Academic Plan link

- app/models/user/basic_attributes.rb
https://jira.berkeley.edu/browse/SISRP-23117
> SISRP-23117 Guard against overlarge Oracle "SELECT IN ()" queries

- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-23272
> [QA] SISRP-23272 - Remove hard-coded text from the Enrollment Verification screen

- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-23272
Master PR of #5709
> SISRP-23272 - Remove hard-coded text from the Enrollment Verification screen

- app/controllers/campus_solutions/link_controller.rb
- app/models/campus_solutions/link.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/campus_solutions/link_spec.rb
https://jira.berkeley.edu/browse/SISRP-23228
> SISRP-23228 - 6.0d - Biz logic in CampusSolutions::Link modifies the cached CS response (localhost only)

- app/models/my_academics/college_and_level.rb
- fixtures/json/hub_academic_status.json
- public/dummy/json/academics.json
- public/dummy/json/hub_academic_status.json
- spec/models/hub_edos/academic_status_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/my_badges/student_info_spec.rb
- src/assets/javascripts/angular/controllers/widgets/photoController.js
- src/assets/javascripts/angular/controllers/widgets/transferCreditController.js
- src/assets/stylesheets/_profile.scss
- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-23083
* Removes cumulativeUnits data from My Academics College and Level feed (which were added in #5634)
* Retrofit CollegeAndLevel to prefer EDO Hub
* Adds Expected Graduation Term to My Academics feed for non-legacy students
> SISRP-22377 - 6.0d - My Academics - Academic Profile - Exp Grad Term

- app/models/calendar/preprocessor.rb
- spec/models/calendar/preprocessor_spec.rb
https://jira.berkeley.edu/browse/SISRP-23473
This code will not be exercised often, but for Oski and a few others it makes all the difference in the world.
> SISRP-23473 Class calendar integration: query LDAP for campus email if not otherwise available

- app/models/calendar/queued_entry.rb
- spec/models/calendar/preprocessor_spec.rb
https://jira.berkeley.edu/browse/SISRP-23457
> SISRP-23457 Class calendar integration: include section identifiers in event summary

- app/models/calendar/queued_entry.rb
- spec/models/calendar/calendar_integration_spec.rb
- spec/models/calendar/preprocessor_spec.rb
https://jira.berkeley.edu/browse/SISRP-23456
> SISRP-23456 Class calendar integration: back to 'UC Berkeley' in locations

- app/controllers/sessions_controller.rb
- app/models/hub_edos/user_attributes.rb
- spec/models/hub_edos/user_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-23303
The cheese stands alone.
> SISRP-23303 Derive CS ID, student ID from CS Affiliations feed

- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-23293
> SISRP-23293 - With current date it should say CNP notification but instead its Warning

- app/models/my_academics/class_enrollments.rb
- config/settings.yml
- config/settings/test.yml
- public/dummy/json/enrollment_instructions.json
- spec/models/my_academics/class_enrollments_spec.rb
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/factories/enrollmentFactory.js
- src/assets/templates/widgets/enrollment/adjust.html
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
- src/assets/templates/widgets/enrollment/consult_advisor.html
- src/assets/templates/widgets/enrollment/decide.html
- src/assets/templates/widgets/enrollment/decide_concurrent.html
- src/assets/templates/widgets/enrollment/explore.html
- src/assets/templates/widgets/enrollment/sites_concurrent.html
- src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-21639
> SISRP-21639 - 6.0 - Class Enrollment - Concurrent

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-23496
> SISRP-23496 Add push predicate hint to EdoOracle enrolled sections query

- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-23331
> SISRP-23331 - CNP status - do not display protected if student is registered, has paid bill

- app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-22287
> SISRP-22287 - 6.0d - EFT - Wire to ENF API for cache clear upon data change

- app/models/berkeley/grade_options.rb
- app/models/edo_oracle/adapters/common.rb
- spec/models/berkeley/grade_options_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsGpaController.js
https://jira.berkeley.edu/browse/SISRP-23391
> SISRP-23391 Add C/NC Grading Option

- app/models/my_academics/class_enrollments.rb
- spec/models/my_academics/class_enrollments_spec.rb
https://jira.berkeley.edu/browse/SISRP-21639
> SISRP-21639 - Updated expected instruction type code for Concurrent Enrollment Students

- public/dummy/json/my_advising.json
https://jira.berkeley.edu/browse/SISRP-22717
> SISRP-22717 Dummy JSON for My Advising

- app/models/advising/legacy_my_advising.rb
- config/settings.yml
- config/settings/test.yml
- spec/models/advising/legacy_my_advising_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
- src/assets/javascripts/angular/factories/myAdvisingFactory.js
- src/assets/stylesheets/_myadvising.scss
- src/assets/templates/academics.html
- src/assets/templates/academics_my_advising.html
* Introduces myAdvisorFactory
* Introduces boilerplate for Advising Card showing up on My Academics page
* 'advising' feature flag will now override the L&S Advising card (which is enabled via `legacy_advising`) feature flag.
https://jira.berkeley.edu/browse/SISRP-22142
> SISRP-22142 - Student Advising factory and card boilerplate, mechanism to disable L & S Advising card

- src/assets/stylesheets/_enrollment_verification.scss
- src/assets/templates/academics_enrollment_verification.html
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-23559
> SISRP-23559 - UX Enrollment Verification availability in View As

- app/models/advising/my_advising.rb
- public/dummy/json/my_advising.json
- spec/controllers/my_advising_controller_spec.rb
- spec/models/advising/my_advising_spec.rb
https://jira.berkeley.edu/browse/SISRP-22717
Follow up to #5736 with more back-end transformation to make life a bit easier for the front end.
- Remove extraneous wrapper keys;
- Suppress completed action items;
- Parse dates;
- Fetch deeplink URLs from the new link API;
- Make dummy JSON more realistic.
> SISRP-22717 Student advising card: more back end transformation

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
- src/assets/stylesheets/_myadvising.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/academics_my_advising.html
https://jira.berkeley.edu/browse/SISRP-22720
This PR assumes that the advising card will show to undergraduates only. If this assumption doesn't pass validation, a last fix may follow.
> SISRP-22720 Advising card front end

- app/models/textbooks/proxy.rb
- src/assets/javascripts/angular/controllers/widgets/textbookController.js
https://jira.berkeley.edu/browse/SISRP-23301
> SISRP-23301 Show Textbooks for waitlisted classes

- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-23468
> SISRP-23468 - Header missing after adding address

- app/models/advising/my_advising.rb
- spec/controllers/my_advising_controller_spec.rb
- spec/models/advising/my_advising_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/templates/academics_my_advising.html
https://jira.berkeley.edu/browse/SISRP-22720
Advising - it's not just for undergraduates any more!
Also, handle all the errors.
> SISRP-22720 Show Advising card to all active students; error handling

- app/models/my_academics/college_and_level.rb
- fixtures/json/hub_academic_status.json
- public/dummy/json/academics.json
- public/dummy/json/hub_academic_status.json
- spec/models/hub_edos/academic_status_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/my_badges/student_info_spec.rb
- src/assets/javascripts/angular/controllers/widgets/photoController.js
- src/assets/javascripts/angular/controllers/widgets/transferCreditController.js
- src/assets/stylesheets/_profile.scss
- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-23188
https://jira.berkeley.edu/browse/SISRP-23083
https://jira.berkeley.edu/browse/SISRP-22377
Temporary reversion of https://github.com/ets-berkeley-edu/calcentral/pull/5713 while we decide what to do with our choice between obsolete data and incomplete data.
> SISRP-22377 Revert My Academics Profile data source change, PR #5713

- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkItemDirective.js
- src/assets/templates/directives/campus_solutions_link_item.html
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
- src/assets/templates/widgets/enrollment/decide_concurrent.html
- src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-21639
See QA PR #5749
> SISRP-21639 - Update card title. Implement disabled Drop link. Update unavailable link notice

- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkItemDirective.js
- src/assets/templates/directives/campus_solutions_link_item.html
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
- src/assets/templates/widgets/enrollment/decide_concurrent.html
- src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-21639
See DEV PR #5747
> [QA] SISRP-21639 - Update card title. Implement disabled Drop link. Update unavailable link notice

- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-23682
> SISRP-23682 - Advising Resources links are not in order

- src/assets/templates/widgets/advisor/advising_links.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5750
Jira https://jira.berkeley.edu/browse/SISRP-23682
> [QA] SISRP-23682 - Advising Resources links are not in order

- app/models/rosters/campus.rb
- app/models/rosters/common.rb
- spec/models/rosters/campus_spec.rb
- spec/models/rosters/common_spec.rb
- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
https://jira.berkeley.edu/browse/SISRP-23749
See QA PR #5754
> SISRP-23749 - 6.0d - Class Info page - Enrollments Tab - Add Academic Career to Student Details

- app/models/rosters/campus.rb
- app/models/rosters/common.rb
- spec/models/rosters/campus_spec.rb
- spec/models/rosters/common_spec.rb
- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
https://jira.berkeley.edu/browse/SISRP-23749
See DEV PR #5753
NOTE: Bringing this into QA for 6.0d is still pending approval by Ray Davis (out of interest for Ben Hubbard)
> [QA] SISRP-23749 - 6.0d - Class Info page - Enrollments Tab - Add Academic Career to Student Details

- src/assets/templates/widgets/holds.html
https://jira.berkeley.edu/browse/SISRP-13613
> SISRP-13613 - UX DESIGN: Lack of Drop-Down Area Box on Status and Blocks Card in My Academics Page

- app/controllers/campus_solutions/student_resources_controller.rb
- app/models/campus_solutions/link.rb
- app/models/campus_solutions/student_resources.rb
- config/routes.rb
- public/json/campuslinks.json
- spec/controllers/campus_solutions/student_resources_controller_spec.rb
- spec/models/campus_solutions/student_resources_spec.rb
- src/assets/javascripts/angular/controllers/widgets/csLinkFactory.js
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/factories/studentResourcesFactory.js
- src/assets/templates/dashboard.html
- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-23268
> SISRP-23268 - 6.0d - Student Forms card

- app/models/hub_edos/user_attributes.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5760
> [QA] SISRP-23714 Handle Hub EDOs feeds which lack identifiers

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6422
> CLC-6422 Update bCourses honor code link

- public/canvas/canvas-customization.js
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5762
> [QA] CLC-6422 Update bCourses honor code link

- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-23757
QA PR of #5756
> [QA] SISRP-23757 - Ensure Summer 2016 Regstatus Expires after End of Instruction

- app/controllers/campus_solutions/student_resources_controller.rb
- app/models/campus_solutions/link.rb
- app/models/campus_solutions/student_resources.rb
- config/routes.rb
- public/json/campuslinks.json
- spec/controllers/campus_solutions/student_resources_controller_spec.rb
- spec/models/campus_solutions/student_resources_spec.rb
- src/assets/javascripts/angular/controllers/widgets/csLinkFactory.js
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/factories/studentResourcesFactory.js
- src/assets/templates/dashboard.html
- src/assets/templates/widgets/student_resources.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5732
> [QA] SISRP-23268 - 6.0d - Student Forms card

- app/controllers/advising_student_controller.rb
- app/models/campus_solutions/advising_resources.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-22619
> SISRP-22619 - 6.0 - Add student-specific links to Personal Summary card

- app/controllers/advising_student_controller.rb
- app/models/campus_solutions/advising_resources.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/toolbox/user_preview.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5738
> [QA] SISRP-22619 - Add student-specific links to Personal Summary using Link API

- app/controllers/campus_solutions/enrollment_verification_deeplink_controller.rb
- app/controllers/campus_solutions/enrollment_verification_messages_controller.rb
https://jira.berkeley.edu/browse/SISRP-23777
QA PR of #5764
> [QA] SISRP-23777 - Enrollment verification - advisors have access to /api/campus_solutions endpoints

- app/models/hub_edos/demographics.rb
- spec/models/hub_edos/demographics_spec.rb
https://jira.berkeley.edu/browse/SISRP-23531
> SISRP-23531 Ignore unparsable Residency data in Demographics

- app/models/hub_edos/demographics.rb
- spec/models/hub_edos/demographics_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5767
> [QA] SISRP-23531 Ignore unparsable Residency data in Demographics

- src/assets/javascripts/angular/controllers/widgets/profile/workExperienceSectionController.js
https://jira.berkeley.edu/browse/SISRP-22987
> SISRP-22987 Protect against inconsistent payloads from Work Experience API

- src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-23968
See QA PR #5772
**NOTE:** Awaiting confirmation from functional owners in [SISRP-23853](https://jira.berkeley.edu/browse/SISRP-23853)
> SISRP-23968 - UX Message Concerning Info Accuracy during transition from legacy to new

- src/assets/javascripts/angular/controllers/widgets/billingController.js
https://jira.berkeley.edu/browse/SISRP-23528
See DEV PR #5773
> [QA] SISRP-23528 - Cal Central Suppress zero amounts in billing details

- app/models/advising/my_advising.rb
- app/models/campus_solutions/link.rb
- spec/models/advising/my_advising_spec.rb
- src/assets/templates/academics_my_advising.html
https://jira.berkeley.edu/browse/SISRP-23764
> SISRP-23764 - Academics > Advising > Appointment Self Service - Return to CalCentral link is not working

- src/assets/javascripts/angular/controllers/widgets/facultyResourcesController.js
- src/assets/templates/faculty-resources.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5739
> [QA] SISRP-21962 - 6.0d - Faculty Resources - add link to Action Center

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-23980
Mop-up from https://github.com/ets-berkeley-edu/calcentral/pull/5732
> SISRP-23980 Remove empty "Forms" category from My Campus

- src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-23968
Reverts #5771
> Revert "SISRP-23968 - UX Message Concerning Info Accuracy during transition from legacy to new"

- src/assets/javascripts/angular/controllers/widgets/profile/workExperienceSectionController.js
Repeat of already QA-merged PR https://github.com/ets-berkeley-edu/calcentral/pull/5770
@pfarestveit spotted that it was missing from the QA branch despite what's shown on the earlier PR page on GitHub. I haven't been able to find out how it got lost after "Merge" was approved, but I have confirmed that other recent QA merges are still in place.
> [QA] SISRP-22987 Protect against inconsistent payloads from Work Experience

- src/assets/javascripts/angular/controllers/widgets/facultyResourcesController.js
- src/assets/templates/faculty-resources.html
https://jira.berkeley.edu/browse/SISRP-21962
Ready for Review...
> SISRP-21962 - 6.0d - Faculty Resources - Link to Action Center

- app/models/campus_solutions/advising_resources.rb
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-24057
> SISRP-24057 - Remove Advising Notes link from Advising Resources card

- app/models/campus_solutions/advising_resources.rb
- src/assets/templates/widgets/advisor/advising_links.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5787
> [QA] SISRP-24057 - Remove Advising Notes link from Advising Resources card

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-24035
See DEV PR #5789
> [QA] SISRP-24035 - Personal Summary Card -> Advising resources section is not loading for Concurrent Students

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-24035
> SISRP-24035 - Personal Summary Card -> Advising resources section is not loading for Concurrent Students

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
https://jira.berkeley.edu/browse/SISRP-24113
> SISRP-24113 - Class Info page - Enrollments Tab - Academic Career Adjustments

- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-23925
> SISRP-23925 - 7.0 - Student Resources card link text does not match design

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-23274
> SISRP-23274 - 7.0 - Remove My Campus Links

- src/assets/templates/academics_my_advising.html
https://jira.berkeley.edu/browse/SISRP-24060
* JIRA ticket is listed as a Blocker, but Ben Hubbard has confirmed this is not a blocker for GL6.0d.
> SISRP-24060 - Advisor Viewing As : On Student’s My Academics -> Advising Card, All the clickable buttons and links should be disabled

- app/models/my_registrations/my_registrations.rb
https://jira.berkeley.edu/browse/SISRP-24173
> SISRP-24173 Fix term-transition loss of registration status feed

- app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-24098
Flying completely blind on this one -- it'll get tested on a test server if it merges.
> SISRP-24098 Change two Advising Resources links

- app/models/campus_solutions/advising_resources.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5795
> [QA] SISRP-24098 Change two Advising Resources links

- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-24027
> SISRP-24027 - Student Resources - some links are only partially visible on mobile view

- src/assets/stylesheets/_myfinances.scss
- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-24165
> SISRP-24165 - CalCentral: Amount Due Now and Total Balance displays oddly when unapplied credits exist

- src/assets/stylesheets/_myfinances.scss
- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-24165
* QA PR of #5804 for emergency release.
* Already in master, we'll need it in QA branch for testing.
> [QA] SISRP-24165 - CalCentral: Amount Due Now and Total Balance displays oddly when unapplied credits exist

- app/models/my_registrations/my_registrations.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/stylesheets/_status_holds.scss
- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-24387
* Lots of logic additions to cater to the CNP extension
* Also found a Promise bug within the Advisors User Overview page that would run a certain function before finishing all API calls/parsing
> [QA FIRST] SISRP-24387 - UX DEV: Status and Holds and Popover (CNP Emergency Update)

- app/models/my_registrations/my_registrations.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/stylesheets/_status_holds.scss
- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-24387
* Master PR of #5806
> SISRP-24387 - UX DEV: Status and Holds and Popover (CNP Emergency Update)

- src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-24414
See QA PR #5810
> SISRP-24414 - Hide My Academics - Advising widget for Law students

- src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-24414
> [QA] SISRP-24414 - Hide My Academics - Advising widget for Law students

- src/assets/javascripts/angular/directives/telPhoneInputDirective.js
- src/assets/templates/widgets/profile/contact_phone_editor.html
- src/assets/templates/widgets/profile/work_experience_editor.html
PR defines a new `telPhoneInputDirective.js` to address two issues in jira:
+ https://jira.berkeley.edu/browse/SISRP-20232 (`work_experience_editor.html`)
+ https://jira.berkeley.edu/browse/SISRP-17589 (`contact_phone_editor.html`)
> SISRP-20232 - Profile Work Experience: "phone" needs better validation

- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-24467
Another CNP nuance:
* Also knocks out [SISRP-24469](https://jira.berkeley.edu/browse/SISRP-24469) and [SISRP-24471](https://jira.berkeley.edu/browse/SISRP-24471)
> SISRP-24467 - Student who has R99 and no ROP, after Aug31st, CNP Exception message is not displayed.

- app/models/campus_solutions/profile_feature_flagged.rb
- app/models/user/aggregated_attributes.rb
- app/models/user/api.rb
- config/settings.yml
- public/dummy/json/status.json
- spec/models/user/aggregated_attributes_spec.rb
- spec/models/user/api_spec.rb
- spec/ui_selenium/pages/api_my_status_page.rb
- src/assets/templates/academics_student_profile.html
- src/assets/templates/myfinances.html
- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-23304
A bit of cleanup before the bigger identity stack refactoring...
> SISRP-23304 Rename misleading isCampusSolutionsStudent flag

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-23500
* Since the design calls for the link to be disabled for delegates (not shown in the JIRA, but discussed w/ Chara), I moved the delegate logic over to the HTML.
> SISRP-23500 - 7.0 - My Academics - Semesters (Law & Unofficial Transcript)

- public/dummy/json/advising_student_academics.json
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academicProfileController.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/javascripts/angular/services/academicsService.js
https://jira.berkeley.edu/browse/SISRP-22618
> SISRP-22618 - 7.0 - Student Overview - Personal Summary (Graduation Terms for Undergraduates)

- app/models/my_academics/college_and_level.rb
- fixtures/json/hub_academic_status.json
- spec/models/my_academics/college_and_level_spec.rb
https://jira.berkeley.edu/browse/SISRP-22085
> SISRP-22085 - My Academics (Student) - Profile Card - Add additional majors

- src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-24474
My embarrassing typo PR =(
> SISRP-24474 - Alert popover message count doesn't match with the alert messages.(Aug 31st date)

- app/controllers/advising_student_controller.rb
- config/routes.rb
- src/assets/javascripts/angular/controllers/widgets/lsAdvisingController.js
- src/assets/javascripts/angular/factories/lsAdvisingFactory.js
- src/assets/javascripts/angular/factories/myAdvisingFactory.js
https://jira.berkeley.edu/browse/SISRP-24062
> SISRP-24062 - Use Advisor specific API for Advisor card on Student Overview page

- app/models/hub_edos/affiliations.rb
- app/models/hub_edos/proxy.rb
- app/models/hub_edos/registrations.rb
- app/models/hub_edos/response_handler.rb
- app/models/hub_edos/student.rb
- app/models/hub_edos/work_experience.rb
- fixtures/json/hub_affiliations.json
- spec/models/hub_edos/affiliations_spec.rb
- spec/models/hub_edos/response_handler_spec.rb
https://jira.berkeley.edu/browse/SISRP-19059
I'm submitting fairly fine-grained PRs in case we need to cherry-pick any commits into an emergency release. See the commit messages for details.
> SISRP-19059 HubEdos cleanup before refactoring

- app/models/my_registrations/my_registrations.rb
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-24588
> SISRP-24588 - UX DEV: CNP GL7

- app/models/my_academics/academics_module.rb
- app/models/my_academics/class_enrollments.rb
- spec/models/my_academics/class_enrollments_spec.rb
https://jira.berkeley.edu/browse/SISRP-24707
I'm leaving slightly duplicated code in this for the benefit of [SISRP-24743](https://jira.berkeley.edu/browse/SISRP-24743)
> SISRP-24707 - CalCentral Class Enrollment logic fails on multiple academicStatuses

- config/settings.yml
- src/assets/templates/academics_semester.html
https://jira.berkeley.edu/browse/SISRP-24748
> SISRP-24748 - Feature Flag for GPA Calculator

- src/assets/javascripts/angular/factories/holdsFactory.js
- src/assets/stylesheets/_finaid_table.scss
- src/assets/stylesheets/_status_holds.scss
- src/assets/stylesheets/_widgets.scss
- src/assets/stylesheets/finaid_awards.scss
- src/assets/templates/cars_activity.html
- src/assets/templates/directives/finaid_table.html
- src/assets/templates/widgets/billing_activity.html
- src/assets/templates/widgets/finaid_communications.html
- src/assets/templates/widgets/holds.html
This PR is finishing off the PR https://github.com/ets-berkeley-edu/calcentral/pull/5803/commits/c53b7768ed92aa4c7ffd1b29de102b00cb9581be done by David K. if this PR is successfully merged, David's PR should be canceled.
> SISRP-13602 - UX DESIGN: Lack of Visual Arrow Indicator on Activity Card in Billing Details Page

- app/models/bearfacts/proxy.rb
- app/models/bearfacts/regblocks.rb
- app/models/campus_solutions/my_email.rb
- app/models/campus_solutions/person_data_expiry.rb
- app/models/campus_solutions/user_api_expiry.rb
- app/models/hub_edos/contacts.rb
- app/models/hub_edos/my_student.rb
- app/models/hub_edos/user_attributes.rb
- app/models/my_academics/exams.rb
- app/models/my_academics/gpa_units.rb
- app/models/my_academics/regblocks.rb
- app/models/my_academics/requirements.rb
- app/models/my_academics/transition_term.rb
- app/models/user/aggregated_attributes.rb
- app/models/user/api.rb
- app/models/user/student.rb
- public/dummy/json/status.json
- spec/models/hub_edos/user_attributes_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/user/aggregated_attributes_spec.rb
- spec/models/user/api_spec.rb
- spec/models/user/student_spec.rb
- spec/support/spec_helper_module.rb
- spec/ui_selenium/pages/api_my_status_page.rb
- src/assets/templates/academics_student_profile.html
- src/assets/templates/myfinances.html
- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-19059
Following on https://github.com/ets-berkeley-edu/calcentral/pull/5834 , with (we hope!) one step to go.
Under most circumstances, Hub Contacts appear to incorporate Hub Affiliations. See SISRP-24928 for more information.
> SISRP-19059 Minimize User::Api Hub dependencies

- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-24832
use badges factory to get law student status and hide link.
> SISRP-24832 - Remove withdraw link for law students (INC306025)

- app/models/berkeley/residency_message_code.rb
- app/models/my_academics/residency.rb
- spec/models/my_academics/residency_spec.rb
https://jira.berkeley.edu/browse/SISRP-24989
> SISRP-24989 Fix Residency handling of blank fields

- src/assets/stylesheets/_myadvising.scss
- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-24060
> SISRP-24060 - Making buttons and links disabled instead of hidden

- public/dummy/json/billing.json
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/factories/financesFactory.js
- src/assets/javascripts/angular/services/statusHoldsService.js
https://jira.berkeley.edu/browse/SISRP-24744
Adds a dummy source for billing data
Prevents JS console error from status holds service
> SISRP-24744 - Fixes registered, enrolled students with no Status information in the popover

- src/assets/templates/faculty_resources.html
add link and change wording on "Faculty Resources Card"
> SISRP-23877 - Dashboard (faculty) - Faculty Resources

- config/settings.yml
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/templates/academics.html
- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-24867
> SISRP-24867 - 7.0 - Remove link to appointments from advising card

- src/assets/javascripts/angular/controllers/widgets/profile/bConnectedController.js
https://jira.berkeley.edu/browse/SISRP-16948
> SISRP-16948 Fix class calendar checkbox handling

- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-25189
> SISRP-25189 Enable View Official Monthly Statement link for delegates

- src/assets/templates/widgets/billing_summary.html
Follow-up to https://github.com/ets-berkeley-edu/calcentral/pull/5849 -- thanks, @paulkerschen !
> SISRP-25189 Fix CSS of Monthly Statement link for financial delegates

- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-25189
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5849 & https://github.com/ets-berkeley-edu/calcentral/pull/5850
> QA SISRP-25189 Enable View Official Monthly Statement for delegates

- src/assets/templates/widgets/academics/college_and_level.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-24681
- Adds SID so advisors can see on the Student Overview
- Cleaned up inline styles from college_and_level and replaced with the table style used elsewhere
> SISRP-24681 - Adds SID to the Student Overview

- app/models/rosters/campus.rb
- config/settings.yml
- public/dummy/json/campus_rosters.json
- spec/models/rosters/campus_spec.rb
- src/assets/javascripts/angular/controllers/widgets/classInfoEnrollmentController.js
- src/assets/javascripts/angular/directives/sortableColumnDirective.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_classinfo.html
- src/assets/templates/directives/academics_class_info_enrollment.html
- src/assets/templates/directives/sortable_column.html
https://jira.berkeley.edu/browse/SISRP-24305
> SISRP-24305 - 7.0 - Dev - Add Section Overview card to Class Page - Enrollment tab/section

- app/models/edo_oracle/queries.rb
- app/models/rosters/common.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-21644
Depends on changes in the EDO DB.
> SISRP-21644 Exclude inactive majors from class roster views

- app/models/oec/courses.rb
- spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6420
> CLC-6420 OEC: Better department-specific validation

- app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6441
QA version of #5857.
> [QA] CLC-6441 Include 'stop further enrollment' sections in OEC queries

- config/settings.yml
Belated follow-up to https://jira.berkeley.edu/browse/SISRP-22703 and https://github.com/ets-berkeley-edu/calcentral/pull/5676
> SISRP-22703 Feature-flag enrollment_verification_deeplink was missing

- src/assets/templates/widgets/profile/demographic.html
- src/assets/templates/widgets/profile/editable_soon.html
https://jira.berkeley.edu/browse/SISRP-24874
> SISRP-24874 - Profile - Demographic Info says "editable in Summer 2016"

- src/assets/templates/widgets/profile/demographic.html
- src/assets/templates/widgets/profile/editable_soon.html
Master PR: https://github.com/ets-berkeley-edu/calcentral/pull/5864
Jira: https://jira.berkeley.edu/browse/SISRP-24874
> [ QA ] SISRP-24874 - Profile - Demographic Info says "editable in Summer 2016"

- public/dummy/json/academics_interim_two_sets_conflicts.json
- src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-25533
https://jira.berkeley.edu/browse/SISRP-25535
Two very small bugs that are now fixed that:
1) Show the message that final exams are tentative
2) Removes the line if there is only one semester present
> SISRP-25535 / SISRP-25533 - Removes line separator and adds tentative message

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5866
https://jira.berkeley.edu/browse/SISRP-25322
https://jira.berkeley.edu/browse/SISRP-25324
> [ QA ] SISRP-25322 - My Academics - Profile Card - Expected Graduation - Displaying as "2016 Fall" instead of "Fall 2016"

- app/models/campus_solutions/link.rb
- spec/models/campus_solutions/link_spec.rb
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/templates/widgets/student_resources.html
Main jira: https://jira.berkeley.edu/browse/SISRP-24502
Addresses the TypeError messages.
Realized too late I included the fix to this related jira: https://jira.berkeley.edu/browse/SISRP-24174
Addresses infinite spinner on student resources.
> SISRP-24502 - CalCentral prod: FATAL TypeError (can't convert nil into String) at campus_solutions/link.rb:47: 'get_url'

- app/models/hub_edos/user_attributes.rb
- app/models/user/api.rb
https://jira.berkeley.edu/browse/SISRP-25495
To reduce load on sys admins over the life of the next release, I'll also submit a QA PR.
> SISRP-25495 Fix CS ID logging

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/javascripts/angular/services/statusHoldsService.js
- src/assets/templates/widgets/status_and_holds.html
- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-24762
See also #5837, the previous commit for this fix.
* In addition to fixing the bug described in the JIRA, this PR moves the logic to show/hide CNP status into `statusHoldsService.js`.
> SISRP-24762 - Undergraduate Students with no reg, 0 units. have s09(Before Aug 30th) - There is CNP warning

- app/models/hub_edos/user_attributes.rb
- app/models/user/api.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/5873
Given the sample logs from Tuesday's load test, I'm worried about overwhelming ops with noise if this doesn't go in. PR reviewers should feel free to push back, though, since the change shouldn't otherwise impact end users.
> QA SISRP-25495 Fix CS ID logging

- src/assets/templates/widgets/gear_popover.html
- src/assets/templates/widgets/status_popover.html
https://jira.berkeley.edu/browse/SISRP-18299
First part of UX fix - show a spinner while the status portion of popover is still loading by moving spinner out of the status template
> SISRP-18299 - "Status" portion of status popover taking long time to load

- config/settings.yml
- src/assets/templates/widgets/profile/bconnected_service_loop.html
https://jira.berkeley.edu/browse/SISRP-25536
We were a bit premature with that CS retrofit...
> SISRP-25536 Add feature flag for Class Calendar sign-up

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- spec/controllers/campus_solutions/advising_resources_controller_spec.rb
- spec/models/campus_solutions/advising_resources_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
SISRP-25248 - Replaces hard-coded links in Advising Resources with calls to link api
https://jira.berkeley.edu/browse/SISRP-25248
> SISRP-25248 - Replaces hard-coded links in Advising Resources

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-22996
> SISRP-22996 - My Campus - police department links are broken

- src/assets/templates/widgets/toolbox/user_search_results.html
https://jira.berkeley.edu/browse/SISRP-19072
> SISRP-19072 - Advisor student lookup: search error message also shown on Recent and Saved tabs

- src/assets/javascripts/angular/services/statusHoldsService.js
https://jira.berkeley.edu/browse/SISRP-25717
> SISRP-25717 - CalCentral Dashboard TypeError: Cannot read property 'unitsEnrolled' of undefined

- README.md
- lib/memcached.rb
- lib/tasks/memcached.rake
- script/load-test-dev.sh
https://jira.berkeley.edu/browse/SISRP-25121
Adds library and Rake task support for more in-depth analysis of Memcached usage.
> SISRP-25121 Add support for Memcached analysis

- src/assets/templates/california_residency_status.html
simple wording change in HTML nothing more.
> SISRP-23614 - UX Design Bug Status and Holds Card modify text

- app/models/campus_solutions/my_checklist.rb
- app/models/my_activities/merged.rb
- app/models/my_classes/merged.rb
- app/models/my_registrations/my_registrations.rb
- app/models/my_tasks/google_tasks.rb
- app/models/my_tasks/merged.rb
- config/settings.yml
- spec/models/my_tasks/merged_spec.rb
https://jira.berkeley.edu/browse/SISRP-25121
Some lightweight adjustments before tackling My Academics. As usual, reviewing one commit at a time will probably be easiest.
> SISRP-25121 Adjust caching of MyActivities, MyTasks, MyClasses, MyChecklist, MyRegistrations

- src/assets/javascripts/angular/directives/loadErrorDirective.js
https://jira.berkeley.edu/browse/SISRP-25897
> SISRP-25897 - loadErrorDirective.js errors out when app gets 401 from photo api

- app/models/advising/my_advising.rb
- app/models/campus_solutions/advising_resources.rb
- app/models/campus_solutions/link.rb
- app/models/campus_solutions/student_resources.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/controllers/campus_solutions/link_controller_spec.rb
- spec/controllers/my_advising_controller_spec.rb
- spec/models/campus_solutions/link_spec.rb
- src/assets/javascripts/angular/controllers/widgets/facultyResourcesController.js
- src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-25232
This changes the shape of the link payload slightly, first by accommodating the new xml response from campus solutions, then reducing the returned json object by replacing `{ ... feed: { link: link } }` with `{ link: link }`
> SISRP-25232 - Link API Updates

- spec/ui_selenium/my_academics_data_final_grades_spec.rb
- spec/ui_selenium/my_academics_data_status_and_holds_spec.rb
- spec/ui_selenium/my_dashboard_data_classes_spec.rb
- spec/ui_selenium/my_finances_financials_cs_data_spec.rb
- spec/ui_selenium/pages/api_edos_student_page.rb
- spec/ui_selenium/pages/cal_central_pages.rb
- spec/ui_selenium/pages/my_dashboard_faculty_resources_card.rb
- spec/ui_selenium/pages/my_finances_billing_page.rb
- spec/ui_selenium/user_authorizations_spec.rb
- spec/ui_selenium/user_delegated_access_spec.rb
- spec/ui_selenium/util/web_driver_utils.rb
https://jira.berkeley.edu/browse/SISRP-26015
> SISRP-26015 - QA test fixes for v83

- app/models/campus_solutions/advising_resources.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-25391
> SISRP-25391 - 7.1 - Refactor Student Overview (Advisor) - Personal Summary card (Link API)

- spec/ui_selenium/pages/api_my_academics_page.rb
https://jira.berkeley.edu/browse/SISRP-26015
> SISRP-26015 - fix QA tests' handling of academics feed

- app/models/campus_solutions/link.rb
https://jira.berkeley.edu/browse/SISRP-25646
> SISRP-25646 - Adjust error logging in CampusSolutions::Link

- app/models/my_academics/class_enrollments.rb
- config/settings.yml
- spec/models/my_academics/class_enrollments_spec.rb
- src/assets/templates/widgets/enrollment/decide_concurrent.html
https://jira.berkeley.edu/browse/SISRP-25752
> SISRP-25752 - 7.1 - Retrofit Concurrent Enrollment links to the link API

- spec/ui_selenium/my_dashboard_data_classes_spec.rb
- spec/ui_selenium/pages/my_academics_semesters_card.rb
https://jira.berkeley.edu/browse/SISRP-26015
> SISRP-26015 - QA test fixes

- config/settings.yml
Just tidying up on my way out...
> NOJIRA Re-sort feature flags in settings.yml

- app/controllers/advising_student_controller.rb
- app/controllers/my_registrations_controller.rb
- app/models/campus_solutions/enrollment_term_expiry.rb
- app/models/my_academics/academics_module.rb
- app/models/my_academics/class_enrollments.rb
- app/models/my_academics/college_and_level.rb
- app/models/my_academics/gpa_units.rb
- app/models/my_academics/registrations.rb
- public/dummy/json/academics.json
- public/dummy/json/advising_student_academics.json
- public/dummy/json/enrollment_instructions.json
- spec/models/my_academics/class_enrollments_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/my_academics/registrations_spec.rb
- spec/support/spec_helper_module.rb
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/services/academicsService.js
https://jira.berkeley.edu/browse/SISRP-24520
> SISRP-24520 - Add Term based CPP data to User Profile

- src/assets/templates/widgets/sir/sir_item.html
https://jira.berkeley.edu/browse/SISRP-26013
simple fix, looks like previous code did not account for multiple acceptance options and was not checking for each specific option to render UI elements.
> SISRP-26013 - SIR option display broken in Calcentral

- app/models/my_academics/semesters.rb
- spec/models/my_academics/semesters_spec.rb
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-23155
> SISRP-23155 Empty semester card if user has only waitlisted courses

- app/models/berkeley/residency_message_code.rb
- spec/models/berkeley/residency_message_code_spec.rb
- spec/models/my_academics/residency_spec.rb
https://jira.berkeley.edu/browse/SISRP-25956
> SISRP-25956 - Residency exception from unknown message code

- src/assets/templates/widgets/profile/emergency_phone.html
- src/assets/templates/widgets/profile/emergency_phone_fields.html
https://jira.berkeley.edu/browse/SISRP-25636
> SISRP-25636 - Profile > Emergency Contact > "phone" needs better validation

- app/models/my_academics/class_enrollments.rb
- spec/models/my_academics/class_enrollments_spec.rb
https://jira.berkeley.edu/browse/SISRP-25837
> SISRP-25837 - Class Enrollment card - Allow FPF only for a single term

- src/assets/javascripts/angular/controllers/widgets/finaid/finaidCoaController.js
https://jira.berkeley.edu/browse/SISRP-24550
> SISRP-24550 - FinAid infinite spinner under "Estimated Cost of Attendance"

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-24519
> SISRP-24519 - 7.1 Advising Card Design Requests for Haas Graduate Programs

- app/models/my_academics/semesters.rb
- public/dummy/json/academics.json
- public/dummy/json/academics_interim_two_sets_conflicts.json
- public/dummy/json/academics_transition_future_profile.json
- public/dummy/json/academics_transition_past_profile_not_registered.json
- public/dummy/json/academics_transition_past_profile_registered.json
- spec/models/my_academics/semesters_spec.rb
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-26244
Includes some other SISRP-23155 follow-ups:
- Follow normal camelCasing convention.
- Add new My Academics property to dummy JSON files.
- Fix text formatting issue.
> SISRP-26244 Restore transcript-only Academics Semesters

- src/assets/stylesheets/_student_success.scss
- src/assets/templates/widgets/student_success/finances.html
- src/assets/templates/widgets/student_success/gpa_trends.html
- src/assets/templates/widgets/student_success/student_success.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-25805
* Surfaces Units & Finances onto Student Success
* I don't think the Design JIRA has been updated to the most recent design, seen here:
* Left out the "click-to-expand" feature, due to it being inconsistent with the GPA section.
* This should be my last PR for the day/7.1
> SISRP-25805 - Front-End Development for Student Overview (Advisor) - Student Success - Units & Finances Sections

- app/models/edo_oracle/course_sections.rb
- app/models/edo_oracle/queries.rb
- app/models/my_academics/exams.rb
- spec/models/edo_oracle/course_sections_spec.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/my_academics/exams_spec.rb
JIRA: https://jira.berkeley.edu/browse/SISRP-25993
Master PR: https://github.com/ets-berkeley-edu/calcentral/pull/5927
Incorporate classes that have an alternate method of final exams or no exam at all.
> SISRP-25993-QA - Final Exam Schedule Incorporate Course Exceptions

- app/models/my_academics/exams.rb
> [QA] SISRP-26305 - MyAcademics::Exams for UID 1064465: NoMethodError: undefined method gsub for nil:NilClass

- app/models/campus_solutions/student_resources.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/campus_solutions/student_resources_spec.rb
https://jira.berkeley.edu/browse/SISRP-25702
> SISRP-25702 - CS Link errors logged without UID

- app/models/campus_solutions/student_resources.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/campus_solutions/student_resources_spec.rb
Master PR - https://github.com/ets-berkeley-edu/calcentral/pull/5932
Jira https://jira.berkeley.edu/browse/SISRP-25702
*Should merge after master PR is merged*
> [QA] SISRP-25702 - CS Link errors logged without UID

- app/models/rosters/campus.rb
- spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-26282
See QA PR #5935
> SISRP-26282 - Class Page - Section Overview - No open position count when enrollments not present

- app/models/rosters/campus.rb
- spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-26282
See DEV PR #5934
> [QA] SISRP-26282 - Class Page - Section Overview - No open position count when enrollments not present

- src/assets/templates/academics.html
- src/assets/templates/academics_teaching.html
https://jira.berkeley.edu/browse/SISRP-26327
If you are faculty with no teaching assignments then you get no Teaching Card.
> SISRP-26327, only show Teaching Card when user has teaching assignments

- src/assets/templates/academics.html
- src/assets/templates/academics_teaching.html
https://jira.berkeley.edu/browse/SISRP-26327
Master PR is #5937
> [QA] SISRP-26327, hide Teaching Card when faculy has no teaching assignments

- app/models/edo_oracle/adapters/common.rb
- spec/models/edo_oracle/adapters/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6453
See 'master' PR #5938 for more info.
> [QA] CLC-6453, instructor role-code 'PROXY' assists instructor(s) with grading (e.g., Head GSI)

- spec/ui_selenium/my_academics_data_teaching_semesters_spec.rb
- spec/ui_selenium/my_finances_finaid_summary_spec.rb
- spec/ui_selenium/pages/my_academics_teaching_card.rb
https://jira.berkeley.edu/browse/SISRP-26445
> SISRP-26445 - FinAid and Teaching QA test fixes

- spec/models/calnet_ldap/client_spec.rb
- spec/models/calnet_ldap/user_attributes_spec.rb
Master PR is #5946 
The [Bamboo breakage we saw on master](https://bamboo.ets.berkeley.edu/bamboo/browse/MYB-CLCMVPMASTER-4601) is likely to impact QA branch, too.
> NOJIRA, CalNetLdap search returns berkeleyeduaffiliations as Enumerable

- spec/ui_selenium/my_academics_data_teaching_semesters_spec.rb
- spec/ui_selenium/pages/my_academics_page.rb
- spec/ui_selenium/pages/my_academics_teaching_card.rb
https://jira.berkeley.edu/browse/SISRP-26445
> SISRP-26445 - fix QA teaching semesters test

- script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-26586
* [I feel like such a newbie](http://stackoverflow.com/questions/7996919/should-url-be-case-sensitive)
* Ran locally, looks good.
> SISRP-26586 - verify_sis_api_endpoints.sh returning error for /UC_SF_STDNT_OS_BAL.v1/get?EMPLID=xxx

- script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-26586
QA PR of #5957
> [QA] SISRP-26586 - verify_sis_api_endpoints.sh returning error for /UC_SF_STDNT_OS_BAL.v1/get?EMPLID=xxx

- app/models/oec/report_diff_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6448
> CLC-6448 OEC: Include fresh new eval types in report diff task

- app/models/oec/report_diff_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6448
QA version of #5961.
> [QA] CLC-6448 OEC: Include fresh new eval types in report diff task

- app/models/campus_solutions/student_resources.rb
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5966
> [QA] SISRP-26598 - Student Dashboard Resources Card links are missing

- spec/ui_selenium/user_delegated_access_spec.rb
https://jira.berkeley.edu/browse/SISRP-26567
> SISRP-26567 - QA delegate test no longer expects final exams

- app/models/edo_oracle/oec.rb
- spec/models/edo_oracle/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6455
Separate ASTRON chocolate from AST peanut butter.
> CLC-6455 OEC: Add trailing space to department-name filters

- app/models/my_academics/filtered_for_delegate.rb
- src/assets/templates/academics.html
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-26567
* QA PR of #5968
> [QA] SISRP-26567 - MyAcademics::Exams for UID 1507981: NoMethodError: undefined method final_exam_cs_data_available for nil:NilClass

- src/assets/javascripts/angular/controllers/widgets/classInfoEnrollmentController.js
https://jira.berkeley.edu/browse/SISRP-26488
See QA PR #5976
> SISRP-26488 - Section Overview card - Sorting order of the columns needs to be fixed

- src/assets/javascripts/angular/controllers/widgets/classInfoEnrollmentController.js
https://jira.berkeley.edu/browse/SISRP-26488
DEV PR #5975
> [QA] SISRP-26488 - Section Overview card - Sorting order of the columns needs to be fixed

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_student_success.scss
- src/assets/templates/widgets/student_success/finances.html
- src/assets/templates/widgets/student_success/gpa_trends.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-26457
* Some friendly UI changes for unexpected values.
* Also in this PR:  nests the `isLoading = false` flag into a `.finally()` promise so we don't get infinitely spinning surprises.
> SISRP-26457 - Student Success Card need to show appropriate message instead of blank details

- app/models/my_academics/class_enrollments.rb
- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/class_enrollments_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
https://jira.berkeley.edu/browse/SISRP-26589
See QA PR #5971
> SISRP-26589 - Class Enrollment card duplicated within term for Haas plans

- app/models/my_academics/class_enrollments.rb
- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/class_enrollments_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
https://jira.berkeley.edu/browse/SISRP-26589
See DEV PR #5970
> [QA] SISRP-26589 - Class Enrollment card duplicated within term for Haas plans

- src/assets/templates/widgets/advisor/advising_links.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5963
> [QA] SISRP-26595 - Advisor Resources link hover text isn't always included in the markup

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_student_success.scss
- src/assets/templates/widgets/student_success/finances.html
- src/assets/templates/widgets/student_success/gpa_trends.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-26457
QA PR of #5955
> [QA] SISRP-26457 - Student Success Card need to show appropriate message instead of blank details

- src/assets/templates/widgets/student_success/finances.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-26637
> SISRP-26637 - Replace dashes with emdash for Student Success

- src/assets/templates/widgets/student_success/finances.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-26637
* QA PR of #5980 
* **Please check with Paul F before merge!** He is currently working on testing in QA and merging this will bring down cc-qa for about 10 minutes.
> [QA] SISRP-26637 - Replace dashes with emdash for Student Success

- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
https://jira.berkeley.edu/browse/SISRP-26605
> SISRP-26605 - CalCentral Enrollment Cards should have newest semester on top (Spring 2017 above Fall 2016)

- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5991
Jira https://jira.berkeley.edu/browse/SISRP-26605
> [QA] SISRP-26605 - CalCentral Enrollment Cards should have newest semester on top (Spring 2017 above Fall 2016)

- src/assets/templates/cars_summary.html
- src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-26478
> SISRP-26478 - 7.1 - Refactor My Finances > CARS Billing Summary given deprecation of CARS

- src/assets/templates/cars_summary.html
- src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-26478
QA PR of #5994
> [QA] SISRP-26478 - 7.1 - Refactor My Finances > CARS Billing Summary given deprecaction of CARS

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- spec/models/campus_solutions/advising_resources_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/toolbox/user_preview.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5982
Jira https://jira.berkeley.edu/browse/SISRP-26666
> [QA] SISRP-26666 - Advising Resources - should not include 'Schedule of Classes - Scheduler View' link

- script/export-cached-csv-enrollments-set.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6460
master PR is #5997
> [QA] CLC-6460, add -J-Xmx1024m to avoid OOM error in export-cached-csv-enrollments-set.sh

- app/models/campus_solutions/student_term_gpa.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/student_success/gpa_trends.html
https://jira.berkeley.edu/browse/SISRP-26676
QA PR of #6000
> [QA] SISRP-26676 - Student Success Card needs to suppress current term GPA

- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-26743
> SISRP-26743 - My Academics - Advising Card - MBA/Juris Doctor (MBA/JD) program should not display duplicate contact info on the advising card

- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-26743
See DEV PR #6003
> [QA] My Academics - Advising Card - MBA/Juris Doctor (MBA/JD) program should not display duplicate contact info on the advising card

- app/models/user/api.rb
- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-26772
master PR is #6005
> [QA] SISRP-26772, My Finances tab if student or has_student_history

- src/assets/javascripts/angular/controllers/pages/academicsController.js
https://jira.berkeley.edu/browse/SISRP-26775
> SISRP-26775 - Request Transcript link in CalCentral lands on telebears webpage

- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-26648
> SISRP-26648 - Delegates get infinite spinner in popover when viewing as student

- src/assets/javascripts/angular/controllers/pages/academicsController.js
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/6007
> [QA] SISRP-26775 - Request Transcript link in CalCentral lands on telebears webpage

- src/assets/templates/widgets/advisor/advising_links.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5998
> [QA] SISRP-26745 - Advising Resources - Advising Assignments link is missing

- src/assets/javascripts/angular/controllers/widgets/statusController.js
- src/assets/templates/widgets/gear_popover.html
Master PR https://github.com/ets-berkeley-edu/calcentral/pull/5985
> [QA] SISRP-26648 - Delegates get infinite spinner in popover when viewing as student

- src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
Essentially updates the academicsFactory for use on the Student Overview page for Advisors so that the filtered feed can be re-used by the Advising card.
https://jira.berkeley.edu/browse/SISRP-26742
> SISRP-26742 - Student Overview page Advising Card (Refactor and Haas Program Messages) are showing incorrect messages

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/support/spec_helper_module.rb
https://jira.berkeley.edu/browse/SISRP-26257
> SISRP-26257 - Filter out inactive studentPlans and remove Academic Statuses when no plans are present

- src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
https://jira.berkeley.edu/browse/SISRP-26742
See DEV PR #6001
> [QA] SISRP-26742 - Student Overview page Advising Card (Refactor and Haas Program Messages) are showing incorrect messages

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/support/spec_helper_module.rb
https://jira.berkeley.edu/browse/SISRP-26257
See DEV PR #6012
> [QA] SISRP-26257 - Filter out inactive studentPlans and remove Academic Status when no plans are present

- app/controllers/campus_solutions/degree_progress_controller.rb
- app/models/berkeley/grad_milestones.rb
- app/models/campus_solutions/degree_progress.rb
- app/models/campus_solutions/degree_progress_feature_flagged.rb
- app/models/my_academics/degree_progress.rb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- fixtures/xml/campus_solutions/degree_progress.xml
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/controllers/campus_solutions/degree_progress_controller_spec.rb
- spec/models/berkeley/grad_milestones_spec.rb
- spec/models/campus_solutions/degree_progress_spec.rb
- spec/models/my_academics/degree_progress_spec.rb
- spec/support/campus_solutions_helper_module.rb
- src/assets/javascripts/angular/controllers/widgets/academics/degreeProgressController.js
- src/assets/javascripts/angular/factories/academics/degreeProgressFactory.js
- src/assets/stylesheets/_degree_progress.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/academics.html
- src/assets/templates/widgets/academics/degree_progress.html
https://jira.berkeley.edu/browse/SISRP-25708
Some of this will get refactored when the UGRD version of the card is implemented.  Just wanted to get this merged so I can start on the [Progress Report card](https://jira.berkeley.edu/browse/SISRP-22302), which will share the same code.
Degree Progress has been pulled from the 7.2 release so I added a feature flag.
> SISRP-25708 - Adds My Academics > Degree Progress card for GRAD

- app/models/campus_solutions/advising_resources.rb
- app/models/campus_solutions/link.rb
master pr https://github.com/ets-berkeley-edu/calcentral/pull/6017
jira https://jira.berkeley.edu/browse/SISRP-26794
> [QA] SISRP-26794 - Student Overview(Advisor) - Advising Resources card - Service Indicators link - doesn't prepopulate the fields in the CS page

- app/models/campus_solutions/advising_resources.rb
- app/models/campus_solutions/link.rb
https://jira.berkeley.edu/browse/SISRP-26794
> SISRP-26794 - Student Overview(Advisor) - Advising Resources card - Service Indicators link - doesn't prepopulate the fields in the CS page

- script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-25708
The new endpoint was added in #5987
> SISRP-25708, add UC_AA_PROGRESS_GET to verify-sis-endpoints script

- script/downgrade.sh
- script/init.d/calcentral
- script/migrate.sh
- script/start-torquebox.sh
- script/stop-torquebox.sh
- script/update-build.sh
- script/update-source.sh
- script/upgrade.sh
https://jira.berkeley.edu/browse/SISRP-25488
https://jira.berkeley.edu/browse/SISRP-26646
https://jira.berkeley.edu/browse/SISRP-26873
Read [comment in SISRP-25488](https://jira.berkeley.edu/browse/SISRP-25488?focusedCommentId=410667&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-410667) for more info.
This PR has a lot of clean up in shell script syntax. The work related to JVM args is all in `start-torquebox.sh`.
> SISRP-25488, Torquebox JVM args to avoid Concurrent Mode Failure and prod outages

- app/models/my_academics/exams.rb
- app/models/my_academics/final_exams_feature_flagged.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- spec/models/my_academics/exams_spec.rb
https://jira.berkeley.edu/browse/SISRP-26963
* do nothing when `FinalExamsFeatureFlagged` is false
* add proper nil checks
* update all YAMLs
* move the `sort_by` out of `assign_exams()`
* code style and spec tidying
> SISRP-26964, avoid crash in MyAcademics::Exams; introduce FinalExamsFeatureFlagged 

- app/models/berkeley/residency_message_code.rb
- spec/models/berkeley/residency_message_code_spec.rb
- spec/models/my_academics/residency_spec.rb
https://jira.berkeley.edu/browse/SISRP-25956
> SISRP-25956 - Residency exception from unknown message code - return value fix

- app/models/mailgun/proxy.rb
- app/models/mailgun/send_message.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- fixtures/json/mailgun_send_message.json
- spec/models/mailgun/send_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6466
The simplicity of the Mailgun API makes this pretty darn straightforward.
> CLC-6466 Proxy, fixture, tests for Mailgun API

- app/models/campus_solutions/advising_resources.rb
- spec/controllers/campus_solutions/advising_resources_controller_spec.rb
- spec/models/campus_solutions/advising_resources_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/advisor/resources.html
https://jira.berkeley.edu/browse/SISRP-26827
> SISRP-26827 - 7.2 - Advising Resources Card for My Dashboard (Advisor) - Reorganize card

- src/assets/javascripts/angular/configuration/routeConfiguration.js
- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academic_summary.html
- src/assets/templates/academics_semesters.html
- src/assets/templates/academics_student_profile.html
https://jira.berkeley.edu/browse/SISRP-26828
Design JIRA:  https://jira.berkeley.edu/browse/SISRP-26096
* Unfortunately, I had to add even more complexity to the front-end of `academic_semesters.html`.  Definitely needs some clean-up in more peaceful times.
* There is a lot of transition term verbiage on the student profile card that I think is related to bug [SISRP-26943](https://jira.berkeley.edu/browse/SISRP-26943).  I left it in in this PR but I think they should be pulled out in this current sprint (on my to-do list).
> SISRP-26828 - 7.2 - Academic Summary on My Academics (Student)

- app/models/advising/my_advising.rb
- app/models/campus_solutions/student_resources.rb
- spec/models/advising/my_advising_spec.rb
https://jira.berkeley.edu/browse/SISRP-26566
> SISRP-22142 - AA/UX: Advising Card (Enhancement)

- app/models/mailing_lists/incoming_message.rb
- app/models/mailing_lists/outgoing_message.rb
- spec/models/mailing_lists/incoming_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6468
https://jira.ets.berkeley.edu/jira/browse/CLC-6469
> CLC-6468 CLC-6469 Handle permission checks and bounces in bCourses mailing lists

- app/models/campus_solutions/student_resources.rb
- spec/models/campus_solutions/student_resources_spec.rb
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-26739
> SISRP-26739 - 7.2: Student Resources: eForm Links - re-organize card

- app/models/my_academics/college_and_level.rb
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-27112
> SISRP-27112 - UX Dev: My Academics (student) - Advising - Reopening Appointment Links

- app/models/campus_solutions/advising_resources.rb
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-21359
> SISRP-21359 - 7.2 - Student Overview - Personal Summary card - Implement direct Schedule Planner link

- app/controllers/advising_student_controller.rb
- app/models/berkeley/degree_progress_graduate.rb
- app/models/berkeley/degree_progress_undergrad.rb
- app/models/campus_solutions/degree_progress/undergrad_requirements.rb
- app/models/campus_solutions/degree_progress_ugrd_advising_feature_flagged.rb
- app/models/degree_progress/milestones_module.rb
- app/models/degree_progress/requirements_module.rb
- app/models/degree_progress/undergrad_requirements.rb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- fixtures/xml/campus_solutions/degree_progress_undergrad.xml
- script/sis/verify_sis_api_endpoints.sh
- spec/controllers/advising_student_controller_spec.rb
- spec/models/berkeley/degree_progress_graduate_spec.rb
- spec/models/berkeley/degree_progress_undergrad_spec.rb
- spec/models/campus_solutions/degree_progress/undergrad_requirements_spec.rb
- spec/models/degree_progress/graduate_milestones_spec.rb
- spec/models/degree_progress/undergrad_requirements_spec.rb
- spec/support/campus_solutions_helper_module.rb
- spec/support/degree_progress_shared_examples.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academics/degreeProgressController.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/templates/academics.html
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academics/degree_progress_graduate.html
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-25756
~~Backend work for~~ Student Overview > Degree Progress.  This uses a completely different set of data than the Graduate Degree Progress card--grad students have "milestones" while undergrads have "requirements".
~~Will submit front-end code in a subsequent PR.~~ Amended to include front-end code.
> SISRP-25756 - Adds Undergrad Degree Progress card to Student Overview

- app/controllers/mailing_lists_message_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6467 continues to attempt landing.
> CLC-6467 Skip CSRF check on incoming mailing list messages

- app/models/campus_solutions/advising_resources.rb
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
1. Change to URL_ID in model from UC_CX_APR_RPT_S**DT**NT to UC_CX_APR_RPT_S**TD**NT
2. add `BackToText` in angular controller on each student resource link
> NOJIRA - URL_ID change in advisor resources - add BackToText in student resources links

- app/models/campus_solutions/link.rb
- spec/models/campus_solutions/link_spec.rb
https://jira.berkeley.edu/browse/SISRP-26982
> SISRP-26982 - Could not retrieve CS link UC_CX_GT_CPPSTACK_ADD for Student Resources feed

- src/assets/javascripts/angular/factories/canvasSiteMailingListFactory.js
Fix a goof in #6054.
https://jira.ets.berkeley.edu/jira/browse/CLC-6480
> CLC-6480 bCourses lists follow-up: fix misnamed param

- src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-27220
* Fixes broken link for "Access and Manage My Appointments"
* Fixes missing `ucFromText` issue with links
* Fixes broken spinner for Advising card
> SISRP-27220 - My Academics (Student) - Advising -"Access and Manage Appointments" link is not working

- app/controllers/canvas_course_grade_export_controller.rb
- app/models/canvas_lti/egrades.rb
- spec/models/canvas_lti/egrades_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6461
> CLC-6461 Update E-Grades CSV export for Campus Solutions compatibility

- config/initializers/rails_admin.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6464
The mailing lists membership table created in #6028 may as well be accessible through ccadmin.
> CLC-6464 Enable MailingList::Member in rails_admin

- app/models/my_academics/class_enrollments.rb
- spec/models/my_academics/class_enrollments_spec.rb
https://jira.berkeley.edu/browse/SISRP-26815
> SISRP-26815 - 7.2 - My Academics - Class Enrollment card - Filter duplicate career term plan roles for FPF Students

- fixtures/xml/campus_solutions/degree_progress_undergrad.xml
- spec/models/berkeley/degree_progress_undergrad_spec.rb
- spec/support/degree_progress_shared_examples.rb
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-25756
Just some minor updates and removal of academic plan from the card.
> SISRP-25756 - Mirrors changes to Degree Progress (UGRD) API

- app/models/degree_progress/milestones_module.rb
- spec/support/degree_progress_shared_examples.rb
- src/assets/templates/widgets/academics/degree_progress_graduate.html
Minor update to prettify the status date that appears on milestones that have been completed or partially completed.
> SISRP-25362 - Formats status dates on Degree Progress (GRAD)

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
https://jira.berkeley.edu/browse/SISRP-27379
> SISRP-27379 - add backToText to advisor resource and student resource links

- app/models/canvas/course_user.rb
- app/models/mailing_lists/site_mailing_list.rb
- spec/models/canvas/course_user_spec.rb
- spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6488
> CLC-6488 Allow TAs and readers to send to bCourses mailing lists

- app/models/canvas/course_user.rb
- app/models/mailing_lists/site_mailing_list.rb
- spec/models/canvas/course_user_spec.rb
- spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6488
QA version of #6085.
> [QA] CLC-6488 Allow TAs and readers to send to bCourses mailing lists

- app/models/my_committees/committees_module.rb
- app/models/my_committees/faculty_committees.rb
- app/models/my_committees/student_committees.rb
- spec/models/campus_solutions/faculty_committees_spec.rb
- spec/models/campus_solutions/student_committees_spec.rb
https://jira.berkeley.edu/browse/SISRP-26824
removed the testext and guarded against committees API returning arrays with empty elements.
> SISRP-26824 - My Academics (Grad students) - Committees Card

- spec/ui_selenium/my_academics_data_profile_spec.rb
- spec/ui_selenium/pages/my_academics_profile_card.rb
- spec/ui_selenium/pages/my_academics_semesters_card.rb
https://jira.berkeley.edu/browse/SISRP-27462
> SISRP-27462 - QA test fixes

- app/models/campus_solutions/advising_resources.rb
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-21359
Added missing "Student Transfer Credit Report" Link on Personal Summary Card . pulls from link API.
> SISRP-21359 - Student Overview - Personal Summary card

- app/models/campus_solutions/student_term_gpa.rb
- app/models/student_success/term_gpa.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/student_success/gpa_trends.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-26895
* Spoke with the API team, and had to change the API itself (breaking contract) to accept new values.
* Now we use the term-specific GPA (as opposed to running cumulative).
* Since a student can take all P/NP or Withdraw from all classes in a term, we don't want those terms affecting the GPA trendline - so we `nil` them out.
QA PR to come upon merge.
> SISRP-26895 - AA/UX: Student Success Card (Future Term)

- app/models/campus_solutions/student_term_gpa.rb
- app/models/student_success/term_gpa.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/student_success/gpa_trends.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-26895
QA PR of #6090
> [QA] SISRP-26895 - AA/UX: Student Success Card (Future Term)

- app/models/canvas_lti/webcast_lti_refresh.rb
- spec/models/canvas_lti/webcast_lti_refresh_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6494
Master PR #6093
> [QA] CLC-6494, Course Capture LTI script: when Canvas Tab API call fails, log error and return nil

- spec/ui_selenium/my_academics_data_final_exams_spec.rb
- spec/ui_selenium/pages/api_my_academics_page.rb
- spec/ui_selenium/pages/api_my_academics_page_semesters.rb
- spec/ui_selenium/pages/api_my_registrations_page.rb
- spec/ui_selenium/pages/my_academics_final_exams_card.rb
- spec/ui_selenium/pages/my_academics_semesters_card.rb
https://jira.berkeley.edu/browse/SISRP-26150
> SISRP-26150 - QA final exams test retrofitted to new UX

- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
https://jira.berkeley.edu/browse/SISRP-27417
> SISRP-27417 - WorkCenter Link working intermittently for Advisors

- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
https://jira.berkeley.edu/browse/SISRP-27417
See DEV PR #6097
> [QA] SISRP-27417 - WorkCenter Link working intermittently for Advisors

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/student_success/gpa_trends.html
https://jira.berkeley.edu/browse/SISRP-27546
> SISRP-27546 - Hide GPA Trendline if less than 2 data points for Student Success

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/widgets/student_success/gpa_trends.html
https://jira.berkeley.edu/browse/SISRP-27546
* QA PR of #6099
> [QA] SISRP-27546 - Hide GPA Trendline if less than 2 data points for Student Success

- app/models/mailing_lists/site_mailing_list.rb
- spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6495
This little devil has been sitting in the test suite for a year, just waiting to bite.
> CLC-6495 bCourses lists: fix flubbed 'email' key

- app/models/mailing_lists/site_mailing_list.rb
- spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6495
QA version of #6111.
> [QA] CLC-6495 bCourses lists: fix flubbed 'email' key

- spec/ui_selenium/my_finances_financials_cs_ui_spec.rb
- spec/ui_selenium/user_delegated_access_spec.rb
https://jira.berkeley.edu/browse/SISRP-27462
> SISRP-27462 - fix for QA transaction sorting tests

- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-26755
See DEV PR #6109
> [QA] SISRP-26755 - Schedule Planner link - Campus Solutions page header needs to be removed

- app/controllers/concerns/advisor_authorization.rb
- app/controllers/search_users_controller.rb
- app/models/berkeley/user_roles.rb
- app/models/user/aggregated_attributes.rb
- app/models/user/parser.rb
- spec/controllers/advising_student_controller_spec.rb
- spec/controllers/concerns/advisor_authorization_spec.rb
- spec/models/berkeley/user_roles_spec.rb
- spec/models/user/aggregated_attributes_spec.rb
- spec/models/user/search_users_by_name_spec.rb
QA version of: https://github.com/ets-berkeley-edu/calcentral/pull/6114
> [QA] SISRP-26578 Give Advisors access to ex-students' academic data

- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-27567
> SISRP-27567 - Handles case when academic plan is missing

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-27005
See [ngRepeat - Tracking and Duplicates](https://docs.angularjs.org/api/ng/directive/ngRepeat#tracking-and-duplicates) to understand more of why this is needed.
> SISRP-27005 - Instructor class enrollment page JS error: Duplicates in a repeater are not allowed

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-27005
See DEV PR #6113
> [QA] SISRP-27005 - Instructor class enrollment page JS error: Duplicates in a repeater are not allowed

- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-27580
* Just some `if` statements to hide zero/nil values.
* QA PR to come after merge.
> SISRP-27580 - Student Overview (Advisors) - Transfer Credit - Test Units section needs to be hidden when there are no test units

- app/models/berkeley/degree_progress_graduate.rb
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- spec/support/degree_progress_shared_examples.rb
This is the QA PR to follow #6107
> [QA] SISRP-25362 - Updates Degree Progress (GRAD) text translation

- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-27567
This is the QA PR to follow #6108
> [QA] SISRP-27567 - Handles case when academic plan is missing 

- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-27580
* QA PR of #6119
> [QA] SISRP-27580 - Student Overview (Advisors) - Transfer Credit - Test Units section needs to be hidden when there are no test units

- script/sync-canvas-new-users.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-6475
Master PR, with details: #6129
> [QA] CLC-6475, JVM - during sync-canvas-new-users script - gets large Max Heap Size

- app/models/my_academics/college_and_level.rb
https://jira.berkeley.edu/browse/SISRP-24743
> SISRP-24743 - Filtering empty academic career and level descriptions

- src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-21321
* `hide-for-medium-up` dynamic class due to the `hide-for-small` class on line 127.
* QA PR to come after merge.
> SISRP-21321 - Transaction Type is charge, that transaction should have Due date

- app/models/advising/my_advising.rb
- spec/models/advising/my_advising_spec.rb
https://jira.berkeley.edu/browse/SISRP-26566
> SISRP-26566 - Exclude unknown Advisor types for Graduate students

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- config/settings/testext.yml
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-27492
QA PR of #6124 
Remember to check-in with @pfarestveit before merging!
> [QA] SISRP-27492 - Advising Dashboard - Remove Academic Progress Link and What If Report Link

- src/assets/templates/widgets/billing_activity.html
https://jira.berkeley.edu/browse/SISRP-21321
QA PR of #6130 
Remember to check w/ @pfarestveit before merge!
> [QA] SISRP-21321 - Transaction Type is charge, that transaction should have Due date

- app/models/my_committees/committees_module.rb
- app/models/my_committees/faculty_committees.rb
- app/models/my_committees/student_committees.rb
- spec/models/campus_solutions/faculty_committees_spec.rb
- spec/models/campus_solutions/student_committees_spec.rb
> [QA] SISRP-26824 - My Academics (Grad students) - Committees Card

- app/models/advising/my_advising.rb
- spec/models/advising/my_advising_spec.rb
https://jira.berkeley.edu/browse/SISRP-26566
See DEV PR #6127
> [QA] SISRP-26566 - Exclude unknown Advisor types for Graduate students

- app/models/my_academics/grading.rb
- public/dummy/json/academics.json
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-27647
small changes to teaching card and added specific assistance link for Law on harder. Future releases will include logic to identify the department of classes and only show Law link if it applies.
> SISRP-23851 - Grading - two links for "Assistance with Grading" (General and Law)

- app/models/my_committees/committees_module.rb
- app/models/my_committees/student_committees.rb
- public/dummy/json/committees.json
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/academics.html
- src/assets/templates/widgets/higher_degree_committees.html
* added new link for student committees pulled from link API
* fix typo in feature flag.
> SISRP-17569 - My Academics (Grad students) - Committees Card

- app/models/my_academics/grading.rb
- public/dummy/json/academics.json
- src/assets/templates/academics_semester_classes.html
> [QA] SISRP-23851 - My Academics [course name] - Faculty Grading

- app/models/my_committees/committees_module.rb
- app/models/my_committees/student_committees.rb
- public/dummy/json/committees.json
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/academics.html
- src/assets/templates/widgets/higher_degree_committees.html
> [QA] SISRP-17569 - My Academics (Grad students) - Committees Card 

- spec/ui_selenium/my_finances_financials_cs_data_spec.rb
https://jira.berkeley.edu/browse/SISRP-21321
QA regression test for CS financials now expects due date for paid charges.
> SISRP-21321 - fix expectation in QA financials test

- app/models/my_academics/college_and_level.rb
https://jira.berkeley.edu/browse/SISRP-24743
See DEV PR #6126
> [QA] SISRP-24743 - Filtering empty academic career and level descriptions

- src/assets/templates/widgets/toolbox/user_preview.html
> [QA] SISRP-21359 - Student Overview - Personal Summary card

- config/settings.yml
- spec/ui_selenium/my_profile_contact_info_spec.rb
- spec/ui_selenium/my_profile_work_experience_spec.rb
- spec/ui_selenium/pages/my_profile_contact_info_card.rb
- spec/ui_selenium/pages/my_profile_work_experience_card.rb
- spec/ui_selenium/util/web_driver_utils.rb
https://jira.berkeley.edu/browse/SISRP-27462
Fix Contact Info and Work Experience tests by:
- using JavaScript to click buttons
- avoiding selects
> SISRP-27462 - fix QA contact info and work experience tests

- app/models/my_academics/class_enrollments.rb
- spec/models/hub_edos/academic_status_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
https://jira.berkeley.edu/browse/SISRP-26894
> SISRP-26894 - 7.3: CalCentral-prod FATAL error: NoMethodError grouped_student_plan_roles

- spec/controllers/my_committees_controller_spec.rb
> SISRP-27723 - Committees card showing inactive members for both Faculty as well as Grad Students

- src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-27258
> SISRP-27258 - 7.3 Class Enrollment Card - Add Class Schedule Link

- script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-27784
Fixes my mistake - it was checking the Degree Progress UGRD feature flag but pointing at the wrong URL.
> SISRP-27784 - Updates endpoint validation script to check Degree Progress UGRD

- app/models/my_academics/grading.rb
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-27604
* added link directive to front end 
* added INSTITUTION parameter to grading link
> SISRP-27604 - Course Grades Link from calcentral not sending faculty into grade roster

- public/maintenance/index_emergency.html
- public/maintenance/index_maintenance.html
https://jira.berkeley.edu/browse/SISRP-26889
Easy time-filler before my next meeting...
> SISRP-26889 More links down the memory hole

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/javascripts/angular/services/linkService.js
https://jira.berkeley.edu/browse/SISRP-28013
> SISRP-28013 - 7.3: Refactor front-end to support backToText for new CS Link API

- app/models/degree_progress/graduate_milestones.rb
- app/models/degree_progress/undergrad_requirements.rb
https://jira.berkeley.edu/browse/SISRP-27912
> SISRP-27912 Do not throw exceptions from Degree Progress if no CS ID

- app/models/my_committees/committees_module.rb
- app/models/my_committees/student_committees.rb
- public/dummy/json/committees.json
- spec/models/my_committees/student_committees_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/widgets/academics/higher_degree_committee.html
- src/assets/templates/widgets/higher_degree_committees.html
- src/assets/templates/widgets/higher_degree_faculty_committees.html
https://jira.berkeley.edu/browse/SISRP-28019
* added new committee member roles to the backend and new sections to frontend for inside and outside members. 
* used CS link directive for committees link 
* small text changes on UI
* removed filter for student committees to allow for active and completed committees to be rendered.
> SISRP-28019 - Committees card need to show Insider/outsider details for committee members

- src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js
- src/assets/javascripts/angular/controllers/widgets/tasksController.js
- src/assets/templates/dashboard_task_loop.html
- src/assets/templates/widgets/activity_archive.html
- src/assets/templates/widgets/activity_list_link.html
- src/assets/templates/widgets/finaid_communications_tasks.html
https://jira.berkeley.edu/browse/SISRP-27781
> SISRP-27781 - CalCentral header links and navigation links during doc upload is not working 

- src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-27258
> SISRP-27258 - Remove 'Berkeley Academic Guide' link from Concurrent Enrollment design

- app/models/my_academics/grading.rb
- spec/models/my_academics/grading_spec.rb
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-27680
* removed grading functionality from teaching section
* added new "Grading" section below "Teaching" section on semester classes card
* added Law grading period to teaching card header
* added logic to apply class role (law/ not law) to determining grading status/link
* remapped "APPR" CS status to display same as "POST"
> SISRP-27680 - My Academics (instr) - Semesters [Teaching] (Final Grading Updates)

- src/assets/stylesheets/_profile_page.scss
- src/assets/templates/widgets/profile/basic.html
- src/assets/templates/widgets/profile/basic_confidential.html
- src/assets/templates/widgets/profile/basic_name.html
- src/assets/templates/widgets/profile/basic_nonstudent.html
- src/assets/templates/widgets/profile/basic_preferred_name.html
- src/assets/templates/widgets/profile/basic_student_id.html
- src/assets/templates/widgets/profile/basic_user_id.html
https://jira.berkeley.edu/browse/SISRP-28121
Resized Basic Profile labels to avoid wrapping.
> SISRP-28121 Show Confidential students their status in Profile

- app/controllers/campus_solutions/cs_official_transcript_controller.rb
- app/models/campus_solutions/cs_official_transcript.rb
- app/models/campus_solutions/my_cs_official_transcript.rb
- config/routes.rb
- public/dummy/json/cs_official_transcript.json
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
- src/assets/javascripts/angular/factories/academics/academicRecordsFactory.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics.html
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-27006
https://jira.berkeley.edu/browse/SISRP-27007
* Also decided to put the front-end work in this PR as well, as it wouldn't have made much sense without it.
* The POST request is being built in the front-end controller.  This is a necessity with the way the Credentials Solutions server accepts connections.
* See attached document at the [Confluence page](https://confluence.ets.berkeley.edu/confluence/display/MYB/Academic+Records) for more info about the POST.
* More than happy to review this in person if anyone wants!
* Next up, add the rest of the links on Academic Records.
> SISRP-27006 - Compile POST Request and send to Credential Solutions for Official Transcript

- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-28049
* simply removed additional credit section on bottom of semesters card.
> SISRP-28049 -  Semesters Card - Remove Additional Course Credit

- app/models/berkeley/term_codes.rb
- app/models/my_academics/class_enrollments.rb
- spec/controllers/my_class_enrollments_controller_spec.rb
- spec/models/berkeley/term_codes_spec.rb
- spec/models/my_academics/class_enrollments_spec.rb
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/factories/enrollmentFactory.js
- src/assets/stylesheets/_enrollment_card.scss
- src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-27700
> SISRP-27700 - 7.3: Class Enrollment Card - Term/Career Transitions

- src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-28181
* added order by lastname then firstname in ng-repeat on roster page
> SISRP-28181 -  On Enrollment card, student names are not sorting correctly

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-27681
* added new grading tab to class info page with links back to semesters page with grading
> SISRP-27681 - My Academics (instr) - Course Page - Instructors Card/Grading Tab (Final Grading Updates)

- src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-26741
Design JIRA:  https://jira.berkeley.edu/browse/SISRP-21544
> SISRP-26741 - 7.3: Academic Records on My Academics (Student)

- app/models/my_academics/merged.rb
- spec/models/my_academics/merged_spec.rb
- src/assets/templates/academics.html
- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-27669
Design JIRA: https://jira.berkeley.edu/browse/SISRP-27670
* Didn't realize until this pull how much I LOVE MERGED MODELS
* Also included a fix for a missing quote that was causing a parsing error (`college_and_level.html`), it's super minor so I figured it wouldn't hurt to just include it and bypass the JIRA process.
> SISRP-27669 - 7.3: Transfer Credit - My Academics (student)

- src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
- src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-28184
> SISRP-28184 - UX Dev: Re-Releasing Appointments links

- app/models/my_academics/college_and_level.rb
- fixtures/json/hub_academic_status.json
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/templates/academics_student_profile.html
- src/assets/templates/widgets/academics/degrees_conferred.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-27695
If a student has completed degrees, display them on the profile card.  
Still missing some of the data points (academic program) so I may be submitting a follow-up PR.
> SISRP-27695 - Adds conferred (awarded) degree(s) to Profile card

- script/sis/verify_sis_api_endpoints.sh
https://jira.berkeley.edu/browse/SISRP-24177
Prevents unwelcome distraction when we're between academic terms.
> SISRP-24177 Fix Hub Terms API verification between terms

- spec/ui_selenium/pages/my_finances_billing_page.rb
- src/assets/javascripts/angular/controllers/pages/billingDetailsController.js
- src/assets/javascripts/angular/controllers/widgets/billingController.js
- src/assets/javascripts/angular/controllers/widgets/carsController.js
- src/assets/templates/billing_details.html
- src/assets/templates/cars_summary.html
- src/assets/templates/myfinances.html
- src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-27684
> SISRP-27684 - 7.3: My Finances - Billing Summary - Phase 2

- app/models/oec/report_diff_task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6515
See JIRA description.
cc: @paulkerschen
> CLC-6515, OEC Report Diff task should log level WARN when row is blank

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- spec/controllers/campus_solutions/advising_resources_controller_spec.rb
- spec/models/campus_solutions/advising_resources_spec.rb
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-28120
> SISRP-28120 - Advising Resources/Personal Summary Revise Imagine CalCentral URL for Experience

- app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-28261
> SISRP-28261 - 7.3 - Advising Dashboard - Re-enable 'My Appointments' link

- src/assets/javascripts/angular/controllers/widgets/billingController.js
https://jira.berkeley.edu/browse/SISRP-23756
> SISRP-23756 - Financials - waivers appearing with item type W

- spec/models/user/aggregated_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-28052
This doesn't fix the problem, but it should at least keep someone else from making the same mistake I did.
> SISRP-28052 Add tests for first & last name in merged user attributes

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-28312
* hide residency for hass plans: MFE, EMBA, EWMBA
> SISRP-28312 - Residency should be hidden from select Haas students

- app/models/my_academics/exams.rb
- spec/models/my_academics/exams_spec.rb
https://jira.berkeley.edu/browse/SISRP-27725
> SISRP-27725 Fix Final Exams data for instructors

- src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
https://jira.berkeley.edu/browse/SISRP-28254
* As noted in JIRA comments, I'm unable to actually test this since I don't have access to BCSQAT.  I do feel comfortable opening a PR however, as the returned URL has a similar structure to other student-specific URLs we are surfacing.
* If anyone feels I should wait until next week to locally test with QA (if they have credentials) and cherry-pick to QA branch next week, let me know and I'll go ahead & close this PR.
> SISRP-28254 - Academic Records card - 'Request Law Unofficial Transcript' link throws invalid URL error

- app/controllers/act_as_controller.rb
- app/controllers/delegate_act_as_controller.rb
- app/policies/authentication_state.rb
- spec/controllers/delegate_act_as_controller_spec.rb
- spec/models/user/api_spec.rb
- spec/support/shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-28316
If this tests out on Master, I'll open a QA PR to match.
> SISRP-28316 Fix Delegate authorization

- src/assets/javascripts/angular/controllers/pages/academicsController.js
> [QA] SISRP-28337 - My Academics Page JavaScript error "Cannot read property 'haasMastersFinEng' of undefined"

- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-28341
> SISRP-28341 - Transfer Credit Link missing from Advising Resources

- app/controllers/act_as_controller.rb
- app/controllers/delegate_act_as_controller.rb
- app/policies/authentication_state.rb
- spec/controllers/delegate_act_as_controller_spec.rb
- spec/models/user/api_spec.rb
- spec/support/shared_examples.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/6204
> [QA] SISRP-28316 Fix Delegate authorization

- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-28341
See DEV PR #6206
> [QA] SISRP-28341 - Transfer Credit Link missing from Advising Resources

- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-28424
* Changes made to API as well.
> SISRP-28424 - Rounding Issue in Transfer Credit Card

- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-28424
* QA PR of #6213
> [QA] SISRP-28424 - Rounding Issue in Transfer Credit Card

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6520
master PR #6217 was merged and https://ucberkeley.beta.instructure.com/ (pointed at cc-sis-qa) now has the 'Create a Site' button.
> CLC-6520, 'Create a Site' button after Canvas dashboard_sidebar renders

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6520
master PR #6221 
cc: @paulkerschen
> [QA] CLC-6520, select #right-side child w/o class for prepend 'Create a Site'

- src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-28467
> SISRP-28467 - My Academics - Academic Records - Hover over text is incorrect

- app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-28458
> SISRP-28458 - Advising Dashboard - Advising Resources - Incorrect hover text for 'Transfer Credit Reports' link

- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/base.rb
- config/settings.yml
https://jira.berkeley.edu/browse/SISRP-28284
Also increases cache lifespan of detailed section info.
> SISRP-28284 Reduce performance impact of EDO DB crosslistings

- app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-28458
See DEV PR #6220
> [QA] SISRP-28458 - Advising Dashboard - Advising Resources - Incorrect hover text for 'Transfer Credit Reports' link

- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-28496
QA PR to come.
> SISRP-28496 - Academic Records - Text Change

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-28431
* spelling fix
> SISRP-28431 - Misspelling in grade roster

- src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-28467
See DEV PR #6219
> [QA] SISRP-28467 - My Academics - Academic Records - Hover over text is in correct

- app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-28460
> SISRP-28460 - Student Overview - Personal Summary card - Remove 'View Student's Appointments' Link

- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-28496
QA PR of #6226
> [QA] SISRP-28496 - Academic Records - Text Change

- app/models/campus_solutions/advising_resources.rb
https://jira.berkeley.edu/browse/SISRP-28460
See DEV PR #6228
> [QA] SISRP-28460 - Student Overview - Personal Summary card - Remove 'View Student's Appointments' link

- src/assets/templates/academics_classinfo.html
> [QA] SISRP-28431 - Misspelling in grade roster

- app/models/campus_solutions/advising_academic_plan.rb
- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/advising_academic_plan.xml
- public/dummy/json/advising_student_academics.json
- script/sis/verify_sis_api_endpoints.sh
- src/assets/templates/academics_plan.html
> [QA] SISRP-28446 -  Academic Plan - point to correct API and adjust for variations in payload

- app/models/campus_solutions/advising_resources.rb
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-28441
QA PR of #6234
> [QA] SISRP-28441 - Advising dashboard - advising resources card missing links

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-28498
* Added some functionality necessary to the Status and Holds card added in #6157 to the User Overview Controller.
> SISRP-28498 - Student Overview (Advisor) - Status and Holds card - Not displaying the correct status

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-28498
* QA PR of #6237
> [QA] SISRP-28498 - Student Overview (Advisor) - Status and Holds card - Not displaying the correct status

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-28450
See QA PR #6241
> SISRP-28450 - Course grade hover over text is not showing

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-28450
See DEV PR #6240
> [QA] SISRP-28450 - Course grade hover over text is not showing

- app/models/campus_solutions/faculty_delegate.rb
- app/models/my_academics/faculty_delegate.rb
- app/models/my_academics/grading.rb
- spec/models/my_academics/faculty_delegate_spec.rb
This reverts commit SISRP-28333 - MyAcademics feed taking over 90 sec to load for faculty user in CC-QA #6239
> Revert SISRP-28333 - MyAcademics feed taking over 90 sec to load for faculty user in CC-QA

- src/assets/templates/academics_semester_classes.html
> [QA] SISRP-28454 - CalCentral showing incorrect grade roster status in Faculty Grading - Confusing to users

- app/models/my_academics/academic_plan.rb
- app/models/my_academics/advising_academic_planner_feature_flagged.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-28532
* Last minute feature flag for Advising Academic Planner
> SISRP-28532 - Create Feature Flag for Advising Academic Plan

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
https://jira.berkeley.edu/browse/SISRP-28181
> SISRP-28181 - On Enrollment card, student names are not sorting correctly

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
https://jira.berkeley.edu/browse/SISRP-28181
See DEV PR #6246
> [QA] SISRP-28181 - On Enrollment card, student names are not sorting correctly

- app/models/my_academics/academic_plan.rb
- app/models/my_academics/advising_academic_planner_feature_flagged.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-28532
QA PR of #6244
> [QA] SISRP-28532 - Create Feature Flag for Advising Academic Plan

- src/assets/templates/academics_classinfo.html
* fix "Goto" to "Go to" for PR #6249
> SISRP-28502 - Grading: UAT Feedback on Nov 30 - fix

- app/models/my_academics/grading.rb
- spec/models/my_academics/grading_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_classinfo.html
- src/assets/templates/academics_semester_classes.html
> [QA] SISRP-28502 - Grading: UAT Feedback on Nov 30

- config/settings/testext.yml
https://jira.berkeley.edu/browse/SISRP-28555
* D'oh!
> SISRP-28555 - testext.yml Feature Flag for Advising Academic Planner

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-28450
See QA PR #6256
> SISRP-28450 - Fixing hover-over text on Class page Grading tab

- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-28622
* added back semesters and enrollments card on student overview
* added feature flag to hide them is advising academic plan card is feature flagged back on.
> SISRP-28622 - Missing Semesters and Enrollments card for advisor student overview

- src/assets/templates/user_overview.html
> [QA] SISRP-28622 - Missing Semesters and Enrollments card for advisor student overview

- src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-28705
> SISRP-28705 - Schedule Planner 404 error from Enrollment card

- app/models/calnet_ldap/client.rb
- spec/models/calnet_ldap/client_spec.rb
- spec/models/user/search_users_by_name_spec.rb
https://jira.berkeley.edu/browse/SISRP-28562
> SISRP-28562 Do not let salutations block LDAP name searches

- src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-28705
See DEV PR #6264
> [QA] SISRP-28705 - Schedule Planner 404 error from Enrollment card

- app/models/campus_solutions/section_grades_expiry.rb
- app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-28699
* Full disclosure, I could not fully test this locally as I can't receive JMS messages from the Hub.  I did verify that cc-sis-dev were receiving expected messages from CS triggers.
* Once this is in, if it passes testing + regression testing, will open a QA PR for emergency release.
> SISRP-28699 - 7.4: ENF for Grade Roster Status and Academic Plan Card

- package.json
https://jira.berkeley.edu/browse/SISRP-28750
See DEV PR #6272
> [QA] SISRP-28750 - Downgrade AngularJS to 1.5.8

- app/models/canvas_csv/provide_course_site.rb
- spec/models/canvas_csv/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6521
> CLC-6521 Restore existing Canvas sites to course provision feed

- app/controllers/campus_solutions/college_scheduler_controller.rb
- app/models/campus_solutions/college_scheduler_url.rb
- app/models/my_academics/college_and_level.rb
- config/routes.rb
- spec/controllers/campus_solutions/college_scheduler_controller_spec.rb
- spec/models/campus_solutions/college_scheduler_url_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/widgets/enrollment/schedule.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-27468
> SISRP-27468 - Student Overview - Personal Summary card - Update 'Schedule Planer' link

- app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-28754
**Please do not merge until Master branch issues have been resolved.**
> SISRP-28754 - Add conditional to logger.error for Grading Roster Status ENF

- app/models/my_academics/grading.rb
https://jira.berkeley.edu/browse/SISRP-28816
* changed grading status mapping for approved grades from 'APPR' to 'RDY'.
> SISRP-28816 - Grading Status mapping for Approved grades not correct

- app/models/edo_oracle/course_sections.rb
- spec/models/edo_oracle/course_sections_spec.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
This kept confusing me a couple of weeks back, so I finally lost my temper and fixed it.
> NOJIRA Clarify variable names for section IDs

- app/models/campus_solutions/section_grades_expiry.rb
- app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-28699
https://jira.berkeley.edu/browse/SISRP-28754
* QA PR of #6269 and #6271.
* Part of Wednesday's emergency release.
* Tested with Nader and Marc - looked good.  Goes in-hand with #6275 (no merge dependencies).
> [QA] SISRP-28699,SISRP-28754 - Grading Roster Status ENF

- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-28644
*QA PR to come for emergency release.
> SISRP-28644 - UX Design 7.4 CNP Wording Updates

- app/models/my_academics/grading.rb
> [QA] SISRP-28816 - Grading Status mapping for Approved grades not correct

- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-28644
* QA PR of #6277
> [QA] SISRP-28644 - UX Design 7.4 CNP Wording Updates

- app/models/my_academics/semesters.rb
> [QA] SISRP-28730 - Fall 2016 Grades need to be pulled from CS into Calcentral

- app/models/campus_solutions/college_scheduler_url.rb
https://jira.berkeley.edu/browse/SISRP-28705
See DEV PR #6283
> [QA] SISRP-28705 - Adds ADVISORID to all college scheduler API requests

- app/models/campus_solutions/college_scheduler_url.rb
- spec/models/campus_solutions/college_scheduler_url_spec.rb
https://jira.berkeley.edu/browse/SISRP-28705
See QA PR #6284. NOTE: The QA PR is much different due to changes not being present from #6270 in the QA branch
> SISRP-28705 - Adds ADVISORID to all college scheduler API requests

- spec/models/campus_solutions/college_scheduler_url_spec.rb
https://jira.berkeley.edu/browse/SISRP-27468
@raydavis - This resolves the [Bamboo test failure](https://jira.berkeley.edu/browse/SISRP-27468#comment-430265) you pointed out. You should be able to un-quarantine the failure with this update.
> SISRP-27468 - Updates test to reflect current environment configuration for basic auth

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-28795
> SISRP-28795 - Text needs to be updated to say 'Enter Grades' instead of 'Course Grades'

- src/assets/templates/widgets/student_success/gpa_trends.html
https://jira.berkeley.edu/browse/SISRP-28903
* API has been changed to include 3 decimal points.
> SISRP-28903 - Cal Central Student Success card - display GPA to 3 decimals

- app/models/financials/proxy.rb
- config/settings.yml
https://jira.berkeley.edu/browse/SISRP-24158
All deployment environments will eventually require configuration changes to reach the new data source.
> SISRP-24158 Switch legacy billing (aka CFV) to new endpoint

- src/assets/templates/widgets/academics/higher_degree_committee_member.html
https://jira.berkeley.edu/browse/SISRP-28310
* removed depart label on committee members.
> SISRP-28310 - Faculty Committees - remove department label from committee members view

- src/assets/templates/widgets/academics/higher_degree_committee.html
- src/assets/templates/widgets/academics/higher_degree_committee_member.html
https://jira.berkeley.edu/browse/SISRP-29039
* move academic senate up on the committee members order.
> SISRP-29039 - Change order of committee members

- app/models/berkeley/user_roles.rb
- spec/models/calnet_ldap/user_attributes_spec.rb
https://jira.berkeley.edu/browse/SISRP-28339
> SISRP-28339 ALUMNUS CalNet affiliation implies ex-student role

- app/models/berkeley/term_codes.rb
- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/academics_module.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/edo_oracle/user_courses/base_spec.rb
- spec/models/my_academics/semesters_spec.rb
- spec/models/my_academics/teaching_spec.rb
- src/assets/templates/academics_classinfo.html
- src/assets/templates/academics_semesters.html
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-27752
> SISRP-27752 - My Academics/Student Overview - Display Summer Sessions

- src/assets/templates/academics_higher_degree_committees.html
- src/assets/templates/academics_higher_degree_faculty_committees.html
- src/assets/templates/widgets/higher_degree_committees.html
- src/assets/templates/widgets/higher_degree_faculty_committees.html
https://jira.berkeley.edu/browse/SISRP-29068
* add pinwheel for committees cards.
> SISRP-29068 - Faculty member 3030724334 is not seeing Committees Cards My academics loads

- app/models/edo_oracle/queries.rb
- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-29104
QA PR of #6304
> [QA] SISRP-29104 - CalCentral - Class Information page missing lecture date, time and location for Sp17 UGBA 118 (INC0367091 & INC0376337)

- app/controllers/advising_student_controller.rb
- app/controllers/bootstrap_controller.rb
- app/models/my_academics/academic_plan.rb
- app/models/my_academics/filtered_for_advisor.rb
- config/routes.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/templates/widgets/academic_plan.html
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-28787
QA PR of #6306
> [QA] SISRP-28787 - Add Cache Expiration for Outgoing/Incoming Academic Plan Link

- src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-29098
* Opens up status popover to advising view-as.
> SISRP-29098 - Registration and CNP warnings are not displayed in the popover

- src/assets/templates/widgets/gear_popover.html
https://jira.berkeley.edu/browse/SISRP-29098
QA PR of #6308
> [QA] SISRP-29098 - Registration and CNP warnings are not displayed in the popover

- src/assets/stylesheets/_foundation_overrides.scss
- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-29226
* Fix 2-column layout for Student Overview page.
* Resolve missing margin on column-2 when at 1025px width in Safari
> SISRP-29226 - CalCentral Student Overview - missing 2 card columns for tablet size

- src/assets/javascripts/angular/directives/finaidSummaryItemDirective.js
- src/assets/stylesheets/_finaid_summary.scss
- src/assets/templates/directives/finaid_summary_item.html
- src/assets/templates/widgets/finaid_summary.html
- src/assets/templates/widgets/finaid_summary_fundingoffered.html
https://jira.berkeley.edu/browse/SISRP-27698
Just some minor changes to the style, layout, and text on the Financial Aid and Scholarships card.  The text under "Funding Offered" is still awaiting API changes but shouldn't require more code changes on our side.
> SISRP-27698 - Implements FinAid card visual enhancements

- src/assets/javascripts/angular/directives/finaidSummaryItemDirective.js
- src/assets/stylesheets/_finaid_summary.scss
- src/assets/templates/directives/finaid_summary_item.html
- src/assets/templates/widgets/finaid_summary.html
- src/assets/templates/widgets/finaid_summary_fundingoffered.html
https://jira.berkeley.edu/browse/SISRP-27698
QA PR for #6311 (sorry for my tardiness. I'm working with the testing team to make sure they can get this tested after it's merged)
> [QA] SISRP-27698 - Implements FinAid card visual enhancements

- src/assets/stylesheets/_finaid_summary.scss
- src/assets/templates/widgets/finaid_summary_netcost.html
https://jira.berkeley.edu/browse/SISRP-27698
QA PR for #6313
> [QA] SISRP-27698 - re-styles <hr> to make it visible

- src/assets/templates/widgets/profile/delegate.html
https://jira.berkeley.edu/browse/SISRP-29308
> SISRP-29308 - Delegate access looses Return to Calcentral header

- app/models/mailing_lists/site_mailing_list.rb
- spec/models/mailing_lists/calmail_list_spec.rb
- spec/support/mailing_list_shared_examples.rb
- src/assets/templates/canvas_embedded/site_mailing_list.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6539
> CLC-6539 bCourses mailing lists: clearer messaging on name conflict

- app/models/berkeley/term.rb
- fixtures/json/terms_next_2016-12-16.json
- spec/models/berkeley/term_spec.rb
https://jira.berkeley.edu/browse/SISRP-29466
Avoid exact repeats of Tuesday's outage.
> SISRP-29466 Handle Hub Term API feeds with missing session timePeriods

- app/models/campus_solutions/advising_resources.rb
- config/settings.yml
- config/settings/test.yml
- public/dummy/json/enrollment_instructions.json
- src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-29535
* Removes deprecated static link configuration from Class Enrollment card
* Updates fixture with data matching current Class Enrollment feed format
* Removes deprecated link configuration missed in #6270 ([SISRP-27468](https://jira.berkeley.edu/browse/SISRP-27468))
> SISRP-29535 - CS reimplementation of CalCentral hard coded links

- app/models/my_activities/webcasts.rb
- fixtures/webcast/warehouse/webcast.json
- spec/models/my_activities/webcasts_spec.rb
- spec/models/webcast/recordings_spec.rb
https://jira.berkeley.edu/browse/SISRP-28970
My my, hey hey
Webcast is out of the blue and into the EDO
cc: @paulkerschen
> SISRP-28970, MyActivities::Webcasts don't care 'bout no stinkin' legacy data

- config/routes.rb
As pointed out by @paulkerschen at https://github.com/ets-berkeley-edu/calcentral/pull/6334#discussion_r97128912
> NOJIRA Remove obsolete Rails 3 "via" syntax for Routes

- app/models/berkeley/degree_progress_graduate.rb
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- spec/support/degree_progress_shared_examples.rb
- src/assets/javascripts/angular/controllers/widgets/academics/degreeProgressController.js
https://jira.berkeley.edu/browse/SISRP-29765
We weren't showing the Capstone milestone; now we are.
> SISRP-29765 - Surfaces the Capstone milestone on Degree Progress

- app/models/my_academics/grading.rb
- config/settings.yml
- config/settings/test.yml
- spec/models/my_academics/grading_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-29570
Design JIRA:  https://jira.berkeley.edu/browse/SISRP-29519
* Title says it all
* Also makes this feature `fake_now`-friendly, enabling testing of past/future dates, since that drives most of the UI.
> SISRP-29570 - Mid-Point Grades: Instructor-Facing

- src/assets/templates/widgets/profile/basic.html
- src/assets/templates/widgets/profile/double_entry.html
https://jira.berkeley.edu/browse/SISRP-26108
> SISRP-26108 - Remove BearFacts Reference from Profile Page

- app/models/my_academics/transfer_credit.rb
https://jira.berkeley.edu/browse/SISRP-27828
* Some fortification for `transfer_credit.rb`
> SISRP-27828 - undefined method [] for nil:NilClass: FilteredForAdvisor > my_academics/transfer_credit.rb:12

- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-29777
I changed the message slightly from what was requested (removed the word "completely" because it doesn't make sense).
> SISRP-29777 - When no degree progress data for grad student, displays the card with a message

- src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-29857
> SISRP-29857 - My Academics - New Transcript Link in CalCentral for UCBX Concurrent Enrollment

- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-29857
> SISRP-29857 - New Transcript Link in CalCentral for UCBX Concurrent Enrollment - Design 2

- public/dummy/json/enrollment_instructions_2172.json
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/directives/campusSolutionsLinkV2Directive.js
- src/assets/javascripts/angular/directives/outboundLinkDirective.js
- src/assets/javascripts/angular/factories/enrollmentFactory.js
- src/assets/javascripts/angular/services/linkService.js
- src/assets/templates/widgets/advisor/advising_links.html
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
- src/assets/templates/widgets/enrollment/decide_concurrent.html
- src/assets/templates/widgets/enrollment/explore.html
- src/assets/templates/widgets/enrollment/plan.html
- src/assets/templates/widgets/finances_links.html
- src/assets/templates/widgets/my_advising.html
- src/assets/templates/widgets/profile/delegate.html
- src/assets/templates/widgets/student_resources.html
- src/assets/templates/widgets/toolbox/user_preview.html
- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-29512
* Introduces ccCampusSolutionsLinkV2Directive
* Updates outboundLinkDirective.js code to not apply to ccCampusSolutionsLinkV2Directive
* Updates linkService to share outboundLink methods
* Updates Advisor Resource links in Advisor Resources card (Dashboard) and Personal Summary card (Student Overview)
> SISRP-29512 - 7.5: Refactor coding conventions to match new CS Link API

- app/models/berkeley/degree_progress_graduate.rb
https://jira.berkeley.edu/browse/SISRP-29962
> SISRP-29962 - Milestone status missing

- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-30017
my best work yet!
> SISRP-30017 - Students' Minors are not showing correctly on My Academics Profile

- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-30001
* moving stuff around on student over page when acad plan is activated via feature flag
> SISRP-30001 - Rearrange Student Overview Page Layout

- src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6562
Wording.
> CLC-6562, update 'Create A Site' project site language and link

- src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-29857
Implementation of final design (change of labels)
> SISRP-29857 - My Academics - New Transcript Link in CalCentral for Concurrent Enrollment (UCBX)

- src/assets/stylesheets/_degree_progress.scss
- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-30021
> SISRP-30021 - Show checkmark icon next to completed milestone

- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-29961
> SISRP-29961 - Ensure proper ordering of milestones

- app/models/my_committees/committees_module.rb
- app/models/my_committees/faculty_committees.rb
- app/models/my_committees/student_committees.rb
- spec/models/my_committees/faculty_committees_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/widgets/higher_degree_faculty_committees.html
Reverts ets-berkeley-edu/calcentral#6364
> Revert "SISRP-30081 - Removes active/completed committee distinction"

- public/dummy/json/campus_solutions_link.json
- public/dummy/json/campus_solutions_link_empty.json
- public/dummy/json/enrollment_instructions_2172.json
- src/assets/javascripts/angular/directives/campusSolutionsLinkV2Directive.js
- src/assets/javascripts/angular/directives/outboundLinkDirective.js
- src/assets/javascripts/angular/factories/csLinkFactory.js
- src/assets/templates/academics.html
- src/assets/templates/faculty_resources.html
- src/assets/templates/widgets/academics/academic_records.html
- src/assets/templates/widgets/academics/degree_progress_graduate.html
- src/assets/templates/widgets/academics/enrollment_verification.html
- src/assets/templates/widgets/activity_archive.html
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
- src/assets/templates/widgets/enrollment/adjust_waitlisted.html
- src/assets/templates/widgets/enrollment/decide.html
- src/assets/templates/widgets/enrollment/explore.html
- src/assets/templates/widgets/enrollment/plan.html
- src/assets/templates/widgets/finaid_communications_tasks.html
- src/assets/templates/widgets/profile/delegate.html
- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-29512
* Updates CS Links in Student Resources, Faculty Resources, Class enrollment, Degree Progress, and Academic Records cards.
* Fixes layout issue for ex-students.
* Updates ccCampusSolutionsLinkV2Directive to watch URL in link object or attribute for changes.
> SISRP-29512 - 7.5: Refactor back and front-end coding conventions to match new CS Link API

- src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6562
Per Steven's recent comment in Jira above.
> CLC-6562, ditch the KB link on bCourses site_creation page

- src/assets/templates/academics.html
https://jira.berkeley.edu/browse/SISRP-30141
Both students and ex-students will be able to see the card.
> SISRP-30141 - show the student committees card to ex-students

- app/models/my_committees/committees_module.rb
- spec/models/my_committees/faculty_committees_spec.rb
- spec/models/my_committees/student_committees_spec.rb
https://jira.berkeley.edu/browse/SISRP-30080
Just a simple text change.
> SISRP-30080 - Updates QE Committee exam date label

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-29452
* This fix should really be done in the back-end, but doing so will require some non-trivial code changes to important feeds that I don't feel comfortable doing so close to 7.5
* Will open a JIRA to follow-up and refactor this fix (bring it to server-side) for GL8.0.
* Opened [SISRP-30187](https://jira.berkeley.edu/browse/SISRP-30187)
* QA PR to come upon merge
> SISRP-29452 - My Academics and Student Overview cards displaying Incorrect GPA and Unit Data - combining UG+G

- public/dummy/json/my_advising.json
https://jira.berkeley.edu/browse/SISRP-29245
Updates dummy feed used to perform front-end testing via factory
> SISRP-29245 - Update My Advising dummy feed with new Link API structure

- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-30019
> SISRP-30019 - 'No midpoint grade roster' showing for non-law classes

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-29452
* QA PR of #6372
> [QA] SISRP-29452 - My Academics and Student Overview cards displaying Incorrect GPA and Unit Data - combining UG+G

- public/dummy/json/my_advising.json
https://jira.berkeley.edu/browse/SISRP-29245
See DEV PR #6374
> [QA] SISRP-29245 - Update My Advising dummy feed with new Link API structure

- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-30019
* QA PR of #6376
> [QA] SISRP-30019 - 'No midpoint grade roster' showing for non-law classes

- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-30208
* Minor edits to student-facing midpoint grades
> SISRP-30208 - UX Dev: Midpoint grades - student facing

- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-30208
* QA PR of #6379
> [QA] SISRP-30208 - UX Dev: Midpoint grades - student facing

- app/models/edo_oracle/adapters/oec.rb
- app/models/oec/worksheet.rb
- spec/models/edo_oracle/adapters/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6569
> CLC-6569 OEC: deduplicate and format ASSOCIATED_PRIMARY

- app/models/edo_oracle/adapters/oec.rb
- app/models/oec/worksheet.rb
- spec/models/edo_oracle/adapters/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6569
QA version of #6383.
> [QA] CLC-6569 OEC: deduplicate and format ASSOCIATED_PRIMARY

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-30239
If the student has undergrad degree progress, we were showing that plus an empty graduate degree progress card.  This hides the empty card in that case.  QA PR forthcoming
> SISRP-30239 - Only show GRAD Degree Progress card if UGRD is hidden

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/templates/user_overview.html
> [QA] SISRP-30239 - Only show GRAD Degree Progress card if UGRD is hidden

- lib/torquebox_inspector.rb
- public/dummy/json/torquebox_status.json
https://jira.berkeley.edu/browse/SISRP-30256
I don't have any theories about the underlying cause, but it doesn't seem like there's much I can do about it, either.
> SISRP-30256 Survive NPE when introspectingTorquebox status

- app/models/berkeley/degree_progress_graduate.rb
- app/models/degree_progress/milestones_module.rb
- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-29961
QA PR of #6384
> [QA] SISRP-29961 - Ensure proper ordering of milestones - Reopened

- fixtures/xml/campus_solutions/financial_aid_funding_sources.xml
- public/dummy/json/financial_aid_funding_sources.json
- src/assets/javascripts/angular/configuration/routeConfiguration.js
- src/assets/javascripts/angular/factories/finaidFactory.js
- src/assets/templates/widgets/finaid_awards_loans.html
- src/assets/templates/widgets/finaid_awards_section.html
- src/assets/templates/widgets/finaid_summary_footer.html
https://jira.berkeley.edu/browse/SISRP-30183
* Fixes Award card links for award sections
* Updates page name for Financial Aid and Scholarships page routes.
* Adds links to fixture for CampusSolutions::FinancialAidFundingSources proxy.
* Adds dummy JSON for finaidFactory
* Updates Shopping Sheet link in Financial Aid and Scholarships Summary card
> SISRP-30183 - I can no longer see Fluid links in CalCentral-sis-dev, CalCentral-sis-test, CalCentral-dev

- fixtures/xml/campus_solutions/financial_aid_funding_sources.xml
- public/dummy/json/financial_aid_funding_sources.json
- src/assets/javascripts/angular/configuration/routeConfiguration.js
- src/assets/javascripts/angular/factories/finaidFactory.js
- src/assets/templates/widgets/finaid_awards_loans.html
- src/assets/templates/widgets/finaid_awards_section.html
- src/assets/templates/widgets/finaid_summary_footer.html
https://jira.berkeley.edu/browse/SISRP-30183
See DEV PR #6389
> [QA] SISRP-30183 - I can no longer see Fluid links in CalCentral-sis-dev, CalCentral-sis-test, CalCentral-dev

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
- src/assets/templates/academics_classinfo.html
- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-26607
QA PR to come upon merge.
> SISRP-26607 - 7.5 My Academics (Instr) - Course Page (Enrollment tab) Hide 'request' buttons (LAW)

- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-30252
See DEV PR #6390
> [QA] SISRP-30252 - 'Request Official Verification' - Google form link showing in addition to CS link

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
- src/assets/templates/academics_classinfo.html
- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-26607
QA PR of #6392
> [QA] SISRP-26607 - 7.5 My Academics (Instr) - Course Page (Enrollment tab) Hide 'request' buttons (LAW)

- src/assets/templates/widgets/finaid_summary_footer.html
https://jira.berkeley.edu/browse/SISRP-30183
* Updates Shopping Sheet link to open in new window without banner parameters.
> SISRP-30183 - Updates Shopping Sheet link to open in new window with no CC banner

- src/assets/templates/widgets/finaid_summary_footer.html
https://jira.berkeley.edu/browse/SISRP-30183
See DEV PR #6395
> [QA] SISRP-30183 - Updates Shopping Sheet link to open in new window with no CC banner

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-30217
* Removes TeleBears link
* Update 'Bookstore - Berkeley Law' link
* Updates 'Campus Shuttles' link in Getting Around section of My Campus page
* Updates 'Class Pass' link in Getting Around section of My campus page
* Updates 'Lab Safety' link in Staff Learning section of My Campus page
* Updates 'Student Organizations Search' link in Student Engagement section of My Campus page
* Updates 'Imagine Services' link within Tools & Resources section of My Campus page
* Updates 'IST Knowledge Base' link within Tools & Resources section of My Campus page
* Updates 'Blu Card' link within Tools & Resources section of My Campus page
* Updates 'Purchasing' link within Tools & Resources section of My Campus page
* Updates 'Travel & Entertainment' link …
> SISRP-30217 - Broken Links under My Campus (404 / DNS )

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-30217
See DEV PR #6397
> [QA] SISRP-30217 - Broken Links under My Campus (404 / DNS )

- src/assets/javascripts/angular/services/academicsService.js
https://jira.berkeley.edu/browse/SISRP-30297
QA PR of #6398
> [QA] SISRP-30297 - Midpoint Status column is missing when the Grading card has Law and Non Law classes

- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-30252
> SISRP-30252 - Removes Google form based Enrollment Verification link

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-30189
QA PR of #6404
> [QA] SISRP-30189 - Grading in CalCentral Accessibility Issues

- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-30252
See DEV PR #6401
> [QA] SISRP-30252 - Removes Google form based Enrollment Verification link

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-30250
QA PR to come.
> SISRP-30250 - 'Assistance with Midpoint Grading: General' needs to be added to the Grading tab on Class Roster

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
> [QA] SISRP-29777 - Show Degree Progress card to GRAD/LAW students with no milestones

- src/assets/stylesheets/_tasks.scss
- src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-30253
* Fixes styling of task buttons to avoid truncated styling when button text exceeds 50 characters.
> SISRP-30253 - Truncated Notification Link

- src/assets/stylesheets/_tasks.scss
- src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-30253
See DEV PR #6412
> [QA] SISRP-30253 - Truncated Notification Link

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-30250
QA PR of #6410
> [QA] SISRP-30250 - 'Assistance with Midpoint Grading: General' needs to be added to the Grading tab on Class Roster

- config/routes.rb
https://jira.berkeley.edu/browse/SISRP-30391
Thank you for the catch, @redconfetti !
> SISRP-30391 Re-enable Rosters in CalCentral-only mode

- config/routes.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/6415
> [QA] SISRP-30391 Re-enable Rosters in CalCentral-only mode

- public/canvas/canvas-customization.js
Instructure tells us the new React-based UI will go live on Feb 18, the same day as our scheduled CalCentral/Junction release. This PR prepares the Add People tool for the new Canvas UI and preserves legacy support in case these future releases do not happen as scheduled.
> CLC-6575, Canvas People tool: custom js for both React-based UI and the legacy UI

- public/canvas/canvas-customization.js
> [QA] CLC-6575, Canvas People tool: custom js for both React-based UI and the legacy UI

- app/models/my_committees/student_committees.rb
Reverts ets-berkeley-edu/calcentral#6418
> Revert "SISRP-30364 - Hides link on Committees card until the e-form is ready"

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-30412
> SISRP-30412 - LinkService Console Error on Student Overview

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-30412
See DEV PR #6421
> [QA] SISRP-30412 - LinkService Console Error on Student Overview

- public/canvas/canvas-customization.js
The new style (on label of link at far right)...
> CLC-6575, style for 'Find a Person' label in Canvas UI

- public/canvas/canvas-customization.js
> [QA] CLC-6575, style for 'Find a Person' label in Canvas UI

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6567
Note a change from the JS given in the ticket (`ALLY_CFG.baseUrl` becomes `window.ALLY_CFG.baseUrl`) in order to avoid a jshint error.
> CLC-6567 Add custom Ally JavaScript to bCourses

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6567
QA version of #6426.
> [QA] CLC-6567 Add custom Ally JavaScript to bCourses

- public/canvas/canvas-customization.js
The times they are a changin'... Dynamically tweak the 'Add People' error dialog:
* We attach listeners to the 'Cancel', 'Back' and 'Next' buttons because, as long as you are on the Add People page, they are not re-drawn.
* Unlike the old UI, the bad email addresses (or IDs) are not rendered in an easy-to-isolate list. We must extract the data from a table and then remove the table. We are removing the option to create new users using unrecognized input.
> CLC-6575, Canvas React-based UI: customize error in Add People

- public/canvas/canvas-customization.js
> [QA] CLC-6575, Canvas React-based UI: customize error in Add People

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6579
Fortunately, both old and new UIs have same id for tab in question. Notice that I ditched `modifiedMarker()` function in favor of local vars.
> CLC-6579, Help icon ('How do I add people to my site?') on tab of Add People tool

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-30335
QA PR to come.
> SISRP-30335 - 'Grading Status Legend' needs to be dynamic

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6579
master PR #6430 
If/when Canvas rolls out the new UI (approx. Feb 18) then, without this particular fix, we will lose the help icon entirely. A QA PR is justified.
> [QA] CLC-6579, Help icon ('How do I add people to my site?') on tab of Add People tool

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-30335
QA PR of #6424
> [QA] SISRP-30335 - 'Grading Status Legend' needs to be dynamic

- src/assets/templates/widgets/finaid_summary_footer.html
https://jira.berkeley.edu/browse/SISRP-30292
> SISRP-30292 - Updates 'Shopping Sheet' link to open in same window with CalCentral banner parameters present

- src/assets/templates/widgets/finaid_summary_footer.html
https://jira.berkeley.edu/browse/SISRP-30292
See DEV PR #6436
> [QA] SISRP-30292 - Updates 'Shopping Sheet' link to open in same window with CalCentral banner parameters present

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6579
master PR is #6438
> [QA] CLC-6579, proper ID of tab on Add People

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/holdsController.js
https://jira.berkeley.edu/browse/SISRP-30536
* removed the loadholds in studentOverviewController
* made holdsController primary module to load holds for all conditions.
> SISRP-30536 - Student Overview Card missing Holds: AA Status and Holds card

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/holdsController.js
> [QA] SISRP-30536 - Student Overview Card missing Holds: AA Status and Holds card

- app/models/my_committees/student_committees.rb
- spec/models/my_committees/student_committees_spec.rb
https://jira.berkeley.edu/browse/SISRP-30527
QA PR for #6443
> [QA] SISRP-30527 - Filters inactive committee members from the student committees card

- app/models/my_academics/grading.rb
https://jira.berkeley.edu/browse/SISRP-30513
* Really glad this was caught, but a bit worried that it was caught during load testing and not beforehand.
* Fixed an error check that was only checking for Final grade status.
* Needed to fortify the code a bit more for nil values from APIs, and fudged on an error object that needed to include both final and midpoint values.
> SISRP-30513 - Grading My Academics merged model reporting errors in QA

- app/models/my_academics/grading.rb
https://jira.berkeley.edu/browse/SISRP-30335
QA PR of #6444
> [QA] SISRP-30513 - Grading My Academics merged model reporting errors in QA

- app/models/my_academics/grading.rb
https://jira.berkeley.edu/browse/SISRP-30335
* Follow-up to #6444 
* QA to follow right after
* Includes @lyttam's suggested changes in #6444 , making the code much more readable/clean.
> SISRP-30513 - Grading My Academics merged model reporting errors in QA v2

- app/models/my_academics/grading.rb
https://jira.berkeley.edu/browse/SISRP-30513
QA PR of #6449
> [QA] SISRP-30513 - Grading My Academics merged model reporting errors in QA v2

- src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6564
> CLC-6564 Add term name to initial course site name

- app/models/oec/report_diff_task.rb
- spec/models/oec/report_diff_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6587
> CLC-6587 OEC: Attach per-department diffs to confirmation sheets

- src/assets/javascripts/angular/controllers/pages/rosterController.js
- src/assets/stylesheets/_canvas_roster.scss
- src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-30579
> SISRP-30579 - Adds Waitlist/Enrollment filtering

- app/controllers/routes_list_controller.rb
- app/models/user/api.rb
- config/initializers/messaging.rb
- config/routes.rb
- config/settings.yml
- config/settings/development.yml
- lib/cache/live_updates_enabled.rb
- lib/provided_services.rb
- script/init.d/calcentral
- script/sis/verify_sis_api_endpoints.sh
- script/update-build.sh
- script/upgrade.sh
https://jira.berkeley.edu/browse/SISRP-30006
https://jira.berkeley.edu/browse/SISRP-30566
https://jira.ets.berkeley.edu/jira/browse/CLC-6592
Preparation for unveiling the ETS-only development cluster.
> SISRP-30566 SISRP-30006 CLC-6592 CalCentral ETS handoff support

- app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6594
The code change is mostly indentation.
> CLC-6594 Handle multiple meeting-schedule ranges in OEC

- app/models/notifications/sis_expiry_class_provider.rb
- app/models/notifications/sis_expiry_processor.rb
- spec/models/notifications/sis_expiry_class_provider_spec.rb
https://jira.berkeley.edu/browse/SISRP-30489
> SISRP-30489 - Develop CalCentral Consumption of Class Grade-Roster JMS

- app/controllers/mediacasts_controller.rb
- app/models/berkeley/course_policy.rb
- app/models/berkeley/summer16_enrollment_terms.rb
- app/models/berkeley/terms.rb
- app/models/campus_oracle/queries.rb
- app/models/canvas_lti/sis_adapter.rb
- app/models/my_academics/gpa_units.rb
- app/models/my_academics/registrations.rb
- app/models/my_academics/semesters.rb
- app/models/my_academics/teaching.rb
- app/models/my_classes/campus.rb
- app/models/rosters/campus.rb
- app/models/rosters/common.rb
- app/models/user/has_instructor_history.rb
- app/models/user/has_student_history.rb
- app/models/user/student.rb
- config/settings.yml
https://jira.berkeley.edu/browse/SISRP-28717
added warning for legacy database use
data source flow gates controlled by new flag
added allow_legacy_fallback flag to semesters model
added allow_legacy_fallback flag to all legacy? logic
> SISRP-28717 Update SOR to CS for CalCentral

- src/assets/stylesheets/_academics.scss
- src/assets/stylesheets/_useful.scss
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academic_plan.html
SISRP-30491 - 8.0 - Grading - Advisor Facing Midterm Grades
* Surfaces student midpoint grades to advisors.
* No work needed in the back-end thankfully, due to `AcademicPlan` pulling directly from `Semesters`.
> SISRP-30491 - 8.0 - Grading - Advisor Facing Midterm Grades

- app/models/campus_solutions/advising_resources.rb
- app/models/campus_solutions/link.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_resources.json
- spec/models/campus_solutions/link_spec.rb
- spec/models/campus_solutions/student_resources_spec.rb
- src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js
- src/assets/stylesheets/_advising_resources.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/widgets/advisor/advising_links.html
https://jira.berkeley.edu/browse/SISRP-30436
* Updates Advising Resources card to display links in alphabetical order
* Adds new links
* Fixes grouping of links in AdvisingResourcesController
* Adds support to CampusSolutions::Link for LINK_DESCRIPTION and LINK_DESCRIPTION_DISPLAY properties
* Updates styling of Advising Resources card to support inline descriptions
* Updates mocked / dummy configuration for new links
> SISRP-30436 - 8.0 - SR: Archived DB2 administrative report need to be surfaced to Advisors

- app/models/campus_solutions/student_resources.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/campus_solutions/student_resources_spec.rb
- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-31046
> SISRP-31046 - Add link to Late Petition to Change Class Schedule to Student Resources card

- app/models/my_academics/gpa_units.rb
- src/assets/javascripts/angular/configuration/routeConfiguration.js
- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/stylesheets/_academic_summary.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/academic_summary_page.html
- src/assets/templates/academics_student_profile.html
- src/assets/templates/directives/academic_plans.html
- src/assets/templates/widgets/academic_summary/academic_summary_card.html
- src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
- src/assets/templates/widgets/academics/college_and_level.html
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-30927
* What's the team's feeling on having half-done features hanging out in DEV/QAT environments before release?  I didn't want to add a feature flag because we don't really need it, but if I leave this feature for one giant PR, it's going to be huge.  So I'm developing this piece-wise, but that means piece-wise functionality in our development environments.  What do you guys think?  Also very interested in PDG's opinion as well (@raydavis @lyttam @redconfetti @nkutub)
* Pretty big PR, so happy to go over this in person as well.
* I was debating for a very long time to use the existing `academics_student_profile.html` and `college_and_level.html` templates, but the designs are different enough that the dynamic classes would have been, in my …
> SISRP-30927 - 8.0 - Academic Summary - Student Profile Section

- src/assets/stylesheets/_canvas_base.scss
- src/assets/stylesheets/_canvas_buttons.scss
https://jira.ets.berkeley.edu/jira/browse/CLC-6607
Following up from @redconfetti 's fix at https://github.com/ets-berkeley-edu/calcentral/pull/6470/files#diff-6bf4289454a57e98915966b94ae1a9c1R1
> CLC-6607 Fix bCourses Roster Photos formatting

- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-30579
* Updates the 'Enrollments' tab section of the Class Page to include the new section columns that were added to the Rosters tab under List view.
> SISRP-30579 - Adds section columns to Class page Enrollments view

- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/stylesheets/_academic_summary.scss
- src/assets/templates/widgets/academic_summary/academic_summary_card.html
- src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-31075
* 2nd piece to Academic Summary
* That's a beautiful +/-, but a lot of it is just indentation once again.
> SISRP-31075 - 8.0 - Academic Summary - Transfer Credit Section

- app/models/degree_progress/my_graduate_milestones.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/degree_progress/my_graduate_milestones_spec.rb
- src/assets/stylesheets/_degree_progress.scss
- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-25708
> SISRP-25708 - Grad Degree Progress card - Add additional links

- app/models/berkeley/graduate_milestones.rb
- app/models/degree_progress/graduate_milestones.rb
- app/models/degree_progress/milestones_module.rb
- fixtures/xml/campus_solutions/degree_progress_graduate.xml
- spec/models/berkeley/degree_progress_graduate_spec.rb
- spec/models/my_committees/faculty_committees_spec.rb
- spec/support/degree_progress_shared_examples.rb
- src/assets/stylesheets/_degree_progress.scss
- src/assets/templates/widgets/academics/degree_progress_graduate.html
- Qualifying Exam Results is a special milestone in that at student can attempt it (the exam) multiple times.  We'll now show list each attempt and its outcome on the Degree Progress card. (https://jira.berkeley.edu/browse/SISRP-30563)
- Qualifying Exam Approval milestone will now show the proposed exam date (https://jira.berkeley.edu/browse/SISRP-30568)
> SISRP-25708 - Degree Progress (Grad) Enhancements

- app/models/service_alerts/alert.rb
- app/models/service_alerts/merged.rb
- db/migrate/20170307233607_add_splash_to_service_alerts.rb
- db/schema.rb
- spec/models/service_alerts/merged_spec.rb
https://jira.berkeley.edu/browse/SISRP-28447
Please don't merge until we have OK from Ben, @nkutub , and CC QA for this to go into GL8.
> SISRP-28447 Remove CalCentral Release Notes dependency on ETS website

- src/assets/templates/widgets/academics/degree_progress_undergrad.html
Parent:  https://jira.berkeley.edu/browse/SISRP-25357
Removes "University Requirements" header and changes "Requirement" to "University Requirement" (https://jira.berkeley.edu/browse/SISRP-30633)
> SISRP-30633 - Removes/updates headers on UGRD Degree Progress

- app/models/berkeley/degree_progress_undergrad.rb
- spec/models/berkeley/degree_progress_undergrad_spec.rb
- spec/support/degree_progress_shared_examples.rb
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
Parent: https://jira.berkeley.edu/browse/SISRP-25357
Changes the icons and labels for requirement statuses. (https://jira.berkeley.edu/browse/SISRP-30635)
> SISRP-30635 - Updates status messages on UGRD Degree Progress

- app/models/campus_solutions/proxy.rb
- app/models/degree_progress/requirements_module.rb
- src/assets/javascripts/angular/controllers/widgets/academics/undergraduateDegreeProgressController.js
- src/assets/javascripts/angular/factories/academics/degreeProgressFactory.js
- src/assets/templates/academics.html
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
Parent:  https://jira.berkeley.edu/browse/SISRP-25357
We'll always show the Degree Progress card to undergrad students - if they have no data to show, we'll instead display a message. (https://jira.berkeley.edu/browse/SISRP-30643)
> SISRP-30643 - Adds 'no data' message on UGRD Degree Progress

- app/models/berkeley/degree_progress_undergrad.rb
- app/models/degree_progress/requirements_module.rb
- fixtures/xml/campus_solutions/degree_progress_undergrad.xml
- public/dummy/json/degree_progress_ugrd.json
- spec/models/berkeley/degree_progress_undergrad_spec.rb
- spec/support/degree_progress_shared_examples.rb
- src/assets/javascripts/angular/factories/academics/degreeProgressFactory.js
- src/assets/stylesheets/_degree_progress.scss
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
Parent JIRA - https://jira.berkeley.edu/browse/SISRP-25357
https://jira.berkeley.edu/browse/SISRP-30966
https://jira.berkeley.edu/browse/SISRP-30634
> SISRP-25357 - Surface formatted last report date and adds 'In Progress' status

- public/canvas/index.js
https://jira.berkeley.edu/browse/SISRP-30003
This file is used to set up JS and CSS customization and front-end URLs.
> SISRP-30003 Shift Canvas support from CalCentral to ETS-Junction servers

- src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-31233
> SISRP-31233 - Urgent UX, don't display Dashboard "Student Resources" card

- public/dummy/json/degree_progress_grad.json
- src/assets/javascripts/angular/factories/academics/degreeProgressFactory.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/templates/widgets/academics/degree_progress_graduate.html
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
Parent:  https://jira.berkeley.edu/browse/SISRP-25708
Updates the text of the message we show to students, and adds a separate message to show to advisors.  (https://jira.berkeley.edu/browse/SISRP-31313)
> SISRP-31313 - Updates 'no data' message on Grad Degree Progress

- src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-31289
> SISRP-31289 - My Finance > Financial Aid and Scholarships card has incorrect spelling for the link "Authorize Title IV authorization".

- src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js
https://jira.berkeley.edu/browse/SISRP-30436
> SISRP-31046 - Fix bug when name is null

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-31239
> SISRP-31239 - Remove ScheduleBuilder Link from CalCentral Academic Planning

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-31239
See DEV PR #6506
> [QA] SISRP-31239 - Remove ScheduleBuilder Link from CalCentral Academic Planning

- spec/models/degree_progress/my_undergrad_requirements_spec.rb
https://jira.berkeley.edu/browse/SISRP-25357
> SISRP-25357 - Resolve tests failing in TestExt env

- public/dummy/json/degree_progress_ugrd.json
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
Parent:  https://jira.berkeley.edu/browse/SISRP-30580
https://jira.berkeley.edu/browse/SISRP-31389
> SISRP-31389 - Adds advisor-specific 'no data' message to UGRD Degree Progress

- public/dummy/json/degree_progress_ugrd.json
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/factories/advisingFactory.js
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
QA PR for #6513
-----
Parent:  https://jira.berkeley.edu/browse/SISRP-30580
https://jira.berkeley.edu/browse/SISRP-31389
> [QA] SISRP-31389 - Adds advisor-specific 'no data' message to UGRD Degree Progress

- app/controllers/hub_edo_controller.rb
- src/assets/images/svg/private_folder.svg
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/pages/campusController.js
- src/assets/javascripts/angular/controllers/pages/dashboardController.js
- src/assets/javascripts/angular/controllers/pages/myFinancesController.js
- src/assets/stylesheets/_status.scss
- src/assets/templates/academics.html
- src/assets/templates/dashboard.html
- src/assets/templates/delegate_access_denied.html
- src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-15392
Adds "Access Denied" pages for inaccessible pages as a delegate, with redirect to either Academics, Finances, or Campus Links (whichever is available).
Also makes Campus Links available to delegates by way of making Academic Status (and the dependent Roles) available.  The caveat is that delegates must be authorized for enrollments, so delegates who are only authorized for financials will have a broken experience still.
To fix this, we need to decouple Roles from Academic Status.  That requires a larger code change, so I think we should put in a fix in a future release instead of cramming it in to 8.0.
QA PR to come.
> SISRP-15392 - Delegated Access: ‘not found’ redirects for inaccessible pages need improvement

- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-31075
QA PR of #6522
> [QA] SISRP-31075 - 8.0 - Academic Summary - Transfer Credit Section

- app/models/edo_oracle/user_courses/all.rb
- app/models/edo_oracle/user_courses/base.rb
https://jira.berkeley.edu/browse/SISRP-31399
QA PR of #6519
> [QA] SISRP-31399 - Delegates Seeing Duplicate Classes in Semesters

- app/controllers/hub_edo_controller.rb
- src/assets/images/svg/private_folder.svg
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/controllers/pages/campusController.js
- src/assets/javascripts/angular/controllers/pages/dashboardController.js
- src/assets/javascripts/angular/controllers/pages/myFinancesController.js
- src/assets/stylesheets/_status.scss
- src/assets/templates/academics.html
- src/assets/templates/dashboard.html
- src/assets/templates/delegate_access_denied.html
- src/assets/templates/myfinances.html
https://jira.berkeley.edu/browse/SISRP-15392
QA PR of #6518
> [QA] SISRP-15392 - Delegated Access: ‘not found’ redirects for inaccessible pages need improvement

- app/models/degree_progress/undergrad_requirements.rb
- spec/models/degree_progress/undergrad_requirements_spec.rb
https://jira.berkeley.edu/browse/SISRP-31506
> SISRP-31506 - Advisors - Degree Progress(UGRD) - APR link page is not available

- src/assets/javascripts/angular/controllers/pages/dashboardController.js
https://jira.berkeley.edu/browse/SISRP-31527
> SISRP-31527 - Page title doesn't get refreshed when delegate tries to navigate to dashboard

- src/assets/javascripts/angular/controllers/pages/dashboardController.js
https://jira.berkeley.edu/browse/SISRP-31527
See DEV PR #6530
> [QA] SISRP-31527 - Page title doesn't get refreshed when delegate tries to navigate to dashboard

- app/models/degree_progress/undergrad_requirements.rb
- spec/models/degree_progress/undergrad_requirements_spec.rb
https://jira.berkeley.edu/browse/SISRP-31506
See DEV PR #6529
> [QA] SISRP-31506 - Student Overview -Degree Progress(UGRD) - APR link page is not available

- src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
https://jira.berkeley.edu/browse/SISRP-31598
QA PR to come if QA confirms they have enough bandwidth to test this today.
> SISRP-31598 - 8.0 - Academic Summary - Conferred Degrees

- src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
https://jira.berkeley.edu/browse/SISRP-31598
QA PR of #6536
> [QA] SISRP-31598 - 8.0 - Academic Summary - Conferred Degrees

- src/assets/templates/finaid_t4.html
- src/assets/templates/finaid_tc.html
https://jira.berkeley.edu/browse/SISRP-31292
* disabled buttons on approved
> SISRP-31292 - Terms and Conditions checklist should not have the Terms and Conditions button active once a student agrees

- src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-30643
> SISRP-30643 - GL 8.1 - Show card with message when there is no data

- src/assets/templates/finaid_t4.html
- src/assets/templates/finaid_tc.html
> [QA] SISRP-31292 - Terms and Conditions checklist should not have the Terms and Conditions button active once a student agrees

- app/models/notifications/sis_expiry_students_provider.rb
- spec/models/notifications/sis_expiry_students_provider_spec.rb
QA PR for #6545
Slated for emergency release.
> [QA] SISRP-28700 - Prevents error when receiving APR event notif

- app/models/edo_oracle/queries.rb
- app/models/rosters/common.rb
- config/settings.yml
> [QA] SISRP-31609 - Faculty cannot view and communicate via email with visiting summer students - Enrollment page

- app/models/my_committees/committees_module.rb
> SISRP-31605 - Extends 'advanced date' logic to look at milestone attempts

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6641
This is a blocker on bCourses-Beta, and likely to become a blocker on bCourses-Production on Saturday.
If so, it will go into a Junction-specific emergency release immediately following the CalCentral-specific emergency release.
> CLC-6641 Deal with breaking change in Canvas Add Users code

- app/models/rosters/canvas.rb
- app/models/rosters/common.rb
- spec/models/rosters/canvas_spec.rb
- spec/models/rosters/common_spec.rb
https://jira.berkeley.edu/browse/SISRP-30392
> SISRP-30392 - Faculty class export file missing columns: Waitlist position, Units, Grading basis

- src/assets/templates/widgets/enrollment/consult_advisor.html
https://jira.berkeley.edu/browse/SISRP-23082
> SISRP-23082 - Mod Request by LAW  (email address change)

- public/dummy/json/cs_checklist_ugrd.json
- public/dummy/json/cs_sir_config.json
- src/assets/javascripts/angular/controllers/widgets/sir/sirItemController.js
- src/assets/javascripts/angular/factories/sirFactory.js
https://jira.berkeley.edu/browse/SISRP-31811
* Adds mock JSON feeds for sirFactory
* Fixes bug arising from AngularJS 1.5.8 to 1.6.3 upgrade
> SISRP-31811 - SIR process giving error while accepting offer

- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academic_plan.html
- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-31889
* QA PR of #6562
> [QA] SISRP-31889 - Grading: Prod: Spring Final Grades Not Appearing for Students in CalCentral (SNow 445421)

- public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6641
It's a sad story...
> CLC-6641 Work around Safari + React JS to customize course Add People

- src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-31628
For Qualifying Exam Results milestone only:  yellow icon if one failed attempt; red icon if more than one failed attempt.
> SISRP-31628 - Replicates committees status icon logic on Degree Progress

- src/assets/templates/widgets/student_success/gpa_trends.html
- src/assets/templates/widgets/student_success/student_success.html
> SISRP-31567 - Student Overview student success card is blank when page loads first time

- .jshintrc
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/factories/advisingFactory.js
WILL REVERT THIS CHANGE AFTER IT STOPS BEING USEFUL, I PROMISE.
> SISRP-31567 - TEMPORARY: adds debug logging to Student Success

- app/models/oec/api_task_wrapper.rb
- lib/tasks/oec.rake
- spec/models/oec/merge_confirmation_sheets_task_spec.rb
- src/assets/javascripts/angular/controllers/pages/oecController.js
- src/assets/stylesheets/_selects.scss
- src/assets/templates/oec.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6646
> CLC-6646 OEC: Select departments for confirmation sheet merge

- lib/link_fetcher.rb
- spec/lib/link_fetcher_spec.rb
https://jira.berkeley.edu/browse/SISRP-31911
Follow-up to #6569, just some small improvements to the `LinkFetcher`
> SISRP-31911 - Improves logging and unit testing

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
Another blind attempt to solve that mystery bug where the data doesn't load on the card the first time.
The console.log statements seemed to point to some timing issue or race condition involving setting things in `$scope` and then relying on them to be there in other parts of the JS controller.  I hope this will fix that, but we won't know until we can test it in dev.
I'd like this to have @davidlimcheng's blessing before merging.
> SISRP-31567 - refactors student success

- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/grading.rb
- app/models/my_academics/grading_module.rb
- spec/models/my_academics/grading_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-30492
* Introduces Summer Grading to CalCentral, which follows significantly different logic than regular term grading.
* Lots of the logic breakdown can be found here:  https://jira.berkeley.edu/browse/SISRP-30589
* But as always, feel free to ask me any questions.
> SISRP-30492 - 8.1 - Summer Grading

- db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6625
> CLC-6625 OEC: Mapping for freshman/sophomore seminars

- app/models/edo_oracle/queries.rb
- app/models/my_academics/semesters.rb
- public/dummy/json/academics.json
- spec/models/my_academics/semesters_spec.rb
- src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-27686
* added withdrawal data to semesters feed 
* new EDODB query  get_withdrawal_status
* added withdrawal info to semseters card
> SISRP-27686 -  Semesters - Withdrawal Status

- app/models/edo_oracle/oec.rb
- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-29536
* using new optimized views in EDODB
> SISRP-29536 - Performance test EDODB to pull legacy semester data

- spec/models/my_academics/grading_spec.rb
https://jira.berkeley.edu/browse/SISRP-32298
* See JIRA description, this is very useful to know for future tests.
> SISRP-32298 - Failing Rspec tests on Bamboo for Summer Grading

- gulpfile.js
https://jira.berkeley.edu/browse/SISRP-31200
> SISRP-31200 - Revision asset files in development build mode

- db/developer-seed-data.sql
- db/migrate/20170418172849_add_oec_course_codes.rb
- db/schema.rb
- spec/models/edo_oracle/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6625
This PR should fix the Bamboo build.
> CLC-6625 Include OEC Freshman/Sophomore seminar support in DB migrate

- .jshintrc
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/factories/advisingFactory.js
Removes logging introduced in #6573 for debugging purposes.  Also returns jshint config to its original state.  This should be merged only into the qa branch, as we want to leave the logging in place in master for now.
> [QA] SISRP-31567 - Removes JS logging

- app/models/edo_oracle/oec.rb
- app/models/oec/course_code.rb
- db/developer-seed-data.sql
- db/migrate/20170418172849_add_oec_course_codes.rb
- db/schema.rb
- spec/models/edo_oracle/oec_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/6588 and https://github.com/ets-berkeley-edu/calcentral/pull/6590
> [QA] CLC-6625 OEC Freshman/Sophomore seminar support

- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/base.rb
- app/models/my_academics/semesters.rb
- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-31171
QA PR of #6593
> [QA] 8.1 - Academic Summary - Add 'Grade Point' Column

- app/models/my_academics/academics_module.rb
- app/models/my_academics/semesters.rb
- spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-28717
QA PR of #6596
> [QA] SISRP-28717 - 8.1: Update SOR to CS for CalCentral

- spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-32347
QA PR of #6598
> SISRP-32347 - Rspec Failures on semesters_spec.rb

- app/models/user/identifiers.rb
- spec/models/user/identifiers_spec.rb
https://jira.berkeley.edu/browse/SISRP-31764
> SISRP-31764 Fix fallback to LDAP when Crosswalk is disabled

- app/models/my_academics/class_enrollments.rb
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-32237
* Late request, but should be small enough that we should be able to get it in.
* Got the OK from QA Team, they have the bandwidth to test this.
> SISRP-32237 - UX: Summer Fees Message on Class Enrollment Card

- app/models/my_academics/class_enrollments.rb
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-32237
QA PR of #6602
> [QA] SISRP-32237 - UX: Summer Fees Message on Class Enrollment Card

- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_student_academics.json
- spec/models/my_academics/academic_plan_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_academic_plan.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academic_plan.html
> SISRP-31634 - Dynamic Display of DB2 Archive Transcript Link

- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_student_academics.json
- spec/models/my_academics/academic_plan_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_academic_plan.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academic_plan.html
> [QA] SISRP-31634 - Dynamic Display of DB2 Archive Transcript Link

- app/models/berkeley/terms.rb
https://jira.berkeley.edu/browse/SISRP-32393
* Check out JIRA comments for a brief description of the analysis
> SISRP-32393 - Update SOR to CS- Missing Semesters card in CC-DEV

- app/models/berkeley/terms.rb
https://jira.berkeley.edu/browse/SISRP-32393
QA PR of #6605
> [QA] SISRP-32393 - Update SOR to CS- Missing Semesters card in CC-DEV

- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_student_academics.json
- spec/models/my_academics/academic_plan_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_academic_plan.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academic_plan.html
This feature is not ready in GL 8.1, it is being moved to GL 9.0. [SISRP-32463](https://jira.berkeley.edu/browse/SISRP-32463) is replacing it as a work-around in GL 8.1.
Reverts ets-berkeley-edu/calcentral#6604
> Revert "[QA] SISRP-31634 - Dynamic Display of DB2 Archive Transcript Link"

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-32462
QA PR to come upon merge.
> SISRP-32462 - Law Grading Legend needs to include 'Law classes: Instructor may need to submit raw score'

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-32462
QA PR of #6608
> [QA] SISRP-32462 - Law Grading Legend needs to include 'Law classes: Instructor may need to submit raw score'

- app/models/my_academics/semesters.rb
https://jira.berkeley.edu/browse/SISRP-32402
* refactor the merge to incorporate as part of the semester's sort.
> SISRP-32402 - Semesters - Withdrawal Status

- app/models/degree_progress/milestones_module.rb
https://jira.berkeley.edu/browse/SISRP-32470
QA PR for #6611
> [QA] SISRP-32470 - Returns empty response when no Grad Div milestones to show

- app/models/my_academics/semesters.rb
> [QA] SISRP-27686 - Semesters - Withdrawal Status

- app/models/my_academics/grading_module.rb
https://jira.berkeley.edu/browse/SISRP-32478
> SISRP-32478 - Grading > Legend Status when a Grade Roster is available needs to be updated

- app/models/my_academics/grading_module.rb
https://jira.berkeley.edu/browse/SISRP-32478
QA PR of #6614
> [QA] SISRP-32478 - Grading > Legend Status when a Grade Roster is available needs to be updated

- app/models/my_academics/academic_plan.rb
- src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-32505
* added withdrawal status to Plan card
> SISRP-32505 - Withdrawal status with the reason needs to be displayedon Student Overview(Advisor view)

- src/assets/stylesheets/_academic_plan.scss
- src/assets/stylesheets/_academic_summary.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academic_plan.html
- src/assets/templates/widgets/academic_summary/academic_summary_card.html
https://jira.berkeley.edu/browse/SISRP-32493
* QA PR of #6618 
* A bit different from #6618 because of past PR already put in place in Master branch by @redconfetti on #6600
> [QA] SISRP-32493QA - Update SOR to CS- Pre-Spring 2010 Data is Missing - Temporary Messaging

- app/models/my_academics/academic_plan.rb
- src/assets/templates/widgets/academic_plan.html
> [QA] SISRP-32505 - Withdrawal status with the reason needs to be displayedon Student Overview(Advisor view)

- src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-32522
* Used old email for text =(
> SISRP-32522 - Advisor side of Temporary message is incorrect for Update SOR to CS- Pre-Spring 2010 Data

- src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-32522
* QA PR of #6622
> [QA] SISRP-32522 - Advisor side of Temporary message is incorrect for Update SOR to CS- Pre-Spring 2010 Data

- src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-32506
> SISRP-32506 - Cancelled status needs to be displayed on Student Overiew(Advisor) and My Academics

- src/assets/templates/widgets/academic_plan.html
> [QA]SISRP-32506 - Cancelled status needs to be displayed on Student Overview(Advisor) and My Academics

- lib/memcached.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6665
We're seeing novel problems on Junction-Prod, and need to learn more.
> CLC-6665 Log more info on Memcached communication failures

- app/models/berkeley/legacy_terms.rb
- app/models/berkeley/term.rb
- app/models/berkeley/term_codes.rb
- app/models/campus_oracle/queries.rb
- app/models/edo_oracle/queries.rb
- app/models/webcast/recordings.rb
- config/settings.yml
- spec/models/berkeley/legacy_terms_spec.rb
- spec/models/berkeley/term_codes_spec.rb
- spec/models/edo_oracle/queries_spec.rb
- spec/models/webcast/recordings_spec.rb
https://jira.berkeley.edu/browse/SISRP-32379
The PR attempts to minimize programmatic joins between DBs rather than attempting full data coverage.
It also removes some obsolete EDO DB queries.
> SISRP-32379 Map legacy CCNs to CS section IDs for Course Captures

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
> SISRP-31567 - Removes sorting from termGpa parsing

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
> SISRP-31567 - Adds more logging

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
> SISRP-31567 - Even More logging

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
I accidentally added logging to the wrong process. I want to see if the Academic process overlaps with the Student Success call in a race condition.
> SISRP-31567 - Academics process logging

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
Using the [QA version](https://github.com/ets-berkeley-edu/calcentral/blob/qa/src/assets/javascripts/angular/controllers/pages/userOverviewController.js) of the controller as a template, reverts the userOverviewController to its original, non-log state.
> SISRP-31567 - Remove all logging

- src/assets/stylesheets/_useful.scss
- src/assets/stylesheets/_widgets.scss
https://jira.berkeley.edu/browse/SISRP-32440
* Lots of good stuff in the JIRA
* The beginning of the end for the clearfix hack
> SISRP-32440 - Update CSS to Include flow-root alternative to clearfix

- src/assets/templates/widgets/enrollment/adjust.html
https://jira.berkeley.edu/browse/SISRP-31724
This is an amendment to #6627
> SISRP-31724 - Hides late class change request link from Summer enrollment card for Law and UC Extension

- public/dummy/json/financial_aid_data.json
- public/dummy/json/financial_aid_data_summer_only.json
- src/assets/javascripts/angular/controllers/widgets/finaid/finaidCoaController.js
- src/assets/javascripts/angular/factories/finaidFactory.js
- src/assets/templates/widgets/finaid_coa.html
https://jira.berkeley.edu/browse/SISRP-32542
> SISRP-32542 - FA Cost of Attendance Card not rendering for Summer Only students

- spec/models/my_academics/grading_spec.rb
https://jira.berkeley.edu/browse/SISRP-33154
Why was this working before?  The mysteries of life.
> SISRP-33154 - Failing Rspec Grading Tests

- app/controllers/sessions_controller.rb
- config/settings.yml
* added UID to be populated from nameIdentifier in the omniauth SAML
> SISRP-32341 - Need connection information to point SiS-TEST to BCSTST92

- app/controllers/hub_edo_controller.rb
- app/models/hub_edos/demographics.rb
- app/models/hub_edos/gender.rb
- app/models/hub_edos/my_student.rb
- fixtures/json/hub_gender.json
- spec/controllers/hub_edo_controller_spec.rb
- spec/models/hub_edos/gender_spec.rb
- src/assets/templates/widgets/profile/demographic.html
https://jira.berkeley.edu/browse/SISRP-30570
* Surfaces Gender to all users except for Delegates
* Very interesting backstory on *why* this bug came about, which pertains to the usage of api-central.berkeley.edu.  More info in JIRA.
> SISRP-30570 - Gender on CalCentral Demographic Card displaying Not Available

- Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-32341
> NOJIRA - Update Omniauth-cas Gem to include newest commit

- app/models/edo_oracle/connection.rb
- app/models/edo_oracle/view_checker.rb
- lib/tasks/sisedo.rake
https://jira.berkeley.edu/browse/SISRP-33211
> SISRP-33211 - Create test script dependent SISEDO views / columns

- app/models/edo_oracle/connection.rb
https://jira.berkeley.edu/browse/SISRP-33211
Fixes interface to EdoOracle::Connection.query
> SISRP-33211 - Fix failing EdoOracle related tests

- lib/proxies/response_wrapper.rb
https://jira.berkeley.edu/browse/SISRP-33238
> SISRP-33238 - Suppress mocked exception stack traces in Test environment logs

- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-33365
> SISRP-33365 - Enrollment Verification is missing Request Official Verification Link

- src/assets/templates/footer.html
https://jira.berkeley.edu/browse/SISRP-32233
> SISRP-32233 - Update links from ETS to SIS support website

- app/models/edo_oracle/view_checker.rb
https://jira.berkeley.edu/browse/SISRP-33211
> SISRP-33211 - Adds configuration for SISEDO.STUDENT_REGISTRATIONV00_VW

- spec/models/oec/department_mappings_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6666
Fixes the 13 testext failures introduced by my earlier PR.
> CLC-6666 Do not run stub-crazed OEC tests against live Postgres DB

- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-31677
> SISRP-31677 - Transfer Credit Report link not available when viewing as a student

- app/controllers/concerns/advising_resources.rb
- spec/controllers/concerns/advising_resources_spec.rb
- src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js
https://jira.berkeley.edu/browse/SISRP-32503
> SISRP-32503 - Add Administrative Transcripts Batch to Advising Resources card

- src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-32471
> SISRP-32471 - On SPRING enrollment card choose classes link navigates only for summer schedule

- app/models/oec/department_mappings.rb
- spec/models/oec/department_mappings_spec.rb
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/6669
I've un-quarantined the now-fixed tests on Bamboo master.
> [QA] CLC-6666 Fix OEC cross-listings bug caught by testext

- src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-32471
See DEV PR #6662
> [QA] SISRP-32471 - On SPRING enrollment card choose classes link navigates only for summer schedule

- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-31074
> SISRP-31074 - Transfer Units in Student Success Card show TC adjust for continuing students

- public/dummy/json/enrollment_verification.json
- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-28785
> SISRP-28785 - Updates Enrollment Verification messaging for Berkeley Law

- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/widgets/student_success/units.html
https://jira.berkeley.edu/browse/SISRP-31074
See DEV PR #6673
> [QA] SISRP-31074 - Transfer Units in Student Success Card show TC adjust for continuing students

- public/dummy/json/enrollment_verification.json
- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-28785
See DEV PR #6674
> [QA] SISRP-28785 - Updates Enrollment Verification messaging for Berkeley Law

- app/controllers/campus_solutions/link_controller.rb
- app/models/campus_solutions/link.rb
- lib/link_fetcher.rb
- spec/lib/link_fetcher_spec.rb
- spec/models/campus_solutions/link_spec.rb
- spec/models/my_academics/advisor_links_spec.rb
- spec/models/my_academics/enrollment_verification_spec.rb
- spec/models/my_academics/grading_spec.rb
- spec/models/my_academics/student_links_spec.rb
https://jira.berkeley.edu/browse/SISRP-27378
QA PR for #6672
> [QA] SISRP-27378 - moves url param replacement outside of cached model

- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-31677
See DEV PR #6678
> [QA] SISRP-31677 - Updates logic to allow link visibility for Advisors viewing as Students

- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_student_academics.json
- spec/models/my_academics/academic_plan_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/calcentral.scss
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academic_plan.html
This reverts commit 30c14486f6d78c424aa696dab23bfe670de140c5.
This update was added to the master branch during GL 8.1 development (#6600), and reverted from the GL 8.1 release candidate (#6607).
It remained in the master branch for GL 9.0 release. Now that this feature is being pushed to GL 9.2, this revert will ensure that it is not in the GL 9.0 release.
> [QA] Revert "SISRP-31634 - Dynamic Display of DB2 Archive Transcript Link"

- src/assets/templates/widgets/enrollment/haas/plan.html
https://jira.berkeley.edu/browse/SISRP-20513
> SISRP-20513 - Fixes Graduation Requirements link for EWMBA

- src/assets/templates/widgets/enrollment/haas/plan.html
https://jira.berkeley.edu/browse/SISRP-20513
See DEV PR #6684
> [QA] SISRP-20513 - Fixes Graduation Requirements link for EWMBA

- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-33088
Removes duplicated listing of Majors. See #6640
> SISRP-33088 - Major is displayed twice on the Profile card

- src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-33088
See DEV PR #6686
> [QA] SISRP-33088 - Major is displayed twice on the Profile card

- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-33408
User::Api tests were due for a makeover.  We'll no longer need to rely on real data from CS, EDO, or LDAP for these tests to run.  Fingers crossed that the tests will now pass on Bamboo.
> SISRP-33408 - Puts kibosh on db connections in User::Api tests

- src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-32471
This removes the work done for SISRP-32471 from the release candidate, leaving it in 'master' for GL 9.2 release.
Reverts ets-berkeley-edu/calcentral#6671
> Revert "[QA] SISRP-32471 - On SPRING enrollment card choose classes link navigates only for summer schedule"

- spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-33408
QA PR for #6689
> [QA] SISRP-33408 - Puts kibosh on db connections in User::Api tests

- src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-33364
* removed the misleading message with no registration
> SISRP-33364 - Status and Holds Remove inaccurate "not registered" message

- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-33696
> SISRP-33696 - JavaScript error on Student Overview page related to Transfer Credit

- src/assets/javascripts/angular/controllers/widgets/finaid/FinaidProfileController.js
https://jira.berkeley.edu/browse/SISRP-33381
> SISRP-33381 - Profile Card Default to Open

- src/assets/templates/academics_classinfo.html
- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-32578
* Fixes column sorting to the section number columns
* Adds column sorting to dates and locations on Section Overview
> SISRP-32578 - Instructor My Academics > Enrollment, sort not working for DIS column

- src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
https://jira.berkeley.edu/browse/SISRP-33780
* Fixed rounding on GPA
> SISRP-33780 - Admin Transcript GPA vs. Academic Summary GPA (INC0483601)

- src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js
- src/assets/javascripts/angular/services/linkService.js
https://jira.berkeley.edu/browse/SISRP-33544
Reverts changes applied in #6677 and #6699
> SISRP-33544 - Revert v2 CS Link Hack

- src/assets/javascripts/angular/directives/telPhoneInputDirective.js
- src/assets/templates/widgets/profile/emergency_phone_fields.html
https://jira.berkeley.edu/browse/SISRP-33914
> SISRP-33914 - Emergency Contacts - Phone is a Required Field

- src/assets/templates/widgets/higher_degree_faculty_committees.html
https://jira.berkeley.edu/browse/SISRP-34100
> SISRP-34100 - Links on Committees Card do not appear as links

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-33357
* change two links in campuslinks.json
> SISRP-33357 - Two broken links in My Campus (DNS and 404)

- app/models/my_registrations/registrations_module.rb
https://jira.berkeley.edu/browse/SISRP-34193
* Takes care of the JIRA, and makes the process a bit more efficient as well by removing CNP message processing if we are not showing the registration status.
> SISRP-34193 - For UCBX student there shouldn't be CNP message

- src/assets/stylesheets/_academic_summary.scss
- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-33640
Margins, paddings, and alignments.
> SISRP-33640 - Academic Summary: discrepancies of prd vs. design

- app/controllers/concerns/advising_resources.rb
- app/models/my_academics/class_enrollments.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_resources.json
- public/dummy/json/enrollment_instructions.json
- public/json/campuslinks.json
- spec/controllers/concerns/advising_resources_spec.rb
- spec/models/my_academics/class_enrollments_spec.rb
- src/assets/javascripts/angular/controllers/widgets/advising/advisingResourcesController.js
- src/assets/templates/widgets/enrollment/explore.html
https://jira.berkeley.edu/browse/SISRP-34234
> SISRP-34234 - Link to Cross-Campus Enrollment site in CalCentral

- app/models/clearing_house/my_clearing_house_url.rb
https://jira.berkeley.edu/browse/SISRP-34412
* Also need to update proxy URL in `yml` file.
> SISRP-34412 - Fix SSS to Clearing House for Enrollment Verification (SSL Protocol)

- src/assets/templates/widgets/higher_degree_faculty_committees.html
> [QA] SISRP-34100 - Links on Committees Card do not appear as links

- app/models/clearing_house/my_clearing_house_url.rb
https://jira.berkeley.edu/browse/SISRP-34412
QA PR of #6715
> [QA] SISRP-34412 - Fix SSS to Clearing House for Enrollment Verification (SSL Protocol)

- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_student_academics.json
- spec/models/my_academics/academic_plan_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_academic_plan.scss
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academic_plan.html
This reverts commit 30c14486f6d78c424aa696dab23bfe670de140c5, which was merged into 'master' branch during GL 8.1 development. It was reverted from the release candidate for GL 8.1, and also GL 9.0, because dependencies were not ready for this feature to be released.
I've decided to revert this in GL 9.2, as it yet again was pushed to GL 9.3. I will make a PR to bring it into the code once again when it appears certain that dependencies are ready.
> SISRP-31634 - Revert "Dynamic Display of DB2 Archive Transcript Link"

- app/models/my_academics/academic_plan.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/advising_student_academics.json
- spec/models/my_academics/academic_plan_spec.rb
- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/stylesheets/_academic_plan.scss
- src/assets/templates/user_overview.html
- src/assets/templates/widgets/academic_plan.html
This reverts commit 30c14486f6d78c424aa696dab23bfe670de140c5
See DEV PR #6716
> [QA] SISRP-31634 - Revert "Dynamic Display of DB2 Archive Transcript Link"

- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-33640
* QA PR of #6721
> [QA] SISRP-33640 - Academic Summary: discrepancies of prd vs. design

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-34455
* Behold the power of a `=`
> SISRP-34455 - GPA trend graph is missing on Student success card

- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/student_resources.json
- src/assets/stylesheets/_icons.scss
- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-34089
> SISRP-34089 - Place link to training page for eForms: committees

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-34455
* Behold, once again, the power of `=`
* QA PR of #6723
> [QA] SISRP-34455 - GPA trend graph is missing on Student success card

- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/student_resources.json
- src/assets/stylesheets/_icons.scss
- src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-34089
See DEV PR #6725
> [QA] SISRP-34089 - Place link to training page for eForms: committees

- app/models/berkeley/academic_roles.rb
> [QA] SISRP-31635 - adds 'grad' to enrollment roles

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
* fix bug introduced by PR #6703 
* Status title was not being added under $watch
> SISRP-33364 - Status and Holds Remove inaccurate 'not registered' message

- src/assets/javascripts/angular/controllers/pages/userOverviewController.js
- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
> [QA] SISRP-33364 - Status and Holds Remove inaccurate 'not registered' message

- public/maintenance/index_maintenance.html
https://jira.berkeley.edu/browse/SISRP-34288
* change maintenace page for long 4 day outage.
> SISRP-34288 - 9.2 Outage - CalCentral Maintenance Page

- public/maintenance/index_maintenance.html
> [QA] SISRP-34288 - 9.2 Outage - CalCentral Maintenance Page

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-34259
* fix broken link
> SISRP-34259 - Broken link on My Campus > Academic Planning > Class Enrollment Rules and Guides

- app/models/student_success/outstanding_balance.rb
- spec/models/student_success/oustanding_balance_spec.rb
- src/assets/templates/widgets/student_success/finances.html
https://jira.berkeley.edu/browse/SISRP-34486
* CS gives us ugly strings, we turn them into numbers, and let the front-end deal with it.
> SISRP-34486 - Student success card display needs to display correct negative amount format

- app/models/student_success/outstanding_balance.rb
- spec/models/student_success/oustanding_balance_spec.rb
- src/assets/templates/widgets/student_success/finances.html
https://jira.berkeley.edu/browse/SISRP-34486
QA PR of #6738
> [QA] SISRP-34486 - Student success card display needs to display correct negative amount format

- public/json/campuslinks.json
> [QA] SISRP-34259 - Broken link on My Campus > Academic Planning > Class Enrollment Rules and Guides

- app/models/degree_progress/my_graduate_milestones.rb
- app/models/my_committees/committees_module.rb
- app/models/my_committees/student_committees.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/degree_progress_grad.json
- spec/models/degree_progress/my_graduate_milestones_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/widgets/academics/degree_progress_graduate.html
- src/assets/templates/widgets/higher_degree_committees.html
https://jira.berkeley.edu/browse/SISRP-30410
> SISRP-30410 - Remove Links from Degree Progress and Higher Degree Committees Card

- app/models/degree_progress/my_graduate_milestones.rb
- app/models/my_committees/committees_module.rb
- app/models/my_committees/student_committees.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- public/dummy/json/degree_progress_grad.json
- spec/models/degree_progress/my_graduate_milestones_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js
- src/assets/templates/widgets/academics/degree_progress_graduate.html
- src/assets/templates/widgets/higher_degree_committees.html
https://jira.berkeley.edu/browse/SISRP-30410
See DEV PR #6740
> [QA] SISRP-30410 - Remove Links from Degree Progress and Higher Degree Committees Card

- src/assets/templates/widgets/enrollment/adjust.html
> [QA] SISRP-31635 - allows grad students who have a plan-based role to see Late Add/Drop link

- public/maintenance/index_maintenance.html
https://jira.berkeley.edu/browse/SISRP-34568
Reverts changes made in #6732, also modifies CSS styles to use alphabetical order.
> SISRP-34568 - Revert maintenance pages to original content

- lib/memcached.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6665
> CLC-6665 Try to avoid corruption of memcached diagnostic messages

- config/deploy.rb
- config/settings/server_config.rb
https://jira.berkeley.edu/browse/SISRP-34776
I tested this script fix on Junction's test server, which is now running the latest Master branch.
> SISRP-34776 Fix Bamboo deployment support for JRuby 2

- app/controllers/application_controller.rb
- spec/controllers/config_controller_spec.rb
- src/assets/javascripts/angular/services/analyticsService.js
https://jira.berkeley.edu/browse/SISRP-33547
> SISRP-33547 - Disable Google Analytics tracking in Local, Dev, and QA environments

- db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6714
Whitespace: can't live with it, can't live without it.
> CLC-6714 Prefer "L & S" to "L&S" as an OEC department name

- app/models/degree_progress/milestones_module.rb
> [QA] SISRP-34908 - Handle milestone attempts only for QE Results

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-24196
* delete link
> My Campus > Academic Planning - Remove DARS Link

- public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-24161
* remove old link
> My Campus > Academic Planning - Edit Links (GL7.0)

- .travis.yml
- Dockerfile
- README.md
Thanks @davidlimcheng for pointing out that the Travis config needs to be updated to use the new JRuby.
> SISRP-26133 - Brings jruby upgrade to Travis, Docker, and README

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-35076
> SISRP-35076 - Update Roster feed to display greatest value for Terms in Attendance

- .travis.yml
- app/models/my_academics/academics_module.rb
- app/models/my_academics/college_and_level.rb
- fixtures/json/hub_academic_status.json
- spec/controllers/campus_solutions/advising_resources_controller_spec.rb
- spec/models/my_academics/academics_module_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- spec/models/user/api_spec.rb
- src/assets/javascripts/angular/controllers/pages/academicSummaryController.js
- src/assets/stylesheets/_academic_summary.scss
- src/assets/stylesheets/_profile.scss
- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
- src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
- src/assets/templates/widgets/academics/degrees_conferred.html
https://jira.berkeley.edu/browse/SISRP-32543
This PR satisfies the following requirement, does a little CSS refactoring, and removes some unrelated debug/log statements that appear to have been accidentally left in.
- Academic Summary page:  on each term, surface "Deans List" and/or "Honors to Date" awards if they were awarded during that term
> SISRP-32543 - Surfaces term honors on Academic Summary

- script/bamboo-tests.sh
Follow-up to https://github.com/ets-berkeley-edu/calcentral/pull/6776
> CLC-6719 Fix typo in script path

- script/bamboo-tests.sh
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/6780 (after validating the master build on Bamboo)
> QA CLC-6719 Fix typo in script path

- fixtures/json/hub_academic_status.json
- src/assets/stylesheets/_academic_summary.scss
- src/assets/templates/widgets/academics/degrees_conferred.html
https://jira.berkeley.edu/browse/SISRP-32543
Degree honors are attached to a conferred degree.  They will be displayed everywhere a conferred degree is displayed - Profile card and Academic Summary.
> SISRP-32543 - Surfaces degree honors

- fixtures/json/hub_academic_status.json
- src/assets/stylesheets/_academic_summary.scss
- src/assets/templates/widgets/academics/degrees_conferred.html
> [QA] SISRP-32543 - Surfaces degree honors

- Gemfile
- Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-29026
> [QA] SISRP-29026 - Upgrades jruby-openssl to the latest.

- .rvmrc
- .travis.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- app/models/my_academics/college_and_level.rb
- script/update-build.sh
> [QA] SISRP-26133 - Downgrades jruby and jruby-openssl

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-35281
> SISRP-35281 - Enrollment: Section Overview and Wait List Open numbers do not match

- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-34230
> SISRP-34230 - Fix logic for hiding adjusted credits when same as total

- script/build-torquebox.sh
> [QA] Adds GEMSET param to build-torquebox script

- src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html
- src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-34230
> [QA] SISRP-34230 - Fix logic for hiding adjusted credits when same as total

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
- src/assets/templates/directives/academics_class_info_enrollment.html
https://jira.berkeley.edu/browse/SISRP-35281
See DEV PR #6792
> [QA] SISRP-35281 - Enrollment: Section Overview and Wait List Open numbers do not match

- db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6720
Plus COG SCI has transferred to the IAS team.
(All changes have already been made on all Junction clusters; this PR is just by way of documentation & dev environment maintenance.)
> CLC-6720 OEC adding Social Welfare, various International & Area Studies

- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/templates/academics_enrollment_verification.html
https://jira.berkeley.edu/browse/SISRP-35206
> SISRP-35206 - Enrollment Verification page accessible to users without academic history

- app/models/canvas_csv/site_memberships_maintainer.rb
- spec/models/canvas_csv/site_memberships_maintainer_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6459
> CLC-6459 Map Administrative Proxy role to Lead TA in bCourses

- src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6725
> CLC-6725 Require Site Abbreviation (aka short_name) when creating a course site

- app/models/canvas/account_roles.rb
- app/models/canvas_csv/provide_course_site.rb
- app/models/canvas_lti/course_add_user.rb
- spec/models/canvas_csv/provide_course_site_spec.rb
- spec/models/canvas_lti/course_add_user_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6459
I've said this before, but this sprawling code desperately needs refactoring.
However, the refactor's not going to happen this week. (I've said that before, too.)
> CLC-6459 Add Proxy to their course site as a Lead TA

- app/models/my_academics/academic_plan.rb
- src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-35516
> SISRP-35516 - Bug in Prod: Waitlisted Classes appearing as Enrolled on Academic Plan Card

- app/models/campus_solutions/degree_progress/undergrad_requirements_expiry.rb
https://jira.berkeley.edu/browse/SISRP-35349
> SISRP-35349 - extends the UGRD degree progress ENF to the student-facing card

- db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6743
> CLC-6743 Graduate Division joins OEC

- app/models/berkeley/academic_roles.rb
- app/models/degree_progress/my_undergrad_requirements.rb
- app/models/degree_progress/requirements_module.rb
- app/models/degree_progress/undergrad_requirements.rb
- app/models/hub_edos/my_academic_status.rb
- fixtures/xml/campus_solutions/link_api_multiple.xml
- spec/models/berkeley/academic_roles_spec.rb
- spec/models/degree_progress/my_undergrad_requirements_spec.rb
- spec/models/hub_edos/my_academic_status_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/javascripts/angular/controllers/widgets/academics/undergraduateDegreeProgressController.js
- src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-34910
Advisors already have the link to run the APR.  We are adding a student-specific version of that link that will only show to students who are active in the UCLS program.
> SISRP-34910 - Surfaces APR link to UCLS students on Ugrd Degree Progress

- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-35467
* simple change for grading option to grading basis
> SISRP-35467 CalCentral displaying letter grading option for all P/NP classes, correct in BCS

- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-35907
> SISRP-35907 - Update Grading Tab to Link to Term page

- app/models/edo_oracle/queries.rb
- app/models/my_academics/academic_plan.rb
- app/models/my_academics/semesters.rb
- spec/models/my_academics/semesters_spec.rb
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_semesters.html
- src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-35201
* Add filing Fee and Absentia status to semesters and acad planning cards.
> SISRP-35201 Add Filing Fee and In Absentia statuses to Cal Central Cards

- src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-34910
Simple text update.
> SISRP-34910 - Changes text around student-facing APR link

- db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6746
> CLC-6746 Make OEC accept "BIC" as a department form name

- script/local/start-torquebox.sh
https://jira.berkeley.edu/browse/SISRP-35822
This is just a script for developers to use to run Torquebox locally. It has no affect on any functionality in production.
> SISRP-35822 - Document / Develop formal Tsung and VisualVM Approach

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-35360
> SISRP-35360 - Update SISEDO queries to return term specific course title

- src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-34910
> SISRP-34910 - Updates text and adds static links

- src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-34910
QA PR for #6838
> [QA] SISRP-34910 - Updates text and adds static links

- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-36337
> SISRP-36337 - Academic Summary Page is showing a blank row for one of the term under Enrollment

- src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
> [QA] SISRP-36337 - Academic Summary Page is showing a blank row for one of the term under Enrollment

- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/templates/california_residency_status.html
https://jira.berkeley.edu/browse/SISRP-36436
* remove unused spinner.
> SISRP-36436 - Residency data is not loading in calcentral

- src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
- src/assets/templates/california_residency_status.html
> [QA] SISRP-36436 - Residency data is not loading in calcentral

- src/assets/javascripts/angular/controllers/widgets/taskAdderController.js
https://jira.berkeley.edu/browse/SISRP-36479
New task was not being displayed after it was added.
> SISRP-36479 - Fixes Tasks card add task bug

- README.md
https://jira.berkeley.edu/browse/SISRP-36339
> SISRP-36339 - Updates README for the modern era

- app/models/oec/task.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6751
> CLC-6751 Tighten regexp for OEC semester migration

- Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-31448
> SISRP-31448 - Upgrades font-awesome gem to match front-end dependency

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-36576
> SISRP-36576 - Hide grading link from non instructors or GSIs

- app/models/canvas/course_policy.rb
- app/models/canvas/course_user.rb
- spec/models/canvas/course_policy_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6747
> CLC-6747 bCourses administrative proxy can edit Official Sections

- app/models/berkeley/academic_roles.rb
- app/models/hub_edos/my_academic_status.rb
- spec/models/hub_edos/my_academic_status_spec.rb
https://jira.berkeley.edu/browse/SISRP-36566
This is a proxy that provides parsed data. I think we want to make this fault tolerant, so that it fails gracefully, especially due to other cards relying on the data it provides.
> SISRP-36566 - Enrollment Card and Student Status Not Displaying In Card

- src/assets/templates/finaid.html
https://jira.berkeley.edu/browse/SISRP-32575
> SISRP-32575 - Calentral FA Cards do not show for new Transfer students if enrolled in Summer w/non-degree plan

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-35360
See DEV PRs - #6837 and #6865
> [QA] SISRP-35360 - Update SISEDO queries to return term specific course title

- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-36576
See #6857 for equivalent 'master' PR
> [QA] SISRP-36576 - Hide grading link from non instructors or GSIs

- app/models/berkeley/academic_roles.rb
- app/models/hub_edos/my_academic_status.rb
- spec/models/hub_edos/my_academic_status_spec.rb
https://jira.berkeley.edu/browse/SISRP-36566
https://jira.berkeley.edu/browse/SISRP-36577
See DEV PR #6860
> [QA] SISRP-36577 - CalCentral missing class enrollment card for UCBX UGRD students

- app/models/my_registrations/registrations_module.rb
https://jira.berkeley.edu/browse/SISRP-36739
* This doesn't fix the bug, but it's a necessary part of the fix.
* That's my old code that failed.  And it's so inefficient!
> SISRP-36739 - Academic summary card doesn't load for students active in UCBX and UGRD careers

- app/models/canvas_csv/lti_usage_reporter.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6759
> CLC-6759 Work around inefficient Google Sheets wrapper

- public/dummy/json/torquebox_status.json
https://jira.berkeley.edu/browse/SISRP-36683
* Updates dummy feed for torquebox-stats endpoint to remove mentions of LiveUpdates and HotPlate statuses.  Taken from cc-dev.
> SISRP-36683 - Update torquebox_stats.json

- src/assets/javascripts/angular/controllers/pages/enrollmentVerificationController.js
- src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
- src/assets/templates/widgets/academics/enrollment_verification.html
- src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-36611
In my refactoring of the academic-status feed, I inadvertently broke the loading spinners on a couple of the cards.
> SISRP-36611 - Fixes spinner issues

- src/assets/templates/widgets/enrollment/decide.html
> SISRP-37144- UX Design: Show time zone information for enrollment phases

- app/models/hub_edos/contacts.rb
- fixtures/json/hub_contacts.json
- spec/models/hub_edos/contacts_spec.rb
https://jira.berkeley.edu/browse/SISRP-37100
> SISRP-37100 - CalCentral Pulling in Inactive Addresses

- src/assets/templates/widgets/enrollment/haas/notifications.html
https://jira.berkeley.edu/browse/SISRP-37225
> SISRP-37225 - Typo - enrollment card link label for FT MBAs Ofice (link OK)

- app/models/my_groups/callink.rb
- src/assets/templates/widgets/my_groups.html
https://jira.berkeley.edu/browse/SISRP-37237
> SISRP-37237 - Removes extraneous hard-coded 'https' from URLs

- src/assets/javascripts/angular/directives/academicsClassInfoEnrollmentDirective.js
https://jira.berkeley.edu/browse/SISRP-29924
> SISRP-29924 - Faculty enrollment drop request does not differentiate section #s

- app/models/my_academics/college_and_level.rb
- fixtures/json/hub_academic_status.json
- spec/models/hub_edos/academic_status_spec.rb
- spec/models/my_academics/college_and_level_spec.rb
- src/assets/images/svg/icon-ribbon.svg
- src/assets/stylesheets/_degrees_conferred.scss
- src/assets/stylesheets/_icons.scss
- src/assets/stylesheets/_profile.scss
- src/assets/stylesheets/calcentral.scss
- src/assets/stylesheets/colors.scss
- src/assets/templates/widgets/academics/degrees_conferred.html
https://jira.berkeley.edu/browse/SISRP-30118
New degrees conferred data is available in the academic-status API. We'll now display the names of majors and certificates correctly, and surface the college name, designated emphasis, and any minors. Also adds an icon for each degree.
> SISRP-30118 - Updates Degrees Conferred with newly available data

- config/settings/test.yml
- config/settings/testext.yml
- spec/models/calnet_ldap/client_spec.rb
https://jira.berkeley.edu/browse/SISRP-37276
> SISRP-37276 - Update LDAP Test Server Proxy

- app/models/edo_oracle/queries.rb
- app/models/edo_oracle/user_courses/base.rb
- src/assets/javascripts/angular/controllers/pages/academicsController.js
- src/assets/javascripts/angular/services/academicsService.js
- src/assets/stylesheets/_academics.scss
- src/assets/templates/academics_classinfo.html
- src/assets/templates/academics_gpa.html
- src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-33947
> SISRP-33947 - PhysEd Classes page missing Course Topic ID and Descr. - can't differentiate topic being taught

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-37310
https://jira.berkeley.edu/browse/SISRP-37248
> SISRP-37310 - Update course record selection sub-query to use last chronological record within term period

- app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-37310
https://jira.berkeley.edu/browse/SISRP-37248
See DEV PR #6894
> [QA] SISRP-37310 - Update course record selection sub-query to use last chronological record within term period

- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/academics_classinfo.html
https://jira.berkeley.edu/browse/SISRP-37460
Also fixes an issue with the logic that determines hiding or showing the Textbooks card.
> SISRP-37460 - Fixes Textbooks card infinite spinner

- src/assets/javascripts/angular/services/academicsService.js
- src/assets/templates/academics_classinfo.html
QA PR for #6899 
https://jira.berkeley.edu/browse/SISRP-37460
> [QA] SISRP-37460 - Fixes Textbooks card infinite spinner

- app/models/student_success/term_gpa.rb
- spec/models/student_success/term_gpa_spec.rb
https://jira.berkeley.edu/browse/SISRP-37409
> SISRP-37409 - Fixes string compare bug suppressing Student Success card

- app/models/student_success/term_gpa.rb
- spec/models/student_success/term_gpa_spec.rb
QA PR for #6902 
https://jira.berkeley.edu/browse/SISRP-37409
> [QA] SISRP-37409 - Fixes string compare bug suppressing Student Success card

- app/models/my_academics/class_enrollments.rb
- spec/models/my_academics/class_enrollments_spec.rb
- src/assets/templates/widgets/enrollment/decide.html
> SISRP-37144 - Surface timezone offset and render with provided offset
