ets-berkeley-edu/junction

app/models/my_academics/class_enrollments.rb, spec/models/my_academics/class_enrollments_spec.rb, src/assets/templates/widgets/enrollment/decide.html
=> [QA] SISRP-37144 - Surface timezone offset and render with provided offset

app/models/my_academics/class_enrollments.rb, spec/models/my_academics/class_enrollments_spec.rb, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment/haas/explore.html, src/assets/templates/widgets/enrollment/haas/plan.html, src/assets/templates/widgets/enrollment/plan.html, src/assets/templates/widgets/enrollment/schedule.html
=> SISRP-37144 - Adds timezone offset for schedule of classes period. Updates times displayed in Class Enrollment sections

app/models/my_academics/class_enrollments.rb, spec/models/my_academics/class_enrollments_spec.rb, src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/explore.html, src/assets/templates/widgets/enrollment/haas/explore.html, src/assets/templates/widgets/enrollment/haas/plan.html, src/assets/templates/widgets/enrollment/plan.html, src/assets/templates/widgets/enrollment/schedule.html
=> [QA] SISRP-37144 - Adds timezone offset for schedule of classes period. Updates times displayed in Class Enrollment sections

src/assets/templates/widgets/enrollment/decide.html
=> SISRP-37144 - Apply offset to day in decide template

src/assets/javascripts/angular/controllers/widgets/myClassesController.js
https://jira.berkeley.edu/browse/SISRP-37548
See QA PR #6911
=> SISRP-37548 - My Classes card not displaying content

src/assets/javascripts/angular/controllers/widgets/myClassesController.js
https://jira.berkeley.edu/browse/SISRP-37548
=> [QA] SISRP-37548 - My Classes card not displaying content

app/models/canvas_csv/maintain_users.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6777
This should eliminate a sometimes painful timing conflict between the two stages of our occasional user account inactivation.
=> CLC-6777 Separate bCourses email deletion from user inactivation

app/models/canvas/communication_channels.rb, app/models/canvas_csv/maintain_users.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6785
Let's hope these comments are loud enough to do the job...
=> CLC-6777 Document bCourses email deletion dependency on settings change

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6780
Also works for the current production release.
=> CLC-6780 Fix Canvas Add People customizations on Beta

src/assets/javascripts/angular/services/userService.js, src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-37569
=> SISRP-37569 - New Admit UX Dev: My Dashboard Page States

src/assets/stylesheets/_icons.scss, src/assets/templates/widgets/billing_summary.html
https://jira.berkeley.edu/browse/SISRP-37812
* Fixes issue with living styleguide (run `gulp styleguide`)
* Updates Billing Summary 'Details' link as 'View Account Details' button
=> SISRP-37812 - New Admit UX Dev: Billing Summary card

public/json/campuslinks.json, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-31258
* Hides 'Withdrawing or Canceling?' link and the 'Leaving Cal?' section it displays under from the Financial Resources card (on My Finances page) for Summer visitors.
=> SISRP-31258 - Edits to Financial Resources Card text for Summer Sessions

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-31124
=> SISRP-31124 - Financial Resources card - typo, Student Advocates Office -> Student Advocate's Office

app/models/campus_solutions/financial_aid_data_housing_segregator.rb, app/models/campus_solutions/my_financial_aid_data.rb, fixtures/xml/campus_solutions/financial_aid_data.xml, spec/models/campus_solutions/financial_aid_data_housing_segregator_spec.rb, spec/models/campus_solutions/my_financial_aid_filtered_for_advisor_spec.rb, spec/models/campus_solutions/my_financial_aid_filtered_for_delegate_spec.rb
https://jira.berkeley.edu/browse/SISRP-37579
=> SISRP-37579 - New Admit UX Dev: Financial Aid & Scholarships Profile card updates

app/models/campus_solutions/sir/sir_statuses.rb, app/models/edo_oracle/queries.rb, spec/models/campus_solutions/sir/sir_statuses_spec.rb
Dependency for both @redconfetti  and mine's work under [SISRP-37480](https://jira.berkeley.edu/browse/SISRP-37480).  I pulled this branch from @redconfetti's repo, so it'll be under his JIRA.
JIRA: https://jira.berkeley.edu/browse/SISRP-37580
=> SISRP-37580 - Updates CampusSolutions::Sir::SirStatuses to include new admit status roles

src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-37993
=> SISRP-37993 - enrollment card - revised summer language for non-Law students

spec/models/campus_solutions/sir/sir_statuses_spec.rb, src/assets/templates/dashboard.html
https://jira.berkeley.edu/browse/SISRP-37567
* Clean-up from earlier PR (thanks @lyttam)
=> SISRP-37567 - New Admit UX Dev: My Dashboard - SIR card Updates (Clean-Up)

config/settings.yml, src/assets/javascripts/angular/controllers/widgets/finaid/finaidSummaryController.js, src/assets/stylesheets/_finaid_summary.scss, src/assets/templates/widgets/finaid_summary.html, src/assets/templates/widgets/finaid_summary_aidyear.html, src/assets/templates/widgets/finaid_summary_footer.html, src/assets/templates/widgets/finaid_summary_netcost.html
Dev JIRA: https://jira.berkeley.edu/browse/SISRP-37574
Design JIRA: https://jira.berkeley.edu/browse/SISRP-36597
* Feature flags can be removed in a couple of cycles, when the changes have stabilized in prod
* Adds some minor features to the Finaid Summary card, adding links and incomplete tasks count
=> SISRP-37574 - New Admit UX Dev: Financial Aid and Scholarships Summary card updates

app/models/campus_solutions/financial_aid_housing.rb, app/models/campus_solutions/message_catalog.rb, app/models/campus_solutions/my_financial_aid_data.rb, app/models/edo_oracle/queries.rb, spec/models/campus_solutions/financial_aid_housing_spec.rb, spec/models/campus_solutions/message_catalog_spec.rb, spec/models/campus_solutions/my_financial_aid_data_spec.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidHousingController.js, src/assets/stylesheets/_finaid_housing.scss, src/assets/stylesheets/calcentral.scss, src/assets/templates/finaid.html, src/assets/templates/widgets/finaid_housing.html
https://jira.berkeley.edu/browse/SISRP-37580
=> SISRP-37580 - New Admit UX Dev: Financial Aid Housing card

.travis.yml, package.json, src/assets/javascripts/angular/controllers/widgets/finaid/finaidHousingController.js, src/assets/templates/widgets/finaid_housing.html
https://jira.berkeley.edu/browse/SISRP-38173
=> SISRP-38173 - Housing update - First year pathways link missing banner parameters

.travis.yml, package.json
https://jira.berkeley.edu/browse/SISRP-38239
=> SISRP-38239 - UX Dev: Upgrade NodeJS across environments

app/models/campus_solutions/new_admit_resources.rb, spec/models/campus_solutions/new_admit_resources_spec.rb
https://jira.berkeley.edu/browse/SISRP-38213
Forgot to add a link...D'oh
=> SISRP-38213 - Undergraduate Admissions Update Form link is missing under Admissions changes section on New Admit Resource card

src/assets/javascripts/angular/controllers/widgets/finaid/finaidHousingController.js, src/assets/templates/widgets/finaid_housing.html
https://jira.berkeley.edu/browse/SISRP-38173
See 'master' PR in #6944
=> [QA] SISRP-38173 - Housing update - First year pathways link missing banner parameters

src/assets/templates/widgets/finaid_profile.html
https://jira.berkeley.edu/browse/SISRP-38231
=> SISRP-38231 - EFC amount need a Dollar amount$) and decimal value on the Profile card on FA page

app/models/campus_solutions/new_admit_resources.rb, spec/models/campus_solutions/new_admit_resources_spec.rb
https://jira.berkeley.edu/browse/SISRP-38213
QA PR of #6948
=> [QA] SISRP-38213 - Undergraduate Admissions Update Form link is missing under Admissions changes section on New Admit Resource card

app/models/notifications/sis_expiry_processor.rb
https://jira.berkeley.edu/browse/SISRP-38220
QA PR of #6952
=> [QA] SISRP-38220 - Pay Deposit button stays even after a deposit is paid and it takes few minute to show confirmation message to student

src/assets/templates/directives/expandable_link_list.html, src/assets/templates/widgets/new_admit_resources.html
https://jira.berkeley.edu/browse/SISRP-38216
* Replaces manual link attribute binding with ccCampusSolutionsLinkDirective
=> SISRP-38216 - Hoover over text for First-Year Pathways link is incorrect

src/assets/templates/directives/expandable_link_list.html, src/assets/templates/widgets/new_admit_resources.html
https://jira.berkeley.edu/browse/SISRP-38216
See 'master' PR in #6955
=> [QA] SISRP-38216 - Hoover over text for First-Year Pathways link is incorrect

app/models/campus_solutions/new_admit_resources.rb
https://jira.berkeley.edu/browse/SISRP-38064
QA PR of #6956
=> [QA] SISRP-38064 - New Resources Card  -> Financial Aid & Scholarships section links aren't in order as per design

app/models/campus_solutions/sir/sir_statuses.rb
https://jira.berkeley.edu/browse/SISRP-38240
* Needed to open up the definition of a "Completed" checklist item for undergraduates, and rearrange the order of processing so that Deposit data is available for undergraduate attribute processing.
=> SISRP-38240 - Conditions of Admission and First-Year Pathway links are missing on the Offer Accepted Confirmation card

app/models/campus_solutions/sir/sir_statuses.rb
https://jira.berkeley.edu/browse/SISRP-38240
QA PR of #6961
=> [QA] SISRP-38240 - Conditions of Admission and First-Year Pathway links are missing on the Offer Accepted Confirmation card

public/json/campuslinks.json, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-38100
=> SISRP-38100 - Edits to financial links for Summer Sessions

public/json/campuslinks.json, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-38100
See #6963 for master branch PR
=> [QA] SISRP-38100 - Edits to financial links for Summer Sessions

src/assets/javascripts/angular/controllers/widgets/sir/sirController.js
https://jira.berkeley.edu/browse/SISRP-38314
* The function has "isUndergraduate" in its name, yet I still forget to add an `isUndergraduate` check =|
=> SISRP-38314 - Hass student NOT seeing SIR confirmation text after accepting offer

src/assets/javascripts/angular/controllers/widgets/sir/sirController.js
https://jira.berkeley.edu/browse/SISRP-38314
QA PR of #6967
=> [QA] SISRP-38314 - Hass student NOT seeing SIR confirmation text after accepting offer

app/models/canvas/course_user.rb, fixtures/json/canvas_course_user.json
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/6965
=> CLC-6803 Work around new bug in Canvas Course User API

app/models/campus_solutions/new_admit_resources.rb, app/models/campus_solutions/sir/sir_statuses.rb, src/assets/templates/widgets/sir/sir_item_completed.html
https://jira.berkeley.edu/browse/SISRP-38329
* Requirements said to look at `athlete` status, but this was identified as incorrect during QA process
* Also adds some text to the COA link on the SIR Confirmation page
=> SISRP-38329 - Conditions of Admissions link needs to be fixed for Transfer student on SIR confirmation card and on the New Admit Resource card

app/models/campus_solutions/new_admit_resources.rb, app/models/campus_solutions/sir/sir_statuses.rb, src/assets/templates/widgets/sir/sir_item_completed.html
https://jira.berkeley.edu/browse/SISRP-38329
QA PR of #6969
=> [QA] SISRP-38329 - Conditions of Admissions link needs to be fixed for Transfer student on SIR confirmation card and on the New Admit Resource card

src/assets/templates/widgets/new_admit_resources.html
https://jira.berkeley.edu/browse/SISRP-38355
QA PR of #6971
=> [QA] SISRP-38355 - Error navigating back to calcentral from 'Add a Withdrawal request' efrom from New Admit Resource card

src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-38359
=> SISRP-38359 - Pluralizes and colorizes finaid tasks

src/assets/templates/widgets/finaid_summary.html
QA PR for #6973 
https://jira.berkeley.edu/browse/SISRP-38359
=> [QA] SISRP-38359 - Pluralizes and colorizes finaid tasks

app/models/my_academics/gpa_units.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/my_academics/gpa_units_spec.rb
https://jira.berkeley.edu/browse/SISRP-36883
=> SISRP-36883 - Check for nil params being passed to EDODB queries

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6800
=> CLC-6800 LAW & LEGALST are no longer enabled for OEC

app/models/edo_oracle/adapters/oec.rb, app/models/edo_oracle/oec.rb, spec/models/edo_oracle/adapters/oec_spec.rb, spec/models/edo_oracle/oec_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6668
The code could be refactored, but leveraging what was already there makes the development job faster and safer. In this case, I chose to err on the side of expediency. Reviewers should feel free to push back if they disagree.
=> CLC-6773 CLC-6668 Switch OEC's source for person name & email

src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js, src/assets/templates/widgets/my_advising.html
https://jira.berkeley.edu/browse/SISRP-38178
This will go in an ER.  I will submit a QA PR once I verify in cc-dev that the fix worked.
=> SISRP-38178 - Fixes race condition on Advising card

src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js
https://jira.berkeley.edu/browse/SISRP-38178
My previous PR #6983 didn't go far enough, so this is a follow-up.  The Advising card was loading before the page-level controller (`userOverviewController`) was finished fetching the student's academic roles.  I added an explicit call to get the roles when the card is being viewed by the student's advisor.
=> SISRP-38178 - Provides missing academic roles to advisor-facing Advising card

src/assets/javascripts/angular/controllers/widgets/sir/sirController.js
https://jira.berkeley.edu/browse/SISRP-38311
=> SISRP-38311 - LAW SIR card is showing multiple confirmation messages after SIR complete

src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js, src/assets/templates/widgets/my_advising.html
QA PR encompassing these two master PRs:
#6983 
#6984 
Slated for 2/14 ER
=> [QA] SISRP-38178 - Fixes race condition on Advising card

app/controllers/campus_solutions/email_controller.rb, app/models/campus_solutions/email.rb, app/models/campus_solutions/user_api_updating_model.rb, spec/controllers/campus_solutions/email_controller_spec.rb, spec/models/campus_solutions/email_spec.rb, src/assets/javascripts/angular/controllers/widgets/profile/profileAddressController.js, src/assets/javascripts/angular/controllers/widgets/profile/profileEmailController.js, src/assets/javascripts/angular/services/profileService.js
https://jira.berkeley.edu/browse/SISRP-38230
Also includes some refactoring of the JavaScript response handlers at @davidlimcheng's request
=> SISRP-38230 - Adds validation to email address update

src/assets/templates/widgets/finaid_profile.html
https://jira.berkeley.edu/browse/SISRP-38433
=> SISRP-38433 - Family member in college is not a Monetary value

src/assets/javascripts/angular/controllers/widgets/myAdvisingController.js, src/assets/templates/widgets/my_advising.html
Reverts ets-berkeley-edu/calcentral#6988
This was originally planned for a pre-3/18 minor release, but instead we are going to wait until 3/18 to release it.
The corresponding master PR (#6983) will stay put.
=> Revert "[QA] SISRP-38178 - Fixes race condition on Advising card"

src/assets/templates/academics_gpa.html
https://jira.berkeley.edu/browse/SISRP-38682
=> SISRP-38682 - Remove GPA Estimator from CalCentral and place message in CLC to students

app/controllers/advising_student_controller.rb, config/routes.rb, public/dummy/json/advising_committees.json, src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/javascripts/angular/controllers/widgets/academicsHigherDegreeCommitteesController.js, src/assets/javascripts/angular/factories/advisingFactory.js, src/assets/javascripts/angular/services/committeesService.js, src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-38681
* Brings Committees to Advisors
* Reorders some stuff that wasn't alphabetical
* User Overview, like so many other things, is in dire need of a refactor
=> SISRP-38681 - Show Committee Card in Adviser Dashboard - UX Development

src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/templates/widgets/finaid_summary.html
https://jira.berkeley.edu/browse/SISRP-38686
=> SISRP-38686 - FinAId Title IV Response Page in CalCentral should NOT be Aid Year Specific

app/models/berkeley/degree_progress_undergrad.rb, app/models/degree_progress/requirements_module.rb, app/models/edo_oracle/queries.rb, spec/models/berkeley/degree_progress_undergrad_spec.rb, spec/support/degree_progress_shared_examples.rb, src/assets/stylesheets/_icons.scss, src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-37998
Establishes a grace period for new admits during which their incomplete requirements appear as "Under Review".  This accounts for the time it takes Transfer Credit to process their incoming credits (which may satisfy some of their requirements).
The grace period is different for each term:
- Fall grace period ends 60 days into the term
- Spring grace period ends 30 days into the term
- Summer grace period ends 60 days after the term ends
=> SISRP-37998 - Creates 'under review' status for new admit degree progress

app/models/degree_progress/requirements_module.rb, spec/support/degree_progress_shared_examples.rb, src/assets/javascripts/angular/controllers/widgets/academics/undergraduateDegreeProgressController.js, src/assets/stylesheets/_degree_progress.scss, src/assets/stylesheets/_icons.scss, src/assets/templates/widgets/academics/degree_progress_undergrad.html, src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-37998
This PR is a follow-up to #7008 
Only the new admits that see the special "Under Review" status should see the help icon and the information explaining the status (which includes the transfer credit review date).
=> SISRP-37998 - Surfaces transfer credit review date for new admits

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-39127
=> SISRP-39127 - Update CalCentral roster queries to use STUDENT_GROUPV01_VW

app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6823
Following on SISRP-38835, SISRP-39127, https://github.com/ets-berkeley-edu/calcentral/pull/7017
=> CLC-6823 Deal with SIS removal of EDO DB view for v97

app/models/campus_solutions/sir/sir_statuses.rb, spec/models/campus_solutions/sir/sir_statuses_spec.rb
https://jira.berkeley.edu/browse/SISRP-38975
QA PR for #7016
=> [QA] SISRP-38975 - fixes error preventing SIR and New Admit cards from loading

src/assets/javascripts/angular/controllers/widgets/tasksController.js, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39154
https://jira.berkeley.edu/browse/SISRP-39155
See QA PR #7022
=> SISRP-39154 / SISRP-39155 - Task Card bugs

src/assets/javascripts/angular/controllers/widgets/tasksController.js, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39154
https://jira.berkeley.edu/browse/SISRP-39155
See DEV PR #7021
=> [QA] SISRP-39154 / SISRP-39155 - Task Card bugs

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-39127
=> [QA] SISRP-39127 - Update CalCentral roster queries to use STUDENT_GROUPV01_VW and CC_ENROLLMENTV00_VW

app/models/edo_oracle/oec.rb
Following on SISRP-38835, SISRP-39127
QA version of https://github.com/ets-berkeley-edu/calcentral/pull/7019 , following CalCentral's QA PR, https://github.com/ets-berkeley-edu/calcentral/pull/7018
=> [QA] CLC-6823 Deal with SIS removal of EDO DB view for v97

app/models/user/api.rb, spec/models/user/api_spec.rb
https://jira.berkeley.edu/browse/SISRP-37023
* Lots of analysis went into this change, see JIRA comments if curious.
=> SISRP-37023 - Hide My Academics Page from New Admits

app/models/berkeley/degree_progress_undergrad.rb, app/models/degree_progress/requirements_module.rb, spec/support/degree_progress_shared_examples.rb
https://jira.berkeley.edu/browse/SISRP-39200
QA PR for #7026
=> [QA] SISRP-39200 - Fixes Ugrd Degree Progress 'under review' logic

app/models/oec/queries.rb, spec/models/oec/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6824
QA-first PR for streamlined verification. Master PR to come.
=> [JQA] CLC-6824 CLC-6668 Fix OEC person attribute handling

app/models/oec/queries.rb, spec/models/oec/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6824
Master branch version of the JQA PR: https://github.com/ets-berkeley-edu/calcentral/pull/7029
=> CLC-6824 CLC-6668 Fix OEC person attribute handling

src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js, src/assets/javascripts/angular/controllers/widgets/taskAdderController.js, src/assets/javascripts/angular/controllers/widgets/taskEditorController.js, src/assets/javascripts/angular/controllers/widgets/tasksController.js, src/assets/javascripts/angular/services/tasksService.js, src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html, src/assets/templates/no_bconnected.html, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39180
https://jira.berkeley.edu/browse/SISRP-39181
https://jira.berkeley.edu/browse/SISRP-39229
* Fixes issue with counts
* Fixes display of messaging when no tasks are present, including bConnected messaging
* Refactored to make code simpler using LoDash [_.clone](https://lodash.com/docs/4.17.5#clone) and [_.remove](https://lodash.com/docs/4.17.5#remove)
* Fixed issue with CS display status showing twice for Financial Aid Tasks
```
var objects = [1, 5, 1, 2];
var shallow = _.clone(objects);
_.remove(shallow, function(i){ return i === 1});
console.log(objects);
// => [1, 5, 1, 2]
console.log(shallow);
// => [5, 2]
```
=> SISRP-39180 / SISRP-39181 / SISRP-39229 - Resolves categorization and count involving overdue tasks. Fixes duplicated FA task statuses

src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js, src/assets/javascripts/angular/controllers/widgets/taskAdderController.js, src/assets/javascripts/angular/controllers/widgets/taskEditorController.js, src/assets/javascripts/angular/controllers/widgets/tasksController.js, src/assets/javascripts/angular/services/tasksService.js, src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html, src/assets/templates/no_bconnected.html, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39180
https://jira.berkeley.edu/browse/SISRP-39181
https://jira.berkeley.edu/browse/SISRP-39229
See DEV PR #7027
=> [QA] SISRP-39180 / SISRP-39181 / SISRP-39229 - Resolves categorization and count involving overdue tasks. Fixes duplicated FA task statuses

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-39227
=> SISRP-39227 - Tasks Card Completed Items Order Bug

app/models/my_academics/grading.rb
https://jira.berkeley.edu/browse/SISRP-39254
=> SISRP-39254 - Law Grading - No links or status

app/models/my_academics/grading.rb
https://jira.berkeley.edu/browse/SISRP-39254
See DEV PR #7034
=> [QA] SISRP-39254 - Law Grading - No links or status

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-39227
See DEV PR #7032
=> [QA] SISRP-39227 - Tasks Card Completed Items Order Bug

src/assets/stylesheets/_tasks.scss, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39228
See DEV PR #7033
=> [QA] SISRP-39228 - Tasks Card Divider Horizontal Line Missing

src/assets/stylesheets/_tasks.scss, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39228
=> SISRP-39228 - Tasks Card Divider Horizontal Line Missing

spec/models/my_tasks/merged_spec.rb
https://jira.berkeley.edu/browse/SISRP-39228
@nkutub - This would have passed had you merged my PR today instead of on a Sunday
=> SISRP-39228 - Fixes testext expectation

spec/models/my_tasks/merged_spec.rb
https://jira.berkeley.edu/browse/SISRP-39228
See DEV PR #7038
=> [QA] SISRP-39228 - Fixes testext expectation

src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-39271
See DEV PR #7041
=> SISRP-39271 - Tasks Card: Incomplete Status Financial aid date should not display 'Due'

src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-39271
=> [QA] SISRP-39271 - Tasks Card: Incomplete Status Financial aid date should not display 'Due'

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-39299
=> SISRP-39299 - Task card Further Action Needed section icon, Sorting of the due date should be chronological order

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-39299
See DEV PR #7042
=> [QA] SISRP-39299 - Task card Further Action Needed section icon, Sorting of the due date should be in chronological order

src/assets/templates/widgets/enrollment/schedule.html
https://jira.berkeley.edu/browse/SISRP-39350
=> SISRP-39350 - Enrollment card -> Schedule Planner section -> Final Exam Schedule Link gives 404 error

src/assets/templates/widgets/enrollment/schedule.html
=> [QA] SISRP-39350 - Enrollment card -> Schedule Planner section -> Final Exam Schedule Link gives 404 error

src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39460
See QA PR #7048
=> SISRP-39460 - Tasks with Received Status are not displaying in CalCentral

src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39460
=> [QA] SISRP-39460 - Tasks with Received Status are not displaying in CalCentral

fixtures/xml/campus_solutions/checklist.xml, spec/models/my_tasks/merged_spec.rb
https://jira.berkeley.edu/browse/SISRP-38270
=> SISRP-38270 - Fixes MyTasks::Merged spec to test against consistent with date/time

app/models/oec/merged_sheet_validation.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6826
=> CLC-6826 OEC: warn, don't error on non-participating DEPT_FORM

src/assets/stylesheets/_tasks.scss, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39460
=> SISRP-39460 - Updates task counts to include tasks 'Being Processed'

src/assets/stylesheets/_tasks.scss, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39460
=> [QA] SISRP-39460 - Updates task counts to include tasks 'Being Processed'

src/assets/javascripts/angular/services/tasksService.js, src/assets/stylesheets/_icons.scss, src/assets/stylesheets/_tasks.scss, src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-39298
=> SISRP-39298 - Task card Further Action Needed section icon, due date and title should be red

public/dummy/json/tasks.json, src/assets/javascripts/angular/factories/tasksFactory.js, src/assets/templates/dashboard_task_loop.html, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-39248
=> SISRP-39248 - Tasks Card - Do not display "Due within 1 week" for bcourses tasks

app/models/my_tasks/sis_tasks.rb, src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-39530
=> SISRP-39530 - UX Dev: Checklist Item Translate Value updates "Assigned" and "Processing" statuses

src/assets/templates/widgets/enrollment/adjust.html, src/assets/templates/widgets/enrollment/decide.html, src/assets/templates/widgets/enrollment/haas/explore.html, src/assets/templates/widgets/enrollment_card.html
https://jira.berkeley.edu/browse/SISRP-33596
=> SISRP-33596 - UX: Haas Class Enrollment Card - Design Update

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-39318
=> SISRP-39318 - Tasks Card Category Order

app/models/berkeley/departments.rb, db/developer-seed-data.sql, db/migrate/20180403202710_oec_add_calteach.rb, db/schema.rb
JQA-first attempt at https://jira.ets.berkeley.edu/jira/browse/CLC-6821
I've done minimal testing on this, so reversion chances are high.
=> [JQA] CLC-6821 Create CalTeach OEC pseudo-department

db/developer-seed-data.sql, db/migrate/20180403202710_oec_add_calteach.rb, spec/models/oec/department_mappings_spec.rb
Another JQA-first commit for https://jira.ets.berkeley.edu/jira/browse/CLC-6821
Followup to https://github.com/ets-berkeley-edu/calcentral/pull/7063
=> [JQA] CLC-6821 Also use CALTEACH as the DEPT_FORM value

app/models/berkeley/departments.rb, db/developer-seed-data.sql, db/migrate/20180403202710_oec_add_calteach.rb, db/schema.rb, spec/models/oec/department_mappings_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6821
Master branch version of https://github.com/ets-berkeley-edu/calcentral/pull/7063 and https://github.com/ets-berkeley-edu/calcentral/pull/7064
=>  CLC-6821 Create CalTeach OEC pseudo-department

src/assets/templates/academics_semesters.html, src/assets/templates/widgets/academic_plan.html
https://jira.berkeley.edu/browse/SISRP-39506
=> SISRP-39506 - Add grading basis to Semesters card - CLC Dev

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-39790
Boneheaded mistake, d'oh.
=> SISRP-39790 - Summer Estimator - CalCentral Dev

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-39790
QA PR of #7071
=> [QA] SISRP-39790 - Summer Estimator - CalCentral Dev

app/models/my_academics/gpa_units.rb, spec/models/my_academics/gpa_units_spec.rb
https://jira.berkeley.edu/browse/SISRP-38429
P/NP units are not relevant for Law students, so we'll hide them on the Academic Summary.
=> SISRP-38429 - Suppress P/NP units for Law students

script/start-torquebox.sh
https://jira.berkeley.edu/browse/SISRP-37608
=> SISRP-37608 - Fixes typo in start-torquebox script

app/models/oec/merge_confirmation_sheets_task.rb, spec/models/oec/merge_confirmation_sheets_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6847
=> CLC-6847 OEC: Fill in missing SIS IDs on confirmation sheets merge

src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira.berkeley.edu/browse/SISRP-38416
=> SISRP-38416 - LAW: Remove Degree progress message in CalCentral

app/models/canvas/course_copy_import.rb, app/models/canvas/progress.rb, app/models/canvas_lti/project_provision.rb, config/settings.yml, fixtures/json/canvas_course_copy_import.json, fixtures/json/canvas_progress.json, spec/models/canvas_lti/project_provision_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6843
This will be tested on J-QA before J-Dev.
=> [JQA] CLC-6843 Base new Project Sites on template

src/assets/javascripts/angular/services/profileMenuService.js, src/assets/templates/widgets/profile/information_disclosure.html
https://jira.berkeley.edu/browse/SISRP-38839
=> SISRP-38839 - UX Dev - UCOP/Counsel Requirements for FERPA and Student Information in Directory

package.json
https://jira.berkeley.edu/browse/SISRP-40115
=> SISRP-40115 - Resolve gulp-concat NodeJS package issue causing builds to fail

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-39794
=> SISRP-39794 - Remove MyFinaid (aid Prior to Fall 2016) Link from Financial Resource card

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-37305
=> SISRP-37305 - My Campus - Rescomp label and link change request

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-39608
=> SISRP-39608 - Fix My Campus Link to BETS

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-39361
=> SISRP-39361 - Update links on My Campus - Wellness Section

app/models/my_academics/gpa_units.rb, fixtures/json/hub_academic_status.json, spec/models/my_academics/filtered_for_delegate_spec.rb, spec/models/my_academics/gpa_units_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb, src/assets/javascripts/angular/controllers/pages/academicSummaryController.js, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/widgets/academicsGpaController.js, src/assets/javascripts/angular/services/academicsService.js, src/assets/stylesheets/_academic_summary.scss, src/assets/stylesheets/_profile.scss, src/assets/templates/academics_gpa.html, src/assets/templates/academics_student_profile.html, src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html, src/assets/templates/widgets/student_success/gpa_trends.html
https://jira.berkeley.edu/browse/SISRP-38419
* Introduces multiple-career parsing for `MyAcademics::GpaUnits`
* Eventually we need the ability to parse multiple careers for all applicable features - but we'll take things one step at a time.
* @lyttam since you'll also be working on a lot of the law stuff that requires multiple-career parsing, can you give this one a review?
=> SISRP-38419 - Profile/Academic Summary - hide GPA from Law students - CalCentral Dev

app/models/canvas/course_settings.rb, app/models/canvas_csv/provide_course_site.rb, fixtures/json/canvas_course_settings_hide_grade_distributions.json
https://jira.ets.berkeley.edu/jira/browse/CLC-6844
=> [JQA] CLC-6844 Hide Grade Distribution Graphs by default in course sites

src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js, src/assets/stylesheets/_lists.scss, src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-39289
=> SISRP-39289 - Create CalCentral Link to Credentials for Law Transcript PDF

app/controllers/my_standing_controller.rb, app/models/concerns/academics_module.rb, app/models/edo_oracle/queries.rb, app/models/my_academics/grading.rb, app/models/my_academics/grading_module.rb, app/models/my_academics/my_standings.rb, config/routes.rb, public/dummy/json/standings_present.json, spec/controllers/my_standings_controller_spec.rb, spec/models/my_academics/my_academic_standings_spec.rb, src/assets/javascripts/angular/controllers/widgets/academicStandingController.js, src/assets/javascripts/angular/factories/academicStandingsFactory.js, src/assets/stylesheets/_status_holds.scss, src/assets/templates/widgets/academic_standing.html, src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-39478
* add academic standing feature to status and holds card
* new angular controller and factory
* new API route
* new backend controller and model
=> SISRP-39478 - Student and Advisor view needs to display Academic status

src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
https://jira.berkeley.edu/browse/SISRP-40143
=> SISRP-40143 - Some of the Student resources link are not showing

app/models/concerns/academic_roles.rb, app/models/degree_progress/my_graduate_milestones.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
https://jira.berkeley.edu/browse/SISRP-39558
=> SISRP-39558 - Add JD Plan to Law APR link

app/models/my_academics/semesters.rb
https://jira.berkeley.edu/browse/SISRP-39586
Error:
```[2018-05-09 13:57:58] [ERROR] [CalCentral] [MyAcademics::Merged] Failed to merge MyAcademics::Semesters for UID XXXXX: NoMethodError: undefined method `collect' for nil:NilClass```
=> SISRP-39586 - Fixes error in Semesters feed

src/assets/templates/widgets/academic_summary/academic_summary_card.html
https://jira.berkeley.edu/browse/SISRP-39706
=> SISRP-39706 - Academic Summary Enrollments section - Add a summary row at the bottom

src/assets/javascripts/angular/controllers/pages/academicSummaryController.js, src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-39586
Work was already done by @lyttam in #7100, this PR is just for an additional requirement that came in late, as seen in the JIRA ticket.
=> SISRP-39586 - Academic Summary Enrollments - Surface earned/enrolled Law units, hide grade points when they don't apply (additional requirements)

app/models/degree_progress/requirements_module.rb, spec/support/degree_progress_shared_examples.rb, src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-40194
=> SISRP-40194 - Update 'Under Review' text in Degree Progress card

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-40187
=> SISRP-40187 - Need SF negative service indicators to display in CalCentral if configured to do so in BCS

.gitignore, README.md
[SISRP-40131](https://jira.berkeley.edu/browse/SISRP-40131)
Updates the Installation Instructions in README.md and adds items to .gitignore (package-lock.json && Prettier)
=> SISRP-40131 - Update README.md and .gitignore

src/assets/templates/widgets/enrollment/concurrent/decide.html, src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-23454
bug fxes
=> SISRP-39289 - Replace hardcoded Add/Drop Deadline for Concurrent Enrollment students

src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-39289
bug fixes
=> SISRP-39289 - Create CalCentral Link to Credentials for Law Transcript PDF - UX Dev w/ API

src/assets/javascripts/angular/directives/academicCareersDirective.js, src/assets/javascripts/angular/directives/expectedGraduationTermsDirective.js, src/assets/stylesheets/_academic_summary.scss, src/assets/stylesheets/_profile.scss, src/assets/templates/academics_student_profile.html, src/assets/templates/directives/academic_careers.html, src/assets/templates/directives/academic_plans.html, src/assets/templates/directives/expected_graduation_terms.html, src/assets/templates/widgets/academic_summary/academic_summary_card.html, src/assets/templates/widgets/academic_summary/academic_summary_semesters.html, src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html, src/assets/templates/widgets/academics/college_and_level.html, src/assets/templates/widgets/academics/degrees_conferred.html, src/assets/templates/widgets/student_success/units.html, src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-38422
Includes visual updates per the design mockups.
Makes some slight changes to styling on Profile and Academic Summary to make the two cards consistent with each other.
=> SISRP-38422 - Refactors Profile and Academic Summary cards

app/models/edo_oracle/queries.rb, app/models/my_academics/semesters.rb, public/dummy/json/academics_reserved_seats.json, spec/models/my_academics/semesters_spec.rb, src/assets/javascripts/angular/factories/academicsFactory.js, src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-37193
=> SISRP-37193 - UX Dev - Reserve Capacity: Show in CalCentral - Student view

src/assets/stylesheets/_academic_summary.scss
https://jira.berkeley.edu/browse/SISRP-38427
Just a style update.
=> SISRP-38427 - Changes style on Req. Designation

app/models/edo_oracle/bulk.rb, spec/models/data_loch/zipper_spec.rb
https://jira.ets.berkeley.edu/jira/browse/NS-46
There will be followup PRs for Nessie, and then for BOAC.
=> NS-46 Fill missing SIS course data for Loch

src/assets/stylesheets/_academic_summary.scss, src/assets/stylesheets/_academics.scss, src/assets/templates/academics_semesters.html, src/assets/templates/directives/expected_graduation_terms.html, src/assets/templates/widgets/academic_summary/academic_summary_semesters.html, src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html
There was inconsistency between the Semesters card and the Academic Summary page in showing a term that the student withdrew from.
=> NOJIRA: Fixes expected grad term error and makes small style improvement on semesters

app/models/my_academics/grading.rb, spec/models/my_academics/grading_spec.rb
=> SISRP-39683 - Fixes grading period status behavior

app/models/edo_oracle/user_courses/base.rb, app/models/my_academics/semesters.rb, public/dummy/json/academics.json, public/dummy/json/academics_reserved_seats.json, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/my_academics/semesters_spec.rb, src/assets/javascripts/angular/controllers/pages/academicSummaryController.js, src/assets/javascripts/angular/controllers/widgets/academicsGpaController.js, src/assets/templates/academics_classinfo.html, src/assets/templates/academics_semester_classes.html, src/assets/templates/academics_semesters.html, src/assets/templates/widgets/academic_plan.html, src/assets/templates/widgets/academic_summary/academic_summary_semesters.html
https://jira.berkeley.edu/browse/SISRP-40401
In order to appease the JS linter, I had to convert some keys from snake to camel case.  Eventually we can convert the entire feed to camel case but I don't want to tackle that whole project at this time.
=> SISRP-40400 - Hides Pts column when semester has no grade points

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js
https://jira.berkeley.edu/browse/SISRP-33623
=> SISRP-33623 - Create a "waivers and other funding" section in the Awards card in CalCentral

app/models/campus_solutions/financial_aid_housing.rb, app/models/concerns/academic_roles.rb, spec/models/campus_solutions/financial_aid_housing_spec.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
https://jira.berkeley.edu/browse/SISRP-40310
In addition to undergrad new admits, we will display the link to undergrad students who are not in the UNODG (non-degree) program.
=> SISRP-40310: Surfaces Update Housing link for continuing undergrads

app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb, src/assets/templates/academics_semesters.html
https://jira.berkeley.edu/browse/SISRP-40400
=> SISRP-40400 - Hides Grading Basis from Law students

src/assets/templates/widgets/enrollment/decide.html
https://jira.berkeley.edu/browse/SISRP-23454
* bug fix
=> SISRP-23454 - Replace hardcoded Add/Drop Deadline for Concurrent Enrollment students

src/assets/templates/widgets/enrollment/decide.html
=> [QA] SISRP-23454 - Replace hardcoded Add/Drop Deadline for Concurrent Enrollment students

src/assets/templates/widgets/academic_plan.html, src/assets/templates/widgets/status_and_holds.html
=> [QA] SISRP-39478 - Student and Advisor view needs to display Academic status

app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-37193
* update formatting for negative capacity
=> SISRP-37193 - Reserve Capacity: Show in CalCentral - Student view

app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb
=> [QA] SISRP-37193 - Reserve Capacity: Show in CalCentral - Student view

app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/all.rb, app/models/edo_oracle/user_courses/base.rb, app/models/my_academics/semesters.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/my_academics/semesters_spec.rb
=> [QA] SISRP-38837 - Moves career filtering logic to the Semesters model

app/models/my_academics/grading.rb, spec/models/my_academics/grading_spec.rb
=> SISRP-39683 - Fixes CS grading status parsing

app/models/my_academics/grading.rb, spec/models/my_academics/grading_spec.rb
=> [QA] SISRP-39683 - Fixes CS grading status parsing

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-39248
=> SISRP-39248 - Fixes bug with sorting of tasks to order further action needed tasks last

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-39248
See DEV PR #7153
=> [QA] SISRP-39248 - Fixes bug with sorting of tasks to order further action needed tasks list

app/models/my_academics/graduation.rb
https://jira.berkeley.edu/browse/SISRP-40305
=> SISRP-40305 - For GRAD Only student there shouldn't be Expected Graduation info

app/models/my_academics/graduation.rb
https://jira.berkeley.edu/browse/SISRP-40305
QA PR of #7155
=> [QA] SISRP-40305 - For GRAD Only student there shouldn't be Expected Graduation info

src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
https://jira.berkeley.edu/browse/SISRP-39289
* added special date setup for law links
=> Create CalCentral Link to Credentials for Law Transcript PDF

src/assets/javascripts/angular/controllers/widgets/academics/academicRecordsController.js
=> [QA] Create CalCentral Link to Credentials for Law Transcript PDF

app/models/my_academics/grading.rb
=> SISRP-39683 - Exposes grading link when roster is present

src/assets/javascripts/angular/controllers/widgets/statusController.js
https://jira.berkeley.edu/browse/SISRP-40514
=> SISRP-40514 - For Academic standing Alert popover is not working

src/assets/javascripts/angular/controllers/widgets/statusController.js
=> [QA] SISRP-40514 - For Academic standing Alert popover is not working

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js
https://jira.berkeley.edu/browse/SISRP-33623
See QA PR #7173
=> SISRP-33623 - Fixes order of award sections (Gift Aid, Waivers and Other, Work Study)

src/assets/javascripts/angular/controllers/widgets/finaid/finaidAwardsController.js
https://jira.berkeley.edu/browse/SISRP-33623
See DEV PR #7172
=> [QA] SISRP-33623 - Fixes order of award sections (Gift Aid, Waivers and Other, Work Study)

src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-40515
=> SISRP-40515 - Undergrad non-degree student shouldn't see Academic Standing at all

src/assets/templates/widgets/status_and_holds.html
=> [QA] SISRP-40515 - Undergrad non-degree student shouldn't see Academic Standing at all

app/models/my_academics/grading.rb, spec/models/my_academics/grading_spec.rb
=> SISRP-39683 - Fixes call to check for grading date config to default to Spring/Fall session code

app/models/my_academics/grading.rb, spec/models/my_academics/grading_spec.rb
=> [QA] SISRP-39683 - Fixes call to check for grading date config to default to Spring/Fall session code

public/json/terms.json
https://jira.berkeley.edu/browse/SISRP-39458
update terms file
=> SISRP-40435 - CalCentral - Turn off Term API and update Flat file for Terms

app/models/concerns/academic_roles.rb, app/models/degree_progress/my_graduate_milestones.rb, app/models/my_academics/my_academic_roles.rb, app/models/my_academics/my_academic_status.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb, spec/models/my_academics/my_academic_status_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js, src/assets/templates/widgets/academics/degree_progress_graduate.html
https://jira.berkeley.edu/browse/SISRP-38416
https://jira.berkeley.edu/browse/SISRP-39558
https://jira.berkeley.edu/browse/SISRP-40493
(Covers 3 JIRAs)
- Opens up mapping of one plan code to multiple plans
- Adds additional logic to degree progress graduate visibility
QA PR of #7182
=> [QA] SISRP-38416 - LAW: Remove Degree progress message in CalCentral

app/models/data_loch/s3.rb, lib/tasks/data_loch.rake, spec/models/data_loch/s3_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6866
In hopes of streamlining our upcoming release process.
=> [JQA] CLC-6866 Support creation of historical term data in S3

src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js
https://jira.berkeley.edu/browse/SISRP-40143
See DEV PR #7188
=> [QA] SISRP-40143 - Some of the Student resources link are not showing

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/controllers/widgets/statusController.js
=> [QA] SISRP-40593 - Status and holds card now showing for students but has on Advisor view

app/models/my_academics/class_enrollments.rb, app/models/my_academics/my_academic_status.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/class_enrollments_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira.berkeley.edu/browse/SISRP-40607
https://jira.berkeley.edu/browse/SISRP-39160
See DEV PR #7194
=> [QA] SISRP-40607 - Summer Late petition eform link not showing up UNODG students #7194

app/models/my_academics/class_enrollments.rb, app/models/my_academics/my_academic_status.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/my_academics/class_enrollments_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira.berkeley.edu/browse/SISRP-40607
https://jira.berkeley.edu/browse/SISRP-39160
See QA PR #7195
=> SISRP-40607 - Summer Late petition eform link not showing up UNODG students

src/assets/templates/widgets/enrollment/adjust.html
https://jira.berkeley.edu/browse/SISRP-40607
See DEV PR #7199 7199
=> [QA] SISRP-40607 - Remove 'courseWorkOnly' support for Late Petition link

src/assets/templates/widgets/enrollment/adjust.html
https://jira.berkeley.edu/browse/SISRP-40607
=> SISRP-40607 - Remove 'courseWorkOnly' support for Late Petition link

Gemfile, Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-37833
Remember to run `bundle install` after pulling this change into your local codebase.
=> SISRP-37833: Upgrades nokogiri

Gemfile, Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-37968
Remember to run `bundle install` after pulling this change into your local codebase.
=> SISRP-37968: Upgrades net-ldap

app/controllers/application_controller.rb
https://jira.berkeley.edu/browse/SISRP-40732
QA PR for #7203
=> [QA] SISRP-40732: Allows advisors to look up released admits

src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira.berkeley.edu/browse/SISRP-40660
See QA PR #7206
=> SISRP-40660 - Blank Degree Progress Card showing for Law Students

src/assets/javascripts/angular/controllers/widgets/academics/graduateDegreeProgressController.js
https://jira.berkeley.edu/browse/SISRP-40660
See DEV PR #7205
=> [QA] SISRP-40660 - Blank Degree Progress Card showing for Law Students

app/models/edo_oracle/bulk.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-919
=> BOAC-919 Change data source for Course Section Allowed Units

script/bamboo-install.sh
Per Ray's comment:  https://jira.berkeley.edu/browse/SISRP-40517?focusedCommentId=567849&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-567849
The script I'm adding is a copy of `bamboo-tests.sh` with the part that runs the tests removed. Once this is merged, I will update the Bamboo configuration to run this script instead of `bamboo-tests.sh`.
=> SISRP-40517: Adds new script to install dependencies for bamboo build

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-40529
=> SISRP-40529: Prevents FPP enrollment call when not authorized

src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-40864
=> SISRP-40864 - Terms in Attendance display missing from profile in CalCentral

app/models/campus_solutions/terms_and_conditions.rb, spec/controllers/campus_solutions/terms_and_conditions_controller_spec.rb, spec/models/campus_solutions/terms_and_conditions_spec.rb
https://jira.berkeley.edu/browse/SISRP-39215
=> SISRP-39215: Improves Terms & Conditions backend validation

src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-40191
=> SISRP-40191: Hides enrollment Swap link from active Law students

app/models/my_academics/grading.rb, app/models/my_academics/grading_module.rb, fixtures/xml/campus_solutions/link_api_multiple.xml, spec/models/my_academics/grading_spec.rb
https://jira.berkeley.edu/browse/SISRP-38459
=> SISRP-38459 - BearFacts legacy grade rosters - Faculty access in CalCentral

src/assets/templates/directives/academic_plans.html
https://jira.berkeley.edu/browse/SISRP-40275
=> SISRP-40275 - CalCentral remove program/college info when displaying minor

src/assets/templates/widgets/academic_standing.html
https://jira.berkeley.edu/browse/SISRP-40581
=> SISRP-40581 - For Advisor description and date is missing on Status and Holds card for Good Standing status for Academic standing

src/assets/javascripts/angular/controllers/pages/userOverviewController.js
https://jira.berkeley.edu/browse/SISRP-40840
=> SISRP-40840: updates advisor-facing Degree Progress logic to match student-facing

src/assets/templates/widgets/activity_list_link.html
https://jira.berkeley.edu/browse/SISRP-40543
=> SISRP-40543 - Update Communication Center link directive

src/assets/templates/directives/expected_graduation_terms.html
https://jira.berkeley.edu/browse/SISRP-32029
=> SISRP-32029 - Format for UGRD Expected Graduation Term Bug

src/assets/templates/widgets/up_next.html
https://jira.berkeley.edu/browse/SISRP-39856
=> SISRP-39856 - Update "Create bConnected account" links in CalCentral

app/models/my_academics/grading.rb, src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/javascripts/angular/services/academicsService.js, src/assets/templates/academics_classinfo.html, src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-37469
Certain types of classes all share the same title, but the topic indicates what the class is actually about. Students can already see the topic. Now we'll show it to instructors too.
I deviated somewhat from the design after coming to an agreement with the BSA.
=> SISRP-37469: Show class topic to instructors

src/assets/javascripts/angular/controllers/pages/academicSummaryController.js, src/assets/templates/widgets/academic_summary/academic_summary_card.html
https://jira.berkeley.edu/browse/SISRP-40307
When I refactored the Transfer Credit card, I forgot to apply the changes to the Transfer Credit section on Academic Summary.
=> SISRP-40307: Fixes issue with Transfer Credit on Academic Summary

src/assets/templates/widgets/activity_list_link.html
Reverts ets-berkeley-edu/calcentral#7226
See comments in 
https://jira.berkeley.edu/browse/SISRP-40543
=> Revert "SISRP-40543 - Update Communication Center link directive"

src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-40840
=> SISRP-40840: Updates degree progress text for advisor viewing inactive student

src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-40790
=> SISRP-40790 - Add text in CalCentral for electronic PDF for Law transcripts to indicate eligible students

app/models/my_academics/class_enrollments.rb, app/models/my_academics/my_academic_roles.rb, spec/models/my_academics/class_enrollments_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb
https://jira.berkeley.edu/browse/SISRP-39575
=> SISRP-39575 - CPP VIEW: CalCentral Development (replace academic status API for Enrollment card)

app/models/berkeley/term.rb, app/models/berkeley/terms.rb, app/models/edo_oracle/queries.rb, spec/models/berkeley/terms_spec.rb
https://jira.berkeley.edu/browse/SISRP-38885
=> SISRP-38885 - Terms API Refactor to SISEDO View for CLC - Development

app/models/my_academics/teaching.rb, spec/models/my_academics/teaching_spec.rb, src/assets/javascripts/angular/directives/campusSolutionsLinkDirective.js, src/assets/templates/academics_teaching.html
https://jira.berkeley.edu/browse/SISRP-38459
=> SISRP-38459 - Updates Legacy Term links to use all CS Link API properties

src/assets/stylesheets/_finaid_housing.scss, src/assets/templates/widgets/finaid/housing.html
https://jira.berkeley.edu/browse/SISRP-41163
See comment https://jira.berkeley.edu/browse/SISRP-41163?focusedCommentId=575381&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-575381
=> SISRP-41163: Updates styles on Housing card

app/models/campus_solutions/enrollment_term.rb
https://jira.berkeley.edu/browse/SISRP-41286
=> SISRP-41286 - Enrollment Card -> Class Adjustment Section -> When Column is not displaying correctly

app/models/my_academics/exams.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, config/settings/testext.yml, spec/models/my_academics/exams_spec.rb, src/assets/templates/academics.html, src/assets/templates/user_overview.html
https://jira.berkeley.edu/browse/SISRP-36756
=> SISRP-36756 - Updates MyAcademics::Exams to support feature flags for Student and Teaching Semesters

app/models/my_academics/exams.rb, spec/models/my_academics/exams_spec.rb, src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-36756
=> SISRP-36756 - Updates feed to provide courses without schedules

app/models/financials/loan_history/loans_aid_years.rb, spec/models/financials/loan_history/loans_aid_years_spec.rb
https://jira.berkeley.edu/browse/SISRP-38606
=> SISRP-38606 - Loan History Card - CLC Dev - fix aid year formatting

app/models/concerns/academics_module.rb, app/models/edo_oracle/queries.rb, app/models/edo_oracle/user_courses/base.rb, app/models/my_academics/exams.rb, spec/models/my_academics/exams_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/finalExamScheduleController.js, src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-41442
=> SISRP-41442 - LAW student it shouldn't show LAW courses in Final Exam Schedules card

public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-41263
=> SISRP-41263 - CalCentral Financial Resources Card: Change URL for the Cal Student Central Help Link

src/assets/javascripts/angular/services/tasksService.js, src/assets/templates/widgets/tasks.html
https://jira.berkeley.edu/browse/SISRP-41072
=> SISRP-41072 - Task card need to show recent due date task on top.

public/dummy/json/academics.json, src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-41460
https://jira.berkeley.edu/browse/SISRP-41461
https://jira.berkeley.edu/browse/SISRP-41462
=> SISRP-41460 - SISRP-41461 / SISRP-41462 - Final Exam Schedule bug fixes

app/models/edo_oracle/transfer_credit.rb, src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-41444
=> SISRP-41444 - If Transfer Credit data is not posted yet then the student should not see Transfer Credit Card on My Academics page

src/assets/javascripts/angular/controllers/widgets/academics/transferCreditController.js
https://jira.berkeley.edu/browse/SISRP-41513
QA PR of #7260
=> [QA] SISRP-41513 - Transfer Credit card is missing on My Academics Page

src/assets/javascripts/angular/controllers/widgets/academics/transferCreditController.js
https://jira.berkeley.edu/browse/SISRP-41513
QA PR to come
=> SISRP-41513 - Transfer Credit card is missing on My Academics Page

src/assets/templates/widgets/enrollment/adjust_enrolled.html
This change will not be included in v98.
https://jira.berkeley.edu/browse/SISRP-40191
=>  Revert "SISRP-40191: Hides enrollment Swap link from active Law students"

src/assets/templates/widgets/enrollment/adjust_enrolled.html
=> [QA] Revert "SISRP-40191: Hides enrollment Swap link from active Law students"

app/models/my_academics/exams.rb, spec/models/my_academics/exams_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/finalExamScheduleController.js, src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-41514
See DEV PR #7264
=> [QA] SISRP-41514 - Update Hardcoded Message on Final Exams Schedule Card

app/models/my_academics/exams.rb, spec/models/my_academics/exams_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/finalExamScheduleController.js, src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-41514
=> SISRP-41514 - Update Hardcoded Message on Final Exams Schedule Card

app/models/concerns/loan_history_module.rb, app/models/financials/loan_history/loans_aid_years.rb, app/models/financials/loan_history/loans_cumulative.rb, spec/models/concerns/loan_history_module_spec.rb
https://jira.berkeley.edu/browse/SISRP-41545
=> SISRP-41545 - Loan History Card - CLC Dev - Est Payment Amt Fix

app/models/concerns/loan_history_module.rb, app/models/financials/loan_history/loans_aid_years.rb, app/models/financials/loan_history/loans_cumulative.rb, spec/models/concerns/loan_history_module_spec.rb
https://jira.berkeley.edu/browse/SISRP-41545
QA PR of #7268
=> [QA] SISRP-41545 - Loan History Card - CLC Dev - Est Payment Amt Fix

src/assets/templates/canvas_embedded/create_project_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6026
Not that high a priority, but it gave me an excuse to bring my local working environment up to date.
=> CLC-6026 Project Site "Cancel" button now does something

src/assets/templates/widgets/loan_history/aid_year_overview.html
https://jira.berkeley.edu/browse/SISRP-41547
=> SISRP-41547 - Loan History - Aid Years Listed Reverse Order

src/assets/templates/widgets/loan_history/aid_year_overview.html
https://jira.berkeley.edu/browse/SISRP-41547
QA PR of #7271
=> [QA] SISRP-41547 - Loan History - Aid Years Listed Reverse Order

src/assets/templates/widgets/finaid_profile.html
https://jira.berkeley.edu/browse/SISRP-41609
* total hack till refactor next sprint
=> SISRP-41609 - Hide SHIP Field on FASO Profile Card b/c inaccurate in some cases

src/assets/templates/widgets/finaid_profile.html
=> [QA] SISRP-41609 - Hide SHIP Field on FASO Profile Card b/c inaccurate in some cases

src/assets/stylesheets/_loan_history_page.scss
https://jira.berkeley.edu/browse/SISRP-41577
No QA PR, this will be going into the next release.
=> SISRP-41577 - Loan History - Table Column Format Updates

app/models/my_academics/class_enrollments.rb
https://jira.berkeley.edu/browse/SISRP-41664
See QA PR #7277
=> SISRP-41664 - Enrollment card - not reflecting Hass student role card in QA

app/models/my_academics/class_enrollments.rb
https://jira.berkeley.edu/browse/SISRP-41664
=> [QA] SISRP-41664 - Enrollment card - not reflecting Hass student role card in QA

config/database.yml, config/settings.yml
https://jira.berkeley.edu/browse/SISRP-34988
=> SISRP-34988 - CalCentral application does not connect to Postgres via SSL

app/models/edo_oracle/view_checker.rb, config/initializers/populate_sisedo_h2.rb
Adds SISEDO view check for:
* CLC_FINAL_EXAM_INFOV00_VW
* CLC_TERM_INSTR_BF2008V00_VW
* CLC_TERMV00_VW
Alphabetizes order of view dependency definitions.
=> NOJIRA - Updates SISEDO Check configuration. Alphabetizes view order

db/migrate/20180824200053_oec_celtic_plus.rb, db/schema.rb
Sad-sack followup to https://github.com/ets-berkeley-edu/calcentral/pull/7290 , in which I missed committing a couple of files while trying to beat the clock.
=> CLC-6889 REALLY add CELTIC, MEDIAST, etc. to OEC departments

src/assets/templates/dashboard_task_loop.html
https://jira.berkeley.edu/browse/SISRP-41093
=> SISRP-41093 - Tasks Card "Being Processed Items" Due within 1 week

app/controllers/my_campus_links_controller.rb, app/models/links/campus_links_from_file_feature_flagged.rb, app/models/links/my_campus_links.rb, config/settings.yml, spec/controllers/my_campus_links_controller_spec.rb, spec/models/links/my_campus_links_spec.rb
https://jira.berkeley.edu/browse/SISRP-42338
Will be adding a new feature flag around using Postgres for campus links.
=> SISRP-42338: Adds option to source campus links from file

app/models/concerns/academics_module.rb, app/models/edo_oracle/queries.rb, app/models/my_academics/exams.rb, spec/models/my_academics/exams_spec.rb, src/assets/javascripts/angular/controllers/widgets/academics/finalExamScheduleController.js, src/assets/javascripts/angular/directives/academicsClassInfoFinalExamsDirective.js, src/assets/stylesheets/_exam_schedule.scss, src/assets/templates/academics.html, src/assets/templates/academics_classinfo.html, src/assets/templates/academics_semester.html, src/assets/templates/directives/academics_class_info_final_exams.html, src/assets/templates/user_overview.html, src/assets/templates/widgets/final_exam_schedule.html
https://jira.berkeley.edu/browse/SISRP-40774
=> SISRP-40774 - Final Exams Schedule (Instructors) - UX Dev

Gemfile, Gemfile.lock, app/models/google_apps/sheets_manager.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6899
QA PR (merged) is #7298
I suggest we merge this _after_ it's been verified in `jqa` environment.
=> CLC-6899, OEC sis-import fix; google-drive gem update and better session mgmt

src/assets/javascripts/angular/services/tasksService.js
https://jira.berkeley.edu/browse/SISRP-42300
=> SISRP-42300 - FA Tasks need to be sorted by Status

app/models/my_academics/class_enrollments.rb, spec/models/my_academics/class_enrollments_spec.rb
https://jira.berkeley.edu/browse/SISRP-27435
=> SISRP-27435 - Revert FPF Hack after transition to Term Specific Academic Status API

app/models/my_academics/exams.rb, spec/models/my_academics/exams_spec.rb
https://jira.berkeley.edu/browse/SISRP-40774
=> SISRP-40774 - Final Exams Schedule (Instructors) - Updates Date Formats

app/models/my_academics/teaching.rb, spec/models/my_academics/teaching_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6904
Pinging @johncrossman (and @redconfetti ) .
If this tests OK, I'll submit a master PR to match.
=> [JQA] CLC-6904 Do not use SIS-specific API in code shared by ETS

public/dummy/json/cal1card-found.json, public/dummy/json/cal1card-lost.json, src/assets/javascripts/angular/factories/cal1cardFactory.js, src/assets/templates/cal1card.html
https://jira.berkeley.edu/browse/SISRP-41780
New design calls for static meal plan links, now that the API no longer provides accurate information.
=> SISRP-41780 - CalCentral Cal 1 Card Meal Plan Update

src/assets/stylesheets/_exam_schedule.scss
https://jira.berkeley.edu/browse/SISRP-41647
=> SISRP-41647 - Final Exam Card - Adjust Column Width

app/models/oec/courses.rb, app/models/oec/report_diff_task.rb, spec/models/oec/validation_task_spec.rb
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/7308
Already verified on the JQA branch.
=> CLC-6905 Add "_MID" to list of acceptable OEC COURSE_ID suffixes

app/controllers/campus_solutions/faculty_resources_controller.rb, app/models/campus_solutions/faculty_resources.rb, app/models/campus_solutions/student_resources.rb, config/routes.rb, public/dummy/json/faculty_resources.json, src/assets/javascripts/angular/controllers/widgets/facultyResourcesController.js, src/assets/javascripts/angular/controllers/widgets/studentResourcesController.js, src/assets/javascripts/angular/factories/facultyResourcesFactory.js, src/assets/templates/dashboard.html, src/assets/templates/faculty_resources.html, src/assets/templates/widgets/student_resources.html
https://jira.berkeley.edu/browse/SISRP-41856
=> SISRP-41856 - Add DSP Links to CalCentral - UX Dev

app/models/my_academics/teaching.rb, spec/models/my_academics/teaching_spec.rb
Master branch version of https://github.com/ets-berkeley-edu/calcentral/pull/7306
@lyttam , @davidlimcheng , @redconfetti , @nkutub : This is a change in code shared by SIS and ETS, and so one of you should review it. Send any questions my way!
=> CLC-6904 Do not use SIS-specific API in code shared by ETS

app/models/user/user_visits_feature_flagged.rb, app/models/user/visit.rb, config/settings.yml, spec/controllers/user_controller_spec.rb, spec/models/user/visit_spec.rb
https://jira.berkeley.edu/browse/SISRP-42360
=> SISRP-42360: Feature flags recording of user visits

src/assets/javascripts/angular/controllers/widgets/profilePopoverController.js, src/assets/templates/widgets/profile/contact.html, src/assets/templates/widgets/profile/demographic.html, src/assets/templates/widgets/profile/emergency.html
https://jira.berkeley.edu/browse/SISRP-39903
Fixes an oversight that David noticed.  Also makes the button look disabled if the link isn't available.
=> SISRP-39903: Adds new profile link to the popover menu

app/controllers/campus_solutions/financial_resources_controller.rb, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-41516
=> SISRP-41516 - Delegates - Financial Resource Card Endless Spinning Bug

app/models/concerns/academics_module.rb, app/models/my_academics/canvas_sites.rb, app/models/my_academics/college_and_level.rb, app/models/my_classes/campus.rb, app/models/my_tasks/canvas_tasks.rb, app/models/my_tasks/google_tasks.rb, app/models/my_tasks/sis_tasks.rb
https://jira.berkeley.edu/browse/SISRP-42335
=> SISRP-42335: Fixes misc. NoMethodErrors

app/models/oec/department_hierarchy.rb, app/models/oec/merged_sheet_validation.rb, app/models/oec/report_viewer_hierarchy.rb, spec/models/oec/publish_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6897
UPDATED: Now with fewer Travis-breaking changes!
=>  CLC-6897 Generate two new OEC spreadsheets for supervisors

app/models/user/has_instructor_history.rb, spec/models/user/has_instructor_history_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6908
=> CLC-6908 Only instructors in current terms should see Create Course Site

app/models/edo_oracle/bulk.rb, app/models/edo_oracle/oec.rb, app/models/edo_oracle/view_checker.rb, config/initializers/populate_sisedo_h2.rb
https://jira.berkeley.edu/browse/SISRP-42541
=>  SISRP-42541 Update SISEDO views used by OEC

app/models/edo_oracle/queries.rb, app/models/user/search_users_by_name.rb, spec/models/edo_oracle/queries_spec.rb, src/assets/javascripts/angular/controllers/widgets/userSearchController.js, src/assets/javascripts/angular/services/adminService.js
https://jira.berkeley.edu/browse/SISRP-39065
=> SISRP-39065 - Adds support for case insensitive search, distinct query results. Fixes Saved/Recent tab functionality

src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-6901
=> CLC-6901 Official Sections needs to let the spinning wheel ride

app/models/edo_oracle/financial_aid/queries.rb, app/models/financial_aid/my_financial_aid_summary.rb, spec/models/edo_oracle/financial_aid/queries_spec.rb, spec/models/finaid/my_financial_aid_summary_spec.rb
https://jira.berkeley.edu/browse/SISRP-42629
=> SISRP-42629: adds EMPLID param to Shopping Sheet link

app/models/canvas_lti/project_provision.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6880
=> CLC-6880 Allow more time for Project Site creation

app/models/edo_oracle/queries.rb
https://jira.berkeley.edu/browse/SISRP-39065
bug fix
=> SISRP-39065 - AA: UX Dev - Advisor Student Lookup

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6913
By way of documentation....
=> CLC-6913 Add CYBER courses to OEC

app/models/user/search_users_by_name.rb, app/models/user/search_users_by_name_filter.rb, config/routes.rb, spec/models/user/search_users_by_name_filter_spec.rb, spec/models/user/search_users_by_name_spec.rb, src/assets/javascripts/angular/factories/adminFactory.js, src/assets/javascripts/angular/services/httpService.js
https://jira.berkeley.edu/browse/SISRP-39065
Follows a Campus Solutions function to prepare an inputted name to use as a query condition for SISEDO.  
CS code can be found in [Confluence.](https://wikihub.berkeley.edu/display/SIS/CalCentral+View+As+Card)
=> SISRP-39065 - filters input name to match campus solutions search criteria

src/assets/javascripts/angular/controllers/widgets/profilePopoverController.js
https://jira.berkeley.edu/browse/SISRP-39903
These changes are for post 10/7 release.
=> SISRP-39903: Fixes issues with link in popover menu

config/settings.yml
https://jira.berkeley.edu/browse/SISRP-42768
=> SISRP-42768 - Updates LDAP host name

README.md
https://jira.berkeley.edu/browse/SISRP-40088
=> SISRP-40088 - Update README to replace mentions of Gulp to Webpack

app/models/user/has_instructor_history.rb, spec/models/user/has_instructor_history_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6908
Junction-QA-first PR to handle the latest twist.
=> [JQA] CLC-6908 Cache HasInstructorHistory correctly

app/models/user/has_instructor_history.rb, spec/models/user/has_instructor_history_spec.rb
Master branch version of https://github.com/ets-berkeley-edu/calcentral/pull/7345
This fix has been verified on Junction-QA.
=> CLC-6908 Cache HasInstructorHistory correctly

app/controllers/my_profile_controller.rb, app/models/hub_edos/my_student.rb, app/models/my_profile/edit_link.rb, config/routes.rb, spec/controllers/my_profile_controller_spec.rb, spec/models/hub_edos/my_student_spec.rb, src/assets/javascripts/angular/controllers/widgets/profilePopoverController.js, src/assets/javascripts/angular/factories/profileFactory.js
https://jira.berkeley.edu/browse/SISRP-39903
This is for 10/17 minor release.
=> SISRP-39903: Restricts profile edit link to students and new admits

app/models/canvas/course_user.rb, app/models/mailing_lists/site_mailing_list.rb, spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6910
=> CLC-6910 Support sending to bCourses Mailing List from Project sites

app/controllers/advising_student_controller.rb, app/controllers/hub_edo_controller.rb, config/routes.rb, spec/controllers/advising_student_controller_spec.rb, spec/controllers/hub_edo_controller_spec.rb, spec/ui_selenium/pages/api_edos_academic_status_page.rb
https://jira.berkeley.edu/browse/SISRP-43077
=> SISRP-43077 - Remove un-used academicStatusFactory and API end-points

public/canvas/canvas-customization.css, public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6906
=> CLC-6906 Add Privacy/Analytics link to bCourses Footer

src/assets/javascripts/angular/controllers/widgets/profile/contactController.js, src/assets/javascripts/angular/controllers/widgets/profile/demographicController.js, src/assets/javascripts/angular/controllers/widgets/profile/emergencyController.js
https://jira.berkeley.edu/browse/SISRP-39903
=> SISRP-39903_QA: Fixes edit profile links

app/controllers/concerns/advising_resources.rb, app/models/concerns/academic_status.rb, app/models/edo_oracle/queries.rb, spec/controllers/concerns/advising_resources_spec.rb, spec/models/concerns/academic_status_spec.rb
https://jira.berkeley.edu/browse/SISRP-43078
=> SISRP-43078 - Update Concerns::AdvisingResources to use Oracle View for CPP

app/models/edo_oracle/queries.rb, app/models/student_success/term_gpa.rb, spec/models/edo_oracle/queries_spec.rb, spec/models/student_success/term_gpa_spec.rb
https://jira.berkeley.edu/browse/SISRP-43080
=> SISRP-43080 - Update StudentSuccess::TermGpa to source career description from Oracle CPP view

app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6929
=> CLC-6929 Treat whitespace as null for OEC location checks

app/models/canvas/sis_import.rb, spec/models/canvas/sis_import_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6930
=> CLC-6930 Fix parsing of Canvas SIS Import status

app/models/oec/courses.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6931
=> CLC-6931 OEC shouldn't worry so much about BIOLOGY

src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-5189
Everybody loves a spinner.
=> CLC-5189 E-Grades Export needs to spin more

app/models/campus_solutions/enrollment_term.rb, fixtures/xml/campus_solutions/enrollment_term.xml, spec/models/campus_solutions/enrollment_term_spec.rb
https://jira.berkeley.edu/browse/SISRP-35692
=> SISRP-35692: Fixes issue with class meeting time format

app/models/my_academics/class_enrollments.rb, fixtures/xml/campus_solutions/enrollment_term.xml, public/dummy/json/enrollment_instructions.json, spec/models/my_academics/class_enrollments_spec.rb, src/assets/stylesheets/_enrollment_card.scss, src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-40675
=> SISRP-40675 - Improve display and visibility of Early Drop Deadline Courses

config/initializers/populate_sisedo_h2.rb, public/json/campuslinks.json
https://jira.berkeley.edu/browse/SISRP-43304
=> SISRP-43304 Update NSLDS Student Site Link in CalCentral My Campus

.gitignore, package-lock.json
https://jira.berkeley.edu/browse/SISRP-43372
=> SISRP-43372: adds package-lock to git and forces upgrade of errant dependency

src/assets/templates/widgets/enrollment/adjust_enrolled.html
https://jira.berkeley.edu/browse/SISRP-35692
=> SISRP-35692: Fixes bug with duplicate class meeting time display

app/models/my_academics/my_standings.rb, src/assets/templates/widgets/academic_standing.html, src/assets/templates/widgets/status_and_holds.html
https://jira.berkeley.edu/browse/SISRP-42013
=> SISRP-42013 - Academic Status updates (UX Dev)

app/controllers/campus_rosters_controller.rb, app/models/rosters/campus.rb, app/models/rosters/csv.rb, spec/controllers/campus_rosters_controller_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/csv_spec.rb, src/assets/templates/directives/academics_class_info_enrollment.html, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-43016
=> SISRP-43016 - UX Dev: Faculty - Export Roster (Phase 1)

src/assets/templates/widgets/exam_results_card.html
https://jira.berkeley.edu/browse/SISRP-39080
=> SISRP-39080 - Fixing text

app/models/my_academics/graduation.rb, spec/models/my_academics/graduation_spec.rb, src/assets/javascripts/angular/configuration/routeConfiguration.js, src/assets/templates/academics_graduation_checklist.html, src/assets/templates/directives/expected_graduation_terms.html
https://jira.berkeley.edu/browse/SISRP-15908
=> SISRP-15908 - My Academics - Graduation Checklist

app/models/berkeley/degree_progress_undergrad.rb, spec/models/berkeley/degree_progress_undergrad_spec.rb
https://jira.berkeley.edu/browse/SISRP-40939
=> SISRP-40939 - Adds EXMP as a completed status

app/models/oec/department_mappings.rb, app/models/oec/merged_sheet_validation.rb, app/models/oec/sis_import_task.rb, app/models/oec/supervisors.rb, app/models/oec/worksheet.rb, fixtures/oec/courses_for_dept_A_RESEC.json, fixtures/oec/supervisors.csv, spec/models/oec/sis_import_task_spec.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6933
=> CLC-6933 Make OEC DEPT_FORM safe for Explorance

package-lock.json, src/assets/javascripts/angular/directives/datePickerDirective.js, src/assets/stylesheets/calcentral.scss
https://jira.berkeley.edu/browse/SISRP-43448
=> SISRP-43448 - Datepicker visually broken; not accessible

src/assets/templates/directives/finaid_permissions.html
https://jira.berkeley.edu/browse/SISRP-41873
=> SISRP-41873 Replaces parts of FA API with SISEDO - fix to button style

app/models/rosters/campus.rb, spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-41586
=> SISRP-41586 - Updates course section name format

app/controllers/campus_rosters_controller.rb, app/models/rosters/campus.rb, app/models/rosters/csv.rb, spec/controllers/campus_rosters_controller_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/csv_spec.rb
https://jira.berkeley.edu/browse/SISRP-43016
See QA PR #7406
=> SISRP-43016 - Switches filenaming to use feed section list. Adds course name column for crosslisted courses

app/controllers/campus_rosters_controller.rb, app/models/rosters/campus.rb, app/models/rosters/csv.rb, spec/controllers/campus_rosters_controller_spec.rb, spec/models/rosters/campus_spec.rb, spec/models/rosters/csv_spec.rb
https://jira.berkeley.edu/browse/SISRP-43016
See DEV PR #7405
=> [QA] SISRP-43016 - Switches filenaming to use feed section list. Adds course name column for crosslisted courses.

app/models/edo_oracle/user_courses/base.rb, app/models/rosters/campus.rb, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-41586
See DEV PR #7407
=> [QA] Revert SISRP-41586

src/assets/javascripts/angular/directives/expectedGraduationTermsDirective.js, src/assets/templates/directives/expected_graduation_terms.html, src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html, src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-43598
=> SISRP-43598 - View Graduation Checklist link showing on Student Overview

src/assets/javascripts/angular/directives/expectedGraduationTermsDirective.js, src/assets/templates/directives/expected_graduation_terms.html, src/assets/templates/widgets/academic_summary/academic_summary_student_profile.html, src/assets/templates/widgets/academics/college_and_level.html
https://jira.berkeley.edu/browse/SISRP-43598
See DEV PR #7413
=> [QA] SISRP-43598 - View Graduation Checklist link showing on Student Overview

app/models/my_profile/edit_link.rb
https://jira.berkeley.edu/browse/SISRP-43388
Reverts ets-berkeley-edu/calcentral#7404
=> Revert "[QA] SISRP-43388: allows ex-student to see new Edit Profile link"

app/models/canvas/sis_import.rb, app/models/canvas_csv/refresh_all_campus_data.rb, spec/models/canvas_csv/refresh_all_campus_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6957
https://jira.ets.berkeley.edu/jira/browse/CLC-6946
=> CLC-6957 Operational improvements for bCourses import jobs

src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-41477
=> SISRP-41477 - On Profile card Student Overview Page is showing Default photo When there is no photo of a student.

app/models/canvas_csv/refresh_all_campus_data.rb, config/settings.yml, fixtures/csv/Canvas_sis_import_enrollments_all.csv, spec/models/canvas_csv/refresh_all_campus_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6957
Would you like a belt with those suspenders?
=> CLC-6957 Interrupt bCourses import if too many enrollment drops

src/assets/templates/widgets/profile/delegate.html, src/assets/templates/widgets/toolbox/delegate_quick_links.html
https://jira.berkeley.edu/browse/SISRP-43097
=> SISRP-43097 - Delegate Access Webpage Links in CalCentral

app/models/berkeley/term.rb, app/models/edo_oracle/queries.rb, public/json/terms.json, spec/models/berkeley/term_spec.rb, spec/models/berkeley/terms_spec.rb
https://jira.berkeley.edu/browse/SISRP-44157
=> SISRP-44157 - Remove unused final exam week attribute from Berkeley::Term

src/assets/javascripts/angular/controllers/pages/termsAndConditionsController.js, src/assets/javascripts/angular/controllers/widgets/finaid/finaidApprovalsController.js
https://jira.berkeley.edu/browse/SISRP-41873
=> SISRP-41873 FA API Refactor #1 - No Terms & Conditions redirect

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-44270
=> SISRP-44270 - Some GRAD students are missing the "Tuition and Fee Payment / Activate Plan" link in CalCentral

app/controllers/sessions_controller.rb, app/models/user/authentication_validator.rb, config/settings.yml, spec/models/user/authentication_validator_spec.rb
More changes needed due to CAS upgrade returning a different-than-expected SAML response.
=> SISRP-42744 - CalCentral Access Fringe Case Review (CLC dev)

src/assets/javascripts/angular/controllers/widgets/finaid/finaidApprovalsController.js
https://jira.berkeley.edu/browse/SISRP-41873
=> SISRP-41873 Fix promise chain for Terms and Conditions & Title IV

.travis.yml
https://jira.berkeley.edu/browse/SISRP-44335
=> SISRP-44335 - Resolve Travis test failure caused by missing Bundler gem

.travis.yml
https://jira.berkeley.edu/browse/SISRP-44335
=> [QA] SISRP-44335 - Resolve Travis test failure caused by missing Bundler gem

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-44270
See #7432 for DEV PR
=> [QA] SISRP-44270 - Some GRAD students are missing the "Tuition and Fee Payment Plan / Activate Plan" link in CalCentral

src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html, src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-42840
=> SISRP-42840: Update Transfer Credit card UX

src/assets/stylesheets/_useful.scss, src/assets/templates/academics_semester_classes.html, src/assets/templates/academics_semesters.html, src/assets/templates/directives/academics_class_info_enrollment.html, src/assets/templates/uid_error.html, src/assets/templates/widgets/academics/degree_progress_undergrad.html, src/assets/templates/widgets/final_exam_schedule.html, src/assets/templates/widgets/roster.html
https://jira.berkeley.edu/browse/SISRP-39112
=> SISRP-39112: use buttons for ng-click functions

Gemfile, Gemfile.lock
https://jira.berkeley.edu/browse/SISRP-42655
=> SISRP-42655: Update gems to fix security vulnerabilities

src/assets/javascripts/angular/controllers/widgets/profile/title4Controller.js, src/assets/templates/widgets/profile/title4.html
https://jira.berkeley.edu/browse/SISRP-41873
=> SISRP-41873 - changes label for My Finances button depending on $location

app/models/user/authentication_validator.rb, config/settings.yml, spec/models/user/authentication_validator_spec.rb
=> SISRP-42744 - add backwards compatibility with CAS v5

src/assets/stylesheets/_myfinances.scss
https://jira.berkeley.edu/browse/SISRP-39745
=> SISRP-39745: Fix visual bug and prevent label from wrapping

src/assets/templates/uid_error.html
=> SISRP-42744 - Update uid_error template with modern verbiage

app/models/berkeley/term.rb, app/models/edo_oracle/queries.rb, public/json/terms.json, spec/models/berkeley/term_spec.rb, spec/models/berkeley/terms_spec.rb
https://jira.berkeley.edu/browse/SISRP-44157
=> [QA] SISRP-44157 - Remove unused final exam week attribute from Berkeley::Term

app/models/edo_oracle/queries.rb, spec/models/edo_oracle/queries_spec.rb
https://jira.berkeley.edu/browse/SISRP-43941
=> SISRP-43941 - 500 error on 'textbooks' proxy when viewing-as instructor

app/models/edo_oracle/queries.rb, spec/models/edo_oracle/queries_spec.rb
=> [QA] SISRP-43941 - 500 error on 'textbooks' proxy when viewing-as instructor

src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/widgets/toolbox/user_preview.html
https://jira.berkeley.edu/browse/SISRP-41477
See Dev PR: #7422
=> [QA] SISRP-41477 - On Profile card Student Overview Page is showing Default photo When there is no photo of a student

app/models/edo_oracle/user_courses/base.rb, app/models/rosters/campus.rb, spec/models/edo_oracle/user_courses/base_spec.rb, spec/models/rosters/campus_spec.rb
https://jira.berkeley.edu/browse/SISRP-41586
This reverts commit 6213c415abc426326fb7e61af896bf304eb227ff (See #7407)
=> SISRP-41586 - Reintroduce updates to course section name format

app/models/campus_solutions/sir/sir_statuses.rb, spec/models/campus_solutions/sir/sir_statuses_spec.rb
https://jira.berkeley.edu/browse/SISRP-44316
For the purposes of cherry-picking commits to prepare the `qa` branch for release, this commit should follow **after** all commits related to [SISRP-42744](https://jira.berkeley.edu/browse/SISRP-42744) (commits documented in JIRA ticket).
=> SISRP-44316 - SIR Card Does Not Display for LAW students selecting Maybe

src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-43926
=> SISRP-43926 - Law Transcripts Note for students before 1995

src/assets/templates/widgets/academics/academic_records.html
https://jira.berkeley.edu/browse/SISRP-43926
See DEV PR #7465
=> [QA] SISRP-43926 - Law Transcripts Note for students before 1995

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-44440
See DEV PR #7467
=> [QA] SISRP-44440 - Removes unused link details

app/controllers/sessions_controller.rb, app/models/berkeley/user_roles.rb, app/models/user/aggregated_attributes.rb, app/models/user/authentication_validator.rb, config/settings.yml, spec/models/hub_edos/user_attributes_spec.rb, spec/models/user/authentication_validator_spec.rb, src/assets/templates/uid_error.html
This also includes PR for #7431, which was a bug opened as a direct result of the first commit for SISRP-42744.
JIRA for #7431: 
https://jira.berkeley.edu/browse/SISRP-44236
All PRs this cherry-picks from:
#7420 
#7431 
#7438 
#7441 
#7449 
#7452
=> [QA] SISRP-42744 - CalCentral Access Fringe Case Review (CLC dev)

app/models/campus_solutions/sir/sir_statuses.rb, spec/models/campus_solutions/sir/sir_statuses_spec.rb
https://jira.berkeley.edu/browse/SISRP-44316
=> SISRP-44316 - change criteria from seq_3c to checklist_seq

app/models/campus_solutions/sir/sir_statuses.rb, spec/models/campus_solutions/sir/sir_statuses_spec.rb
https://jira.berkeley.edu/browse/SISRP-44316
QA PR of #7473
=> [QA] SISRP-44316 - change criteria from seq_3c to checklist_seq

fixtures/xml/campus_solutions/link_api_multiple.xml, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/stylesheets/_useful.scss, src/assets/templates/widgets/finances_links.html
https://jira.berkeley.edu/browse/SISRP-44463
=> SISRP-44463 - Update CalCentral EFT link to say "Direct Deposit"

app/models/concerns/academic_roles.rb, app/models/degree_progress/my_undergrad_requirements.rb, spec/models/concerns/academic_roles_spec.rb, spec/models/degree_progress/my_undergrad_requirements_spec.rb, spec/models/my_academics/my_academic_roles_spec.rb, src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-43657
=> SISRP-43657 - Update UGRD Degree Progress Card to show APR link for COE students

app/models/my_academics/grading/applicator.rb, spec/models/my_academics/grading/applicator_spec.rb
https://jira.berkeley.edu/browse/SISRP-40280
=> SISRP-40280 - Fixes section grading issue, and absent grading links

src/assets/javascripts/angular/controllers/widgets/financesLinksController.js
https://jira.berkeley.edu/browse/SISRP-44463
=> SISRP-44463 - Update hover text for Direct Deposit Enrollment/Management link

app/models/degree_progress/my_undergrad_requirements.rb, config/settings.yml, spec/models/degree_progress/my_undergrad_requirements_spec.rb
https://jira.berkeley.edu/browse/SISRP-43657
=> SISRP-43657 - Adds feature flag for APR link displayed to UGRD College of Engineering students

fixtures/xml/campus_solutions/link_api_multiple.xml, spec/controllers/my_campus_links_controller_spec.rb, src/assets/javascripts/angular/controllers/widgets/finaid/finaidCommunicationsController.js, src/assets/javascripts/angular/controllers/widgets/financesLinksController.js, src/assets/templates/widgets/finaid_communications_tasks.html, src/assets/templates/widgets/finances_links.html, src/react/components/StudentResources.js, src/react/containers/StudentResourcesContainer.js
https://jira.berkeley.edu/browse/SISRP-44405
=> SISRP-44405 - Link to Campus Logic from CalCentral

app/models/my_academics/grading/applicator.rb
https://jira.berkeley.edu/browse/SISRP-40280
=> SISRP-40280 - Fixes bug with Law grading dates

app/models/data_loch/s3.rb, app/models/data_loch/stocker.rb, app/models/data_loch/zipper.rb, app/models/edo_oracle/bulk.rb, config/settings.yml, lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-6944
=> CLC-6944 Collect demographics data for advisors

src/assets/templates/widgets/finaid_profile.html
https://jira.berkeley.edu/browse/SISRP-41162
Minor change to message displayed to student when no data found (per UX recommendation)
=> SISRP-41162 FA Profile API Refactor - error message change

app/models/campus_solutions/sir/sir_statuses.rb, spec/models/campus_solutions/sir/sir_statuses_spec.rb
https://jira.berkeley.edu/browse/SISRP-44842
QA PR of #7488
=> [QA] SISRP-44842 - UGRD SIR Card Disappearing when items are added to the Finalization Checklist

src/assets/stylesheets/_academics.scss, src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-40280
Somehow I coded the back-end to surface the correct dates, but I forgot to update the front-end view. 🤦‍♂️
=> SISRP-40280 - Updates front-end to display dates

app/models/edo_oracle/queries.rb, app/models/my_academics/semesters.rb, app/models/my_academics/student_links.rb, config/settings.yml, config/settings/test.yml, fixtures/xml/campus_solutions/link_api_multiple.xml, spec/models/edo_oracle/queries_spec.rb, spec/models/my_academics/semesters_spec.rb, spec/models/my_academics/student_links_spec.rb, src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-43706
=> SISRP-43706 - Display waitlist info to students

app/models/student_success/term_gpa.rb, package-lock.json, src/assets/javascripts/angular/controllers/pages/userOverviewController.js, src/assets/templates/widgets/student_success/gpa_trends.html
https://jira.berkeley.edu/browse/SISRP-44520
=> SISRP-44520 - Terms not appearing in Student Success card for Advisor

src/assets/javascripts/angular/controllers/widgets/finaid/finaidProfileController.js
https://jira.berkeley.edu/browse/SISRP-41162
Implements [change](https://github.com/ets-berkeley-edu/calcentral/pull/7498#discussion_r254900640) suggested by @davidlimcheng (post-merge)
=> SISRP-41162 - FA Profile API Refactor - more followup

app/models/edw_oracle/connection.rb, app/models/edw_oracle/queries.rb, config/database.yml, config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-6979
Another day, another database....
=> CLC-6979 Define queries to collect applicant data

.eslintrc.json, app/controllers/advising_student_controller.rb, app/models/edo_oracle/employment_appointment_queries.rb, app/models/my_academics/filtered_for_advisor.rb, app/models/my_employment_appointments.rb, config/routes.rb, package-lock.json, package.json, src/assets/templates/user_overview.html, src/react/components/EmploymentAppointments.js, src/react/components/EmploymentAppointments/AppointmentRow.js, src/react/components/EmploymentAppointments/AppointmentRow.scss, src/react/components/EmploymentAppointments/InstructingAppointments.js, src/react/components/EmploymentAppointments/InstructingAppointments.scss
https://jira.berkeley.edu/browse/SISRP-42206
=> SISRP-42206 - Display Current Term Appointment Data in CalCentral

app/models/my_academics/grading/applicator.rb
https://jira.berkeley.edu/browse/SISRP-40280
=> SISRP-40280 - Fixes issue with Summer grading due date

app/models/my_academics/semesters.rb, spec/models/my_academics/semesters_spec.rb
https://jira.berkeley.edu/browse/SISRP-43287
=> SISRP-43287 - withdrawal with UCBX enrollments not showing classes on semesters card

src/assets/templates/widgets/academics/degree_progress_undergrad.html
https://jira.berkeley.edu/browse/SISRP-41853
=> SISRP-41853 - Disable in student overview and add view-as note

src/react/components/pnp_calculator/RatioCalculation.js
https://jira.berkeley.edu/browse/SISRP-44909
=> SISRP-44909 - Bug Value needs max decimal places CalCentral P/NP Limit Calculator

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-6983
Dear Diary....
=> CLC-6983 More departments sign onto OEC

src/react/components/StudentProfile/CumulativeUnits.js, src/react/components/StudentProfile/StudentProfile.scss
https://jira.berkeley.edu/browse/SISRP-44968
=> SISRP-44968: Cummulative GPA on Academic Summary page is incorrect.

app/models/edo_oracle/transfer_credit.rb, spec/models/edo_oracle/transfer_credit_spec.rb, src/react/components/AcademicSummary/Enrollment.js, src/react/components/AcademicSummary/Semester.js, src/react/components/TransferCredit/LawTransferCredit.js
That's the original JIRA, bug is in the comments WRT "Transfer Units Posted"
=> SISRP-42529: Bugfix, failure to always show transfer credit in semester detail

app/models/edo_oracle/transfer_credit.rb
Another bug related to https://jira.berkeley.edu/browse/SISRP-42529
=> SISRP-42529: Bug fix, show correct semester for posted tranfer credit

src/react/components/AcademicSummary/AcademicSummary.js
=> SISRP-42529: Bugfix, prevent undefined credit report link exception

app/models/notifications/sis_expiry_processor.rb
=> SISRP-44030 - Improve ENF topic logging

src/assets/templates/widgets/academic_summary/academic_summary_transfer_credit.html, src/assets/templates/widgets/transfer_credit.html
https://jira.berkeley.edu/browse/SISRP-42840
See DEV PR #7445
=> [QA] Revert "SISRP-42840: Update Transfer Credit card UX"

src/react/components/AcademicSummary/AcademicSummary.js
=> [QA] SISRP-42529: Bugfix, prevent undefined credit report link exception

src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js, src/react/components/CalGrantAcknowledgement/Status.js
=> SISRP-44030: Fetch latest acknowledgement data with refresh=true

app/controllers/cal_grant_acknowledgements_controller.rb, app/controllers/my_holds_controller.rb, app/models/cal_grant/acknowledgement_expiry.rb, src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js
=> SISRP-44030: Allow expiration at the server with refresh=true

app/controllers/my_class_enrollments_controller.rb, app/models/cal_grant/acknowledgement_expiry.rb, src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js
=> SISRP-44030: Expire enrollment card data when returning

app/models/cal_grant/acknowledgement.rb, src/react/components/CalGrantAcknowledgement/HoldListItem.js, src/react/components/CalGrantAcknowledgement/Status.js
=> SISRP-44030: Remove 'View Completed' link from acknowledgement status

app/controllers/cal_grant_acknowledgements_controller.rb, app/controllers/my_class_enrollments_controller.rb, app/controllers/my_holds_controller.rb, app/models/cal_grant/acknowledgement.rb, app/models/cal_grant/acknowledgement_expiry.rb, src/assets/javascripts/angular/controllers/widgets/academicsStatusHoldsBlocksController.js, src/assets/javascripts/angular/controllers/widgets/enrollment/enrollmentCardController.js, src/react/components/CalGrantAcknowledgement/HoldListItem.js, src/react/components/CalGrantAcknowledgement/Status.js
Includes DEV PRs #7525, #7527, #7528, and #7529.
=> [QA] SISRP-44030: Bugfix work to complete Cal Grant acknowledgement

app/controllers/cal_grant_acknowledgements_controller.rb, app/controllers/my_holds_controller.rb, app/models/cal_grant/acknowledgement_expiry.rb
=> SISRP-44030: Expire financial aid profiles on acknowledgement

app/models/berkeley/departments.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6997
=> CLC-6997 Remove obsolete "Center for Buddhist Studies" department

src/react/components/AcademicSummary/AcademicSummary.js, src/react/components/AcademicSummary/Semester.js, src/react/components/StudentProfile/LawGraduation.js, src/react/components/StudentProfile/Major.js, src/react/components/StudentProfile/Minor.js, src/react/components/TransferCredit/LawTransferCredit.js
Also addresses some duplicate key warnings and prevents the component
from fetching data until it's actually mounted
See DEV PR #7536
=> [QA] SISRP-42529: Changes requested by law

src/react/components/AcademicSummary/AcademicSummary.js, src/react/components/AcademicSummary/Semester.js, src/react/components/StudentProfile/LawGraduation.js, src/react/components/StudentProfile/Major.js, src/react/components/StudentProfile/Minor.js, src/react/components/TransferCredit/LawTransferCredit.js
Also addresses some duplicate key warnings and prevents the component
from fetching data until it's actually mounted
=> SISRP-42529: Changes requested by law

app/controllers/cal_grant_acknowledgements_controller.rb, app/controllers/my_holds_controller.rb, app/models/cal_grant/acknowledgement_expiry.rb
=> [QA] SISRP-44030: Expire financial aid profiles on acknowledgement

src/react/components/TransferCredit/LawTransferCredit.js
=> SISRP-42529: Actually, use "Posted" in summary

src/react/components/TransferCredit/LawTransferCredit.js
=> [QA] SISRP-42529: Actually, use "Posted" in summary

src/react/components/EnrollmentLinks/Swap.js, src/react/components/EnrollmentLinks/Withdraw.js
=> SISRP-44030 - Fixes link references

src/react/components/EnrollmentLinks/Swap.js, src/react/components/EnrollmentLinks/Withdraw.js
=> [QA] SISRP-44030 - Fixes link references

src/react/components/AcademicSummary/AcademicSummary.js
https://jira.berkeley.edu/browse/SISRP-45121
=> SISRP-45121 - Testing behavior of rogue requests

app/models/campus_solutions/student_resources.rb, spec/models/campus_solutions/student_resources_spec.rb
https://jira.berkeley.edu/browse/SISRP-45259
=> SISRP-45259 - Student Resources Card is missing links for Higher Degree Committees Form, Special Enrollment Petition

src/react/components/AcademicSummary/AcademicSummary.js
https://jira.berkeley.edu/browse/SISRP-45121
This reverts commit a8d7d279ddeb4e7dbf50e27920279f13b6671627.
=> Revert "SISRP-45121 - Testing behavior of rogue requests"

src/react/components/base/link/CampusSolutionsHigherDegreeCommitteeFormLink.js, src/react/containers/CampusSolutionsLinkContainer.js
https://jira.berkeley.edu/browse/SISRP-45259
See DEV PR #7550
=> [QA] SISRP-45259 - Adds text and link for higher degree progress form link

src/react/components/StudentProfile/Minor.js, src/react/components/StudentProfile/StudentProfile.js
https://jira.berkeley.edu/browse/SISRP-45296
=> SISRP-45296: Fix blank Academic Summary for students with minors

src/react/components/StudentProfile/Minor.js, src/react/components/StudentProfile/StudentProfile.js
https://jira.berkeley.edu/browse/SISRP-45296
DEV PR: #7553
=> [QA] SISRP-45296: Fix blank Academic Summary for students with minors

app/models/campus_oracle/queries.rb, app/models/canvas_csv/add_new_users.rb, app/models/canvas_lti/course_add_user.rb, app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/connection.rb, app/models/edo_oracle/queries.rb, app/models/edo_oracle/view_checker.rb, app/models/user/basic_attributes.rb, config/settings.yml, spec/models/campus_oracle/queries_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7003
https://jira.berkeley.edu/browse/SISRP-36642
The new SISEDO.CALCENTRAL_PERSON_INFO_VW will only be referred to if the application is configured with `features.legacy_caldap=false`.
=> SISRP-36642 CLC-7003 Add support for SISEDO CalDap view

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-45364
=> SISRP-45364 - Remove waitlist info displayed to Law students

src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-45364
=> SISRP-45364 - Use courseCareerCode instead of dept_code

src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-45364
=> SISRP-45364 - Hide 'No Reserved Seats'

src/assets/javascripts/angular/controllers/pages/academicsController.js, src/assets/templates/academics_semester_classes.html
https://jira.berkeley.edu/browse/SISRP-45364
See DEV PRs #7556, #7557, #7559
=> [QA] SISRP-45364 - Remove waitlist info displayed to Law students

app/controllers/bootstrap_controller.rb, app/controllers/canvas_lti_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7007
=> CLC-7007 Improve home page rendering

app/models/canvas_csv/base.rb, app/models/canvas_csv/provide_course_site.rb, lib/background_job.rb, spec/models/canvas_csv/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-6989
=> CLC-6989 Automatically create bCourses subaccounts for new departments

app/models/calnet_ldap/client.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7018
=> CLC-7018 New LDAP Guest accounts will be CREATED, not MODIFIED

app/models/edo_oracle/bulk.rb, app/models/edo_oracle/queries.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7016
=> CLC-7016 Do not show old SIS course titles

app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7013
The OEC slowdown may make this code unusable in practice, but this should at least be a short-term functional fix.
=>  [QA] CLC-7013 Exclude secondary section enrollments for late withdrawals

app/models/edo_oracle/oec.rb
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/7569
TODO: OEC performance may be unacceptably slow. Depending on what QA says, that will either be taken care of by an amendment now or a follow-up JIRA later.
=> CLC-7013 OEC exclude secondary section enrollments for late withdrawals

app/models/edo_oracle/bcourses.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7033
QA-first copy of the fix already implemented for OEC.
=> [QA] CLC-7033 Fix SQL error on Course Site Creation

app/models/edo_oracle/bcourses.rb
Master-branch version of https://github.com/ets-berkeley-edu/calcentral/pull/7571 (and an earlier QA-first PR)
=>  CLC-7033 Fix SQL error on Course Site Creation

app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/oec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7034
This version appears to fulfill the test cases at CLC-7034, CLC-7033, and CLC-7013. Let's see how many more we can trip over.
=> [QA] CLC-7034 Another attempt to thread the late-withdrawal needle

app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/oec.rb
Master-branch version of https://github.com/ets-berkeley-edu/calcentral/pull/7573
=> CLC-7034 Another attempt to thread the late-withdrawal needle

app/models/edo_oracle/bulk.rb
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/7575
=> CLC-7036 Work around order-dependent Oracle issue in WHERE clause

app/models/data_loch/stocker.rb, app/models/data_loch/zipper.rb, app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/oec.rb
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/7577
=> CLC-7037 CLC-7038 Fix blocker bCourses, OEC, Data Loch issues

app/models/calnet_ldap/user_attributes.rb, app/models/user/basic_attributes.rb, spec/models/user/basic_attributes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7042
=> CLC-7042 Exclude inactive CalNet populations from bulk UID search

app/models/canvas/sis_import.rb, config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7041
Just swiping some low-hanging fruit while I'm in the neighborhood.
=> CLC-7041 Configure Canvas SIS Import wait time

app/models/data_loch/stocker.rb, app/models/data_loch/zipper.rb, app/models/edo_oracle/bulk.rb, lib/tasks/data_loch.rake, script/data-loch-l-and-s.sh
https://jira.ets.berkeley.edu/jira/browse/NS-482
The first domino topples....
=> NS-482 Load list of L&S students into Nessie S3

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-6768
=> CLC-6768 Add E-Grades link to new Gradebook UX

app/models/data_loch/stocker.rb, app/models/data_loch/zipper.rb, spec/models/data_loch/stocker_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7028
=> CLC-7028: Exports notes data as JSON

app/models/data_loch/stocker.rb, spec/models/data_loch/stocker_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7028
=> CLC-7028: Adds datestamp to daily path for SIS notes

app/models/data_loch/stocker.rb, app/models/edw_oracle/queries.rb, lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7052
=> CLC-7052 Send Gender/Ethnicity data to Loch

app/models/data_loch/stocker.rb, app/models/edw_oracle/queries.rb, lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7052
=> CLC-7052 Improve performance of bulk Gender query

app/models/data_loch/stocker.rb
Followup to https://github.com/ets-berkeley-edu/calcentral/pull/7593 after testing
=> CLC-7053 Tweak wording of Data Loch access check

app/models/data_loch/stocker.rb, script/data-loch-notes.sh
A couple of things we missed in review, @lyttam :
- No need to run the same DB queries multiple times.
- Log to a unique file.
=> NOJIRA Tweaks to Data Loch Notes scripts

app/models/data_loch/stocker.rb, app/models/data_loch/zipper.rb, app/models/edo_oracle/bulk.rb, app/models/edw_oracle/queries.rb, lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7063
=> CLC-7063 Use SIS as an alternative provider of Gender/Ethnicity data

app/models/data_loch/zipper.rb
Followup to https://github.com/ets-berkeley-edu/calcentral/pull/7599
=> CLC-7063 "Oops"

app/models/edo_oracle/bulk.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7052
=> CLC-7063 Add visa code to advisor demographics

README.md, app/controllers/bootstrap_controller.rb, app/controllers/ping_controller.rb, spec/controllers/ping_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7065
Another step toward shutdown.
=> CLC-7065 Junction can live without the legacy Oracle DB

app/models/data_loch/zipper.rb, spec/models/data_loch/stocker_spec.rb
=> CLC-7059: Intifies new advisor columns

script/data-loch-advisors.sh, script/data-loch-snapshot.sh
I messed up with #7605 and added the heap size option to the wrong script.
=> CLC-7059: Correction: Increases heap size for advisor data upload

script/data-loch-advisors.sh, script/data-loch-snapshot.sh
=> [JQA] CLC-7059: Correction:  Increases heap size for advisor data upload

config/settings/production.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7071
=> CLC-7071 Keep temporary working files out of the deploy directory

app/models/data_loch/zipper.rb, app/models/edo_oracle/bulk.rb, spec/models/data_loch/stocker_spec.rb
=> [JQA] CLC-7059: Fixes typo in query

app/models/data_loch/zipper.rb, app/models/edo_oracle/bulk.rb, spec/models/data_loch/stocker_spec.rb
=> CLC-7059: Fixes typo in query

app/models/data_loch/stocker.rb, app/models/edo_oracle/bulk.rb, lib/tasks/data_loch.rake, script/data-loch-undergrads.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7081
=> CLC-7081 Send list of all active undergraduates to Data Loch

script/sync-canvas-new-users.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7082
=> CLC-7082 Normalize memory settings for sync-canvas-new-users.sh

app/models/edo_oracle/bulk.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7083
QA-first PR.
=> [QA] CLC-7083 Filter Minor plan rows from Data Loch Undergrads upload

app/models/edo_oracle/bulk.rb
Master version of https://github.com/ets-berkeley-edu/calcentral/pull/7627
No need to wait for Travis-CI; I've already run tests locally.
=> CLC-7083 Filter Minor plan rows from Data Loch Undergrads upload

.travis.yml
Cherrypicked from redconfetti's change at https://github.com/sis-berkeley-edu/calcentral/pull/162
=> NOJIRA Fix Travis-CI conflicts with JRuby

app/models/canvas_csv/add_new_users.rb, fixtures/csv/Canvas_provisioning_report_users_csv.csv, spec/models/canvas_csv/add_new_users_spec.rb, spec/models/canvas_csv/base_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7082
=> CLC-7082 Belatedly optimize sync-canvas-new-users.sh memory use

app/models/hub_edos/user_attributes.rb, app/models/hub_edos/v2_students_api.rb, app/models/user/aggregated_attributes.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7085
=> CLC-7085 Reduce Hub V2 Students API noise for non-students

script/data-loch-notes.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7089
=> CLC-7089: Increases max heap size for notes script

app/models/data_loch/stocker.rb, app/models/data_loch/zipper.rb, app/models/edo_oracle/bulk.rb, lib/tasks/data_loch.rake, spec/models/data_loch/stocker_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7092
=> CLC-7092 Add "Term GPAs for all students" Data Loch job

app/models/berkeley/terms.rb, app/models/edo_oracle/queries.rb, config/settings.yml, config/settings/test.yml, spec/models/berkeley/terms_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7097
=> CLC-7097 Give up on the Hub Terms API for now

app/models/canvas_csv/provide_course_site.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7100
=> CLC-7100 Fix job progress in Official Sections app

app/models/data_loch/stocker.rb, app/models/edo_oracle/bulk.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7101
The change will simplify Nessie code a bit.
=> CLC-7101 Tailor Term Definitions output to Data Loch needs

src/base.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7096
=> CLC-7096 Remove some obsolete boilerplate

app/models/berkeley/departments.rb, db/developer-seed-data.sql, db/migrate/20190909202711_legalst_plus.rb, db/schema.rb, package-lock.json
https://jira.ets.berkeley.edu/jira/browse/CLC-7106
https://jira.ets.berkeley.edu/jira/browse/CLC-7077
https://jira.ets.berkeley.edu/jira/browse/CLC-7104
https://jira.ets.berkeley.edu/jira/browse/CLC-7105
=> CLC-7106 CLC-7077 CLC-7104 CLC-7105 - Mostly OEC

script/configure-all-canvas-apps-from-current-host.sh, script/data-loch-advisors.sh, script/data-loch-notes.sh, script/data-loch-snapshot.sh, script/data-loch-undergrads.sh, script/data-loch-verify.sh, script/export-cached-csv-enrollments-set.sh, script/load-test-dev.sh, script/memcached-stats.sh, script/migrate.sh, script/reconfigure-canvas-test-servers.sh, script/refresh-canvas-enrollments.sh, script/refresh-canvas-users.sh, script/report-lti-usage.sh, script/report-turnitin-usage.sh, script/run-oec-task.sh, script/sync-canvas-guest-users.sh, script/sync-canvas-new-users.sh, script/update-mailing-list-memberships.sh, script/webcast_lti_refresh.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7113
This solves a few puzzles from the past few years...
=> CLC-7113 Log fatal exceptions from Rake shell scripts

app/models/berkeley/departments.rb, db/developer-seed-data.sql, db/migrate/20190909202711_legalst_plus.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7110
=> CLC-7110 Remove American Studies from OEC

app/models/data_loch/manager.rb, app/models/data_loch/stocker.rb, spec/models/data_loch/manager_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7090
https://jira.ets.berkeley.edu/jira/browse/CLC-7124
As requested by SysAdmin.
=> CLC-7090 Add S3 "mv" permission check to verify_endpoints

script/sis/verify_sis_api_endpoints.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7129
(with a hat tip to @yoshers for dealing with this on production)
=> CLC-7129 Fix SIS V2 Student API verification check

app/models/edo_oracle/connection.rb
Probably a temporary measure, but we'll see....
=> CLC-7125 Add more logging for connection pool leakage

app/models/edo_oracle/connection.rb
You haven't heard the last of https://jira.ets.berkeley.edu/jira/browse/CLC-7125
=> CLC-7125 Tweak logging for connection pool leakage

app/models/edo_oracle/connection.rb, config/database.yml, config/settings.yml, lib/background_thread.rb
=> CLC-7125 Two-for-one experimental Oracle connection methods

lib/background_thread.rb
=> CLC-7125 Fix a typo which slipped twixt cup and lip

src/assets/templates/canvas_embedded/site_creation.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7118
=> CLC-7118 Create a Site text update

app/models/edo_oracle/connection.rb, config/settings.yml, lib/background_thread.rb
=> CLC-7125 Release Oracle connections at the end of a background job

app/models/oec/merged_sheet_validation.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7137
=> CLC-7137 [OEC] Reduce severity of possibly bogus room-shares

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-7131
No effect on the shared servers, but useful as a memo.
=> CLC-7131 [OEC] Toggle CHM ENG participation

app/models/data_loch/stocker.rb, app/models/edo_oracle/bulk.rb, lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7150
=> CLC-7150 Add intended majors to Data Loch stocker runs

Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-7153
=> CLC-7153 haml version upgrade

.travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7142
I expect this build to fail, although I have tested the "package" steps on my own branch. I'm interested in output of Travis' new `deploy.s3` feature.  See https://docs.travis-ci.com/user/deployment/codedeploy/
The env variable `APP_TRAVIS_ACCESS_KEY` has been added to account settings.
=> CLC-7142, calcentral.knob deploy with .travis > deploy.s3

app/models/edo_oracle/bcourses.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7025
This does what it says, but as yet has no callers.
=> CLC-7025 Find (possibly) recently added instructor assignments

Gemfile, Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-7158
Possibly my last PR... but WHAT A PR!
=> CLC-7158 Upgrade rubyzip

db/migrate/20191101190708_add_canvas_whitelist.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7135
Follow-up to #7668.
=> [QA] CLC-7135 Make whitelist migration reversible

db/migrate/20191101190708_add_canvas_whitelist.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7135
Master version of #7675, follow-up to #7668.
=> CLC-7135 Make whitelist migration reversible

.travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7161
The [artifacts approach](https://docs.travis-ci.com/user/uploading-artifacts/) is simpler and equally effective. 
Please **do not merge** until I give the go-ahead.
=> CLC-7161, use Travis 'artifacts' scheme to push knob to S3

app/models/berkeley/departments.rb, db/developer-seed-data.sql, db/migrate/20191219114410_oec_add_hum.rb, db/schema.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7187
=> CLC-7187 Add L&S Arts and Humanities HUM courses to OEC

config/settings/junction-deploy.properties, script/update-build.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7146
I will ask Ops to create `~/.calcentral_config/junction-deploy.properties` in `j-qa` and `j-prod` environments.
=> CLC-7146, Junction deploy script has option to pull knob file from AWS S3

script/update-build.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7146
Logic to pull from S3 and check against the version currently running in Junction environment.
=> CLC-7146, query S3 for latest knob file and make a record of its timestamp

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7170
=> CLC-7170 Add Academic Policies link to Canvas custom JS

.travis.yml, script/update-build.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7147
=> CLC-7147, no aws cli dependency; script cleanup

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7170
Follow-up to #7689.
=> CLC-7170 Accessibility tweaks for academic policies link

script/deploy/junction-deploy.sh, script/update-build.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7192
Ops will copy this shell script to designated dir.
=> CLC-7192, junction-deploy.sh will run from app_junction home dir

script/deploy/_download-knob-for-torquebox.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7202
=> CLC-7202, exec scripts get-knob-file-id and download-knob before cd ./deploy

LICENSE
In addition to bumping copyright year, this is a test of new deploy script.
=> NOJIRA, bump copyright in LICENSE file

script/deploy/_download-knob-for-torquebox.sh, script/deploy/deploy-to-all-nodes.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7205
Tidy up.
=> CLC-7205, remove unnecessary deploy_tmp_dir and git clone (s3-based deploy script) 

script/deploy/_is_deploy_necessary.sh, script/deploy/deploy-to-all-nodes.sh, script/deploy/deploy-to-current-node.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7206
Also, I removed the redundant 'missing properties file?' check.
=> CLC-7206, if the artifact (knob) is running on current host then do nothing

script/data-loch-terms.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7168
=> CLC-7168: Adds script to upload term definitions to loch

script/deploy/_is_deploy_necessary.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7205
=> CLC-7205, boilerplate for is_deploy_necessary.sh script

public/canvas/canvas-customization.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7211
=> CLC-7211 Update bCourses footer links

src/assets/templates/canvas_embedded/_shared/sections_table.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7216
=> [QA] CLC-7216 Fix model binding in section list checkboxes

src/assets/templates/canvas_embedded/_shared/sections_table.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7216
Master-branch version of #7706.
=> CLC-7216 Fix model binding in section list checkboxes

src/assets/templates/footer_junction.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7156
Testing new S3-based deploys.
=> CLC-7156, element ids on basic-auth form in footer

app/models/canvas_csv/base.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7238
=> CLC-7238 Get robust about encoding in CSV generation

app/models/edo_oracle/bulk.rb
https://jira.ets.berkeley.edu/jira/browse/BOAC-3314
=> BOAC-3314 Doh semicolon

app/models/edo_oracle/bulk.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7241
=> CLC-7241 Include term ID in academic standing query

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-7240
Update developer data with changes already made in all Junction environments.
=> CLC-7240 Enable HNNES courses in OEC

public/canvas/canvas-customization.js
PR https://jira.ets.berkeley.edu/jira/browse/CLC-7248
=> CLC-7248 New-style Canvas gradebook is now mandatory

app/controllers/application_controller.rb, config/initializers/secure_headers.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7249
This might work.
=> CLC-7249 Update LTI header override to new secure_headers syntax

Gemfile, Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-3685
=> CLC-3685 Dependency updates

script/deploy/_download-knob-for-torquebox.sh, script/deploy/_is_deploy_necessary.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7262
=> CLC-7262, each Junction host needs its own .deployment-summary on NFS

Gemfile, Gemfile.lock, config/initializers/session_store.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7258
=> CLC-7258 Drop rails_same_site_cookie dependency, use custom Rack for samesite cookies

Gemfile, Gemfile.lock, config/initializers/session_store.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7258
QA version of #7725.
=> [QA] CLC-7258 Drop rails_same_site_cookie dependency, use custom Rack for samesite cookies

package-lock.json, package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-7259
=> CLC-7259 Update front-end dependencies

app/controllers/canvas_course_grade_export_controller.rb, app/models/canvas_lti/egrades.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb, spec/models/canvas_lti/egrades_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/stylesheets/_canvas_course_grade_export.scss, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7277
https://jira.ets.berkeley.edu/jira/browse/CLC-7278
https://jira.ets.berkeley.edu/jira/browse/CLC-7279
https://jira.ets.berkeley.edu/jira/browse/CLC-7286
=> CLC-7271 E-grades: update pass-fail handling

src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7296
=> CLC-7296 E-Grades: adjust heading structure

app/controllers/canvas_course_grade_export_controller.rb, app/models/canvas_lti/egrades.rb, spec/models/canvas_lti/egrades_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseGradeExportController.js, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7293
=> CLC-7293 E-Grades: make P/NP grade conversion optional

app/models/canvas_lti/egrades.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7298
=> CLC-7298 E-Grades: don't attempt automatic conversion to C/NC basis

app/models/berkeley/departments.rb, db/developer-seed-data.sql, db/migrate/20200409193200_oec_add_redd.rb, db/schema.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7268
=> CLC-7268 OEC, meet Real Estate Development and Design

script/deploy/_download-war-file.sh, script/deploy/_download-war-for-tomcat.sh, script/deploy/_get-war-file-id.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7299
=> [Tomcat] CLC-7299 Remove stray references to knob files

config/deploy.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7301
=> [Tomcat] CLC-7301 Update Capistrano deploy task

script/deploy/_download-war-for-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7299
=> [Tomcat] CLC-7299 Tweak paths in deploy script

app/models/canvas_csv/refresh_all_campus_data.rb, app/models/canvas_csv/synchronization.rb, db/migrate/20200415190551_add_refresh_timestamps_to_canvas_synchronization.rb, db/schema.rb, spec/models/canvas_csv/refresh_all_campus_data_spec.rb, spec/models/canvas_csv/synchronization_spec.rb, spec/models/canvas_csv/term_enrollments_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7306
https://jira.ets.berkeley.edu/jira/browse/CLC-7310
=> CLC-7306 CLC-7310 Database-stored timestamps for site membership refresh

app/models/edo_oracle/bcourses.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7311
=> CLC-7311 Query for recent enrollment updates

Gemfile, Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-7318
=> [Tomcat] CLC-7318 Explicitly add net/telnet to dependencies

script/deploy/_download-war-for-tomcat.sh, script/deploy/_is_deploy_necessary.sh, script/deploy/deploy-to-current-node.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7288
=> [Tomcat] CLC-7288 More deploy script modifications

script/deploy/_download-war-for-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7318
=> [Tomcat] CLC-7318 Yet more deploy script changes

config/initializers/rails_admin.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7320
=> CLC-7320 Add Canvas sync timestamps to ccadmin

config/initializers/rails_admin.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7320
Follow-up to #7754.
=> CLC-7320 When you give Rails bad syntax, it just smiles, nods and ignores you

script/deploy/_download-war-for-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7318
=> [Tomcat] CLC-7318 String match on status to check for running server

script/deploy/_download-war-for-tomcat.sh
Per @dkawase's suggestion in https://jira.ets.berkeley.edu/jira/browse/CLC-7318.
=> CLC-7318 Check Tomcat status in deploy script without blowing up

app/models/edo_oracle/bcourses.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7326
Also take out UTC timestamp conversion since SISEDO is proudly local.
=> CLC-7326 Prioritize undergrad enrollments in bCourses refresh

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-7334
=> CLC-7334 Add INDONES to OEC

script/deploy/deploy-to-current-node.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7327
=> [Tomcat] CLC-7327 Add environment variable to deploy script

app/models/canvas_csv/maintain_users.rb, app/models/canvas_csv/refresh_campus_data_recent.rb, spec/models/canvas_csv/refresh_campus_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7332
=> CLC-7332 bCourses recent refresh: test coverage

app/models/mailgun/send_message.rb, app/models/mailing_lists/incoming_message.rb, config/settings.yml, config/settings/test.yml, spec/models/mailing_lists/incoming_message_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7344
=> CLC-7344 bCourses mailing lists: retry and failure notifications

script/deploy/_download-war-for-tomcat.sh, script/deploy/_start-tomcat.sh, script/downgrade.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7336
=> CLC-7336 Use systemctl to start/stop Tomcat in deploy scripts

script/deploy/_download-war-for-tomcat.sh, script/deploy/_start-tomcat.sh, script/downgrade.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7336
Reverts #7768.
=> CLC-7336 Revert systemctl for Tomcat start/stop

app/models/canvas_csv/refresh_campus_data_recent.rb
QA-first fix (maybe) for https://jira.ets.berkeley.edu/jira/browse/CLC-7350
=> [QA] CLC-7350 Canvas recent refresh: distinguish course sites linked to same section

app/models/canvas_csv/refresh_campus_data_recent.rb, spec/models/canvas_csv/refresh_campus_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7350 again. Following on #7770.
=> [QA] CLC-7350 Distinguish course sites with same section, round two

app/models/canvas_csv/refresh_campus_data_recent.rb, spec/models/canvas_csv/refresh_campus_data_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7350
Master-branch version of #7770, #7771.
=> CLC-7350 Canvas recent refresh: distinguish course sites linked to same section

Gemfile, Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-7352
=> CLC-7352 Update actionpack gems

db/developer-seed-data.sql
Housekeeping PR for https://jira.ets.berkeley.edu/jira/browse/CLC-7348.
=> CLC-7348 OEC: add a few more SSEAS course codes

script/refresh-canvas-enrollments.sh, script/refresh-canvas-recent.sh, script/refresh-canvas-users.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7354
=> CLC-7354 Don't allow multiple Canvas refreshes to run simultaneously

app/models/data_loch/stocker.rb, app/models/edo_oracle/bulk.rb, lib/tasks/data_loch.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7386
=> CLC-7386 Add basic student (and ex-student) attributes to nightly loch upload

app/models/data_loch/stocker.rb, app/models/edo_oracle/bulk.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7386
The big data got too big for the JVM.
=> CLC-7386 Let's try batching that student attributes query

app/models/data_loch/zipper.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7386
=> CLC-7386 Student ids are not decimals

app/models/webcast/recordings.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7392
The `jqa` PR is #7788
=> CLC-7392, webcast/recordings init fix: 'fake' false in non-test env

app/models/webcast/recordings.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7392
Tomcat-branch version of #7788, #7789.
=> [Tomcat] CLC-7392, webcast/recordings init fix: 'fake' false in non-test env

src/assets/javascripts/angular/controllers/pages/canvasCreateCourseSiteController.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7406
Follow-up to #7791.
=> CLC-7406 Follow-up template fix

app/controllers/canvas_course_provision_controller.rb, app/models/canvas_csv/provide_course_site.rb, app/models/canvas_lti/course_provision.rb, spec/controllers/canvas_course_provision_controller_spec.rb, spec/models/canvas_csv/provide_course_site_spec.rb, spec/models/canvas_lti/course_provision_spec.rb, src/assets/javascripts/angular/controllers/pages/canvasCourseManageOfficialSectionsController.js, src/assets/javascripts/angular/directives/bcSectionsTableDirective.js, src/assets/javascripts/angular/factories/canvasCourseProvisionFactory.js, src/assets/stylesheets/_canvas_base.scss, src/assets/templates/canvas_embedded/_shared/sections_table.html, src/assets/templates/canvas_embedded/course_manage_official_sections.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7410
=> CLC-7410 Enable name updates from Official Sections LTI

src/assets/templates/canvas_embedded/create_course_site.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7413
=> CLC-7413 Update descriptive text in Create a Site tool

app/models/edo_oracle/bulk.rb, spec/models/data_loch/stocker_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7414
=> CLC-7414 Add instruction mode to bulk loch exports

src/assets/templates/canvas_embedded/_shared/sections_table.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7410
=> CLC-7410 Official Sections text tweak

app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/queries.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7421
=> [QA] CLC-7421 Section enrollment queries need our crazy withdrawal-screening logic

app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/queries.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7421
Master-branch version of #7802.
=> CLC-7421 Section enrollment queries need our crazy withdrawal-screening logic

app/models/edo_oracle/bcourses.rb, app/models/edo_oracle/queries.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7421
Tomcat-branch version of #7802.
=> [Tomcat] CLC-7421 Section enrollment queries need our crazy withdrawal-screening logic

app/models/berkeley/term_codes.rb, lib/tasks/data_loch.rake, spec/models/berkeley/term_codes_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7418
=> CLC-7148 Range notation for term-specific data loch jobs

app/models/data_loch/manager.rb, spec/models/data_loch/manager_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7422
=> CLC-7422 Adjust term calendaring in data loch jobs

app/models/calnet_ldap/user_attributes.rb, app/models/canvas_csv/base.rb, app/models/edo_oracle/queries.rb, app/models/user/basic_attributes.rb, spec/models/calnet_ldap/user_attributes_spec.rb, spec/models/canvas_csv/add_new_users_spec.rb, spec/models/canvas_csv/base_spec.rb, spec/models/canvas_csv/maintain_users_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7378
=> CLC-7378 Prefer official bMail address in Canvas integrations

app/models/canvas_lti/egrades.rb, spec/models/canvas_lti/egrades_spec.rb, src/assets/templates/canvas_embedded/course_grade_export.html
https://jira.ets.berkeley.edu/jira/browse/CLC-7450
=> CLC-7450 Respect Canvas gradebook override in E-Grades exports

app/controllers/application_controller.rb, config/settings.yml, config/settings/development.yml, package-lock.json, package.json, public/index-vue-js.html, src/auth.ts, src/main.ts, src/router.ts, src/views/Login.vue, src/views/NotFound.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7465
Highlights:
- In regard to UI framework, see latest comment in [CLC-7464](https://jira.ets.berkeley.edu/jira/browse/CLC-7464)
- In "local" env we `set_access_control_headers` to allow 8080 origin
- The Vue init code calls on `/api/my/status` and `/api/config` to begin session
=> CLC-7465, axios, auth and decision points in router; bootstrap for UI

Gemfile, Gemfile.lock
https://jira.ets.berkeley.edu/jira/browse/CLC-7474
See if this helps with our current dependency woes on junction-dev.
=> CLC-7474 Update bootstrap-sass dependencies, move out of development group

app/controllers/act_as_controller.rb, app/controllers/application_controller.rb, app/controllers/bootstrap_controller.rb, app/controllers/cache_controller.rb, app/controllers/canvas_controller.rb, app/controllers/canvas_course_add_user_controller.rb, app/controllers/canvas_course_grade_export_controller.rb, app/controllers/canvas_lti_controller.rb, app/controllers/canvas_project_provision_controller.rb, app/controllers/canvas_rosters_controller.rb, app/controllers/canvas_site_creation_controller.rb, app/controllers/canvas_user_provision_controller.rb, app/controllers/canvas_webcast_recordings_controller.rb, app/controllers/config_controller.rb, app/controllers/mailing_lists_message_controller.rb, app/controllers/oec_google_auth_controller.rb, app/controllers/sessions_controller.rb, app/controllers/stored_users_controller.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7459
A filter by any other name...
=> CLC-7459 Remove deprecated filter syntax

Gemfile, Gemfile.lock, app/models/canvas_lti/lti.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7488
=> CLC-7488 Update LTI authentication dependencies

config/database.yml, config/settings/production.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7488
=> CLC-7488 Switch EDODB connection to Oracle enhanced adapter

src/api/api-utils.ts, src/api/canvas.ts, src/api/config.ts, src/api/oec.ts, src/api/user.ts, src/router.ts, src/views/Oec.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7467
The start of a Vue-based `/oec` page.
=> CLC-7467, the /oec page will be the full-blown proof-of-concept (Vue)

.travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7462
Follow-up to #7842.
=> CLC-7462 No more asset pipeline in the rake

Gemfile, Gemfile.lock, lib/proxies/tls12.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7494
=> CLC-7494 jruby-openssl, roll forward; net-ssh, roll back

app/controllers/user_controller.rb, config/settings.yml, public/dummy/json/status.json, src/components/Footer.vue, src/components/util/BuildSummary.vue, src/components/util/DevAuth.vue, src/mixins/Utils.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7499
=> CLC-7499, Junction build info in footer

README.md
Devs doing Junction dev on local must have:
```yaml
vue:
localhost_base_url: 'http://localhost:8080'
```
=> NOJIRA, Junction README: dev setup for front-end (Vue) work

src/api/act.ts, src/components/toolbox/ActAs.vue, src/components/toolbox/ActAsSaved.vue, src/components/util/DevAuth.vue, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7501
Shared component for `saved` and `recent` users. More to come.
=> CLC-7501, 'Act As' component and correspond API calls (work in progress)

src/api/act.ts, src/components/Footer.vue, src/components/toolbox/ActAs.vue, src/components/toolbox/ActAsSaved.vue, src/components/toolbox/ToolboxHeader.vue, src/views/StandaloneLti.vue, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7501
=> CLC-7501, UI clean up in 'Act As' and header/footer

config/environments/development.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7546
=> CLC-7546, allow_forgery_protection = false if Settings.vue.localhost_base_url

package-lock.json, package.json, src/App.vue, src/components/Footer.vue, src/components/toolbox/ActAs.vue, src/main.ts, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7501
`?w=1` might help.
=> CLC-7501, when acting-as the footer is fixed with 'Stop acting' button

src/components/Footer.vue, src/components/toolbox/ActAs.vue, src/components/toolbox/ActAsSaved.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7501
=> CLC-7501, add/remove user from list of recent/saved users

public/index.html, src/assets/styles/_containers.scss, src/components/bcourses/UserProvision.vue, src/components/toolbox/ToolboxHeader.vue, src/views/StandaloneLti.vue, vue.config.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7540
=> CLC-7540 More styling and structure alignments

src/api/oec.ts, src/components/oec/Oec.vue, src/components/oec/RunTask.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7507
=> CLC-7507, run OEC task, tail log, and then announce success or fail

src/components/Footer.vue, src/components/oec/RunTask.vue, src/components/toolbox/ActAsSaved.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7507
Tidy up.
=> CLC-7507, UI cleanup for OEC widget

src/api/canvas.ts, src/components/bcourses/UserProvision.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7541
FontAwesome! Spinners!
=> CLC-7541 API wiring for user provision LTI tool

src/assets/styles/_bootstrap_variables.scss, src/assets/styles/junction-global.scss, src/components/Footer.vue, src/components/bcourses/roster/RosterHeader.vue, src/components/oec/Oec.vue, src/router.ts, src/views/Login.vue, src/views/RosterPhotos.vue, src/views/StandaloneLti.vue, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7516
Let's get it started.
=> CLC-7516, /roster view and header component; fix participating-depts in OEC widget

src/api/act.ts, src/api/api-utils.ts, src/api/canvas.ts, src/api/oec.ts, src/components/Footer.vue, src/main.ts, src/router.ts, src/views/Error.vue, src/views/Login.vue, src/views/StandaloneLti.vue, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7548
=> CLC-7548, if error then forward to /error; tweaks to axios interceptor

src/components/bcourses/roster/RosterPhoto.vue, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7515
=> CLC-7515, student photo component with img-not-found fallback

src/views/Roster.vue, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7517
=> CLC-7517, /roster: search and section dropdown work in concert

package-lock.json, package.json, src/api/api-utils.ts, src/api/canvas.ts, src/components/bcourses/roster/RosterPhoto.vue, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7518
=> CLC-7518, download roster CSV

src/api/canvas.ts, src/components/bcourses/SiteMailingLists.vue, src/mixins/Utils.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7545
=> CLC-7545 Site mailing lists admin tool: API wiring

app/models/edo_oracle/subject_areas.rb, spec/models/canvas_lti/sis_adapter_spec.rb, spec/models/edo_oracle/subject_areas_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7552
=> [QA] CLC-7552 Update column name in EDO decompressor

app/models/edo_oracle/subject_areas.rb, spec/models/canvas_lti/sis_adapter_spec.rb, spec/models/edo_oracle/subject_areas_spec.rb, spec/models/edo_oracle/user_courses/base_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7552
Vue-branch version of #7875.
=> [Vue] CLC-7552 Update column name in EDO decompressor

src/components/Footer.vue, src/mixins/Utils.vue, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7519
=> CLC-7519, printable roster with legacy CSS 

app/models/oec/merge_confirmation_sheets_task.rb, config/settings.yml
QA-first PR. If it improves matters in that environment, PRs to other branches will follow.
=> [QA] CLC-7553 Add delay to Google API loop in OEC merge

src/components/bcourses/SiteMailingList.vue, src/components/bcourses/SiteMailingLists.vue, src/router.ts, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7542
https://jira.ets.berkeley.edu/jira/browse/CLC-7543
=> CLC-7542 CLC-7543 Course-level site mailing lists tool

config/settings/test.yml
=> [QA] CLC-7553 No sleeping on the job during Travis runs

src/api/auth.ts, src/components/Footer.vue, src/components/toolbox/ToolboxHeader.vue, src/components/util/DevAuth.vue, src/components/util/Spinner.vue, src/views/Login.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7502
=> CLC-7502, sr-alerts and putFocus for log in/log out

app/models/oec/merge_confirmation_sheets_task.rb, config/settings.yml, config/settings/test.yml
Master-branch version of #7880, #7882.
=> CLC-7553 Add delay to Google API loop in OEC merge

.travis.yml, package-lock.json, package.json
This will add a little weight to the WAR but not much.
=> NOJIRA, a few dev node dependencies are required to build WAR bundle

config/settings.yml, package-lock.json, public/lti.html, script/deploy/_start-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7557
=> CLC-7557, _start-tomcat.sh must deploy 'dist' dir; code must ref the DOC_ROOT

app/models/oec/report_diff_task.rb
Master-branch version of #7888.
=> CLC-7553 Beauty sleep for Oec::ReportDiffTask

app/models/oec/report_diff_task.rb
=> [QA] CLC-7553 Beauty sleep for Oec::ReportDiffTask

src/components/bcourses/CourseGradeExport.vue, src/components/bcourses/shared/ProgressBar.vue, src/router.ts
https://jira.ets.berkeley.edu/jira/browse/CLC-7565
https://jira.ets.berkeley.edu/jira/browse/CLC-7566
=> CLC-7565 CLC-7566 E-Grades: Vue template layout

src/auth.ts, src/router.ts, src/views/EmbeddedLti.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7555
=> CLC-7555 Basic routing for embedded LTI views

src/App.vue, src/api/canvas.ts, src/assets/styles/_canvas_site_creation.scss, src/assets/styles/junction-global.scss, src/views/SiteCreation.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7524
=> CLC-7524, bring over canvas_site_creation.scss and foundation.css

public/lti.html, src/mixins/Iframe.vue, src/views/EmbeddedLti.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7555
=> CLC-7555 Port LTI/iframe code into Vue context

docs/Canvas-README.md, public/canvas/index.js
https://jira.ets.berkeley.edu/jira/browse/CLC-7573
=> CLC-7573, udpate README refs to canvas-customization.[js|css]

public/lti.html, src/components/bcourses/SiteMailingList.vue, src/mixins/CanvasUtils.vue, src/views/EmbeddedLti.vue, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7555
=> CLC-7555 Some more LTI wiring fixes

src/api/canvas.ts, src/components/bcourses/SiteMailingList.vue, src/components/bcourses/SiteMailingLists.vue, src/views/EmbeddedLti.vue, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7555
=> CLC-7555 More front-end fixes for LTI context

src/api/canvas.ts, src/components/bcourses/CourseGradeExport.vue, src/components/bcourses/shared/BackgroundJobError.vue, src/components/bcourses/shared/MaintenanceNotice.vue, src/components/bcourses/shared/ProgressBar.vue, src/router.ts, src/views/CreateCourseSite.vue, src/views/SiteCreation.vue
I put TODOs on the yet-to-be-migrated Angular directives.
=> CLC-7526, CreateCourseSite view and its dependents; placeholder vars and methods

src/main.ts
https://jira.ets.berkeley.edu/jira/browse/CLC-7576
=> CLC-7576 Add CSRF headers to Axios defaults

src/components/bcourses/shared/MaintenanceNotice.vue, src/router.ts, src/views/CreateCourseSite.vue, src/views/CreateProjectSite.vue, src/views/SiteCreation.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7531
=> CLC-7531, create-project-site template converted to Vue; wiring up API calls is next

src/api/canvas.ts, src/mixins/Iframe.vue, src/views/CreateProjectSite.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7531
=> CLC-7531, wired in API call to create project site

src/mixins/Accessibility.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7556
Old-school DOM manipulation here, but seems like it did the job in Angular land.
=> CLC-7556 Accessibility announcer

src/components/Footer.vue, src/components/util/DevAuth.vue, src/views/Login.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7523
Concerned and caring, help the helpless
But always remain ultimately selfish
Get the balance right
=> CLC-7523, fix footer alignment in Toolbox template

script/deploy/_start-tomcat.sh
https://jira.ets.berkeley.edu/jira/browse/CLC-7573
=> CLC-7573, cp compiled index.html into ${TOMCAT_DEPLOY}/ROOT

src/api/api-utils.ts, src/api/canvas.ts, src/components/bcourses/CourseGradeExport.vue, src/components/bcourses/shared/ProgressBar.vue, src/mixins/CanvasUtils.vue, src/mixins/Iframe.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7567
=> CLC-7567 API wiring and component logic for E-Grades

src/components/Footer.vue, src/components/bcourses/CanvasErrors.vue, src/components/bcourses/CourseGradeExport.vue, src/components/bcourses/shared/MaintenanceNotice.vue, src/components/toolbox/ActAs.vue, src/components/util/OutboundLink.vue, src/views/SiteCreation.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7580
=> CLC-7580 Consistent markup for outbound links

src/api/canvas.ts, src/components/bcourses/CanvasErrors.vue, src/views/CreateCourseSite.vue, src/views/CreateProjectSite.vue, src/views/SiteCreation.vue
=> CLC-7526, CreateCourseSite: more API calls, more response parsing

package-lock.json, package.json, src/assets/styles/_canvas_base.scss, src/components/Footer.vue, src/components/bcourses/CourseSectionsTable.vue, src/views/CreateCourseSite.vue
=> CLC-7526, CourseSectionsTable component is Vue equivalent of Angular data-bc-sections-table

src/components/bcourses/CourseSectionsTable.vue, src/components/util/Spinner.vue, src/views/CreateCourseSite.vue
It's a simpler read with `?w`.
=> CLC-7526, CourseSectionsTable has optional functions; swap out data-ng attributes

src/api/canvas.ts, src/components/bcourses/CourseAddUser.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7562
`?w=1` makes changes in page markup clearer.
=> CLC-7562 Find a User to Add: API wiring, controller logic

src/components/bcourses/CourseAddUser.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7562
=> CLC-7562 Find a Person to Add: minor cleanup

src/router.ts
https://jira.ets.berkeley.edu/jira/browse/CLC-7563
=> CLC-7563 Fix routing typo

src/components/bcourses/create/CreateCourseSiteHeader.vue, src/components/oec/Oec.vue, src/components/toolbox/ActAs.vue, src/components/toolbox/ToolboxHeader.vue, src/components/util/Spinner.vue, src/main.ts, src/store/modules/context.ts, src/views/BaseView.vue, src/views/CreateCourseSite.vue, src/views/CreateProjectSite.vue, src/views/Login.vue, src/views/SiteCreation.vue, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7528
You can be explicit about sr-alert and focus:
```
this.$ready('Create bCourses Project Site', 'bc-page-create-project-site-name')
```
Do nothing and focus is put on the `h1` element, if present.
Use `?w=1`
=> CLC-7528, accessibility related cleanup; use $ready to put-focus (optional)

app/models/berkeley/legacy_terms.rb, config/settings.yml, config/settings/production.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7587
=> CLC-7587, Settings.terms.legacy_ccn_mappings_file is used by 'webcasts'

src/components/bcourses/CourseAddUser.vue, src/components/bcourses/CourseGradeExport.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7559
=> CLC-7559, import Context.vue to get alertScreenReader

src/components/bcourses/CourseCaptures.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7563
=> CLC-7563 Course capture LTI: gotta have a loading prop

src/components/bcourses/CourseCaptures.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7563
=> CLC-7563 Course captures LTI: little CSS fix

src/components/bcourses/SiteMailingLists.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7594
`mailing-list-court-site-name` is for Charlie the Tuna.
=> CLC-7594 Proper outbound link for site mailing lists LTI

src/components/bcourses/SiteMailingLists.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7595
=> CLC-7595 Mailing Lists LTI: bring back the little spinner

src/components/Footer.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7593
=> CLC-7593, no 'you are viewing as' when isInIframe

src/components/bcourses/SiteMailingLists.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7595
=> CLC-7595 Whoops, creating isn't updating

src/api/canvas.ts, src/components/bcourses/CanvasErrors.vue, src/components/bcourses/create/CreateCourseSiteHeader.vue, src/views/BaseView.vue, src/views/CreateCourseSite.vue, src/views/Error.vue, src/views/Login.vue, src/views/NotFound.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7529
=> CLC-7529, Create course site by section IDs, with validation

package-lock.json, src/components/bcourses/CourseCaptures.vue, src/components/bcourses/CourseGradeExport.vue, src/components/bcourses/SiteMailingList.vue, src/components/bcourses/SiteMailingLists.vue, src/main.ts, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7596
We love our vue-router error handling. But then again, sometimes components need to deal with a 401 or a 403 themselves. But then again again, not every component knows what to do with a 401 or a 403. Maybe this pattern will help.
=> CLC-7596 Make error routing available to Vue components

src/components/bcourses/create/CreateCourseSiteHeader.vue, src/views/CreateCourseSite.vue
=> CLC-7526, instructors go directly to 'selecting sections' step in create-course-site workflow

src/components/bcourses/CourseSectionsTable.vue, src/components/bcourses/create/ConfirmationStep.vue, src/components/bcourses/create/CreateCourseSiteHeader.vue, src/components/bcourses/create/SelectSectionsStep.vue, src/views/CreateCourseSite.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7528
=> CLC-7528, in select-sections step, select some or all; style fixes

src/components/bcourses/CourseSectionsTable.vue, src/views/CreateCourseSite.vue
=> CLC-7530, kick off progress bar with selected CCNs

src/components/bcourses/CourseSectionsTable.vue, src/components/bcourses/create/MonitoringJob.vue, src/views/CreateCourseSite.vue, src/views/CreateProjectSite.vue
=> CLC-7530, error handling in create-course-site

src/components/bcourses/SiteMailingLists.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7594
=> CLC-7594 Mailing List LTI: another very proper outbound course site link

src/components/toolbox/ToolboxHeader.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7598
=> CLC-7598, no ToolbarHeader if isInIframe

src/components/bcourses/CourseGradeExport.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7600
=> CLC-7600 Better messaging when E-Grades degrades

src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7599
This is one part of the CLC-7599 fix.
=> CLC-7599, you must be directly-authenticated to do the OEC dance

src/api/canvas.ts, src/components/bcourses/create/MonitoringJob.vue, src/components/bcourses/shared/MaintenanceNotice.vue, src/views/CreateCourseSite.vue
=> CLC-7530, fixes around courseCreate API call

src/api/canvas.ts, src/api/oec.ts, src/components/bcourses/CanvasErrors.vue, src/components/bcourses/CourseAddUser.vue, src/components/bcourses/CourseSectionsTable.vue, src/components/bcourses/create/ConfirmationStep.vue, src/components/bcourses/create/CreateCourseSiteHeader.vue, src/components/bcourses/create/MonitoringJob.vue, src/views/CreateCourseSite.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7529
=> CLC-7530, site-creation fixes; enter CCN list; ids on buttons

src/components/bcourses/create/ConfirmationStep.vue, src/components/bcourses/create/MonitoringJob.vue, src/views/CreateCourseSite.vue
=> CLC-7530, redirect to new Canvas course site when job complete

src/components/bcourses/roster/RosterPhotos.vue, src/components/util/OutboundLink.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7605
=> CLC-7605, use OutboundLink for mailto links in Roster Photos

src/api/api-utils.ts, src/api/canvas.ts, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7607
=> CLC-7607, Roster download filename when 'embedded'

package-lock.json
https://jira.ets.berkeley.edu/jira/browse/CLC-7627
=> CLC-7627 Update npm packages

package-lock.json
DO NOT MERGE until @pfarestveit greenlights.
https://jira.ets.berkeley.edu/jira/browse/CLC-7627
QA version of #7962.
=> [QA] CLC-7627 Update npm packages

app/models/oec/courses.rb, app/models/oec/merged_sheet_validation.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7583
=> CLC-7583 OEC: change evaluation type validation error to warning

app/models/oec/courses.rb, app/models/oec/merged_sheet_validation.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7583
QA version of #7967.
=> [QA] CLC-7583 OEC: change evaluation type validation error to warning

src/components/oec/RunTask.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7630
Master-branch (Vue) equivalent to #7970., leaving in place the not-quite-complete OEC front-end implementation (https://jira.ets.berkeley.edu/jira/browse/CLC-7625).
=> CLC-7630 OEC task polling: three times a failure

app/models/canvas/proxy.rb, app/models/canvas/report/base.rb, app/models/canvas/sis_import.rb, app/models/mailgun/proxy.rb, config/initializers/ssl_store.rb, lib/proxies/http_request.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7632
=> CLC-7632 Experimental SSL change using frozen certificate store

db/developer-seed-data.sql
Housekeeping PR for https://jira.ets.berkeley.edu/jira/browse/CLC-7582.
=> CLC-7582 OEC: America decides

app/models/canvas/proxy.rb, app/models/canvas/report/base.rb, app/models/canvas/sis_import.rb, app/models/mailgun/proxy.rb, config/initializers/ssl_store.rb, lib/proxies/http_request.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7632
Master-branch version of #7972.
=> CLC-7632 Use constant certificate store for better SSL performance

src/components/toolbox/ActAs.vue, src/views/BaseView.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7612
https://jira.ets.berkeley.edu/jira/browse/CLC-7598
=> CLC-7598 / CLC-7612, no header bg-color if isInIframe

package-lock.json, package.json, src/api/canvas.ts, src/assets/styles/_canvas_base.scss, src/components/bcourses/CourseManageOfficialSections.vue, src/components/bcourses/CourseSectionsTable.vue, src/main.ts, src/router.ts
https://jira.ets.berkeley.edu/jira/browse/CLC-7568
https://jira.ets.berkeley.edu/jira/browse/CLC-7569
https://jira.ets.berkeley.edu/jira/browse/CLC-7570
Wiring not yet in place end to end, but this takes care of most of the templating.
=> CLC-7568 CLC-7569 CLC-7570 Vue: Official Sections LTI layout

src/api/canvas.ts, src/components/bcourses/CourseManageOfficialSections.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7571
=> CLC-7571 Vue: finish Official Sections LTI wiring

src/components/bcourses/create/SelectSectionsStep.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7613
=> CLC-7613 A submit button without a form is no submit button at all

src/components/bcourses/create/CreateCourseSiteHeader.vue, src/components/bcourses/roster/RosterList.vue, src/components/bcourses/roster/RosterPhoto.vue, src/components/bcourses/roster/RosterPhotos.vue, src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7520
https://jira.ets.berkeley.edu/jira/browse/CLC-7521
=> CLC-7520/CLC-7521, roster photos accessibility and ids for QA

src/views/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7619
=> CLC-7619, fix search by SID in roster

src/assets/styles/_print.scss, src/components/bcourses/roster/RosterList.vue, src/components/bcourses/roster/RosterPhoto.vue, src/components/bcourses/roster/RosterPhotos.vue, src/views/Roster.vue, src/views/StandaloneLti.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7604
=> CLC-7604, printable roster with proper stylings

src/components/bcourses/CourseAddUser.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7617
=> CLC-7617 Find a User: element IDs in results table

src/components/oec/Oec.vue, src/components/oec/RunTask.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7623
=> CLC-7623, OEC task runner: multi-select when MergeConfirmationSheets

src/App.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7616
=> CLC-7616 No skip-to-content link when in iframe

src/components/bcourses/CourseAddUser.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7618
=> CLC-7618 Client-side validation for user search

src/components/oec/Oec.vue, src/components/oec/RunTask.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7625
=> CLC-7625, OEC task runner: report success/failure

src/components/bcourses/CourseSectionsTable.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7622
=> CLC-7622 Outbound link for site creation

app/controllers/user_controller.rb, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7624
=> CLC-7624, OEC user has access to OEC feature in toolbox

src/components/bcourses/SiteMailingLists.vue, src/mixins/Utils.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7621
=> CLC-7621 Fix mailing list membership display

app/controllers/application_controller.rb, app/controllers/user_controller.rb, src/api/act.ts, src/components/toolbox/ActAs.vue, src/views/Toolbox.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7620
And, after re-auth, redirect to `vue.localhost_base_url` in local-dev env.
=> CLC-7620, front-end canViewAs prop defined by backend's policy

src/components/util/DevAuth.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7620
=> CLC-7620, update 'X-CSRF-Token' after successful dev-auth

src/views/SiteCreation.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7602
=> CLC-7602 Proper embedded paths for site creation

src/router.ts
https://jira.ets.berkeley.edu/jira/browse/CLC-7602
=> CLC-7602 Embedded paths for site creation

src/components/oec/Oec.vue, src/components/oec/RunTask.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7506
=> CLC-7506 Element ids for OEC

src/components/bcourses/CourseManageOfficialSections.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7647
=> CLC-7647 Fix multiple spinners during Official Sections update

src/auth.ts, src/components/util/DevAuth.vue, src/main.ts
https://jira.ets.berkeley.edu/jira/browse/CLC-7620
It's the `/api/config` response that has tokens.
=> CLC-7620, refresh CSRF-Tokens in axios headers after login

app/models/berkeley/departments.rb, db/developer-seed-data.sql, db/migrate/20201130212057_oec_add_data.rb, db/schema.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7645
=> CLC-7645 DATA science for OEC

src/components/bcourses/CreateCourseSite.vue, src/components/bcourses/create/MonitoringJob.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7650
https://jira.ets.berkeley.edu/jira/browse/CLC-7651
=> CLC-7650 CLC-7651 Fixes to site creation workflow and styling

app/models/berkeley/grade_options.rb, app/models/canvas_lti/egrades.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7652
=> [QA] CLC-7652 Accommodate new CPN grading basis

app/models/berkeley/grade_options.rb, app/models/canvas_lti/egrades.rb, spec/controllers/canvas_course_grade_export_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7652
Master-branch version of #8007.
=> CLC-7652 Accommodate new CPN grading basis

src/components/bcourses/Roster.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7657
=> CLC-7657 Message when no students in roster

src/components/bcourses/roster/RosterPhoto.vue, src/components/bcourses/roster/RosterPhotos.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7656
=> CLC-7656 Show placeholder image whenever roster photo not provided

src/components/bcourses/roster/RosterPhoto.vue, src/components/bcourses/roster/RosterPhotos.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7604
=> CLC-7604 Tweak roster photo grid display

src/components/bcourses/roster/RosterPhoto.vue, src/components/bcourses/roster/RosterPhotos.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7604
=> CLC-7604 One more go-round on the roster grid

src/components/oec/RunTask.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7664
=> CLC-7664 Line breaks for OEC validation logs

src/assets/styles/_canvas_base.scss, src/components/bcourses/CourseAddUser.vue, src/components/bcourses/CourseManageOfficialSections.vue, src/components/bcourses/CourseSectionsTable.vue, src/components/bcourses/CreateCourseSite.vue, src/components/bcourses/CreateProjectSite.vue, src/components/bcourses/SiteCreation.vue, src/components/bcourses/create/ConfirmationStep.vue, src/components/bcourses/create/MonitoringJob.vue, src/components/bcourses/create/SelectSectionsStep.vue, src/components/bcourses/shared/MaintenanceNotice.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7665
https://jira.ets.berkeley.edu/jira/browse/CLC-7666
https://jira.ets.berkeley.edu/jira/browse/CLC-7667
https://jira.ets.berkeley.edu/jira/browse/CLC-7668
https://jira.ets.berkeley.edu/jira/browse/CLC-7669
https://jira.ets.berkeley.edu/jira/browse/CLC-7670
https://jira.ets.berkeley.edu/jira/browse/CLC-7672
=> Site creation: Accessibility improvements

src/components/bcourses/CourseSectionsTable.vue, src/components/bcourses/CreateCourseSite.vue, src/components/bcourses/create/ConfirmationStep.vue, src/components/bcourses/create/SelectSectionsStep.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7665
https://jira.ets.berkeley.edu/jira/browse/CLC-7666
https://jira.ets.berkeley.edu/jira/browse/CLC-7670
https://jira.ets.berkeley.edu/jira/browse/CLC-7672
=> CLC-7665 CLC-7666 CLC-7670 CLC-7672 Accessibility markup take two

src/components/bcourses/CourseAddUser.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7674
https://jira.ets.berkeley.edu/jira/browse/CLC-7675
https://jira.ets.berkeley.edu/jira/browse/CLC-7676
https://jira.ets.berkeley.edu/jira/browse/CLC-7677
https://jira.ets.berkeley.edu/jira/browse/CLC-7678
=> Find a User to Add: accessibility fixes

src/components/bcourses/roster/RosterPhotos.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7679
=> CLC-7679 Roster photos: fix email link structure

src/components/bcourses/CourseGradeExport.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7681
=> CLC-7681 E-Grades: buttons are buttons, links are links

src/components/bcourses/CourseGradeExport.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7680
https://jira.ets.berkeley.edu/jira/browse/CLC-7683
=> CLC-7680 CLC-7683 E-Grades: focus fixes

src/components/bcourses/CourseGradeExport.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7681
=> CLC-7681 E-grades links need absolute URLs

src/components/bcourses/CourseGradeExport.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7684
=> CLC-7684 E-Grades: screenreader friendly grade voicing

src/components/bcourses/SiteMailingList.vue, src/components/bcourses/SiteMailingLists.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7685
https://jira.ets.berkeley.edu/jira/browse/CLC-7686
https://jira.ets.berkeley.edu/jira/browse/CLC-7687
https://jira.ets.berkeley.edu/jira/browse/CLC-7688
=> Site mailing lists: accessibility fixes

src/components/bcourses/CourseGradeExport.vue, src/components/bcourses/CourseManageOfficialSections.vue, src/components/bcourses/CourseSectionsTable.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7689
https://jira.ets.berkeley.edu/jira/browse/CLC-7690
https://jira.ets.berkeley.edu/jira/browse/CLC-7691
https://jira.ets.berkeley.edu/jira/browse/CLC-7692
https://jira.ets.berkeley.edu/jira/browse/CLC-7693
=> Official Sections: accessibility fixes

src/components/bcourses/CreateCourseSite.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7673
=> CLC-7673 Voice site creation progress bar only when value changes

app/models/google_apps/drive_manager.rb, config/settings.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7660
=> CLC-7660 Let the Google API client retry on errors

app/models/oec/validator.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7478
=> CLC-7478 OEC: case insensitive validation on certain fields

app/models/oec/create_confirmation_sheets_task.rb, app/models/oec/task.rb, spec/models/oec/create_confirmation_sheets_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7490
=> CLC-7490 Run preparatory SIS import before creating confirmation sheets

app/models/oec/api_task_wrapper.rb, app/models/oec/task.rb, spec/models/oec/sis_import_task_spec.rb, src/components/oec/Oec.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7486
https://jira.ets.berkeley.edu/jira/browse/CLC-7491
=> CLC-7486 CLC-7491 OEC: use multiselect department input for all tasks

app/models/oec/api_task_wrapper.rb, app/models/oec/merge_confirmation_sheets_task.rb, app/models/oec/merged_sheet_validation.rb, spec/models/oec/merge_confirmation_sheets_task_spec.rb, spec/models/oec/publish_task_spec.rb, spec/support/oec_shared_examples.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7484
=> CLC-7484 OEC: stop merging supervisors from dept confirmation sheets

app/models/oec/merged_sheet_validation.rb, spec/models/oec/validation_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7597
=> CLC-7597 OEC: fix validation task error on blank dates

app/models/oec/merge_confirmation_sheets_task.rb, spec/models/oec/merge_confirmation_sheets_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7475
=> CLC-7475 OEC: Suffixes to disambiguate co-taught courses with distinct end dates

app/models/oec/merge_confirmation_sheets_task.rb, spec/models/oec/merge_confirmation_sheets_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7476
=> CLC-7476 OEC: infer missing values when merging confirmation sheets

db/developer-seed-data.sql
https://jira.ets.berkeley.edu/jira/browse/CLC-7671
=> CLC-7671 Get DEMOG on the OEC train

app/models/oec/task.rb, app/models/oec/term_setup_task.rb, spec/models/oec/term_setup_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7482
=> CLC-7482 Create tracking spreadsheet during term setup

app/models/oec/create_confirmation_sheets_task.rb, app/models/oec/task.rb, spec/models/oec/create_confirmation_sheets_task_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7695
=> CLC-7695 OEC: Link confirmation sheet URLs from tracking sheet

app/controllers/oec_tasks_controller.rb, app/models/oec/api_task_wrapper.rb, app/models/oec/tasks/base.rb, app/models/oec/tasks/create_confirmation_sheets.rb, app/models/oec/tasks/merge_confirmation_sheets.rb, app/models/oec/tasks/term_setup.rb, app/models/oec/term_tracking_sheet.rb, config/routes.rb, spec/controllers/oec_tasks_controller_spec.rb, spec/models/oec/course_code_spec.rb, spec/models/oec/tasks/create_confirmation_sheets_spec.rb, spec/models/oec/tasks/merge_confirmation_sheets_spec.rb, spec/models/oec/term_tracking_sheet_spec.rb, spec/support/oec_shared_examples.rb, src/api/oec.ts, src/components/oec/Oec.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7483
=> CLC-7483 OEC: integrate confirmation sheets merge with tracking sheet

app/models/oec/tasks/base.rb, app/models/oec/tasks/create_confirmation_sheets.rb, app/models/oec/tasks/merge_confirmation_sheets.rb, app/models/oec/worksheets/base.rb, app/models/oec/worksheets/course_confirmation.rb, spec/models/oec/tasks/create_confirmation_sheets_spec.rb, spec/models/oec/tasks/merge_confirmation_sheets_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7694
=> CLC-7694 OEC: status in tracking sheet derives from individual confirmation sheet

app/models/oec/tasks/merged_sheet_validation.rb, spec/models/oec/tasks/validation_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7143
=> CLC-7143 OEC: DEPT_FORM validation allows arbitrary underscore suffixes

package-lock.json, package.json
https://jira.ets.berkeley.edu/jira/browse/CLC-7699
=> CLC-7699 Bump axios version

app/models/mailing_lists/incoming_message.rb, app/models/mailing_lists/mailgun_list.rb, app/models/mailing_lists/outgoing_message.rb, app/models/mailing_lists/site_mailing_list.rb, db/migrate/20210105224707_add_timestamps_to_canvas_site_mailing_list_members.rb, db/schema.rb, spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7706
=> CLC-7706 Soft delete, welcome timestamp for mailing list memberships

app/models/mailing_lists/mailgun_list.rb, app/models/mailing_lists/site_mailing_list.rb, spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7706
=> CLC-7706 Syntax fixes, more test coverage

app/models/oec/tasks/merge_confirmation_sheets.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7709
=> CLC-7709 OEC: don't repeatedly query Google for default term dates

app/models/oec/tasks/merge_confirmation_sheets.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7708
=> CLC-7708 OEC: Don't mark confirmation sheets merged until merge completed

app/models/oec/tasks/merge_confirmation_sheets.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7708
=> CLC-7708 OEC: don't set merged status until sheet exported

app/controllers/canvas_mailing_list_controller.rb, app/models/mailing_lists/site_mailing_list.rb, config/routes.rb, db/migrate/20210107222456_add_welcome_email_to_canvas_site_mailing_lists.rb, db/schema.rb, spec/controllers/canvas_mailing_list_controller_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7701
=> CLC-7701 bCourses welcome email: db columns and backend code

src/api/canvas.ts, src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7703
=> CLC-7703 Welcome email: front-end API wiring, activation toggle

app/models/mailing_lists/outgoing_message.rb, app/models/mailing_lists/site_mailing_list.rb, lib/html_sanitizer.rb, lib/tasks/mailing_lists.rake, spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7705
=> CLC-7705 Welcome emails: send as part of list membership update

app/controllers/canvas_mailing_list_controller.rb, app/models/mailing_lists/site_mailing_list.rb, config/routes.rb, spec/controllers/canvas_mailing_list_controller_spec.rb, spec/models/mailing_lists/mailgun_list_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7704
=> CLC-7704 Welcome emails: message log CSV download, back end

app/controllers/canvas_mailing_list_controller.rb, src/api/canvas.ts, src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7704
=> CLC-7704 Welcome email: download message log, front end

app/models/mailing_lists/site_mailing_list.rb, package-lock.json, package.json, spec/models/mailing_lists/mailgun_list_spec.rb, src/api/canvas.ts, src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7702
=> CLC-7702 Welcome email: rich text editor

app/controllers/canvas_mailing_list_controller.rb, spec/controllers/canvas_mailing_list_controller_spec.rb, src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7719
=> CLC-7719 bCourses mailing lists: user text, style/accessibility fixes

.travis.yml
https://jira.ets.berkeley.edu/jira/browse/CLC-7722
See Jira description for my concern with tossing out concurrency altogether.
=> CLC-7722, Junction Travis build will run two concurrent jobs instead of three

src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7724
=> CLC-7724 bCourses welcome email: breathing room for message input

src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7725
=> CLC-7725 Fix notifications when editing newly created email

src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7723
QA version of #8064.
=> [QA] CLC-7723 bCourses welcome email: no cancel button when no message created

src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7723
=> CLC-7723 bCourses welcome email: no cancel button when no message created

app/controllers/canvas_mailing_list_controller.rb, spec/controllers/canvas_mailing_list_controller_spec.rb, src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7730
=> CLC-7730 bCourses welcome emails: do not deactivate on edit

app/controllers/canvas_mailing_list_controller.rb, spec/controllers/canvas_mailing_list_controller_spec.rb, src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7730
QA version of #8066.
=> [QA] CLC-7730 bCourses welcome emails: do not deactivate on edit

src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7731
=> CLC-7731 bCourses welcome email: revert front-end properties on cancel

src/components/bcourses/SiteMailingList.vue
https://jira.ets.berkeley.edu/jira/browse/CLC-7731
QA version of #8068.
=> [QA] CLC-7731 bCourses welcome email: revert front-end properties on cancel

lib/tasks/mailing_lists.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7733
=> [QA] CLC-7733 Fix typos in mailing list rake task

lib/tasks/mailing_lists.rake
https://jira.ets.berkeley.edu/jira/browse/CLC-7733
Master-branch version of #8071.
=> CLC-7733 Fix typos in mailing list rake task

app/models/canvas/external_tools.rb, app/models/canvas_csv/provide_course_site.rb, fixtures/json/canvas_tab_hidden_course_1234567.json, spec/models/canvas_csv/provide_course_site_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7436
=> CLC-7436 Hide Conferences tool during course site creation

app/models/canvas_lti/project_provision.rb, spec/models/canvas_lti/project_provision_spec.rb
https://jira.ets.berkeley.edu/jira/browse/CLC-7436
=> CLC-7436 Hide Conferences tab during project site creation
